### ISSUE TITLE
launch screen animation in nativescript ios

### ISSUE THREAD

**Issue by cpmobilecoder** [NativeScript/nativescript-angular#1004]
Hi i want to use the animation in nativescript iOS launch screen , any suggestion is appreciated.

**Comment by NickIliev** [comment]
@cpmobilecoder please use the community channels (like [https://discourse.nativescript.org/](https://discourse.nativescript.org/)) for how-to related questions.

As a note using video on the launch screen (a.k.a. splash screen) is strongly discouraged by both Android and iOS guidelines.
