### ISSUE TITLE
How to Hide/Show Layout with Scroll Down/Up

### ISSUE THREAD

**Issue by talatccan** [NativeScript/nativescript-angular#1008]
Hi, i am trying to hide a layout when scrolling down however i want to show it up back when i scrolling up.

How can i do this?

My template is like that

```
<GridLayout>
  <GridLayout> /* this layout i want to hide
  </GridLayout>   and show with scroll up/down */

  <ScrollView>
  </ScrollView>
<GridLayout>
```

**Comment by NickIliev** [comment]
@talatccan please post how-to related questions in one of the community channels like [discourse.nativescript.org ](https://discourse.nativescript.org/)

Regarding your question - you can check this example showing one possible approach to implement a parallax-like effect or use [nativescript-parallax ](https://github.com/TheOriginalJosh/nativescript-parallax)plugin
