### ISSUE TITLE
DatePicker inside TabView in Modalpage cannot render while open modal page in other component

### ISSUE THREAD

**Issue by kumaran-dena** [NativeScript/nativescript-angular#1012]
I have tried to design datetime picker modal-page. I have planned to keep pickers inside Tabview in modal.

Once modal page created, After open the modal Its not showing the Datepicker in date tab.
FYI,
![dp](https://user-images.githubusercontent.com/30895291/30932614-a596d1fc-a3e5-11e7-9512-43574a50b207.PNG)

But the timepicker was rendered in time tab.
![tp](https://user-images.githubusercontent.com/30895291/30932624-b0a2d49c-a3e5-11e7-99f2-377208c88cde.PNG)

Regarding this i have created topic on NS forum [thread](https://discourse.nativescript.org/t/datepicker-inside-tabview-in-modalpage-cannot-render-while-open-modal-page-in-other-component/2699).

Please suggest!

Thanks
.Kumaran

**Comment by tsonevn** [comment]
Hi @kumaran-dena,
I tested the described scenario while using ModalPage TabView and DatePicker and the component seems to be shown on the screen as expected. I am attaching the sample code, which is used for testing and screenshot from the simulator.
HTML 
```
<StackLayout class="modal-view-style" sdkExampleTitle sdkToggleNavButton>
            <TabView selectedIndex="0" height="500" backgroundColor="green">
                    <StackLayout *tabItem="{title: 'DatePicker'}">
                        <DatePicker (loaded)="dploaded($event)" id="datePicker"></DatePicker>
                        <Button class="btn btn-primary btn-active" text="Submit" (tap)="submit()"></Button>
                    </StackLayout>
                    <StackLayout *tabItem="{title: 'Second'}">
                        <Label text="Second tab item"></Label>
                    </StackLayout>
                    <StackLayout *tabItem="{title: 'Third'}">
                        <Label text="Third tab item"></Label>
                    </StackLayout>
                </TabView>
    

</StackLayout>
```
TypeScript
```
import { Component, OnInit, NgModule } from "@angular/core";
import { ModalDialogParams } from "nativescript-angular/modal-dialog";
import { DatePicker } from "ui/date-picker";
import { Page } from "ui/page";

// >> passing-parameters
@Component({
    moduleId: module.id,
    templateUrl: "./modal-view.html",
})
export class ModalViewComponent implements OnInit {
    public currentdate: Date;

    constructor(private params: ModalDialogParams, private page: Page) {
        this.currentdate = new Date(params.context);

        this.page.on("unloaded", () => {
            // using the unloaded event to close the modal when there is user interaction
            // e.g. user taps outside the modal page
            this.params.closeCallback();
        });
    }

    ngOnInit() {  
    }

    dploaded(args){
        let datePicker: DatePicker = <DatePicker>this.page.getViewById<DatePicker>("datePicker");
        datePicker.year = this.currentdate.getFullYear();
        datePicker.month = this.currentdate.getMonth() + 1;
        datePicker.day = this.currentdate.getDate();
        datePicker.minDate = new Date(1975, 0, 29);
        datePicker.maxDate = new Date(2045, 4, 12);
    }

    public submit() {
        let datePicker: DatePicker = <DatePicker>this.page.getViewById<DatePicker>("datePicker");
        this.params.closeCallback(datePicker.date);
    }
}
// << passing-parameters
```

The code was tested with [nativescript sdk examples ng](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/modal-page/sample-modal-page-module-example
![angleropr6 170623 019ntsonev09282017132503](https://user-images.githubusercontent.com/17448734/30962236-a6267c0a-a451-11e7-9212-bb39c75d1474.png)
), while making the above-mentioned changes for the modal page.

**Comment by kumaran-dena** [comment]
Hey @tsonevn, 

I have tried the attached sample code. But still i don't get what i am expect.

Please see my code,
Modal page -

HTML
`<StackLayout class="datetimepic-commonall-stack">
<ScrollView>
<StackLayout class="modal-view-style" sdkExampleTitle sdkToggleNavButton>
    <TabView selectedIndex="0" height="500" backgroundColor="green">
            <StackLayout (loaded)="dploaded($event)" *tabItem="{title: 'DatePicker'}">
                <DatePicker id="datePicker"></DatePicker>
            </StackLayout>
            <StackLayout *tabItem="{title: 'TimePicker'}">
                <TimePicker id="timePicker"></TimePicker>
            </StackLayout>
    </TabView>
<StackLayout>
<Button class="btn btn-primary btn-active" text="Submit" (tap)="submit()"></Button>
<Button class="btn btn-primary btn-active" text="Clear" (tap)="clear()"></Button>
</StackLayout>
</StackLayout>
</ScrollView>
</StackLayout>`

TYPESCRIPT
`import { Component, OnInit, NgModule } from "@angular/core";
import { ModalDialogParams } from "nativescript-angular/modal-dialog";
import { DatePicker } from "ui/date-picker";
import { Page } from "ui/page";
import { TimePicker } from "ui/time-picker";

@Component({
    moduleId: module.id,
    templateUrl: "./datetimepic.html",
})
export class Datetimepicmodal implements OnInit {
public currentdate: Date;
public currenttime: Date;

    constructor(private params: ModalDialogParams, private page: Page) {
        this.currentdate = new Date(params.context);
        this.currenttime = new Date();
        
        this.page.on("unloaded", () => {
                    this.params.closeCallback();
        });
    }

    ngOnInit() {
     let timePicker: TimePicker = <TimePicker>this.page.getViewById<TimePicker>("timePicker");
timePicker.hour = this.currenttime.getHours();
timePicker.minute = this.currenttime.getMinutes();
    }

    dploaded(args){
        let datePicker: DatePicker = <DatePicker>this.page.getViewById<DatePicker>("datePicker");
        datePicker.year = this.currentdate.getFullYear();
        datePicker.month = this.currentdate.getMonth() + 1;
        datePicker.day = this.currentdate.getDate();
        datePicker.minDate = new Date(1975, 0, 29);
        datePicker.maxDate = new Date(2045, 4, 12);
    }
    public submit() {
        let datePicker: DatePicker = <DatePicker>this.page.getViewById<DatePicker>("datePicker");
        let timePicker: TimePicker = <TimePicker>this.page.getViewById<TimePicker>("timePicker");

var date = datePicker.date.toString();
var arr= new Array();
arr= date .split(" ");
var month = arr[1];
var fullDate = arr[2] + "-" + month + "-" + arr[3];

  var format = this.addZero(timePicker.time.getHours());
  var formatt =  this.addZero(timePicker.time.getMinutes());
  var Datetime = arr[2] + "-" + month + "-" + arr[3] + " " + format + ":" + formatt;
console.log("selected datetime " + Datetime );
 this.params.closeCallback(Datetime); 
    }

    public clear(){
        this.params.closeCallback(""); 
    }

    addZero(i) {
    if (i < 10) {
        i = "0" + i;
    }
    return i;
}

}   `

Actual component -
HTML
`----body--------
  <StackLayout id="tabitem" *tabItem="audcerttitleAndIcon">
<StackLayout class="stackrit" col="0" row="1">
<Label class="m-15 h2 text-left" text="Opening Meeting" textWrap="true"></Label>
</StackLayout>
<StackLayout class="testkumss" col="1" row="1">
<TextField class="input input-border" [(ngModel)]="adrcert.omeetng" (tap)="createdtpModelView('opening')" editable="false"></TextField>
</StackLayout>
</StackLayout>
-------------`
TYPESCRIPT
`     createdtpModelView(args) {
        let currentDate = new Date();
        let options: ModalDialogOptions = {
            context: currentDate.toDateString(),
            fullscreen: false,
            viewContainerRef: this.viewContainerRef
        };
     
        this.modalService.showModal(Datetimepicmodal, options)
            .then((dateresult: Date) => {           
                if (args === "opening") 
                {
                this.adrcert.omeetng = dateresult;
                }
                 else if (args === "closing")
                {
     //set the datetime
                }
    });
 }`

Hope you will get what i am trying to do!

If i tried with above codes means, 
When the component initialized for the first time its showing the datepicker widget inside tab properly. If i tried again & again means datepicker not rendering only its showing blank tab.
If i do double tap on textfield means that time its showing the datepicker inside tabview.

Why its behaving like this? Please suggest!

**Comment by tsonevn** [comment]
Hi @kumaran-dena,
Thank you for the provided description.
I will test it on my side and will write you back as soon as I have some results on the investigation.

**Comment by tsonevn** [comment]
Hi @kumaran-dena,
 After reviewing your code I was able to recreate an issue with showing the DatePicker component. Also, I found that this issue is caused due too early loading the initial value for the TimePicker component in ngOnInit.  To resolve this you should load this date on the loadedEvent of the TimePicker. For example:
modal-view.html
```
<StackLayout class="datetimepic-commonall-stack">
    <ScrollView>
        <StackLayout class="modal-view-style" sdkExampleTitle sdkToggleNavButton>
            <TabView selectedIndex="0" height="500" backgroundColor="green">
                <StackLayout (loaded)="dploaded($event)" *tabItem="{title: 'DatePicker'}">
                    <DatePicker id="datePicker"></DatePicker>
                </StackLayout>
                <StackLayout *tabItem="{title: 'TimePicker'}">
                    <TimePicker (loaded)="rpLoaded($event)" id="timePicker"></TimePicker>
                </StackLayout>
            </TabView>
            <StackLayout>
                <Button class="btn btn-primary btn-active" text="Submit" (tap)="submit()"></Button>
                <Button class="btn btn-primary btn-active" text="Clear" (tap)="clear()"></Button>
            </StackLayout>
        </StackLayout>
    </ScrollView>
</StackLayout>
```
modal-view.ts
```
import { Component, OnInit, NgModule } from "@angular/core";
import { ModalDialogParams } from "nativescript-angular/modal-dialog";
import { DatePicker } from "ui/date-picker";
import { Page } from "ui/page";
import { TimePicker } from "ui/time-picker";

// >> passing-parameters
@Component({
    moduleId: module.id,
    templateUrl: "./modal-view.html",
})
export class ModalViewComponent implements OnInit {
    public currentdate: Date;
    public currenttime: Date;
    
        constructor(private params: ModalDialogParams, private page: Page) {
            this.currentdate = new Date(params.context);
            this.currenttime = new Date();
            console.log("--------------------------------------------------------");
            console.log("params.context");
            console.log("--------------------------------------------------------");
            console.log(params.context);
            console.log("--------------------------------------------------------");
            this.page.on("unloaded", () => {
                        this.params.closeCallback();
            });
        }
        ngOnInit(){}
        rpLoaded(args) {
         let timePicker: TimePicker = <TimePicker>this.page.getViewById<TimePicker>("timePicker");
    timePicker.hour = this.currenttime.getHours();
    timePicker.minute = this.currenttime.getMinutes();
        }
    
        dploaded(args){
            let datePicker: DatePicker = <DatePicker>this.page.getViewById<DatePicker>("datePicker");
            datePicker.year = this.currentdate.getFullYear();
            datePicker.month = this.currentdate.getMonth() + 1;
            datePicker.day = this.currentdate.getDate();
            datePicker.minDate = new Date(1975, 0, 29);
            datePicker.maxDate = new Date(2045, 4, 12);
        }
        public submit() {
            let datePicker: DatePicker = <DatePicker>this.page.getViewById<DatePicker>("datePicker");
            let timePicker: TimePicker = <TimePicker>this.page.getViewById<TimePicker>("timePicker");
    
    var date = datePicker.date.toString();
    var arr= new Array();
    arr= date .split(" ");
    var month = arr[1];
    var fullDate = arr[2] + "-" + month + "-" + arr[3];
    
      var format = this.addZero(timePicker.time.getHours());
      var formatt =  this.addZero(timePicker.time.getMinutes());
      var Datetime = arr[2] + "-" + month + "-" + arr[3] + " " + format + ":" + formatt;
    console.log("selected datetime " + Datetime );
     this.params.closeCallback(Datetime); 
        }
    
        public clear(){
            this.params.closeCallback(""); 
        }
    
        addZero(i) {
        if (i < 10) {
            i = "0" + i;
        }
        return i;
    }
}
// << passing-parameters

```
This should resolve the issue with the black screen

**Comment by kumaran-dena** [comment]
Hi @tsonevn, 
I have tried as you suggested,
So its load the date on the loadedEvent of the TimePicker. then
![datetimeissue](https://user-images.githubusercontent.com/30895291/31441602-480eb546-aeb1-11e7-96b2-ac5e2fac9491.PNG)
 both date/time pickers renders as expected. 
But the problem is what, In datepicker its showing next month(current month + 1) instead of showing current month.
In modal page constructor and dploaded() function, Its receiving the date values correctly.
FYI,
![datetimeissue](https://user-images.githubusercontent.com/30895291/31441649-6752e184-aeb1-11e7-9673-726b1cf2a94e.PNG)

while setting the month value to the date picker, its taking +1 month.
`dploaded(args){
            let datePicker: DatePicker = <DatePicker>this.page.getViewById<DatePicker>("datePicker");
            datePicker.year = this.currentdate.getFullYear();
            **_datePicker.month = this.currentdate.getMonth() + 1;_**
            datePicker.day = this.currentdate.getDate();
            datePicker.minDate = new Date(1975, 0, 29);
            datePicker.maxDate = new Date(2045, 4, 12);
        }`
So i have tried with follows, I don't get solution.
`**datePicker.month = this.currentdate.getMonth() - 1;**
**datePicker.month = this.currentdate.getMonth();**`

No luck both are failed!

**Comment by tsonevn** [comment]
Hi @kumaran-dena,
The problem with showing the wrong month is known issue, which was reported [here](https://github.com/NativeScript/NativeScript/issues/4851) . The fix is already available for the upcoming version and you could test it on your side by using @next modules. 
`tns plugin remove tns-core-modules`
`tns plugin add tns-core-modules@next`
Bear in mind to delete node_modules, platforms and hook folders before rebuilding
