### ISSUE TITLE
Calling existing project android java methods

### ISSUE THREAD

**Issue by patelhr** [NativeScript/nativescript-angular#1013]
Hello,
I am new to nativescript.I don't know how to call activity method from typescript.So please help me out this.

**Comment by NickIliev** [comment]
Hey @patelhr this repository is for logging issue, bugs, and feature requests. Please post a how-to related question in one of the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/) where you can receive faster help from the NativeScript community.

Regarding your question: You can enable IntelliSense in TypeScript (and JavaScript) projects by installing [tns-platform-declarations ](https://github.com/NativeScript/NativeScript/tree/master/tns-platform-declarations). This way you will receive autocomplete for all native classes, methods, and properties in both Android and iOS.

**Comment by patelhr** [comment]
@NickIliev thanks for reply.I followed instruction you have provided.I have crated method to call activity methods.but my existing application activity methods contain context and calling some other java virtual methods.So is there any way to tackle this solution?
