### ISSUE TITLE
Custom fonts not applied for ActionBar Title

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1015]
Custom fonts are not applied for ActionBar in Angular based application (works as expected in NativeScript Core).

Steps to reproduce: use [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/actionBarCustomFont) or the following snippets (using Nasalization.ttf)

```
.na {
    font-family: "Nasalization";
    background-color: #343838;   
    color: #BCBCBC;
}

ActionBar {
    font-family: "Nasalization";
    background-color: #343838;   
    color: #BCBCBC;
}
```

Background and color are successfully applied while font-family is not respected.

**Comment by prabudevarrajan1** [comment]
I am also facing the same issue. Any work around plz?

**Comment by MaxiSonntag** [comment]
Still an ugly issue, would really appreciate if this was fixed someday

**Comment by NickIliev** [comment]
@MaxiSonntag @prabudevarrajan1 you could workaround this issue by creating a custom action bar content

For example:
```
<ActionBar>
	<StackLayout>
		<!--Add your page content here-->
		<Label textWrap="true" text="Play with NativeScript!" class="na" />
	</StackLayout>
</ActionBar>
```

Playground demo [here](https://play.nativescript.org/?template=play-js&id=y8q8C9)

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/NativeScript #6654](https://github.com/NativeScript/NativeScript/issues/6654) via [**ZenHub**](https://www.zenhub.com/)
