### ISSUE TITLE
Issue while calling activity

### ISSUE THREAD

**Issue by patelhr** [NativeScript/nativescript-angular#1016]
I have crated method to call activity methods.but my existing application activity methods contain context and calling some other java virtual methods.So is there any solution for this problem?

I am calling method using this 
var test = new com.tns.TestObject();
console.log(test.doSomething());
It will call java method but it don't have activity context and calling failed to virtual method.
So is there any way in native script to call activity method with context?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/android-runtime#854
