### ISSUE TITLE
Custom ActionBar.titleView crashing on iOS (Angular app)

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1017]
_From @NickIliev on September 29, 2017 6:44_

Setting custom title view for ActionBar is throwing on iOS with 
```
file:///app/tns_modules/tns-core-modules/ui/core/view/view.js:60:124: JS ERROR Error: onMeasure() did not set the measured dimension by calling setMeasuredDimension() ProxyViewContainer(11)
```

Reproducible only in **Angular** based application.

Steps to reproduce:
Use [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/actionBarTitleViewNg) or the following snippet

```
<!-- Custom titleView NOT working on iOS - working on Android-->
<ActionBar>
    <ActionBar.titleView>
        <StackLayout orientation="horizontal">
            <Label text="lbl 1" textWrap="true"></Label>
            <Label text="lbl 2" textWrap="true"></Label>
            <Label text="lbl 3" textWrap="true"></Label>
        </StackLayout>
    </ActionBar.titleView>
</ActionBar>
```

_Copied from original issue: NativeScript/NativeScript#4905_

**Comment by davidsandoz** [comment]
Is there any plan to fix this high-severity bug?

**Comment by manoldonev** [comment]
@davidsandoz it seems we have mistakenly logged this as a bug in the first place. Property dot notation (`<ActionBar.titleView>...</ActionBar.titleView>`) is not a valid syntax in html so in Angular the action bar title should be set like this:
``` html
<ActionBar>
    <StackLayout orientation="horizontal">
        <Label text="lbl 1" textWrap="true"></Label>
        <Label text="lbl 2" textWrap="true"></Label>
        <Label text="lbl 3" textWrap="true"></Label>
    </StackLayout>
</ActionBar>
```

This is also described in the documentation [here](https://docs.nativescript.org/angular/ui/action-bar#using-a-custom-title-view).
