### ISSUE TITLE
Default App name appearing as ActionBar title after live syncing HTML files

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1020]
When creating the ActionBar without explicitly setting `title` property the default application name is appearing after live syncing changes in the HTML files. Observed only in Angular.

Steps to reproduce - use [this application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/test/my-app-name) or the following steps

- create ActiojnBar with no explicit `title` property
```
<ActionBar class="action-bar">
    <Label class="action-bar-title" text="MY Text"></Label>
</ActionBar>
```

- execute `tns run android` and make a change in the HTML file

Result: new title will appear with the application default name.
Happens only in Angular and only on Android.

Reported by templates team.

**Comment by mhmo91** [comment]
Hello guys, any updates here? i notice there'r  a lot of issues in nativescript and they are not moving fast enough, makes me wonder if we can depend on it for production at this moment?

**Comment by liuwei108** [comment]
+1

**Comment by kamok** [comment]
One way to fix this is to set the title property to `""`, and the title will be blank. Or whatever title you want. It'll override the default.

I'm not sure if this is a "feature" of Android, or just problem with the Angular version of NativeScript, but it seems like an easy quick fix.

**Comment by VladimirAmiorkov** [comment]
HI all,

After reviewing this issue I am not able to reproduce it with the current versions of Angular (7.2.0) and nativescript-angular (7.2.2). 

I am attaching a test project that I used to test this issue. @NickIliev  @kamok Can you confirm if this is still an issue?
[NS-Issues-2017-test-my-app-name-edited.zip](https://github.com/NativeScript/nativescript-angular/files/2911012/NS-Issues-2017-test-my-app-name-edited.zip)

**Comment by NickIliev** [comment]
Closing the issue as it is no longer reproducible with latest versions of `nativescript-angular` and `tns-core-modules`.

Tested with @VladimirAmiorkov's app and with all developer sync options
```
tns run android
tns run android --bundle
tns run android -hmr
```
