### ISSUE TITLE
router-outlet's misbehaviour in @angular/router 4.4.4

### ISSUE THREAD

**Issue by Liooo** [NativeScript/nativescript-angular#1025]
After upgrading angular things to 4.4.4, router-outlet started misbehaving.  
I have the following routes

```
  { path: 'home', component: HomeComponent, canActivate: [AuthGuard], children: [
    { path: 'list', component: AssignmentListComponent, outlet: 'assignmentsOutlet'},
    { path: 'detail/:id', component: AssignmentDetailsComponent, outlet: 'assignmentsOutlet'}
  ]}
```

HomeComponent's view is looking like this.
```
<TabView
  [(ngModel)]="selectedIndex"
  (selectedIndexChanged)="tabViewIndexChange(tabView.selectedIndex)">

  <StackLayout *tabItem="{title: 'assigments'}">
    <router-outlet name="assignmentsOutlet"></router-outlet>
  </StackLayout>
   ..
```

and when I navigate from '/home/list' to 'detail/:id', by 

```
router.navigate(['/home', {outlets: { assignmentsOutlet: ['detail', 1] } }])
```
I see `AssignmentDetailsComponent`'s view ABOVE `AssignmentListComponent`'s one, rather than the prior replacing the latter.
Reverting the angular version fixed the problem so I'm assuming it's an issue introduced by the update.

package.json before (which is working)
```
    "@angular/animations": "~4.2.0",
    "@angular/common": "~4.2.0",
    "@angular/compiler": "~4.2.0",
    "@angular/core": "~4.2.0",
    "@angular/forms": "~4.2.0",
    "@angular/http": "~4.2.0",
    "@angular/platform-browser": "~4.2.0",
    "@angular/router": "~4.2.0",
    "nativescript-angular": "^4.2.0",
    "tns-core-modules": "^3.2.0",
```

package.json after (which is not working)
```
    "@angular/animations": "~4.4.4",
    "@angular/common": "~4.4.4",
    "@angular/compiler": "~4.4.4",
    "@angular/core": "~4.4.4",
    "@angular/forms": "~4.4.4",
    "@angular/http": "~4.4.4",
    "@angular/platform-browser": "~4.4.4",
    "@angular/router": "~4.4.4",
    "nativescript-angular": "^4.2.0",
    "tns-core-modules": "^3.2.0",
```

**Comment by danielgek** [comment]
@Liooo i think `nativescript-angular@4.2.0` can **only** be used with angular `4.2.x`, next version will support angular `4.4.x`

**Comment by Liooo** [comment]
@danielgek Thank you, probably that's it.
Maybe [package.json's version and dependency](https://github.com/NativeScript/nativescript-angular/blob/c264453ffa6e28ca4659e7e35f31507842072a93/nativescript-angular/package.json#L4) should be fixed.

**Comment by jogboms** [comment]
@Liooo check this out https://github.com/NativeScript/nativescript-angular/issues/941

**Comment by NickIliev** [comment]
@Liooo can you confirm if the fix introduced [here](https://github.com/NativeScript/nativescript-angular/issues/941#issuecomment-335510169) is resolving your issue

**Comment by Liooo** [comment]
@jogboms @NickIliev sorry I just reverted back to 4.2.0 and still haven't tried the solution, will check it out and get back to you guys

**Comment by Liooo** [comment]
@jogboms @NickIliev updating to `nativescript-angular@4.4.0` fixed it, thanks!
