### ISSUE TITLE
After update Nativescript Cli 3.2.1- Unfortunately app has stopped occurred

### ISSUE THREAD

**Issue by kumaran-dena** [NativeScript/nativescript-angular#1028]
I have updated my app to Cli version 3.2.1 from Cli 3.0.3. After updated the tns-core-modules/platfroms to up to date.

I tried to build the app, Its won’t build and result with some errors on console. Then tried with suggestions from this similar [github issue](https://github.com/NativeScript/NativeScript/issues/3791).

This time app builds successfully and splashscreen loaded then end up with " Unfortunately, app has stopped " in device. I was tested with android platform.
**Console-**
`System.err: Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_m
odules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
System.err:     android.app.ActivityThread.access$1600(ActivityThread.java:175)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:146)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5602)
System.err:     java.lang.reflect.Method.invokeNative(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:515)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
System.err:     dalvik.system.NativeStart.main(Native Method)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.IFS/files/app/tns_modules/nati
vescript-bottombar/src/common.js', line: 4, column: 15
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.IFS/files/app/tns_modules/nati
vescript-bottombar/bottombar.js', line: 6, column: 10
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.IFS/files/app/audit/ism/vessel
comdetails.js', line: 32, column: 32
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.IFS/files/app/app.routing.js',
 line: 7, column: 26
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.IFS/files/app/app.module.js',
line: 5, column: 21
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.IFS/files/app/main.js', line:
5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266`

FYI, Here is my console logs in this attachment [console_log.txt](https://github.com/NativeScript/nativescript-angular/files/1362635/console_log.txt).

Regarding this i have raised the topic on NS forum [thread](https://discourse.nativescript.org/t/after-update-nativescript-cli-3-2-1-unfortunately-app-has-stopped-occurred/2764).

Thanks in advance.

**Comment by kumaran-dena** [comment]
App logcat- 
[Log-2017-10-09-10-53-59.txt](https://github.com/NativeScript/nativescript-angular/files/1367613/Log-2017-10-09-10-53-59.txt)

**Comment by tsonevn** [comment]
Hi @kumaran-dena,

Did you try deleting node_moodules, platforms and hooks folders from the project and rebuilding it with 
`tns run ios`?
The above-given error could be related to some old files, which were not removed properly from the old platforms folders.

Please let me know, whether this suggestion resolves the problem.

**Comment by kumaran-dena** [comment]
Hey @tsonevn,

- I have tried with deleted the node_moodules, platforms and hooks folders from the project 

- npm cache clean

- Rebuilding it with tns run android

But no luck, Again encountered with same issue.

**Comment by NickIliev** [comment]
@kumaran-dena the issue seems to be related to nativescript-bottombar plugin version.
[The issue is logged in the author's repository](https://github.com/rhanb/nativescript-bottombar/issues/33) and you might want to contact him about the date of the upcoming fix or revert the version of the plugin.

**Comment by kumaran-dena** [comment]
@NickIliev As you told when i removed the nativescript-bottombar plugin, Then app works perfectly as expected.

@NickIliev & @tsonevn thanks for your support.

**Comment by NickIliev** [comment]
@kumaran-dena as far as I noticed in the discussion in the plugin's repository you can try to install the previous version of the plugin where the issue is not observed

**Comment by kumaran-dena** [comment]
@NickIliev I have tried with previous version nativescript-bottombar plugin,

FYI,
`
PS D:\IFS\IFS_Latest\IFSAppMobile> tns plugin add nativescript-bottombar@2.1.4
D:\IFS\IFS_Latest\IFSAppMobile
`-- nativescript-bottombar@2.1.4
Successfully installed plugin nativescript-bottombar.
`

After app builds successfully. But when i tried to run app, "..../bindable"' has no exported member 'Bindable' error occurred.
`
PS D:\IFS\IFS_Latest\IFSAppMobile> tns run android
Searching for devices...
Executing before-liveSync hook from D:\IFS\IFS_Latest\IFSAppMobile\hooks\before-liveSync\nativescript-a
ngular-sync.js
Executing before-prepare hook from D:\IFS\IFS_Latest\IFSAppMobile\hooks\before-prepare\nativescript-dev
-typescript.js
Found peer TypeScript 2.2.2
node_modules/nativescript-bottombar/index.d.ts(3,10): error TS2305: Module '"D:/IFS/IFS_Latest/IFSAppMobile
/node_modules/tns-core-modules/ui/core/bindable/bindable"' has no exported member 'Bindable'.

Unable to apply changes on device: 3004c567d59f1200. Error is: TypeScript compiler failed with exit code 1.
Executing after-watch hook from D:\IFS\IFS_Latest\IFSAppMobile\hooks\after-watch\nativescript-dev-types
cript.js
PS D:\IFS\IFS_Latest\IFSAppMobile>
` 
Any idea on this?

**Comment by NickIliev** [comment]
@kumaran-dena version 2.x.x are for sure not compatible with NativeScript 3.x.x.
Try installing nativescript-bottombar@3.0.5

**Comment by kumaran-dena** [comment]
@NickIliev As you suggested, nativescript-bottombar@3.0.5 works as expected with Cli version 3.2.1.

Thanks again.
