### ISSUE TITLE
TabView - Cannot read property 'nativeSize' of undefined, undefined

### ISSUE THREAD

**Issue by Tyre88** [NativeScript/nativescript-angular#1029]
Hello,

I am getting this error when using the TabView. I have my "Main page" where i have a TabView but if i navigate away from that "Main page" and then press back or navigate back i am getting the error:
"Cannot read property 'nativeSize' of undefined, undefined"

This can be solved by doing this:
`page.on(Page.navigatingToEvent, () => {
                this.showTabView = true;
            });
            page.on(Page.navigatingFromEvent, () => {
                this.showTabView = false;
            });`

And then have a *ngIf="showTabView" on my TabView element. The problem with this solution is that it makes the navigation slow since it needs to render the tabview everytime i navigate to the "Main page".

**Comment by tsonevn** [comment]
HI @Tyre88,
Thank you for reporting this issue.
I tested this case while using the latest version nativescript-angular 4.2, however, I was unable to recreate the reported problem. For your convenience I am attaching sample project, please review it and make the needed changes, which will allow us to reproduce this issue.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1367861/Archive.zip)
![screencast 2017-10-09 at 11 12 11 am](https://user-images.githubusercontent.com/17448734/31329576-7941cf38-ace3-11e7-9400-f06d296a0451.gif)
![screencast 2017-10-09 at 11 14 28 am](https://user-images.githubusercontent.com/17448734/31329575-793df944-ace3-11e7-86be-5131c5016b9a.gif)

**Comment by Tyre88** [comment]
It seems like i can't recreate the error with this package selection only so there's probably some other package causing this error. 
Closing the issue.
