### ISSUE TITLE
Documentation repo and build

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#103]
Use the {N} docs. Introduce a conditional build that hides/shows Angular2 content.

**Comment by NathanWalker** [comment]
This sounds nice. Lemme know if I can assist in anyway here. :+1:

**Comment by hdeshev** [comment]
Pushed the changes to the docs repo (master branch), and [documented](https://github.com/NativeScript/docs/blob/master/README.md) them a bit.

I also went over most of the content and hid topics that don't make sense in the Angular context (bindings, dependency properties, etc). Conditionally switched a lot of code for the `nativescript` build env and added `TODO` sections for its Angular equivalent. Still a lot of work left to be done there.

Oh, and we now have a "Cookbook" section enabled only for the `angular` environment.
