### ISSUE TITLE
NativeScript drawer not working : " showDrawer() is not a function"

### ISSUE THREAD

**Issue by moda20** [NativeScript/nativescript-angular#1032]
Hey, is it me or the official documentation at docs.telerik.com about the drawer is not right ?

I tried that in my app and it didn't work. 
Here is the code i wrotein the ts file.
```
    toggleDrawer(){
        console.log("RRRR");
       let X = <RadSideDrawer>( frame.topmost().getViewById("drawer"));
        /*console.log(sideDrawer.toggleDrawerState())*/
        /*sideDrawer.toggleDrawerState()*/
        X.showDrawer();
    } 
```

and the XML content 
```
    <drawer:rad-side-drawer id="drawer">
        <drawer:rad-side-drawer.mainContent>

            <grid-layout>
                <slides>
                    <slide class="slide-1">
                        <StackLayout>
                            <GridLayout rows="60" columns="*, *, *" >
                                <Button class="btn btn-primary" col="2" text="Button" (tap)="rr()"></Button>
                            </GridLayout>
                        </StackLayout>
                        <Label text="This is Panel 1"></Label>
                    </slide>
                </slides>
            </grid-layout>

        </drawer:rad-side-drawer.mainContent>
        <drawer:rad-side-drawer.drawerContent>

        </drawer:rad-side-drawer.drawerContent>
    </drawer:rad-side-drawer>
```

Note i use the nativescript plugin slides, which should not by any means have any problems with the drawer.
so when i try to show the drawer like the docs says i get this error
`JS: ERROR TypeError: X.showDrawer is not a function
JS: ERROR CONTEXT [object Object]
`
any ideas if this is a bug or outdated docs ?

**Comment by NickIliev** [comment]
@moda20 there are few things to consider.
The above code seems to be for NativeScript Core application (JavaScript or TypeScript) and not for Angular application. If you need to create RadSideDrawer for Angular application see [these documentation articles](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/overview).

Another thing you can check if you got your reference to the side drawer compoennt.
is this portion of code returning the drawer reference.
```
let X = <RadSideDrawer>( frame.topmost().getViewById("drawer"));
console.log(X);`
````

You can check how the drawer examples in nativescript-ui=samples are getting reference by id [here](https://github.com/telerik/nativescript-ui-samples/tree/release/sdk/app/sidedrawer).

Closing this issue as it seems unrelated to nativescript-angular. Please post drawer related issues in [nativescript-ui-feedback repository ](https://github.com/telerik/nativescript-ui-feedback/issues)or in the community channels if they are how-to related.
