### ISSUE TITLE
Missing (tab) event emitter on tabItem on TabView

### ISSUE THREAD

**Issue by christian-kolb** [NativeScript/nativescript-angular#1034]
I use a TabView as described here with nested routing: https://github.com/NativeScript/nativescript-angular/issues/1022

```
<TabView 
  #tabView 
  tabsBackgroundColor="#f57c00" selectedTabTextColor="#B23010"
  [(ngModel)]="selectedIndex"
  (selectedIndexChanged)="tabViewIndexChange(tabView.selectedIndex)">

  <StackLayout *tabItem="{iconSource: 'res://tab-icons/cats'}">
    <cats-tab></cats-tab>
  </StackLayout>

  <StackLayout *tabItem="{iconSource: 'res://tab-icons/dogs'}">
    <dogs-tab></dogs-tab>
  </StackLayout>
</TabView>
````

When navigating into a detail view in my already active tab there is now way through the tab navigation to go back to overview component. The selectedIndexChanged event is of course only triggered when I change my tab. But I can't go back to my tab overview component with clicking on the already selected tab. I would be able to put in this functionality if there was a way to emit a `tab` event on the `tabItem`. I tried to get the TabViewItem programmatically but as I also can't set an `id` on it I can't really get to it.

This would also be needed if I wanted to scroll up in the view that I'm currently in (as Facebook is using it).

Is there a way to get to the TabViewItem programmatically or any other way to add a (tab) event emitter to it?

**Comment by tsonevn** [comment]
Hi @christian-kolb,
Thank you for the detailed description of your case.
I reviewed that case and found that there is no such functionality that allows to setup custom tab event emitters. 
However, bear in mind that the main idea for this components is to allow switching between a different viewed on the same page, where the event will be fired only while switching the tabs. 
In your specific case, while using a nested router, which is pure Angular technique, I would suggest creating a custom view with buttons, where you could set up the needed content in StackLayouts, which could be shown and hide depending on the selected button.
For example:
```
<GridLayout rows="auto *" columns="* *">
  <Button row="0" col="0" text="First Tab" (tap)="onTap()"></Button>
  <Button row="0" col="1" text="Second Tab" (tap)="onTap2()" ></Button>
  <StackLayout row="1" col="0" colSpan="2" [visibility]="isItemVisible ? 'visible' : 'collapsed'">
    <Label text="Content for ther first tab" textWrap="true"></Label>

  </StackLayout>
  <StackLayout row="1" col="0" colSpan="2" [visibility]="isItemVisible2 ? 'visible' : 'collapsed'">
    <Label text="Content for ther second tab" textWrap="true"></Label>

  </StackLayout>
</GridLayout>
```
For any further question, you could use [NativeScript forum](https://discourse.nativescript.org/).

**Comment by ianrothmann** [comment]
Just for the record (if anyone's googling), this is how I handled it:
In onSelectedIndexChanged, I update an index variable.

` idx=0;
    onSelectedIndexChanged(args: SelectedIndexChangedEventData) {
        const tabView = <TabView>args.object;
        const selectedTabViewItem = tabView.items[args.newIndex];
        this.idx=args.newIndex;

        this.title = selectedTabViewItem.title;
    }`

and then I ngIf my page on that variable:

`<StackLayout *tabItem="{title: 'Browse', iconSource: getIconSource('browse')}">
        <Browse *ngIf="idx==0"></Browse>
    </StackLayout>`

And then I use ngOnInit inside my page. This forces the component to recreate when the tab is changed. Of course, this probably causes a performance decrease, but anyway.
