### ISSUE TITLE
No provider for NSRouteReuseStrategy! nativescript-angular@4.4.0

### ISSUE THREAD

**Issue by kinggolf** [NativeScript/nativescript-angular#1036]
Tried nativescript-angular@4.4.0 on standard tabs project: https://github.com/NativeScript/template-tab-navigation-ng and received this error: 
`No provider for NSRouteReuseStrategy!`
Ran on iOS simulator only.

Dependencies:
```
  "nativescript": {
     "id": "org.nativescript.tabsTest",
     "tns-ios": {
        "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.4.1",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "nativescript-angular": "4.4.0",
    "nativescript-plugin-firebase": "4.1.1",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "3.2.0",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "codelyzer": "3.2.0",
    "nativescript-dev-sass": "1.3.2",
    "nativescript-dev-typescript": "0.5.1",
    "node-sass": "4.5.3",
    "tslint": "5.7.0",
    "typescript": "2.5.2"
  }
```

Works with nativescript-angular@4.2.0 and angular packages all set to 4.2.5.
Dependency, nativescript-plugin-firebase not part of the tabs template, but previously added, and has no bearing on this issue.
Thanks.

**Comment by tsonevn** [comment]
Hi @kinggolf,
 I reviewed the reported issue, however as you could see in the attached GIF, I was unable to reproduce an issue while using the angular 4.4.
Make sure that after changing the version for the dependencies in the project, you have deleted platforms, node_modules and hook folders. 
I am attaching sample project, please review it and verify, whether I am missing something.
![screencast 2017-10-12 at 11 27 15 am](https://user-images.githubusercontent.com/17448734/31486531-755433ac-af40-11e7-9a26-3b42bae6daf8.gif)
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1378620/Archive.zip)

**Comment by kinggolf** [comment]
@tsonevn Thank you for you response. Yes, when I removed all of the folders you recommended, then the application works with latest nativescript-angular. Sorry for taking your time with this, but thanks again. Cheers.
