### ISSUE TITLE
Update tutorial to templates and styles paths compatible with webpack

### ISSUE THREAD

**Issue by felipeferri** [NativeScript/nativescript-angular#1038]
I was using the excellent Groceries tutorial as a reference for my first Nativescript app, using Angular and Typescript.

My app worked ok on the simulators and devices, but when I ran webpack I started to get lots of error messages of templates being looked for in weird places, such as:

`../pages/splash/pages/splash/splash.html`

This was happening because I was using, as the tutorial suggests, the following format for setting the templates paths on the @Component decorators:

`pages/splash/splash.html`

This works then running the app, but it seems that webpack resolves this relative path over the current working directory. So I found out that the correct way of setting the templates and styles paths is using:

```
@Component({
    selector: "splashview",
    moduleId: module.id,
    templateUrl: "./splash.html",
    styleUrls: ["./splash-common.css"]
})
```

And if you check the Groceries code on github the paths are set like this.

Some answers I found on Stackoverflow (see [here](https://stackoverflow.com/a/37178295/212292) for example) suggest it is not necessary anymore to use the moduleId line, however I tested it and noticed it breaks the app if you omit it.

I propose the tutorials are corrected to use this format for the path, or at least the documentation on webpack is updated to include this.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/docs#937
