### ISSUE TITLE
Still getting Nativescript splash screen instead of mine

### ISSUE THREAD

**Issue by mutazmq** [NativeScript/nativescript-angular#1041]
I'm developing an iOS app but I'm still getting the Nativescript splash screen even though I did the following:

1. Changed all images in `Assets.xcassets` folder
2. Removed iOS platform using`tns platform remove ios` and added it again (Just in case there was some caching)
3. Deleted the app from my iPhone several times

But still I'm getting the same default Nativescript image when the app is launched on my device! However iOS simulator doesn't have this problem and shows me the new image.

Using tns version 3.2.0:

```
    "tns-android": {
      "version": "3.2.0"
    },
    "tns-ios": {
      "version": "3.2.0"
    }
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3159
