### ISSUE TITLE
ActionBar title value cannot be overwritten by custom title when using ngIf

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-angular#1042]
Here is the code I use for my calendar page. Default title text is overwritten by custom title elements.

````html
<ActionBar title="Calendar">
    <label class="title" [text]="pageTitle" *ngIf="!selectedEvents.length"></label>
    <label class="title" [text]="selectedEvents.length" *ngIf="selectedEvents.length"></label>
</ActionBar>
````

Current month is shown as the title. If user selects some events, page goes into selection mode and title shows the selected item count.

The problem is `Calendar` text is hidden by default but after I choose some events it becomes visible and even if I cancel selection that text is still visible with custom title element.

Title changes like that after performing these operations:
When app loaded: October 2017
Select event: Calendar 1
Deselect event: Calendar October 2017

tns-android: 3.2.0
tns-core-modules: 3.2.0
tns --version: 3.2.1

**Comment by erkanarslan** [comment]
Might be related with https://github.com/NativeScript/nativescript-angular/issues/1020

**Comment by tsonevn** [comment]
Hi @erkanarslan,
Thank you for contacting us.
I tested this case and indeed this is the same case, which is reported in #1020.
I am closing this issue in favor of the other one.
