### ISSUE TITLE
Cannot find name UIApplicationDelegate UIApplication NSDictionary UIApplication

### ISSUE THREAD

**Issue by bumbella** [NativeScript/nativescript-angular#1047]
Hi!

I get this error when I want to insert example code from NativeScript iOS UIApplicationDelegate example. I use latest Nativescript angular version with typescript 2.4.2
I insert tsconfig "noEmitOnError": false, but not resolve this problem.

app/main.ts(35,53): error TS2304: Cannot find name 'UIApplicationDelegate'.
app/main.ts(38,63): error TS2304: Cannot find name 'UIApplication'.
app/main.ts(38,93): error TS2304: Cannot find name 'NSDictionary'.
app/main.ts(44,49): error TS2304: Cannot find name 'UIApplication'.

Code in main ts

```
import { ios, start as applicationStart } from "application";
class MyDelegate extends UIResponder implements UIApplicationDelegate {
    public static ObjCProtocols = [UIApplicationDelegate];

    applicationDidFinishLaunchingWithOptions(application: UIApplication, launchOptions: NSDictionary): boolean {
        console.log("applicationWillFinishLaunchingWithOptions: " + launchOptions)

        return true;
    }

    applicationDidBecomeActive(application: UIApplication): void {
        console.log("applicationDidBecomeActive: " + application)
    }
}
ios.delegate = MyDelegate;
applicationStart();
```

Please help me what is the problem with my code.
Miklos

**Comment by tsonevn** [comment]
Hi  @bumbella,
Regarding the provided log, it seems that you missed adding `tns-platform-declarations`. You could review the [plugins ReadMe](https://www.npmjs.com/package/tns-platform-declarations), where it is described, how to add it in your project. For your convenience, I am also attaching a 
sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1397632/Archive.zip)

**Comment by bumbella** [comment]
Thanx.
I already make this things but I get errors.
I have no idea what is the problem.
I make it too your sample projects.
Please help me.
Miklos

**Comment by tsonevn** [comment]
Hi @bumbella,
The NSDictionary in your code should be defined as `NSDictionary<any, any>`. The code for the delegate method should be like the attached code below:
```
applicationDidFinishLaunchingWithOptions(application: UIApplication, launchOptions: NSDictionary<any, any>): boolean {
        console.log("applicationWillFinishLaunchingWithOptions: " + launchOptions)

        return true;
    }
```
