### ISSUE TITLE
Angular/OnDestroy - How to detect page leaving navigation event?

### ISSUE THREAD

**Issue by morzyns** [NativeScript/nativescript-angular#1049]
OnDestroy doesn't work for angular navigation lifecycle hooks. That's fine, but i still need to detect the page leaving event.
What's the best way to do that?

**Comment by anuragd7** [comment]
Try the page unloaded event.

On 20 Oct 2017 5:10 p.m., "morzyns" <notifications@github.com> wrote:

OnDestroy doesn't work for angular navigation lifecycle hooks. That's fine,
but i still need to detect the page leaving event.
What's the best way to do that?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NativeScript/nativescript-angular/issues/1049>, or mute
the thread

**Comment by jfturcot** [comment]
Here is how I handle it:

```typescript
constructor(private page: Page) {}

ngOnInit(): void {
  this.page.on('navigatingTo', (data) => {
    // run init code
    // (note: this will run when you either move forward or back to this page)
  }

  this.page.on('navigatingFrom', (data) => {
    // run destroy code
    // (note: this will run when you either move forward to a new page or back to the previous page)
  }
}
```

You could probably try this in the constructor also if you do not need an OnInit in the controller where you need this, but I usually add this to the OnInit.

**Comment by morzyns** [comment]
Thanks @jfturcot, i tried similar approach but with a router navigatingFrom and navigatingTo events. in my case, navigatingFrom & navigatingTo were hit every time simultaneously.

**Comment by tsonevn** [comment]
Hi @morzyns,
Did you try the solution provided by @anuragd7 to handle page unloaded event? For example:
```
this.page.on('unloaded ', (data) => {
    // run init code
    // (note: this will run when you either move forward or back to this page)
  }
```

**Comment by abhayastudios** [comment]
A bit late to the party, but since the OP is asking about Angular, I wanted to point out that if you are not using page navigation, the page navigation events mentioned above will of course not fire. In that case you you can listen to Angular's navigation events like below:

```
import { NavigationStart, Router } from '@angular/router';

  private routeSub:any;  // subscription to route observer

  public ngOnInit() {
    /* 
       Register to Angular navigation events to detect navigating away (so we can save changed settings for example)
    */
    this.routeSub = this.router.events.subscribe((event) => {
      if (event instanceof NavigationStart) {
        // save your data
      }
    });
  }

  public ngOnDestroy() {
    this.routeSub.unsubscribe();
  }
```

**Comment by BasyaLipman** [comment]
@abhayastudios - in the code you posted here, you are unsubscribing in ngOnDestroy. NgOnDestroy won't necessarily fire when you navigate away from the angular component, since NativeScript caches the component.

This means that the subscription will exist beyond the point when you navigate away from the component and you'll be executing the subscription callback on NavigationStart events of other components.

**Comment by CoreyCole** [comment]
In my experience, `ngOnDestroy` does not get called when the user presses the back button (in web angular). To have an event fired before the page changes in web angular, you can subscribe to `window:beforeunload` using `@HostListener`.
```typescript
@HostListener('window:beforeunload')
doSomething() {
}
```

[Source (with some other options)](https://stackoverflow.com/questions/36763141/is-there-any-lifecycle-hook-like-window-onbeforeunload-in-angular2)

This obviously won't work in nativescript as there is no `window` object, but I ended up here from google when searching how to do this in web angular.

**Comment by CoreyCole** [comment]
@jfturcot @tsonevn where do you import { Page } from ? Sorry I'm new to NativeScript and I see [here](https://docs.nativescript.org/api-reference/classes/_ui_page_.page) that it is `ui/page` but importing from `nativescript-angular/ui/page` doesn't work

**Comment by abhayastudios** [comment]
@CoreyCole 

```
import { Page } from 'tns-core-modules/ui/page';
```

**Comment by jpierront** [comment]
Use

```
page.on(Page.navigatingFromEvent, () => {
    this.ngOnDestroy(); // Replace by what you want
});
```

And not `Page.unloadedEvent` because `Page.unloadedEvent` is also triggered when the application goes into background.

**Comment by Stanteq** [comment]
I wrote an [article](https://www.stanteq.com/blog/6/nativescript-ngondestroy-is-not-called) about this. I solved it in generic way with the decorator.

**Comment by jpierront** [comment]
@joelau71 Unfortunately ngOnDestroy isn't called when you navigate to a new page

**Comment by jpierront** [comment]
@Stanteq Nice solution! This will avoid some duplication, especially with a NativeScript + Web application. Not great to have to inject the injector, but hard to do better, I think.

**Comment by jpierront** [comment]
Instead of injecting the injector in each page, we could store the injector in a static var ... It's ugly too but it's ugly in only one place! https://stackoverflow.com/questions/39409328/storing-injector-instance-for-use-in-components

**Comment by juniorschen** [comment]
@Stanteq 
This solution would not work for modals

**Comment by Stanteq** [comment]
> @Stanteq
> This solution would not work for modals

As I know the modals works well without this workaround.

**Comment by edusperoni** [comment]
@juniorschen how so? ngOnDestroy is called in modals without navigation and page navigation works normally with named outlets

**Comment by juniorschen** [comment]
@edusperoni I didn't know that in modals destroy was usually called hehe

**Comment by juniorschen** [comment]
@edusperoni 
In navigation modals, will I have the page instance to register for the event?

**Comment by edusperoni** [comment]
@juniorschen if you don't have a Page, ngOnDestroy is called normally, so you don't need this workaround at all

**Comment by juniorschen** [comment]
@edusperoni 
Ooh got it, thanks so much for the explanation

**Comment by osmanraifgunes** [comment]
> Here is how I handle it:
> 
> ```ts
> constructor(private page: Page) {}
> 
> ngOnInit(): void {
>   this.page.on('navigatingTo', (data) => {
>     // run init code
>     // (note: this will run when you either move forward or back to this page)
>   }
> 
>   this.page.on('navigatingFrom', (data) => {
>     // run destroy code
>     // (note: this will run when you either move forward to a new page or back to the previous page)
>   }
> }
> ```
> 
> You could probably try this in the constructor also if you do not need an OnInit in the controller where you need this, but I usually add this to the OnInit.

Where is the "Page" class?

**Comment by marie-dk** [comment]
In a web app I needed to save a message draft to the server automatically when the composer (a child component) was closed: The child component was removed or user navigates to another local page, or navigates away from the web app e.g. by closing the tab.

In my search I came across this article:[A Deep Dive into Angulars NgOnDestroy]( https://wesleygrimes.com/angular/2019/03/29/making-upgrades-to-angular-ngondestroy.html) which explains how to use ngDestroy for all these purposes.

First of all: Add async in front of our ngOnDestroy function.
Then call the function you need onDestroy with await
Last but not least, add @HostListener just above ngOnDestroy

Example:

```
import { Component, OnInit,OnDestroy, HostListener } from '@angular/core';

@Component({
  selector: 'my-example',
  templateUrl: './example.component.html',
  styleUrls: ['./example.component.scss']
})

export class ExampleComponent implements OnInit, OnDestroy {

  constructor() { }

  saveData():Promise<any> {
    //Return a promise so that ngOnDestroy will wait for it to finish
  }

  ngOnInit() {
  }
 
  @HostListener('window:beforeunload') //<-- Do NOT put a semicolon here
  async ngOnDestroy() {
    await this.saveDraft();
  }
}

```
Angular version: 12
At the time of writing it works when closing a tab in Chrome 91. 
You should do your own testing.

**Comment by Dante1349** [comment]
This still wont call the ngOnDestroy function of the sub components in the components template.

**Comment by dgcooke** [comment]
> 
> constructor(private page: Page)
> 

Might be a really dumb question, but what is the Page class you are referring to?
