### ISSUE TITLE
Issue with custom route reuse strategy

### ISSUE THREAD

**Issue by Serge-SDL** [NativeScript/nativescript-angular#1050]
Hello,

I have an app with a special behavior and I need to never reuse a compoent so I have a CustomReuseStrategy file looking like this:
```
export class CustomReuseStrategy implements RouteReuseStrategy {
    shouldDetach(route: ActivatedRouteSnapshot): boolean {
        return false;
    }
    store(route: ActivatedRouteSnapshot, handle: DetachedRouteHandle): void {
    }
    shouldAttach(route: ActivatedRouteSnapshot): boolean {
        return false;
    }
    retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandle {
        return null;
    }
    shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
        return false;
    }
}
```
When I upgrade nativescript-angular from 3 to 4.4.1 I have got this error: 
> Error: Currently not in page back navigation - component should be detached instead of deactivated.

I worked on this for a few days without finding a solution. My question is simple: How to skeep the new reuse strategy system and never reuse any page component?

Thanks !
Serge

**Comment by vakrilov** [comment]
Hi,
The new route-reuse strategy will reuse the component if it uses the same config with different params. This was the previous behaviour and also the default behaviour provided by angular.

The current implementation of the `<page-router-outlet>` relies on the `NSRouteReuseStrategy` to be used. What you can do in your case is to extend [`NSRouteReuseStrategy`](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/ns-route-reuse-strategy.ts#L59) and override only the `shouldReuseRoute` method. You will still have to call `super.shouldReuseRoute(future, curr);` as it contains some important code that has to be executed.

I hope this was helpful.

**Comment by SD-Lab** [comment]
Hi,
Thank you for your answer, it didn't fix my problem but help me to undersant it's related to tns-core-modules version...

**Comment by hdrdiab** [comment]
Hi,
I am currently facing the same problem , my problem is occurring specifically from my custom `shouldDetach` and `shouldAttach` which are not compatible with the `page-router-outlet` behavior , my question is how can i know which strategy is being used by angular router and when ,my `CustomReuseStrategy` or `NSRouteReuseStrategy`? And can i override the behavior of `page-router-outlet` ?

**Comment by vakrilov** [comment]
If you have registered a custom `CustomReuseStrategy` it is probably the one that is used (you can always debug to be sure =) ).
Overriding the behavior of the `page-router-outlet` will not be trivial. It will probably be easier to check the code of the  [`NSRouteReuseStrategy`](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/ns-route-reuse-strategy.ts) and try to extend it with your custom logic. It handles the routes that relate to the `page-router-outlet` in a specific manner as it should always detach(cache) components when navigating to a different page and then reattach them when navigating back. For other cases (for example navigation in nested `router-outlet` in a single page) you can try to plug in your own logic.

**Comment by hdrdiab** [comment]
For example  i need `page-router-outlet` to call `deactivavte()` when navigating back , this will throw an error. Maybe we can remove the behavior of throwing an error (although i don't have any idea how much harm this can cause).

**Comment by manojdcoder** [comment]
@vakrilov If you get a moment please lets know if this would be right way of implementing it or do you recommend any changes on this?

https://play.nativescript.org/?template=play-ng&id=AspHuI

**Comment by vakrilov** [comment]
Hey @manojdcoder 
It looks ok (I haven't tests extensively thought). It's important to call the `super.shouldReuseRoute()` method when you are going to return true as there is an additional logic that `NSRouteReuseStrategy` executes in that [particular](https://github.com/NativeScript/nativescript-angular/blob/258ce980c243dc0cbc1245eb0216e55967e19604/nativescript-angular/router/ns-route-reuse-strategy.ts#L128-L132) case.

**Comment by manojdcoder** [comment]
Thank you @vakrilov for the valuable feedback, will follow that.

**Comment by vakrilov** [comment]
Closing this one for now. Will reopen if needed.

**Comment by TheOnlyMatt** [comment]
Hello
I am somewhat stuck with the same error (component should be reattached instead of activated), whereas I already implemented the customRouteReuseStrategy as stated there. 
Here is my situation : 

RandomComponent > ReusableComponent > ReusableComponent > ... > AnotherComponent
The navigation forward is working well, the navigation forward and backward from the ReusableComponent to AnotherComponent is working correctly (as well than the navigation backward from the ReusableComponent to the RandomComponent), but as soon as I try to navigate back inside the ReusableComponent, this error is thrown, breaking all my navigation.
I am struggling to find where this error could come from, but I haven't found any clue ...
I know the origin is in the way I navigate inside the component, or maybe when I navigate back.
Here the code involved : 

```
//ReusableComponent
 ngOnInit() {
        //Gets the data passed in case of an inner app navigation
        if(this.activatedRoute.snapshot.queryParams["value"]){
            let data = JSON.parse(this.activatedRoute.snapshot.queryParams["value"])
            this.setContent(data[0])
        }
    }

someFunction(){
self.routerExtensions.navigate(["/simple_content"],  {
                                    transition: {
                                        name: "slideLeft",
                                        duration: 300,
                                        curve: "easeInOut"
                                    },
                                    //Necessary to do inner app navigation
                                    queryParams: {
                                        value: response.data
                                    }
                                })
}

goBack(){
        console.log(this._componentNavigationHistory.length)
        console.dir(this._componentNavigationHistory[this._componentNavigationHistory.length -1])

        //If there is no more data to go back in the same component
        if(this._componentNavigationHistory.length > 1){
            console.log("this.routerExtensions.back()")
            this.routerExtensions.back()
            this._componentNavigationHistory.pop()
        }
        else{
            this.routerExtensions.backToPreviousPage();
        }
    }
```

```
export class CustomRouteReuseStrategy extends NSRouteReuseStrategy {

    constructor(location: NSLocationStrategy) {
        super(location);
    }

    shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
        console.log("reusing route")
        super.shouldReuseRoute(future, curr)
        return false;
    }
}
```

```
@NgModule({
    imports: [
        NativeScriptModule,
        NativeScriptRouterModule,
        CommonModule,
    ],
    declarations: [
        SimpleItemComponent,
    ],
    exports:[
        SimpleItemComponent,
    ],
    providers:[
        {
            provide: RouteReuseStrategy,
            useClass: CustomRouteReuseStrategy
        }
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class ContentsModule { }
```

Any help would be very appreciated ! :)
