### ISSUE TITLE
NativeScript Chart doesn't render  - IOS

### ISSUE THREAD

**Issue by morzyns** [NativeScript/nativescript-angular#1057]
Hey, 
i created a component to contain the spline chart from the nativescript example, but apparently, that doesn't render. Also with no console log error/warnings. 

**I tried with different types of parent containers - nothing renders. I think it's not a desired behavior that's why created an issue. It's obviously an issue not a request for the feedback.
** 

The thing is there are other conditions have to be accomplished to render that chart, i those are not in the docs, and not obvious while develop. 

1. Component in the template
```
<GridLayout class="market-chart" rows="*" columns="*" row="1">
       <market-chart></market-chart>
</GridLayout>
```

2. component's template 

```

    <RadCartesianChart tkExampleTitle tkToggleNavButton>
            <CategoricalAxis tkCartesianHorizontalAxis></CategoricalAxis>
            <LinearAxis tkCartesianVerticalAxis></LinearAxis>
        
            <SplineSeries tkCartesianSeries [items]="categoricalSource" categoryProperty="Country" valueProperty="Amount"></SplineSeries>
    </RadCartesianChart>

```

3. component's controller

```
import { Component, OnInit } from '@angular/core';
import { ObservableArray } from "tns-core-modules/data/observable-array";

export class Country {
    constructor(public Country?: string, public Amount?: number, public SecondVal?: number, public ThirdVal?: number, public Impact?: number, public Year?: number) {
    }
}

@Component({
    moduleId: module.id,
    selector: 'market-chart',
    templateUrl: 'market-chart.component.html'
})
export class MarketChartComponent implements OnInit {
    private _categoricalSource: ObservableArray<Country>;

    constructor() {
    }

    get categoricalSource(): ObservableArray<Country> {
        return this._categoricalSource;
    }

    getCategoricalSource(): Country[] {
        return [
            { Country: "Germany", Amount: 15, SecondVal: 14, ThirdVal: 24, Impact: 0, Year: 0 },
            { Country: "France", Amount: 13, SecondVal: 23, ThirdVal: 25, Impact: 0, Year: 0 },
            { Country: "Bulgaria", Amount: 24, SecondVal: 17, ThirdVal: 23, Impact: 0, Year: 0 },
            { Country: "Spain", Amount: 11, SecondVal: 19, ThirdVal: 24, Impact: 0, Year: 0 },
            { Country: "USA", Amount: 18, SecondVal: 8, ThirdVal: 21, Impact: 0, Year: 0 }
        ];
    }

    ngOnInit() {
        console.log('test');
        this._categoricalSource = new ObservableArray(this.getCategoricalSource());
    }
}
```

4. package.json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.BTrex",
    "tns-android": {
      "version": "3.3.0-2017-9-29-1"
    },
    "tns-ios": {
      "version": "3.2.0"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "^4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/router": "4.2.5",
    "email-validator": "^1.0.7",
    "fast-sha256": "^1.0.0",
    "nativescript-angular": "4.2.0",
    "nativescript-telerik-ui": "^3.1.3",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "3.3.0-2017-9-9-1",
    "zone.js": "0.8.17"
  },
  "devDependencies": {
    "codelyzer": "3.2.0",
    "nativescript-dev-sass": "1.3.2",
    "nativescript-dev-typescript": "0.5.0",
    "node-sass": "4.5.3",
    "tslint": "5.7.0",
    "typescript": "2.5.2"
  }
}

5.  Component itself renders/works. console.log('test') works, and it can render for ex the button.
Why can;t i see any errors? What can be possibly wrong?

**Comment by morzyns** [comment]
It;s not a feedback request - i need to know what are the other conditions i need to fulfill to render this chart.

**Comment by NickIliev** [comment]
@morzyns is your chart module imported as shown [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started)?  

I've noticed that in your `package.json` the dependency is to `nativescript-telerik-ui` which **does not** contain the chart module. In fact, currently, the whole nativescript-ui suite is free and published under the name `nativescript-pro-ui` with current version 3.1.4. Try updating the plugin and import the chart module as shown above.

Notice that this repository is for logging issues. bugs and feature related to nativescript-angular plugin.
For how-to related questions use one of the community channels like [discourse.nativescript.org](https://discourse.nativescript.org/) or [SO](https://stackoverflow.com/questions/tagged/nativescript)

**Comment by morzyns** [comment]
Thanks for the help.
