### ISSUE TITLE
Using font-awesome dynamically, icons don't appear

### ISSUE THREAD

**Issue by ParVisual** [NativeScript/nativescript-angular#1060]
When I pass font-awesome unicode dinamically, Nativescript don’t show the icon.

my-section.component.ts file:
```
public items = [
{
title : "Calendar",
icon: "&#xf073;"
},
{
title : "Map",
icon: "&#xf041;",
}
....
];
```
my-section.component.html file:
```
<StackLayout orientation="vertical">
    <ListView [items]="items">
        <ng-template let-item="item">
            <Label [text]="item.icon" class="font-awesome"></Label>
        </ng-template>
    </ListView>
</StackLayout>
```
WRONG RESULT:
![temp](https://user-images.githubusercontent.com/19213467/32056968-5e2a9c14-ba3c-11e7-91cb-36812c58b2de.png)

If I try hardcoding the unicode value:
```
<StackLayout orientation="vertical">
    <ListView [items]="sections">
        <ng-template let-item="item">
            <Label text="&#xf0a1;" class="font-awesome"></Label>
        </ng-template>
    </ListView>
</StackLayout>
```
… the result is correct:

![temp-2](https://user-images.githubusercontent.com/19213467/32056987-6a9bec82-ba3c-11e7-8c70-928952a86975.png)

**Comment by NickIliev** [comment]
@ParVisual  create a string from char value for code behind as shown in the documentation article [here](https://docs.nativescript.org/ui/icon-fonts#using-icon-fonts-in-nativescript)
For example
```
String.fromCharCode(0xe903).
```

**Comment by ParVisual** [comment]
Thank you @NickIliev, that solved the problem.

My array provider now look like this: 

```
public items = [
{
title : "Calendar",
icon: String.fromCharCode(0xf073)
},
{
title : "Map",
icon: String.fromCharCode(0xf041),
}
....
];
```
