### ISSUE TITLE
Properties newIndex and oldIndex not working for SelectedIndexChangedEventData TabView 

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [NativeScript/nativescript-angular#1066]
```
<TabView selectedIndex="1" selectedColor="#FF0000"   (selectedIndexChange)="tabChanged($event)" iosIconRenderingMode="alwaysOriginal" sdkExampleTitle
         sdkToggleNavButton>
    <StackLayout  *tabItem="{title: 'tab.map' | translate}">
        <!--<GridLayout>
    <WebView src="~/home/map.html"></WebView>
</GridLayout>
-->
        <Label text="First tab item"></Label>
    </StackLayout>

    <StackLayout *tabItem="{title: 'tab.meeting.planner' | translate}">
        <Label text="Second tab item"></Label>
    </StackLayout>
    <StackLayout *tabItem="{title: 'tab.service.profile' | translate}">
        <Label text="Second tab item"></Label>
    </StackLayout>

</TabView>

  tabChanged($event: SelectedIndexChangedEventData) {
        console.log($event.newIndex);
//import {SelectedIndexChangedEventData} from 'ui/tab-view';
// $event.newIndex always undefined
    }

```

**Comment by NickIliev** [comment]
@vitaliy-kuzmich can confirm that `newIndex` and `oldIndex` [properties](https://docs.nativescript.org/api-reference/interfaces/_ui_tab_view_.selectedindexchangedeventdata) are returning undefined.

As a **workaround** use directly the selectedIndex property of the TabView.
For example:
```
tabChanged(args) {
    let tabView = <TabView>args.object;
    console.log(tabView.selectedIndex);
}
```

**Comment by vitaliy-kuzmich** [comment]
@NickIliev mentioned code example works, thank you. There is another issue with tabs :  [(ngModel)]="tabSelectedIndex" (from example) also does not works. it says 
`
JS: ERROR Error: No value accessor for form control with unspecified name attribute
JS: ERROR CONTEXT [object Object]
`
By the way how did you detect args.object data type ?

**Comment by NickIliev** [comment]
@vitaliy-kuzmich in order for two-way binding to work verify that you have imported `NativeScriptFormsModule ` in the respective `ngModule`

```
import { NativeScriptFormsModule } from "nativescript-angular/forms"
@NgModule({
    imports: [
        NativeScriptModule,
        NativeScriptRouterModule,
        NativeScriptFormsModule, // RIGHT HERE
    ],
})
```

**Comment by vitaliy-kuzmich** [comment]
@NickIliev right, thanks!

**Comment by jamie-pate** [comment]
Also applies to `<SegmentedBar>`

`value` and `oldValue` do seem to work (on SegmentedBar at least), and you can use them to detect splurious events on initialization...
JS: value: 0, oldValue: -1, model.value: 1 (ui initialized to 0, even though the `selectedIndex` property is bound and the bound value is `1` `T_T`
JS: value: 1, oldValue: 0, model.value: 1 (selectedIndex is updated to the model value)

```
<SegmentedBar
    [selectedIndex]="model.value"
    (selectedIndexChange)="onModeChanged($event)">
```
```
    onModeChanged(event: any) {
        const value = 'newIndex' in event ? event.newIndex : event.value,
            oldValue = 'oldIndex' in event ? event.oldIndex : event.oldValue;

        if (oldValue != -1) {
            this.model.value = value;
        }
    }
```

**Comment by medigeek** [comment]
any news on this? there's no point having SelectedIndexChangedEventData  if the data doesn't work

**Comment by edusperoni** [comment]
@medigeek  This had me scratching my head for a while after your comment and it's popped up somewhere else:

https://github.com/NativeScript/docs-new/pull/31

due to how "NativeScript core" (xml) is wired, every time you change a property it emits the event `propertyNameChange`, so if you change `selectedIndex` it emits `selectedIndexChange`. SegmentedBar, TabView and others also emit `selectedIndexChanged` (notice the `d`) which has the correct values your expecting.

In the end all you need is to change `(selectedIndexChange)="tabChanged($event)"` to `(selectedIndexChanged)="tabChanged($event)"`.
