### ISSUE TITLE
Problems with currency pipe

### ISSUE THREAD

**Issue by SparkValor** [NativeScript/nativescript-angular#107]
When I try to use the currency pipe I get the following error:

JS: EXCEPTION: ReferenceError: Intl is not defined in [{{item.price | currency:'GBP':true:'4.0-0'}} in SearchResultsComponent@5:39]
JS: ORIGINAL EXCEPTION: ReferenceError: Intl is not defined
JS: ORIGINAL STACKTRACE:
JS: ReferenceError: Intl is not defined
JS:     at Function.NumberFormatter.format (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/facade/intl.js:22:20)
JS:     at Function.NumberPipe._format (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/common/pipes/number_pipe.js:54:39)
JS:     at CurrencyPipe.transform (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/common/pipes/number_pipe.js:177:27)
JS:     at AbstractChangeDetector.ChangeDetector_SearchResultsComponent_1.detectChangesInRecordsInternal (viewFactory_SearchResultsComponent:234:134)
JS:     at AbstractChangeDetector.detectChangesInRecords (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/core/change_detection/abstract_change_detector.js:104:18)
JS:     at AbstractChangeDetector.runDetectChanges (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/core/change_detection/abstract_change_detector.js:81:14)
JS:     at AbstractChangeDetector._detectChangesContentChildren (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/core/change_detection/abstract_change_detector.js:174:18)
JS:     at AbstractChangeDetector.runDetectChanges (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/core/change_detection/abstract_change_detector.js:82:14)
JS:     at AbstractChangeDetector._detectChangesInViewChildren (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/core/change_detection/abstract_change_detector.js:181:18)
JS:     at AbstractChangeDetector.runDetectChanges (/data/data/com.propertycross.nativescript.PropertyCross/files/app/tns_modules/angular2/src/core/change_detection/abstract_change_detector.js:85:14)

**Comment by hdeshev** [comment]
Unfortunatel,y that one (and several other pipes) aren't supported. To offer support for them, the NativeScript Android and iOS runtimes must support the [ECMA-402](http://www.ecma-international.org/publications/standards/Ecma-402.htm) standard, which is not a small task at all.

We are evaluating several alternatives as well:
- Use a polyfill such as [Intl.js](https://github.com/andyearnshaw/Intl.js/)
- Ship similarly-named versions of the builtin pipes in an extension package.

**Comment by hdeshev** [comment]
Closing this one in favor of #108
