### ISSUE TITLE
tab view, height property touch top margin at the android

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [NativeScript/nativescript-angular#1070]
```
<ActionBar height="20px" class="action-bar">
    <StackLayout orientation="horizontal" ios.position="left" android.position="left">

    </StackLayout>

    <ActionItem ios.position="right" android.position="right" (tap)="showSettings()">
        <Label text="Settings" class="action-item"></Label>
    </ActionItem>
</ActionBar>

<TabView height="30px" minHeight="20px" selectedIndex="2"  [(ngModel)]="tabSelectedIndex" (selectedIndexChange)="tabChanged($event)"
         iosIconRenderingMode="alwaysOriginal" sdkExampleTitle
         sdkToggleNavButton>
   <!-- <StackLayout *tabItem="{title: 'tab.map' | translate}">
        <GridLayout>
            <WebView src="~/home/map.html"></WebView>
        </GridLayout>
        <Label text="First tab item"></Label>
    </StackLayout>-->

    <StackLayout *tabItem="'t1'">
        <Label text="F tab item" ></Label>
    </StackLayout>
    <StackLayout *tabItem="'t2'">
        <Label text="S tab item"></Label>
    </StackLayout>
    <StackLayout *tabItem="'t3'" className="circle" >
        <Label text="T tab item" ></Label>
    </StackLayout>

</TabView>

```

For some reasons, "<TabView height="30px"" put top marginTop=600 as well. In order to fix, there should be added marginTop="-640".  Tested on Android 4.2.2 and 7.1.2

**Comment by tsonevn** [comment]
Hi @vitaliy-kuzmich,
Thank you for contacting us. 
I tested this scenario and to be applied properly the height for the TabView component, you should setup the component inside a StackLayout. Then the height will be calculated properly and this marginTop will not be applied. For Example:
```
<StackLayout>
<TabView height="30px" minHeight="20px" selectedIndex="2"  [(ngModel)]="tabSelectedIndex" (selectedIndexChange)="tabChanged($event)"
         iosIconRenderingMode="alwaysOriginal" sdkExampleTitle
         sdkToggleNavButton>
   <!-- <StackLayout *tabItem="{title: 'tab.map' | translate}">
        <GridLayout>
            <WebView src="~/home/map.html"></WebView>
        </GridLayout>
        <Label text="First tab item"></Label>
    </StackLayout>-->

    <StackLayout *tabItem="'t1'">
        <Label text="F tab item" ></Label>
    </StackLayout>
    <StackLayout *tabItem="'t2'">
        <Label text="S tab item"></Label>
    </StackLayout>
    <StackLayout *tabItem="'t3'" className="circle" >
        <Label text="T tab item" ></Label>
    </StackLayout>

</TabView>
</StackLayout>
```

**Comment by vitaliy-kuzmich** [comment]
@tsonevn thank you for respond, could you please aim me to the example, or information where it is explained in details ?

**Comment by tsonevn** [comment]
Hi @vitaliy-kuzmich,
In our further research, we found that this is something that depends on Android. While setting TabView with specified height without using some of the [Layouts ](https://docs.nativescript.org/ui/layout-containers#stacklayout) provided by NativeScript, the element will be stretched in the center of the screen.
This is default Android behavior and to avoid it you could use StackLayout, which will order the elements from the top of the window. More about the Android layout system and the stretch functionality review the below-attached articles.
https://developer.android.com/guide/topics/ui/declaring-layout.html
http://envyandroid.com/stretching-and-spanning-layouts/
