### ISSUE TITLE
nativescript-camera restart app

### ISSUE THREAD

**Issue by bumbella** [NativeScript/nativescript-angular#1075]
Hi,
I use nativescript-angular
tns info:
│ nativescript     │ 3.3.0           │ 3.3.0          │ Up to date  │
│ tns-core-modules │ 3.3.0           │ 3.3.0          │ Up to date  │
│ tns-android      │ 3.3.0           │ 3.3.0          │ Up to date  │
│ tns-ios          │ 3.3.0           │ 3.3.0          │ Up to date  │

Camera version:
nativescript-camera: "^3.1.3"

I take a picture on android 7.1.1 Nokia 5 phone but the app is restart.
I tested all iphone and Android 6.0.0 HtC Desire 626 Genymotion Android 6.0.0 emulator and code works fine and not restart but Nokia 5 android 7.1.1 crash when take a photo.
The photo not save to gallery when I turn saveToGallery to true.
Terminal send:
```
ActivityManager: Process hu.xxx.xxx (pid 4096) has died
ActivityManager: cleanUpApplicationRecord -- 4096
```

Please help me what is the wrong in my code:
```
let options = { width: 100, height: 100, keepAspectRatio: false, saveToGallery: false };
        takePicture( options )
            .then( picture => {
                console.log("ok")
                //this.cameraImageSrc = picture;
                //this.searchItemsbyPicture(picture);
            }).catch((err) => {
            console.log("Error -> " + err.message);
        });
```

Thanx, Miklos

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-camera#69
