### ISSUE TITLE
Intl (ECMA-402) support and pipes

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#108]
Several of the builtin Angular pipes rely on the `Intl` API which isn't supported by NativeScript.

We have several options:
- Use (and possibly adapt) a polyfill such as [Intl.js](https://github.com/andyearnshaw/Intl.js/)
- Provide alternative implementations for the pipes and ship it in an extension package.
- Build a custom polyfill that exposes the native ICU APIs from Android and iOS.

Pipes affected:
- date
- currency
- number
- percent
- decimal
- ...

/cc @nsndeck @slavchev

**Comment by nsndeck** [comment]
A dedicated plugin [nativescript-intl](https://github.com/NativeScript/nativescript-intl) has been created to mimic Intl.js API and translate it to native devices (uses native ways to format date, time and numbers). NativeScript-intl plugin is added as dependency for NativeScript-Angular, so all built-in pipes that work with date, time and numbers will work out-of-the-box (using native ways for formatting).

**Comment by nmeissner-scottlogic** [comment]
I tried the currency pipe, but it disregards the currency code and always shows USD.

**Comment by hdeshev** [comment]
@nmeissner-scottlogic Angular has its locale [hardcoded](https://github.com/angular/angular/blob/master/modules/angular2/src/common/pipes/number_pipe.ts#L18) to en-US. They will probably add a way to configure that in the future.

**Comment by codeback** [comment]
Hi @hdeshev , now Angular expose LOCALE_ID to set the desired locale. 

In web platform we can do something like this:
```
{provide: LOCALE_ID, useValue: navigator['language'] || navigator['userLanguage'] },
```

How can we get the default language/locale in Nativescript (similar to navigator['language'])?

Thanks in advance.

**Comment by Burgov** [comment]
@hdeshev regardless of the configured locale, if 'EUR' is passed into the pipe, it shouldn't yield 'USD'. E.g.:

`<Label [text]="5|currency:'EUR'"></Label>` renders as `USD5`. Is there some workaround for this?
