### ISSUE TITLE
 WebService Consumption

### ISSUE THREAD

**Issue by joaovictorpsantos** [NativeScript/nativescript-angular#1082]
Hello, I am a beginner in NativeScript and I have a project in development where I need to consume webservice, for information manipulation (input and output), but I'm kind of lost because I'm a beginner, I do not know where to start or how.

So I wanted the help of someone who can tell me the best way to make this connection and how to do it, or if possible indicating any articles that will contribute.

Thank you !

**Comment by tsonevn** [comment]
Hi @joaovictorpsantos,
Thank you for your interest in NativeScript.
In your case, I would suggest reviewing our [getting started tutorial](https://docs.nativescript.org/angular/tutorial/ng-chapter-1) , where are described all the best practices while developing a NativeScirpt Angular application.
Please for any further questions use our NativeScript [forum ](https://discourse.nativescript.org/) or [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by joaovictorpsantos** [comment]
Thank you very much !
