### ISSUE TITLE
Can Nativescript get rid of moduleId (deprecated)

### ISSUE THREAD

**Issue by PurpleEdge2214** [NativeScript/nativescript-angular#1083]
`moduleId: module.id`

...has be deprecated in Angular 4.

https://angular.io/guide/change-log

...can Nativescript be updated accordingly as it seems to be causing problems...

https://discourse.nativescript.org/t/relative-vs-absolute-template-paths-when-using-webpack-build/1516

**Comment by NickIliev** [comment]
Resolved with the latest nativescript-angular where the projects are no longer using module.id.

```
moduleId: __filename,`
``

**Comment by DeepakArora76** [comment]
How did you get rid of module.id?  I have Angular 7.1.4 and "nativescript-angular": "~7.1.0".

**Comment by NickIliev** [comment]
@DeepakArora76 are you making a Webpack build? Currently removing `moduleId` would work when passing `--bundle` (using Webpack)

```
tns run android --bundle
```

Here is a sample application that works without `moduleId` (but with Webpack builds)

**Comment by DeepakArora76** [comment]
Yeah - it is a Webpack based build, and the command line option `--bundle` solves the problem. Thank you for the reply.
