### ISSUE TITLE
Don't compile with 'angular2-token' package

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1084]
_From @betosalvador on November 9, 2017 16:13_

## Please, provide the details below:
Hello, I'm trying to use the 'Angular2-Token' package in my nativescript app, but its doesn't compile.

I'm getting this error bellow:

```
Preparing project...
Project successfully prepared (Android)
Successfully transferred app.routing.ts.
Successfully transferred app.routing.js.
Refreshing application...
Successfully synced application org.nativescript.testeangular2token on device 192.168.128.101:5555.
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err: Error calling module function
System.err: Error calling module function
System.err: Error calling module function
System.err: Error calling module function
System.err: Cannot compile /data/data/org.nativescript.testeangular2token/files/app/tns_modules/angular2-token/lib/angular2-token.service.js
System.err: SyntaxError: Unexpected token import
System.err: File: "file:///data/data/org.nativescript.testeangular2token/files/app/tns_modules/angular2-token/lib/angular2-token.service.js, line: 1, column: 60
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.testeangular2token/files/app/tns_modules/angular2-token/angular2-token.js', line: 5, column: 10
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.testeangular2token/files/app/app.routing.js', line: 7, column: 24
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.testeangular2token/files/app/app.module.js', line: 5, column: 21
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.testeangular2token/files/app/main.js', line: 5, column: 20
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:530)
System.err:     at com.tns.Runtime.run(Runtime.java:522)
System.err:     at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
System.err:     ... 9 more

```

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.1
- Cross-platform modules: (package.json)
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.testeangular2token",
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.4.1",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "angular2-token": "^0.2.0-beta.12",
    "nativescript-angular": "~4.4.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "~3.2.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.5.0",
    "typescript": "~2.4.2"
  }
}
```

### Please tell us how to recreate the issue in as much detail as possible.
1- Generate a new tns app with ng template
2- Install angular2-token package (npm install angular2-token --save)
3- Add 'Angular2TokenService' to AppModule providers arrary
4- Run app (tns run android)

THanks in advance

_Copied from original issue: NativeScript/NativeScript#5056_

**Comment by tsonevn** [comment]
_From @jogboms on November 9, 2017 16:28_

@betosalvador It appears the plugin still contains ES6 code.

**Comment by tsonevn** [comment]
_From @betosalvador on November 9, 2017 17:44_

Hello, @jogboms 

thanks for response.

Can you give a tip how to fix this?

thanks in advance

**Comment by tsonevn** [comment]
Hi @betosalvador
Thank you for your interest in NativeScript.
I reviewed your case, however, at this time `angular2-token` is not supported.
Regarding that, it would help if you could provide some more info about your scenario and the needed functionality.

**Comment by betosalvador** [comment]
Hello @tsonevn .

Thanks for response.

I have a rails api application that uses 'DeviseTokenAuth' gem.

This gem works perfectly with "angular2-token", because this gem implements a lot of things, like 'SignUp', 'SignIn', 'AccountUpdates', 'TokenControl', etc., and the 'angular2-token' has a service class done to use this functionalities.

I am already using this 'angular2-token' package in my angular frontend project.

It would be great if I could use it on my nativescritp project as well.

I think every community would benefit.

THanks in advance.

**Comment by jogboms** [comment]
@betosalvador The thing is, getting it to work directly in {N} may not be as straight-forward and would require some input from the developer. Also to note that the {N} environment is slightly different from the Web environment and not all of its API is available here.

**Comment by betosalvador** [comment]
Hello @jogboms .
thanks for reponse.

If anyone need inputs, I can help with it.

I understand that is not a priority for now.

But, anyway, thanks!

**Comment by tsonevn** [comment]
Hi @betosalvador,
I think that this is a perfect candidate for a new plugin, which implements similar functionality like this is `angular2-token` plugin. 
Regarding that, I would suggest reviewing this article [here](https://docs.nativescript.org/plugins/building-plugins), where it is described, how to create a NativeScript plugin and for starting point you could use [nativescript-plugin-seed](https://github.com/NativeScript/nativescript-plugin-seed).

**Comment by betosalvador** [comment]
Hello

thanks for response

I will try this solution!

👍

**Comment by rodrigosantiag** [comment]
I know I'm late, but anyone have seen this? https://github.com/costanonato/ns-angular2-token
