### ISSUE TITLE
FontAwesome icons dissapear after ListView scroll

### ISSUE THREAD

**Issue by valera1401** [NativeScript/nativescript-angular#1086]
Hi everyone!

I have a simple ListView with FontAwesome icons.
```
<ListView [items]="itemList">
    <ng-template let-record="item">
        <GridLayout columns="*">
            <Label [text]="record.icon" class="fa" fontSize="35"></Label>            
        </GridLayout> 
    </ng-template>
</ListView>
```

After the ListView scroll some icons dissapear.

Before scroll:
![image](https://user-images.githubusercontent.com/33029076/32701820-0babf210-c7e5-11e7-847c-4e65f772d176.png)

After scroll:
![image](https://user-images.githubusercontent.com/33029076/32701822-149d88ca-c7e5-11e7-9173-33c27bf65947.png)

**Comment by tsonevn** [comment]
Hi @valera1401,
I tested your case on my side, however, was unable to recreate this behavior.
For your convenience I am attaching sample project, please review it and make the needed changes, which will allow us to recreate the problem.
![screencast 2017-11-13 at 1 03 06 pm](https://user-images.githubusercontent.com/17448734/32722822-d466c5e8-c873-11e7-8731-ccdb3f8daf1b.gif)
![screencast 2017-11-13 at 1 07 57 pm](https://user-images.githubusercontent.com/17448734/32722823-d4878210-c873-11e7-8128-cf716863eea2.gif)

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1466564/Archive.zip)

**Comment by valera1401** [comment]
Thank you for your response.

I have found the reason.
It was wrong style, which cause so strange behavior.

label {
horizontal-align: center;
}
