### ISSUE TITLE
NativeScript usage of the new HttpClient - causes error?

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-angular#1087]
Currently I have a working app (Groceries app):

 [_Using this app.module.ts file_][1]

Where [this is how I use the (old) `Http`  module][2] : 

(Although it's working) - Webstorm doesn't recognize it ( since `Http` is old): 

![image](https://user-images.githubusercontent.com/2842123/32726306-2fa425b0-c881-11e7-8dfa-1a797c937b17.png)

So  I've changed `app.module.ts` to use the new `HttpClient` : 

via : 

    import {HttpClient, HttpHeaders} from "@angular/common/http";

![image](https://user-images.githubusercontent.com/2842123/32726427-ac69c7a8-c881-11e7-9c82-00d8aaaf57b8.png)

 - Then I get this exception : 
```
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onActivityResumed failed
System.err: 
System.err: **Error: Trying to link invalid 'this' to a Java object**
System.err: File: "file:///data/data/org.nativescript.Groceries/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js, line: 266, column: 35
System.err: 
System.err: StackTrace: 
```

Full error (in console) is [**here**][3] : 
 

**Question**

How can I fix my code  not to show this error  ? 

[Here is the package.json file][4]

  [1]: http://jsbin.com/femofufeta/edit?html
  [2]: http://jsbin.com/norujoxenu/edit?html
  [3]: http://jsbin.com/gecagaduwe/edit?html
  [4]: http://jsbin.com/sifinuyibu/edit?html,output

**Comment by tsonevn** [comment]
duplicated with issue [#1085](https://github.com/NativeScript/nativescript-angular/issues/1085)

**Comment by RoyiNamir** [comment]
@tsonevn FYI : https://stackoverflow.com/a/47243712/859154
this fixed the error ( for now)
