### ISSUE TITLE
Feature request: Set title with ActionBarExtension

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-angular#1090]
Hi,

`ActionBarExtension` lets us change the `ActionItem` and `NavigationButton` on the page from our components.
It would also be great to be able to change the page-title in the same way.

Something like:
```html
<ActionBarExtension title="New Title"></ActionBarExtension>
```

**Comment by NickIliev** [comment]
Closing this one due to inactivity.

As a side note not so sure if that is needed functionality - if you need to overwrite the current action bar title you can achieve that with binding. Also if the `ActionBarExtension` overwrites the whole `ActionBar` it would break its main idea
