### ISSUE TITLE
Upgrading to Angular 5.0.0 causes animation-driver.js crash

### ISSUE THREAD

**Issue by souly1** [NativeScript/nativescript-angular#1091]
So...
I've tried to upgrade to angular 5.0.0 and after the regular hiccups the app loads up but throws the attached exception causing the app to not work. Any idea when you'll get to implement and release this?
Thanks

ERROR Error: Uncaught (in promise): Error: Not implemented!
JS: Error: Not implemented!
JS:     at NativeScriptAnimationDriver.validateStyleProperty (file:///data/data/org.project.project/files/app/tns_modules/nativescript-angular/animations/animation-driver.js:49:15) [angular]
JS:     at file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:1159:36 [angular]
JS:     at Array.forEach (native) [angular]
JS:     at file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:1158:32 [angular]
JS:     at Array.forEach (native) [angular]
JS:     at AnimationAstBuilderVisitor._validateStyleAst (file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:1155:20) [angular]
JS:     at AnimationAstBuilderVisitor.visitStyle (file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:1075:14) [angular]
JS:     at AnimationAstBuilderVisitor.visitState (file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:923:46) [angular]
JS:     at file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:892:39 [angular]
JS:     at Array.forEach (native) [angular]
JS:     at file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:890:41 [angular]
JS:     at Array.forEach (native) [angular]
JS:     at AnimationAstBuilderVisitor.visitTrigger (file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:885:30) [angular]
JS:     at visitDslNode (file:///data/data/org.project.project/files/app/tns_modules/@angular/animations/bundles/animations-browser.umd.js:674:28) [angular]

**Comment by sis0k0** [comment]
Angular Animations are not yet updated to support Angular 5. tracking issue: #1073
