### ISSUE TITLE
ActionBar displaying on webpack angular compilation

### ISSUE THREAD

**Issue by miguelcostero** [NativeScript/nativescript-angular#1096]
Hello there,

I wanted to my app to be faster, so for that I follow the steps described here [https://docs.nativescript.org/best-practices/startup-times](https://docs.nativescript.org/best-practices/startup-times), everything works fine, but I disabled on the app bootstrap (main.ts) the action bar displaying:

`
platformNativeScriptDynamic({
  startPageActionBarHidden: true
}).bootstrapModule(AppModule);
`

When I run `tns run android` the action bar **is not displayed as I wanted**, but when I run `npm run start-android-bundle --uglify --snapshot` **is displayed**.

I don't know what could cause these. Do you have any idea?

Thank you very much.

**Comment by tsonevn** [comment]
Hi @miguelcostero,
Thank you for reporting this issue.
I tested this case on my side and I have to confirm that this is a real issue.  The ActionBar component will be rendered, while `startPageActionBarHidden` is set to false and the app is built with `webpack`.
I am attaching sample project, which could be used for debugging.
For further info, please keep track on the issue.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1505095/Archive.zip)

**Comment by tsonevn** [comment]
Hi @miguelcostero,
Could you check if have set up the startPageActionBarHidden  to false in the main.aot.ts file in the project. For example
```
platformNativeScript({ startPageActionBarHidden: true }).bootstrapModuleFactory(AppModuleNgFactory);
```
This is needed while the webpack techink is used.
