### ISSUE TITLE
card emulation

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/nativescript-angular#1104]
is any plugin for https://developer.android.com/guide/topics/connectivity/nfc/hce.html ?
thx for advance.

**Comment by tsonevn** [comment]
Hi @Nurgunkalol,
I have researched your case and found that there is a plugin, which provides support for `NFC Tag Reading` called nativescript-nfc. Regarding that, you could review the plugins [repository ](https://github.com/EddyVerbruggen/nativescript-nfc) and verify, if it is applicable to your case.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#5109
