### ISSUE TITLE
Floating button on all views? 

### ISSUE THREAD

**Issue by mpochron** [NativeScript/nativescript-angular#1111]
```
@Component({
    selector: "app",
    template: '
    <FrameLayout>
        <page-router-outlet></page-router-outlet><floating-button></floating-button>
    </FrameLayout>',
})
export class AppComponent {}
```

After new route (changing to new view) floating button has been hidden. I was debugging with tool GUI View (Android Device Monitor), also FrameLayout and FloatingButton were there, after that they are lost.

Element FrameLayout is made of class Layout with android view FrameLayout.
Element FloatingButton is just made component with buttons. 

Please help, it's is very important to me. I spent 20 hours on that like crazy to find solution.

**Comment by NickIliev** [comment]
@mpochron not sure about the custom implementation behind FrameLayout and floating-button but you can easily achieve floating layout functionality by using [nativescript-floatingactionbutton plugin](https://github.com/bradmartin/nativescript-floatingactionbutton). 

Or if you need something like fixed toolbar you can even use [DockLayout ](https://docs.nativescript.org/angular/code-samples/ui/layouts#dock-layout)(example [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/apod.component.html#L11-L13))

In both cases, it might be a good idea to navigate inside page-router-outlet and then create router-outlet for the main content and dock the floating button relative to the router-outlet.

Side note: please post a how-to related question in the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/) or slack so we could keep this repository strictly for logging issues, bugs and feature request related to nativescript-angular. In  the community channels

**Comment by mpochron** [comment]
@NickIliev 
DockLayout or nativescript-floatingactionbutton aren't solution for me, because they have to be placed inside router. Must be on top of all views. 

Please reopen.
