### ISSUE TITLE
Question - Can I restart or reload app when push notification receive handler?

### ISSUE THREAD

**Issue by bumbella** [NativeScript/nativescript-angular#1112]
Can Is restart or reload app with Native script angular?
I want to go to route when notification receiv and app is running but in notification received event I cant get route extensions.navigation. I think because this code is before bootstrap.
Anybody can help me?

```
public static notificationReceived(notification: com.onesignal.OSNotification) {
        alert(notification.payload.title);
        reload or restart app
        //body: notification.payload.body,
        //data: OneSignalAndroid.parseJson(notification.payload.additionalData),
    }
```

**Comment by NickIliev** [comment]
@bumbella, please post how-to related questions in the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/) so we could keep this repository clean and for logging issues, bugs and feature request related to nativescript-angular.

Regarding your question: Not sure which plugin you are using to receive push notifications but all of them usually comes with functionality to implement the messageReceived callback anywhere in your application 

For example (based on nativescript-plugin-firebase)
```
// add the fierbase addOnMessageReceivedCallback where your business logic requres it
firebase.addOnMessageReceivedCallback(
    function(message) {
      // .. navigate to the start pointof your applicaiton here
    }
  );
```
