### ISSUE TITLE
Getting error for TNS RUN ANDROID

### ISSUE THREAD

**Issue by shaileshkadam25** [NativeScript/nativescript-angular#1117]
Error Message - Unable to apply changes on device: XXXX. Error is: TypeScript compiler failed with exit code 3221225477.

Please find attached file for more into

![image](https://user-images.githubusercontent.com/34359368/33748539-25c667f0-db97-11e7-9e3f-211197db0325.png)

**Comment by NickIliev** [comment]
@shaileshkadam25 can you provide the `package.json` content of your application.
Try using this versi0ons of TypeScript and nativescript-dev-ttypescript and then rebuilding your project with reset node_modules and platforms folders.
```
"nativescript-dev-typescript": "~0.5.0",
"typescript": "~2.4.2"
```

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#3254

**Comment by shaileshkadam25** [comment]
[package.txt](https://github.com/NativeScript/nativescript-angular/files/1550145/package.txt)
[package-lock.txt](https://github.com/NativeScript/nativescript-angular/files/1550146/package-lock.txt)
[tsconfig.txt](https://github.com/NativeScript/nativescript-angular/files/1550147/tsconfig.txt)


@NickIliev, i have upgraded to latest version on NPM but still getting same error. please find below screenshot and attachd package.json, package-lock.json and tsconfig.json files

![image](https://user-images.githubusercontent.com/34359368/33865914-e42188c4-dec1-11e7-8ac9-d05cd3773e5a.png)

**Comment by charlbarrera** [comment]
I have de same thing, I try to update all versions, but I don´t have solutions for this error

**Comment by ramasas** [comment]
@charlbarrera @shaileshkadam25 
I had the same problem before.

This is resolved by editing 
[Project Path]\node_modules\nativescript-dev-typescript\lib\compiler.js
Line 28 > var nodeArgs = ['--max_old_space_size=4096', tscPath, '--project', projectDir];

After changing 4096 to 2048, the problem's gone.
(i.e. var nodeArgs = ['--max_old_space_size=2048', tscPath, '--project', projectDir];)

I don't know why it works that way.
Hope this helps people having the same issue.

**Comment by phatakrajan** [comment]
@ramasas After wasting entire day in installing and reinstalling Node, Typescript finally your solution saved me. However what is the root cause? Just to share the information, this error was coming only on my 32 bit system and no other 64 bit system where i build was giving this error. Anything related to it?

**Comment by ramasas** [comment]
@phatakrajan Yes! I do think it is related.  I encountered many similar errors when trying React Native, plain NativeScript and NativeScript+Angular with my 32-bit Windows.  The tutorials for starters should give people a hint about this.

**Comment by arumuganainar73** [comment]
@ramasas 
Thanks you so much!!
The problem's gone
