### ISSUE TITLE
ListView loadMoreItems event is called continuously

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-angular#1118]
When ListView size is smaller than screen size, it fires loadMoreItems event continuously.

I have this template:

````xml
<grid-layout rows="*">
    <ListView [items]="tasks" (loadMoreItems)="loadMore()" class="bordered" row="0">
			<!-- Template is here -->
    </ListView>
    <FAB row="0 icon="res://ic_add_white_24dp" rippleColor="#c0d0e0" class="fab-button"></FAB>
</grid-layout>
````
When listview content is longer than screen size, there is no problem.
If I scroll to the bottom and there is new content, it is loaded and there is no problem.
If I scroll to the bottom and there is no new content, listview stays scrolled to the bottom and always fires loadMoreItems event.
If listview content is shorter than screen size, loadMoreItems event is always fired.

Right now, I will try to fix this by adding a flag to my code but it would be nice if this is fixed in the repository.

**Comment by tsonevn** [comment]
Hi @erkanarslan,
Thank you for reporting this issue. 
I tested this case on my side and was able to recreate some odd behavior with not properly firing `loadMoreItems` event in none angular project, while there are just a few items. 
I will log this as a bug and in the meantime, you could review [load on demand ](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/ListView/load-on-demand) functionality provided by RadListView component and to verify if using this component is applicable to your case. 

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1547162/Archive.zip)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#5155

**Comment by erkanarslan** [comment]
@tsonevn RadListView removes the ripple effect from list items. Because of that I don't use it if I don't have to. Now I fixed it like that: I set a flag to true if there is no new content and don't request more content if that flag is set.
