### ISSUE TITLE
Support for active link/route with NSRouterLink

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#112]
It would be great to have active state support for `NSRouterLink`. I didn't see an example of this here:
https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/navigation/navigation-test.ts

And doesn't look like it's supported yet here:
https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/router/ns-router-link.ts

Something like this:
https://github.com/angular/angular/blob/75343eb34007579be9cdc803da834c38e02ae12c/modules/angular2/src/router/directives/router_link.ts#L43

I can look into a PR for this unless someone else knows how to support this easily (maybe quicker).

**Comment by vakrilov** [comment]
The NSRouterLink is really similar to the original [router-link directive](https://github.com/angular/angular/blob/master/modules/angular2/src/router/directives/router_link.ts) from the Angular2 repo. The main difference is that it subscribes to the `tap` event, instead of `click`. If you want to try implementing `isRouteActive` - go ahead :)

**Comment by matt4446** [comment]
I'm off to Ireland in a couple of days till Monday. But I'll certainly be looking into this next week if it hasn't been solved by anyone.

**Comment by matt4446** [comment]
@NathanWalker you may also like: 
https://github.com/angular/angular/pull/6407/files

As for some testing my side i cant seem to ever get isRouteActive to ever be true. :-/ 
Change detection seems to go abit crazy as well particularly after navigation. I'm too ill to look more closely right now.

**Comment by NathanWalker** [comment]
Thanks @matt4446 this has been on a list but I haven't gotten to it yet. Appreciate you giving it a go!

**Comment by shangab** [comment]
Well, I want to read the params that are passed to this page with : [nsRouterLink]="/dosomething/:funky/:city"

How do I read it in the navigated to page ??
