### ISSUE TITLE
implement angular ViewChildren on ListView to get the instance of child component per item  

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1120]
_From @XoronEdge on December 10, 2017 10:34_

on tap per item to show more detail 
But viewchildren userdetail variable have nothing  But child component view is display
![screenshot from 2017-12-10 10-34-19](https://user-images.githubusercontent.com/32927728/33804098-c1787fee-dd95-11e7-9b60-898bcd5cb7ca.png)

# **child component.ts** # 

```
import { Component, Input} from "@angular/core";

@Component({
	selector:"user-some-detail",
	templateUrl:"./pages/some-detail/user-some-detail.page.html"
})
export class UserSomeDetail {

	@Input("item")item:any;
	private canShowMore:boolean;

	public constructor() {
		this.canShowMore = true;
	}
	public setShowMore(value: boolean) {
		this.canShowMore = value;
	}
}
```
# child view
```
<StackLayout>    			
	<Label text='User'></Label>
        <StackLayout *ngIf="canShowMore">
        	<Label [text]="item.name"></Label>
        	<Label [text]='item.age'></Label>	
        </StackLayout>
</StackLayout>

```
# Parent ts
```
import { Component, ViewChildren, QueryList, AfterViewInit }  from "@angular/core";

import { UserSomeDetail } from "../../pages/some-detail/user-some-detail.page";

class User {
	public constructor(public name: string, public age: number) {
	}
}

@Component({
	selector: "user-list",
	templateUrl: "./pages/user-list/user-list.page.html"
})
export class UserList implements AfterViewInit{
	@ViewChildren(UserSomeDetail) userdetail:QueryList<UserSomeDetail>;
	public users: Array<User>
	
	public constructor() {
		this.users = [];
		for(let i = 0; i <= 10; i++) {
			this.users.push(new User("lala"+i, i));
		}
	}

	public ngAfterViewInit() {
		//for testing use console
		console.log(this.userdetail);
		this.userdetail.forEach(ins => ins.setShowMore(true));
	}
	
	public onItemTap(args) {
	}
	
}
```
# Parent view
```
<Page>
	 <ListView [items]="users" (itemTap)="onItemTap($event)">
    	<ng-template let-item="item" let-i="index" >
    		<user-some-detail [item]="item"></user-some-detail>
    	</ng-template>
	</ListView>
</Page>
```

_Copied from original issue: NativeScript/NativeScript#5153_

**Comment by tsonevn** [comment]
Hi @XoronEdge,
Thank you for contacting us.
We reviewed your case, however, it would help if you provide some more info about your case and why you need to access the child elements while using the `ViewChildren`? It would also help if you also provide info about what you are would like to achieve as a final result after you get the instance for all items?
Thank you in advance for your cooperation.

**Comment by XoronEdge** [comment]
when we tap on User it show more detail about user in same view as child component so when user tap on User or per item.The list view function onItemTap change the the property 'canShowMore' of child component to true .so i need the instance of child component in parent component.child view you see in stacklayout i use ngif="canShowMore".OnTap it become true and show userdetail

**Comment by tsonevn** [comment]
Hi @XoronEdge,
In case you need to show some content dynamically in the ListView item cell, you could set up the value for the ngIf directive for every element via bindingContext.
On item tap event you could change the visibility of the taped item. Keep in mind that the ListView's refresh method should be called after those changes. This will allow the changes with the visibility to be applied. 

For your convenience, I am attaching sample project, where the above-given suggestions are demonstrated. 
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1550872/Archive.zip)
