### ISSUE TITLE
Background color not working in {N} modal page in iOS

### ISSUE THREAD

**Issue by relvis** [NativeScript/nativescript-angular#1122]
Hi there, I just noticed that if I set a modal view to `fullscreen: false` and the background color to `rgba(0,0,0,0.4)` it gets a solid color instead of semi-transparent color. Is there any issue or maybe an extra code for iOS?

Thanks!

**Comment by tsonevn** [comment]
Hi @relvis,
You could review this thread [here](https://github.com/NativeScript/nativescript/issues/2086#issuecomment-221956483), where it is described, how to make modal page with transparent background color in iOS.

Also keep in mind that by [design on iPhone](https://docs.nativescript.org/core-concepts/navigation#modal-pages), a modal page appears only in fullscreen.
