### ISSUE TITLE
Issue on dynamically render the views inside Listview in landscape mode

### ISSUE THREAD

**Issue by kumaran-dena** [NativeScript/nativescript-angular#1130]
I was trying to create set of template(components) dynamically using Listview in nativescript angular application. It works as expected in portrait mode. If i tried to add components on click of some icon with landscape mode means then i got encountered with errors. 

**ListView code -** 
`

				<GridLayout row="1" sdkExampleTitle sdkToggleNavButton>
					<ScrollView>

						<ListView [items]="nfrepeat" (itemTap)="onItemTap($event)">
							<ng-template let-nfadd="item" let-i="index" let-odd="odd" let-even="even">

								<GridLayout [id]="i" class="newfindbody" rows="auto,auto,auto,auto,auto,auto" columns="*,30,*,30,30,30">

									<TextField class="input input-border" [text]='nfadd.category' hint="Category" row="0" col="0" colSpan="1"></TextField>
									<TextField class="input input-border" [text]='nfadd.ismcode' hint="ISM Code" row="0" col="2" colSpan="1"></TextField>
									<label text="&#xf1f8;" class="fa" row="0" col="4" (tap)="onItemdel(i)"></label>
									<label text="&#xf13a;" class="fa" row="0" col="5"></label>
									<TextView class="input input-border" [text]="nfadd.ismelement + i" hint="ISM Element" height="70" row="1" col="0" colSpan="6"></TextView>

									<TextField class="input input-border" [text]='nfadd.ncategory' hint="Category" row="2" col="0"></TextField>
									<Label text="&#xf150;" class="fa" row="2" col="1"></Label>
									<TextField class="input input-border" [text]='nfadd.status' hint="Status" row="2" col="2"></TextField>
									<Label text="&#xf150;" class="fa" row="2" col="3"></Label>

									<TextField class="input input-border" [text]='nfadd.statusdate + i' hint="Status Date" row="3" col="0"></TextField>
									<Label text="&#xf073;" class="fa" row="3" col="1"></Label>
									<TextField class="input input-border" [text]='nfadd.nextaction' hint="Next Action" row="3" col="2"></TextField>
									<Label text="&#xf150;" class="fa" row="3" col="3"></Label>

									<TextField class="input input-border" [text]='nfadd.duedate' hint="Due Date" row="4" col="0"></TextField>
									<Label text="&#xf073;" class="fa" row="4" col="1"></Label>
									<TextView class="input input-border" [text]='nfadd.description' hint="Description" row="4" col="2" colSpan="6"></TextView>
									<StackLayout row="5" col="0" colSpan="6" class="newfindbodyattach">
										<GridLayout class="nfattachouterstack" width="100%" rows="auto, auto" columns="30,*,*,*" orientation="horizontal">
											<Label class="fa" text="&#xf0c6;" color="black" row="0" col="0" horizontalAlignment="center" paddingtop="5" paddingleft="5"
											 margintop="10"></Label>
											<Label text="File Name" row="0" col="1" horizontalAlignment="center" padding="10 20"></Label>
											<Label text="Download" row="0" col="2" horizontalAlignment="center" padding="10 20"></Label>
											<Label text="Action" row="0" col="3" horizontalAlignment="center" padding="10 20"></Label>
											<GridLayout class="nfinnerattachfiles" row="1" col="0" colSpan="4" rows="auto" columns="*,*,*" orientation="horizontal">
												<Label text="filname" row="0" col="0" horizontalAlignment="center"></Label>
												<Label class="fa" text="&#xf019;" row="0" col="1" horizontalAlignment="center"></Label>
												<Label class="fa" text="&#xf1f8;" row="0" col="2" horizontalAlignment="center"></Label>
											</GridLayout>
										</GridLayout>
									</StackLayout>
								</GridLayout>

							</ng-template>
						</ListView>

					</ScrollView>
				</GridLayout>`

And here is my playground link [demo-app](https://play.nativescript.org/?template=play-ng&id=Lka9jr&v=3) which will be help to reproduce the issue. 

Thanks!

**Comment by NickIliev** [comment]
@kumaran-dena please clarify if the issue is happening on iOS or on Android.
I have tried to reproduce your case but was not entirely sure how to handle the provided UI.

Please keep in mind that you will find better support for how-to related questions in our community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/) or [SO](https://stackoverflow.com/questions/tagged/nativescript) and in the same time we can keep the repository clean for login issues, bugs and features related to nativescript-angular.

You can also contact me on the community slack channel to clarify the issue so I can test it on my side.
(username: **nikl_iliev**)
