### ISSUE TITLE
webview: page is not adaptive

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/nativescript-angular#1135]
Hello!
Im working with webview of page. Page doesnt show correct (css problems) on webview, but in browser and with plugin 'https://github.com/bradmartin/nativescript-advanced-webview' is working fine. 
thx for advance

**Comment by NickIliev** [comment]
@Nurgunkalol what is the actual issue you are facing?

It seems that using the plugin [nativescript-advanced-webview](https://github.com/bradmartin/nativescript-advanced-webview) is resolving the issue so we can thread this one as a feature request for the core WebView. Closing as the provided information is not enough.
