### ISSUE TITLE
NullInjectorError: No provider for Http!

### ISSUE THREAD

**Issue by briandilley** [NativeScript/nativescript-angular#1138]
Upgraded some libraries and now i get this error:
```
StaticInjectorError[Http]:
  StaticInjectorError[Http]:
    NullInjectorError: No provider for Http!
```

here's my `app.module.js`, you'll see that `NativeScriptHttpModule` is imported as expected:
```
import {NgModule, NO_ERRORS_SCHEMA} from "@angular/core";
import {NativeScriptModule} from "nativescript-angular/nativescript.module";
import {NativeScriptFormsModule} from "nativescript-angular/forms";
import {NativeScriptHttpModule} from "nativescript-angular/http";

import {
  DeviceService,
  DirectionsService,
  ParamsService,
  ShuttleRideService,
  ShuttleService,
  StationService
} from "@suna/quickride-ts-libcore";

import {
  ActionBarLarge,
  AppRoutingModule,
  ConnectionInfo,
  ConnectivityService,
  EnRoutePage,
  LocationService,
  LoginPage,
  NotificationHandler,
  RideListItem,
  RideListPage,
  RouterData,
  ShuttleListItem,
  ShuttleListPage,
  TaskPage
} from "./quickride";

import {AppComponent} from "./app.component";

@NgModule({
  bootstrap: [AppComponent],
  imports: [
    NativeScriptModule,
    NativeScriptFormsModule,
    NativeScriptHttpModule,
    AppRoutingModule
  ],
  declarations: [
    ActionBarLarge,
    RideListItem,
    ShuttleListItem,
    NotificationHandler,
    ConnectionInfo,
    AppComponent,
    LoginPage,
    ShuttleListPage,
    RideListPage,
    EnRoutePage,
    TaskPage
  ],
  providers: [
    RouterData,
    DirectionsService,
    ShuttleService,
    ShuttleRideService,
    StationService,
    DeviceService,
    LocationService,
    ConnectivityService,
    ParamsService
  ],
  schemas: [
    NO_ERRORS_SCHEMA
  ]
})
export class AppModule {

}

```

**Comment by tsonevn** [comment]
Hi @briandilley,
Could you try replacing the old `nativescript-angular/http` module with the `nativescript-angular/http-client`? The http-client is introduced with the latest versions of Angular and it is upgraded version of http. More about it could be found here in the [Angular docs](https://angular.io/guide/http).

Also, you could review our example [here ](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/http) where it is used the http-client module.

In case the problem still persists, please provide sample project, which could be debugged locally.

**Comment by somayaji1983** [comment]
Hi, I am getting the same problem. Here is my app.module.ts and app.component.ts
app.module.ts
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { SpeechRecognition } from "nativescript-speech-recognition";
import { AppComponent } from "./app.component";
import { EventData, PropertyChangeData } from 'data/observable';
import { Page } from 'ui/page';
import { NativeScriptHttpClientModule } from "nativescript-angular/http-client";

@NgModule({
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  imports: [NativeScriptModule,NativeScriptHttpClientModule],
  providers: [SpeechRecognition],
  schemas: [NO_ERRORS_SCHEMA],
})
export class AppModule {}


app.component.ts

import { Component } from "@angular/core";
import { SpeechRecognition, SpeechRecognitionTranscription, SpeechRecognitionOptions } from "nativescript-speech-recognition";
import { EventData, PropertyChangeData } from 'data/observable';
import { Page } from "ui/page";
import { TextView } from "ui/text-view";
import { Switch } from "ui/Switch";
import { MyHttpGetService } from "./httpmodule/httpservice";

@Component({
  selector: "my-app",
  templateUrl: './appview.html',
  providers: [MyHttpGetService]
})

export class AppComponent {
 
  options: SpeechRecognitionOptions;
  public textvalue: string = "Say some thing..."  
  public led_visibility : string = "hidden";
  public ledhttplink : string = "http://192.168.1.101:8080/"

  public LedSwitchState : string;
  public sendColor : string;

  constructor(private speech: SpeechRecognition, private page: Page,private myService: MyHttpGetService){



I have pasted till constructor as I am getting error when the objected added to it. if I remove it is working find.

This is the error
JS: ERROR Error: No provider for MyHttpGetService!
JS: ERROR CONTEXT [object Object]
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: No provider for MyHttpGetService!

Please help

**Comment by tsonevn** [comment]
Hi @somayaji1983,
Make sure that you have made your service component injectable as it shown [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/http/http-get/http-get.services.ts#L8) in nativescript-sdk-examples-ng. 

Also, it would help if you send us sample project, which could be used for debugging and more info about your environment(CLI modules, runtime, nativescript-angular versions)

**Comment by WrightTrae** [comment]
> Hi @somayaji1983,
> Make sure that you have made your service component injectable as it shown [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/http/http-get/http-get.services.ts#L8) in nativescript-sdk-examples-ng.
> 
> Also, it would help if you send us sample project, which could be used for debugging and more info about your environment(CLI modules, runtime, nativescript-angular versions)

Hey, @tsonevn that link is throwing a 404 now, do you mind giving us a new link for the ng injection example?

**Comment by tsonevn** [comment]
Hi @WrightTrae,
You can find the example [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ng-framework-modules-category/http)
