### ISSUE TITLE
`Invalid or unexpected token` when `tns generate component`

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-angular#1143]
I'm using the latest webstorm with latest node and latest npm

When I create a "generate component" - I get an error : 

![image](https://user-images.githubusercontent.com/2842123/34435382-ccccbe50-ec95-11e7-92ed-94bdc414415f.png)

If I try doing it manually in cmd  : 

![image](https://user-images.githubusercontent.com/2842123/34435390-df118672-ec95-11e7-85c6-7d26e9f15a49.png)

Worth to mention  : 

```
C:\Users\sff\WebstormProjects\rpstrackersnsng>npm list -g --depth=0
C:\Users\sff\AppData\Roaming\npm
+-- nativescript@3.3.1
+-- nativescript-angular-cli@0.1.9
+-- timeline-view@0.0.6
+-- typescript@2.6.1
`-- webpack@3.8.1
```

Also worth to mention that  this command does work : 

```
C:\Users\sff\WebstormProjects\rpstrackersnsng>tns generate component "asd"
Prepared classifiedName: Asd dasherizedName: asd
Asd component has been created.
```

SET PATH variables : http://jsbin.com/cubumabeje/1/edit?html

**Comment by NickIliev** [comment]
Closing as duplicate to [https://github.com/sebawita/nativescript-angular-cli/issues/5](https://github.com/sebawita/nativescript-angular-cli/issues/5)
