### ISSUE TITLE
Router Outlet: Going back two times, or more

### ISSUE THREAD

**Issue by hypertenso** [NativeScript/nativescript-angular#1146]
I'm trying to do something I do not know if it's possible. In the app I'm developing, the first page is a map, the second a list, and the third a detail page, in this flow (Map > List > Detail). The detail page contains a button that plot a route on map. In addition to plotting the route, I need navigation back to the map, which is the home page (I need a double back, or just a redirect). The problem is

The problem is that I can't navigate to the desired route (something like
`this.routerExtensions.navigate(["/home"], { clearHistory: true });`), because this will cause the component to be loaded again.

I need to make the list page disappear of the page stack (or something like that) for `goBack()` to go back to the map.

Has anyone had this problem before? Is there any workaround for this?

My routes:

```
const routes: Routes = [
    { path: "", redirectTo: "/splash", pathMatch: "full" },
    { path: "splash", loadChildren: "./splash/splash.module#SplashModule" },
    { path: "home", loadChildren: "./home/home.module#HomeModule" },
    { path: "companies", loadChildren: "./companies/companies.module#CompaniesModule"}
];
```

My dependencies: 

```
{
  "description": ...,
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.informabrejo",
    "tns-android": {
      "version": "3.3.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/router": "4.2.5",
    "nativescript-angular": "4.2.0",
    "nativescript-carousel": "^3.1.1",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-directions": "^1.1.2",
    "nativescript-email": "^1.5.1",
    "nativescript-fresco": "^3.0.6",
    "nativescript-geolocation": "^4.2.0",
    "nativescript-mapbox": "^3.1.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-pro-ui": "3.1.4",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "^3.4.0",
    "zone.js": "0.8.17"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "codelyzer": "3.2.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.2",
    "nativescript-dev-typescript": "0.5.1",
    "node-sass": "4.5.3",
    "tslint": "5.7.0",
    "typescript": "2.5.2"
  },
  "author": ...
}

**Comment by NickIliev** [comment]
@hypertenso your issue seems related to [this discussion](https://github.com/NativeScript/nativescript-angular/issues/309) and can be implemented by using [Route Guards](https://angular.io/guide/router#!#guards).  Use[ this code base as a reference](https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/router/login-test.ts)

**Comment by bhavincb** [comment]
hii @NickIliev ,
the discussion you addressed is more like how to clear navigation stack after login.
but scenario asked here is different.
suppose i have navigation stack like page1->page2->page3->page4->page5 this and i want to remove pages 2 and 3 from the stack so that back navigation works like this page5 -> page4-> page1 -> exit.
any workaround for doing this?

**Comment by trunkovich** [comment]
It would be really awesome if we will be able to manage route stack.
I have same issue, but I have a route, where user could land in 2 diferent ways.
1 way takes 2 navigations; another takes 3 navigations. 

And I need to route him back directly to home without reloading home page.
