### ISSUE TITLE
Nativescript `--ng` templates comes with not-needed packages

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-angular#1152]
`tns create aaa --ng` comes with `vendor.ts` file which contains : 

`require("@angular/platform-browser");`

IMHO this  file is not needed due to that there's no browser involved : 

*`Platform-browser` contains code shared for browser execution (DOM thread, WebWorker)

*`platform-browser-dynamic` contains the client side code that processes templates (bindings, components, ...) and reflective dependency injection

![image](https://user-images.githubusercontent.com/2842123/34640802-61e52aa0-f302-11e7-888d-be992c5f1f63.png)

this is making the package bigger.

I think it should be removed. ( and maybe other browser things as well)
  
Also why you import the old `require("@angular/http");` with ver 5 ? ( in vendor.ts)

This causes this : 
https://stackoverflow.com/questions/48129206/whats-the-difference-b-w-angular-common-esm5-http-js-vs-angular-http-esm

Also , regarding the old http , you use it in another place : 

Looking at   - 

![image](https://user-images.githubusercontent.com/2842123/34642182-9b980172-f317-11e7-800b-ffa5865bf606.png)

it seems that index.js also imports the old http  module. : 
 
![image](https://user-images.githubusercontent.com/2842123/34642183-a8f8092a-f317-11e7-856a-0770819f4c6b.png)

So there are 3 problems : 

* angular/platform-browser in vendor.ts
* angular/http in vendor.ts
* nativescript-angular\index.js which imports angular/http

**Comment by NickIliev** [comment]
@RoyiNamir the `platform-browser` dependencies are used to create the NativeScript wrappers in  `nativescript-angular` in the following files [dom-adapter.ts](https://github.com/NativeScript/nativescript-angular/blob/c0660cc15c0e42509e9e9f9e0354ae0e2056fbdb/nativescript-angular/dom-adapter.ts#L6), [platform.ts](https://github.com/NativeScript/nativescript-angular/blob/040e0e3576dfc74127f48792ef869b8afccd795b/nativescript-angular/platform.ts#L16-L18) and in [animation.module.ts](https://github.com/NativeScript/nativescript-angular/blob/191f2a039c7793ce86ce9072c6008bfbbd2dbb1b/nativescript-angular/animations/animations.module.ts#L12-L15)

**Comment by RoyiNamir** [comment]
@NickIliev  OK so what about `require("@angular/http");` with ver 5 ?? ( in `vendor.ts`) 
Why doesn't it import the `httpclient` which is in `@angular/common/http` ?
