### ISSUE TITLE
Angular animation using states doesn't work in submodules

### ISSUE THREAD

**Issue by walderpinheiro** [NativeScript/nativescript-angular#1155]
I've 2 submodules from app that i define to load on app-routing.module as : 

```
    { path: "", redirectTo: "/home", pathMatch: "full" },
    { path: "home", loadChildren: "./home/home.module#HomeModule" },
    { path: "deficientes/:id", loadChildren: './deficientes/deficiente.module#DeficienteModule' },
```
I've imported "NativeScriptAnimationsModule" in both submodules, but animation only work if component/element is on app.component.html

This's my project on github : [https://github.com/walderpinheiro/hello-world-nativescript](https://github.com/walderpinheiro/hello-world-nativescript)

**Comment by sis0k0** [comment]
@walderpinheiro, the NativeScriptAnimationsModule should be imported only in the root module.

**Comment by walderpinheiro** [comment]
Thanks, now my animations is working properly in all components of submodule
