### ISSUE TITLE
Cannot read property 'setInputType' of undefined

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-angular#1162]
I don't know if it's related to 3.4.1 version : 

but  i've read [here ](https://github.com/NativeScript/NativeScript/issues/1307)and in some other place that the code should work : 

I have this markup XML : 

    <TextField [(ngModel)]="user"  hint="user" #a  id="a"></TextField>

Inside the class I have : 

    @ViewChild('a') someInput: ElementRef;

But when I do this : (Inside : ` ngOnInit()`)

```
   this.page.getViewById< TextField>("a")
                  .android
                  .setInputType(android.text.InputType.TYPE_CLASS_DATETIME  );
```

I get : 

>ERROR TypeError: Cannot read property 'setInputType' of undefined

Is this a Bug ? 

(I already know I can do it via keyboard type attribute in markup , But I want to do it imperative).

**Comment by NickIliev** [comment]
@RoyiNamir the error indicates taht you do not have a reference to 
```
this.page.getViewById<TextField>("a").android
```
in `ngOnInit`.

Try getting your reference in `ngAfterViewInit` or in the `loaded` event for your `TextField`
