### ISSUE TITLE
NativeScriptAnimationsModule unexpected behavior

### ISSUE THREAD

**Issue by hamdiwanis** [NativeScript/nativescript-angular#1165]
when I import NativeScriptAnimationsModule to the app module everything works fine but when I use it in any other module the app suddenly behaves unexpectedly for example navigation does not work.

**Comment by sis0k0** [comment]
@hamdiwanis, NativeScriptAnimationsModule should be imported only in the root module. The same is valid if you are using the BrowserAnimationsModule in web.

**Comment by hamdiwanis** [comment]
But otherwise the animations does not work

**Comment by hamdiwanis** [comment]
i forgot to mention that the other modules are lazy loaded.

**Comment by sis0k0** [comment]
Here's a sample app with animations and lazy loaded module: https://github.com/NativeScript/ns-ng-animation-examples.

**Comment by hamdiwanis** [comment]
thanks it was probably the absence of NativeScriptCommonModule i will try and see :)
