### ISSUE TITLE
'let-' cause error with RadListView

### ISSUE THREAD

**Issue by ngunhaSO** [NativeScript/nativescript-angular#1166]
I have recently used nativescript cli to generate a starter app. When I tried to use RadListView, I receive the following error: "let-" only support for ng-template. 
This is the package.json generated when i used the nativescript cli:
 "angular/animations": "~5.2.0",
 "angular/common": "~5.2.0",
 "angular/compiler": "~5.2.0",
 "angular/core": "~5.2.0",
 "angular/forms": "~5.2.0",
"angular/platform-browser": "~5.2.0",
 "angular/platform-browser-dynamic": "~5.2.0",
"nativescript-angular": "~5.2.0",
"reflect-metadata": "~0.1.8",
"rxjs": "~5.5.2",
"tns-core-modules": "~3.4.0",
 "zone.js": "~0.8.2"

However, everything is ok if I copied the old package.json from my previous project. The old package.json is like this:
"angular/animations": "4.2.5",
"angular/common": "4.2.5",
"angular/compiler": "4.2.5",
"angular/core": "4.2.5",
"angular/forms": "4.2.5",
"angular/http": "4.2.5",
"angular/platform-browser": "4.2.5",
"angular/router": "4.2.5",
"nativescript-angular": "4.2.0",
"reflect-metadata": "0.1.10",
"rxjs": "5.4.3",
"tns-core-modules": "^3.2.0",
"zone.js": "0.8.16"

The template that I use is this: 
`<GridLayout #holder>
    <RadListView row="1" [items]="outlets" selectionBehavior="Press">
        <template let-item="item" let-i="index">
            <CardView class="outlets" margin="5" radius="3" (tap)="outletItemTap(item)">
                <GridLayout rows="1*,1*, 1*" columns="1*, 1*, 1*, 1*, 1*">
                    <Image class="outlet-img-bg" row="0" rowSpan="3" col="0" colSpan="5" [src]="item.image" stretch="fill"></Image>
                    <StackLayout row="0" col="0" colSpan="5">
                        <Label class="outlet-name" [text]="item.name"></Label>
                    </StackLayout>
                </GridLayout>
            </CardView>
        </template>
        <ListViewGridLayout tkListViewLayout VerticalOptions="Start" scrollDirection="Vertical" itemHeight="200" spanCount="2" itemInsertAnimation="Slide"></ListViewGridLayout>
    </RadListView>
</GridLayout>`

**Comment by NickIliev** [comment]
Indeed you need to use `ng-template` as the old `template` syntax was dropped in Angular 5.x.x

For example:
```
<ng-template let-item="item" let-i="index">
    <!-- template layout here -->
</ng-template>
```
