### ISSUE TITLE
Lazyloaded modal not working in AOT

### ISSUE THREAD

**Issue by patrick-nurt** [NativeScript/nativescript-angular#1169]
By following https://github.com/NativeScript/tests-app-ng/blob/master/app/modal/lazy/lazy-load-modal.component.ts

I can't get AOT compiling working, I can do the normal tns run ios.

Getting this error:
```
CONSOLE ERROR file:///app/vendor.js:1:5913: ERROR Error: Uncaught (in promise): Error: Cannot find module './pages/login/forgot-password/forgot-password.module.ngfactory'.
```

I'm using:
```
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.4.1           │ 3.4.1          │ Up to date    │
│ tns-core-modules │ 3.4.0           │ 3.4.0          │ Up to date    │
│ tns-android      │                 │ 3.4.1          │ Not installed │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date    │
```
and nativescript-angular: 5.2.0

Please help :-)

**Comment by NickIliev** [comment]
@patrick-nurt try following [these instructions](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) including the part for "Single tsconfig for AOT and JIT" and then rebuild your application with AOT flag.

**Comment by patrick-nurt** [comment]
@NickIliev thanks for your swift reply! All of the above is already done and have had no issues actually compiling it with AOT, as soon as I click the modal, I get the error... Could it be because I'm lazy loading a modal from inside a lazyloaded module?

**Comment by patrick-nurt** [comment]
I got it working now in AOT by adding the modal to my routing file as a route with loadchildren :-)
