### ISSUE TITLE
The page-router-outlet’s useAsDefault flag doesn’t appear to work

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#117]
In Groceries I’m attempting to conditionally set the `useAsDefault` flag to determine which component the app should start with. After a bit of debugging I found that even if I set the first component’s `useAsDefault` flag to `false`, and the second component’s `useAsDefault` flag to `true`, I still start on the first component.

You can recreate this in Groceries. Just change the `useAsDefault` flags at https://github.com/NativeScript/sample-Groceries/blob/4ea4f122ff31e0eb85e8196392634e1f1de5fe40/app/app.component.ts#L17-18.

**Comment by vakrilov** [comment]
Dynamically changing the `useAsDefault` value won't work as `RouteConfig` is read when the component is instantiated. That said, I tried to set the `useAsDefault` property on non-first route and it works as expected (tried it both with `page-router-outlet` and with `router-outlet`). 
Probably the `Config.token` variable is always empty when defining routes.

**Comment by tjvantoll** [comment]
For anyone that stumbles across this issue in the future, the problem I had was my first route was configured to have a `path` or "/". Because of that, Angular always picked that route and ignored the `useAsDefault` flag. Once I switched the `path` to something other than root, the `useAsDefault` flag worked as expected.

Thanks @vakrilov!

**Comment by NathanWalker** [comment]
I've run into this before and been puzzled, good to know!

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
