### ISSUE TITLE
How can I download a file and save to the device?

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/nativescript-angular#1171]
Im using POST Method and response is PDF 1.4, how i can save it?
this.http.post(url, JSON.stringify(data), { headers: this.headers })
            .toPromise()
            .then((response) => response)
            .catch(this.handleError);

**Comment by tsonevn** [comment]
Hi @Nurgunkalol,
Thank you for contacting us
To save the file which you received from the request, you could try using the writeSync method provided by File-System module, which will allow you to save the binary data, which you get from your backend service. 
```
this.testFile.writeSync(this.binarySource, err => {
    console.log(err);
});
``` 

For further info, you could also review this article in our documentation, where the usage of [this ](https://docs.nativescript.org/angular/code-samples/file-system) method has been demonstrated.

Hope this helps

**Comment by alereisan** [comment]
@tsonevn the link is broken

**Comment by tsonevn** [comment]
HI @alereisan,
I have updated the link with the correct one.

**Comment by Fabiyo-90** [comment]
And Can I save the in external storage ?
