### ISSUE TITLE
Running the HelloWorld template won't accept any changes to `app.component.ts`

### ISSUE THREAD

**Issue by AjawadMahmoud** [NativeScript/nativescript-angular#1172]
I'm trying to launch a new app with NativeScript but the beginning isn't so good. I'm using NativeScript on WSL. The app seems to work pretty fine; I was able to run it and create a new HelloWorld-templated project and even run it on my Android device (not emulator). Following onto the tutorial I was able to change the color scheme and it was `livesynced` onto my device, however, not a single change in `app.component.ts` is being reflected on the app on my device including changing the app title which is stuck to `My App`.

Any suggestions?

**Comment by tsonevn** [comment]
Hi @AjawadMahmoud,
Could you provide some more info about the problem and changes, which you are making in the ts file?


It would also help if you send us some further info about your environment(NAtiveScript CLI, tns-core-modules, nativescript-angular and tns-android versions) and info about the exact steps, which are used while building project

Thank you in advance for your cooperation.

**Comment by AjawadMahmoud** [comment]
Hello,,

@tsonevn, thanks for your reply. Next is my `package.json` generated by creating a new tns hello-world template project:
```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.TnsHelloWorld",
		"tns-android": {
			"version": "3.4.1"
		}
	},
	"dependencies": {
		"@angular/animations": "~5.2.0",
		"@angular/common": "~5.2.0",
		"@angular/compiler": "~5.2.0",
		"@angular/core": "~5.2.0",
		"@angular/forms": "~5.2.0",
		"@angular/http": "~5.2.0",
		"@angular/platform-browser": "~5.2.0",
		"@angular/platform-browser-dynamic": "~5.2.0",
		"@angular/router": "~5.2.0",
		"nativescript-angular": "~5.2.0",
		"nativescript-theme-core": "~1.0.4",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~5.5.2",
		"tns-core-modules": "~3.4.0",
		"zone.js": "~0.8.18"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.6.0",
		"typescript": "~2.6.2"
	}
}
```
I ended up with this issue by following NativeScript Angular tutorial from chapter 1: https://docs.nativescript.org/angular/tutorial/ng-chapter-1. As I explained earlier, any changes to `app.component.ts` are not being taken into consideration, including manipulating the `template` attribute of the `component`. However, changing `app.css` file even slightly, would trigger a file change and push the updated file to my device and `livesync` the css changes.

**Comment by tsonevn** [comment]
Hi @AjawadMahmoud,
I investigated further your case and reviewed the tutorial, however, I am still unable to recreate the similar scenario.  while using a newly created project with` nativescript-template-ng-tutorial` template ->`tns create HelloWorld --template nativescript-template-ng-tutorial` and while building the project with `tns run <platform_name>` command.
Also, does this issue happens on both platforms(Android and iOS) or it is platform specific? Send us an info about the CLI  (`tns --version`) and TypeScript (tsc --version) versions, which you are using.

**Comment by AjawadMahmoud** [comment]
Hello,,

@tsonevn, thanks for the reply. I'm currently into the scope of another project. I'd have time in two days max to check on this again. I'm planning to remove `tns` completely and reinstall it. Do you have any clue if `npm` installs any additional global files for `tns` beside the binary file? I noticed all `tns` objects are actually part of the local `node_modules` except the global binary file.

**Comment by AjawadMahmoud** [comment]
Hello,,

@tsonevn, thanks for the reply. After twice reinstalling `node_modules` I got HelloWorld sample to work on my phone. This is really weird expereince. Again, thanks for your time!
