### ISSUE TITLE
Change the top color of a modal page on iOS

### ISSUE THREAD

**Issue by bnbs** [NativeScript/nativescript-angular#1174]
This is a normal page
![capturar](https://user-images.githubusercontent.com/22986188/35525274-2eefe7e6-050b-11e8-9faa-be9839c20fe9.PNG)

This is a modal page
![capturar2](https://user-images.githubusercontent.com/22986188/35525275-2f0bb2b4-050b-11e8-9f02-97987f8070d1.PNG)

As you can see the modal page top color is white but I want the same color as the normal page. Is there a way to change that color?

**Comment by NickIliev** [comment]
@bnbs as far as I see, you need to change the status bar color for your modal page.
Try to change the status bar color for your whole application as shown in [this documentation article](https://docs.nativescript.org/ui/change-status-bar-style-ios)
