### ISSUE TITLE
nativeElement.android is undefind in custom directive

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1179]
_From @shabib3 on January 31, 2018 2:2_

Hi,

I searched some for this issue and didn't find something that help me.

I have a custom directive that set up a time picker...I want to set it to 24 Hours format so I need to get into the android property of the nativeElement/nativeView to run `timePicker.android.setIs24HourView(java.lang.Boolean.TRUE);` command.

until now I use the timePicker in modal dialog and the following situation worked just great which don't  work now on custom directive:
HTML:
```
<StackLayout>
    <TimePicker id="timePicker"></TimePicker>
    <Button class="btn btn-primary btn-active" text="Submit" (tap)="submit()"></Button>
</StackLayout>
```

TS:
```
let timePicker: TimePicker = <TimePicker>this.page.getViewById<TimePicker>("timePicker");
if(isAndroid) {
    timePicker.android.setIs24HourView(java.lang.Boolean.TRUE);
} else if(isIOS) {
    const local = NSLocale.alloc().initWithLocaleIdentifier("NL");
    timePicker.ios.locale = local;
}
timePicker.minute = this.currentdate.getMinutes();
timePicker.hour = this.currentdate.getHours();
```

I don't get what I am doing wrong.

I also tried to do this:
```
<TimePicker #timePicker id="timePicker"></TimePicker>
```
and 
```
@ViewChild("timePicker") timePickerElement: ElementRef;
.
.
.
let timePicker: TimePicker = this.timePickerElement.nativeElement;
```

But also without success.

and also tried to put the code inside OnInit and AfterViewInit and inside setTimeout just to be sure the view is good to go.

Thanks a lot! (:

_Copied from original issue: NativeScript/NativeScript#5362_

**Comment by NickIliev** [comment]
@shabib3 we can't use @ViewChild() to query something outside of the component. 

Just get the reference to the element in the component where the directive is used.

**Comment by shabib3** [comment]
@NickIliev - but if I have this custom directive twice in the component?
