### ISSUE TITLE
Cannot style ActionBar in CSS

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#118]
First of all, the new ability to use `<ActionBar>` is great. One thing I’ve noticed though is that I’m unable to style an `<ActionBar>` in an `app.css` file. `<ActionBar backgroundColor="..." color="...">` works as expected, so I have a workaround, but I’m wondering if styling via `app.css` can be supported, because I think most apps will want to style their action bars globally.

Thanks.

**Comment by vakrilov** [comment]
Yup - it should be supported.

I tried it [here](https://gist.github.com/vakrilov/ff9d58d34bcac77cbdf9) and it worked as expected:
![actionbar](https://cloud.githubusercontent.com/assets/4092076/13874372/2b8e94b4-ed00-11e5-9cbc-8158a5b2ff07.png)

Maybe it is more complicated issue - can you share more details.

**Comment by tjvantoll** [comment]
Thanks @vakrilov,

Sorry, I would’ve swore this wasn’t working for me yesterday, but today it is. I’ll reopen this if I can recreate the problem I was having.
