### ISSUE TITLE
How to detect iPhone or Android Model in Nativescript Angular

### ISSUE THREAD

**Issue by sunpasup** [NativeScript/nativescript-angular#1181]
PSST! Want to get faster responses to bug reports and important issues? Help us keep the issue tracker organized by:

- Reporting bugs. Please include all details about the problem and provide a sample app (consider using the [playground](https://play.nativescript.org) for this.
- Proposing features and enhancements.
- Discussing implementation details.

Please move all other content to the [forums](http://forum.nativescript.org).

**Comment by NickIliev** [comment]
@sunpasup it is not clear what you are trying to achieve because there is no information provided for the problem you are facing.

If you need to create different logic for iOs and Android you can achieve that in several ways including wrapping the code in platform specific checks.
```
import { isAndroid, isIOS } from "platform";
if (isAndroid) {
    // Android code here
} else if (isIOS) {
    // iOS code here
}
```

**Comment by ibnYusrat** [comment]
for me the import goes something like:

`import {isAndroid, isIOS} from 'tns-core-modules/ui/page';`

**Comment by andre505** [comment]
It appears 'platform' is deprecated. 

import {isAndroid, isIOS} from 'tns-core-modules/ui/page' 
works for me too

**Comment by u007** [comment]
updated:
```
import { isAndroid, isIOS } from "@nativescript/core";
```
