### ISSUE TITLE
Source control integration - read only files - can't compile ? 

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-angular#1187]
I'm facing a read only files ( which are read only becuase they are under source control)

But when they are in read only state - `tns run` - doesn't run.

for example , all files are in check in : 

 
![image](https://user-images.githubusercontent.com/2842123/35778562-7e732992-09c8-11e8-90dd-8347431568ae.png)

lets run `tns run android`  : 

![image](https://user-images.githubusercontent.com/2842123/35778550-53d98f1e-09c8-11e8-8572-ae61b4743267.png)

>Error: EPERM: operation not permitted, open 'C:\NS\dev\dsapp1\app\app.android.css'

so let's deal with that css : 

 
![image](https://user-images.githubusercontent.com/2842123/35778596-dc029aac-09c8-11e8-96b5-39e04d7a79c4.png)

let's run again : 

![image](https://user-images.githubusercontent.com/2842123/35778601-edd71a1e-09c8-11e8-8657-919677ba04e7.png)

so you that other files is also in read only

**Question**

How can I run tns run android without(!) check out all files ?

It is not a realistic situation where I'm forced to check out all files just to compile ...

**Comment by darind** [comment]
You seem to be using the `nativescript-dev-sass` plugin. In this case you should not put under source control your `.css` files but rather the corresponding `.scss`.

**Comment by RoyiNamir** [comment]
@darind Thank you for reply. What about the ts and js files then ? do I have to manually check all ts and exclude al JS's ????

**Comment by RoyiNamir** [comment]
@darind  The problem is not only with Sass. I've checked out all the css files : 

![image](https://user-images.githubusercontent.com/2842123/35780395-55bce284-09e3-11e8-8331-1ecc91ef4485.png)


And then I got tons of error js files (probably from TS transpilation) : 

![image](https://user-images.githubusercontent.com/2842123/35780403-758a3ff8-09e3-11e8-9882-09b23dcec277.png)


So what is the right way of dealing with those files with source controls ? Must I go each js files under a ts file and exclude it ???
