### ISSUE TITLE
Cannot use ActionItem systemIcons

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#119]
For whatever reason, whenever I try to use the `ios.systemIcon` or `android.systemIcon` attribute on an `<ActionItem>` it doesn’t show up. 

You can recreate this by putting the following code in a template:

```xml
<ActionBar title="Groceries">
  <ActionItem ios.systemIcon="9" android.systemIcon="ic_menu_share_holo_light"></ActionItem>
</ActionBar>
```

**Comment by tjvantoll** [comment]
In a related note I don’t seem to be able to apply a `color` either for some reason.

**Comment by vakrilov** [comment]
Confirmed - currently the render does not support setting nested properties. We will research ways to enable this scenario.

**Comment by tjvantoll** [comment]
Works great. Thanks!
