### ISSUE TITLE
Injected `page`  is not affected by ` styleUrls: ['./login.component.scss']`

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-angular#1190]
I have a simple component : 
```
import { Component, OnInit } from '@angular/core';
import {Page} from "ui/page";
@Component({
  moduleId: module.id,
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  constructor( private page: Page) { }

    ngOnInit()
    {
        this.page.actionBarHidden = true;
        this.page.className = "list-page";
    }
}
```

Where `login.component.scss` is : 

```
.list-page {
  background-image: url("res://bg_android");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
}
```
But the page is not being applies with the background image : 

![image](https://user-images.githubusercontent.com/2842123/35851259-201a364c-0b30-11e8-8aaa-b0cbd8990e83.png)

However if I go to the root : `_app-common.scss` and write : 

![image](https://user-images.githubusercontent.com/2842123/35851277-3430a53a-0b30-11e8-9504-75fad489e7e9.png)

Then I do get the background image applied : 

![image](https://user-images.githubusercontent.com/2842123/35851286-3f8cf58c-0b30-11e8-8bbd-80f03d648167.png)

bug  ? 

Injected page should be applied with the css.

**Comment by darind** [comment]
Try pointing the `styleUrls` property of your component to the actual CSS file and not the SASS file:

```
styleUrls: ['./login.component.css']
```

**Comment by RoyiNamir** [comment]
@darind  still doesn't work : 

![image](https://user-images.githubusercontent.com/2842123/35853093-46cd0ddc-0b35-11e8-9695-0b1f4a81ab47.png)

**Comment by NickIliev** [comment]
@RoyiNamir confirming this behavior and we will investigate if respecting the local CSS files is possible for injected pages. 

Meanwhile as a workaround, if you need to apply a CSS class for your injected page use the root application CSS file (usually `app.component.css`)

e.g.
app.coomponent.css
```
.list-page {
  background-image: url("res://bg_android");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
}
```

any in-app component
```
this.page.className = "list-page";
```

**Comment by NickIliev** [comment]
@RoyiNamir we have discussed this issue and the thing is that in ANgular the CSS styles from `styleUrls` are prefixed build-time which makes the issue appear when trying to apply a style on the injected Page instance. 

As a workaround, you can either use the root CSS (e.g. app.component.css) or create a container element for your in-app component.

**Comment by RoyiNamir** [comment]
@NickIliev "prefixed " with what ?
