### ISSUE TITLE
[iOS] Navigation back button appears when the app reloads or refresh

### ISSUE THREAD

**Issue by relvis** [NativeScript/nativescript-angular#1194]
Hi there, I just noticed that after I updated my device (or simulator) to iOS 11.2 everytime I refresh the app (by a change in the code or simply close and reopen the app) the back button appears along with the drawer. This is the code I am using right now and I have attached an image to illustrate the issue. I have tested in iOS 11.1 and 11.0 and is working as expected.

```
<ActionBar class="action-bar" title="">
    <NavigationButton ios:visibility="collapsed" icon="res://menu" (tap)="onDrawerButtonTap()"></NavigationButton>
    <ActionItem icon="res://navigation/menu" android:visibility="collapsed" (tap)="onDrawerButtonTap()" ios.position="left"></ActionItem>
    <Label class="action-bar-title" text="Dashboard"></Label>
</ActionBar>
```
![fb8c226e33c18e61e6166b3ff106eeadc04a423a_1_690x113](https://user-images.githubusercontent.com/3420851/35978655-55dcda70-0cb4-11e8-833e-2c25f6311181.png)

I also tried some approaches like using the code below:

```
if (page.ios) {
        const controller = frameModule.topmost().ios.controller;
        // get the view controller navigation item
        const navigationItem = controller.visibleViewController.navigationItem;
        // hide back button
        navigationItem.setHidesBackButtonAnimated(true, false);
}
```
But is not working in iOS 11.2.

Thanks!

**Comment by tsonevn** [comment]
duplicated with the issue [#5406](https://github.com/NativeScript/NativeScript/issues/5406)
