### ISSUE TITLE
Property 'extend' does not exist on type 'typeof WebViewClient'

### ISSUE THREAD

**Issue by TheOnlyMatt** [NativeScript/nativescript-angular#1197]
Hi everybody !

I am facing some issue relative to the Webviews, more particularly about a way to open in the browser, links which are clicked in the web view. 
I have a valid snippet : 
  ```
try {
            
                var MyWebViewClient = android.webkit.WebViewClient.extend({
                    shouldOverrideUrlLoading: function(_webView,interceptedUrl){
                        console.log('Intercepted Url was ', interceptedUrl);
                        utilityModule.openUrl(interceptedUrl)
                        webView.stopLoading()
                        return false
                    }
                });
                webView.android.setWebViewClient(new MyWebViewClient());
            } catch(e) {
                alert(e.message);
            }
```

Basically when the app is building, the TypeScript compiler launches an error saying : ` error TS2339: Property 'extend' does not exist on type 'typeof WebViewClient'.`

During development phase I found a hack to prevent the TS compiler from throwing this error and stopping compilation. I set the "noEmitOnError" property to false in my tsconfig file.
Doing so let the app build and enabled the possibility to open links from the webviews.

But when I decided to build with webpack options, the compiler started back to throw the error, so I am unable to build with webpack options.

I can point that I have already installed the tns platform declarations plugin and added the references path in references.d.ts.

What could be the cause of this error ?

**Comment by tsonevn** [comment]
Hi @TheOnlyMatt,
To solve the issue with the `'extend' does not exist on type 'typeof WebViewClient'` error, you could extend the needed class while following the TypeScript syntaxes, which is shown [here](https://docs.nativescript.org/runtimes/android/generator/extend-class-interface).

However, if you want to keep the JavaScript approach for extending, you could merely cast `android` to any as following:
`declare var android: any;`
Adding this line in the project will allow you to build it without the need of setting `"noEmitOnError"` property to `false`. This also will allow you to build the project with webpack. For your convenience, I am attaching a sample project.

**Comment by TheOnlyMatt** [comment]
Ok, so I implemented your second solution on mine

```
declare var android:any;
...
export class SimpleItemComponent  {

    webviewLoaded(args){
        let webView : WebView = args.object

        if (webView.android) {

            try {

                var MyWebViewClient = android.webkit.WebViewClient.extend({
                    shouldOverrideUrlLoading: function(_webView,interceptedUrl){
                        console.log('Intercepted Url was ', interceptedUrl);
                        utilityModule.openUrl(interceptedUrl)
                        webView.stopLoading()
                        return false
                    }
                });
                webView.android.setWebViewClient(new MyWebViewClient());
            } catch(e) {
                console.log(e.message);
            }
        }
        else if(webView.ios)
            webView.on("loadStarted", function(data){
                utilityModule.openUrl(data.url)
            })

    }
```
With this the compilation ends without any error.
If I set an alert in the catch, I have an error like "Trying to link a java object" or something like that, and the link doesn't open. But if I just set a log in the catch, the browser opens fine.

I tried quickly to extend the webview class, but I didn't succeeded as I never made it. So perhaps I will try later if I have more time to spend on it.

But anyway it is working, thank you for your anwser !
