### ISSUE TITLE
ScrollView

### ISSUE THREAD

**Issue by anhoev** [NativeScript/nativescript-angular#120]
Does anyone have a sample for scrollview ?

**Comment by NathanWalker** [comment]
```
<StackLayout>
  <ScrollView>
    ... anything ...
  </ScrollView>
</StackLayout>
```

In the future you may want to ask this question on the {N} slack channel:
https://t.co/uExEluDrmO

And please just keep this in mind:
https://github.com/NativeScript/codeofconduct

**Comment by NathanWalker** [comment]
This is also a great example repo you can try:
https://github.com/NativeScript/sample-Groceries

**Comment by NathanWalker** [comment]
This is also a specific {N} + ng2 repo you can try:
https://github.com/NathanWalker/angular2-seed-advanced

Instructions to run the NativeScript app:
https://github.com/NathanWalker/angular2-seed-advanced#run-nativescript-app

**Comment by NathanWalker** [comment]
Another sample repo:
https://github.com/NativeScript/sample-ng-todomvc

**Comment by anhoev** [comment]
@NathanWalker
I tried to get ScrollView working in TabView but not successful.  Do you have any idea?
