### ISSUE TITLE
Inserting a dynamic transparent component - is not being transparent 

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-angular#1204]
(Preface : Creating transparent layer on top)  -  Let's make a simple case : 

Looking at these 2 views , where the second view has `opacity` : 

```
<StackLayout class="home-panel" backgroundColor="red">
	<Label textWrap="true" text="Play with NativeScript!" class="h2 description-label"></Label>
</StackLayout>
 
<StackLayout orientation="vertical" backgroundColor="orange" opacity="0.5" verticalAlignment="middle" height="100%">
	<Label textWrap="true" backgroundColor="yellow" text="TEST TEST TEST"></Label>
</StackLayout> 
```

We can see that the second view is transparent.

 
![image](https://user-images.githubusercontent.com/2842123/36339246-ea8e1ece-13c9-11e8-99ed-4c18b0cb7ef1.png)

Good.

Ok - now let's inject a component dynamically (after  1 second) : 
`home.component` , injects the `c1.component` : 

```
   ngOnInit(): void {
        const componentContainer = this.viewContainerRef;
        const resolver = componentContainer.injector.get(ComponentFactoryResolver);
        const providers = ReflectiveInjector.resolve([{ provide: Page, useValue: this.page }]);
        const childInjector = ReflectiveInjector.fromResolvedProviders(providers, this.viewContainerRef.parentInjector);

        setTimeout(() => {
            const detachedFactory = resolver.resolveComponentFactory(C1Component);
            this.viewContainerRef.createComponent(detachedFactory, -1, childInjector, null);
        }, 1000)
    }
```

The component does being injected but no transparency exists : 

![image](https://user-images.githubusercontent.com/2842123/36339256-10271802-13ca-11e8-900d-eadf50ea8928.png)

**[HERE IS PLAYGROUND](https://play.nativescript.org/?template=play-ng&id=CIhfHk&v=13)**

Code as taken from https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/directives/dialogs.ts

Diagnostics : transparency should exists , but it doesn't

**Comment by NickIliev** [comment]
@RoyiNamir perhaps instead of using the Angular dynamic loader to load native layouts [you can reuse the selector](https://play.nativescript.org/?template=play-ng&id=CIhfHk&v=14) (c1 in your case) and show/hide this layout when needed (e.g with `visibility` or with structural directive like *ngIf)

**Comment by RoyiNamir** [comment]
@NickIliev this requires me to go through each component and add this tag.
I'm doing this becuase I want to do it via service. 
such as   : `_serviceModal.show()`

So I don't think that each component should have ngif'ed component just to sit and wait there.

Is this a bug ?
