### ISSUE TITLE
Uglify doesnt work on build after upgrading to angular 5 and nativescript-dev-webpack 0.9.0

### ISSUE THREAD

**Issue by CoericK** [NativeScript/nativescript-angular#1209]
Hello guys, my team just decided to migrate from angular 4.4.1 and webpack 0.8.0 to angular 5 and nativescript-dev-webpack 0.9.0.

Current dependencies version:

```
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
     "nativescript-angular": "^5.2.0",
    "rxjs": "^5.5.0",
    "tns-core-modules": "^3.4.1",
    "zone.js": "^0.8.4",
   "@angular/compiler-cli": "~5.2.0",
   "nativescript-dev-webpack": "^0.9.2",
    "uglifyjs-webpack-plugin": "^1.2.0",
    "webpack": "~3.8.1"
```

Current nativescript dependencies:
nativescript 3.4.2, tns-android 3.4.1, tns-ios 3.4.1, tns-core-modules 3.4.1

If i run:
tns run ios --bundle, it works.

but if i want to build with uglify:
tns prepare ios --bundle && tns build ios --bundle --env.uglify

I got this error:

ERROR in bundle.js from UglifyJs
Unexpected token: punc ()) [bundle.js:77292,29]
Child worker:
                             Asset     Size  Chunks                    Chunk Names
    943e638cb8213864c3cf.worker.js  1.03 MB       0  [emitted]  [big]  main
      [29] ./package.json 147 bytes {0} [optional] [built]
        + 96 hidden modules
    
    ERROR in 943e638cb8213864c3cf.worker.js from UglifyJs
    Unexpected token: name (xxxx) [943e638cb8213864c3cf.worker.js:16432,4]
Webpack compilation complete.
Executing webpack failed with exit code 2.

Im asumming its something related to uglify not being able to parse some es6 syntax. In projects using .babelrc they recommend adding the loader es2015 and it fixes it but in the case of nativescript there is no .babelrc and adding it to webpack.config.js as loader doesnt seem right to me.

Any idea what could it be?

**Comment by NickIliev** [comment]
Closing as duplicate to [https://github.com/NativeScript/nativescript-dev-webpack/issues/443](https://github.com/NativeScript/nativescript-dev-webpack/issues/443)
