### ISSUE TITLE
SegmentedBar using Vue.js not working

### ISSUE THREAD

**Issue by vtvhunter** [NativeScript/nativescript-angular#1214]
Hi, I am testing the development of an app using Vue.js through Nativescript and have encountered a problem when using SegmentedBar ui component (using [this](https://nativescript-vue.org/en/docs/elements/components/segmented-bar/) as a guide: ) :

**template**

`<SegmentedBar :items="listOfItems" v-model="selectedItem" />`

**object**

`data: {
    	listOfItems: [
			{title: 'Cool'},
			{title: 'Warm'}
    	]`

**error**
```
JavaScript error:
file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:456:27: JS ERROR TypeError: child._setupUI is not a function. (In 'child._setupUI(context)', 'child._setupUI' is undefined)
```
I have also tried using [items]="arrayName" and that prevents the error but the component renders blank. The only way I can make it work is if I use static data with `SegmentedBarItem` component.

Thanks

**Comment by vtvhunter** [comment]
sorry this should be inside the nativescript-vue folder

**Comment by tsonevn** [comment]
You could log your issues related to `nativescript-vue` in [this repository](https://github.com/nativescript-vue/nativescript-vue/issues).
