### ISSUE TITLE
Abnormal behaviour with "loaded" event

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1216]
i was trying to get element's true width value while width is set using percentage value.
so i had try implemented it in below nativescript playground project
[https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=15](https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=15)
as you can see it is not working, output is not what we expected.

but if add (loaded)="getHeight(abc)" to GridLayout  it starts showing desired output.
here is playground [https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=16](https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=16)
here  "getHeight" functions simply console.log the View.effectiveWidth, View.getMeasuredWidth() and  View.getActualSize().width value.

Note: look at the device logs,  View.effectiveWidth, View.getMeasuredWidth(), View.getActualSize().width all value are 0. i'm unable to get correct width value.

1. if i'm just console log some value on loaded event then it should not effect the UI.
2. also what is the correct way of creating square or aspect ratio based element while having percentage width?
3. when and how can i get correct hieght and width measurements ?

**Comment by tsonevn** [comment]
First of all, thank you for the sample projects.
I reviewed them and was able to recreate an issue with getting the actual component width and height while using **getActualSize** method.  The returned value for the width and height will be 0 on the loaded event. To workaround this case I would suggest setting up timeout with 200 milliseconds. For example:
home.component.html
```
<ActionBar title="Home" class="action-bar">
</ActionBar>

<ListView [items]="a"  class="list-group">
	<ng-template let-country="item" let-i="index" let-odd="odd" let-even="even">
		<WrapLayout  width="100%"  orientation="horizontal" backgroundColor="palegreen">
			<GridLayout rows="*,*" #abc  (loaded)="getSize($event)" columns="*"  width="20%" [height]="testWidth" backgroundColor="lightgray">
				<Label row="0" [text]="'W'+testWidth" col="0" backgroundColor="red"></Label>
				<Label row="1" text="LA" col="0" backgroundColor="green"></Label>
			</GridLayout>
		</WrapLayout>
	</ng-template>
</ListView>
```
html.component.ts
```
import { Component, OnInit, ViewChild } from "@angular/core";
import { PercentLength } from "tns-core-modules/ui/styling/style-properties"
import { GridLayout } from "ui/layouts/grid-layout"
@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html",
    styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
    a = ['1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2', '1', '2',]
    @ViewChild('abc') abc;
    testWidth = 0;
    constructor() {
        
    }
    getSize(args) {
        setTimeout(() => {
            let grid = <GridLayout>args.object;
            var gridSize = args.object.getActualSize();
            var gridWidth = gridSize.width;
            var gridHeight = gridSize.height;
            console.log("gridWidth: " + gridWidth);
            console.log("gridHeight: " + gridHeight);
            this.testWidth = gridWidth;
        }, 200);
    }
    ngOnInit(): void {
    }
    toDevicePixels(percentage: PercentLength) {
        console.dir(PercentLength.convertToString(percentage))
        return PercentLength.toDevicePixels(percentage,0,0);
    }
}

```

In the code sample is also show, how to bind and set up the height of the GridLayout dynamically, which will allow you to create the needed square in the ListView template.

**Comment by bhavincb** [comment]
what i'm trying to accomplish here is creating 5*n grid where grid child elements must have same height as their width, even after rotating from landscape to portrait or portrait to landscape, their height must be same as width, but using above approach and binding element "height" attribute  to "this.testWidth" will work only on portrait mode.
do you have any workaround for this?
and actual bug i had reported is that without loaded event UI is not working properly, can u explain what is the cause of that?

**Comment by tsonevn** [comment]
HI @bhavincb,
This issue seems to be related to this feature request [#3946](https://github.com/NativeScript/NativeScript/issues/3946) for providing event, which will notify you at the time when the components are rendered, and you can take their actual size.

Regarding the problem you are facing you can try to call ListView's [refresh](https://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview#refresh) method on orientation change or to specify the rows and columns size with fixed numbers. For example:
```
<GridLayout rows="100, *" #abc   columns="100"   [height]="abc.getActualSize().width" backgroundColor="lightgray">
				<Label row="0" [text]="abc.getActualSize().width" col="0" backgroundColor="red"></Label>
				<Label row="1" text="LA" col="0" backgroundColor="green"></Label>
			</GridLayout>
```

**Comment by bhavincb** [comment]
hii @tsonevn ,
problem i am facing is that without loaded event binding UI doesn't render at all. as we can see in playground sample project i had provided.

**Comment by tsonevn** [comment]
HI @bhavincb,
In the sample project, you are using `getActualSize()` method and  `width` property which are not from type observable. In this case, the UI will not be notified for the change of the actual size and the Layout width will not be changed as well.
This could be handled by using the [orientation change event](https://docs.nativescript.org/api-reference/modules/_application_#orientationchangedevent) and binding the width property. When the orientation changes, you could get the needed data with the `getActualSize()` and to set up the new width value.

**Comment by bhavincb** [comment]
hii @tsonevn ,

i had thought about orientation change event but unable to locate any documentation relating that. mark an suggestion or request that all this event should be added to documentation with some examples of themselves.

**Comment by tsonevn** [comment]
Hi @bhavincb,
Thank you for the suggestion.
Indeed we will provide examples, which demonstrates how to handle orientation change event in for NS Angular and non-Angular project. Regarding that, we logged new [task ](https://github.com/NativeScript/docs/issues/995#issuecomment-374501821) in our docs repository.

**Comment by darkyelox** [comment]
For those who want to get the measured width or height of an element you can use the next code in your ngAfterViewInit lifecycle callback:

```TypeScript
this.someViewElement.on(ViewBase.loadedEvent, () => {
      setTimeout(() => {
        const elementHeight = this.nativeView.getMeasuredHeight()
        console.log('view height', this.elementHeight)
      })
})
```
