### ISSUE TITLE
0.0.36 on npm?

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#122]
I noticed the package was bumped:
https://github.com/NativeScript/nativescript-angular/commit/9477a7656faa41cd58365001960bdf7f9068eb46

But I don't see `0.0.36` on npm yet?

**Comment by tjvantoll** [comment]
This is sort of odd. https://www.npmjs.com/package/nativescript-angular says 0.0.35 but if I `npm install --save natiescript-angular` I get 0.0.36.

**Comment by NathanWalker** [comment]
Hmm. That is strange. I'll try to update and proceed then. npmjs usually updates right away after a publish I have found so that is puzzling.
