### ISSUE TITLE
keyboard opens automatically while using SearchBar.

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1225]
if we had used the SearchBar inside a Page when searchbar is created it automatically opens keyboard.
here is playground [https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=24](https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=24).
there should be some option to change this default behavior. i had checked api reference for "SearchBar" but unable to find such a option. 
Also tried using `searchBar.dismissSoftInput()` on searchbar "loaded" event but still not working.

**Comment by tsonevn** [comment]
Hi, @bhavincb,
In your case, you could use the SearchBar loaded event and `dismissSoftInput`, while calling the method with a delay of 200  milliseconds. For example:
HTML
```
<SearchBar (loaded)="loadedSB($event)" hint="Search hint" (clear)="onClear($event)" [text]="searchPhrase" (textChange)="onTextChanged($event)" (submit)="onSubmit($event)"
	 color="white" textFieldHintColor="white"></SearchBar>
```
TypeScript
```
loadedSB(args) { 
        setTimeout(() => {
            args.object.dismissSoftInput();
        }, 200)
        
    }
```
The loaded event will be fired; when the component is already initialised, however, the focus will come a little bit later. In this case, you could call the dismiss method with a timeout.

**Comment by bhavincb** [comment]
hii @tsonevn ,
if That is the case then Nativescript should need to work on "loaded" event or need to provide some more events for "SearchBar" like "focus" and "blur". so please also add feature label.

**Comment by tsonevn** [comment]
Hi, @bhavincb,
A [similar issue](https://github.com/NativeScript/NativeScript/issues/4594) already exists in the core [modules repository](https://github.com/NativeScript/NativeScript/issues/4594). You could review it and add your edition info.
