### ISSUE TITLE
Android api calls (httpClient.post()) don't work??

### ISSUE THREAD

**Issue by dhandas180391** [NativeScript/nativescript-angular#1226]
Running full build
Project successfully built.
Installing...
Successfully installed on device with identifier '57U7N17C22004408'.
Successfully transferred all files.
Refreshing application...
Successfully synced application com.maxtest.Test on device 57U7N17C22004408.
System.err: java.net.SocketException: Software caused connection abort
System.err: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
System.err: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
System.err: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
System.err: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
System.err: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
System.err: 	at java.net.Socket.connect(Socket.java:592)
System.err: 	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
System.err: 	at com.android.okhttp.Connection.connectSocket(Connection.java:196)
System.err: 	at com.android.okhttp.Connection.connect(Connection.java:172)
System.err: 	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
System.err: 	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
System.err: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
System.err: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
System.err: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
System.err: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
System.err: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
System.err: 	at org.nativescript.widgets.Async$Http$RequestOptions.writeContent(Async.java:313)
System.err: 	at org.nativescript.widgets.Async$Http$HttpRequestTask.doInBackground(Async.java:536)
System.err: 	at org.nativescript.widgets.Async$Http$1.run(Async.java:482)
System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
System.err: 	at org.nativescript.widgets.Async$PriorityThreadFactory$1.run(Async.java:52)
System.err: 	at java.lang.Thread.run(Thread.java:776)

I get the above in my terminal when the api call times out (This call is to login). This happens ON/OFF randomly. Sometimes it works fine on android but most times when i do `tns run android --bundle` i get this issue???

I have set a timeout for 1 minute.

On iOS it works perfectly fine.

**Comment by tsonevn** [comment]
Hi @dhandas180391,
Can you provide sample project, which could be used for debugging as well as more info about your environment(CLI, tns-core-modules, nativescript-angular, tns-ios, tns-android versions)

**Comment by dhandas180391** [comment]
I found the issue, the Android device i was using was not connecting to the work wifi correctly hence api calls were not working. When testing with my personal iphone i had been using mobile data.
