### ISSUE TITLE
Single line input for Prompt

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1228]
```
let options:PromptOptions = {
    title: "Group Name",
    defaultText: "Name",
    inputType: inputType.text,
    okButtonText: "Create",
    cancelButtonText: "Cancel"
};
prompt(options).then((result: PromptResult) => {
    console.log("prompt data", result.result);
    console.log("prompt data", result.text);
}).catch((e) => {
    console.log("prompt data", e);
});
```
i'm creating prompt using above code. but it creates multi-line input inside promt and i want it to be single line input.
is there any workaround for this?

also i'm requesting some extra feature for "prompt" like it will be great if there is some way to add user defined css class to prompt elements like TextView and buttons, also it will be great if we can add custom validators also. and using it dynamically disable and enable ok button.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#5509
