### ISSUE TITLE
Terminal does not output any logs for Android

### ISSUE THREAD

**Issue by ngunhaSO** [NativeScript/nativescript-angular#1233]
After I upgrade my tns to 3.4.3, the terminal does not output any console log for Android. It is ok for iOS. 
Then I tried to downgrade the nativescript by running: npm uninstall -g nativescript and ran: npm install -g nativescript@3.4.2 again but the log still does not shows.

More info:

The output of running tns --version shows: 3.4.2

Detail of my package.json file:
tns-android: 3.4.1
tns-ios: 3.4.1

Dependencies:
angular/animations: ~5.2.0,
angular/common: ~5.2.0,
angular/compiler: ~5.2.0,
angular/core: ~5.2.0,
angular/forms: ~5.2.0,
angular/http: ~5.2.0,
angular/platform-browser: ~5.2.0,
angular/platform-browser-dynamic: ~5.2.0,
angular/router: ~5.2.0,
email-validator: "^1.1.1",
nativescript-angular: "~5.2.0",
nativescript-iqkeyboardmanager: "^1.2.0",
nativescript-loading-indicator: "^2.4.0",
nativescript-localstorage: "^1.1.5",
nativescript-ngx-fonticon: "^4.0.0",
nativescript-socket.io: "^0.9.0",
nativescript-theme-core: "~1.0.4",
nativescript-toast: "^1.4.6",
nativescript-ui-listview: "^3.5.1",
nativescript-ui-sidedrawer: "^3.5.1",
reflect-metadata: "~0.1.8",
rxjs: "~5.5.2",
tns-core-modules: "^3.4.1",
zone.js: "~0.8.2"

Dev Dependencies:
"babel-traverse": "6.26.0",
"babel-types": "6.26.0",
"babylon": "6.18.0",
"lazy": "1.0.11",
"nativescript-dev-typescript": "~0.6.0",
"typescript": "~2.6.2"

Can you please assist how to get the log back on the terminal? Both real device and genymotion shows no console log

**Comment by ngunhaSO** [comment]
Reverted back to 3.4.2, and did a npm cache clean fixed the issue.
However, the question is still: why upgrade to 3.4.3, the terminal log does not appear

**Comment by tsonevn** [comment]
Hi @ngunhaSO,

I tested your case on a sample project while using latest NativeScript CLI and Android runtime, however, was unable to recreate the problem.
I noticed that you are using an old runtime I would suggest upgrading the NativeScirpt CLI to version(`3.4.3`) as well as the Android runtime(`3.4.2`) as follows:
`tns platform remove android`
`tns platform add android`

**Comment by ngunhaSO** [comment]
Is there any specific tns-core-modules needed? Previously i remember the version was like 3.4.2@2018.... then i changed to 3.4.1 which is what returned by running: npm install tns-core-modules@latest --save

**Comment by tsonevn** [comment]
You should use the latest official version of tns-core-module, which now is 3.2.1. You could add it as follows: 
1. `tns plugin remove tns-core-modules` 
2. `tns plugin add tns-core-modules`
