### ISSUE TITLE
Item in RadSideDrawer does not respond

### ISSUE THREAD

**Issue by ngunhaSO** [NativeScript/nativescript-angular#1237]
I installed the sample app for nativescript-ui-radsidedrawer, however the click event for the close drawer button does not respond. I have to tap multiple times before the event get triggered. 

The sample is downloaded from: https://github.com/telerik/nativescript-ui-samples-angular

Devices used to test:
Device 1:  Samsung galaxy S7, Android version: 7.0
Device 2: Samsung galaxy S5, Android version: 5.0.2
Device 3: Galaxy Tab S, Android version: 6.0.1

Tns version: 3.4.3

Also, tapping outside of the sidedrawer does not close the drawer.

Everything works fine in genymotion emulator though

**Comment by ngunhaSO** [comment]
When I switched back to nativescript-pro-ui package, the side drawer item respond properly on all devices

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#575
