### ISSUE TITLE
Suggestion: Add documentation on Page navigation events

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1239]
i was getting trouble with navigation data. i had to do some clean up work only when page is navigated using android hardware button or RouterExtentons backToPreviousPage function call.
i didn't find any relevant information regarding on page navigation event on nativescipt-angular documentation.
i had found this useful article on this [https://pointdeveloper.com/nativescript-page-navigation-events/](url).
there should be some official documentation regarding this.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/docs#1099
