### ISSUE TITLE
Label Margin inside ActionBar not working

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1240]
here is playground demo `https://play.nativescript.org/?template=play-ng&id=FpaWzb&v=33`
i'm trying to apply  margin to label inside ActionItem but for some reasons it is not working.
```
<ActionItem>
		<Label margin="11" text="B"></Label>
	</ActionItem>
```

**Comment by bhavincb** [comment]
i also noted one more unexpected behaviour.
when applying margin using css it is still not working.
```
ActionBar Label{
    margin:10;
}
```
but here is the catch if i add one more styling `padding:10` then both works as expected both applied successfully.
```
ActionBar Label{
    padding: 10;
    margin:10;
}
```

**Comment by tsonevn** [comment]
Hi, @bhavincb,
In this case, the Label should be set inside a Layout container, which will allow the margin to be set properly. Example:
```
<ActionBar title="Home" class="action-bar">
	<ActionItem>
		<Label text="A"></Label>
	</ActionItem>

	<ActionItem>
		<StackLayout>
			<Label margin="11" text="B"></Label>
		</StackLayout>
	</ActionItem>
	<ActionItem>
		<Label  text="C"></Label>
	</ActionItem>
	<ActionItem>
		<Label text="D"></Label>
	</ActionItem>
	<ActionItem>
		<Label text="E"></Label>
	</ActionItem>
</ActionBar>
```

**Comment by bhavincb** [comment]
hii @tsonevn ,
yes i checked it and working pefectly.
but as i said there is some glitch or bug.
because below class has no effects 
```
ActionBar Label{
    margin:10;
}
```
and if i had `padding:10`  then it will work with both padding and margins.
below is working class code
```
ActionBar Label{
    padding: 10;
    margin:10;
}
```

**Comment by tsonevn** [comment]
Hi, @bhavincb,
I have checked again the case with the margin and padding.

On iOS, only the padding will be applied to the Label component.
On Android the padding will be appropriately applied as well, however, the margin will not be respected on the left or right sides. The margin will be attached only to the top. Also, there is no functionality, which allows setting up the margin to the label, while it is used directly in the ActionItem. In this case, it is not clear what it will happen while setting up a margin to the component on different Android devices.

Regarding that, in my previous comment, I have mentioned, what is the correct way to setup margin to a Label in ActionBar item.

**Comment by bhavincb** [comment]
hii @tsonevn ,
thank you for detail information regarding issue. As you mentioned there is problem with ActionItem. so please mark this as Bug or add some information to official doc regarding this. so that it help others in future.

**Comment by tsonevn** [comment]
Hi, @bhavincb,
Thank you for writing us back.
Indeed we will extend the ActionBar articles for both ns Angular and non-Angular and will describe that this case with margin and padding.

**Comment by bhavincb** [comment]
hi @tsonevn ,
should i close this issue? or this will be feature request and will be added to nativescript in future?

**Comment by tsonevn** [comment]
Hi, @bhavincb,
I think that this issue should be closed. We will describe this scenario in the docs and will clarify what the right approach is.
