### ISSUE TITLE
how to use actionItems?

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1242]
in my project i want to show and hide group of more than 5 ActionItem at a time. only option i have to write *ngIf in every ActionItem.
i had searched nativescript docs and found below example.
```
<ActionBar title="{{ pageTitle }}">
                    <NavigationButton icon="res://ic_arrow_back_white_24dp" tap="onNavigateBack" />
                    <ActionBar.actionItems>
                        <ActionItem tap="onShareUrl" ios.position="right" android.position="right">
                            <ActionItem.actionView>
                                <Label text="&#xE80D;" class="materialdesign actionbaricon" />
                            </ActionItem.actionView>
                        </ActionItem>
                        <ActionItem tap="toggleFavorite" ios.position="right" android.position="right">
                            <ActionItem.actionView>
                                <Label text="&#xE866;" class="materialdesign actionbaricon" />
                            </ActionItem.actionView>
                        </ActionItem>
                    </ActionBar.actionItems>
            </ActionBar>
```

which shows the use of ActionItems for grouping ActionItem. but i didn't find any related code for nativescript angular.
i also tried using 'ActionBar.actionItems' and 'ActionItems' but no luck.
so what is the proper way of using ActionItems with nativescript-angular?

**Comment by tsonevn** [comment]
Hi @bhavincb,
The `<ActionBar.actionItems>` is valid tag only for the non-Angular project. In NS Angular project every ActionItem should be set directly in the ActionBar as it is demonstrated in our [documentation code samples.](https://docs.nativescript.org/angular/code-samples/ui/action-bar)
Also, the appropriate way to hide those components is to set up ngIf or visibility property to every single ActionItem.

**Comment by bhavincb** [comment]
hii @tsonevn ,
i get it is available only for non-angular projects. but can it be added to angular projects also. i think it it very handy feature.

**Comment by tsonevn** [comment]
Hi @bhavincb,
Excuse me for the delay in the replay.
`actionItems` is a container and the idea is to collect the ActionBar Items in a non-Angular project. As you can see in the [ActionItems definition](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/action-bar/action-bar-common.ts#L159), the class does not extend the View component, which means that setting up the visibility property on it will not have an effect in a non-Angular project as well.  Regarding that, the solution on NS Angular and Vanilla Javascript project is the same, and you should set up the visibility option on each ActionBarItem.
