### ISSUE TITLE
nativescript-angular/animations with AOT

### ISSUE THREAD

**Issue by jolafrite** [NativeScript/nativescript-angular#1247]
I created multiple animations using the nativescript-angular/animations.
But when I compile the app using AOT, the animations are not showing anymore.

Do you have a demo where animations work with AOT ?

tns run ios --device 1 --bundle --env.uglify
![without-aot](https://user-images.githubusercontent.com/579224/37653112-b2720772-2c78-11e8-9b82-b2877e5543f5.gif)

tns run ios --device 1 --bundle --env.aot --env.uglify
![with-aot](https://user-images.githubusercontent.com/579224/37653284-48d2026c-2c79-11e8-9337-3a642237d302.gif)

**Comment by jolafrite** [comment]
I just found a difference between without AOT and with AOT

Without AOT the AnimationPlayer instance is **AnimationRenderer**
With AOT the AnimationPlayer instance is **BaseAnimationRenderer**

**Comment by jolafrite** [comment]
one more update
with the following line :
```
this._renderer = rootRenderer.createRenderer(doc.body, typeData);
```
```doc.body``` is defined in not AOT and undefined with AOT

**Comment by sis0k0** [comment]
Hey @jolafrite, can you test with the `next` version of {N} angular?
```
npm install nativescript-angular@next
```
This should be fixed with https://github.com/NativeScript/nativescript-angular/pull/1164, but hasn't been released yet.

**Comment by jolafrite** [comment]
@sis0k0 just when I found what I was supposed to do to fix the issue :-)
yes move the document polyfill to platform-common.ts fixes the issue
Great!
