### ISSUE TITLE
Different behavior of nsRouterLink and Router@navigate()

### ISSUE THREAD

**Issue by bozhidarc** [NativeScript/nativescript-angular#1252]
I have the following route tree:

**app-routing.module.ts**
```
const routes: Routes = [
    { path: "", redirectTo: "/home", pathMatch: "full" },
    { path: "home", loadChildren: "./home/home.module#HomeModule" }
];
```
And in my lazy loaded module this one:
**home-routing.module.ts**
```
const routes: Routes = [
    {
        path: "", component: HomeComponent,
        children: [
            { path: "", component: Child1Component}
        ]
    },
    {
        path: "child2", component: Child2Component
    }
];
```

When I try to navigate from ChildOneComonent to Child2Component with **nsRouterLink** everything works fine, but if I try with the navigate() method of the Router class I receive the following error 
"ERROR: ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'child2'". This behavior can be observed in the playground example bellow.

Playground Example: https://play.nativescript.org/?template=play-ng&id=Xt1Ynk&v=2

**Comment by tsonevn** [comment]
Hi @bozhidarc,
Thank you for reporting this issue.
I tested this scenario on my side and had to confirm that this is a real issue. Regarding that, this problem could also be reproduced while using the RouterExtention provided by nativescript-angular. 
You could keep track on the issue for further info.

**Comment by vakrilov** [comment]
Hey @bozhidarc,
The reason for this behavior is that `nsRouterLink` will navigate relative to the current path by default. The `navigate()` method will not unless you explicitly tell it to do so by passing the current activated route:
```
constructor(private router: Router, private currentRoute: ActivatedRoute) {
}

onButtonTap(): void {
    this.router.navigate(["child2"], { relativeTo: this.currentRoute });
}
```

You can check out modified example here: https://play.nativescript.org/?template=play-ng&id=9ABJDn
