### ISSUE TITLE
pieChart not found

### ISSUE THREAD

**Issue by waszqba** [NativeScript/nativescript-angular#1257]
Hello, I have a problem with charting library. I try to create a donut chart in my application and it logs `JS: ERROR TypeError: Cannot read property 'pieChart' of undefined` when I try to run it. In an act of despair I tried to copy playground templated code into my app just to see if it will work, unfortunately, no luck.

I have 3.4.3 tns version and nativescript-pro-ui in version 3.4.1
I have noticed that playground import uses path: `nativescript-pro-ui-chart/angular` and my local build uses `nativescript-pro-ui/chart/angular` path, which is basically the only difference I can see there

NativeScriptUIChartModule is imported into my app.module

My chart display attempt is written in a component

chart.component.ts:
```import { Component, OnInit } from '@angular/core';
@Component({
    selector: 'chart',
    moduleId: module.id,
    templateUrl: './chart.component.html',
    styleUrls: ['./chart.component.scss']
})
export class ChartComponent implements OnInit {
    pieSource: {Brand: string, Amount: number}[] = [
            { Brand: 'Audi', Amount: 10 },
            { Brand: 'Mercedes', Amount: 76 },
            { Brand: 'Fiat', Amount: 60 },
            { Brand: 'BMW', Amount: 24 },
            { Brand: 'Crysler', Amount: 40 }
    ];

    ngOnInit(): void {}
}
```
not setting any type no pieSource doesn't change anything

chart.component.html:
```<GridLayout rows="*" height="1000px">
    <RadPieChart allowAnimation="true" row="0">
        <DonutSeries tkPieSeries selectionMode="DataPoint" outerRadiusFactor="0.9" expandRadius="0.5" outerRadiusFactor="0.7" innerRadiusFactor="0.4"
                     [items]="pieSource" valueProperty="Amount" legendLabel="Brand"></DonutSeries>
        <RadLegendView tkPieLegend position="Right" title="Brands" offsetOrigin="TopRight" width="110" enableSelection="true"></RadLegendView>
    </RadPieChart>
</GridLayout>
```

You can see that html is purely copied from template. Playground-based application works and mine doesn't. Any suggestions where to look for solutions?

**Comment by bhavincb** [comment]
try to use nativescript-ui instead of nativescript-pro-ui.

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#600
