### ISSUE TITLE
Navigation Bar and Page-Router-Outlet

### ISSUE THREAD

**Issue by AlvaHub** [NativeScript/nativescript-angular#1260]
What is the right way to build a navigation bar for the main screens and use page-router-outlet for the sub-screens using nativescript-angular? I was unable to use page-router-outlet inside a normal router-outlet so I had to make the menu as a component and add it to each main screen like the code below:

```
<StackLayout>
  <menu></menu>
  <Label text="My Screen" ></Label>
</StackLayout>
```

But the menu blinks when the screen is changed, so I believe this is not the right approach.

**Comment by tsonevn** [comment]
Hi @AlvaHub,
You can review our `tns-template-drawer-navigation-ng`(https://github.com/NativeScript/template-drawer-navigation-ng, https://www.npmjs.com/package/tns-template-drawer-navigation-ng) template and check how the shared navigation menu scenario is solved there.

For further question please use our [forum ](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).
