### ISSUE TITLE
Cannot able to programmatically select/change a item/index in SegmentedBar

### ISSUE THREAD

**Issue by kumarandena** [NativeScript/nativescript-angular#1263]
Hi team,

I was tried to programmatically change/select SegmentedBar item/index using ElementRef approach. 

But i cannot able to get reference of selectedIndex property.

regarding this i have created forum post [here ](https://discourse.nativescript.org/t/programmatically-change-segmentedbar-item-index/5274).

Thanks.

**Comment by NickIliev** [comment]
@kumarandena 

Here is [a Playground demo](https://play.nativescript.org/?template=play-ng&id=h1ETJF) showing a possible approach to get the `selectedIndex` of your `SegmentedBar` in an Angular app.
