### ISSUE TITLE
ListView multiple template dont Work

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1264]
_From @domzinhuu on April 3, 2018 20:46_

## Please, provide the details below:

When use mutiple template with observable and async pipe the itemTemplateSelector dont call the method when array is empyt

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
nativescript     │ 3.4.2         
tns-core-modules │ 3.4.1 
tns-android      │ 3.4.2
 tns-ios          │ 3.4.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Components.ts

```
Observable<Objetct[]>
this.beneficiaries$ = this.beneficiaryService.getAll();
```

```
templateSelector(item:any, index: number, items: any) {
    return items.length > 0 ? 'base' : 'empty'; }
```

Html

```
<ListView [items]="beneficiaries$ | async" class="list-group" [itemTemplateSelector]="templateSelector">
      <ng-template nsTemplateKey="base" let-item="item" let-odd="odd" let-index="item.id" let-even="even">
        <StackLayout class="list-group-item" (tap)="onItemTap(item.id)">
          <Label [text]="item.fullName" class="list-item-title"></Label>
          <Label [text]="item.bankName" class="body"></Label>
          <Label [text]="item.accountNumber" class="body"></Label>
        </StackLayout>
      </ng-template>

      <ng-template nsTemplateKey="empty">
        <StackLayout class="list-group-item">
          <Label [text]="'Algum texto'" class="list-item-title"></Label>
          <Label [text]="'algo'" class="body"></Label>
        </StackLayout>
      </ng-template>
    </ListView>
```

_Copied from original issue: NativeScript/NativeScript#5615_

**Comment by tsonevn** [comment]
Hi @domzinhuu
I tested the scenario with the async pipe while using multiple templates, however, was unable to recreate a problem.
For your convenience, I am attaching a sample project. Please review it and make the needed changes, which will allow me to recreate the issue. Also, provide more info about your case, and what you are trying to achieve as a final result.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1874580/Archive.zip)

**Comment by domzinhuu** [comment]
Hello @tsonevn 

Well, i need show a empty template when the list is empty, but when the list is empty the templateSelector is not call. I modified your zip project.

[modified.zip](https://github.com/NativeScript/nativescript-angular/files/1875935/modified.zip)

**Comment by tsonevn** [comment]
Hi @domzinhuu,
We checked your scenario, and this seems to be expected behaviour. The `itemTemplateSelector` will be fired for every ListView item, If there are no items, this will not templateSelector method will not be executed.
In your scenario, you could set up the `No Items` label outside the ListView and hide it when the ListView has items, which to be displayed. For example:
HTML
```
<StackLayout sdkExampleTitle sdkToggleNavButton>
    <GridLayout rows="*" columns="*">
        <Label row="0" class="text-center" text="No Item..." [visibility]="!isItemVisible ? 'visible' : 'collapsed'"></Label>
        <ListView row="0" [items]="myItems | async" class="list-group" [itemTemplateSelector]="templateSelector" [visibility]="isItemVisible ? 'visible' : 'collapsed'">
            <ng-template nsTemplateKey="red" let-item="item" let-i="index" let-odd="odd" let-even="even">
                <GridLayout class="list-group-item" backgroundColor="red">
                    <Label [text]="item.name" android:class="label-item"></Label>
                </GridLayout>
            </ng-template>
        
            <ng-template nsTemplateKey="green" let-item="item" let-i="index" let-odd="odd" let-even="even">
                <GridLayout class="list-group-item" backgroundColor="green">
                    <Label [text]="item.name" android:class="label-item"></Label>
                </GridLayout>
            </ng-template>
        </ListView>
    </GridLayout>
</StackLayout>
```
TypeScript
```
import { Component, ChangeDetectionStrategy } from "@angular/core";
import { Observable as RxObservable } from "rxjs/Observable";

export class DataItem {
    constructor(public id: number, public name: string) { }
}
@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent {
    public myItems: RxObservable<Array<DataItem>>;
    public isItemVisible:boolean = false;
    constructor() {
        let items = [];

        let subscr;
        this.myItems = RxObservable.create(subscriber => {
            this.isItemVisible = false;
            subscr = subscriber;
            subscriber.next(items);
            return function () {
                console.log("Unsubscribe called!");
            };
        });

        let counter = 2;
    }
    public templateSelector = (item: DataItem, index: number, items: any) => {
 
        return index%2 === 0 ? "red" : "green";
    }
}
```

**Comment by domzinhuu** [comment]
Cool , thanks!




Obter o Outlook para Android







On Thu, Apr 5, 2018 at 5:32 AM -0300, "Nikolay Tsonev" <notifications@github.com> wrote:












Hi @domzinhuu,

We checked your scenario, and this seems to be expected behaviour. The itemTemplateSelector will be fired for every ListView item, If there are no items, this will not templateSelector method will not be executed.

In your scenario, you could set up the No Items label outside the ListView and hide it when the ListView has items, which to be displayed. For example:

HTML
<StackLayout sdkExampleTitle sdkToggleNavButton>
    <GridLayout rows="*" columns="*">
        <Label row="0" class="text-center" text="No Item..." [visibility]="!isItemVisible ? 'visible' : 'collapsed'"></Label>
        <ListView row="0" [items]="myItems | async" class="list-group" [itemTemplateSelector]="templateSelector" [visibility]="isItemVisible ? 'visible' : 'collapsed'">
            <ng-template nsTemplateKey="red" let-item="item" let-i="index" let-odd="odd" let-even="even">
                <GridLayout class="list-group-item" backgroundColor="red">
                    <Label [text]="item.name" android:class="label-item"></Label>
                </GridLayout>
            </ng-template>
        
            <ng-template nsTemplateKey="green" let-item="item" let-i="index" let-odd="odd" let-even="even">
                <GridLayout class="list-group-item" backgroundColor="green">
                    <Label [text]="item.name" android:class="label-item"></Label>
                </GridLayout>
            </ng-template>
        </ListView>
    </GridLayout>
</StackLayout>



TypeScript
import { Component, ChangeDetectionStrategy } from "@angular/core";
import { Observable as RxObservable } from "rxjs/Observable";

export class DataItem {
    constructor(public id: number, public name: string) { }
}
@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent {
    public myItems: RxObservable<Array<DataItem>>;
    public isItemVisible:boolean = false;
    constructor() {
        let items = [];

        let subscr;
        this.myItems = RxObservable.create(subscriber => {
            this.isItemVisible = false;
            subscr = subscriber;
            subscriber.next(items);
            return function () {
                console.log("Unsubscribe called!");
            };
        });

        let counter = 2;
    }
    public templateSelector = (item: DataItem, index: number, items: any) => {
 
        return index%2 === 0 ? "red" : "green";
    }
}
