### ISSUE TITLE
KeytoolException: Failed to read key

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1265]
```
Execution failed for task ':app:packageRelease'.
> com.android.ide.common.signing.KeytoolException: Failed to read key bunkerzon
from store "E:\incpt\nativescript\bunkerzon\bunkerzon.jks": Keystore was tampere
d with, or password was incorrect

```
i'm getting above error while executing following command.

`tns build android --release --key-store-path bunkerzon.jks --key-store-password BunkerZon --key-store-alias bunkerzon --key-store-alias-password BunkerZon`

i had generating key from following command.
`keytool -genkey -v -keystore bunkerzon.jks -keyalg RSA -keysize 2048 -validity 10000 -alias bunkerzon`

i had verified that there is no issue with keystore file and password.
issue can be reproduced using this repo [https://github.com/bhavincb/nativescript-ng-scss-template](url)

**Comment by tsonevn** [comment]
Hi, @bhavincb,
This problem can be caused by using specific symbols are used in the password. You could review [this ](https://discourse.nativescript.org/t/keystore-error-to-release-an-android-app-keystore-was-tampered-with-or-password-was-incorrect/641/3) forum thread, where this is discussed.

**Comment by bhavincb** [comment]
hii @tsonevn ,
i was using password `#$%BunkerZon%$#` as instructed in forum i had tried using `'#$%BunkerZon%$#'`
but still getting same error.

**Comment by tsonevn** [comment]
HI @bhavincb,
The way that should be used for escaping the special symbols, such as `$`, depends on the console, which you are using. The quotation marks, might not help in your case.
I would suggest to checkout what is specific to your console.

**Comment by bhavincb** [comment]
hii @tsonevn ,
i am using windows 8.1 command Prompt and one more thing to note that same keystore and same password working as expected on some other project which i have access to. so i don't think it the problem with keypassword.

**Comment by bhavincb** [comment]
hii @tsonevn ,
i can confirm that after changing keystore password it works perfectly. but i still think this should be considered as bug.
because when signing APK with `jarsigner` and using same password `#$%bunkerzon%$#` it works as expected.
```
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.jks android-release-unsigned.apk my-alias
```
issuing above command will ask for keystore password in cmd and then starts signing process. i think nativescript should ask for password when it is not entered as command line argument. so that there will be no worries for escaping the special symbols which depends on the console,

**Comment by bhavincb** [comment]
@NickIliev  is this issue solved?
