### ISSUE TITLE
Creating custom keyboard

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/nativescript-angular#1268]
Hello, any tutorial for creating custom keyboard? for example i use keyboard type "number" and "phone" but i want to make like calculator keyboard + just 0-9 keyboard and etc..

**Comment by NickIliev** [comment]
@Nurgunkalol thank you for your interest in NativeScript.
Take a look[ at this blog post](https://www.nativescript.org/blog/nativescript-ios-numeric-keyboard) that shows how to solve this issue on iOS.

the repository is for logging issues, bugs and features related to nativescript-angular plugin.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)
