### ISSUE TITLE
Error: com.tns.NativeScriptException: Failed to find module ... when I use frame.topmost().navigate

### ISSUE THREAD

**Issue by djom20** [NativeScript/nativescript-angular#1269]
Based on the tab template that you provide in the examples I'm trying to use this template but actually when I try to change the view with this code:

```
const frameModule = require("ui/frame");
frame.topmost().navigate("vehiclesmodule/vehiclesmodule-page");
```

This are the modules failing:

![image](https://user-images.githubusercontent.com/1834808/38439442-433181d4-39a3-11e8-9644-05d25dad5747.png)

![image](https://user-images.githubusercontent.com/1834808/38439471-62a7cb22-39a3-11e8-89ce-0d419f490837.png)

This code it's on a click action of a item list, when I click on the item I got this error:

![image](https://user-images.githubusercontent.com/1834808/38439281-b1666eea-39a2-11e8-9655-5b587fe152c0.png)
![image](https://user-images.githubusercontent.com/1834808/38439304-bffe2d6c-39a2-11e8-866f-9822b191d341.png)

I have tried adding it, removing it, recreating the module with other names and things like that, but it is still failing. This issue happing with other modules at the same way, and I don't understand why it's looking for a style into the module, because if the module had not any .css what happen with this?

Thanks so much.

**Comment by tsonevn** [comment]
Hi @djom20,
In NativeScript Angular, you should use the Angular router or NativeScript RouterExtensions to make navigation. Please review [this ](https://docs.nativescript.org/core-concepts/angular-navigation) article from the documentation.
