### ISSUE TITLE
ConstraintLayout & AutoLayout implementation

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1272]
Is there any layout available which works on constraint in nativescript?
Constraint based layout are more efficient than other layouts.
[https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html](https://android-developers.googleblog.com/2017/08/understanding-performance-benefits-of.html) 
is there any workaround for this?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#5665
