### ISSUE TITLE
Navigating with `{ clearHistory: true }` crashes with `TypeError: null is not an object (evaluating 'navController.viewControllers')`

### ISSUE THREAD

**Issue by darxmac** [NativeScript/nativescript-angular#1283]
On a certain component, when navigating away with `{ clearHistory: true }` it crashes/fails with:

```
CONSOLE ERROR [native code]: ERROR TypeError: null is not an object (evaluating 'navController.viewControllers')
CONSOLE ERROR [native code]: ERROR CONTEXT {
"view": {
"def": {
"nodeFlags": 50774083,
"rootNodeFlags": 33554435,
"nodeMatchedQueries": 0,
"flags": 0,
"nodes": [
{
"nodeIndex": 0,
"parent": null,
"renderParent": null,
"bindingIndex": 0,
"outputIndex": 0,
"checkIndex": 0,
"flags": 33554433,
"childFlags": 17219651,
"directChildFlags": 17088579,
"childMatchedQueries": 0,
"matchedQueries": {},
"matchedQueryIds": 0,
"references": {},
"ngContentIndex": null,
"childCount": 16,
"bindings": [
{
"flags": 8,
"ns": "",
"name": "title",
"nonMinifiedName": "title",
"securityContext": 0
}
],
"bindingFlags": 8,
"outputs": [],
"element": {
"ns": "",
"name": "ActionBar",
```

I finally traced it down to a problem when items in the action bar are changed while navigating away. In this instance I had a conditional on a save button in the ActionBar that got reset when some state in a service was changed while navigating away.

This only popped up after upgrading to {N} 4.0.0, any ideas what might have changed ?

**Comment by iosdeveloper1001** [comment]
I am facing a same issue.can any one elaborate more about it?
How to solve it?

**Comment by tsonevn** [comment]
Hi @iosdeveloper1001,
We are still unable to recreate the issue on our side. It will help if you provide a sample project, which could be used for debugging.

**Comment by jonnysamps** [comment]
Yep, I'm getting this too.

**Comment by tsonevn** [comment]
Hi @jonnysamps,
Can you provide sample project, which could be used for debugging?

**Comment by simonox** [comment]
Happens in my project, too. Unfortunately it is too large to share it.

**Comment by jonnysamps** [comment]
@tsonevn I think it is actually due to using a custom component as my `tkDrawerContent` of my `RadSideDrawer`.

When I do 
```xml
<RadSideDrawer>
  <nav  tkDrawerContent active="SEARCH"></nav>
  ...
</RadSideDrawer>
```
I get the above error but when I wrap my custom component with a standard layout it works fine. 
```xml
<RadSideDrawer>
  <GridLayout tkDrawerContent><nav  active="SEARCH"></nav></GridLayout>
  ...
</RadSideDrawer>
```
BTW the unwrapped version worked fine in ~3.3.0. I only found this when upgrading my app.

Here is the nav component template and code:

```xml
<DockLayout stretchLastChild="false" bgBlur>
  <Label text="Search" (tap)="goToSearch()" dock="top" [class.active]="active === 'SEARCH" ></Label>
  <Label text="Inventory" (tap)="goToInventory()" dock="top" [class.active]="active === 'INVENTORY"></Label>
  <Label text="Logout" (tap)="logout()" dock="top"></Label>
  <label text="My App v0.0.1" dock="bottom"></label>
</DockLayout>
```

```typescript
import { RouterExtensions } from 'nativescript-angular/router';
import { Component, Input, ElementRef } from '@angular/core';

@Component({
  selector: 'nav',
  templateUrl: 'components/nav/nav.component.html'
})
export class NavComponent {
  @Input() active: string;

  constructor(
    private routerExtensions: RouterExtensions,
  ) 
  { }
   
  logout() {
    this.routerExtensions.navigate(['/'], {clearHistory: true})
  }
  
  goToInventory() {
    this.routerExtensions.navigate(['/inventory'], { clearHistory: true });
  }
  
  goToSearch() {
    this.routerExtensions.navigate(['/search'], { clearHistory: true });
  }
}
```

**Comment by terreb** [comment]
This happens to me with vanilla NS as well. Any workaround?

**Comment by tsonevn** [comment]
Hi @jonnysamps,
Can you try whether you will be able to recreate the issue with NativeScript 4.1.0 and angular 6?

@terreb, please send us sample project, which could be used for reproducing and debugging the issue.

**Comment by OliverNiebsch** [comment]
This NativeScript pull request: https://github.com/NativeScript/NativeScript/pull/6029 seems to fix all problems with navigation in NativeScript 4 + angular 6 in my project.
