### ISSUE TITLE
ActivityIndicator bug - NS 4

### ISSUE THREAD

**Issue by morzyns** [NativeScript/nativescript-angular#1288]
After changing variable busy to false, ActivityIndicator is still visible.

```
            <StackLayout visible="{{busy}}">
                <ActivityIndicator busy="true" width="100" height="100"></ActivityIndicator>
            </StackLayout> 
```
NativeScript 4
Angular 5.2

**Comment by vakrilov** [comment]
Hey @morzyns 
The name of the property is `visibility` and you can set it to [`"visible"`,`"collapse"` or `"hidden"`](https://docs.nativescript.org/api-reference/modules/_ui_enums_.visibility#visible)

**Comment by NickIliev** [comment]
@morzyns the `ActivityIndicator` is working as expected with[ this test project](https://github.com/NickIliev/NS-Issues-2018/tree/master/nativescript-angular/issue_1288_ng) - let me know if you have some specific scenario which can reproduce the issue.
