### ISSUE TITLE
VS Code debugger

### ISSUE THREAD

**Issue by matt4446** [NativeScript/nativescript-angular#129]
I've tried debugging using VS Code and the [new plugin](http://docs.nativescript.org/core-concepts/visual-studio-code-extension). I can't get as far as debugging into the running application (through attach or start up) ... 

From the debug panel I tried: Launch on an android device 

```
# NativeScript Debugger started #
Attaching to debug application
Debugger connected
```

it will break on the first line of `ts_helpers.js` pressing continue the logging will suggest its started. I have the usual logging for my elements, but the screen on genymotion remains black. Detaching brings the app back to life. 

Anyone else have this problem?

Thanks,
Matt

**Comment by hdeshev** [comment]
This issue was moved to NativeScript/nativescript-vscode-extension#39
