### ISSUE TITLE
RadAutoCompleteTextView and async data loading

### ISSUE THREAD

**Issue by waszqba** [NativeScript/nativescript-angular#1290]
Hi there, I have a serious problem with loading async suggestions with `RadAutoCompleteTextView` in my angular app. I have 4.0.0 version of tns and tns-android version is 4.0.1. Autocomplete version I'm using is 3.6.0.
The problem is: I have a function defined in a service (or anywhere for that matter) intended to be used with `loadSuggestionsAsync` of the component. The problem is, when I try to get a service or basically anything imported to my module/component/service the function is defined in, I cannot, as all imports are stored in `this` of the class, and when I try to reach `this` while executing my function triggered by text input, I see that `this` is overridden by `RadAutoCompleteTextView`.
Thus, I cannot reach my http client to make a request fetching suggestions.
Any `suggestions` what to do?

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#627
