### ISSUE TITLE
Serious memory leaks with CSS animations

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-angular#1291]
I've created a simple new project via `tns create bbb --ng`

![image](https://user-images.githubusercontent.com/2842123/39033892-edd54baa-447c-11e8-9a69-024e90c17b5c.png)

Added a CSS animation class via `animate.css` library : 

**app.css**
```
@import '~nativescript-theme-core/css/core.light.css';
@import "~animate.css/animate.min.css";

.breath {
    animation-name: pulse;
    animation-duration: 2s;
    animation-iteration-count: infinite;
    animation-fill-mode: forwards;
}

```

And now I've created 7 images with that class. Some with manual images and some are via `*ngFor` : 

![image](https://user-images.githubusercontent.com/2842123/39033944-247af402-447d-11e8-8b7f-a08f27626357.png)

This is the code for **items.component.html**

```
<ActionBar title="My App" class="action-bar"></ActionBar>
<GridLayout columns="*,*,*,*,*,*,*" rows="*">

    <StackLayout row="0" col="1"  >
        <Image class="breath " [src]="'~/images/hat00001.png'" stretch="aspectFit"></Image>
    </StackLayout>

    <StackLayout row="0" col="2"  >
        <Image class="breath " [src]="'~/images/hat00001.png'" stretch="aspectFit"></Image>
    </StackLayout>

    <Image *ngFor="let o of [1,2,3,4,5];let i = index;"
           [col]="i+3"
           [class]="'breath'"
          verticalAlignment="top"
           [src]="'~/images/hat0000'+(i+2)+'.png'"
           stretch="aspectFit"></Image>
</GridLayout>

```

**There's nothing else. No TS code ,  no nothing. Just this html and css.**

However  , while writing down this issue ^  , look at the memory consumption : 

![image](https://user-images.githubusercontent.com/2842123/39034024-777f0526-447d-11e8-8276-2bc5568797fa.png)

Started at : 

![image](https://user-images.githubusercontent.com/2842123/39034039-83f6e68e-447d-11e8-8c35-ecff4c1fa17f.png)

And now it's (keeps growing) : 

![image](https://user-images.githubusercontent.com/2842123/39034051-92f5d3f2-447d-11e8-9057-48f1a772524d.png)

**Attached project** : https://ufile.io/spicc

Video showing the ease growing leak : 

![video_2018-04-20_093614](https://user-images.githubusercontent.com/2842123/39034403-f21ba52c-447e-11e8-8d8a-d0a7323adfc1.gif)

_Worth to mention: I'm not talking about the jumps. I'm talking about the easy growing memory consumption_

**Eventually the app is shutdown due to out of memory**

Additional info : 

![image](https://user-images.githubusercontent.com/2842123/39034546-6da88444-447f-11e8-8544-516f44ce889d.png)

Update:  after 51 min -  it's  0.2 GB : 

![image](https://user-images.githubusercontent.com/2842123/39035747-d2c3c858-4483-11e8-8412-2081dd782b68.png)

This bug hurts  the ability to use NS with  games/continuous animations  (said to be supported with css animations).  :-(
Any workaround ?
BTW  it also happens with Angular animations. ( i've created a test and still there's also a leak with Angular animations).

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#5731
