### ISSUE TITLE
App deployed in Iphone stopped opening after a few days

### ISSUE THREAD

**Issue by lumayara** [NativeScript/nativescript-angular#1301]
Hi, I deployed the app I made in my Iphone and it was good for a couple of days but now it is not opening. When I click the icon, it only shows the launching screen and then it goes back to the Iphone menu. If I click twice in my middle button to see the apps running in background, I can see my app and the initial screen, but still when I tap on it, it will go away and take me back to the menu. I had this same problem 2 weeks ago and I deleted and deployed it again. However, I wanted to know if this is a big or there is a reasonable explanation for that. Thank you!

**Comment by NickIliev** [comment]
@lumayara it is hard to say what is causing your issue without any related code base and error logs. Based on what you are saying  I would check the HTTP related execution (if the blank page is waiting for some date to render a UI). 


However, the above is a shot in the dark - please consider following the recommendation for opening a new issue
```
PSST! Want to get faster responses to bug reports and important issues? Help us keep the issue tracker organized by:

- Reporting bugs. Please include all details about the problem and provide a sample app (consider using the [playground](https://play.nativescript.org) for this.
- Proposing features and enhancements.
- Discussing implementation details.

Please move all other content to the [forums](https://discourse.nativescript.org/).

```
