### ISSUE TITLE
app crash due to undefined back function in RouterExtension

### ISSUE THREAD

**Issue by MuhammadTahir92** [NativeScript/nativescript-angular#1307]
`System.err: TypeError: Cannot read property 'back' of undefined
System.err: File: "file:///data/data/org.nativescript.tradelivemobile/files/app/app.component.js, line: 31, column: 33
System.err: StackTrace:
System.err:     Frame: function:'AppComponent.activity.onBackPressed', file:'', line: 31, column: 34
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onBackPressed(NativeScriptActivity.java:59)
System.err:     at android.app.Activity.onKeyUp(Activity.java:2522)
System.err:     at android.view.KeyEvent.dispatch(KeyEvent.java:2765)
System.err:     at android.app.Activity.dispatchKeyEvent(Activity.java:2775)
System.err:     at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2353)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4637)
System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4593)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4271)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4133)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4328)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4133)
System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4106)
System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4159)
System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4125)
System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4304)
System.err:     at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4474)
System.err:     at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2330)
System.err:     at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1934)
System.err:     at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1925)
System.err:     at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2307)
System.err:     at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
System.err:     at android.os.MessageQueue.next(MessageQueue.java:328)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5728)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)`

> _I want to route to previous child component when press on back button _
code snippets

` let activity = AndroidApplication.startActivity ||
      AndroidApplication.foregroundActivity ||
      topmost().android.currentActivity ||
      topmost().android.activity;

    activity.onBackPressed = function () {
      // Your implementation
      console.log("back button is pressed");
      this.routerExtensions.back();
    };`

Please guide

**Comment by tsonevn** [comment]
Hi @MuhammadTahir92,
You should set up the callback method as follow:
```
activity.onBackPressed = (args) => {
                console.log("back button is pressed");
                this.routerExtention.back();
            }
```
Then, you will have access to the `this.routerExtensions` and its methods.
For your convenience, I am attaching sample project as well.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1959930/Archive.zip)
