### ISSUE TITLE
ListView items do not have index property on tap event

### ISSUE THREAD

**Issue by vaindil** [NativeScript/nativescript-angular#1309]
`ListView` items are not passing an `index` parameter via `ItemEventData` when tapped. An example is [here](https://play.nativescript.org/?template=play-ng&id=wZst2Q&v=2). The `onTap` method is called, as it should be, but the `args` object in the callback does not have an `index` property. I therefore have no way to reference items in the `.ts` file from the tap event.

**Comment by tsonevn** [comment]
In your case, you should use `itemTap`, which will allow you to take the index of the selected item. Check out this [example](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/ui-category/listview/creating-listview/creating-listview.component.html).
