### ISSUE TITLE
Android: All Button texts are capitalised

### ISSUE THREAD

**Issue by nmeissner-scottlogic** [NativeScript/nativescript-angular#131]
All text on Buttons I use is automatically capitalised even if I set text-transform:none in the css.

Any way I can avoid this?

**Comment by nsndeck** [comment]
The reason for this is the Android platform. The easiest way to achieve this is by using `FormattedString`:

```XML
<Button >
    <FormattedString>
        <Span text="Some text with small caps" ></Span>
    </FormattedString>
</Button>
```

**Comment by nsndeck** [comment]
Some follow-up: Since `FormattedString` does not working with the current version, you should use 0.0.41 version.
