### ISSUE TITLE
Tab-view androidTabsPosition not working on android platform version 3.4.2

### ISSUE THREAD

**Issue by jannotabamo** [NativeScript/nativescript-angular#1311]
PSST! Want to get faster responses to bug reports and important issues? Help us keep the issue tracker organized by:

- Reporting bugs. Please include all details about the problem and provide a sample app (consider using the [playground](https://play.nativescript.org) for this.
- Proposing features and enhancements.
- Discussing implementation details.

Please move all other content to the [forums](https://discourse.nativescript.org/).

**Comment by tsonevn** [comment]
`androidTabsPosition` property is related to a new feature introduced in NativeScript 4.0
