### ISSUE TITLE
Listview taps are not recognised when placed inside a TabView in iOS

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1317]
_From @GBeushausen on May 6, 2018 10:56_

Hi,

i'm evaluating NativeScript using the [WhatsApp Template](https://github.com/Especializa/nativescript-whatsapp-template) .

The problem here is that in iOS only the first tap on a chat item is recognised and all the subsequent taps are ignored. I narrowed the problem down so that i know that the problem is related to the ListView inside the Tabview. If i remove the TabView the application works correctly.

So if we have this code here:

```
<TabView [(ngModel)]="selectedIndex" iosIconRenderingMode="automatic">
  <ng-template tabItem title="Chats" [iconSource]="selectedIndex === 3 ? 'res://tabs/chats-filled' : 'res://tabs/chats'">
    <StackLayout>
      <ns-chats></ns-chats>
    </StackLayout>
  </ng-template>
</TabView>
```

and this for the ListView:

````
<ListView [items]="chats" class="list-group" (itemTap)="goToChat($event)">
  <ng-template let-chat="item" let-index="index">
    <GridLayout rows="auto, auto" columns="auto, *, auto" class="list-group-item">
      <Image row="0" col="0" rowSpan="2" [src]="chat.contact.avatar" class="thumb"></Image>
      <Label row="0" col="1" [text]="chat.contact.name"></Label>
      <Label row="1" col="1" [text]="chat.text" class="body"></Label>
      <Label row="0" col="2" [text]="chat.when | shortWhen | uppercase"
        class="body time" [class.time-unread]="chat.unread > 0"></Label>
      <StackLayout row="1" col="2" orientation="horizontal" class="m-x-auto">
        <Label *ngIf="chat.muted" [text]="'mdi-volume-off'|fonticon" class="mdi muted"></Label>
        <Label *ngIf="chat.unread > 0" [text]="chat.unread" class="body unread"></Label>
      </StackLayout>
    </GridLayout>
  </ng-template>
</ListView>

```

How can we make it work correctly inside the TabView?

Thanks

_Copied from original issue: NativeScript/NativeScript#5788_

**Comment by tsonevn** [comment]
Hi @GBeushausen,
I tested the itemTap event, while the ListView is inside a TabView, however, I was unable to recreate an issue.
For your convenience, I am attaching a sample project. You can review it and make the needed changes, which will allow us to recreate the problem.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1979591/Archive.zip)

**Comment by GBeushausen** [comment]
Hi @tsonevn 
Thank you very much for your quick help. Thanks to your sample i could figure out it was a bug in the whatsapp template that i used. In the TabView there was a [(ngModel)]="selectedIndex". This was causing the issue. Not quite sure yet what's wrong but since the code using this variable is only for Android the original author probably missed some code regarding to iOS.

Anyway, thanks now i know it's not a NativeScript issue. NativeScript seems to be awesome.
