### ISSUE TITLE
Android: ActionBar icon not appearing.

### ISSUE THREAD

**Issue by nmeissner-scottlogic** [NativeScript/nativescript-angular#132]
I tried to use '< ActionBar android.icon="res://icon" android.iconVisibility="always">' but the icon isn't showing.

Is the setting of the icon supported yet?

Cheers,

Nils

**Comment by vakrilov** [comment]
Can you please try this with the latest version of the `nativescript-angular` module. 
We have have only recently(#124) enabled setting nested properties (like `android.icon` and `android.iconVisibility`).

**Comment by nmeissner-scottlogic** [comment]
Thanks, I wasn't aware of the newer version. It works now.

Cheers,

Nils
