### ISSUE TITLE
Unable to load 3D Secure page with ios webview

### ISSUE THREAD

**Issue by angularturk** [NativeScript/nativescript-angular#1321]
Hello,

The webview component doesn't render 3D secure pages. 

```js
<WebView src="https://www.denizbank.com/3ds/default.aspx"></WebView>
```

The page above works fine on desktop and mobile browsers. Even it renders correctly on nativescript's playground/preview apps.

But when we try to run it locally with;

```bash
tns run ios
```

it renders blank page.

Tried to debug with _WebView.loadFinishedEvent_ when we try to visit the url above the event callback never triggers.

Here is a playground [link](https://play.nativescript.org/?template=play-ng&id=RfNxwX). 

P.S: nativescript preview renders the page fine.

tns version 4.0.1

**Comment by NickIliev** [comment]
@angularturk the thing is that on iOS you should explicitly allow the loading of HTTPS pages (which is done by default in Playground). 

This can be done either by entirely allowing the arbitrary loads (not recommended by Apple)as follows:
in your `App_Resources/iOS/info.plist` file add
```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

**The proper way** to do that is to add only the domains you are going to use and trust as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/App_Resources/iOS/Info.plist#L46-L62)

**Comment by angularturk** [comment]
@NickIliev thanks for the answer it solves the issue. This was working fine without the NSAllowsArbitraryLoads conf for most of the https pages.

**Comment by gungoromer** [comment]
@NickIliev thanks for the answer. It worked for me.
