### ISSUE TITLE
TypeError: org.nativescript.widgets.TabViewPager is not a constructor after update tns-core-modules 4.0.0

### ISSUE THREAD

**Issue by kumarandena** [NativeScript/nativescript-angular#1323]
Hi Team, 

After updating tns-core-modules to version 4.0.0, i got the typo 'TypeError: org.nativescript.widgets.TabViewPager is not a constructor'. 

**Environment**
NS Angular
Android

**tns info**
PS E:\RAA> tns info
√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 4.0.0 and the latest available version is 4.0.1.
√ Component tns-core-modules has 4.0.0 version and is up to date.
√ Component tns-android has 4.0.1 version and is up to date.
‼ Update available for component tns-ios. Your current version is 3.3.0 and the latest available version is 4.0.1.

**Console**
System.err: com.tns.NativeScriptException:
System.err: Calling js method onCreateView failed
System.err: TypeError: org.nativescript.widgets.TabViewPager is not a constructor
System.err: File: "file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js, line: 317, column: 24
System.err: StackTrace:
System.err:     Frame: function:'TabView.createNativeView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 317, column: 25
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 492, column: 35
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'RadSideDrawer.eachChildView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/nativescript-pro-ui/sidedrawer/sidedrawer-common.js', line: 148, column: 13
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'LayoutBaseCommon.eachChildView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js', line: 125, column: 26
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 534, column: 19
System.err:     Frame: function:'ContentView.eachChildView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/content-view/content-view.js', line: 70, column: 13
System.err:     Frame: function:'PageBase.eachChildView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/page/page-common.js', line: 120, column: 40
System.err:     Frame: function:'ViewCommon.eachChild', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view/view-common.js', line: 855, column: 14
System.err:     Frame: function:'ViewBase._setupUI', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 533, column: 14
System.err:     Frame: function:'ViewBase._addViewCore', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 431, column: 18
System.err:     Frame: function:'ViewBase._addView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 420, column: 14
System.err:     Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 576, column: 24
System.err:     Frame: function:'FragmentClass.onCreateView', file:'file:///data/data/org.nativescript.RAA/files/app/tns_modules/tns-core-modules/ui/frame/fragment.js', line: 27, column: 38
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.FragmentClass.onCreateView(FragmentClass.java:40)
System.err:     at android.app.Fragment.performCreateView(Fragment.java:1700)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
System.err:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
System.err:     at android.app.BackStackRecord.run(BackStackRecord.java:684)
System.err:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1453)
System.err:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
System.err:     at android.os.Handler.handleCallback(Handler.java:733)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:146)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5602)
System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
System.err:     at dalvik.system.NativeStart.main(Native Method)
ActivityManager: Process org.nativescript.RAA (pid 21801) (adj 0) has died.

**package.json**
`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.RAA",
    "tns-ios": {
      "version": "3.3.0"
    },
    "tns-android": {
      "version": "4.0.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/router": "4.4.6",
    "crypto-js": "^3.1.9-1",
    "lodash": "^4.17.4",
    "moment": "^2.20.1",
    "nativescript-angular": "4.4.1",
    "nativescript-bottombar": "^3.0.7",
    "nativescript-filterable-listpicker": "^1.0.5",
    "nativescript-imagepicker": "^4.0.1",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-pro-ui": "3.2.0",
    "nativescript-snackbar": "^2.0.0",
    "nativescript-sqlcipher": "^1.0.0",
    "nativescript-theme-core": "1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-zip": "^3.0.0",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "tns-core-modules": "^4.0.0",
    "tns-platform-declarations": "^3.4.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "3.2.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.2",
    "nativescript-dev-typescript": "0.5.1",
    "node-sass": "4.5.3",
    "tslint": "5.8.0",
    "typescript": "2.4.2"
  }
}`

Thanks in advance.

**Comment by tsonevn** [comment]
Hi @kumarandena,

Try to remove the platform with `tns platform remove android`, delete `node_modules` and `hooks` folders. Make sure to delete the app from the device or simulator, which you used for testing. Then rebuild the app ->`tns run android`.

If the issue persists, please send us the project.

**Comment by kumarandena** [comment]
Hi @tsonevn,

Update the Nativescript Cli to V 4.0.1 and rebuild the project did the trick. 
Now its working fine. 

Thanks for your support.
