### ISSUE TITLE
[TabView] Icons/Text shows in the top and reaches the content

### ISSUE THREAD

**Issue by relez** [NativeScript/nativescript-angular#1329]
Hi guys, I am working on a page with contains a TabView and using font-awesome icons instead of text. The icons are showing in the top of the TabView and part of them are shown inside the current content. I have been searching and I couldn’t find a way to center them vertically. I have shared my code and a screenshot. This only happens in the iPad...

HTML:

```
<TabView [(ngModel)]="_dashboardSelectedIndex" class="tab-view font-18 fa">
    <StackLayout class="no-fa" *tabItem="{title: '\uf085'}">
    </StackLayout>
    <StackLayout class="no-fa" *tabItem="{title: '\uf201'}">
    </StackLayout>
    <StackLayout class="no-fa" *tabItem="{title: '\uf025'}">
    </StackLayout>
    <StackLayout class="no-fa" *tabItem="{title: '\uf200'}">
    </StackLayout>
</TabView>
```
[
![tabview-nativescript-ng](https://user-images.githubusercontent.com/3420851/40120843-2c376aba-58ee-11e8-81f4-6dee3f7a662e.png)
](url)

Thanks!

**Comment by tsonevn** [comment]
Hi @relez,
This is a known issue, which is described in [this ](https://github.com/NativeScript/NativeScript/issues/3402) thread. To solve the issue, you can set an icon instead of using iconFont and set up a title. For example:
```
<TabView iosIconRenderingMode="alwaysOriginal"  class="tab-view font-18 fa">
        <StackLayout class="no-fa" *tabItem="{ title:'test', iconSource: 'res://icon'}">
        </StackLayout>
        <StackLayout class="no-fa" *tabItem="{ title:'test', iconSource: 'res://icon'}">
        </StackLayout>
        <StackLayout class="no-fa" *tabItem="{ title:'test', iconSource: 'res://icon'}">
        </StackLayout>
        <StackLayout class="no-fa" *tabItem="{ title:'test', iconSource: 'res://icon'}">
        </StackLayout>
    </TabView>
```
