### ISSUE TITLE
Icons are now working in nativescript angular 

### ISSUE THREAD

**Issue by MuhammadTahir92** [NativeScript/nativescript-angular#1333]
hey every one , I am using icons in nativescript with angular but its not working ,
I try icomoon icons , material icons, font-aweasome but all of them have issues are not working for me 
My package.json is 
`
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.loginScreen",
    "tns-android": {
      "version": "4.0.1"
    },
    "tns-ios": {
      "version": "3.4.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "font-awesome": "^4.7.0",
    "nativescript-angular": "~5.3.0",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-ng2-fonticon": "^1.3.4",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.5.2",
    "tns-core-modules": "~4.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.5.0",
    "nativescript-dev-typescript": "~0.7.0",
    "typescript": "~2.7.2"
  }
}

`

Hear is my fonts folder 
![image](https://user-images.githubusercontent.com/25048331/40251204-810e1c1e-5a8d-11e8-9e78-d4e78e6edbde.png)

and my html looks like this
![image](https://user-images.githubusercontent.com/25048331/40251555-72e346d6-5a8e-11e8-9da0-d447a872a761.png)
![screenshot_20180518-232803](https://user-images.githubusercontent.com/25048331/40251675-d8e4c59a-5a8e-11e8-9505-d242ce17eaf1.png)

**Comment by racknoris** [comment]
In case of Font Awesome, use this in your css:
```
.font-awesome {
    font-family: "FontAwesome";
}
```
Then in your html, if you want a phone icon, you would do: 
`<Label text="&#xf095;" class="font-awesome"></Label>`

**Comment by MuhammadTahir92** [comment]
![image](https://user-images.githubusercontent.com/25048331/40252981-f37f4bb0-5a92-11e8-9da9-f6126c835dbe.png)

still same

**Comment by MuhammadTahir92** [comment]
i have fontawesome-webfont.tff in fonts folder but still the same

**Comment by racknoris** [comment]
Perhaps in the css, try this:
 
```
.font-awesome {
    font-family: "fontawesome-webfont";
}
```

**Comment by MuhammadTahir92** [comment]
No still same

**Comment by tsonevn** [comment]
Hi @MuhammadTahir92,
Check whether you are setting up the correct font name as it is described in the [documentation](https://docs.nativescript.org/ui/icon-fonts#using-icon-fonts-in-nativescript):
> Do not forget to set the Label's font-family to the name of your font either through CSS, XML or code-behind. Remember: Android needs the actual filename (without extension) whereas iOS needs the font name. To be cross-platform-ready, you can provide both.

Also, it will help if you provide sample project, which could be used for debugging.

**Comment by MuhammadTahir92** [comment]
hey @tsonevn  @racknoris the problem is solved the font-family is right and every thing is working fine the issue is i am using sass not just css so i add styling in app.css but not specifying in app.android.scss or app.ios.sass thats why its not working

**Comment by jaygandhi49** [comment]
> hey @tsonevn @racknoris the problem is solved the font-family is right and every thing is working fine the issue is i am using sass not just css so i add styling in app.css but not specifying in app.android.scss or app.ios.sass thats why its not working , I just add the font family in common sass for both ios and android and it works .

still same issue please add proper solution

**Comment by belachkar** [comment]
@MrCroft Thanks, works for me. _For **Fontawesome 4.7**_:
- move `fonts` directory to `src` folder instead of `app`.
- Apply the font-familly to the scpecific class
```css
.fa {
  font-family: "FontAwesome", "fontawesome-webfont";
}
```
- Applying the class to the ns element (class:`fa`, text:`the unicode`):
```html
<label col="0" class="sidedrawer-list-item-text fa" text="&#xf05a;"></label>
```
I hope it helps
