### ISSUE TITLE
(Question) Datepicker - select only month and year.

### ISSUE THREAD

**Issue by csi-stasik** [NativeScript/nativescript-angular#1338]
Hi, What is the way to hide the day in Datepicker and allow to choose only month and year? (Android & IOS)

I suppose I need to access native components of each platform, but i can't succeed to do that.

I have a reference of datePicker doing this:

```
...

 @ViewChild('datePicker') datePicker: ElementRef;

...

 ngOnInit() {

        const datePicker: DatePicker = this.datePicker.nativeElement;
        datePicker.minDate = new Date(this.params.context.min);
        datePicker.maxDate = new Date(this.params.context.max);
        
        let dayId = app.android.context.getResources().getIdentifier("android:id/day", null, null);  // <- I get some id
}

...
```

But how to use this dayId to setVisibility(View.GONE)?

`console.log(datePicker.android) // -> is always undefined.`

Thanks

**Comment by tsonevn** [comment]
Duplicate of [#1338](https://github.com/NativeScript/nativescript-angular/issues/1338)
