### ISSUE TITLE
 touch event programmatically

### ISSUE THREAD

**Issue by hamdiwanis** [NativeScript/nativescript-angular#1339]
is it possible to fire touch event on a view programmatically? using x, y coordinates?

**Comment by tsonevn** [comment]
Hi @hamdiwanis,
Thank you for your interest in NativeScript.
Regarding the question.
Similar functionality does not exist in `the tns-core-modules`. Also for any further questions, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests.
