### ISSUE TITLE
Nativescript ListView loadmoreItems loading indicator like radListView?

### ISSUE THREAD

**Issue by jannotabamo** [NativeScript/nativescript-angular#1341]
Is there any workaround to show some loading indicator with loadMoreItems in Listview? for great user experience :)

**Comment by NickIliev** [comment]
@jannotabamo perhaps using `ActivityIndicator` with your own implementation that shows/hides the indicator when the event is triggered.

Please note that the repository is for logging issues, bugs and features related to NativeScript Angular.
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)
