### ISSUE TITLE
TextField text cursor going to the first position after value update 

### ISSUE THREAD

**Issue by yassern** [NativeScript/nativescript-angular#1348]
This bug is android only, I have a Slider and a TextField that have the same ngModel attribute reference and when the value of that attribute is updated, the cursor goes to the first position of the input, no matters if the user use the textfield or the slider.

Sample project:
https://play.nativescript.org/?template=play-ng&id=O0oLGQ&v=1

**Comment by tsonevn** [comment]
Hi @yassern,
Thank you for contacting us.
I tested this case and found that it is reproducible also in a non-Angular [project](https://play.nativescript.org/?template=play-js&id=uI4SZ4). For further info, please keep track on the issue.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#5873
