### ISSUE TITLE
Feature: Enable nesting page router outlets

### ISSUE THREAD

**Issue by MartoYankov** [NativeScript/nativescript-angular#1351]
With nativescript-angular 6.0 we will enable sibling named page-router-outlet at root level to enable the scenario with root TabView with navigations inside the tabs. This scenario is demonstrated in the template -  https://github.com/NativeScript/template-tab-navigation-ng.

We would like to also support nested sibling named page-router-outlet. This will enable more scenarios with PROs that are now only possible with NG <router-outlet>. Here are two scenarios:

1. Having a root page-router-outlet (PRO) that initially navigates to a Login page and upon login, navigates to a TabView with nested PRO navigations:
 - PRO
    - Login
    - Tabs
        - PRO: Tab 1 Master --> Tab 1 Detail
        - PRO: Tab 2 Master --> Tab 2 Detail

2. Having a root RadSideDrawer that can switch between regular pages and TabView with nested PRO navigations:
 - RadSideDrawer
    - PRO
        - Page 1 Master --> Page 2 Detail
        - Tabs
            - PRO: Tab 1 Master --> Tab 1 Detail
            - PRO: Tab 2 Master --> Tab 2 Detail

**Comment by manojdcoder** [comment]
@NickIliev / @vakrilov / @sis0k0  Are we depended on Angular to fix any issues on their end to complete this feature? Just curious, as I'm aware that there are few issues with Angular's router when nesting named outlets.

**Comment by Bolhy10** [comment]
@NickIliev  @sis0k0  @vakrilov ???

**Comment by IAMtheIAM** [comment]
This is a greatly desired feature

**Comment by NickIliev** [comment]
@IAMtheIAM @Bolhy10 @manojdcoder @YvesCandel thank you guys for your feedback. Indeed, we are aware that this feature is highly desirable and we are planning it for the next release of `nativescript-angular`. We will post all related updates here.

**Comment by IAMtheIAM** [comment]
@NickIliev That's great news! Thanks for the update.

**Comment by gbaldeck** [comment]
That's awesome @NickIliev. Will it be in {N} 4.2 or a later version?

**Comment by tskweres** [comment]
Awesome! +1 for lazy loading the tab views too :)

**Comment by NickIliev** [comment]
@gbaldeck the 4.2 release is a few days away and this feature is not ready and is still in the planning phase. I am sorry if I had misled anyone about the release date - the feature is planned for the **4.3** but still, in the end, it all depends on the complexity of the feature.

**Comment by gbaldeck** [comment]
@NickIliev In the meantime is there a workaround for having Tabs work with the RadSideDrawer?

**Comment by tskweres** [comment]
@gbaldeck @NickIliev I could try making a test app using just <router-outlet> and not <page-router-outlet> that has parents and children:

Login (eager)
Tabs (eager)
    -- Tab one (lazy) (aux named outlet)
        -- Tab Detail one
    -- Tab two (lazy) (aux named outlet)
        -- Tab Detail two

But - i'm curious if the page and header transitions, back button etc will still work as expected.

re:  https://github.com/angular/angular/issues/10981

**Comment by MartoYankov** [comment]
@sokolovstas This is indeed a valid workaround and in fact is the suggested pattern for login with root TabView in native mobile.

@hettiger The nested routes/routes with children problems are indeed tied to this feature request. However, the problems with lazy loading named outlet routes are a separate issue and is not well handled in angular. See https://github.com/angular/angular/issues/24657 .

**Comment by hettiger** [comment]
@sokolovstas @MartoYankov 

The suggested modal view workaround leads me to another problem:
Modal view navigation requires a PRO and it seems to cause issues?

A login view should support creating accounts and resetting lost passwords.
Navigation is a requirement for good UX in that case thought.

**Comment by sokolovstas** [comment]
I agree that this is workaround only. For now, I have 3 modals and open one and close another on navigation.

**Comment by MartoYankov** [comment]
@hettiger @sokolovstas  The navigation inside a modal with PRO should work. Can you please share the issue you experience?

**Comment by hettiger** [comment]
@MartoYankov 

Then I am probably doing it wrong.

How am I supposed to register the modal routes?

Here's the active route when opening the modal:

```
    {
        path: "",
        redirectTo: "/(aTab:a//bTab:b//cTab:c)",
        pathMatch: "full"
    },
```

Children are not supported when using `redirectTo`.

That's what the examples suggest:

https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/70675f2de9f8238418b93e961901cc31d0d42507/app/ng-ui-widgets-category/modal-page/modal-page-examples.module.ts#L24-L38

I don't see how the pieces can be put together.
My attempts so far didn't work out unfortunately.

If you tell me how to register the routes, I'll give it a shot and share a playground here if I'm still experiencing issues.

**Comment by MartoYankov** [comment]
@hettiger I created a quick playground demo [here](https://play.nativescript.org/?template=play-ng&id=Xl73dO&v=5). It displays two scenarios - a modal as a child to a route in the home tab and a login modal that opens from the root app component.

**Comment by hettiger** [comment]
@MartoYankov Thank you for the playground. That was really helpful! :-)

**Comment by mendeljacks** [comment]
Trying to achieve the functionality described in scenario 1, login page and a tab view, would there be a way to achieve this without a modal by using angular router instead of nsrouter for the login page? I have been fiddling with a modal, ngIf and [visibility] to recreate the effect of an actual login route but modals just dont cut it.

**Comment by mendeljacks** [comment]
My desired structure is:
const routes: Routes = [
    { path: "", redirectTo: "login", pathMatch: "full" },
    { path: "login", component: LoginComponent },
    { path: "home", children: [
        { path: "", redirectTo: "/(ordersTab:orders//productsTab:products//shelvesTab:shelves)", pathMatch: "full" },
        { path: "orders", component: OrdersComponent, outlet: "ordersTab" },
        { path: "products", component: ProductsComponent, outlet: "productsTab" },
        { path: "shelves", component: ShelvesComponent, outlet: "shelvesTab" },
    ]}
    
];

could it be that the pathMatch full is messing with the nested routes?

**Comment by mendeljacks** [comment]
To put an end to this issue and prove nativescripts viability as a competing candidate to react native, I'm offering $100 incentive to the first developer who can help achieve the above desired structure

**Comment by chrisbekas** [comment]
I gather this is also an issue for {N} core? I've trying to navigate to my login frame (unsuccessfully) using `application.run()`. [Question](https://stackoverflow.com/questions/51942195/maximum-call-stack-size-exceeded-error-when-opening-application) over on stackoverflow.

**Comment by MartoYankov** [comment]
@chrisbekas Actually, this is quite possible to implement in {N} core. I answered your SO [question](https://stackoverflow.com/questions/51942195/maximum-call-stack-size-exceeded-error-when-opening-application/52000678#52000678).

The reason why this works in {N} core and not in NG is because of the default NG location history, which is browser based and linear. Nesting frames combined with tab navigation creates a non-linear history which must be handled differently. In other words, the main problem with nesting PROs is the back navigation. We`re actively working on this issue.

@mendeljacks The structure you specified should be possible. It's possible the redirect doesn't work, but you can navigate directly from login to `home/(ordersTab:orders//productsTab:products//shelvesTab:shelves)`. However, as I mentioned above the back navigation in this scenario won't work correctly.

**Comment by chrisbekas** [comment]
@MartoYankov Thanks so much Martin, works a treat!

**Comment by hackerunet** [comment]
This also disables RadSideDrawer position to be placed over the action bar of child elements, in the original RadSideDrawer template the app.component.html template has the main radsidedrawer directive and the page-router-outlet as child of it, if I place the radSideDrawer as a secondary element rendered inside the main page-router-outlet the menu never gets its position over the action bar of all child elements. no matter what we do, the menu is under all action bars on all modules.
app.component.html
```
<page-router-outlet class="page page-content"></page-router-outlet>
```
menu.component.html
```
<!--
RadSideDrawer is a UI component part of the Progress NativeScript UI set of components.
Learn more about the RadSideDrawer UI component and how it can be customized in this documentation article:
http://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/SideDrawer/getting-started
-->
<RadSideDrawer #menuDrawer [drawerTransition]="sideDrawerTransition">
    <GridLayout tkDrawerContent rows="auto, *" class="sidedrawer sidedrawer-left">
        <StackLayout row="0" class="sidedrawer-header">
            <Label class="sidedrawer-header-image fa" text="&#xf2bd;"></Label>
            <Label class="sidedrawer-header-brand" text="User Name"></Label>
            <Label class="footnote" text="username@mail.com"></Label>
        </StackLayout>

        <ScrollView row="1">
            <StackLayout class="sidedrawer-content">
                <GridLayout columns="auto, *" class="sidedrawer-list-item" [class.selected]="isComponentSelected('/home')" (tap)="onNavItemTap('/home')">
                    <Label col="0" text="&#xf015;" class="fa"></Label>
                    <Label col="1" text="Home" class="p-r-10"></Label>
                </GridLayout>

                <GridLayout columns="auto, *" class="sidedrawer-list-item" [class.selected]="isComponentSelected('/browse')" (tap)="onNavItemTap('/browse')">
                    <Label col="0" text="&#xf1ea;" class="fa"></Label>
                    <Label col="1" text="Browse" class="p-r-10"></Label>
                </GridLayout>

                <GridLayout columns="auto, *" class="sidedrawer-list-item" [class.selected]="isComponentSelected('/search')" (tap)="onNavItemTap('/search')">
                    <Label col="0" text="&#xf002;" class="fa"></Label>
                    <Label col="1" text="Search" class="p-r-10"></Label>
                </GridLayout>

                <GridLayout columns="auto, *" class="sidedrawer-list-item" [class.selected]="isComponentSelected('/featured')" (tap)="onNavItemTap('/featured')">
                    <Label col="0" text="&#xf005;" class="fa"></Label>
                    <Label col="1" text="Featured" class="p-r-10"></Label>
                </GridLayout>

                <StackLayout class="hr-light"></StackLayout>

                <GridLayout columns="auto, *" class="sidedrawer-list-item" [class.selected]="isComponentSelected('/settings')" (tap)="onNavItemTap('/settings')">
                    <Label col="0" text="&#xf013;" class="fa"></Label>
                    <Label col="1" text="Settings" class="p-r-10"></Label>
                </GridLayout>
            </StackLayout>
        </ScrollView>
    </GridLayout>

    <StackLayout tkMainContent>
        <router-outlet name="mainapp" class="page page-content"></router-outlet>
    </StackLayout>
</RadSideDrawer>
```
app-routing.module.ts
```
import { NgModule } from "@angular/core";
import { Routes } from "@angular/router";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { LoginComponent } from "./login/login.component";
import { MenuComponent } from "./menu/menu.component";

const routes: Routes = [
    { path: "", redirectTo: "/menu", pathMatch: "full" },
    { path: "login", component: LoginComponent },
    { path: "menu", component: MenuComponent, children: [
            { path: "", loadChildren: "./home/home.module#HomeModule" },
            { path: "home", loadChildren: "./home/home.module#HomeModule" },
            { path: "browse", loadChildren: "./browse/browse.module#BrowseModule" },
            { path: "search", loadChildren: "./search/search.module#SearchModule" },
            { path: "featured", loadChildren: "./featured/featured.module#FeaturedModule" },
            { path: "settings", loadChildren: "./settings/settings.module#SettingsModule" }
    ]}
];

@NgModule({
    imports: [NativeScriptRouterModule.forRoot(routes)],
    exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
```
![simulator screen shot - iphone 8 plus - 2018-09-19 at 12 09 07](https://user-images.githubusercontent.com/897448/45769303-d9840880-bc04-11e8-891b-b946b2f78124.png)

**Comment by wvegteren** [comment]
Is there any news about this issue? Any thoughts about timing?
This issue is blocking our next app release 😟

**Comment by YvesCandel** [comment]
It's been 118 days since this had been reported! Is the NS team still actively developing the NS-Angular repo or...?

**Comment by manojdcoder** [comment]
@YvesCandel It's really unfortunate but I believe it is not a blocker at least if you use TabViews without router outlets inside and navigate to new pages on the parent outlet (like old times with {N} 3.x). It may not be desirable solution but works for now.

**Comment by YvesCandel** [comment]
We need page router outlets inside of our tabviews. Otherwise you're missing out on the whole "history per tab" feature which literally every tabview app on the market has.

**Comment by kspearrin** [comment]
Looks like it is assigned to the 6.2 milestone. Is this actively being worked on?

**Comment by MartoYankov** [comment]
@kspearrin Yes, this is actively developed. There is a branch `djenkov/nested-named-outlets` with the feature in progress. There is a new e2e app there - `nested-router-tab-view` for testing. Keep in mind there is still a lot of work to be done there.

**Comment by keerl** [comment]
I discovered an alternative solution to this problem. I used [Bottom Navigation](https://www.npmjs.com/package/nativescript-bottom-navigation) instead of TabView. 

[Here](https://github.com/keerl/tab-drawer-nav-alt-ng) is a sample project demonstrating it. Contains 4 tabs and a side drawer. Side drawer contains a link to a page and tab 4 contains a child page as well as a link to a normal page,

See demo gif below:
<img src="https://imgur.com/nLnWMXO.gif" width="250"/>

**Comment by tskweres** [comment]
@jbarnabe do you have a playground link you could send or a repo to look at?

**Comment by jbarnabe** [comment]
@tskweres hi, you can simply check out the officialy **tns-template-tab-navigation-ng** here : [https://github.com/NativeScript/template-tab-navigation-ng](url)

**Comment by MartoYankov** [comment]
@drewcovi I might have deleted it... Here is the example - https://play.nativescript.org/?template=play-ng&id=XfRwGm&v=8

**Comment by drewcovi** [comment]
@MartoYankov thanks so much! I misunderstood and thought your example would provide a nested page-router-outlet inside the modal itself. Seems that's not the case but appreciate you quickly putting this together!

**Comment by jbarnabe** [comment]
@MartoYankov so, i must open a bug report ?

**Comment by MartoYankov** [comment]
@jbarnabe Yes, please.

@drewcovi The example opens a modal view that has a page-router-outlet inside it and you can navigate in it. Isn't that what you are looking for?

**Comment by drewcovi** [comment]
@martoyankov yes! I’m on my way. And learning quite a bit as I go. 🙂

Thanks a million. This is a brilliant framework.

Now I’m sorting out how to style that tabview. But I’ll sort it out.

**Comment by jbarnabe** [comment]
@MartoYankov done : [https://github.com/NativeScript/nativescript-angular/issues/1567#issue-373500458](url).

**Comment by FBorgonjen** [comment]
@ADjenkov thank you for your effort in implementing this feature. We've been checking out the code since you've started working on it. It works like a charm in our application!

**Comment by tskweres** [comment]
@FBorgonjen  oh wow this is awesome, how can I get a hold of this, just npm i nativescript@latest? Is there a starter or test app I can fork?

**Comment by martinstofko219** [comment]
Thanks so much for implementing this feature, this is wonderful! Same question as @tskweres about how to get our hands on it/release schedule. Thanks again!

**Comment by manojdcoder** [comment]
Just tested the latest release for the modal navigation issue that I had for months, all works as expected now.

Great job, thanks!

**Comment by kspearrin** [comment]
I see that this was released with 6.2.0, great! Are there any docs on how to use nested paged router outlets?

**Comment by tskweres** [comment]
I'll pay someone for a starter with examples :)

**Comment by tskweres** [comment]
I'll pay someone for a starter with examples :)

**Comment by ouss4m4** [comment]
@tskweres i just installed
 nativescript-angular@next on my tns v4

And got it working
 i refered to the e2e nested-tabview for some code.  That's all

**Comment by kspearrin** [comment]
I tied running the e2e/nested-router-tab-view project from this repo, but it crashes on start.

**Comment by ouss4m4** [comment]
@kspearrin install naivescript-angular@next     first (check the package.json first ) this is what i did and run it

**Comment by kspearrin** [comment]
`e2e/nested-router-tab-view` is referencing `"nativescript-angular": "file:../../nativescript-angular"`. Seems like it should be the latest dev version?

**Comment by ouss4m4** [comment]
Yes i know it didn't work for me first till i installed @next (ref in package json will change)

**Comment by kspearrin** [comment]
@ouss4m4 Tried that and still doesn't seem to be working for me. Looks like its missing some resource asset or something.

```
An uncaught Exception occurred on "main" thread.
android.content.res.Resources$NotFoundException: Resource ID #0xfffffff6
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2134)
	at android.content.res.Resources.getAnimation(Resources.java:1167)
	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:107)
	at android.support.v4.app.FragmentManagerImpl.loadAnimation(FragmentManager.java:1102)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1600)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1641)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2415)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2200)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2153)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2063)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:725)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by jbarnabe** [comment]
@ADjenkov Hi, it's possible to provide an example that works ?

**Comment by ADjenkov** [comment]
Hi @jbarnabe, 
Please refer to https://github.com/ADjenkov/login-tabs-ng for a sample application that covers the scenario you had described. The last commit adds lazy loading for the `tabs` and its nested `players` /`teams`. You can check the initial commit for non lazy loaded approach.

_Note: Take a look at the `package.json`. The sample app uses tns-core-modules@next and nativescript-angular@next_

**Comment by TishoTM** [comment]
> Edit: wtih a template like this
> 
> PRO
> ...Login
> ...Tabs
> ......PRO: Tab 1 Master --> Tab 1 Detail
> ......PRO: Tab 2 Master --> Tab 2 Detail

That setup was possible with `"tns-core-modules": "4.1.1",` and `"nativescript-angular": "~5.3.0",`

What happened since then? I am planning to upgrade to nativescript 5 but I guess I might need to wait.

**Comment by jbarnabe** [comment]
> Hi @jbarnabe,
> 
> The docs along with some blog/spec for this feature are currently in progress so stay tuned for more official info. For now you can refer to https://github.com/ADjenkov/login-tabs-ng for a sample application that covers the scenario you had described. The last commit adds lazy loading for the `tabs` and its nested `players` /`teams`. You can check the initial commit for non lazy loaded approach.
> 
> _Note: Take a look at the `package.json`. The sample app uses tns-core-modules@next and nativescript-angular@next_

Hi, @ADjenkov, 

After exporting and testing your sample I have 2 problems : 

1/ I always have this errors in console just after launching the app (I have same problem with all my app after upgrading to tns-core-module 5.0.0+) 😖  : 
```
11-12 20:59:43.946  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
11-12 20:59:43.946  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
11-12 20:59:43.946  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
11-12 20:59:43.946  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
11-12 20:59:43.946  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
11-12 20:59:43.946  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
11-12 20:59:43.947  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
11-12 20:59:43.947  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1116)
11-12 20:59:43.947  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:996)
11-12 20:59:43.947  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:983)
11-12 20:59:43.947  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:967)
11-12 20:59:43.947  4597  4597 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:959)
```

2/ After a click on **"Go to home page"** an error occurs (I also have this problem with all my applications that have Lazy Loading hence my request for an working sample) : 
```
JS: Error: Cannot find module './app/tabs/tabs.module'
JS:     at file:///data/data/org.nativescript.nestedroutertabview/files/app/bundle.js:161:11 [angular]
JS:     at Object.onInvoke (file:///data/data/org.nativescript.nestedroutertabview/files/app/vendor.js:34929:33) [angular]
JS:     at file:///data/data/org.nativescript.nestedroutertabview/files/app/vendor.js:64160:34 [angular]
JS:     at Object.onInvokeTask (file:///data/data/org.nativescript.nestedroutertabview/files/app/vendor.js:34920:33) [angular]
JS:     at drainMicroTaskQueue (file:///data/data/org.nativescript.nestedroutertabview/files/app/vendor.js:63872:35) [<root>]
```

_Note : `tns preview --bundle` does not work either with same error like `ErrorHandler Stack: Error: Uncaught (in promise): Error: com.tns.NativeScriptException: Failed to find module: "./app/tabs/tabs.module", relative to: app//`_

**Comment by MartoYankov** [comment]
@TishoTM With the previous versions it was possible to do the scenario and it would work navigating forward. The main issue that led to lots of changes is that navigating back using the hardware buttons and the API didn't work in lots of scenarios.

@jbarnabe The first issue is already logged as a separate issue [here](https://github.com/NativeScript/android-runtime/issues/1210).

Regarding the second issue both the --bundle and --hmr options for `tns preview` are considered in beta state. There are a number of issues about them one of which is that they don't work with lazy loaded modules. `tns preview` without the options should work though. This is logged [here](https://github.com/NativeScript/nativescript-cli/issues/4128)

Please log any further problems that you encounter in separate issues. It's better for maintainability.

**Comment by jbarnabe** [comment]
@MartoYankov thx for reply and sorry for duplicate issues in this thread

**Comment by tskweres** [comment]
@ouss4m4 similar issue to above, I got the nativescript-angular/e2e/nested-router-tabview working, but it has two actionbars on the tabs page. Any idea what's causing this?

<img width="405" alt="screen shot 2018-11-14 at 10 35 56 pm" src="https://user-images.githubusercontent.com/520309/48530532-b15c0300-e85d-11e8-86e9-fa304442f9f9.png">

**Comment by tskweres** [comment]
Solved, silly me. Just add visibility hidden to the parent actionbar:

`
<ActionBar title="Tabs Component" class="action-bar" visibility="hidden"></ActionBar>
`

**Comment by seveneye** [comment]
cant seem to make it work in latest version. 
"tns-core-modules": "~5.0.2"
"nativescript-angular": "~7.0.0"

**Comment by seveneye** [comment]
Is it possible to make this

- PRO
- Login
- CustomComponent
- PRO
- Tabs
- PRO: Tab 1 Master --> Tab 1 Detail
- PRO: Tab 2 Master --> Tab 2 Detail

**Comment by artu-ole** [comment]
@MartoYankov so there's no way to run this feature with lazy loaded modules in an angular code shared project currently?
It would be quite useful to have a disclaimer somewhere in [code sharing docs](https://docs.nativescript.org/angular/code-sharing/intro) that one is getting into a beta state project there and some basic functionality would not be supported.

**Comment by MartoYankov** [comment]
@seveneye Yes, this should be possible. Take a look at this demo project - https://github.com/ADjenkov/login-tabs-ng.

@artu-ole I'm not sure where you got this from. The angular code sharing project should be working fine with lazy loaded modules with `tns run <platform> --bundle` as it is [documented](https://docs.nativescript.org/angular/code-sharing/build-process).

What currently doesn't work is any {N} NG project with lazy loaded modules with the `tns preview --bundle` command. The `tsn preview --bundle` command is in beta state and this is pointed in the [docs](https://docs.nativescript.org/tooling/docs-cli/project/testing/preview).

If you are having trouble with running an angular code sharing project,  please open a new issue.

**Comment by artu-ole** [comment]
@MartoYankov just lazy modules work a-okay. Lazy modules through page-router-outlet in a shared project - not so much. This feature is probably not the culprit, so I've created the issue with my troubles running all of this together: https://github.com/NativeScript/nativescript-angular/issues/1635

**Comment by tskweres** [comment]
Not sure if this is the place to write this - but does anyone know how to customize the tabs and make custom elements and designs? I find the tabs support and styling pretty bare-bones
