### ISSUE TITLE
iOS: Modal Dialog is transparent during showModal animation

### ISSUE THREAD

**Issue by cerireyhan** [NativeScript/nativescript-angular#1356]
Modal Dialog is transparent during showModal animation causing parent component view getting mixed with modal view until animation is complete.

"angular/animations": "~6.0.0",
"angular/common": "~6.0.0",
"angular/compiler": "~6.0.0",
"angular/core": "~6.0.0",
"angular/forms": "~6.0.0",
"angular/http": "~6.0.0",
"angular/platform-browser": "~6.0.0",
"angular/platform-browser-dynamic": "~6.0.0",
"nativescript-angular": "~6.0.0",
"tns-core-modules": "~4.1.0",

**Comment by tsonevn** [comment]
Hi @cerireyhan,
Can you provide more info about the problem? It will help if you provide a sample project, which could be used for debugging.

**Comment by cerireyhan** [comment]
Hi @tsonevn 
I created a sample app below, modal background is transparent during showModal animation in iOS.

[sample app](https://github.com/cerireyhan/nativescript-modal-dialog-animation-bug)

**Comment by jannotabamo** [comment]
Hi @tsonevn I experienced it also after upgraded to 6

**Comment by jannotabamo** [comment]
My workaround is I put a background color for the modal

**Comment by cerireyhan** [comment]
@tsonevn Can you update label of the issue?

**Comment by cerireyhan** [comment]
@tsonevn I created a playground [playground](https://play.nativescript.org/?template=play-ng&id=rP9MeR&v=2)
sorry for the problem in repo

**Comment by tsonevn** [comment]
Hi @cerireyhan,
In this case, you should setup the backgroundColor for the AbsoluteLayout, which is used in the modal page. For example:
```
<AbsoluteLayout backgroundColor="red">
	<Button (tap)="cancel()" class="btn btn-rounded-sm" text="Dismiss"></Button>
</AbsoluteLayout>
```
Then the color of the modal page will no longer be transparent while opening.
