### ISSUE TITLE
Items in ListView collapsing

### ISSUE THREAD

**Issue by DMarinsa** [NativeScript/nativescript-angular#1361]
Good Morning, my list view is displaying ok, but when I try to scroll through it, it's like if it was aplying another css and not displaying the height assigned by CSS

Also, this [plugin](https://github.com/bradmartin/nativescript-floatingactionbutton) is not displaying.

Could you help me?

https://play.nativescript.org/?template=play-ng&id=AY40xi&v=4

**Comment by tsonevn** [comment]
Hi @DMarinsa,
When you are setting up the height of the Label via CSS, you should set up the component inside some of the available Layouts(e.g GridLayout). This will help with the correct measuring the Label's height when the ListView cells are reloaded.  For example:
```
<ListView [items]="partidas" class="lista-partidas">
			<ng-template let-item="item">
				<GridLayout>
					<Label [text]="item" class="partida-item"></Label>
				</GridLayout>
			</ng-template>
		</ListView>
```

Regarding the nativescript-floatingactionbutton.
In NativeScript playground you can use a limited number of plugins, unfortunately, `nativescript-floatingactionbutton`  is not one of the supported plugins. Also if you are facing issues with the plugin, while building the app locally, please contact the author while using this [repository](https://github.com/bradmartin/nativescript-floatingactionbutton).
