### ISSUE TITLE
nativescript navigate clear history bug

### ISSUE THREAD

**Issue by PraktikerNeosoft** [NativeScript/nativescript-angular#1363]
Hi, I have a problem with Nativescript 4.0 and 4.1.0
When I navigate with clearHistory: true then I give this error in ios:
ERROR TypeError: null is not an object (evaluating 'navController.viewControllers')

```
this.routerExtensions.navigate(["/menu"], {
    clearHistory: true,
    animated: false
});
```
Please help me because I must use clearHistory.
Thnx Miklos

**Comment by tsonevn** [comment]
Hi @PraktikerNeosoft,
I tested this case while using the latest NativeScirpt version, however, was unable to recreate the issue on my side. For your convenience, I am attaching sample project. Please review it and make the needed changes, which will help us to recreate the problem.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2067803/Archive.zip)

**Comment by PraktikerNeosoft** [comment]
Archive Zip ok. I use nativescript-ui-sidedrawer and if I open sidedrawer and click menu with clearHistory true then get this error.
I think this nativescript-ui-sidedrawer plugin problem.
I search the solution again.
Thanx

**Comment by tsonevn** [comment]
Duplicate of [#685](https://github.com/telerik/nativescript-ui-feedback/issues/685)
