### ISSUE TITLE
Want a server to integrate in android

### ISSUE THREAD

**Issue by shubh234** [NativeScript/nativescript-angular#1365]
PSST! Want to get faster responses to bug reports and important issues? Help us keep the issue tracker organized by:

- Reporting bugs. Please include all details about the problem and provide a sample app (consider using the [playground](https://play.nativescript.org) for this.
- Proposing features and enhancements.
- Discussing implementation details.

Please move all other content to the [forums](https://discourse.nativescript.org/).

**Comment by tsonevn** [comment]
Hi @shubh234,
Can you provide more info about your case?

**Comment by shubh234** [comment]
I want to integrate a web server just like Nanohttpd in android mobile.

**Comment by tsonevn** [comment]
Hi @shubh234,
In your case, you can create a NativeScript plugin, which will allow you using the available iOS and Android libraries in the NativeScript project. In the plugin, you can also implement the functionality, which you need. For more info, you can review the below-attached link.
https://docs.nativescript.org/plugins/building-plugins

**Comment by shubh234** [comment]
I have tried to create Nativescript plugin and try to use java libraries but it doesn't work.
