### ISSUE TITLE
Subscribing to Multiple Gestures and Events 

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1369]
how to use multiple gesture event together ?

is there any direct binding available from view?

**Comment by tsonevn** [comment]
Hi @bhavincb,
You can register multiple gestures for a specific view component via code behind while using the component's `loaded` event or via HTML while registering callback method for each gesture that you need to use. For example:
HTML
```
<StackLayout class="page">
    <Label text="test test" (touch)="touchCallback($event)" (doubleTap)="doubleTapCallback($event)" textWrap="true"></Label>
    
</StackLayout>
```
TypeScript
```
public touchCallback(args){
        console.log("test touch");
    }
    public doubleTapCallback(args){
        console.log("test doubleTap");
    }
```

**Comment by bhavincb** [comment]
hii @tsoneven,
actually my question was slightly different.

how to use multiple gesture event together ?
like first `tap` and then `doubleTap` or `tap` and then  `hold` .

is there any direct binding available from view?

**Comment by tsonevn** [comment]
Hi, @bhavincb,
In this case, you should define the gestures via code behind, for example on the component loaded event. This will allow you to set a single callback for multiple gestures.

**Comment by bhavincb** [comment]
hii @tsonevn ,
but it will called separately for all the gestures defined. what if one needs chaining event like `tap and then hold` or `tap and then doubleTap`

**Comment by NickIliev** [comment]
@bhavincb you could create your own flags which can be raised when a set of events are called.
For example something like having a `false` flag which will become true once the user triggers both `touch and 'long press` events over a period of time or in a specific area.

**Comment by bhavincb** [comment]
can't be this added as feature?
