### ISSUE TITLE
Lazy loaded module route redirectTo ignored or not working

### ISSUE THREAD

**Issue by darkyelox** [NativeScript/nativescript-angular#1374]
I don't know if this is an Angular or Nativescript issue but this is not working with the latest Nativescript-angular projects, when we load a lazy module and in its routes there is an empty path that redirest to another path the `redirectTo` option is ignored, no matter if the path is wrong there is not error log and the view is not loaded, [here](https://play.nativescript.org/?template=play-ng&id=WO6e2M&v=1) i have a playground for showing the issue

If you go to `home-module.routing.ts` file you can see the configuration.

**Comment by jolafrite** [comment]
one question

```js
const routes: Routes = [
    { path: "", redirectTo: "/home", pathMatch: "full" }, <--- why do you need this ?
    { path: "home", component: HomeComponent }
];
```

can't you just do

```js
const routes: Routes = [
    { path: "", component: HomeComponent }
];
```

?

**Comment by NickIliev** [comment]
@darkyelox the default route in the lazily loaded component can be directly registered with:
```
{ path: "", component: HomeComponent } 
```

As done and shown [here](https://angular-2-training-book.rangle.io/handout/modules/lazy-loading-module.html). Not sure if the

**Comment by darkyelox** [comment]
Sure but this is a problem because if i want yo redirect to something more complex like a child route, like you suggest i must reorder my structure every time i want to go todo another view, this problem was not present in version 3.x of narivescript but in 4.x it is

**Comment by NickIliev** [comment]
Confirming that using `redirectTo` from lazily loaded module does not seem to work as expected.

**Comment by darkyelox** [comment]
I need redirectTo because i will have a module with all my navigation and i want to redirect from the empty route to every component using its path, i will have also an internal outlet so i will have a route with childs and i want to redirect using the path with outlet

**Comment by pbourdu** [comment]
+1

**Comment by NickIliev** [comment]
@darkyelox the issue is not a bug as  it appears that we should use the path without a slash
For example:
```TypeScript
const routes: Routes = [
    { path: "", redirectTo: "home", pathMatch: "full" },  // notice the redirectTo: "home" (lacks a slash)
    { path: "home", component: HomeComponent }
];
```

**Comment by darkyelox** [comment]
Remember that i'm talking about lazy loaded modules and the redirect not works no matters what i do, simply is ignored:

![image](https://user-images.githubusercontent.com/8183191/42174213-1e81b36c-7de7-11e8-901d-823e5763f910.png)

You can test it in the playground link in my first comment, i update it with your workaround and that not work, this issue must not be closed

**Comment by NickIliev** [comment]
@darkyelox I am investigating the issue at this very moment and will post any related information here. I am using `redirectTo` in a lazily loaded module [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/info/info.module.ts#L7-L8) and it works as expected n my side but still not working in your playground example. 

Reopening the issue until further information is available,

**Comment by NickIliev** [comment]
@darkyelox I was able to resolve your case with the usage of `children` routing property as shown [here](https://stackoverflow.com/a/41885916/4936697).

For your convenience, here is[ the modified Playground demo](https://play.nativescript.org/?template=play-ng&id=WO6e2M&v=5). The things that have changed are the lazily loaded routing table

home-routing.module.ts
```TypeScript
// home-routing.module.ts
const routes: Routes = [
    {
        path: '',
        children: [
            {
                path: '',
                redirectTo: 'home',
                pathMatch: 'full'
            },
            {
                path: 'home',
                component: HomeComponent
            }
        ]
    }
]
```

I've also changed the `app-routing.module.ts` file (mainly for readability to avoid multiple `home` paths but also to remove the `/` infront of the `main` path)
```TypeScript
// app-routing.module.ts
const routes: Routes = [
    { path: "", redirectTo: "main", pathMatch: "full" },
    { path: "main", loadChildren: "./home/home.module#HomeModule" }
];

```

**Comment by ishan123456789** [comment]
I was facing issues with lazy loading modules as I've been generating modules with VSCode and it was registering the modules and importing them in the root module. On removing the import in root module all went fine.

**Comment by ashikjs** [comment]
It work for my Angular 7...

{ path: '', redirectTo: '/dashboard', pathMatch: 'full', },

**Comment by prajilshresthaiw** [comment]
I was having this issues and after a day wasting searching for answers I figured out that I was adding
a slash in the app-routing file during redirection
 `{ path: '', redirectTo: '/dashboard', pathMatch: 'full', }, `make sure you don't have a / in redirectTo like 
`{ path: '', redirectTo: 'dashboard', pathMatch: 'full', },`

**Comment by codergauravsharma** [comment]
> I was having this issues and after a day wasting searching for answers I figured out that I was adding
> a slash `/` in the app-routing file during redirection
> `{ path: '', redirectTo: '/dashboard', pathMatch: 'full', }, `make sure you don't have a `/` in redirectTo like
> `{ path: '', redirectTo: 'dashboard', pathMatch: 'full', },`

this worked for me as well ! thanks !

**Comment by codergauravsharma** [comment]
> @darkyelox I was able to resolve your case with the usage of `children` routing property as shown [here](https://stackoverflow.com/a/41885916/4936697).
> 
> For your convenience, here is[ the modified Playground demo](https://play.nativescript.org/?template=play-ng&id=WO6e2M&v=5). The things that have changed are the lazily loaded routing table
> 
> home-routing.module.ts
> 
> ```ts
> // home-routing.module.ts
> const routes: Routes = [
>     {
>         path: '',
>         children: [
>             {
>                 path: '',
>                 redirectTo: 'home',
>                 pathMatch: 'full'
>             },
>             {
>                 path: 'home',
>                 component: HomeComponent
>             }
>         ]
>     }
> ]
> ```
> 
> I've also changed the `app-routing.module.ts` file (mainly for readability to avoid multiple `home` paths but also to remove the `/` infront of the `main` path)
> 
> ```ts
> // app-routing.module.ts
> const routes: Routes = [
>     { path: "", redirectTo: "main", pathMatch: "full" },
>     { path: "main", loadChildren: "./home/home.module#HomeModule" }
> ];
> ```

thanks for this ! this worked for me as well !

**Comment by kuttikrishnankodoth** [comment]
What ever , nothing is working for me than 
`const routes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    component: MainComponent,
    children: [
      {
        path: '',
        loadChildren: () => import('./gateways/gateways.module').then(m => m.GatewaysModule),
        pathMatch: 'full'
      },
      {
        path: 'auth',
        loadChildren: () => import('./authentication/authentication.module').then(m => m.AuthenticationModule),
      },
      {
        path: 'areas',
        loadChildren: () => import('./areas/areas.module').then(m => m.AreasModule)
      },`

**Comment by kuttikrishnankodoth** [comment]
no solution is working for me than 

const routes: Routes = [
  {
    path: '',
    pathMatch: 'full',
    component: MainComponent,
    children: [
      {
        path: '',
        loadChildren: () => import('./gateways/gateways.module').then(m => m.GatewaysModule),
        pathMatch: 'full'
      },
      {
        path: 'auth',
        loadChildren: () => import('./authentication/authentication.module').then(m => m.AuthenticationModule),
      },
      {
        path: 'areas',
        loadChildren: () => import('./areas/areas.module').then(m => m.AreasModule)
      },

**Comment by LeonVay** [comment]
Works fine on Angular 9.1.7:
`````
// parent 'main' module
const routes: Route = [
...
{
                path: 'cool',
                loadChildren: () => import('@libs/cool-feature').then((m) => m.CoolFeatureModule),
}
...

// inside cool-feature-routing.module
const coolRoutes: Routes = [{
    path: '',
    component: CoolLayoutComponent,
    children: [
        {
            path: '',
            redirectTo: 'first',
            pathMatch: 'full'
        },{
            path: 'first',
            component: CoolFirstComponent
       }
... //some other internal paths
]
@NgModule({
    exports: [RouterModule],
    imports: [RouterModule.forChild(diameterRoutes)]
})
export class CoolFeatureRoutingModule {
}

// and insdide CoolFeatureModule 
@NgModule({
    declarations: [
        CoolFirstComponent,
        CoolSecondComponent
    ],
    exports: [],
    imports: [
        CoolFeatureRoutingModule,  <-- issue was when this module was listed as a last item inside imports array
        CommonModule,
        FormsModule,
        CoreModule
    ]
})
export class CoolFeatureModule {}
`````
So again if CoolFeatureRoutingModule goes as a last element of NgModule imports array - redirection fails without any error in console. If CoolFeatureRoutingModule goes as a first element of NgModule imports array - everything works fine.

**Comment by darkyelox** [comment]
For everyone facing a similar problem using the RoutingModule as first import  in the imports of the module works as @LeonVay said, also as @NickIliev pointed we shouldn't use "/" in redirects ( mainly not in the root app routing module for loading a lazy module )
