### ISSUE TITLE
Feature request: Integration with Android's AccountManager for Oauth2.0 login with Google APIs

### ISSUE THREAD

**Issue by suparnavg** [NativeScript/nativescript-angular#1381]
Currently, the Enterprise Authentication service in Sidekick is geared toward the client ID, client secret model. However, for Oauth2.0 login on the android platform, Google lets an app use the[ Android AccountManger.](https://support.google.com/cloud/answer/6158849?hl=en#installedapplications&android)

Also, in the google console, if I create a new set of Android credentials for my existing web app, the auth credentials are in this form:
![image](https://user-images.githubusercontent.com/1419812/41341223-d1bcc2f8-6f16-11e8-8d15-a6e7433efd0a.png)

Would be cool if there was a way to do Enterprise auth using the Android AccountManager (for enterprises running on Google's G-Suite platform, for e.g.)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/sidekick-feedback#208
