### ISSUE TITLE
Race condition between app events and angular events

### ISSUE THREAD

**Issue by fthuin** [NativeScript/nativescript-angular#1386]
Hi,

There seems to be something counter-intuitive in the lifecycle of my app. I discovered it using nativescript-facebook plugin. Here are some code samples to add context.

In my `app.module.ts`, I add a listener to the app:

```
application.on(application.launchEvent, function(args) {
    console.log('launchEvent');
    nsFacebook.init('{{ fb_app_id }}');
});
```

In my `app.component.ts`, I use the angular hook onInit
```
    ngOnInit() {
        console.log('ngOnInit');
        // nsFacebook.init('{{ fb_app_id }}');
    }
```

What I would suppose is that the launchEvent of the application should be always triggered before the ngOnInit... But when I run

```tns run android```
application launch event is triggered first
app.component ngOnInit is triggered after

```tns deploy android --bundle --env.aot --env.uglify --env.snapshot --release ...```
app.component ngOnInit is triggered first
application launchEvent is triggered after

in the second case I have a `A valid Facebook app id must be set in the AndroidManifest.xml or set by calling FacebookSdk.setApplicationId before initializing the sdk.`

It might not be a real issue that you want to fix, but could you at least provide a sequence diagram or a little explanation about what is happening in the background, or even better, a solution on where to put code so that it's always executed before the first page is loaded?

Thank you for your time and your work

**Comment by NickIliev** [comment]
@fthuin for code that will bring effect globally in your application (e.g. firebase initialization) use the application events. For example you could use the `loaded` event of your layout root container.

```HTML
<StackLayout #root (loaded)="onStackLoaded($event)">
</StackLayout>
```

```TypeScript
loaded(args: EventData) {
    const stack = <StackLayout>args.object;
}
```

This would guarantee that the application has launched and then the stack has loaded.
