### ISSUE TITLE
ui-listview load-on-demand auto scroll to top

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1387]
when loading items on demand in RadListView. adding more item automatically scrolls to the top.
here is playground demo:[https://play.nativescript.org/?template=play-ng&id=E2d9wx&v=2](https://play.nativescript.org/?template=play-ng&id=E2d9wx&v=2)

**Comment by NickIliev** [comment]
@bhavincb please use [this repository](https://github.com/telerik/nativescript-ui-feedback/issues) for issues related to `RadListView`
