### ISSUE TITLE
ListView: (itemTap) ignored on Android

### ISSUE THREAD

**Issue by artdias90** [NativeScript/nativescript-angular#1391]
"nativescript-angular": "~6.0.0",
"angular/common": "~6.0.0",

I have the following list (followed documentation)
```
<ListView
    [items]="questions"
    (setupItemView)="onSetupItemView($event)"
    (itemLoading)="onItemLoading($event)"
    (itemTap)="onItemTap($event)"
    class="list-group"
    row="0">
      <ng-template>...
```

iOS working as expected. on Android, tap is not being triggered. using `tap=""` works for me, but I lose reference to the collection.
tested on 
- Nexus 5 / API 26 (emulated)
- Galaxy S6

**Comment by NickIliev** [comment]
@artdias90 I've used [this test application ](https://github.com/NickIliev/NS-Issues-2018-II/blob/master/nativescript-angular/issue-1391/app/item/items.component.ts#L22-L25)and on my side, the `itemTap` event works as expected.

However, keep in mind that in Angular applicaiton some Angular events might be triggered before the NativeScript's events (and the respective native events). For example, using `nsRouterLink`  inside your item template will cause the applicaiton to effectivly navigate before any `itemTap` logic is triggered.
