### ISSUE TITLE
Need Tabular display with ngFor gridLayout

### ISSUE THREAD

**Issue by sarvagayatri** [NativeScript/nativescript-angular#1396]
![image](https://user-images.githubusercontent.com/10768839/41754948-7610572a-75f2-11e8-8c75-165c5675f949.png)

I want to get grid like this. was unable to acheive as its displaying only last element. and my stores object is array coming from view, and need to bind it

**Comment by tsonevn** [comment]
Hi @sarvagayatri ,
I will suggest reviewing our Samples in the documentation about the [GridLayout](https://docs.nativescript.org/angular/ui/ng-ui-widgets/layouts#grid-layout) and [Border](https://docs.nativescript.org/ui/ns-ui-widgets/styling#border-basics) styling, which can help you in achieving the needed view.
For further how-to questions, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).
