### ISSUE TITLE
The pipe 'mypipe' could not be found

### ISSUE THREAD

**Issue by xjpmauricio** [NativeScript/nativescript-angular#1403]
Hi all, I'm trying to use pipes and I've developed my own very simplified pipe just to get things started but, I keep getting this error:
```
The pipe 'mypipe' could not be found
```

Here's the code to my pipe:
```
import {Pipe, PipeTransform} from '@angular/core';
@Pipe({
    name: 'welcome'
})
export class WelcomePipe implements PipeTransform {
  transform(value: string): string {
    let message = "Welcome to " + value;
    return message;
  }
} 
```
The html usage example:
```
[text]="'Heaven' | welcome"
```

In my app.module, I've tried to reference it almost everywhere (declarations, providers, etc) but with no luck. I'm also getting this problem with other components that use pipes on the html/xml side of the app.

Any ideias?

**Comment by tsonevn** [comment]
Hi @xjpmauricio,
The custom pipe should be registered in the module's `declarations`. You can check our sample project [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/ng-framework-modules-category/color/color-examples.module.ts#L31), where this scenario with the custom pipe is demonstrated. You can review the project and check what the differences between the sample and your project are. 

Also, it will help if you send us sample project, which can be used for debugging.

**Comment by xjpmauricio** [comment]
Hi, thanks for the quick response. The sdk sample project, contains this pipe: \app\ng-framework-modules-category\color\creating-colors\creating-colors.component.ts
...but, the pipe is contained inside a component.  On that same project, the pipe is referenced in a @NgModule, on the declarations section. If I try to import code from that project, the HexPipe pipe section of code only, and if I create a file containing only the pipe, I still get the same error. Could it be related to the way I'm declaring the pipe on the page I want to use it? I basically need a pipe I can use in multiple pages; a shared pipe I guess. This used to be a trivial thing to do on angular.

**Comment by xjpmauricio** [comment]
Hi, I made a teste using this template: tns create my-app-name --template tns-template-blank-ng
I created a pipe and a page where I use the pipe. I'm attaching the source code of the test app.
[pipetest.zip](https://github.com/NativeScript/nativescript-angular/files/2148899/pipetest.zip)

**Comment by tsonevn** [comment]
Hi @xjpmauricio,
You should declare the pipe in a home.module.ts file, where is also the declaration of the HomeComponent, and remove the ToKm from the app.module.ts file's declarations. For example:
```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptCommonModule } from "nativescript-angular/common";
import {ToKm} from "../pipes/km.pipe";
import { HomeRoutingModule } from "./home-routing.module";
import { HomeComponent } from "./home.component";

@NgModule({
    imports: [
        NativeScriptCommonModule,
        HomeRoutingModule
    ],
    declarations: [
        HomeComponent,
        ToKm
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class HomeModule { }

```

**Comment by xjpmauricio** [comment]
Hi @tsonevn, I removed all references to the pipe from app.module.ts and home.component.ts, I changed home.module.ts like you said and now it works. Thanks!!!
