### ISSUE TITLE
Singleton services when app suspended and resumed

### ISSUE THREAD

**Issue by margusbirk** [NativeScript/nativescript-angular#1408]
Can NativeScript with Angular configured to only create a single instance of a Service when user navigates out of application (suspended, possibly exited state) and later navigates back to application (resumed state). 

I am registering the Service in providers at the app.module.ts so it should be at the root most level (unless there is bootstrap scope or something similar?) and things are as expected - only a single instance of this service is created and shared between other components. 

However, when I navigate out of the app and then back to the app, a new instance is created. Is it possible configure/bootstrap in a way to always inject the same instance of a Service to all components in this scenario?

**Comment by NickIliev** [comment]
@margusbirk in the mobile development navigating out of the application might mean that your application is in the background or that it is completely removed from the background tasks (e.g. Activity is destroyed on Android). This means that for example in Andriod if the native `Activity`
 is destroyed (e.g. when the OS needs additional resources) the newly created application will bootstrap the Angular abstraction and create a new instance of your service.

If your scenario is to persist in-app data that is later obtained via service in your Angular abstraction then perhaps it is best to make sure that this data is stored permanently (e.g. via application-settings or SQLite database). The newly started application will use the Singelton instance of your service and in this case, you could obtain the stored info to pass the needed arguments/data
