### ISSUE TITLE
Change Background color of Selected Tab in TabView

### ISSUE THREAD

**Issue by darkyelox** [NativeScript/nativescript-angular#1409]
I want to change the background color of the button in a TabView when is selected, how i can achieve this if i can't select the TabViewItem directly or the API of the TabView don't have a tabSelectedBackgroundColor property, [here](https://stackoverflow.com/questions/31640563/how-do-i-change-a-tab-background-color-when-using-tablayout) is an example using Android native code

**Comment by NickIliev** [comment]
@darkyelox the properties that allow you to change the style of the selected color are [`selectedTabTextColor`](https://docs.nativescript.org/api-reference/classes/_ui_tab_view_.tabview#selectedtabtextcolor) (for both iOS and Android) and [`androidSelectedTabHighlightColor`](https://docs.nativescript.org/api-reference/classes/_ui_tab_view_.tabview#androidselectedtabhighlightcolor) for Android only. Currently, there are not other opti9ons to change the style of selected items via NativeScript module.
