### ISSUE TITLE
TabView documentation article

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/nativescript-angular#141]
Write an explaining how to use the [`TabView` directive](https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/directives/tab-view.ts).

**Comment by NathanWalker** [comment]
Hi @vakrilov I'd like to update the snippets to contain correct markup for this if you get a chance to just provide a sample here?

**Comment by vakrilov** [comment]
@nsndeck is working on the article - he will probably provide the snippets as well.

**Comment by nsndeck** [comment]
Article is already committed in master branch of documentation.
