### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file

### ISSUE THREAD

**Issue by zeesulehria** [NativeScript/nativescript-angular#1412]
Unable to apply changes on device: UKYTWOVGTG69RK55. Error is: Failed to build plugin nativescript-ng-shadow : 
Error: Command ./gradlew failed with exit code 1 Error output: 
 Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /Users/m.tahir/.gradle/wrapper/dists/gradle-4.4-bin/bgaq7vklkazwgxox0hdadxbvi/gradle-4.4-bin.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

how to solve this issue?

**Comment by tsonevn** [comment]
HI @zeesulehria,
From the provided Error log it seems that you have some issue with the `nativescript-ng-shadow` plugin. Regarding that, I will suggest [contacting](https://github.com/Especializa/nativescript-ng-shadow/issues) the author of the plugin, who can help in resolving the issue. 
This repository is used mainly for bug reporting and feature requests related to nativescript-angular.

Meanwhile,  I also tested the nativescript-ng-shadow's [demo](https://github.com/Especializa/nativescript-ng-shadow/tree/master/demo) app with the latest NativeScript and the app seems to be built and executed correctly. You can review the attached project.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2161952/Archive.zip)

**Comment by tsjly** [comment]
Jump into /User/username/.gradle/wrapper/dists/
There maybe many folders, open each one, check in which one there is a zip file, record the version number.
In gradle-wrapper.properties in the flutter project, replace the version number to the one you checked.
Done.

**Comment by ixhimanshu** [comment]
This usually happens because of the incompatible java JDK version. Please check your current java version using this command: **java --version**

If there is java installed already then remove that version first, after that install LTS version of java JDK from [https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html)
