### ISSUE TITLE
After android.content.Context.getTheme() error, app don't reflect changes.

### ISSUE THREAD

**Issue by ParVisual** [NativeScript/nativescript-angular#1423]
After this message error the CLI don't reflect the correct changes.

Android
Emulator: Nexus 5X API 28

- CLI: 4.1.2
- Cross-platform modules: 4.1.0
- Plugin(s):
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "~4.0.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.5.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.10.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~6.0.6",
    "tslint": "~5.8.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"

ERROR LOG:
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android
.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
JS:     android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:224)
JS:     android.app.AlertDialog$Builder.<init>(AlertDialog.java:465)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:954)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:946)
JS:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
JS:     android.app.Activity.performCreate(Activity.java:7136)
JS:     android.app.Activity.performCreate(Activity.java:7127)
JS:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
JS:     a...

This issue don't involve any part of my code. 
Apparently it's a core, or missing plugin issue.

I tried different Android versions, I unninstalled all dependencies and reinstalling again. Same with node.js, cli and tns.

**Comment by tsonevn** [comment]
Hi @ParVisual ,
Try to delete `node_modules` and `platforms` folders and rebuild the app `tns run <platform_name>`.
