### ISSUE TITLE
activityBackPressedEvent confirm exit

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-angular#1429]
I am trying to make the user confirm on back button press. I am using Nativescript + Angular
The issue is that the back button handling is not async in nativescript, so I can't really wait for the user input before calling ```data.cancel = true```.
So What I did is call  ```data.cancel = true``` then show the confirm dialog. Now my issue is how to close the page on confirmation.
I tried calling ```RouterExtensions.back```  and ```RouterExtensions.backToPreviousPage``` but they do nothing. 
I should mention that I am on the "root" path "" when I try to do that. Is that why ```back``` and ```backToPreviousPage``` are not working?

How can make my page close ? and thus the app actually close like it does if I don't call ```data.cancel = true```?

Thanks

**Comment by jibon57** [comment]
You can try like this:

```
if (!this.routerExt.canGoBackToPreviousPage()) {
    data.cancel = true;
    let options = {
        title: "Exit App",
        message: "Are you sure？",
        okButtonText: "OK",
        cancelButtonText: "Cancel",
        neutralButtonText: "Go to home"
    };

    dialogs.confirm(options).then((result: boolean) => {
        if (result) {
            java.lang.System.exit(0);
        } else if (typeof result == "undefined") {
            if (this.routerExt.router.url !== "/home") {
                this.routerExt.navigate(['home'], { clearHistory: true })
            }
        }
    });

}
```

**Comment by farfromrefug** [comment]
@jibon57 thanks but I don't really like the ```java.lang.System.exit(0);```. I would prefer the page(activity) to close normally

**Comment by jibon57** [comment]
@farfromrefug in this case you can follow this: https://stackoverflow.com/a/13197445/1281864

**Comment by farfromrefug** [comment]
@jibon57 This is simulate the "home" button. What I want is the exact same behaviour as the back button.

**Comment by jibon57** [comment]
@farfromrefug your question isn't clear to me. Better to use http://discourse.nativescript.org/ ?

**Comment by tsonevn** [comment]
HI @farfromrefug,
All dialogs, including the confirm, requires user interaction. To close the confirm the user should tap on the some of the available options. If you need further control on the pop-up window, which you need to display, you can create a [modal page](https://docs.nativescript.org/angular/ui/ng-ui-widgets/modal-page). The modal allows you to close it via code-behind. As @jibon57 mentioned, the best place for similar discussions will be [discourse](https://discourse.nativescript.org/) or [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by tsonevn** [comment]
Hi @farfromrefug,
From the provided code I am assuming that you are trying to make back navigation after the user click on the confirm's `ok` button. I tested this scenario and everything seems to work as expected. For your convenience, I am attaching a sample project. Also, bear in mind that if you are on the root page and call `this._routerExtensions.back();`, nothing will happen, because there is not page, where the app can navigate back.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2197199/Archive.zip)

**Comment by farfromrefug** [comment]
@tsonevn thanks for the sample. I think that's the case I am on the root page! I get that ```backToPreviousPage``` does nothing in this case. But ```back``` should close the activity in this case.
I mean that ```_routerExtensions.back()```  should have the same behaviour as the android "back" button. 
If you don't agree with that, at least there should be a way to programmatically simulate the behaviour of the android "back" button.  To my knowledge there is none. I tried directly closing the activity with "topmost().currentPage.android.activity.finish()" but then I get a crash when reopening the app

**Comment by tsonevn** [comment]
HI @farfromrefug,
You can check [nativescript-exit](https://www.npmjs.com/package/nativescript-exit). I haven't tested the plugin on my side, however, it can help in your case.

**Comment by farfromrefug** [comment]
@tsonevn I managed to get it to work with 
```typescript
this._routerExtensions.frameService.getFrame().android.activity.finish();
```
So that's good.

Now I still think ```_routerExtensions.back()``` should actually do that. if not what's the difference between ```_routerExtensions.back()``` and ```_routerExtensions.backToPreviousPage()``` ?
There should be a way do "back or close"

Thanks
