### ISSUE TITLE
Navigation within a Modal Dialog

### ISSUE THREAD

**Issue by phatakrajan** [NativeScript/nativescript-angular#1435]
I am trying to perform navigation over the Modal dialog. I referred https://docs.nativescript.org/angular/ui/ng-ui-widgets/modal-page for doing the same. I could successfully do that within a sample project which is created at 
https://play.nativescript.org/?template=play-ng&id=vLzkuH&v=8

However when i tried to replicate in my production code, i am getting a dialog box without any content.(with no errors) I have added my sample code on GIT

https://github.com/phatakrajan/ModalDialog

Can someone please guide me on what is the issue that content is not being shown on modal dialog?

**Comment by tsonevn** [comment]
Hi @phatakrajan,
I notice that you are using an old version of `nativescript-angular`. Update the `nativescript-angular` and all other `@angular` dependencies, while following the below-attached sample package.json.
```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": ""
	},
	"dependencies": {
		"@angular/animations": "~6.0.0",
		"@angular/common": "~6.0.0",
		"@angular/compiler": "~6.0.0",
		"@angular/core": "~6.0.0",
		"@angular/forms": "~6.0.0",
		"@angular/http": "~6.0.0",
		"@angular/platform-browser": "~6.0.0",
		"@angular/platform-browser-dynamic": "~6.0.0",
		"@angular/router": "~6.0.0",
		"nativescript-angular": "~6.0.0",
		"nativescript-theme-core": "~1.0.4",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~6.1.0",
		"tns-core-modules": "~4.1.0",
		"zone.js": "^0.8.26"
	},
	"devDependencies": {
		"babel-traverse": "6.26.0",
		"babel-types": "6.26.0",
		"babylon": "6.18.0",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "~0.7.0",
		"typescript": "~2.7.2"
	}
}

```
Bear in mind to delete `node_modules`, `platforms` and `hooks` folders, before rebuilding the project.
For any further questions, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests.

**Comment by phatakrajan** [comment]
thanks @tsonevn . I will keep that in mind. I already had posted the question on forums as well by the way.
