### ISSUE TITLE
Can we use css shadow property in nativescript with angular?

### ISSUE THREAD

**Issue by zeesulehria** [NativeScript/nativescript-angular#1437]

**Comment by tsonevn** [comment]
Hi @zeesulehria,
The CSS shadows are still not supported in NativeScript. This has been logged as a feature request [here](https://github.com/NativeScript/NativeScript/issues/550). Meanwhile, you can check [nativescript-ng-shadow](https://github.com/Especializa/nativescript-ng-shadow), that can help in setting up the shadow to the components.
