### ISSUE TITLE
Router Extension Navigation creates an actionbar with < Back button

### ISSUE THREAD

**Issue by SGissubel** [NativeScript/nativescript-angular#1462]
Occurring in IOS Emulator.

tns version: 4.1.2
Cross-platform modules: "version": "4.1.1"
"tns-ios": "version": "4.1.1"

I have a landing page which navigates to a login page. 
Landingpage html: ```<GridLayout rows="*, 250">
	
	<Image row="0" src="res://bg_login"  horizontalAlignment="center"></Image>

	<StackLayout width="100%"	row="1"> 
		
  	
  	<Image src="res://logo_dark"  horizontalAlignment="center"></Image>
  	
  	<Label 
  		class="landing-label" 
  		text="Connecting businesses and brands with customers & local visitors." 
  		textWrap="true"
  		horizontalAlignment="center"></Label>
  	
  	<Button text="SIGN IN" class="submit-button" [nsRouterLink]="['/login']"></Button>
  	
  	<Button class="landing-signup-button" text="Don't have an account? Sign up here!" [nsRouterLink]="['/login/signup']"></Button>
	
	</StackLayout>
	    
</GridLayout>```
This is what the landingpage looks like: 
![image](https://user-images.githubusercontent.com/21371158/43373008-d7287386-9374-11e8-981a-b643f599cada.png)

Login page:
![image](https://user-images.githubusercontent.com/21371158/43373019-eefdd6c2-9374-11e8-8eaf-b22716e92eb2.png)

 I am using the following html (the x) on the login page to go back to the landing-page: 
`<Label row="0" class="fa go-back" [text]="'fa-times-circle' | fonticon" (tap)="goBack()" orientation="horizontal" horizontalAlignment="right"></Label>`

goBack method: ```this.routerExt.navigate([''],{
        transition: {
            name: "flip",
            duration: 400,
            curve: "linear"
        }})```

When it navigates to the landing-page, I all of a sudden get a Navigationbar - which is not in my html:
![image](https://user-images.githubusercontent.com/21371158/43373058-30fdbbf0-9375-11e8-8834-78b6be8eac36.png)

I do not want that to be there.  Wondering why it creates itself - and how I can completely remove any navigationbar at all -- or simply return to that page (WITH the animation of flip) - without creating a magical new actionbar -- keeping the same display as shown above.

**Comment by tsonevn** [comment]
HI @SGissubel,
Showing the navigation back button is the default iOS behavior when you make navigation to another page. Regarding that, the described behaviour seems to be the right one. 
About the question, You can setting up clearHistory property to true, when making the navigation and the `Back` button will not be shown. You can review the documentation [here](https://docs.nativescript.org/angular/core-concepts/angular-navigation#clearing-page-navigation-history).

**Comment by SGissubel** [comment]
That was exactly what I was looking for. Thanks so much!
