### ISSUE TITLE
Is Named router outlets still not work with page-router-outlet at the root in latest version

### ISSUE THREAD

**Issue by liuwei108** [NativeScript/nativescript-angular#1464]
I followed the blog [Using Nested Router Outlets with NativeScript and Angular](https://www.nativescript.org/blog/using-nested-router-outlets-with-nativescript-and-angular) and noticed that it mentions:

> Named router outlets work only with router-outlet at the root, as page-router-outlet navigates to a whole different page each time we call navigate.

I wonder is it still the case in the latest version? is there any plan to support page-router-outlet in future version? Thanks!

**Comment by tsonevn** [comment]
Hi @liuwei108,
I tested the case described in the blog post with the named router-outlets, and this scenario seems to be still supported in NativeScript Angular.
I also tested the project provided in the article with the latest modules 4.1 and nativescript-angular 6.0 and the scenario with the named router outlets, and the root page-router-outlet also seems to be supported now. For your convenience, I am attaching the project with the needed changes.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2244093/Archive.zip)
