### ISSUE TITLE
 RadSideDrawer is not able to shown over the navigation bar if using router-outlet in root

### ISSUE THREAD

**Issue by liuwei108** [NativeScript/nativescript-angular#1465]
If I use router-outlet instead of page-router-outlet in the root, like below: 

```
<RadSideDrawer>
    <GridLayout tkDrawerContent>
        <Label text="Side Menu"></Label>
    </GridLayout>
    <StackLayout tkMainContent>
        <router-outlet></router-outlet>
    </StackLayout>
</RadSideDrawer>
```

Then the sidedrawer can not shown over the navigation bar.
Is there any way to let it shown over the navigation bar without using page-router-outlet?

Thanks!

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#761
