### ISSUE TITLE
getting error in RecyclerView class while scrolling

### ISSUE THREAD

**Issue by Sumit-ignistec** [NativeScript/nativescript-angular#1468]
getting below error while scroll  end or sometimes at scroll top, its getting after updating nativescript 4.1

System.err: java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
System.err:     at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6687)
System.err:     at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
System.err:     at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
System.err:     at android.support.v7.widget.GapWorker.prefetchInnerRecyclerViewWithDeadline(GapWorker.java:332)
System.err:     at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:348)
System.err:     at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
System.err:     at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
System.err:     at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
System.err:     at android.os.Handler.handleCallback(Handler.java:789)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6938)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
ActivityManager: START u0 {act=null typ=null flg=0x14008000 cmp=ComponentInfo{org.nativescript.drinkmates/com.tns.ErrorReportActivity}} from uid 10503

**Comment by Sumit-ignistec** [comment]
/* AUTO-GENERATED FILE. DO NOT MODIFY.
 * This class was automatically generated by the
 * static binding generator from the resources it found.
 * Please do not modify by hand.
 */
package com.tns.gen.android.support.v7.widget;

public class RecyclerView_OnScrollListener_vendor_1_2187278_n extends android.support.v7.widget.RecyclerView.OnScrollListener implements com.tns.NativeScriptHashCodeProvider {
	public RecyclerView_OnScrollListener_vendor_1_2187278_n(){
		super();
		com.tns.Runtime.initInstance(this);
	}

	public void onScrolled(android.support.v7.widget.RecyclerView param_0, int param_1, int param_2)  {
		java.lang.Object[] args = new java.lang.Object[3];
		args[0] = param_0;
		args[1] = param_1;
		args[2] = param_2;
		com.tns.Runtime.callJSMethod(this, "onScrolled", void.class, args);
	}

	public void onScrollStateChanged(android.support.v7.widget.RecyclerView param_0, int param_1)  {
		java.lang.Object[] args = new java.lang.Object[2];
		args[0] = param_0;
		args[1] = param_1;
		com.tns.Runtime.callJSMethod(this, "onScrollStateChanged", void.class, args);
	}

	public boolean equals__super(java.lang.Object other) {
		return super.equals(other);
	}

	public int hashCode__super() {
		return super.hashCode();
	}

}

Above is the autogenerated RecycleView class file in build folder

**Comment by Sumit-ignistec** [comment]
<GridLayout>
            <RadListView [items]="getPost" (loaded)="onPageLoaded()" itemInsertAnimation="fade" [itemTemplateSelector]="templateSelector"
                >
                <ng-template tkTemplateKey="checkin" let-item="item" let-i="index">
                    <CardView class="cardStyle m-l-5 m-r-5 m-t-5 m-b-5" elevation="10" radius="55">
                        <post-checkin [post]="item"></post-checkin>
                    </CardView>
                </ng-template>

                <ng-template tkTemplateKey="event" let-item="item">
                    <CardView class="cardStyle m-l-5 m-r-5 m-t-5 m-b-5" elevation="10" radius="55">
                        <event [post]="item"></event>
                    </CardView>
                </ng-template>

                <ng-template tkTemplateKey="content" let-item="item">
                    <CardView class="cardStyle m-l-5 m-r-5 m-t-5 m-b-5" elevation="10" radius="55">
                        <image-video [post]="item"></image-video>
                    </CardView>
                </ng-template>

                <ng-template tkTemplateKey="default" let-item="item">
                    <CardView class="cardStyle m-l-5 m-r-5 m-t-5 m-b-5" elevation="10" radius="55">
                        <post-view [post]="item"></post-view>
                    </CardView>
                </ng-template>
                
                
            </RadListView>
            <StackLayout horizontalAlignment="right" verticalAlignment="bottom">
                <Button text="" class="img"></Button>
            </StackLayout>
        </GridLayout>

Above is code which generate list view

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#769
