### ISSUE TITLE
Bootstrap property startPageActionBarHidden not working

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1471]
The property `startPageActionBarHidden` is not working with tns-core-modules@4.1.1 and nativescript-angular@6.0.6. The property [as described here](https://docs.nativescript.org/angular/ui/action-bar#defining-the-actionbar), use to hide the ActionBar on the landing page

Steps to reproduce:
- Create the master-details NG app
```
tns create myApp --ng
```
- **Remove** ActionBar from items.component.html and item-details.component.html
- Add the property in `main.ts`
```TS
platformNativeScriptDynamic({ startPageActionBarHidden: true }).bootstrapModule(AppModule);
```

Result: On Android, we will have Actionbar with the title the name of the application while on iOS there will be no ActionBar at all (no matter if the property is set or not).

Test application [here](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-angular/issue-353)

**_Workaround_**:
Go to the landing page and hide the action bar though the Page instance from Di
```TS
constructor(private itemService: ItemService, private _page: Page) { 
   this._page.actionBarHidden = true;
}
```

**Comment by tsonevn** [comment]
might be related to issue https://github.com/NativeScript/NativeScript/issues/6098

**Comment by NickIliev** [comment]
As of version 4.x.x of `tns-core-modules` and NativeScript the porperty `startPageActionBarHidden` is no longer needed as there is no longer a `Page` instance created on bootstrap. Instead the first page instance is created for the default route.

So to hide the action bar on Android (on iOS we simply need to remove it from the HTML) we can get a Page instance in our default route and use `actionBarHidden` property.

```TS

import { isAndroid } from "platform";
import { Page } from "ui/page";

constructor(private page: Page) {
        if (isAndroid) {
            this.page.actionBarHidden = true;
        }
}
```

The `startPageActionBarHidden` will be marked for deprcication and removed from the documentation articles examples.

**Comment by NickIliev** [comment]
Documentation updated via [https://github.com/NativeScript/docs/pulls](https://github.com/NativeScript/docs/pulls)
