### ISSUE TITLE
When we perform hotspot via Bluetooth on iOS, Connectivity type is returned as none

### ISSUE THREAD

**Issue by phatakrajan** [NativeScript/nativescript-angular#1475]
### If there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS

### Please, provide the following version numbers that your issue occurs with:

This issue occurs when we start monitoring the connectivity and connect our tablet to a hotspot created via iPhone. Here are exact steps to reproduce
1. Take tablet/phone without SIM/mobile network.
2. Take iPhone and enable hotspot. 
3. Pair iPhone with the tablet/phone on which we are testing the app.
4. Connectivity services is started. You will be able to get connection type as none even though you are able to access internet from tablet/phone

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#6158
