### ISSUE TITLE
Doing backToPreviousPage using Router Outlet inside a TabView cause an error 

### ISSUE THREAD

**Issue by 18clans** [NativeScript/nativescript-angular#1477]
### Make sure to check the existing issues in this repository 
This is similar to this issue https://github.com/NativeScript/nativescript-angular/issues/941.
iOS throws this error:  ERROR TypeError: undefined is not an object (evaluating 'states.pop')

Android throws this error: ERROR TypeError: Cannot read property 'pop' of undefined

![tab-view-router-outlet-previous-page](https://user-images.githubusercontent.com/41965764/43805078-0dda3fcc-9a64-11e8-8b58-50c5be343313.gif)

### If there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
Both Android and iOS.
iOS: 11.4
Android: 8.1.0

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
4.1.2
- Cross-platform modules: (check the 'version' attribute in the
~4.1.0
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
tns-ios: 4.1.1
tns-android: 4.1.3
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
"@angular/animations": "~6.0.0",
		"@angular/common": "~6.0.0",
		"@angular/compiler": "~6.0.0",
		"@angular/core": "~6.0.0",
		"@angular/forms": "~6.0.0",
		"@angular/http": "~6.0.0",
		"@angular/platform-browser": "~6.0.0",
		"@angular/platform-browser-dynamic": "~6.0.0",
		"@angular/router": "~6.0.0",
		"nativescript-angular": "~6.0.0",
		"nativescript-theme-core": "~1.0.4",
		"reflect-metadata": "~0.1.8",
		"rxjs": "~6.1.0",
		"tns-core-modules": "~4.1.0",
		"zone.js": "^0.8.26"

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.
1.) Go to TabView page.  
2.) On Tab 1, click on 'Go to another page'.
3.) Once you're on 'Another Page', click on 'Go Back to Tab View Child'.  
4.) You'll see an error and the navigation doesn't work anymore.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) consider using the [playground](https://play.nativescript.org) to provide an application where the problem is reproducible. If this is not possible, provide a .zip with application or refer to a repository with application where the problem is reproducible.
 
A demo project is here: https://github.com/18clans/blank_master/tree/tab-view-router-outlet

**Comment by tsonevn** [comment]
Hi @18clans,
This issue seems to be related to a missing functionality. You can follow the issue [here](https://github.com/NativeScript/nativescript-angular/issues/1351).
