### ISSUE TITLE
TabItem title not binding

### ISSUE THREAD

**Issue by Jongui** [NativeScript/nativescript-angular#1480]
### Make sure to check the existing issues in this repository 

I have found issue [845](https://github.com/NativeScript/nativescript-angular/issues/845)

### If there is no issue for your problem, tell us about it
Trying to define the TabItem title dynamically, but title is blank.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
Both

- iOS/Android versions 
iOS: 11.2
Android: 8.1.0

- emulator or device. What type of device?
Emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.2
- Cross-platform modules: 4.1.0
- Runtime(s): 
tns-android: 4.1.3
tns-ios: 4.1.1
- Plugin(s): 
"dependencies": {
    "@angular/animations": "^6.0.9",
    "@angular/cli": "^6.0.8",
    "@angular/common": "^6.0.9",
    "@angular/compiler": "^6.0.9",
    "@angular/core": "^6.0.9",
    "@angular/forms": "^6.0.9",
    "@angular/http": "^6.0.9",
    "@angular/platform-browser": "^6.0.9",
    "@angular/platform-browser-dynamic": "^6.0.9",
    "@angular/router": "^6.0.9",
    "buffer": "^5.2.0",
    "email-validator": "^2.0.4",
    "font-awesome": "^4.7.0",
    "nativescript-angular": "~6.0.6",
    "nativescript-aws-sdk": "0.0.4",
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-camera": "^4.0.2",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-fancyalert": "^1.2.0",
    "nativescript-feedback": "^1.2.0",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-gradient": "^2.0.1",
    "nativescript-imagepicker": "^6.0.2",
    "nativescript-iqkeyboardmanager": "~1.3.0",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-localize": "^3.0.4",
    "nativescript-masked-text-field": "^3.0.1",
    "nativescript-observable-subscribe": "^0.1.5",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-sidedrawer": "^1.0.6",
    "nativescript-snackbar": "^3.1.0",
    "nativescript-social-share": "~1.5.0",
    "nativescript-sqlite": "^2.2.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-unit-test-runner": "^0.3.3",
    "ng2-cookies": "^1.0.12",
    "reflect-metadata": "~0.1.10",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "tns-core-modules": "^4.1.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0-rc.0",
    "@ngtools/webpack": "~6.1.0-rc.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "~4.4.2",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "~0.7.2",
    "nativescript-dev-webpack": "^0.15.0",
    "tslint": "~5.10.0",
    "typescript": "^2.9.2"
  }

### Please, tell us how to recreate the issue in as much detail as possible. 
Create a TabView and place inside it RadListViews. In these, define *tabItem and bind it to a variable from the Componente class. It will show blank.

### Is there any code involved? 

 - Playground example: [TabItemTitle](https://play.nativescript.org/?template=play-ng&id=1L2Dqc)

**Comment by tsonevn** [comment]
Hi @Jongui,
We tested the `tabItem ` binding, and it seems to work as expected. Keep in mind that when you are binding the `tabItem `, you should provide the content for property in JSON format with the need key and value. For example:
HTML
```
<ActionBar title="My App" class="action-bar">
</ActionBar>

<GridLayout rows="" columns="">
    <TabView #tv iosIconRenderingMode="alwaysTemplate"  selectedTabTextColor="green">
        <StackLayout *tabItem="myFirstItem">
            <Label text="First tap" textWrap="true"></Label>
        </StackLayout>
        <StackLayout *tabItem="mySecondItem">
            <Label text="Second tab item"></Label>
        </StackLayout>
        <StackLayout *tabItem="myThirdItem">
            <Label text="Third tab item"></Label>
        </StackLayout>
    </TabView>
</GridLayout>
```
TypeScript
```
import { Component, OnInit } from "@angular/core";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    myFirstItem = { title: "Tab1", iconSource: "" };
    mySecondItem = { title: "Tab2", iconSource: "" };
    myThirdItem = { title: "Tab3", iconSource: "" };
    
    constructor() { }

    ngOnInit(): void {
       
    }
}
```
You can also review our [documentation](https://docs.nativescript.org/angular/ui/ng-ui-widgets/tab-view), where it is described, what is needed to define a TabView in NativeScript Angular.
