### ISSUE TITLE
ngClass is not working

### ISSUE THREAD

**Issue by cerealexx** [NativeScript/nativescript-angular#1481]
Hi, I'm trying to add an active class to my custom tab component on path change but for some reason, the class is never applied.

This is the view:
```
<FlexboxLayout>
  <Button [nsRouterLink]="['products']" [ngClass]="{'active': activeTab === 0}">
    <Span text="&#xf291;                " class="i no-bg"></Span>
    <Span text="Productos" class="text no-bg"></Span>
  </Button>
  <Button [nsRouterLink]="['user']" [ngClass]="{'active': activeTab === 1}">
    <Span text="&#xf007;                " class="i no-bg"></Span>
    <Span text="Tu perfil" stretch class="text no-bg"></Span>
  </Button>
  <Button [nsRouterLink]="['diets']" [ngClass]="{'active': activeTab === 2}">
    <Span text="&#xf2e6;                " class="i no-bg"></Span>
    <Span text="Dietas" class="text no-bg"></Span>
  </Button>
</FlexboxLayout>
```

This is the class:
```
import { OnInit, OnChanges, Input } from '@angular/core';
import { Component } from "@angular/core";

@Component({
    selector: 'ns-main-tabs',
    templateUrl: 'shared/main-tabs/main-tabs.component.html',
    styleUrls: ['shared/main-tabs/main-tabs.component.css']
})

export class MainTabsComponent implements OnInit, OnChanges { 

    @Input() path: string;
    public activeTab = 1;

    constructor() {}

    ngOnInit() {}
    
    ngOnChanges() {
        if (this.path === '/products') {
            this.activeTab = 0;
        } else if (this.path === '/user') {
            this.activeTab = 1;
        } else if (this.path === '/diets') {
            this.activeTab = 2;
        }
    }
}
```
I've tried to apply the class directly and it works, so it isn't a css problem.
Also I've hardcoded the interpolated activeTab value to the view and it is correctly displayed on change. So no idea what the problem could be...

Thanks!

**Comment by tsonevn** [comment]
Hi @cerealexx,
I have created a sample project while reusing some part of your code. However, I was unable to recreate the issue with `ngClass`. For your convenience, I am attaching the project, which I used for testing. Please review it and make the needed changes, which will allow us to reproduce the issue.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2276740/Archive.zip)

**Comment by tsonevn** [comment]
Hi @cerealexx,
Can you make the needed changes in the sample project, provided in my previous comment? It will help in investigating the problem, which you are facing.

**Comment by cerealexx** [comment]
Hi @tsonevn,
Here is my stripped down not working version with path evaluation. As you will see, the logs are correctly shown as in your example but still ngClass doesn't work.
Thanks!
[ngClassBug.zip](https://github.com/NativeScript/nativescript-angular/files/2278551/ngClassBug.zip)

**Comment by vakrilov** [comment]
Hey @cerealexx 
You will have to import the `NativeScriptCommonModule` in your shared module - it exports the `CommonModule` from `@angular/common` that defines the `ngClass` directive. The reason it works in your main module is that it imports `NativeScriptModule` which does the same: 

```
import { NativeScriptCommonModule } from "nativescript-angular/common";

@NgModule({
  imports: [
    NativeScriptCommonModule,
    ...
  ],
 ...
})

export class SharedModule { }
```
You can also check out [this blog](https://www.nativescript.org/blog/working-with-angular-modules-in-nativescript-apps) for other useful info on modules.

**Comment by cerealexx** [comment]
Great! Thanks @vakrilov
