### ISSUE TITLE
FormattedString's Spans cannot be styled using margin, padding, and alignment 

### ISSUE THREAD

**Issue by kamok** [NativeScript/nativescript-angular#1482]
### Which platform(s) does your issue occur on?
- iOS 4.1.1
- iOS/Android versions 
- emulator, iPhone 6

-Playground used Android real device

### Please, provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) `4.1.0`
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
```
    "tns-android": {
      "version": "4.1.3"
    },
    "tns-ios": {
      "version": "4.1.1"
    }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Put 2 `Spans` inside a `FormattedString`, and try to style it with things besides color.

### Is there any code involved? 
https://play.nativescript.org/?template=play-ng&id=HTQkgE

**Comment by tsonevn** [comment]
Hi @kamok,
Thank you for the sample project.
The margin seems not to be supported by the Spans. You can check all available properties for this component [here](https://docs.nativescript.org/api-reference/classes/_text_span_.span). Regarding that, you can set up the `fontFamily`, `fontSize`, `color` and `backgroundColor`.

**Comment by kamok** [comment]
This is pretty limiting. There's no way for me to make sure the icon text + text on my Button or Label to be aligned vertically. Right now it looks very strange, even if the font size is set to exactly the same, there is still a minor difference between the two font sets.

**Comment by Sunhat** [comment]
@tsonevn Have you got an alternative solution for this? You provided an blunt, rude and unhelpful answer to @kamok

**Comment by Sunhat** [comment]
Use 3 spans, one the middle with a " \n" and small fontsize

**Comment by 0x80085** [comment]
@tsonevn That answer is not helpful, why was this issue closed?

It's still an issue up until this day. There's some serious styling limitations for simple things in nativescript. I've been researching this framework for some time and already found many styling limitations for things which are trivial even in Android Kotlin or even CSS/HTML.
For example putting an icon and text next to eachother but centered vertically in a Button is literally impossible. StackLayout doesn't work, FormattedString doesn't work. No decent production-ready examples are provided, only very simple UI compositions.
After this hell, I'm gonna check out ReactNative next in hopes it's better maintained and documented than this project.
