### ISSUE TITLE
FontIcon not working in ActionItem

### ISSUE THREAD

**Issue by SGissubel** [NativeScript/nativescript-angular#1483]
### Which platform(s) does your issue occur on?
- iOS emulator

tns version: 4.1.2
Cross-platform modules: "version": "4.1.1"
"tns-ios": "version": "4.1.1"

### Please, tell us how to recreate the issue in as much detail as possible. 
Using fonticon with my Nativescript-angular app.  I have followed all of the instructions and have even debugged several items.

It displays the icon in `Label` BUT the layout gets completely messed up:
```
<ActionBar [title]="user.userName">
...
  <Label
    class="fa"
    [text]="'fa-cog' | fonticon"
    ios.position="right"
    android.position="right"></Label>
</ActionBar>
```
Results in:
![image](https://user-images.githubusercontent.com/21371158/43995867-361cdd36-9d85-11e8-9a14-99cab98db61d.png)

What I need is to use `ActionItem`:
```
<ActionBar [title]="user.userName">
  <ActionItem
    class="fa"
    [text]="'fa-user-plus' | fonticon"
    ios.position="left"
    android.position="left"></ActionItem>
  <ActionItem
    class="fa"
    [text]="'fa-cog' | fonticon"
    ios.position="right"
    android.position="right"></ActionItem>
</ActionBar>
```
But results in:
![image](https://user-images.githubusercontent.com/21371158/43995884-9cda736c-9d85-11e8-8fb5-246b0cd92eb7.png)

In my app.scss:
```
.fa {
  font-family: FontAwesome, fontawesome-webfont;
}
```
(I tried using a capital F in Font-family - no change.)

My app module:
```
import { NgModule } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NativeScriptFormsModule } from 'nativescript-angular/forms';
import { NativeScriptHttpModule } from 'nativescript-angular/http';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { ReactiveFormsModule } from '@angular/forms';

import { TNSFontIconModule, TNSFontIconService } from 'nativescript-ngx-fonticon';

import { MinLengthDirective, IsEmailDirective } from "./directives/input.directive";
import { AppComponent } from "./app.component";
import { routes, navigatableComponents } from './app.routing'
// TNSFontIconService.debug = true;
@NgModule({
  imports: [
  	NativeScriptModule,
  	NativeScriptFormsModule,
  	NativeScriptHttpModule,
  	NativeScriptRouterModule,
  	NativeScriptRouterModule.forRoot(routes),
  	TNSFontIconModule,
  	ReactiveFormsModule,
  	TNSFontIconModule.forRoot({
			'fa': './assets/fontawesome.scss',
		})
  ],
  declarations: [
  	MinLengthDirective,
  	IsEmailDirective,
  	AppComponent,
  	...navigatableComponents
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

In my `fonts` folder I have:
`fontawesome-webfont.ttf` & `FontAwesome.ttf`

In my `assets` folder I have:
`fontawesome.css`(the compiled form of -->)  `fontawesome.scss`

Desired output:

![image](https://user-images.githubusercontent.com/21371158/43995920-423cae60-9d86-11e8-8a1a-e04ea9643dba.png)

**Comment by tsonevn** [comment]
Hi @SGissubel,
Thank you for the provided code samples.
Currently, while using IconFonts inside the ActionBar, you should use Label. For example:
```
<ActionBar title="Title"  class="action-bar">
  <ActionItem >
      <Label text="&#xf359;" class="icon" ></Label>
  </ActionItem>
  <ActionItem ios.position="right">
        <Label text="&#xf2bb;" class="icon" ></Label>
  </ActionItem>
</ActionBar>
```
I tested this case with the free version of  Font Awesome. Bear in mind that for properly setting up the position of the Labels, you should set them inside the ActionItems. For your convenience, I am attaching sample project, which can be used for debugging.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2282247/Archive.zip)

**Comment by NathanWalker** [comment]
@SGissubel you can also use `fonticon` pipe on those `Label`'s just as well there too.

**Comment by SGissubel** [comment]
Thanks folks! I used both solutions and worked like a CHARM!

**Comment by SGissubel** [comment]
But while I am here... 

Any idea why the following wouldn't work? 

`<Button class="fa" width="20%" [text]="'fa-map-marked-alt' | fonticon"></Button>`

It is apparently JUST that particular font icon.  Most other things I try work: 

![image](https://user-images.githubusercontent.com/21371158/44129035-46afb0ec-a014-11e8-8d9c-0f4ddac4c513.png)

But if I put in another icon... 
`<Button class="fa" width="20%" [text]="'fa-map-pin' | fonticon"></Button>`

![image](https://user-images.githubusercontent.com/21371158/44129088-98facfbc-a014-11e8-9645-901ccc165424.png)


I also tried:

`fa-map-marker-alt`

But I get the same question-mark box.

**Comment by NathanWalker** [comment]
Check the CSS and make sure that icon class is actually in the styles. Sometimes depending on version the docs may reference an icon which may have not been in the version of css at the time you downloaded. Just search the .css for that classname.

**Comment by SGissubel** [comment]
![image](https://user-images.githubusercontent.com/21371158/44133386-9032baf2-a02d-11e8-80b1-26bf2a12037a.png)

**Comment by SGissubel** [comment]
I have had A few weird similar issue like the previous. 

For example - I also just get nothing at all for this: 

`<Label flexGrow="1" class="fa icon-utensil" [text]="'fa-utensils' | fonticon"></Label>`

Which doesn't show up at all... 
![image](https://user-images.githubusercontent.com/21371158/44133532-3ca9d086-a02e-11e8-95d2-d51d6f769060.png)

But I also checked the css for `fa-utensils` and it also does exist.

**Comment by NathanWalker** [comment]
What’s in your icon-utensil class there?

**Comment by SGissubel** [comment]
Currently nothing. I attempted to set `color: black;`  but it did nothing.

**Comment by NathanWalker** [comment]
You might post whole template or at least the bottom tabbar setup. Sometimes things like that could be the position is not where you might expect especially when using flex layout rules.

**Comment by SGissubel** [comment]
Flex was one of many I tried. haha.  

This is actually a child component.


**Parent:**
```
<GridLayout rows="150, 200, *">
	<StackLayout row="0">
		<profile-head
			[profileUser]="user">
				
		</profile-head>
	</StackLayout>
	
	<StackLayout row="1">
		<profile-nav row="1">
		</profile-nav>
	</StackLayout>
	<!-- <Label row="1"></Label> -->
	<Label row="2"></Label>
</GridLayout>
```

**Child:** _including some of the different attempts commented out_
```
<!-- <GridLayout columns="*, *, *, *" class="profile-head" > -->
		<GridLayout col="0" orientation="horizontal" horizontalAlignment="center">
			<Label class="fa" [text]="'fa-list-ul' | fonticon"></Label> -->
		<!-- 	<Label row="0" class="fa go-back" [text]="'fa-times-circle' | fonticon" (tap)="goBack()" orientation="horizontal"></Label>\ --><!-- 
	  </GridLayout>

		<GridLayout col="1" orientation="horizontal" horizontalAlignment="center">
	  	<Label class="fa" [text]="'fa-utensils' | fonticon"></Label>
	  </GridLayout>

		<GridLayout col="2" orientation="horizontal" horizontalAlignment="center">
	  	<Label class="fa" [text]="'fa-calendar' | fonticon"></Label>
	  </GridLayout>

		<GridLayout col="3" orientation="horizontal" horizontalAlignment="center">
	  	<Label class="fa" [text]="'fa-bookmark' | fonticon"></Label>
	  </GridLayout>
	    
<!-- </GridLayout> -->


<FlexboxLayout flexDirection="row">
    <!-- Use even flexGrow to achieve uniform grid -->
    <Label flexGrow="1" class="p-15 text-center font-weight-bold fa" [text]="'fa-list' | fonticon"></Label>
    <Label flexGrow="1" class="p-15 text-center font-weight-bold fa icon-utensil" [text]="'fa-utensils' | fonticon"></Label>
    <Label flexGrow="1" class="p-15 text-center font-weight-bold fa" [text]="'fa-calendar' | fonticon"></Label>
    <Label flexGrow="1" class="p-15 text-center font-weight-bold fa" [text]="'fa-bookmark' | fonticon"></Label>
    
</FlexboxLayout>
```

**Comment by NickIliev** [comment]
@SGissubelI've stumbled upon similar issue - some specific icons from FontAwesome5 are not shown while most are working as expected. In my case, it appeared that some icons are shown only when using a specific font variant. 

For example, for the icon [fa-marked-map-alt](https://fontawesome.com/icons/map-marked-alt?style=regular)  only the solid font is working 
```HTML
<!-- Works as expectedv with fas map-marked-alt -->
<Label class="fas" text="&#xf041;">
</Label>

<!-- WON'T WORK far map-marked-alt -->
<Label class="far" text="&#xf041;">
</Label>

<!-- WON'T WORK with fab map-marked-alt -->
<Label class="fab" text="&#xf041;">
</Label>
```

where the **fas**, **far** and **fab** are the following fonts in my CSS
```CSS
.far {
    font-family: Font Awesome 5 Free, fa-regular-400;
    font-weight: 400; 
}

.fab {
    font-family: Font Awesome 5 Brands, fa-brands-400;
    font-weight: 400; 
}

.fas {
    font-family: Font Awesome 5 Free, fa-solid-900;
    font-weight: 900; 
}
```
