### ISSUE TITLE
[Android] Buttons in GridLayout appear over other gridLayout items 

### ISSUE THREAD

**Issue by breningham** [NativeScript/nativescript-angular#1486]
So, i have a 'home' component which acts a base for navigating to other pages, and is basically the master template for the other pages, in which we only switch out part of the page instead of the full page (we use the angular router for this.)

in the html we have the following: 

```(html)
<GridLayout class="background" rows="auto, auto, *" columns="*, *, *">
    
    <Button class="home-booking-switcher-btn" id="button" horizontalAlignment="right" [text]="isHome ? '&#xe808;' : '&#xe807;' " row="0" col="2" (tap)="toggleNavigation()" marginRight="10" marginTop="10"></Button>
    <Image src="res://msplogo" stretch="aspectFit" class="logo" row="0" col="0" colSpan="3"></Image>
    
    <StackLayout row="2" col="0" colSpan="3">
        <router-outlet></router-outlet> 
    </StackLayout>
    
    <smartparking-loader rowSpan="3" colSpan="3" [show]="comms.isLoading$ | async"></smartparking-loader>
</GridLayout>
```
in that code i have the custom component 'smartparking-loader', which is pretty simple, just a GridLayout, with a NSCard in the Middle creating a traditional loading screen. 

looks like the following: 

```(html)
<GridLayout width="100%" height="100%" style="background-color: rgba(0,0,0,0.3);" [rowSpan]="rowSpan" [colSpan]="colSpan" [row]="row" [col]="col" [visibility]="visibility">
    <ns-card radius="10" elevation="11" class="loader" #loaderCard shadowOffsetHeight="0" shadowOffsetWidth="0" shadowRadius="5" verticalAlignment="center">
        <GridLayout rows="60, 60" columns="*" class="inner-container">
            <ActivityIndicator [busy]="show" row="0" horizontalAlign="center" class="loader-indicator"></ActivityIndicator>
            <Label text="loading..." row="1" horizontalAlign="center" class="loader-text" ></Label>
        </GridLayout>
    </ns-card>
</GridLayout>
```

Problem is, the Button on the 'home' component appears to always be above the gridlayout in the loader component.  as you can see here: 
![screenshot_20180814-112529](https://user-images.githubusercontent.com/23170786/44086569-ecfa5386-9fb4-11e8-89fe-e3534640969c.jpg)

**Comment by tsonevn** [comment]
Hi @breningham,
I reviewed the reported case, and it seems that there is a problem with the Button and how it is rendered in the GridLayout. The problem is also reproducible in a non-Angular project.  I will mark this as a bug. The workaround at this time is to use the `visibility` property and with its help to control when the element should be visible. For example:
```
<GridLayout class="background" rows="auto, auto, *" columns="*, *, *">
    
    <Button [visibility]="isItemVisible ? 'visible' : 'collapsed'" class="home-booking-switcher-btn" id="button" horizontalAlignment="right" style="z-index:10;" [text]="'Home'" (tap)="onTap($event)" row="0" col="2"  marginRight="10" marginTop="10"></Button>
    <Image src="res://logo" stretch="aspectFit" width="50" height="50" class="logo" row="0" col="0" colSpan="3"></Image>
    
    <StackLayout row="2" col="0" colSpan="3">
        <!-- <router-outlet></router-outlet>  -->
    </StackLayout>
    
    <ns-details rowSpan="3" colSpan="3" row="0" col="0" style="z-index:100;" [show]="true" [isItemVisible]="test"></ns-details>
</GridLayout>

```

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2289560/Archive.zip)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#6184
