### ISSUE TITLE
Using Parse as backend

### ISSUE THREAD

**Issue by Jai-Krish** [NativeScript/nativescript-angular#1494]
Getting the following error while using the ParseJs SDK
`ERROR Error: Uncaught (in promise): ParseError: 100 XMLHttpRequest failed: {"originalStack":"Error: Cannot make a request: No definition of XMLHttpRequest was found.\n    at new ZoneAwareError...`

[NSParse.zip](https://github.com/NativeScript/nativescript-angular/files/2311217/NSParse.zip)

CLI: 4.2.2

**Comment by tsonevn** [comment]
Hi @Jai-Krish,
I reviewed the [plugin](https://github.com/parse-community/Parse-SDK-JS#parse-sdk-for-javascript). However, it seems that the `parse` plugin is not supported in NativeScript Angular. 
You can check [nativescript-parse](https://github.com/triniwiz/nativescript-parse) plugin, which seems to provide support for Parse SDK  in NativeScript.

Also, you can check out the [nativescript-nodeify](https://github.com/EddyVerbruggen/nativescript-nodeify) plugin, which makes most npm packages compatible with NativeScript.

**Comment by Jai-Krish** [comment]
@tsonevn thank you for pointing me towards the [nativescript-nodeify](https://github.com/EddyVerbruggen/nativescript-nodeify) but the error still exists even while using `parse/node`. Also this [SDK](https://github.com/parse-community/Parse-SDK-JS#parse-sdk-for-javascript) works out of the box with [nativescript-vue](https://nativescript-vue.org/blog/using-parse-in-nativescript-vue/).
