### ISSUE TITLE
App on Android is really slow...

### ISSUE THREAD

**Issue by relez** [NativeScript/nativescript-angular#1495]
Hi there I am about to release our apps for Android/iOS but I just found out that the app is running slow in Android devices (simulators too), I have been researching on some tricks and I already tried uglify/webpack, etc and it does not make it faster. 

I have prepared a project I can share with you to review this issue. Please, if you are willing to review it, let me know a private way to send it to you (for security reasons).

Thanks!

**Comment by NathanWalker** [comment]
Hi @relez many factors can influence speed and perception of performance especially with different code setups and view construction. You can email a link to a zip of your project to team@nstudio.io and we’ll give you a couple insights where possible in next couple days.

**Comment by NickIliev** [comment]
@relez you can share the project with @NathanWalker  or with me (search for user **niliev** in [the community slack](https://nativescriptcommunity.slack.com/messages/general)). 

Closing the issue as the information is too abstract to investigate a concrete problem.

**Comment by jannomeister** [comment]
@NickIliev I'm also experiencing this issue running on android. Is it okay to send you a sample project in private on slack?
