### ISSUE TITLE
No possibility to override provider in unit tests

### ISSUE THREAD

**Issue by slaven3kopic** [NativeScript/nativescript-angular#1496]
Platform: Android
Using the emulator.

- CLI: 4.1.1
- Cross-platform modules: 4.2.0
- Runtime(s): 4.1.3

  "dependencies": {
    "@angular/animations": "~6.0.0",
    "@angular/common": "~6.0.0",
    "@angular/compiler": "~6.0.0",
    "@angular/core": "~6.0.0",
    "@angular/forms": "~6.0.0",
    "@angular/http": "~6.0.0",
    "@angular/platform-browser": "~6.0.0",
    "@angular/platform-browser-dynamic": "~6.0.0",
    "@angular/router": "~6.0.0",
    "moment": "^2.22.2",
    "nativescript-angular": "~6.0.0",
    "nativescript-cardview": "^3.1.0",
    "nativescript-feedback": "^1.2.0",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-phone": "^1.3.1",
    "nativescript-pulltorefresh": "^2.1.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~4.1.1",
    "nativescript-unit-test-runner": "^0.3.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.1.0",
    "tns-core-modules": "^4.2.0",
    "yargs": "^11.0.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/core": "~0.6.3",
    "@angular/compiler-cli": "~6.0.0",
    "@ngtools/webpack": "^6.0.8",
    "@types/chai": "^4.0.2",
    "@types/chai-spies": "^1.0.0",
    "@types/mocha": "^2.2.41",
    "@types/node": "^7.0.5",
    "archiver": "^2.1.1",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "^6.18.0",
    "body-parser": "^1.18.3",
    "browser-sync": "^2.23.7",
    "chai": "^4.1.2",
    "chai-spies": "^1.0.0",
    "clean-webpack-plugin": "^0.1.19",
    "codelyzer": "^4.4.2",
    "copy-webpack-plugin": "^4.5.1",
    "cors": "^2.8.4",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-plugin-import": "^2.10.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-standard": "^3.0.1",
    "express": "^4.16.3",
    "extract-text-webpack-plugin": "^3.0.2",
    "html-pdf": "^2.2.0",
    "karma": "^3.0.0",
    "karma-chai": "^0.1.0",
    "karma-chai-spies": "^0.1.4",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "marked": "^0.3.19",
    "nativescript-dev-appium": "^3.3.0",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.12.0",
    "nativescript-worker-loader": "^0.9.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "^2.3.0",
    "sass-loader": "^7.0.3",
    "shelljs": "^0.8.1",
    "tslint": "^5.10.0",
    "tslint-angular": "^1.1.2",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "watch": "^1.0.2",
    "webpack": "^4.16.5",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.8",
    "webpack-sources": "^1.1.0"
  }

Example:

    class MockSomeService {
        date: 'dummy'
    };

    describe('Test something.component.ts:', () => {

        beforeEach(nsTestBedBeforeEach([
           SomethingComponent
        ], [{ provide: SomeService, useClass: MockSomeService }]));
       afterEach(nsTestBedAfterEach(false));

       it('test', (done) => {
           nsTestBedRender(SomethingComponent)
           .then((fixture: ComponentFixture<SomethingComponent>) => {
               const component = fixture.componentRef.instance;
               console.log(component.someService.date) 
               /* Getting actual SomeService not the mock one */
               done();
           });
      });

      });

Need something like TestBed.overrideComponent from Angular.

**Comment by sebastiandenis** [comment]
Instead of useClass use useValue like this:
`[{ provide: SomeService, useValue: new MockSomeService() }]`

**Comment by slaven3kopic** [comment]
@sebastiandenis Works. Thanks

**Comment by mahmoudajawad** [comment]
Is this applicable to all services? I'm unable to mock `HttpClient` in the following:

```typescript
@Component({
    template: ``
})
export class TestComponent {
    constructor(public api: ApiService) {}
}

export class NSHttpClientMock {
  get(...params: Array<any>): Observable<any> {
    let observable = new Observable(
		(observer) => {
			observer.next({}); // Attempting to mock invalid response
			observer.complete();
			observer.unsubscribe();
		}
	);
	return observable;
  }
}

describe('ApiService', () => {
	beforeEach(
		nsTestBedBeforeEach(
			[
				TestComponent
			],
			[
				{
					provide: HttpClient,
					useValue: new NSHttpClientMock()
				},
				HttpService, // This service injects HttpClient
				ApiService,
			]
		)
	);
    afterEach(nsTestBedAfterEach(false));
    afterAll(() => {});

   //...
});
```

The results from the tests are positive outcome as `HttpService` is overriding mocked class and is using Angular `HttpClient` to make the call and return the expected response.
