### ISSUE TITLE
When set "flat" property of ActionBar to 'true' with css TabView after navigate not display and How to solve it ?

### ISSUE THREAD

**Issue by LeCaoPhuc** [NativeScript/nativescript-angular#1497]
### Make sure to check the existing issues in this repository 
Yes
### If there is no issue for your problem, tell us about it
I see a issues [https://github.com/NativeScript/NativeScript/issues/5901]() but it is of naivescript core.
 I want know a way to solve it but I can use flat property.

### Which platform(s) does your issue occur on?
- iOS
- emulator or device. What type of device?
-device :  Iphone 6 plus  . 
- OS version : 11.2.6
### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.1.2
- Cross-platform modules: 4.1.0
- Runtime(s): 
 `"tns-ios": {
            "version": "4.1.1"
        },
        "tns-android": {
            "version": "4.1.3"
        }`
- Plugin(s): I create a nativescript playground i can't find a full package.json.

### Please, tell us how to recreate the issue in as much detail as possible. 
- when navigate from a normal page to a page that have TabView , if you uncomment line css 
`flat: true;` of class ActionBar in file app.css, a TabView will be not display.

### Is there any code involved? 
 - I have create a sample projefct playground [`source`](https://play.nativescript.org/?template=play-ng&id=dEkWQN&v=7)

**Comment by tsonevn** [comment]
Hi @LeCaoPhuc,
Try to set up the TabView inside a GridLayout. For example:
```
<ActionBar title="Home" class="action-bar">
</ActionBar>
<GridLayout>
	<TabView >
		<StackLayout *tabItem="{title: 'Tab 1'}">
				<Label text="When you comment line 'flat: true;' of class ActionBar in app.css file, TabView will display " textWrap="true"  color="blue"></Label>t>
		</StackLayout>
		<StackLayout *tabItem="{title: 'Tab 2'}">
			<Label text="Label in Tab 2"></Label>
		</StackLayout>
	</TabView>
</GridLayout>
```

**Comment by rickybrown** [comment]
is there any similar implementation for the TavView? my tab background color appears to have the translucent overlay as well, thus not matching the background color of my page content
