### ISSUE TITLE
RouterExtension's back() method not honouring NavigationCancel event

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/nativescript-angular#1506]
I ran into something which seems to be an issue with the `RouterExtensions.back()` method from nativescript-angular.  

Consider [this playground project](https://play.nativescript.org/?template=play-ng&id=BiuzGg&v=7), where the `CanDeactivate` guard works fine, but in which the `RouterExtensions.back()` will not honour the `NavigationCancel` event (which results in the `canGoBack()` method not working properly):

1. Start project (note the `cannot go back` label on top from header component)
2. Tap op `Guarded Route` button
3. Tap on the `Go Back` button from header component
4. You will see underneath the confirm that the "Go Back" button has already been replaced by the  `cannot go back` label even before you confirm.
5. Tap on NO in the confirm dialog --> this cancels the navigation but the `RouterExtensions.canGoBack()` was already updated and now not in sync with Angular.

### Which platform(s) does your issue occur on?
- Both iOS & Android
- Android 8 real device, iOS simulator latest

### Please, provide the following version numbers that your issue occurs with:
```
$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.2.3 version and is up to date.
✔ Component tns-core-modules has 4.3.0-2018-08-28-01 version and is up to date.
✔ Component tns-android has 4.2.0 version and is up to date.
✔ Component tns-ios has 4.3.0-2018-08-17-02 version and is up to date.
```

```
"dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "~6.1.0",
```

**Comment by tsonevn** [comment]
Hi @abhayastudios,
Thank you for the provided sample project. 
I will mark this issue as a bug, and we will investigate the problem further. I will suggest keeping track of the issue, and we will provide more info about the case.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2352618/Archive.zip)

**Comment by abhayastudios** [comment]
@tsonevn thanks!

I tried to dive a little into the code and from what I can understand [these lines](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/ns-location-strategy.ts#L162-L225) are executed regardless (or before) the `NavigationCancel` event. I tried to look how the vanilla Angular LocationStrategy handles it but to be honest it is a little over my head.

When I enable router tracing as below, I do see the `NavigationCancel` event in the console, but I would also expect the [RouterExtensions tracing](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/ns-location-strategy.ts#L189) to show up but it didn't. Any idea how to enable those as well for additional debugging?

```
imports: [
    RouterModule.forRoot(routes, { enableTracing: true })
]
```

In any case, if you can think of a workaround until this is fixed that would be awesome.

Thanks!

**Comment by abhayastudios** [comment]
Actually in my case I can just use the Angular's Location back()

**Comment by tsonevn** [comment]
Hi @abhayastudios,
We have discussed further the case with the dev team, and it seems that using the guards in the back navigation cannot be supported in NativeScript Angular.  This is caused, because the back navigation, triggered by`goBack` method or via hardware back button(for Android), will trigger the native functionality for the native back and then will notify the Angular about it. We will describe this specific in the docs and will provide more info, why the guards can not be used in NativeScript Angular.

**Comment by kamilchlebek** [comment]
@tsonevn With today NS - is there any workaround to prevent navigation to happen on "back button" ? We have few forms in the app, user may accidentally lost all filled data :(

**Comment by NickIliev** [comment]
@kamilchlebek [see this blog post ](https://www.thepolyglotdeveloper.com/2018/05/override-android-back-button-nativescript-angular-application/)for details on how to overwrite the default action for the hardware back button on Android.

Basically, you need something like
```JavaScript
application.android.on(application.AndroidApplication.activityBackPressedEvent, (args: any) => {
    args.cancel = true;
    // the custom logic follows here
});
```

**Comment by kamilchlebek** [comment]
Thanks I'll try that. It's a pity there's no built in solution for that

**Comment by Clonk-HTML5** [comment]
Is there any Solution to prevent navigation on IOS ? Android seems to be working
