### ISSUE TITLE
Fullscreen ModalService rendering issue on iOS

### ISSUE THREAD

**Issue by dcarrot2** [NativeScript/nativescript-angular#1508]
### Which platform(s) does your issue occur on?
- iOS only (Android seems fine)
- Versions
- Physical iPhone 8 11.4.1
- Emulator iPhone 6 11.4

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it) 4.2.2
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) 4.2.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project) Both are 4.2.0
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
```
"dependencies": {
        "@angular/animations": "~6.1.0",
        "@angular/common": "~6.1.0",
        "@angular/compiler": "~6.1.0",
        "@angular/core": "~6.1.0",
        "@angular/forms": "~6.1.0",
        "@angular/http": "~6.1.0",
        "@angular/platform-browser": "~6.1.0",
        "@angular/platform-browser-dynamic": "~6.1.0",
        "@angular/router": "~6.1.0",
        "nativescript-angular": "~6.1.0",
        "nativescript-theme-core": "~1.0.4",
        "reflect-metadata": "~0.1.8",
        "rxjs": "^6.0.0",
        "tns-core-modules": "~4.2.0",
        "zone.js": "^0.8.26"
    },
    "devDependencies": {
        "typescript": "~2.7.2",
        "nativescript-dev-typescript": "~0.7.0"
    }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
When using `this.modalService.showModal` from  `ModalDialogService` to render a full screen modal in iOS, the background of the modal doesn't render until the animation completes. The elements of the modal do render immediately which causes them to overlap with the elements of the component calling the `ModalDialogService`.

### Is there any code involved? 
 - Can be found at (https://play.nativescript.org/?template=play-ng&id=jaHCgx) as well as another example using the template tns-cli creates (https://bitbucket.org/ddosgov/nsngmodaliosexample/src/master/). Video recording capturing issue (https://streamable.com/jcw53)

**Comment by tsonevn** [comment]
Hi @dcarrot2,
I tested the attached Playground project and found that to solve the issue, you need just to set up `backgroundColor` to the main container in the modal page. For example:
```
<GridLayout backgroundColor="green">
........
</GridLayout>
```
You can also check the sample [here](https://play.nativescript.org/?template=play-ng&id=jaHCgx&v=2).

**Comment by dcarrot2** [comment]
Great, this fixed our issue--thanks!
