### ISSUE TITLE
angular beta.13, rxjs beta.4, zone.js 0.6.6

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#151]
Curious if any known issues exist to updating `nativescript-angular` and the `ng-sample` app to depend on those latest versions?

Even though beta.13 still has a peer dep of rxjs beta.2, it's only a warning and works fine with beta.4

I may attempt a PR here, but not sure of some specific internals affected.

**Comment by hdeshev** [comment]
I haven't tried it yet, but I anticipate the new zone.js release may cause some trouble (it usually does, :frowning:)

We had issues with it before, as it was monkeypatching stuff too agressively, and crashed when not being run outside the browser. It also patched the XHR API in a way that broke the {N} karma test runner.

Here's my original issue:
https://github.com/angular/zone.js/issues/263

...and the hacks I had to do to work around it:
https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/application.ts#L4-L12

**Comment by vakrilov** [comment]
Resolved in #162
