### ISSUE TITLE
RadList Nativescript (undefined is not an object)

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1515]
hey I am using Nativescript Listview and these error are coming from listview 
`CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating '_v.context.item.range')
CONSOLE ERROR [native code]: ERROR CONTEXT {
"view": {
"def": {
"nodeFlags": 1,
"rootNodeFlags": 1,
"nodeMatchedQueries": 0,
"flags": 0,
"nodes": [
{
"nodeIndex": 0,
"parent": null,
"renderParent": null,
"bindingIndex": 0,
"outputIndex": 0,
"checkIndex": 0,
"flags": 1,
"childFlags": 1,
"directChildFlags": 1,
"childMatchedQueries": 0,
"matchedQueries": {},
"matchedQueryIds": 0,
"references": {},
"ngContentIndex": null,
"childCount": 1,
"bindings": [],
"bindingFlags": 0,
"outputs": [
{
"type": 0,
"target": null,
"eventName": "tap",
"propName": null
}
],
"element": {
"ns": "",
"name": "GridLayout",
"attrs": [
[
"",

`

**Html**
`	<GridLayout verticalAlignment="middle" tkExampleTitle tkToggleNavButton>
			<RadListView [items]="statisitcs" >
				<ng-template tkListItemTemplate let-item="item">
					<GridLayout class="margin-horizontal-list" col="1" (tap)="onfilterSelect(item.range)">
						<Label class="h3 label-hor-list" horizontalAlignment="center" verticalAlignment="middle" col="0" [text]="item.range"></Label>
					</GridLayout>
				</ng-template>
				<ListViewLinearLayout tkListViewLayout scrollDirection="Horizontal"></ListViewLinearLayout>
			</RadListView>
		</GridLayout>`

hear i am defining Data

`

  statisticsData = [
    { dataList: "sdf" },
    { dataList: "sdfsdasd" },
    { dataList: "sdf" },
    { dataList: "sddsfdsff" },
  ];
`
NativeScriptUIListViewModule is also added
import { NativeScriptUIListViewModule  } from "nativescript-ui-listview/angular/listview-directives";

any thing i am missing?

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#840
