### ISSUE TITLE
cannot find the module angular2/core

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/nativescript-angular#152]
I just use the command to create nativescript -angular2 app

tns create my-app-name --template https://github.com/NativeScript/template-hello-world-ng

but my vscode show me an error `cannot find the module angular2/core`

beta 9.

and I try to install the definition by `tsd install angular2 rx es6-promise --save`. still not working.
any solution for this these kind of ts issue?

**Comment by hdeshev** [comment]
TypeScript (and hopefully VSCode as well) resolves that module to `node_modules/angular2/core.js`/`...core.d.ts`. Could you  verify that the angular package and that file exist in that location below `node_modules` in your project, and if not, run an `npm install` command to obtain them.

**Comment by dreambo8563** [comment]
I can find the angualr2 folder under nativescript-angular/node_modules.
but not root folder/node_module. you mean I should install angular2 under root path?

**Comment by dreambo8563** [comment]
@hdeshev that  works. npm install angular2 under root path. but the beta.13 installed. hte angular under nativescript-angular is beta.9, hope different version won't raise issues.

**Comment by hdeshev** [comment]
Also, we don't provide beta.13 support yet, so if you encounter any issues, try downgrading to beta.9.
