### ISSUE TITLE
Issue running unit tests after upgrade: Error: Could not find module 'nativescript-angular/zone.js/dist/zone-nativescript'.

### ISSUE THREAD

**Issue by kamok** [NativeScript/nativescript-angular#1523]
Error: Could not find module 'nativescript-angular/zone.js/dist/zone-nativescript'. Computed path '/Users/kamok/Library/Developer/CoreSimulator/Devices/23D6BD89-37DA-42CD-876F-E422E455410D/data/Containers/Bundle/Application/5430F4FF-08BC-4FB2-A6C8-A10F98C17BAF/InternalOrganizing.app/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript'

I ran the commands on the official NS docs on upgrading for nativescript 4.2+

`npm install -g nativescript`
`tns update`
`tns platform remove ios`
`tns platform add ios`
`npm i nativescript-angular@latest --save`
`./node_modules/.bin/update-app-ng-deps`
`npm i`

The app works with `tns run ios`, but `tns test ios` gives me the error.

**Comment by kamok** [comment]
I was able to solve the issue by removing a rogue .js file that did not have an accompanying .ts file

**Comment by Ahnert1** [comment]
@kamok Do you know what rogue .js file you removed?  I'm still looking how to fix the same issue.
