### ISSUE TITLE
How to capture event in drawing pad using "nativescript-drawingpad" plugin 

### ISSUE THREAD

**Issue by kanchanagarwal3** [NativeScript/nativescript-angular#1524]
This issues is happening for ipad device (version 11.4.1)
Nativescript-drawingpad  plugin - 3.0.3
Nativescript - 4.1.2

Issue:
How can we enable a ‘reset’ button by checking if drawing pad is not empty
Is there a way to capture event while writing anything in drawing pad

**Comment by tsonevn** [comment]
This issue was moved to bradmartin/nativescript-drawingpad#44
