### ISSUE TITLE
remove an item from navigation history without clearing the whole history

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1525]
_From @janossuta on September 20, 2018 9:1_

Hi,

I would like to remove an item from navigation history.

I have a route like this

`Homepage -> Comment list -> Add comment`

After you add a comment it navigates back to `Comment list`
So the navigation history is this:
`Homepage -> Comment list -> Add comment -> Comment list`

What I want is to prevent navigation back from `Comment list` to `Add comment` when pressing the back button and jump to `Homepage` instead

`Comment list  -> (back button) skip Add comment -> Homepage` 

Here is a simple example:
https://play.nativescript.org/?template=play-ng&id=zhyj9e

### Which platform(s) does your issue occur on?
Both

_Copied from original issue: NativeScript/NativeScript#6285_

**Comment by tsonevn** [comment]
Hi @janossuta,
Currently, there is no way to remove a Page from the navigation history in NativeScript Angular. Regarding your case, I would suggest creating a modal page, where you can display the content for the `Add comment` component. When the new comment is added, you can close the modal and display the `Comment list` component. 
For more info, you can review the [Modal page article](https://docs.nativescript.org/angular/ui/ng-ui-widgets/modal-page) from the documentation and the sample in the issue [here](https://github.com/NativeScript/nativescript-angular/issues/284#issuecomment-235511604).

**Comment by janossuta** [comment]
Hi @tsonevn,
 
Thank you! I'm going to use modal page then.

**Comment by janossuta** [comment]
Hi @tsonevn,

Thank you it is solved my problem.

But I have an other question regarding modal views. If I have multiple modal views which are not related together but from the same page I have to create a modal-root component for each new modals?

Comment list page -> Add comment modal
Comment list page -> Show comment picture modal

**Comment by tsonevn** [comment]
Hi @janossuta,
Yes, in the described above scenario, when you have multiple modal pages, which are not related, you should define modal-root for each of them. Keep in mind that the [first described approach](https://docs.nativescript.org/angular/ui/ng-ui-widgets/modal-page#modal-page-actionbar) is used in the scenarios, when you would like to setup ActionBar inside the modal page or when you will make navigations inside the modal.

In case you need to display only a specific component as a modal, you can use the approach described in the example [here in the article](https://docs.nativescript.org/angular/ui/ng-ui-widgets/modal-page#sample-modal-page-module-example).

**Comment by BosH9** [comment]
Any solution without model based approach ?

**Comment by joshcomley** [comment]
Is there any solution to this now with all the updates since?

**Comment by IMDaniyal** [comment]
Any update on this without using the modal approach yet?

**Comment by gayatri-kadam** [comment]
Any update here? I wish to clear only the previous item from the navigation history.
