### ISSUE TITLE
Make a Currency Input with TextField

### ISSUE THREAD

**Issue by domzinhuu** [NativeScript/nativescript-angular#1526]
Hi,

I need create a currency input mask for a textfield that change the dot and comma when the user input some value  exemple:

initial value 0,00;

input 1
field 0,01;
------------
input 2
field 0,12;
-------------
input 3
field 1,23;
-------------
input 4
field 1.234;
--------------
input 5
field 1.234,05;

I try with ControlValueAccessor and textChange but no success when format the first value with comma or dot the cursor jump to start of the textField.

**Comment by davimello28** [comment]
Sorry for respawning this topic. But I think that the question resembles a much bigger problem in data formats. Not only on NativeScript but on the web. The reason I know it is that most of the apps that I've developed are related to financial industries.

There is no default way to handle money input. This also explains why the plugins shown above are insufficient to create the desired behavior. Here are some of the problems: 

1. Currency inputs are normally handled in RTL (*right-to-left*), starting with the `0,00` or `0.00` (depending on your location). If you press any digit (Eg:`6`) it should display `0.06` and move the cursor to the end of the string. If another key is pressed (Eg:`3`), the input should display `0.63`, and so on.  There is no support for RTL in `TextField` for NativeScript. The only support for this is a UI plugin that reverses a GridLayout.

2.  Currency inputs usually use masking. As @tsonevn mentioned before, there are some options for plugins. None of those (and none of the ones that I am aware of) can be used to :
 - set a pattern (like `[*0].[00]`) to include N numbers before the dot. You have to specify how many characters you need to use.
- set default values that are going to be replaced during typing. So we are unable to input `6` inside a `0.00` and get a `6.00`.

3. There is a problem with using float points as currency representation: rounding. The correct way of handling it is using a `BigInt` variable for the smallest currency with `DP = 2` and `RM = 1` (according to the law for most countries). 

My point here is: this is hard. Believe me, I spent almost a month searching for *good* a solution and didn't find one. I ended up using [currency.js](https://github.com/scurker/currency.js) for most of my projects.

I hope this changes in the future, but until that, I really don't think that NativeScript developers are going to do something about it. W3C is strugling with this. JavaScript is trying hard to do something about it (with things like `toStringLocale()`). 

Good luck for anyone finding this post in the future.

**Comment by faelperetta** [comment]
Hi @domzinhuu, did you find a solution for your problem? I'm trying to do the same thing and the suggested plugins **nativescript-masked-text-field** or **nativescript-input-mask** has a different behavior that we expect.

**Comment by flipimmobilier** [comment]
Good morning all. I read your comments. And I try in a calculation application to display the amount in this way: $ 2 000 000.

with the help of two programmer we tried the pipes on android. we have come to successful but on ios when registering a $ 5 digits he will be writing $ 55 due to the dollars.

your solution works on android but not on ios. Is there any new solution for ios or android?

**Comment by faelperetta** [comment]
Hi @domzinhuu, thanks for share your solution.
I ended up creating my own solution using a set method for the model where I format the value. I using the [Intl.NumberFormat](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat) to format the value for me according to the current language of the user.

**Comment by Natym-git** [comment]
> Sorry for respawning this topic. But I think that the question resembles a much bigger problem in data formats. Not only on NativeScript but on the web. The reason I know it is that most of the apps that I've developed are related to financial industries.
> 
> There is no default way to handle money input. This also explains why the plugins shown above are insufficient to create the desired behavior. Here are some of the problems:
> 
> 1. Currency inputs are normally handled in RTL (_right-to-left_), starting with the `0,00` or `0.00` (depending on your location). If you press any digit (Eg:`6`) it should display `0.06` and move the cursor to the end of the string. If another key is pressed (Eg:`3`), the input should display `0.63`, and so on.  There is no support for RTL in `TextField` for NativeScript. The only support for this is a UI plugin that reverses a GridLayout.
> 2. Currency inputs usually use masking. As @tsonevn mentioned before, there are some options for plugins. None of those (and none of the ones that I am aware of) can be used to :
> 
> * set a pattern (like `[*0].[00]`) to include N numbers before the dot. You have to specify how many characters you need to use.
> * set default values that are going to be replaced during typing. So we are unable to input `6` inside a `0.00` and get a `6.00`.
> 
> 1. There is a problem with using float points as currency representation: rounding. The correct way of handling it is using a `BigInt` variable for the smallest currency with `DP = 2` and `RM = 1` (according to the law for most countries).
> 
> My point here is: this is hard. Believe me, I spent almost a month searching for _good_ a solution and didn't find one. I ended up using [currency.js](https://github.com/scurker/currency.js) on most of my projects.
> 
> I hope this changes in the future, but until that, I really don't think that NativeScript developers are going to do something about it. W3C is struggling with this. JavaScript is trying hard to do something about it (with things like `toStringLocale()`).
> 
> Good luck to anyone finding this post in the future.
----------------------------------------
Hi @davimello28 ! 
Could you please provide an example of the use of currency.js in Nativescript?

Thank you!

**Comment by MateusSpadari** [comment]
Hello @faelperetta i'm struggling with this, can you share you solution ?

**Comment by edusperoni** [comment]
https://play.nativescript.org/?template=play-ng&id=b2D1DH&v=2

Check `currency-input.ts`. You can change `numberToCurrency` and `currencyToNumber` to fit your needs.

I've added a helper function (`toEnd`) that will move the cursor to the end of the string.
