### ISSUE TITLE
text-align in android device

### ISSUE THREAD

**Issue by aminghe** [NativeScript/nativescript-angular#1527]
### If there is no issue for your problem, tell us about it
Hello
When I'm running on Android - I set Label the text-align to the right. Posts go to the left.
Play.nativescript.org link

https://play.nativescript.org/?template=play-ng&id=Yjrr3x&v=3

The language is Persian.

![photo_2018-09-24_13-04-25](https://user-images.githubusercontent.com/16360624/45945436-6579a400-bffa-11e8-913f-9265f2502148.jpg)

### Which platform(s) does your issue occur on?
- Android
- emulator or device. Both

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.2.3
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0

**Comment by tsonevn** [comment]
Hi @aminghe,
Thank you for the provided sample project. 
I reviewed your case, and it seems that a similar issue has been already logged [here](https://github.com/NativeScript/NativeScript/issues/6051). You can also check the provided solutions ([solution 1](https://github.com/NativeScript/NativeScript/issues/6051#issuecomment-404440939) [solution 2](https://github.com/NativeScript/NativeScript/issues/6051#issuecomment-404850628)).
