### ISSUE TITLE
Ability to disable custom modal dialog close back navigation

### ISSUE THREAD

**Issue by kkoates** [NativeScript/nativescript-angular#1534]
Feature request:

Ability to disable custom modal dialog on close back navigation by providing an option similar to "fullscreen" when showing the modal. 

Use case:

I have a simple RadSideDrawer template app where I would like to be able to display a global modal.  This can easily be achieved by showing a modal from the root app component.  The modal shows no matter the page however upon closing it always routes back to the root page setup in routing instead of the current page.

A trial of removing the line below changed the behavior of closing the modal and navigating back a page to simply closing the modal.

https://github.com/NativeScript/nativescript-angular/blob/6155f022cb05dfbd0d6e3b19aab53561f14f65f6/nativescript-angular/directives/dialogs.ts#L132

**Comment by tsonevn** [comment]
Hi @kkoates,
This issue seems to be duplicated with the one described [here](https://github.com/NativeScript/nativescript-angular/issues/1503). Let me know, if I am missing something or if you think that the case is different.

**Comment by kkoates** [comment]
@tsonevn Thanks for yet another quick response and all the work you are doing for the NativeScript community.  I posted a proposed solution in [#1534](https://github.com/NativeScript/nativescript-angular/issues/1503).  I originally opened this a feature request because I was having a tough time deciding if the location.back call in closeCallback is bug/issue in all cases.
