### ISSUE TITLE
RouterExtension.back() doesn't works after upgraded to the latest version 6.1.0

### ISSUE THREAD

**Issue by LSmint** [NativeScript/nativescript-angular#1548]
**Describe the bug**
The routerExtension.back() doesn't navigate back to the previous page after i upgraded angular from 5.2 to 6.1.

**Sample project**
import { RouterExtensions } from "nativescript-angular/router";
constructor(private router: RouterExtensions) {}

navigateBack() {  <=== A button to trigger the back function
        this.router.back();
}

**Additional context**
Package.json info:
{
  "nativescript": {
    "tns-ios": {
      "version": "4.1.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "^6.1.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^6.0.0",
    "tns-core-modules": "^4.2.1",
    "tns-platform-declarations": "^4.2.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/core": "~0.6.3",
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.0.3",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.5.1",
    "css-loader": "~0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-assets": "0.0.6",
    "nativescript-dev-sass": "^1.3.5",
    "nativescript-dev-typescript": "^0.5.1",
    "nativescript-dev-webpack": "^0.12.0",
    "nativescript-worker-loader": "~0.9.0",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.3.0",
    "sass-loader": "~7.0.1",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "~1.2.5",
    "webpack": "~4.6.0",
    "webpack-bundle-analyzer": "~2.13.0",
    "webpack-cli": "~2.1.3",
    "webpack-sources": "~1.1.0"
  }
}

**Comment by NickIliev** [comment]
@LSmint I've created [this basic Playground demo](https://play.nativescript.org/?template=play-ng&id=UhwCzP) using the `back` method and it works as expected on my side. Can you provide more details on how to reproduce your issue (e.g. by providing a Playground or a sample app)

**Comment by LSmint** [comment]
I have tried to rebuilt your playground code and follow exactly as the package.json that i posted, at the end i can't simulated the issue. It may due to my code didn't not placed correctly. I will follow your version as a base.
