### ISSUE TITLE
Open plugin and go back to the app [slow response]

### ISSUE THREAD

**Issue by NeriCodec** [NativeScript/nativescript-angular#1552]
**Environment**
```
{
  "nativescript": {
    "id": "org.nativescript.apphardworkers",
    "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "~6.1.0",
    "nativescript-camera": "^4.0.2",
    "nativescript-imagecropper": "^1.0.4",
    "nativescript-imagepicker": "^6.0.4",
    "nativescript-localstorage": "^2.0.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.2.0",
    "tns-core-modules": "~4.2.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@nativescript/schematics": "~0.2.5",
    "codelyzer": "~4.3.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.16.0",
    "tslint": "~5.11.0",
    "typescript": "~2.7.2",
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.2.0"
  },
  "readme": "NativeScript Application"
}
```
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):
 - NativeScript-Angular:
 - Angular:
 
**Describe the bug**
When opening any activity that is provided by another plugin, for example camera, paypal, gallery and return to the main Nativescript activity, the screen stays locked for 5 ~ 10 seconds

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@NeriCodec is this happening on a specific API level/device?(btw: Android or iOS?). Is there any specific code involved in your case - if so please provide a sample application and detailed information about the testing device

Using [this test application,](Android or iOS) the issue seems not to be reproducible on my side.

**Comment by NeriCodec** [comment]
Hi @NickIliev The telephone for the tests has the following requirements,  but with any phone the same thing happens (just go with android):

- Processor: 2
- Base memory (MB): 1024 mb
- Android version: 6.0 (level api 23)


The performance problem happens with any plugin in the market.nativescript.org that must be opened in another tab that is not the same as the app (eg, camera, gallery, paypal checkout, photo-viewer, etc.), that creates a new activity and return to the main, at the time of returning to the main appears a delay in responding the app of 5 ~ 10 seconds.

**Comment by NickIliev** [comment]
@NeriCodec We are testing the scenarios on phones with even lower hardware specifications and we are not able to recreate similar time issues. Try the same scenario on a different device just to verify that the issue is not related to a specific device problem.

**Comment by NeriCodec** [comment]
@NickIliev I have already tried several phones and after several investigations activating "markingMode": "none", drastically improved my results, there is no delay time.

**Comment by NickIliev** [comment]
@NeriCodec great news! Still, I would advise fully testing your application as the `markingMode` option is still experimental and might lead to side effects.

**Comment by NeriCodec** [comment]
At what point can we use 100% "markingMode": "none", because without it, the performance of my application when opening plugins is slow...

**Comment by NickIliev** [comment]
@NeriCodec can' really tell if the code behind the nativescript-imagecropper will cause issues but your could test extensively the part of the code where the UI plugins that are using native libraries are called.

More info on what exactly `markingMode` is doing and how it works can be found [in this thread](https://github.com/NativeScript/android-runtime/issues/887#issuecomment-378895152)

**Comment by NeriCodec** [comment]
Thanks @NickIliev, but I still can not find a solution, the only way that the app does not have those freeze lapses is with `markingMode`

**Comment by NickIliev** [comment]
@NeriCodec as a solution can you try introducing the following option in your `AndrоidManifest` file

```
android:launchMode="singleInstance"
```

More about the above optiin [here](https://inthecheesefactory.com/blog/understand-android-activity-launchmode/en)

**Comment by NeriCodec** [comment]
@NickIliev I think he did not make any changes, but I will try `markingMode` for the moment in production mode. Thanks !!!

**Comment by tsonevn** [comment]
Hi @NeriCodec,
Were you able to solve the issue with the slow response?

**Comment by NeriCodec** [comment]
Hi @tsonevn, I have not been able to solve it, the only way is with `markingMode`

**Comment by NickIliev** [comment]
@JavierAnaya @NeriCodec the core modules (`tns-core-modules`) and the plugins under the NativeScript organization are now all having official support for markingMOde (meaning we are testing them for stability and performance). If you guys still have an issue when using `markingMode` then please isolate the bug to a specific plugin and report the issue at the plugin's repository
