### ISSUE TITLE
Understanding startup profiling

### ISSUE THREAD

**Issue by gummibjorn** [NativeScript/nativescript-angular#1553]
Hi everyone

After investing some time in improving app-startup-time we got down to quite an acceptable speed.
Thanks to https://www.nativescript.org/blog/deep-dive-into-nativescript-3.1-performance-improvements.

I am asking now if someone could explain to me what this rather big chunk (marked with a black box) does? I assume it has something to do with angular bootstrap, but according to the blog it is just the creation of the activity and the frame which shouldn't take that long.

Thankful for any input.

![startup_profiling](https://user-images.githubusercontent.com/11292339/46736346-163d9f80-cc99-11e8-8257-fda7b6df44b7.png)

**Comment by NickIliev** [comment]
The 800ms are[ for the Angular bootstrapping](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/platform-common.ts#L201-L257)

**Comment by gummibjorn** [comment]
alright, thanks!

So this can be lowered by using AoT compilation

**Comment by NickIliev** [comment]
Yep it should - try building with [webpack ](https://docs.nativescript.org/angular/performance-optimizations/bundling-with-webpack)and AOT
```
npm i nativescript-dev-webpack --save-dev
tns run android --bundle --env.uglify --env.aot --env.snapshot
```
