### ISSUE TITLE
nativeScriptBootstrap should probably return a promise

### ISSUE THREAD

**Issue by matt4446** [NativeScript/nativescript-angular#156]
Angular 2 [bootstrap](https://github.com/angular/angular/blob/master/modules/angular2/src/core/application_ref.ts#L341-l342) - returns `Promise<ComponentRef>`

NativeScript's Angular2 [bootstrap](
https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/application.ts#L54) implementation - returns `Promise<ComponentRef>`

NativeScript's [nativeScriptBootstrap](https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/application.ts#L91-l128) implementation returns `void`. 

I expect the sample projects and documentation will continue to prefer the `nativeScriptBootstrap` function to start the application. What I believe to be missing from `nativeScriptBootstrap` is that it should return a `Promise<ComponentRef>` just as the bootstrap method does, which will make the following possible and add flexibility if needed: 

`nativeScriptBootstrap(startComponent).then((appRef : ComponentRef) => {});`

**Comment by battistaar** [comment]
I'm trying to use the promise, but it seems that it is never called.

`
nativeScriptBootstrap(AppComponent).then(function(appRef: ComponentRef<AppComponent>){
  console.log("done!");
});
`

The console prints "ANGULAR BOOTSTRAP DONE." and nothing else.

**Comment by matt4446** [comment]
I'm pretty sure it works as I use it [here](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/decorators/app.ts#L59-L66). Which version of nativescript-angular are you using? 

I'll double check this evening to make sure.

**Comment by battistaar** [comment]
0.1.6
I checked the source code of the package and it should return a promise and resolve it with the app ref, but it doesn't.

I'm not sure that's the problem, but according to the [documentation](https://docs.nativescript.org/core-concepts/application-management#ios-uiapplicationdelegate) "Any code after the start call will not be executed.". nativeScriptBootstrap calls  application.start and it seems that everything I write after is not executed, either inside or outside the "then".

**Comment by matt4446** [comment]
Curious. Lucky I never read the documentation. That just raises more questions. Are you running it on IOS? I have not tried it there. 

I didn't escape work till just over an hour ago ... and so my response is much later than expected. 

Android:
```
JS: Setup App annotations
JS: Page loaded
JS: BOOTSTRAPPING...
JS: Setting DOM
JS: =Debug===============
JS: 2016-05-20T21:49:46.510Z: Main Page Starting
JS: ======================
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ANGULAR BOOTSTRAP DONE.
JS: Add element: CardView
JS: Add element: PullToRefresh
JS: =Debug===============
JS: 2016-05-20T21:49:46.843Z: Start Page - constructor hit
JS: ======================
```

Two console writes after the app promise:
```
JS: Add element: CardView
JS: Add element: PullToRefresh
```
It is the only place I have `Add element`. ;-) 

subscribing to the promise on the [sample app](https://github.com/NativeScript/sample-Groceries/tree/angular/app) I presume you end up with the same result? (from the nativescript samples http://docs.nativescript.org/angular/tutorial/ng-chapter-1)

**Comment by battistaar** [comment]
I did some tests and it seems that it's an iOS related problem, it works on android emulator

**Comment by matt4446** [comment]
I would create a new issue and copy this one in.
