### ISSUE TITLE
Angular http observable not triggering

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1561]
_From @gonniegijsen on October 19, 2018 12:34_

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  4.2.4
 - Cross-platform modules: 4.2.1
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s):

**Describe the bug**

This is more a question;
I'm working on an application with nativescript-angular that needs to send information to the server each 10minutes (I need access to my angular services as well). When the phone is locked and charging everything works fine but when I remove the charger, the http requests take ages to complete and when I unlock it everything works again.

**To Reproduce**

```typescript
setInterval(() =>
{
// do stuff
}, 60000);
```
lock the phone without charger, after some time the interval will not trigger correctly (or not trigger at all)

**Expected behavior**

**Sample project**

**Additional context**

_Copied from original issue: NativeScript/NativeScript#6435_

**Comment by tsonevn** [comment]
Hi @gonniegijsen,
Check out [this Blog post for Android](https://www.nativescript.org/blog/using-android-background-services-in-nativescript) and  [ the BackgroundExecution article for iOS](https://docs.nativescript.org/core-concepts/ios-runtime/how-to/BackgroundExecution) where it is described, what are the options for executing tasks, when the app is in background.

**Comment by gonniegijsen** [comment]
I took a look at it and was able to get it working but I'm not sure how I can inject my angular services in them

**Comment by tsonevn** [comment]
Hi @gonniegijsen,
You can try using the [http module](https://docs.nativescript.org/api-reference/modules/_http_) provided by tns-core-modules for making the needed request while the app is in a background.

**Comment by gonniegijsen** [comment]
Hi,

A bit of a late response but yea I focused on android and got it working.

Now I am working on the iOS version but the applicationPerformFetchWithCompletionHandler is never fired on a real device (simulator works fine). My guess is that I have to call applicationPerformFetchWithCompletionHandler on sharedApplication but I'm not sure where I should do that. I put it in app.component.ts but it seems to not trigger
