### ISSUE TITLE
Getting data from webview

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1568]
Hey gyes
I am using nativescript webview to simply show the page but can i get data from the html file in my nativescript angular app ?
like we can get data from html forms using js
https://stackoverflow.com/questions/40889152/is-it-possible-to-get-data-from-html-forms-into-android-while-using-webview

and what if we get a string of html tags or what ever from which we grab the desired value

just an example if their a number 2 on the page i know the tag and its id so i get the tags html and then get over desired value directly into my app
is it possible ?

**Comment by tsonevn** [comment]
Hi @tahir-jamil,
Check out `nativescript-webview-interface` plugin, which can help you in making communication between WebView and the application. To make it work, you might need to make some changes in the page, which will be loaded in the WebView (including `nativescript-webview-interface.js` script, adding some event listeners). For more info, you can check the plugin's [ReadMe file](https://www.npmjs.com/package/nativescript-webview-interface).
