### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by divyachandana** [NativeScript/nativescript-angular#1571]
Undefined symbols for architecture i386:
  "_fEqual", referenced from:
      -[FIRVisionPoint isEqual:] in FirebaseMLVision(FIRVisionPoint_4f04bc57476c98935c2a2df41948a031.o)
  "_OBJC_CLASS_$_FBMLx_GMVFaceInitializationOptions", referenced from:
      objc-class-ref in FirebaseMLVision(FIRVisionFaceDetectorOptions_aad8020cef277ef84e95fb1088aff2ba.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

**Comment by tsonevn** [comment]
Hi @divyachandana,
Please provide the info requested in the template(I am attaching the template below) and the full error log.
Meanwhile, you can try to clear up the content of the derived data folder(`~/Library/Developer/Xcode/DerivedData`) and make sure that you are using the latest pod(you can update cocoapods spec repos using `pod repo update` command) and the latest [nativescript-plugin-firebase](https://www.npmjs.com/package/nativescript-plugin-firebase) plugin's version `7.3.0`.

Template ->
```
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):
 - NativeScript-Angular:
 - Angular:
 
**Describe the bug**
<!-- A clear and concise description of what the bug is. Please, explain whether it's a build time error or a runtime error. More detailed logs can be easily obtained by following the instructions in this guide: https://docs.nativescript.org/get-support#how-to-obtain-diagnostic-reports. -->

**To Reproduce**
<!-- Add commands used or steps taken to reproduce the behaviour. -->

**Expected behavior**

**Sample project**
<!-- If possible, provide a link from the [Playground](https://play.nativescript.org) with reproduction of the problem. If not, consider attaching a sample project or link to a repository with such project. -->

**Additional context**
<!-- Add any other context about the problem here. -->

```

**Comment by EddyVerbruggen** [comment]
The Firebase plugin has just been bumped to 7.4.0, which solves the issue.
