### ISSUE TITLE
unable to load images from  local files in nativescript angular

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1586]
hear is the error log.
JS: Error in reading bitmap - java.io.FileNotFoundException: /data/data/org.nativescript.testingOne/files/app/images/chair.png (No such file or directory)

hear is the repo issue will recreate from the start itself
https://github.com/tahir-jamil/new-translator

hear is my list
`<ActionBar title="English to Chinese" class="action-bar">
	<ActionItem (tap)="favourite()" backgroundColor="transparent" ios.position="right">
		<Button text="&#xe87d;"  backgroundColor="transparent" borderWidth="1dp" borderColor="transparent" class="mdiBottomBarIcons f-25" ></Button>
	</ActionItem>
</ActionBar>

<GridLayout rows="auto,*,auto" columns="*">
	
	<GridLayout row="1" colSpan="2" tkExampleTitle tkToggleNavButton>
		<RadListView [items]="userData">
			<ng-template tkListItemTemplate let-item="item">
				<GridLayout class="itemWord" rows="auto,auto,auto" columns="auto,*,auto">
					<GridLayout rows="auto" columns="*,*" borderRadius="5">
						<GridLayout (tap)="getData()" columns="auto,auto">
							<Label [text]="item.english" textWrap="true" class="p-r-5"></Label>
							<Label col="1" text="&#xe050;" (tap)="stateAudioSound()" class="mdiBottomBarIcons alignIcon f-25" textWrap="true"></Label>
						</GridLayout>
					</GridLayout>
					
					<GridLayout rows="auto" columns="*,*" col="2" borderRadius="5">
						<GridLayout (tap)="saveData()" columns="auto,auto" horizontalAlignment="right">
							<Label [text]="item.chinese" textWrap="true" class=" text-right p-r-5"></Label>
							<Label col="1" text="&#xe050;" (tap)="stateAudioSound()" class="mdiBottomBarIcons f-25 alignIcon text-right " textWrap="true"></Label>
						</GridLayout>
					</GridLayout>

					<GridLayout row="1" colSpan="3" class="image-size">
						<Image row="2" stretch="aspectFill" [src]="'~/images/' + item.img" ></Image>
					</GridLayout>
					<Label row="2" col="2" text="Add to Favourite" class="text-right f-13 text-muted" textWrap="true"></Label>
				</GridLayout>
			</ng-template>
		</RadListView>
	</GridLayout>
</GridLayout>

data = [
    { english:"book", chinese: "chinese", img: "chair.png"},
    { english:"book", chinese: "chinese", img: "chair.png"},
    { english:"book", chinese: "chinese", img: "chair.png"},
    { english:"book", chinese: "chinese", img: "chair.png"},
    { english:"book", chinese: "chinese", img: "chair.png"},
    { english:"book", chinese: "chinese", img: "chair.png"},
    { english:"book", chinese: "chinese", img: "chair.png"},
    { english:"book", chinese: "chinese", img: "chair.png"}
  ]

`
and this is the data i am showing

this is the result i get

![screen shot 2018-11-04 at 9 16 08 pm](https://user-images.githubusercontent.com/40952630/47966673-de96fd00-e076-11e8-82ab-41a389cc9558.png)

**Comment by tsonevn** [comment]
Hi @tahir-jamil,
The issue in the project is related to wrong image path. `~/` will points to the `src` folder. In this case, you should change the path from `[src]="'~/images/' + item.img"` to `[src]="'~/app/images/' + item.img"`

**Comment by PeymanKhodadust** [comment]
I had the same problem. Normally it wouldn't be a problem to figure out which directory is meant by "~" if there wasn't the confusing error message:

> /data/data/org.nativescript.testingOne/files/_app_/images/chair.png (No such file or directory)

@tsonevn Thank you for the tip. Now I can even reference the assets folder ;-)

**Comment by MonsterGameDev** [comment]
Thank You, Thank You, Thank You ..... :-)

**Comment by Neyodhino** [comment]
Thank you....
