### ISSUE TITLE
Creating new project in nativescript not working! Resource ID #0xfffffff6

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1591]
hear is the error logs for new project 

> System.err: java.lang.RuntimeException: Unable to resume activity {org.nativescript.voteCandidate/com.tns.NativeScriptActivity}: android.content.res.Resources$NotFoundException: Resource ID #0xfffffff6

issue to reproduce
tns create new-angular --ng
tns debug android

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/android-runtime #1204](https://github.com/NativeScript/android-runtime/issues/1204) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/android-runtime #1205](https://github.com/NativeScript/android-runtime/issues/1205) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/android-runtime#1206
