### ISSUE TITLE
How do I get nativescript to launch other apps using deeplink?

### ISSUE THREAD

**Issue by ls8266** [NativeScript/nativescript-angular#1595]
**Environment**
 - Android Runtime: 5.1

**Comment by tsonevn** [comment]
Hi @ls8266,
Check out this plugin - [nativescript-open-app](https://www.npmjs.com/package/nativescript-open-app). For further questions use [this](https://stackoverflow.com/questions/tagged/nativescript) StackOverflow thread. This repository is used only for bug reporting and feature request related to nativescript-angular.

**Comment by ls8266** [comment]
Thank you for helping me solve this problem.

> Hi @ls8266,
> Check out this plugin - [nativescript-open-app](https://www.npmjs.com/package/nativescript-open-app). For further questions use [this](https://stackoverflow.com/questions/tagged/nativescript) StackOverflow thread. This repository is used only for bug reporting and feature request related to nativescript-angular.
