### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by SkupeZZ** [NativeScript/nativescript-angular#1597]
I'm using a blank ng template and it seems it's not possible to use custom fonts. I've tried to place the "fonts" folder under /my-project/src/app/fonts and /my-project/fonts, and I've also named the font family after the file's name.

In order to reproduce, install the blank ng template
`tns create my-blank-ng --template tns-template-blank-ng`
and try using a custom font.

**Comment by jibon57** [comment]
@SkupeZZ the location of `fonts` directory should be `/my-project/src/fonts`

**Comment by SkupeZZ** [comment]
That solved it, thanks 👍

**Comment by pisitch** [comment]
I got this issue too. I tried for a week but it isn't work.

![2019-01-13_10-34-31](https://user-images.githubusercontent.com/15905772/51081338-0e6e1b00-1720-11e9-92ba-a7e02e63401f.jpg)
![2019-01-13_10-35-36](https://user-images.githubusercontent.com/15905772/51081340-1463fc00-1720-11e9-88f6-f05fe5e2b4e2.jpg)
![2019-01-13_10-38-02](https://user-images.githubusercontent.com/15905772/51081342-17f78300-1720-11e9-8999-48ddf078dc24.jpg)

**Comment by tsonevn** [comment]
HI @pisitch,
Can you send us a sample project, which can be used for debugging?

**Comment by pisitch** [comment]
I have solved this problem. The problem is that Android is required to exactly use font file name in CSS file ,whereas IOS is required to exactly font name.

**Comment by Avonstar** [comment]
Fabulous. It worked. Thanks.
