### ISSUE TITLE
TypeScript compilation issues

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#16]
Hey @hdeshev,

I’m going through the installation instructions, but the TypeScript compilation seems to be failing. Specifically when I run `grunt ng-sample` I get the following error:

```
Running "ts:build" (ts) task
Compiling...
Using the custom compiler : node_modules/typescript/bin/tsc
/Users/tj/dev/nativescript/nativescript-angular/ng-sample/src/angular2/typings/zone/zone.d.ts(1,1): error TS6053: File '/Users/tj/dev/nativescript/nativescript-angular/ng-sample/src/angular2/typings/es6-shim/es6-shim.d.ts' not found.
```

Any idea what’s up here?

Thanks.

**Comment by hdeshev** [comment]
I had forgotten to add a gitignored file, and I had to add a tiny regex hack to get rid of the es6-shim error. The build should be fine now.
