### ISSUE TITLE
[5.0.0] could not open modal from an outlated compoent ! 

### ISSUE THREAD

**Issue by alqabali** [NativeScript/nativescript-angular#1600]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0
 - Cross-platform modules: 5.0.0
 - Android Runtime: 5.0.0
 - iOS Runtime:5.0.0
 - Plugin(s):N/A

**Describe the bug**
i did not change anything from the project that worked perfectly on pre-current version(4.X.X) , but after updating the tns cli and tns-core-modules and android runtime to the latest version (5.0 .0) i could not open the modals anymore i get this error:

> JS: ERROR TypeError: Cannot set property 'showingModal' of undefined
JS: ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
JS:       "nodeFlags": 660062213,
JS:       "rootNodeFlags": 1,
JS:       "nodeMatchedQueries": 30,
JS:       "flags": 0,
JS:       "nodes": [
JS:         {
JS:           "nodeIndex": 0,
JS:           "parent": null,
JS:           "renderParent": null,
JS:           "bindingIndex": 0,
JS:           "outputIndex": 0,
JS:           "checkIndex": 0,
JS:           "flags": 1,
JS:           "childFlags": 660062213,
JS:           "directChildFlags": 33554433,
JS:           "childMatchedQueries": 30,
JS:           "matchedQueries": {},
JS:           "matchedQueryIds": 0,
JS:           "references": {},
JS:           "ngContentIndex": null,
JS:           "childCount": 31,
JS:           "bindings": [],
JS:           "bindingFlags": 0,
JS:           "outputs": [],
JS:           "element": {
JS:             "ns": "",
JS:             "name": "GridLayout",
JS:             "attrs": [
JS:               [
JS:                 "",
JS:                 "columns",
JS:                 "*"
JS:               ],
JS:               [
JS:                 "",
JS:                 "rows",
JS:                 "auto,auto,*,auto"
JS:               ]

**To Reproduce**

```
const options: ModalDialogOptions = {
      viewContainerRef: this.vcRef,
      context: data,
      fullscreen: true
};
return this.modalService.showModal(SomeComponentName, options).then(
      data =>
        console.log(data),
      error => {
        console.log(error);
      }
);
```

**Expected behavior**
opening the modal as it does before updating .

**Additional context**
**PS 1 : i'm call this function from tabview item (outlet component like the default one used [here](https://github.com/NativeScript/template-tab-navigation-ng)  ) .**
**PS2 : i have imported and injected everything as usually (the modal works in the previous versions) .**
**PS 3 : i'm currently producing this issue using Android 8 (Samsung S7)**

**Comment by tsonevn** [comment]
Hi @alqabali,
Can you send us a sample project, which can be used for debugging? I tested the described scenario on my side, however, was unable to recreate the problem. 

Meanwhile, try to clear up the project following the below-attached steps:
1. delete `platforms`, `node_modules`,  `hooks` folders and `package-lock.json` file.
2. run `npm i`
3. rebuild the project with `tns run android`
