### ISSUE TITLE
unable to change statusbar text color to white text (iOS)

### ISSUE THREAD

**Issue by gonick** [NativeScript/nativescript-angular#1601]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.0 
 - Cross-platform modules: 5.0.2 
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s):
 - NativeScript-Angular: ^6.2.0
 - Angular: 6.1.3
 
**Describe the bug**
I want the status bar text color to be white.

I tried two approaches:
Approach 1:

//App.component
ngOnInit() {
     if (isIOS) {
      topmost().ios.controller.navigationBar.barStyle=1;
     }
  }
-> says controller is undefined.
--------------------------
Approach 2:
//main.ts

import * as application from 'application';
import * as platform from 'platform';
import * as utils from 'utils/utils';

declare var UIResponder: any;
declare var UIStatusBarStyle: any;
declare var UIApplication: any;
declare var UIApplicationDelegate: any;

export function setStatusBarColors() {
  //ios status bar transparent with white color;
  if (application.ios) {
    let AppDelegate = UIResponder.extend({
      applicationDidFinishLaunchingWithOptions: function () {
        utils.ios.getter(UIApplication, UIApplication.sharedApplication).statusBarStyle =
          UIStatusBarStyle.LightContent;
        return true
      }
    }, {
        name: "AppDelegate",
        protocols: [UIApplicationDelegate]
      });
    application.ios.delegate = AppDelegate;
  }
}

//and invoking this function in main.ts
setStatusBarColors();
-> still not working

**Comment by tsonevn** [comment]
Hi @gonick,
Check out [nativescript-statusbar](https://www.npmjs.com/package/nativescript-statusbar) plugin, which enables changing the StatusBar color in NativeScript. Also, to use the component from the plugin in a NativeScript Angular app you need to register it. Review the article [here](https://docs.nativescript.org/plugins/angular-third-party).

**Comment by gonick** [comment]
This is also not working with nativescript-angular and no one is answering on that repo as well.
@tsonevn Could you please help me with a way to implement this.

**Comment by felicks** [comment]
I followed the article but its not working for me...

app.module.ts
```
import { registerElement } from 'nativescript-angular/element-registry';
registerElement("StatusBar", () => require("nativescript-statusbar").StatusBar);
```
html
`<StatusBar ios:barStyle="light" android:barStyle="red"></StatusBar>`

**Comment by tsonevn** [comment]
HI @felicks,
If you are facing a problem with the `nativescript-statusbar` plugin, please contact the plugin's author by opening a new issue in the [plugin's repository](https://github.com/burkeholland/nativescript-statusbar).
