### ISSUE TITLE
Page is not able to add css file when using --bundle in Component.

### ISSUE THREAD

**Issue by relez** [NativeScript/nativescript-angular#1602]
Hi guys, I am trying to add css files in components according if the device is a tablet or phone, based on this article [Tablet support for NativeScript with Angular](https://www.nativescript.org/blog/tablet-support-for-nativescript-with-angular) it works as expected using nativescript-angular (tns run ios), but if I use webpack (tns run ios --bundle) does not work.

Any suggestions?

Thanks!

**Comment by tsonevn** [comment]
Hi @relez,
Can you provide a sample project, which demonstrates the issue? You might need to specify the path to the CSS files, which you need to include in the bundle. Check out the example [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/webpack.config.js#L224-L229).

**Comment by relez** [comment]
Hi there, adding this line to  to webpack.config.js worked:

```
new CopyWebpackPlugin([
    ...
    { from: "**/*.css" }, // New line added!
    ...
```

Thanks!
