### ISSUE TITLE
How can i integrate 360 image preview with nativescript angular?

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1609]
Hey i am new to nativescript angular and how can i use 360 degree image preview . We have support of VR in nativescript so how can i do that?

**Comment by tsonevn** [comment]
Hi @tahir-jamil,
Check out the [nativescript-panorama-imageview](https://www.npmjs.com/package/nativescript-panorama-imageview). It seems that this plugin can help in achieving the needed result.
