### ISSUE TITLE
Custom ActionBar not working ANDROID(ANGULAR) version 5.0.0

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1613]
@tebieto commented on [Fri Nov 16 2018](https://github.com/NativeScript/NativeScript/issues/6566)

Everything is working fine on my new Nativescript-Angular project but my custom ActionBar <ActionBar></ActionBar> does not display. The App uses the default ActionBar with default app title... tns vesion is 5.0.0. 

---

@tsonevn commented on [Fri Nov 16 2018](https://github.com/NativeScript/NativeScript/issues/6566#issuecomment-439417012)

Hi @tebieto,
Can you provide a sample project or at least some sample code snippets, which can be used for recreating the problem?

**Comment by tebieto** [comment]
OK, I will upload project and send link right away

**Comment by tebieto** [comment]
Here is the project https://github.com/tebieto/Panafri-User-Ng

**Comment by tebieto** [comment]
Any help?

**Comment by tebieto** [comment]
@tsonevn  any help please?

**Comment by tebieto** [comment]
Hello I found the solution,

import { NativeScriptCommonModule } from "nativescript-angular/common";

was missing in my home.module.ts file

**Comment by tsonevn** [comment]
Hi @tebieto,
I am glad to hear that the issue is resolved on your side. I think that we can close the issue.
