### ISSUE TITLE
could not leave an outlet component when i set tab as root

### ISSUE THREAD

**Issue by alqabali** [NativeScript/nativescript-angular#1615]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules: 5.0.0
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - Plugin(s): -
 - NativeScript-Angular: 5.0.0
 - Angular: 7
 
**Describe the bug**
using this project strucutre:
```
-app.component.ts (root tab)
---home.module
--------home tab (outlet)
--------categories tab (outlet)
--------etc.. (outlet)
---login.module(lazy loaded)
---ex.module (lazy loaded)
```
when i'm inside any tab (outlet component) i canno't leave the tabview totally in order to go inside an other component outside the tabview (login component as exemple).

**To Reproduce**

**Expected behavior**
the tabview shoudl diseappear and login will appear .

**Sample project**

https://play.nativescript.org/?template=play-ng&id=IyP222&v=11

**Additional context**
1) im using lazy-load modules .
2)playground angular version does not orgnize tabview root , so please use your owen envirement to test the bug .

**Comment by tsonevn** [comment]
Hi @alqabali,
Thank you for the provided sample project,
When you are using `page-router-outlet` for the TabView's tabs, you need to specify the path for each page router-outlet directly by using its name and the path of the initial page. Check out, how it is done in the [template-tab-navigation-ng](https://github.com/NativeScript/template-tab-navigation-ng/blob/master/src/app/app-routing.module.ts). In your case the outlet name should be followed by the path, that loads the module. 
```
import { NgModule } from "@angular/core";
import { Routes } from "@angular/router";
import { NativeScriptRouterModule } from "nativescript-angular/router";

const routes: Routes = [
    { path: "", redirectTo: "/(homeTab:home//browseTab:login)", pathMatch: "full" },
    { path: "home", loadChildren: "~/home/home.module#HomeModule", outlet: "homeTab" },
    { path: "login", loadChildren: "~/login/login.module#LoginModule", outlet: "browseTab" }
];

@NgModule({
    imports: [NativeScriptRouterModule.forRoot(routes)],
    exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }

```
Also, in the HomeModule, you should define the root path, which should be loaded. For your convenience, I am attaching the project with some changes in it. 
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2595031/Archive.zip)

Keep in mind that currently preview app has a limitation and does not support lazy loading with angular projects.
