### ISSUE TITLE
Typing ng g component stops LiveSync

### ISSUE THREAD

**Issue by dolanmiu** [NativeScript/nativescript-angular#1627]
Ttyping in `ng g component my-component` in the command line stops LiveSync, and I need to restart the app with `tns run ios` every time

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4171](https://github.com/NativeScript/nativescript-cli/issues/4171) via [**ZenHub**](https://www.zenhub.com/)
