### ISSUE TITLE
Modal dialogs always open fullscreen on iOS

### ISSUE THREAD

**Issue by RobertGardner** [NativeScript/nativescript-angular#1628]
**Environment**
 - CLI: 5.0.1
 - Cross-platform modules: 5.0.3
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0
 - NativeScript-Angular: 6.2.0
 - Angular: 6.1.0
 
**Describe the bug**
Modal Dialogs on iOS always display in fullscreen mode, even when fullscreen is set to false.
The fullscreen flag is properly honored on Android.

**To Reproduce**
Create a HelloWorld app using `tns create HelloWorld --ng`.
Add a button on the Home page to create a modal dialog. Add a modal dialog component.
On iOS, the dialog always displays full screen.

**Expected behavior**
iOS should behave the same as Android: when `fullscreen` is false the dialog should not take up the full screen.

**Sample project**
Here is the code for my sample modal dialog and the code that displays the dialog.

`modal.component.ts`:
```
import { Component } from "@angular/core";
import { ModalDialogParams } from "nativescript-angular/modal-dialog";

@Component({
  selector: "my-modal",
  moduleId: module.id,
  templateUrl: "./modal.component.html"
})
export class ModalComponent {
  words = ["alphabet", "brightness", "color"];

  constructor(private params: ModalDialogParams) {
  }

  close(response: string) {
    this.params.closeCallback(response);
  }
}
```

`modal.component.html`:
```
<GridLayout>
  <ListView [items]="words" class="list-group">
    <ng-template let-word="item">
      <StackLayout (tap)="close(word)" class="list-group-item">
        <Label [text]="word" class="label"></Label>
      </StackLayout>
    </ng-template>
  </ListView>
</GridLayout>
```

In `home.component.ts`:
```
    showModal() {
        let options: ModalDialogOptions = {
            context: {},
            fullscreen: false,
            viewContainerRef: this.vcRef
        };
        this.modal.showModal(ModalComponent, options).then(res => {
            console.log(res);
        })
    }
```

**Comment by NickIliev** [comment]
@RobertGardner currently the modals on iOS are fullscreen by default (which is the iOS recommendation and design guideline). We have a feature request to enhance the modals by proving more supported native options  ([here](https://github.com/NativeScript/NativeScript/issues/6387)). At this very moment, fullscreen is the only option on iPhone (some possible suggestions are discussed in numerous threads - see these  [search results](https://www.google.bg/search?q=nativescript+ios+modal&rlz=1C1CHBF_enBG781BG781&oq=nativescript+ios+modal+&aqs=chrome..69i57j69i60l3.8989j0j7&sourceid=chrome&ie=UTF-8))

Closing as related to the linked feature request.

**Comment by cerireyhan** [comment]
@NickIliev its still not possible for nativescript-angular, not implemented in ModalDialogService

**Comment by AatiqUrRehman** [comment]
Please post workaround for this issue in detail.
With latest ns ng project.
