### ISSUE TITLE
Nativescipt - Blurry effect for line chart using canvas

### ISSUE THREAD

**Issue by bijalmistry** [NativeScript/nativescript-angular#1631]
Hello Developer Team,

We have one application developed in Nativescript 4.2 with Angular v6. In our app we have to plot a line chart graph using canvas, but when we are trying to plot a graph then we have blurry effect.

Following is the demo code for your reference.
https://play.nativescript.org/?template=play-ng&id=zp7MGK&v=11

An urgent help in solving this issue will be greatly appreciated!

Thanks In Advance!
Bijal Mistry

**Comment by NickIliev** [comment]
Duplicate to [https://github.com/NativeScript/NativeScript/issues/6605](https://github.com/NativeScript/NativeScript/issues/6605)
