### ISSUE TITLE
NativeScript angular navigation not working

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1636]
@agnoam commented on [Tue Nov 27 2018](https://github.com/NativeScript/NativeScript/issues/6632)

Hi,
I have problem on navigation with my app.
I'm using the RouterExtensions class in the ngOnInit callback.

This line of code is the navigation, in the logs the router write the new route like it moved but in the UI not moved.

`this.ngZone.run(() => this.routerExtention.navigate(['upload'], additionalData))`

---

@NickIliev commented on [Wed Nov 28 2018](https://github.com/NativeScript/NativeScript/issues/6632#issuecomment-442333048)

@agnoam is there are a reason to use `NgZone` ? The Angular navigation should work as expected so please consider posting a Playground demo that reproduces the issue. You can also enable the route tracing with `{ enableTracing : true }` and investigate your local setup (the option should be passed in `forRoot` method of `NativeScriptRouterModule`).

C

**Comment by agnoam** [comment]
This is a playground with the error:

https://play.nativescript.org/?template=groceries-ng&tutorial=groceries-ng&autoStart=true&id=S2Yfj1&v=2

the error in app/pages/home/home.component.ts

**Comment by NickIliev** [comment]
@agnoam the code you are trying to execute is wrapped in the `launch` application event which is declared long after the application has already launched (in the ngOnInit of an internal page). This won't work as the native launch event is long gone and you can navigate within the page-router as it is not yet present during the launch.

So that said you should revise your logic and if you want to navigate to a specific page based on some additional data do not use the application launch event. On the other hand, you could raise some flags in the launch event which you can later reuse (e.g. track for the image intents in the launch event.. set a flag via application-settings and then use this flag to trigger navigation once you are in the Angular component.

Closing this one as the issue is not related to nativescript-angular bug
