### ISSUE TITLE
Weird tab view behavior when navigating

### ISSUE THREAD

**Issue by SkupeZZ** [NativeScript/nativescript-angular#1639]
I'm trying to navigate from a tab view to a component, and I noticed some weird behavior. I slowed down the animation so that you could have a better idea of what's happening.

When the navigation starts, all the content of the tab view disappears (except the tab view menu).  But when I go back, the tab's view content is there as expected. 

This is an example (gif)

![weird](https://user-images.githubusercontent.com/11478949/49300925-56f8ae80-f4bb-11e8-8002-86f5fdc20eed.gif)

Any idea why this is happening?

**Comment by manoldonev** [comment]
@SkupeZZ I was able to reproduce the problematic behavior with the core NativeScript framework (issue with Android fragments used in the tabview component) and moved the issue there. You can track the progress here: https://github.com/NativeScript/NativeScript/issues/6641
