### ISSUE TITLE
Error converting Angular to Nativescript

### ISSUE THREAD

**Issue by allurefx** [NativeScript/nativescript-angular#1640]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.0.2 version and is up to date.
✔ Component tns-core-modules has 5.0.5 version and is up to date.
✖ Component tns-android is not installed.
✔ Component tns-ios has 5.0.0 version and is up to date.
 
**Describe the bug**

Creating and previewing with tns (tns create and tns preview) works fine, but converting an existing Angular project is not working. Below is the error when trying to preview the default Angular app converted to Nativescript (see the **To Reproduce** section for the steps).

```
LOG from device Sekhar’s iPhone: 2018-11-30 10:33:22.907 nsplaydev[4800:1896425] ***** Fatal JavaScript exception - application has been terminated. *****
2018-11-30 10:33:22.907 nsplaydev[4800:1896425] Native stack trace:
1   0x103087f84 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2   0x1030c06bc -[TNSRuntime executeModule:referredBy:]
3   0x102cd0154 -[UIApplication(PlayLiveSync) swizzled_executeModule:]
4   0x10274f4f4
5   0x1e7c06bb4 <redacted>
2018-11-30 10:33:22.908 nsplaydev[4800:1896425] JavaScript stack trace:
2018-11-30 10:33:22.908 nsplaydev[4800:1896425] 1   resolve@[native code]
2   loadModule@[native code]
3   loadAndEvaluateModule@[native code]
2018-11-30 10:33:22.908 nsplaydev[4800:1896425] JavaScript error:
[native code]: JS ERROR Error: Could not find module './'. Computed path '/var/mobile/Containers/Data/Application/41C1E8E2-EC72-47F0-96A2-68C4A57AD22D/Documents/Playground/LiveSync/app'.
2018-11-30 10:33:22.909 nsplaydev[4800:1896425] PlayLiveSync: Uncaught Exception
2018-11-30 10:33:22.910 nsplaydev[4800:1896425] *** JavaScript call stack:
(

)
2018-11-30 10:33:22.910 nsplaydev[4800:1896425] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Could not find module './'. Computed path '/var/mobile/Containers/Data/Application/41C1E8E2-EC72-47F0-96A2-68C4A57AD22D/Documents/Playground/LiveSync/app'.
 at 
1   resolve@[native code]
2   loadModule@[native code]
3   loadAndEvaluateModule@[native code]
', reason: '(null)'
*** First throw call stack:
(0x1e81bbea0 0x1e738da40 0x1030882d4 0x1030c06bc 0x102cd0154 0x10274f4f4 0x1e7c06bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**To Reproduce**
ng new Angular
cd Angular
ng add @nativescript/schematics
tns preview

Open on iPhone.

**Expected behavior**
Should preview the app without errors, as it does with the app installed directly with tns create.
[Angular.tar.gz](https://github.com/NativeScript/nativescript-angular/files/2634615/Angular.tar.gz)

**Sample project**
Attached (with node_modules/ removed - please do an npm update).

**Additional context**
I'm doing this on Fedora, which I understand is not fully supported, but I'm getting similar errors on Windows. Also, like I said, the default app created with tns create works fine.

**Comment by NickIliev** [comment]
@allurefx the code-shared project can be built **only with Webpack**. Pass the `--bundle` flag to the `tns preview` and you should be good to go.

```
ng new test
cd test
ng add @nativescript/schematics
tns preview -- bundle
```

Test project demonstrating the above [here](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-angular/issue1640)

**Comment by allurefx** [comment]
Thanks a bunch for the quick response! I still needed to tweak the package.json (the default ng new seems to produce a package.json that doesn't work, as of today), but it's basically working. Hopefully, I can now extend this to my actual project.
