### ISSUE TITLE
Custom modal dialog - Programatically close

### ISSUE THREAD

**Issue by seveneye** [NativeScript/nativescript-angular#1649]
Is there a way to close custom modal dialog programatically? There are times I would navigate away to other page, but there are also times that I want to stay in the page and just close the dialog.

#663 provides some workarounds but its not working on the latest NS 5 + angular 7.

Is there a right way to close dialogs?

**Comment by tsonevn** [comment]
HI @seveneye,
For closing the ModalView, you can use `closeCallback` method. You can check out the NativeScript Angular example [here](https://docs.nativescript.org/angular/ui/modal-view-ng#sample-modal-view-module-example), where it is demonstrated, how to use the method.
