### ISSUE TITLE
"Name of the app" isn't responding. Do you want to close it ?

### ISSUE THREAD

**Issue by ngydat** [NativeScript/nativescript-angular#165]
So everytime you want to see the modifications of your app you run the command tns livesync/run android (obviously). But after a while, I get this message error :

![capture du 2016-04-11 10-43-52](https://cloud.githubusercontent.com/assets/11611999/14421549/9a8f5eae-ffd2-11e5-9613-9f5d3b52cbaf.png)

What's the cause of this ?

Thank you in advance

**Comment by hdeshev** [comment]
It's tough to say for sure just by looking at a screenshot. Does the console spew some errors? Do you have a public repo hosted somewhere that reproduces the problem?

**Comment by ngydat** [comment]
@hdeshev hello. No there aren't any errors in the console. As for a public repo, since I'm developing this mobile app for my internship, I'm not sure I can share the code.

**Comment by hdeshev** [comment]
@ngydat, I can't do much without reproducing the problem. Perhaps you could strip down the confidential bits of your project or reproduce the problem in a different app.
