### ISSUE TITLE
[help wanted] Update ListPicker 

### ISSUE THREAD

**Issue by VincentRenotte** [NativeScript/nativescript-angular#1652]
Hi there,

I know similar questions have been answered to a few times (particulary spent time on #967 and #465) but I wasn't able to adapt the solutions I found to my issue.

So I'm trying to update the content of a ListPicker (add and remove items) when tapping on the selected item. So far, I've been able to detect the tap and add the element in the array used to fill the ListPicker. However, the UI element does not refresh once done.

Here is a dummy project I started to simplify my issue :

```
<ActionBar title="My App" class="action-bar">
</ActionBar>
<StackLayout class="page">

    <ListPicker [items]="myPokemons | async" textField="name" valueField="id" selectedIndex="selectedIndex" (tap)="onTap($event)" class="p-15"></ListPicker>

</StackLayout>
```
And my component.ts file : 
```
import { Component, OnInit } from "@angular/core";
import { Observable as RxObservable } from "rxjs";

@Component({
    selector: "ns-items",
    moduleId: module.id,
    templateUrl: "./items.component.html",
})
export class ItemsComponent implements OnInit {
    public myPokemons: RxObservable<Array<string>>;
    public pokemons = [{name: "Bulbasaur", id: 1}, {name: "Squirtle", id: 2},  {name: "Charmander", id: 3}];

    constructor() { 
        this.myPokemons = RxObservable.create(subscriber => {
            subscriber.next(this.pokemons);
            console.log("Subscribe called!");
            return function () {
                console.log("Unsubscribe called!");
            };
        });
    }

    public onTap() {
        console.log("onTap()")
        this.pokemons.push({name: "Pikachu", id: 4});
        console.log(this.pokemons)
    }

    ngOnInit(): void {
    }
}
```

Thank you in advance for your help

**Comment by tsonevn** [comment]
Hi @VincentRenotte,
I have tested the described scenario on my side, and the ListPicker seems to be refreshed properly when a new item is added to it. I am attaching a sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2667962/Archive.zip)

**Comment by VincentRenotte** [comment]
Hi Nikolay, thanks for the time you've put into that !
After comparing my code and the sample project I was able to correct my issue, here the missing line :
```
public onTap() {
        console.log("onTap()")
        this.pokemons.push({name: "Pikachu", id: 4});
        console.log(this.pokemons)
        **this.subscr.next([...this.pokemons]);**
    }
```
This can be labelled as answered (if needed)
Best of luck to {N] team !
