### ISSUE TITLE
Keyboard Dismiss Mode - Interactive

### ISSUE THREAD

**Issue by dolanmiu** [NativeScript/nativescript-angular#1657]
I would like to make the keyboard dismiss mode to be interactive so that the user can slowly drag to hide the keyboard. Just like iMessage, WhatsApp, Facebook Messenger etc

I have found the solution using Swift 3, but not for NativeScript:

https://stackoverflow.com/questions/43469638/how-to-show-hide-keyboard-smoothly-on-drag-in-ios-swift-3

Can someone guide me on how to do this

**Comment by tsonevn** [comment]
Hi @dolanmiu,
The described scenario can be achieved while using the `nativescript-iqkeyboardmanager` plugin. You will also need setting up the ScrollView's `keyboardDismissMode` property to `UIScrollViewKeyboardDismissModeInteractive`. Check out the attached sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2667831/Archive.zip)
