### ISSUE TITLE
Page router outlet memory leak

### ISSUE THREAD

**Issue by KkevinLi** [NativeScript/nativescript-angular#1658]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
```✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 5.0.1 and the latest available version is 5.0.3.
✔ Component tns-core-modules has 5.2.0-2018-11-29-161511-02 version and is up to date.
⚠ Update available for component tns-android. Your current version is 5.0.0-rc-2018-10-26-162351-01 and the latest available version is 5.0.0.
✔ Component tns-ios has 5.0.0 version and is up to date.
```
 
**Describe the bug**

I am noticing that forward navigations never release the memory and eventually I will run out of memory and my app will crash. This is happening even with clearHistory = true. Calling gc.__collect() did not free up the memory either.

In this sample project the pages are pretty empty so the increase takes a bit of time, but in production with more content on a page the memory increase is very noticeable. 

(Starts at around 80mb. The sharp increase in the beginning is navigating often between "Go To Welcome and Logout". As we navigate around the simple app you can see the memory allocation keeps increasing.)

<img width="872" alt="screen shot 2018-12-10 at 9 55 42 am" src="https://user-images.githubusercontent.com/14020249/49740245-d0ce2c00-fc61-11e8-9443-aede8b8d4912.png">

**To Reproduce**

Using that sample project which explains nested routers, if you just hit "Go to welcome page" and then "logout" a few times you can see using instruments that the memory allocation keeps increasing. 

**Expected behavior**

Navigating between pages with clearHistory should be restoring us to the initial memory usage.

**Sample project**

https://github.com/ADjenkov/login-tabs-ng

**Comment by tsonevn** [comment]
Hi @KkevinLi,
I have tested the described scenario with the login-tabs-ng project, however, was unable to recreate a crash. I have noticed that in the project, that you have mentioned, are used some old dependencies. I would suggest updating then. Check out the attached sample `package.json`.
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.testapp",
    "tns-ios": {
      "version": "5.0.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "nativescript-angular": "~7.0.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.1.0",
    "tns-core-modules": "^5.0.5",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.12.0",
    "typescript": "~2.7.2",
    "webpack": "~4.6.0",
    "webpack-cli": "~2.1.3",
    "webpack-bundle-analyzer": "~2.13.0",
    "webpack-sources": "~1.1.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "~4.5.1",
    "raw-loader": "~0.5.1",
    "css-loader": "~0.28.11",
    "nativescript-worker-loader": "~0.9.0",
    "extract-text-webpack-plugin": "~3.0.2",
    "uglifyjs-webpack-plugin": "~1.2.5",
    "@angular/compiler-cli": "~7.0.0",
    "@ngtools/webpack": "~6.0.3",
    "@angular-devkit/core": "~0.6.3",
    "resolve-url-loader": "~2.3.0"
  }
}
```
Keep in mind that the garbage collection will not be triggered immediately when you make navigation with a clear history. The GC will be called when the OS required it. You can check the post here, where it is described the [memory management](https://panayotcankov.github.io/nativescript-3.2.0-memory-management/) in NativeScript. You can check the attached image from `instruments`, generated while testing the case. You can notice that the memory is released at some intervals. The result is based on 630 navigations.

![screen shot 2018-12-12 at 2 17 32 pm](https://user-images.githubusercontent.com/17448734/49869315-c1451380-fe18-11e8-92a1-c840b47c94dd.png)

It will help if you can send us your app, which will allow us to investigate further the crash, you are facing and what exactly is causing it.

**Comment by KkevinLi** [comment]
I will work on making a minimal app to reproduce the issue I am facing. When using instruments I do see the memory allocation similar to what you have where the memory would be freed, but the total memory the app is using does not return to the initial app usage or even close to it. After the GC, the memory would drop slightly (roughly 50mb on the iPhone X), but I am able to get the app up to 1GB as I continue navigating.

<img width="850" alt="screen shot 2018-12-13 at 9 12 34 am" src="https://user-images.githubusercontent.com/14020249/49944143-c0af8a00-feb7-11e8-80cb-222237666f3b.png">

**Comment by KkevinLi** [comment]
Closing for now. Turns out my issue was related to the issue @NickIliev mentioned and 5.1 fixed it.
