### ISSUE TITLE
Quick question regarding release 7.1

### ISSUE THREAD

**Issue by larssn** [NativeScript/nativescript-angular#1659]
So this release has been out for about 4 days here on Github, but it's not been added to the NPM repo yet. Is this an oversight?

**Comment by NickIliev** [comment]
Closing ad duplicate to [https://github.com/NativeScript/NativeScript/issues/6697](https://github.com/NativeScript/NativeScript/issues/6697) - the information about RC is also valid for `nativescript-angular`
