### ISSUE TITLE
Best way to keep user logged in

### ISSUE THREAD

**Issue by ngydat** [NativeScript/nativescript-angular#166]
Hello,

Like Facebook I'd like the user to be logged in indefinitely. I might add that I use Oauth2 to log the user.
So how can I do that ?

Thank you

**Comment by hdeshev** [comment]
Hi @ngydat 

We are trying to keep GitHub issues focused on features, bugs, and other development topics. Please use [StackOverflow](http://stackoverflow.com/questions/tagged/nativescript) for general questions.
