### ISSUE TITLE
[7.1.0] iOS crash when using Angular animations

### ISSUE THREAD

**Issue by larssn** [NativeScript/nativescript-angular#1662]
**Environment**
 - CLI: 5.1.0
 - Cross-platform modules:
 - Android Runtime: 5.1.0
 - iOS Runtime: 5.1.0
 - Plugin(s):
```
"nativescript-angular": "^7.1.0",
    "nativescript-feedback": "^1.3.3",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-orientation": "^2.2.1",
    "nativescript-plugin-firebase": "file:../nativescript-plugin-firebase/publish/package/nativescript-plugin-firebase-7.4.3.tgz",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~5.0.1",
    "nativescript-webview-interface": "^1.4.2",
```
 - NativeScript-Angular: 7.1.0
 - Angular: 7.1.3
 
**Describe the bug**
We're seeing the following error on iOS, when using Angular's built in animation support.

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
nw_endpoint_flow_protocol_connected [C6.1 IPv4#dd7d11d1:443 in_progress channel-flow (satisfied)] Transport protocol connected
TIC TLS Event [6:0x28254e100]: 1, Pending(0)
TIC TLS Event [6:0x28254e100]: 2, Pending(0)
1   0x102637f84 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2   0x102664fdc NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10313d578 ffi_closure_SYSV_inner
4   0x1031401b4 .Ldo_closure
5   0x1d695b5fc __NSFireTimer
6   0x1d5e39bf0 <redacted>
7   0x1d5e39920 <redacted>
8   0x1d5e39154 <redacted>
9   0x1d5e34030 <redacted>
10  0x1d5e335b8 CFRunLoopRunSpecific
11  0x1d80a7584 GSEventRunModal
12  0x2029f0bc8 UIApplicationMain
13  0x103140044 ffi_call_SYSV
14  0x10313cc8c ffi_call_int
TIC TLS Event [6:0x28254e100]: 2, Pending(0)
TIC TLS Event [6:0x28254e100]: 11, Pending(0)
TIC TLS Event [6:0x28254e100]: 14, Pending(0)
15  0x10313c750 ffi_call
16  0x102605740 NativeScript::FFICall::call(JSC::ExecState*)
17  0x10313b80c llint_entry
18  0x10313abd0 llint_entry
19  0x10313abd0 llint_entry
20  0x10313abd0 llint_entry
21  0x10313abd0 llint_entry
22  0x10313abd0 llint_entry
23  0x10313abd0 llint_entry
24  0x10313abd0 llint_entry
25  0x10313abd0 llint_entry
26  0x10313abd0 llint_entry
27  0x10313abd0 llint_entry
28  0x103133870 vmEntryToJavaScript
29  0x102f298d8 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*)
30  0x102ef5940 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&)
31  0x1030c8c6c JSC::call(JSC::ExecState*, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&)
System Trust Evaluation yielded status(0)
TIC TLS Trust Result [6:0x28254e100]: 0
JavaScript stack trace:
1   _getNativeAnimationArguments@file:///app/vendor.js:104325:43
2   @file:///app/vendor.js:104291:62
3   play@file:///app/vendor.js:104260:35
4   animate@file:///app/vendor.js:104810:27
5   @file:///app/vendor.js:104783:58
6   runTask@file:///app/vendor.js:66908:57
7   invokeTask@file:///app/vendor.js:67216:41
8   timer@file:///app/vendor.js:68281:34
9   invoke@file:///app/vendor.js:102880:53
10  runGuarded@file:///app/vendor.js:66871:53
11  tick@file:///app/vendor.js:102845:26
12  UIApplicationMain@[native code]
13  start@file:///app/vendor.js:93502:26
14  run@file:///app/vendor.js:93530:10
15  bootstrapNativeScriptApp@file:///app/vendor.js:63627:26
16  bootstrapApp@file:///app/vendor.js:63545:38
17  bootstrapModuleFactory@file:///app/vendor.js:63516:26
18  ./main.ts@file:///app/bundle.js:15965:115
19  __webpack_require__@file:///app/bundle.js:76:34
20  checkDeferredModules@file:///app/bundle.js:45:42
21  @file:///app/bundle.js:166:38
22  anonymous@file:///app/bundle.js:167:12
23  evaluate@[native <\M-b\M^@\M-&>
JavaScript error:
file:///app/vendor.js:104325:43: JS ERROR TypeError: undefined is not an object (evaluating 'nativeView.layer')
```

**To Reproduce**
Create 2 sibling views like this:
```
<GridLayout @routerInAnimation>
   <Label text="Hello World"></Label>
</GridLayout>
```
The `ts` files have the `animations` line in their `@Component()` declaration:
```
@Component({
  moduleId: module.id,
  templateUrl: './hello.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  animations: [routerInAnimation],
})
```

The `routerInAnimation` looks like this:
```
export const routerInAnimation =
  trigger('routerInAnimation', [
    // route 'enter' transition
    transition(':enter', [

      // styles at start of transition
      style({ opacity: 0 }),

      // animation and styles at end of transition
      animate('1s ease-in', style({ opacity: 1 })),
    ]),
  ]);
```

Then route between the 2 views, to trigger the animation.

Note: If you comment out the `animate` line, it stops crashing, so it seems related.

**Sample project**
If you can't reproduce it, we'll supply one.

**Additional context**

**Comment by tsonevn** [comment]
Hi @larssn,
I have tested the described scenario with the animations, however, was unable to recreate the issue. For your convenience, I am attaching a sample project. Please review it and make the needed changes, which will allow us to recreate the problem.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2675844/Archive.zip)

**Comment by larssn** [comment]
We'll look at it immediately

**Comment by larssn** [comment]
So we tried to reproduce it in the sample, but weren't able to.

We then tried slowly removing code from our app, until the problem disappeared.
The result was inconclusive, and our working theory is that the problem is CPU related (meaning a race condition). We came to this conclusion based on removing certain pieces of code that were entirely isolated from the animation logic, that somehow caused the animation to work as intended. The more processing we added to that particular component, the more likely the problem was to occur. So my guess is that there is some async logic somewhere, that isn't allowed to complete, but sometimes does complete, hence the race condition.

So we've had little choice but to scrap Angular animations for now.

Ps. As I mentioned, when our component was stripped bare bones (no data being read etc, basically only the animation), the following tiny code block would cause the problem to reappear:
```
ngOnInit() {
  for (let i = 0; i < 10; i++) {
    setTimeout(() => { this.changeDetectorRef.markForCheck(); }, i);
  }
}
```
Not much to go by :(

I'm available if you have any questions.

**Comment by tsonevn** [comment]
Hi @larssn,
Thank you for your further research on the issue, however, without any stable steps to recreate the problem it is hard to investigate further the case. Can you please send us the project as a private message via our [community slack](https://nativescriptcommunity.slack.com/)? My nickname is `nikts`. With its help, we will be able to check what exactly is causing this animation issue.

**Comment by larssn** [comment]
Sure, when I have time, I'll send a stripped down version of the app that only contains the problem.

Thank you
