### ISSUE TITLE
LiveSync does not work on iOS

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#167]
I think this is a known issue, but I thought I’d log it here so it could be tracked. In ng2 {N} apps LiveSync does not work for on iOS—with or without the `--watch` flag.

The command executes successfully, but the app itself never updates. `tns livesync android --watch` works great.

Thanks.

**Comment by rosen-vladimirov** [comment]
@tjvantoll Can you give me a sample project reproducing the issue.
I've tried (with latest CLI from release branch of course) to reproduce the issue, but it works fine on my side. My steps are:
* `$ tns create myAngularApp --ng`
* `$ cd myAngularApp`
* `$ tns run ios`
* `$ tns livesync ios --watch`

@burkeholland in case you have any idea how to reproduce it, can you share it.

**Comment by tjvantoll** [comment]
@rosen-vladimirov Using the released version of the CLI I’m unable to livesync any changes in Groceries. Here’s what I’m doing:

* `git clone https://github.com/NativeScript/sample-Groceries.git`
* `cd sample-Groceries`
* `git checkout angular-end`
* `tns install`
* `tns run ios --emulator`
* `tns livesync ios --emulator --watch`
* Change any file. The livesync watcher will detect the change, but the app won’t update.

This might something specific to the configuration in Groceries, because when I try a new app I can only recreate the problem with CSS changes (TypeScript changes livesync as expected). Here are the steps:

* `tns create myAngularApp --template tns-template-hello-world-ng`
* `cd myAngularApp`
* `tns run ios --emulator`
* `tns livesync ios --emulator --watch`
* Change anything in `app.css`. The livesync watcher will again detect the change, but the app again won’t update.

I’ll give the release branch a shot to see if I have better luck with it.

**Comment by tjvantoll** [comment]
Ok good news and bad news.

**Good news**: I installed the {N} CLI from the release branch and I’m no longer having the same issue with Groceries. TypeScript changes livesync as expected 🎉

**Bad news**: I am still not seeing changes I make to CSS files, even in the release branch. I can recreate this in Groceries and in new apps using the steps above.

**Comment by tjvantoll** [comment]
So it appears that, with the updated CLI, the problem is limited to CSS changes on iOS.

**Comment by hdeshev** [comment]
This issue was moved to NativeScript/nativescript-cli#1696
