### ISSUE TITLE
{N} + Ng - class added in TS w/ className not affecting styling

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1670]
@jamessouth commented on [Mon Dec 24 2018](https://github.com/NativeScript/NativeScript/issues/6737)

**Describe the bug**
adding a CSS class with className updates the list of classes on the element, but the styles are not changing 

**To Reproduce**
programmatically create an element in TS and apply a class with element.className = 'myClass'

**Expected behavior**
per the docs [here](https://docs.nativescript.org/angular/ui/styling#class-selector) you should be able to simply create an element and add a class to it with className

**Sample project**
[playground demo](https://play.nativescript.org/?template=play-ng&id=mmmJ5Q&v=13) 
the newly added class is logged to the console, but the styling of the text doesn't change

**Additional context**
i'm using the playground/preview apps on my android phone

**Comment by tsonevn** [comment]
Hi @jamessouth,
In your case, you need to specify the CSS classes that you need to use in the app.css file. This will ensure that CSS class will be loaded when you are setting it to the dynamically created component.

> Note: Creating dynamically component in NativeScript Angular project is not recommended. If you need to show components dynamically, you can use the ngIf directive to hide/show the component.

**Comment by jamessouth** [comment]
ok thanks @tsonevn I sent a PR https://github.com/NativeScript/docs/pull/1487#issue-240825216
