### ISSUE TITLE
"Sync operation is taking too long."

### ISSUE THREAD

**Issue by mchallenger88** [NativeScript/nativescript-angular#1674]
**Environment**
Nativescript has 5.1.0 version and is up to date.
tns-core-modules version is 5.1.0
tns-android has 5.1.0 version and is up to date.
angular 7.1.4

 
**Describe the bug**
Whenever a change is made to a component that modifies its imports or a new component is added, livesync stalls out and webpack stops. Communication with both physical devices and emulators are lost. Livesync also sometimes stalls when minor component changes are made.

**To Reproduce**
Not sure

**Expected behavior**
Livesync should work as normal to refresh the project.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-cli #4248](https://github.com/NativeScript/nativescript-cli/issues/4248) via [**ZenHub**](https://www.zenhub.com/)
