### ISSUE TITLE
Textfield letters only

### ISSUE THREAD

**Issue by seveneye** [NativeScript/nativescript-angular#1675]
Hi, is there a way to set the textfield to only accept letters. Other characters should not be displayed on the textfield. How can I accomplish this? Thanks!

**Comment by tsonevn** [comment]
Hi @seveneye,
Check out the [nativescript-masked-text-field](https://www.npmjs.com/package/nativescript-masked-text-field). The plugin allows specifying a mask for the TextField's input.
For further questions, I would suggest using our StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).
