### ISSUE TITLE
Can't npm install a branch

### ISSUE THREAD

**Issue by rynop** [NativeScript/nativescript-angular#1676]
**Is your feature request related to a problem? Please describe.**
Yes. I can only `npm i` versions that have been released to npmjs.com.  For example, [7.1.1](https://github.com/NativeScript/nativescript-angular/pull/1668) has a github release, but has not been uploaded to npmjs.com

Because the module is in the `nativescript-angular` subdir, the standarized way to install from a branch does not work. IE: 
```
npm i NativeScript/nativescript-angular@master
```

**Describe the solution you'd like**
Move `package.json` to root.

**Describe alternatives you've considered**
move the nativescript-angular npm module to its own repo.

**Additional context**
AFAIK npm and yarn [do not support](https://github.com/npm/npm/issues/2974) installing from git when `package.json` is in a subdir.

**Comment by tsonevn** [comment]
Hi @rynop,
Thank you for the provided feedback.
I would suggest checking out the described workflow in the repository - [developer-workflow](https://github.com/NativeScript/nativescript-angular/blob/master/DevelopmentWorkflow.md#developer-workflow). As it is mentioned the repository contains several test apps that are used for testing the nativescript -angular and provides a straightforward workflow for the devs.

If you need to use the upcoming version of this page you can use `@next` npm version of the nativescript-angular, which corresponds to the master branch. If you still need to use directly the master branch, you can follow the below-described steps.
1. `git clone https://github.com/NativeScript/nativescript-angular`
2. cd `nativescript-angular/nativescript-angular`
3. `npm i`
4. `tsc`
5. [link](https://docs.npmjs.com/cli/link.html) the package in your project.

**Comment by rynop** [comment]
Thanks @tsonevn.  I tried `@next` but it did not correspond to master (was still 7.1.0-x).

It's unfortunate that the file structure of the repo is preventing a slew of easy-to-use npm/yarn function on install/update (ex: tag,version,url,tar).

Any idea when [7.1.1](https://github.com/NativeScript/nativescript-angular/pull/1668) is going to be released to npmjs.com?  I think my use case/concern goes away with just some education on my part.
  
When a [patch](https://github.com/NativeScript/nativescript-angular/releases/tag/7.1.1) version is released to github, what is the timeline for it to be released to npmjs.org? 7.1.1 contains a fix for a regression bug that broke navigation functionality.
