### ISSUE TITLE
Thousand images on screen

### ISSUE THREAD

**Issue by dolanmiu** [NativeScript/nativescript-angular#1677]
What is the performance like with nativescript Angular with 1000+ images on the screen at once? 

Is nativescript the right choice of technology for this task?

**Comment by tsonevn** [comment]
Hi @dolanmiu,
In your case, if you need to display a significant number of images, I would suggest using a ListView component or RadListView provided by [nativescript-ui-listview](https://www.npmjs.com/package/nativescript-ui-listview). Both components allow lazy data loading and support data virtualisation. Those features will keep the good app performance and will prevent the app from memory issues. For more info check out the article [here](https://www.nativescript.org/blog/discover-the-list-component-in-nativescript).
