### ISSUE TITLE
Not All Kabab Case Is Recognized

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-angular#168]
Some elements are not recognized when kabab case.

**Environment**

OSX 10.11.1
NativeScript 1.7.0

**Steps To Reproduce**

Create a component with a `<stack-layout>` in kabab case. The StackLayout will be ignored. Use `<StackLayout>` and the app works as expected.

**Comment by hdeshev** [comment]
Duplicate of #29
