### ISSUE TITLE
Best Pratice in Shared Projects for specifics behaviors

### ISSUE THREAD

**Issue by betosalvador** [NativeScript/nativescript-angular#1683]
Hello, I thank you guys so much for this work!!! 

Very, very good!
	
I would like to do an ask, using like reference this code:
**https://github.com/sebawita/tour-of-heroes/blob/finished/src/app/hero-detail/hero-detail.component.ts**

What would be the best pratice if in the **HeroDetailComponent**, on **save()** method, I want to do a differente behavior for mobile and web platform? 

Example: After save the Hero, in web I want to run a "**this.goBack()**" and in mobile I want to run a "**alert('Saved')**"?
		
Again, thanks for this awsome framework!

**Comment by NickIliev** [comment]
Hello @betosalvador and thank you for your interest in NativeScript. Please notice that this repository is for logging bugs, issues and feature requests related to the CLI. FOr how-to related concepts, please use the community channels (SO or NativeScript community slack)

Closing as how-to related question

**Comment by pragmaticbox** [comment]
Sorry.. i Will post on Slack
  Thanks
