### ISSUE TITLE
Creating a Library

### ISSUE THREAD

**Issue by Lightk3ira** [NativeScript/nativescript-angular#1684]
Hello I am writing an Angular + Nativescript code sharing project and have realized it would be beneficial to create a Library. I have tried using schematics but I am unable to create a proper library. Any component that get's created within the library only has angular files not typescript.

Steps To reproduce:
1. Create a Workspace:  `ng new <project-name> --create-application false`
2.  Create a Library:  `ng generate library library-name`
3. Create a module within the library: `ng generate module navigation-module --project=Library`
4. Create a component within the library: `ng generate component` ran within the module directory

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-schematics #179](https://github.com/NativeScript/nativescript-schematics/issues/179) via [**ZenHub**](https://www.zenhub.com/)
