### ISSUE TITLE
Publish 7.1.1 to npm?

### ISSUE THREAD

**Issue by drewcovi** [NativeScript/nativescript-angular#1685]
Is there a cooling off period between github releases and npm publishes?

Just curious, not sure how releases are handled in this repo.

**Comment by tsonevn** [comment]
Hi @drewcovi,
The nativescript-angular 7.1.1 will soon be available in npm. Regarding your question, there is no cooling off period between the minor releases publishing(there might be some delay on GitHub and npm releases if more time for testing the package is needed). About the major releases, we are following the [Roadmap](https://www.nativescript.org/roadmap-and-releases#releases) and the time that it is set for each period.

Hope this helps.
