### ISSUE TITLE
nativescript javascript todo app

### ISSUE THREAD

**Issue by Gurucharan** [NativeScript/nativescript-angular#1690]
Hello, I was creating a simple todo app and got the following error. please tell me a solution for the below error.

System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bytes.noter/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "data/observable-arrray", relative to: app/tns_modules/

System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)

System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)

System.err: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)

System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)

System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)

System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6494)

System.err: 	at java.lang.reflect.Method.invoke(Native Method)

System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)

System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

System.err: Caused by: com.tns.NativeScriptException: Failed to find module: "data/observable-arrray", relative to: app/tns_modules/
System.err: 	at com.tns.Module.resolvePathHelper(Module.java:146)
System.err: 	at com.tns.Module.resolvePath(Module.java:55)
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)

System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:987)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)

System.err: 	at android.app.Activity.performCreate(Activity.java:7009)
System.err: 	at android.app.Activity.performCreate(Activity.java:7000)

System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)

System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
System.err: 	... 9 more

# NativeScript Debugger started #

device: emulator-5554 debug port: 40001

To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40001

Successfully synced application com.bytes.noter on device emulator-5554.

01-08 12:21:03.562  8907  8907 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodNative(Native Method)

01-08 12:21:03.562  8907  8907 E AndroidRuntime: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1120)
01-08 12:21:03.562  8907  8907 E AndroidRuntime: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1000)
01-08 12:21:03.562  8907  8907 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:987)

01-08 12:21:03.562  8907  8907 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)

01-08 12:21:03.562  8907  8907 E AndroidRuntime: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)

√ Getting NativeScript components versions information...
√ Component nativescript has 5.1.0 version and is up to date.
√ Component tns-core-modules has 5.1.1 version and is up to date.
√ Component tns-android has 5.1.0 version and is up to date.
√ Component tns-ios has 5.1.0 version and is up to date.

**Comment by NickIliev** [comment]
Try using the full path in the imports.

e.g. **instead** of
```TypeScript
import { ObservableArray} from "data/observable-array";
```

use
```TypeScript
import { ObservableArray} from "tns-core-modules/data/observable-array";
```

CLosing the issue as there is not enough information to actually reproduce the issue on our side (Pleasae consider posting the information requested in the "report a bug" template when creating new issue).
