### ISSUE TITLE
Content falls behind StatusBar on iOS

### ISSUE THREAD

**Issue by DanielRitvas** [NativeScript/nativescript-angular#1694]
In newly created NativeScript + Angular app I have an issue on iOS that content of root StackLayout spans behind the StatusBar. Is there any property that would adjust app's content to some sort of frame with StatusBar excluded? So that app content starts after StatusBar.

**Comment by tsonevn** [comment]
Hi @DanielRitvas,
You can set [iosOverflowSafeAreaEnabled](https://docs.nativescript.org/api-reference/modules/_ui_core_view_#iosoverflowsafeareaenabledproperty) property to `false` on the root component. Example:
```
<StackLayout iosOverflowSafeAreaEnabled="false">

......
</StackLayout>
```

**Comment by DanielRitvas** [comment]
@tsonevn great, thanks! But then I have to manually adjust StatusBar colours for views with different backgrounds?

**Comment by tsonevn** [comment]
While setting up `iosOverflowSafeAreaEnabled ` to `false `, you may need to change the StatusBar color for each page.

**Comment by DanielRitvas** [comment]
@tsonevn  great, thanks! Also is there analogical preference for android?
