### ISSUE TITLE
editable not working in template

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/nativescript-angular#170]
```
import {Component, ViewChild, ElementRef} from "angular2/core";
import {Color}  from "color";
import {SearchBar} from "ui/search-bar";
import {TextField} from "ui/text-field";
import {Switch} from "ui/switch";
import {Slider} from "ui/slider";

@Component({
    selector: "my-app",
    template: `
<StackLayout orientation="vertical">
<TextField #text  style="color:red;" editable="false" keyboardType="email" hint="your name" secure="false"></TextField>

</StackLayout>
`,
    styleUrls: ["app.css"]
})
export class AppComponent {

    // value: Number;
    // @ViewChild('searchBar') ngSearchBar: ElementRef;

    constructor() {
//    returnKeyType="search"
    }

    ngAfterViewInit() {

    }



}
```
template not working, but working with ts `this.nsText.editable = false;`

#### Add more info: after a few test, I found if we set editable and keyboardType at the same time. the editable props will not work. 

by the way, is there a way to change the color when the textfiled focused?(the line's color)

for tabView we can set `selectedColor ` for the line. how to do that for textfield?

**Comment by vakrilov** [comment]
Hi @dreambo8563 
I tried it and it seems to be working as expected (both on IOS and Android). Can you please elaborate a bit more or even better - post the entire code that reproduces the behavior.

**Comment by dreambo8563** [comment]
@vakrilov I have update the issue description. please have a look. if you need more info, pls let me know

**Comment by vakrilov** [comment]
Looks like it is a bug.
I have moved the issue to the NativeScript repo: NativeScript/NativeScript/issues/1966. You can track its progress there.
