### ISSUE TITLE
Can not use custom component inside ActionBar

### ISSUE THREAD

**Issue by aleksander351** [NativeScript/nativescript-angular#1702]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules: 5.0.5
 - Android Runtime: -
 - iOS Runtime: -
 - Plugin(s):
 - NativeScript-Angular: 7.0.0
 - Angular: 7.0.0
 
**Describe the bug**

This is my custom upload component template:
`<Button android.position="popup" class="new-doc" text="Novo +" (tap)="uploadFile()"></Button>`
    

I try to insert it into my ActionBar:
 `

    <ActionBar [title]="title">
          <NavigationButton class="navigation-button" ios:visibility="collapsed" icon="res://menu" 
             (tap)="toggle()"></NavigationButton>                    
          <ActionItem icon="res://menu" android:visibility="collapsed" (tap)="toggle()" ios.position="left">
          </ActionItem>
          <app-upload [folder]="currentFolder" (updateView)="updateList($event)"></app-upload>
    </ActionBar>
`

As you can see, the upload component is a Button and is insertet without an ActionItem wrapper.

The problem is:
When I insert it like that, the Button displays fine, but the ActionBar title is not visible anymore.
And when I wrap it inside an ActionItem, the title is visible again, but the Button changes to a drop-down menu, with 3 vertical dots, and the button in the menu is not accessible/visible anymore.

I can not use this for my component:
`<ActionItem android.position="popup" class="new-doc" text="Novo +" (tap)="uploadFile()"></ActionItem>`

As a component, since it produces an error:
System.err: Calling js method onCreateView failed
System.err: TypeError: cv._getNativeViewsCount is not a function

**Comment by aleksander351** [comment]
Possible duplicate of [https://github.com/NativeScript/NativeScript/issues/4279](url)

**Comment by tsonevn** [comment]
Hi @aleksander351,
Try to set up the custom component inside a StackLayout. For example:
```
<StackLayout>
        <ns-test></ns-test>
</StackLayout>
```
You can also check the attached sample project.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2802661/Archive.zip)
