### ISSUE TITLE
nativescript with angular installing any plugin app is not running getting some error

### ISSUE THREAD

**Issue by dkandari** [NativeScript/nativescript-angular#1708]
Error: com.tns.NativeScriptException: Failed to find module: "nativescript-youtu
beplayer/angular", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:553)
    com.tns.Runtime.run(Runtime.java:545)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:102
5)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5505)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1591)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:163)
    android.app.ActivityThread.main(ActivityThread.java:6228)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:9
04)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
File: "<unknown>, line: 1, column: 265

StackTrace:
        Frame: function:'require', file:'', line: 1, column: 266
        Frame: function:'', file:'file:///data/data/org.nativescript.preview/fil
es/app/app/app.module.js', line: 6, column: 17
        Frame: function:'require', file:'', line: 1, column: 266
        Frame: function:'', file:'file:///data/data/org.nativescript.preview/fil
es/app/main.js', line: 5, column: 20
        Frame: function:'require', file:'', line: 1, column: 266

**Comment by tsonevn** [comment]
Hi @dkandari,
I checked your case, however, was unable to recreate a similar problem on my side. I tested the `nativescript-youtubeplayer` plugin in a demo project, and it was built correctly. You can find the demo in the below-attached file.
Can you provide more info about your environment(CLI, tns-core-modules, nativescript-angular, tns-android, tns-ios)? Also, it will help if you can send us a sample project, that can be used for debugging.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2811217/Archive.zip)

**Comment by dkandari** [comment]
sorry for delay replay. 
my info is
Angular CLI 6.0.5
Node 8.12.0
tns-core-modules : 5.1.1
tns-android : 27;

and i also check Archive.zip folder of you give me but problem is same.

**Comment by tsonevn** [comment]
Hi @dkandari,
Can you provide some more info about the exact steps, that you have used while building the project?

**Comment by dkandari** [comment]
thanks for replay.
yes. i am follow all steps installing and building nativscript app. then scan payground and preview app.
sample page is running ok. but when i install any native plugin and problem is coming. 

i already setup ionic and react native environment. and those area working fine.

**Comment by NickIliev** [comment]
@dkandari the Playground is not supporting all plugins (only the ones that are already part of the Preview app) so that behavior is expected. The Playground team is working on this functionality (to be able to add third-party plugins e.g. nativescript-youtube player) but this option is not available so far.
