### ISSUE TITLE
keyboard overlay error with action bar

### ISSUE THREAD

**Issue by NeriCodec** [NativeScript/nativescript-angular#1711]
I use in AndroidManifest.xml:

android:windowSoftInputMode="adjustResize"

and then the actionBar goes down

Screenshot:

https://ibb.co/K7GvvkS

**Comment by tsonevn** [comment]
Hi @NeriCodec,
Check out [this](https://github.com/telerik/nativescript-ui-feedback/issues/730#issuecomment-408112729) thread, where a similar case has been discussed.
