### ISSUE TITLE
How to know scrollview stop scrolling?

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [NativeScript/nativescript-angular#1732]
Iam working android and ios application using nativescript angular.I want to know how to know if the scrollview stopped scrolling.Any event is there?

**Comment by tsonevn** [comment]
Hi @ArigarasuthanRepo,
The ScrollView does not have a similar option, which allows detecting when the scroll stopped. Currently, you can catch only when the user is scrolling while using the [ scroll event](https://docs.nativescript.org/api-reference/classes/_ui_scroll_view_.scrollview#scrollevent).

**Comment by ArigarasuthanRepo** [comment]
Ok then how to detect user is not scrolling?

**Comment by tsonevn** [comment]
Hi @ArigarasuthanRepo,
You can detect the scrolling while using the [scrollEvent ](https://docs.nativescript.org/angular/ui/ng-ui-widgets/scroll-view#scroll-event)

**Comment by ashhadaimviz** [comment]
Hey I am stuck on the same problem I want to know when user stopped scrolling but unfortunately nothing is there to help I tried it out using scroll event but still it is not working 
I am trying to combine scroll event with scroll to Index event If you have solved this issue I need your help

**Comment by mreall** [comment]
I work around this issue by setting a variable when the scrolling event fires, then setting a timeout to reset the variable to false.  In NS-vue it looks like the following:

```
onScroll(args) {
  if (this.scrolling) {
    clearTimeout(this.scrolling);
  }
  this.scrolling = setTimeout(() => (this.scrolling = false), 50);
}
```

**Comment by mauriruizd** [comment]
In case someone is with this issue and has not found a solution yet, you can detect the `touch` event, which has an `action` property with the value `up` when the user removes his/her finger from the screen.

Hence you can do something like this in your HTML
```html
<ScrollView #scrollView(touch)="onTouch($event)"></ScrollView>
```

And in your TS check the action property. I also set a timeout in case the ScrollView is still scrolling.
```js
import { TouchGestureEventData } from "tns-core-modules/ui/gestures";
import { ScrollView } from "tns-core-modules/ui/scroll-view";
...
onTouch(args: TouchGestureEventData) {
    if (args.action == 'up') {
        setTimeout(() => {
            // finger off the screen
        }, 50);
    }
}
```
