### ISSUE TITLE
_routerExtensions.back() causes crash after closing modal

### ISSUE THREAD

**Issue by jeffswitzer** [NativeScript/nativescript-angular#1735]
**Environment**
have only tried on android
 
**Describe the bug**
After closing a modal, back navigation via routerExtension doesn't work resulting in a runtime error.

**To Reproduce**
Open [this nativescript playground](https://play.nativescript.org/?template=play-ng&id=AT8Nvd&v=42)
1. using router, navigate from component1 to component2
2. open a modal inside component2
3. close the modal
4. click back to attempt to navigate back from component2 to component1
5. runtime error says: `ERROR TypeError: Cannot read property 'isPageNavigationBack' of undefined`

**Expected behavior**
The back navigation should take you back to component 1

**Additional context**
This may be related to #1350

**Comment by tsonevn** [comment]
Hi @jeffswitzer,
I was able to recreate the issue while using your demo app and will mark this problem as a bug. It seems that there is an issue with the `router-outlet`. As a workaround, I would suggest using `page-router-outlet`. Check out the example [here](https://play.nativescript.org/?template=play-ng&id=AT8Nvd&v=43).
