### ISSUE TITLE
HostListener for keyboard events returns error

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1747]
@danu165 commented on [Thu Feb 21 2019](https://github.com/NativeScript/NativeScript/issues/6948)

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.1.2
 - Cross-platform modules: 4.1.1
 - Android Runtime: 4.1.3
 - iOS Runtime: 4.1.1
 - Plugin(s):

**Describe the bug**
I get a runtime error when I try to add a HostListener to a component. I've listed my example code with the error I get. I get this on Android, I have not tried on iOS. I have also tried specifying the type for event as KeyboardEvent and that does not work.

```
import { Component, OnInit, HostListener  } from '@angular/core';
@Component({
  moduleId: module.id,
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.scss']
})
export class MenuComponent implement OnInit {
  @HostListener('document:keydown', ['$event'])
  onKeyboardEvent(event: any) {
    console.log(event.key)
  }
}


JS: ERROR Error: Uncaught (in promise): TypeError: renderElement.on is not a function
JS: TypeError: renderElement.on is not a function
JS:     at NativeScriptRenderer.listen (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/nativescript-angular/renderer.js:188:23)
JS:     at DebugRenderer2.listen (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:11321:34)
JS:     at listenToElementOutputs (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:7956:52)
JS:     at createViewNodes (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:10173:21)
JS:     at createRootView (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:10120:9)
JS:     at callWithDebugContext (file:///data/data/org.nativescript.SampleApp/files/app/tns_modules/@angular/core/bundles/core.umd.js:11151:29)
JS:     at Object.debugCreateRootView [as create...```

**Comment by tsonevn** [comment]
Hi @danu165,
Excuse me for the delay in reply. 
I tested the issue in a sample project, however, I was unable to recreate the reported error. I would suggest upgrading your project to the latest available NativeScript version, following the instructions [here](https://docs.nativescript.org/releases/upgrade-instructions). If the problem persists, please send us the project or sample one.

**Comment by danu165** [comment]
I upgraded and got the same error. I'm not sure what process would be best to send you a sample project, but I just zipped the whole thing here: https://drive.google.com/file/d/1JtFLbdeicriOEEUSnhCAt_CSwEfjwVhe/view?usp=sharing

**Comment by tsonevn** [comment]
Hi @danu165,
Thank you for the attached project.
In NativeScript you can set up the HostListener for a specific component while using directive. You can not set it up globally inside the component. For example:
```
<ActionBar title="Details" class="action-bar"></ActionBar>
<FlexboxLayout flexDirection="column" class="page">
    <FlexboxLayout class="m-15">
        <Label (tap)="test()" btnTch class="h2" [text]="item.id + '. '"></Label>
        <Label class="h2" btnTch [text]="item.name"></Label>
    </FlexboxLayout>
    <Label class="h4" btnTch [text]="item.role"></Label>
</FlexboxLayout>
```
```

@Directive({
  selector: '[btnTch]'
})
export class btnTchDirective {

    constructor() { }

    @HostListener('touch', ['$event'])
    toggleColor(event){
        console.log("tap")
    }

}
@Component({
    selector: "ns-details",
    moduleId: module.id,
    templateUrl: "./item-detail.component.html",
})
export class ItemDetailComponent implements OnInit {
    item: Item;
    constructor(
        private itemService: ItemService,
        private route: ActivatedRoute
    ) { }

    ngOnInit(): void {
        const id = +this.route.snapshot.params["id"];
        this.item = this.itemService.getItem(id);
    }
    test(){}
}
```

Regarding your case, you can set the directive on the root component as well. For example:
```
<FlexboxLayout btnTch flexDirection="column" class="page">
....
</FlexboxLayout>
```
For further help, check out the attached example.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/2909755/Archive.zip)

**Comment by danu165** [comment]
Hm, this doesn't seem to be working on my end. Regardless this is different from what I am trying to accomplish and maybe if I explain that, it would help with a solution. I am currently trying to integrate a credit card reader with my app. Swiping the credit card sends keystrokes to the application. So if I was focused on a text field, it would print out the credit card number there. However, I would like to intercept these keystrokes and handle them in Typescript without them appearing in the text field. Is using a HostListener on "keypress/keydown/keyup" the right direction here?

**Comment by tsonevn** [comment]
Hi @danu165,
Thank you for the additional info.
You can try using the TextField's textChange event. With its help, you can get the text value of the field and then clear up its value. For example:
```
<TextField hint="Test" (textChange)="onTextChange($event)" text=""></TextField>
```
```
public onTextChange(args){
        console.log("test");
        console.log(args.object.text);
        //......
    }
```
Can you also provide more info about the plugin, that you are using for the card reader? Perhaps, there is a much better way to get the needed info, without the need to intercept specific event.

**Comment by danu165** [comment]
That sounds like a good work around. So I definitely have to use a text field to intercept a keystroke event? 

As far as the plugin, I am not actually using a native script plugin with the card reader as one does not seem to exist. The card reader is the MagTek Dynamag. They do however have an android SDK here: https://www.magtek.com/support/dynamag?tab=software. I assume it's possible to use this SDK in native script somehow, but I have not figured that part out yet. From my online research it seems I'll have to dig through the java to get it working with native script. I'm not too familiar with java, so, if you have any other suggestions on how to accomplish that, that would be great!

**Comment by tsonevn** [comment]
Hi @danu165,
Creating a nativescript plugin, which implements the functionality provided by the  MagTek Dynamag native SDK, is the best option. I also found this plugin[(nativescript-card-io)](https://github.com/skhye05/nativescript-card-io/), that may help in your case. The plugin provides an easy way to scan credit card in NativeScript app.

**Comment by danu165** [comment]
Hm unfortunately, that plugin doesn't seem to install properly, but I appreciate the suggestion. I also tried to implement the textchange method. It doesn't seem to clear the text field as it goes, but I can work around it and put a password mask on it so the user doesn't see what's happening. Unless you might have some other suggestions, I think we're all good here now.

**Comment by tsonevn** [comment]
HI @danu165,
I think that we can close this issue because the main case is related to the `MagTek Dynamag card reader` lib and the functionality that it provides. Also, were you able to solve your case with the `textChange` event?

**Comment by danu165** [comment]
Yes, it can be closed. Also, yes I did use textChange. My full solution was to create a text field with a width of 0 and auto focus on it. That keeps the text hidden and let’s me parse it in typescript. Thanks for your help!
