### ISSUE TITLE
Indents from child elements

### ISSUE THREAD

**Issue by 3DtuningProduction** [NativeScript/nativescript-angular#1761]
- CLI: 5.2.0
 - NativeScript-Angular:7.2.2
 - Angular:7.2.7

```
<GridLayout columns="*,*" rows="auto,*" width="100%" height="100%">
    <Label col="0" row="0" class="debug" height="50" [iosOverflowSafeArea]="true"></Label>
</GridLayout>
```

Regardless of what settings the parent element
all children have padding

http://prntscr.com/mxer3m

**Comment by tsonevn** [comment]
Hi @3DtuningProduction,
Can you provide some more info about the problem, you are facing? I tested the provided code snippet in a [sample project](https://play.nativescript.org/?template=play-ng&id=cmVmxy), however, both elements( the `GridLayout` and its child component(`Label`) were correctly layouted).

**Comment by 3DtuningProduction** [comment]
> Hi @3DtuningProduction,
> Can you provide some more info about the problem, you are facing? I tested the provided code snippet in a [sample project](https://play.nativescript.org/?template=play-ng&id=cmVmxy), however, both elements( the `GridLayout` and its child component(`Label`) were correctly layouted).

Hi @tsonevn 
thanks for the answer
I looked in your example - everything works fine.
The difference with my project is only that
in app.component.html 
`<RadSideDrawer [drawerTransition]="sideDrawerTransition">
    <GridLayout rows="auto, *" tkDrawerContent  class="main-menu">
        <ScrollView row="1">
            <StackLayout>
                <GridLayout columns="auto, *" *ngFor="let menuItem of menuItems; let i=index" class="menu-item monserrat semi-bold" [ngClass]="'menu_item_' + i" (tap)="onTapMenu(menuItem)">
                    <Label col="0" [text]="menuItem.icon" class="fa solid"></Label>
                    <Label col="1" [text]="menuItem.name"></Label>
                </GridLayout>
            </StackLayout>
        </ScrollView>
    </GridLayout>
    <page-router-outlet tkMainContent></page-router-outlet>
</RadSideDrawer>`

Can it somehow affect?

**Comment by tsonevn** [comment]
Hi @3DtuningProduction,
Can you send us a sample project or make the needed changes [in the one that I have attached](https://play.nativescript.org/?template=play-ng&id=cmVmxy), which will help us to reproduce the problem? Also, please provide some more context about the problem with the padding. I reviewed the attached image in your very first comment, however, I am not sure that I am understanding where is the problem.

**Comment by NickIliev** [comment]
@3DtuningProduction the explanation is still a bit vague -  if you can't share your case then try isolating the problem [in a sample Playground](https://play.nativescript.org/). As of now, it is not clear what the issue is and what you are trying to achieve (and what you have used as a codebase).
