### ISSUE TITLE
Fixed height TextView inside ScrollView is not scrollable

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1765]
**Environment**

 - Nativescript-Playgroud: 5.0.2
 
**Describe the bug**
when `TextView`  has fixed height and it is placed inside the ScrollView at the bottom of the content then when we type more line than the height it does scroll to bottom automatically. but to see the top content there is no way other than erasing the text. scrolling inside `TextView` doesn't work.

**To Reproduce**
[https://play.nativescript.org/?template=play-ng&id=kwJNyQ](https://play.nativescript.org/?template=play-ng&id=kwJNyQ)

**Expected behavior**
we should be able to scroll the typed text inside the TextView to see the top text.

**Sample project**
[https://play.nativescript.org/?template=play-ng&id=kwJNyQ](https://play.nativescript.org/?template=play-ng&id=kwJNyQ)

**Comment by NickIliev** [comment]
It seems that the issue is reproducible with NativeScript Core project (not related to Angular) - here is [a Playground demo](https://play.nativescript.org/?template=play-tsc&id=TYU9En) with Core project. Moving the issue to the main modules repository.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#7040
