### ISSUE TITLE
TextView pressing android back button doesn't call blur event

### ISSUE THREAD

**Issue by bhavincb** [NativeScript/nativescript-angular#1768]
**Describe the bug**
when TextView is focused and we press back button then it does hide the keyboard but blur event doesn't fired. i want to do some task when this happens.

**Expected behavior**
TextViee should fire some event for this.

**Comment by tsonevn** [comment]
Hi @bhavincb,
I checked the reported issue with our [ SDK examples](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ng-ui-widgets-category/text-view/basic-text-view), however, was unable to recreate the issue on Android. The only change I made is to add the blur event to the TextView component. For example:
**basic-text-view.component.html**
```
<StackLayout sdkExampleTitle sdkToggleNavButton>
	<StackLayout class="form">
		<!-- >> textview-html -->
		<Button [text]="buttonText" class="btn btn-primary btn-active" (tap)="disableTextView()"></Button>
		<Button text="Show text" class="btn btn-outline btn-active" (tap)="showText()"></Button>
		<StackLayout class="input-field">
			<Label text="Enter text:" class="label"></Label>
			<TextView (blur)="onBlur($event)" [(ngModel)]="tvtext" hint="Enter some text" [editable]="editState"
				class="input input-border"></TextView>

		</StackLayout>
		<!-- << textview-html -->
	</StackLayout>
</StackLayout>
```
**basic-text-view.component.ts**
```
..................
onBlur(){
            console.log("on blur");
    }
..................
```
When I navigate back from `BasicTextViewComponent`, the blur event has been fired. Regarding that, can you send us a sample project, that can be used for recreating the issue and provide some more info about the device/emulator, that you are using for testing?

**Comment by bhavincb** [comment]
@tsonevn  here is brief description

1. Click on "TextView". so that keyboard will open automatically.
2. now press the hardware back button. it will hide the keyboard. but it will not fire any events for that.

 we want to do some task at that time.

**Comment by tsonevn** [comment]
HI @bhavincb,
You can check the article [here](https://www.thepolyglotdeveloper.com/2018/05/override-android-back-button-nativescript-angular-application/), where it is described how to handle, when the hardware back button is tapped for Android.

**Comment by bhavincb** [comment]
@tsonevn i already thought about it. but issue is that we want to do some task only when keyboard is opened and hardware button is pressed.

**Comment by tsonevn** [comment]
Hi, @bhavincb,
You can try combining the `application.AndroidApplication.activityBackPressedEvent` handler with the functionality provided by  `nativescript-keyboardshowing` plugin. When the back button is tapped, you check if the keyboard is opened and when it is open, execute the needed task.
