### ISSUE TITLE
Ability to apply background color for UI Switch in "off" state in IOS

### ISSUE THREAD

**Issue by M-kothakapu** [NativeScript/nativescript-angular#1773]
**Environment**
 - NativeScript-Angular
 
**Describe the bug**
I'm working on Nativescript Switch component. I found an issue while applying background colors when the switch state is ON/OFF (i.e, checked or unchecked).
Based on checked property, The background color of Switch should change. 
 
**Expected behavior**

      Background Color should change when checked property is false (off state).

**Current behavior**

     Background color is not applied to OFF state (unchecked) behavior of Switch.  

**Sample project**
https://play.nativescript.org/?template=play-ng&id=8DLLBY&v=14

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/NativeScript #7095](https://github.com/NativeScript/NativeScript/issues/7095) via [**ZenHub**](https://www.zenhub.com/)
