### ISSUE TITLE
Android 4.4: Crash with lot of update in template

### ISSUE THREAD

**Issue by jpierront** [NativeScript/nativescript-angular#1777]
**Environment**
CLI: 5.3.1
Cross-platform modules: 5.3.1
Android Runtime: 5.3.1 and 5.4.0-2019-04-08-180559-01
NativeScript-Angular: 7.2.2
Angular: 7.2.7
 
**Describe the bug**
On Android 4.4, the following demo app definitely freeze in less than 60 second without specific error message (ActivityManager: Process org.nativescript.MarkingModeNoneBackground (pid 2927) has died.)

This seems to work without problems on Android 5/6/7/8/9.

**To Reproduce**
See Sample project

**Expected behavior**
No crash

**Sample project**
```
import {Component, OnInit, ViewChild} from '@angular/core';

@Component({
    selector: 'ns-app',
    moduleId: module.id,
    templateUrl: './app.component.html',
})
export class AppComponent implements OnInit {
    public elements: number[] = [];
    protected indexes = Array.from(Array(1000).keys());

    public constructor() {
        let elementValue = 0;
        for (let i in this.indexes) {
            this.elements.push(elementValue);
            elementValue = elementValue ? 0 : 1;
        }
    }

    public ngOnInit(): void {
        setTimeout((): void => {
    	    this.update();
    	    this.ngOnInit();
        }, 100);
    }

    protected update(): void {
        for (let i in this.indexes) {
            this.elements[i] = this.elements[i] ? 0 : 1;
        }
    }
}
```
```
<StackLayout>

    <ng-container *ngFor="let element of elements">
        <Label [text]="element"></Label>
    </ng-container>

</StackLayout>
```

**Comment by tsonevn** [comment]
Hi @jpierront,
I tested the provided code snippets in a sample project on Android API level 19, however, was unable to recreate the problem. For your convenience, I am attaching a sample project. Please review it and make the needed changes, which will allow me to reproduce the issue.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/3057480/Archive.zip)

**Comment by jpierront** [comment]
Hello @tsonevn,
Actually, it crash on my API 19 Virtual Device, but not on my API 19 Real Device.
I didn't encounter this problem on a classic application, we can probably close this ticket.
