### ISSUE TITLE
iOS - Text field becomes covered by keyboard on input 

### ISSUE THREAD

**Issue by jalbatross** [NativeScript/nativescript-angular#1780]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  Playground
 - Cross-platform modules: Playground
 - Android Runtime: Playground
 - iOS Runtime: 5.3.0
 - Plugin(s): Playground
 - NativeScript-Angular: Playground
 - Angular: Playground
 
**Describe the bug**
On iOS, a TextField placed near the bottom of the screen will become overlapped by the keyboard upon input if a Label with text binding is placed above it and that Label is wrapped by a horizontally oriented ScrollView.

**To Reproduce**

Input text into the pink box at https://play.nativescript.org/?template=play-ng&id=5rD1jG&v=3

**Expected behavior**
The keyboard should be below the text field

**Sample project**
https://play.nativescript.org/?template=play-ng&id=5rD1jG&v=3

**Additional context**
Removing the binding from the Label OR removing the ScrollView tag OR changing the ScrollView orientation produces correct behavior.

iOS only

**Comment by tsonevn** [comment]
Hi @jalbatross,
In your case, you need to wrap the page content in a ScrollView. This will position the TextField correctly above the keyboard. Check out the example [here](https://play.nativescript.org/?template=play-ng&id=5rD1jG&v=10).
