### ISSUE TITLE
Debug breakpoints (on VSCode) are ignored when running with HMR

### ISSUE THREAD

**Issue by gbbarroso** [NativeScript/nativescript-angular#1792]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.3
 - Cross-platform modules: 5.3.1
 - Android Runtime: 5.3.1
 - iOS Runtime: 5.3.1
 - NativeScript-Angular: 7.2.0
 - Angular: 7.2.0
 
**Describe the bug**
VScode says breakpoints are ignored because no sourcemaps are found when running with `--hmr`.

**To Reproduce**
```
tns create my-app --ng
cd ./my-app
tns run android --hmr
```
Set breakpoints and attach debugger (using NativeScript extension v0.10.0 on VSCode).

You'll see the output:

```
Searching for devices...

device: 192.168.1.101:5555 debug port: 40000


To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000


[NSDebugAdapter] Ready to attach to application on 40000

ActivityManager: Start proc 31974:org.nativescript.myapp/u0a453 for activity org.nativescript.storydownloader/com.tns.NativeScriptActivity

JS: HMR: Hot Module Replacement Enabled. Waiting for signal.

JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
```

But breakpoints are ignored (and greyed out by VScode)

**Expected behavior**
Breakpoints should trigger.

**Comment by tsonevn** [comment]
Hi @gbbarroso,
If I understand your case correctly, you are starting the debug command via CLI and then trying to attach the debugger via VSCode. 
Regarding that, in case you want to debug your project via VSCode, you need to build it only by using our [VSCode extension](https://www.nativescript.org/nativescript-for-visual-studio-code).

**Comment by gbbarroso** [comment]
@tsonevn thanks for the quick reply

Hmm not sure if I follow. The extension says it can attach to a running app, so I tested running my app using the `tns run android` command. Aftewards, I was able to get the debugger working. 

But the problem is when I add the `--hmr` flag, from what I understand VSCode doesn't know where are the sourcemaps (since it doesn't create the .js files), so the debugger doesn't work at all.

So...there is no way to debug with HMR? I see that there is indeed a command from the extension itself "Run on android", but it doesn't have HMR from what it looks like.

**Comment by NickIliev** [comment]
@gbbarroso you are trying to simultaneously run the application via `tns run` and also run it in debug mode via the VSCode extension. This won't work (or at least it could lead to side effects) so you need to stop the `tns run` command and then via your VSCodfe debug do the following:

- Add the NativeScript configuration for debug (if not done already).
- open the **launch..json** file where the NativeScript debug configuration resides and add the HMR yto the option you want to use. Use `tnsArgs` to achive taht - for example:

**_launch.json_**
```
        {
            "name": "Launch on Android",
            "type": "nativescript",
            "request": "launch",
            "platform": "android",
            "appRoot": "${workspaceRoot}",
            "sourceMaps": true,
            "watch": true,
            "tnsArgs": [
                "--hmr"
            ]
        },
```

- With the above, place your breakpoint and start the debug process with **_Launch on Android_** via VSCode.

Note that HMR is creating a bundle with Webpack behind the scenes. Bundle.js files will need the `sourceMaps` option set to true (which is the default option for NativeScript debug configuration).
All of the above is valid for **debugging via VSCode.**


For debugging with **Chrome DevTools** you just need to pass the `--hmr` flag alongside the `tns debug` but you can also pass `--env.sourceMap` which creates inline source maps (useful for debbuging bundled app).

e.g.
```
tns debug android --hmr --env.sourceMap
```
