### ISSUE TITLE
RadListView Refresh Not working

### ISSUE THREAD

**Issue by nileshmean** [NativeScript/nativescript-angular#1797]
RadListView Refresh Not working

My view code
![image](https://user-images.githubusercontent.com/49154304/56732559-6da9e580-677b-11e9-9cf0-80ca612dad19.png)

My Refresh code on component ts. 
![image](https://user-images.githubusercontent.com/49154304/56732626-9cc05700-677b-11e9-9d5d-7a8726131154.png)

**Comment by NickIliev** [comment]
@nileshmean please consider posting the actual code involved (in the form of code snippets or sample project) instead of making screenshots (which are hard to impossible to re-use for testing purposes)

**Comment by NickIliev** [comment]
It seems that even in your screenshot the `this.listview` is underlined by your IDE with a red underline. So that probably means that you don't have a reference to the listview - once again proving a sample project will make it easier to give proper instructions
