### ISSUE TITLE
Android - Setting height of TabView overrides androidTabsPosition value

### ISSUE THREAD

**Issue by YannickRtz** [NativeScript/nativescript-angular#1798]
**Environment**
 - CLI: 5.3.1
 - Android Runtime: API Level 27
 - NativeScript-Angular: 7.2.1
 - Angular: 7.2.12
 
**Describe the bug**
We use the `androidTabsPosition="bottom"` property of the TabView Component to achieve the same style in both iOS and Android Systems. We also would like to have control over the height of the TabBar. Using the `height` property for this works, but on Android the Tabbar now appears at the top again.

Our sample code:
```
<TabView androidTabsPosition="bottom" height="100px" selectedTabTextColor="#FFFFFF" tabTextColor="#777777">
    <page-router-outlet
        *tabItem="{title: 'Support', iconSource: getIconSource('support'), textTransform: 'capitalize'}"
        name="supportTab">
    </page-router-outlet>

    <page-router-outlet
        *tabItem="{title: 'Dashboard', iconSource: getIconSource('dashboard'), textTransform: 'capitalize'}"
        name="dashboardTab">
    </page-router-outlet>

    <page-router-outlet
        *tabItem="{title: 'Settings', iconSource: getIconSource('settings'), textTransform: 'capitalize'}"
        name="settingsTab">
    </page-router-outlet>
</TabView>
```

**Expected behavior**
I would like to use the height property alongside of the androidTabsPosition property of the TabView Component without the Tabbar appearing at the top of the view on Android.

**Comment by tsonevn** [comment]
Hi @YannickRtz,
I checked the described case, however, was unable to recreate a similar problem on  Android. For your convenience, I am attaching a Screen Shot and a [link ](https://play.nativescript.org/?template=play-ng&id=ADFo08) to the sample project that I am using for testing. You can review the project and make the needed changes, which will allow us to reproduce the issue.
![Capture](https://user-images.githubusercontent.com/17448734/56888502-c8de1f80-6a7c-11e9-8f0d-db3aaead4cc0.PNG)

**Comment by YannickRtz** [comment]
Thank you @tsonevn for the sample project. Seeing that you put "1300px" as height, we realized that there was a misunderstanding on our side: Our goal was to change the height of the tabbar itself, not that of the whole view. Trying out small numbers like 100px of course made the tabbar appear at the top of th app.
Is there a way to influence the height of the Tabbar in the TabView? Our goal is to have the Android app look very similar to the iOS app.

**Comment by YannickRtz** [comment]
I found a way to achieve a custom Tabbar height using this answer: https://stackoverflow.com/a/53570961

**Comment by tsonevn** [comment]
Hi @YannickRtz,
I am glad to hear that you have solved your case.
