### ISSUE TITLE
Calling saveActivityState on Android with nativescript angular 

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1799]
**Is your feature request related to a problem? Please describe.**
on android when we press on back button and the routes are empty then application will close and when we start the application again it will takes time to load 
what i need is that , when the applications routes are empty and we press the button button instead of closing the application we move the application in foreground (the activity called when we press home button on android ) so when we start the application again the activity will resume instead of creating new   

please help what can we do in order to compete this requirement.

**Comment by tsonevn** [comment]
In your case, you can try setting the `launchMode` to `singleTask` in AndroidManifest. Check out the link [here ](https://developer.android.com/guide/topics/manifest/activity-element)for details.
