### ISSUE TITLE
FormattedString Cast EXCEPTION when a Number is used

### ISSUE THREAD

**Issue by palpa** [NativeScript/nativescript-angular#180]
I.e. below construction:
`
<Label>
      <FormattedString>
        <Span text="500"></Span>
      </FormattedString>
</Label>
`

Cause this exception:
`
JS: EXCEPTION: Error: Uncaught (in promise): Error: Cannot convert number to Ljava/lang/CharSequence; at index 1
JS: STACKTRACE:
JS: Error: Uncaught (in promise): Error: Cannot convert number to Ljava/lang/CharSequence; at index 1
`

**Comment by ngydat** [comment]
What would you like to do exactly ? From my understanding, it seems that you want to put a label with the number 500 in it.

**Comment by palpa** [comment]
``` <Label> <FormattedString> <Span text="500"></Span> </FormattedString> </Label>``` is the simplest case that cause the issue.
What I want to do is the below:
```
           <Label>
            <FormattedString>
              <Span text="Code: " fontAttributes="Bold"></Span>
              <Span [text]="item.code"></Span>
            </FormattedString>
          </Label>
```
I've temporary solved the issue adding a character before the number like below:

```
          <Label>
            <FormattedString>
              <Span text="Code: " fontAttributes="Bold"></Span>
              <Span [text]='"#" + item.code'></Span>
            </FormattedString>
          </Label>
```
But it would be good to remove it in the future.
Thanks!
