### ISSUE TITLE
Triggering changeDetection on back navigation

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1802]
**Environment**
 - CLI: 5.3.1
 - Cross-platform modules: 5.3.1
 - Android Runtime:5.3.1
 - iOS Runtime:5.3.1
 - NativeScript-Angular:7.2.3
 - Angular:7.2.0
 
**Describe the bug**
The change detection is not triggered for the page when we navigate back to it. A similar case is when we have made a change, which requires an update on the content of the previous page. The issue is reproducible only while using `OnPush` change detection strategy.

Reported via admin. t.1407062

**Comment by elena-p** [comment]
the fix is in both release and master branches
