### ISSUE TITLE
iOS - When nesting page-router-outlets, the inner "page" is rendered fullscreen instead of where it should be positioned.

### ISSUE THREAD

**Issue by sbknick** [NativeScript/nativescript-angular#1804]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.0
 - iOS Runtime: 5.1.0
 - NativeScript-Angular: 7.1.0
 - Angular: 7.1.0
 
**Describe the bug**
On iOS, when a page-router-outlet is nested within a root page-router-outlet, the inner PRO will be drawn full-screen regardless of its positioning or other sizing.

**To Reproduce**
1. Create a NS Angular project.
2. Create two components, an OuterComponent and an InnerComponent.
3. In the OuterComponent, define the template like so:
```
<StackLayout>
    <Label text="I am an outer header!"></Label>
    <page-router-outlet name="inner-outlet"></page-router-outlet>
</StackLayout>
```
4. In the InnerComponent, define the template like so:
```
<Label text="I am inner text!"></Label>
```
5. Define the routing for the application like so:
```
{ path: "", redirectTo: "/outer/(inner-outlet:inner)", pathMatch: "full" },
{ path: "outer", component: OuterComponent, children: [
    { path: "inner", component: InnerComponent, outlet: "inner-outlet" }
] },
```
6. When running the app on iOS, only the "I am inner text!" label will be visible.

**Expected behavior**
"I am an outer header!" should display at the top, and beneath it, "I am inner text!"

**Sample project**
https://github.com/sbknick/ns-ios-nestedpagerouters.git

**Additional context**
On Android, this functions as expected.

**Comment by tsonevn** [comment]
Hi @sbknick,
In your specific case, you need to nest the inner page-router-outlet inside a Layout container. For example:
```
<StackLayout>
        <Label text="I am outer-header-text!"></Label>
        <GridLayout>
            <page-router-outlet name="inner-outlet" actionBarVisibility="never"></page-router-outlet>
        </GridLayout>
    </StackLayout>
```
With the above-described code fragment, the page-router-outlet should be rendered as expected on both(iOS and Android).
