### ISSUE TITLE
Can not access child tab item from tabs component

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/nativescript-angular#1809]
I want to access tab items properties from tabs component (parent). I do the following:

```TS
@ViewChild(BrowseComponent) public browseComponent: QueryList<BrowseComponent>;
...
changeLang(lang) {
    // this is undefined
    console.log(this.browseComponent);
}
```

Any idea?

**Comment by NickIliev** [comment]
@vahidvdn you can try to access the component via its NativeScript's` loaded` event - if you are still experiencing troubles provide a sample Playground so we could test your case.

**Comment by vahidvdn** [comment]
@NickIliev Thanks for the reply.
About `loaded` event, when it comes to the tabs component, there is a bug (also mentioned [here](https://github.com/NativeScript/NativeScript/issues/6650)) that you can't set `androidOffscreenTabLimit` to 0. So I can't change anything when going to the particular tab.

For a workaround, I used a BehaviourSubject to achieve what I need. But for further investigate I try to provide a sample Playground ASAP.

**Comment by vahidvdn** [comment]
Hey @NickIliev 
[Here](https://play.nativescript.org/?template=play-ng&id=l7d3Ky) is a Playground demo for demonstrating the issue. Sorry for being late.

**Comment by NickIliev** [comment]
@vahidvdn looking at your demo project but I am not pretty sure where the issue resides? Are you trying to access the `BrowserComponent` thought `app.component.ts` and `ViewChild`? Or am I missing something? The former is expected not to work - think of `page-router-outlets` as navigation frames and not as views that you can traverse.

**Comment by vahidvdn** [comment]
@NickIliev 

> Are you trying to access the BrowserComponent thought app.component.ts and ViewChild?

Yes I am.

I understand. Let me explain what I want to do. In my project, I have a carousel in tabs component (in this case, app.component.ts) that I get the user's language. Therefore when the user skips the carousel (hiding it with `visibility` or `*ngIf`), the translation must be done in all of the tabs. So I must be able to access to the components.

Btw, as I mentioned, I did it with BehaviourSubject. But couldn't be able to do as I do in Angular web projects.
