### ISSUE TITLE
Creating white-space using typescript instead of html in angular

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1827]
How to create White space from typescript 

example
I am have button with text charge 
and when i send request i show loader over button 
in such case text is no longer shown and i want to replace the number of characters to an empty string.

Why i need such requirement is explain below
Suppose we have buttons like 

-----charge-----
-----create data-----
-----Add more customers-----

each button have same padding on left and right so when i remove the text then the button size will shrink thats why i need to replace the characters with empty spaces in such case the buttons will not change its size

**Comment by tsonevn** [comment]
Hi @tahir-jamil,
In your specific case,  I would suggest saving the initial width of the button. When the text is set to empty string, you can set the previously saved width. Check out the sample project [here](https://play.nativescript.org/?template=play-ng&id=mJLT8w). For further questions, please use our [StackOverflow thread](https://stackoverflow.com/questions/tagged/nativescript).

**Comment by tahir-jamil** [comment]
thanks @tsonevn
