### ISSUE TITLE
custom icons in nativescript 

### ISSUE THREAD

**Issue by tahir-jamil** [NativeScript/nativescript-angular#1836]
Is that any way of creating our own icons and used in nativescript project ?

**Comment by tsonevn** [comment]
Yes, you can use custom icons in your application. Keep in mind that you should create the images for the required device screen densities while using  [NativeScript Image Builder ](http://nsimage.brosteins.com/) or some other tool for image edit and you should add them in the `App_Resources` folder as it is described in the article [here.](https://docs.nativescript.org/ui/image-resources).
For further question-related issues, please use our [thread in StackOverflow](https://stackoverflow.com/questions/tagged/nativescript), this repository is used only for bug reporting and feature requests.
