### ISSUE TITLE
List Views not visible

### ISSUE THREAD

**Issue by itsmeneartou** [NativeScript/nativescript-angular#1844]
I have a code sharing Nativescript-Angular project. I am using two `ListView's` in a Lazy loaded module. The lazy loaded module is structured such that when I navigate to that module from AppModule. The component has a TabView with two page router outlets as shown below.

    <TabView id="tabViewContainer">
        <page-router-outlet  actionBarVisibility="never"  *tabItem="{title: 'Players'}" name="playersTab"></page-router-outlet>
        <page-router-outlet  actionBarVisibility="never" *tabItem="{title: 'Event Requests'}" name="eventRequestsTab"></page-router-outlet>
    </TabView>

Now each tab item is a `page-router-outlet` which routes to a child component and that child 
component has `ListView` as parent element as shown below.

    <ListView
      class="list-group"
      [items]="players"
     
      (loaded)="onListViewLoaded($event)"
      #listView
    >
      <ng-template let-player="item" let-third="third">
        <GridLayout class="list-group-item" rows="*" columns="auto, *">
          <Image
          col="0"
          [src]="player.photoURL"
          class="thumb img-circle"
        ></Image>
          <StackLayout col="1">
            <Label
              [text]="player.displayName"
              class="list-group-item-heading"
            ></Label>
            <Label
              [text]="player.uid"
              class="list-group-item-text"
              textWrap="true"
            ></Label>
          </StackLayout>
        </GridLayout>
      </ng-template>
    </ListView>

Now the problem I am facing is when these two list views are shown side by side sometimes both the list views don't show anything and sometimes only the second tab shows data where as the first tab only shows the item dividers as shown below:-

**Case 1 tab-1**
[![enter image description here][1]][1]

**Case 1 tab-2**
[![enter image description here][2]][2]

**Case 2 tab-1**
[![Case 2-picture-1][3]][3]

**Case 2 tab-2**
[![Case 2-picture-2][4]][4]

The items always have more than one element but still this problem is being arised.

I have tried using the function `listview.refresh()` but still no success with that. I have also used `ChangedDetectionStratergy.OnPush` and called `markedForRefresh` function when data is received. I have tried using `ObservableArray` provided by `Nativescript` but I was bit confused while using that and also I felt it was not available for code sharing project.

I am frustrated since yesterday and it looks like a bug in Nativescript. Can you help overcome it so that both tabs shows the data always(knowing the arrays always have atleast one element) ?

  [1]: https://i.stack.imgur.com/FtOMM.png
  [2]: https://i.stack.imgur.com/aTOnr.png
  [3]: https://i.stack.imgur.com/lvjEf.png
  [4]: https://i.stack.imgur.com/JTwGN.png

**Comment by m-abs** [comment]
Try wrapping the `ListView` in a `GridLayout`, the first looks like the `ListView` gets zero height.

Where do you get the `let-third="third"` from?
I've never seen that before and you don't use the variable `third` in the item template.

**Comment by tsonevn** [comment]
Hi @itsmeneartou,
Can you attach the project, that you are using for testing? From the given code fragments, we can not see how the source is loaded via code-behind and whether there is something specific lead to the not-loading source.

**Comment by itsmeneartou** [comment]
I couldn't add the exact project in which I was facing the problem but I created another project to test list view from source algolia and source from placeholder data shown as example in docs, what I found was when the array which is used as data source for listview is filled with data in constructor then the listview is rendered correctly but If same data is pushed to array after some delay like callback from algolia the data is not rendered in listview, also callbacks like `onSetupItemView` are not called even after calling methods like `listView.refresh()`, `ref.markForCheck()` after the array is filled with data in algolia callback. 
The test project is available [here](https://github.com/itsmeneartou/listview-test/tree/placeholder-data)
Note: It is the branch `algolia-data` which is causing the problem, I created `placeholder-data` branch just to show the difference that when data is pushed to array in constructor list view is rendered.

**Comment by edusperoni** [comment]
Can you try calling `ref.detectChanges()` instead? Also call that even if listview is null. Also try removing OnPush just to check if this is a change detection issue or a ListView issue.

I haven't run the code but to me it seems you're updating your array reference outside of angular zone (algolia probably calls the callback outside) and the reference is never passed to the ListView, so ListView.refresh() doesn't work.

**Comment by itsmeneartou** [comment]
I tried calling `ref.detectChanges()` and the data was rendered correctly on main screen. So I also changed `markedForChanges` to `detectChanges` in my original project and what I observed was that now the case 1 where list views were blank didn't occur but still the case 2 was occuring where one list view was rendered correctly but one list view showed only item dividers. So I created another branch in test project to simulate this behaviour and I was able to get that behaviour in test project as well. The branch which shows this behaviour is called `aloglia-data-with-lazy-list-in-tabs` which is available [here](https://github.com/itsmeneartou/listview-test/tree/aloglia-data-with-lazy-list-in-tabs). I am unable to figure out why this is happening, sometimes I have observed players tab rendering data and events tab showing only list dividers and sometimes I have observed vice versa as well, looks like a race condition somewhere.

**Comment by edusperoni** [comment]
Try calling `this.ref.detectChages()` before `this.listView.refresh()`. You could also try using a subject + async pipe. Make sure `this.subject.next` runs inside `NgZone` like so:

```
players$ = new Subject();
...
this.ngZone.run(() => {
    this.players$.next(newPlayers);
});
```

html:

```
<ListView ... [items]="players$ | async"> ...
```

**Comment by itsmeneartou** [comment]
I made changes like you said but still not success with being able to show both `ListView`'s` simultaneously, the same behaviour of only one list being rendered properly still seen. I have made a commit with the changes which is available [here](https://github.com/itsmeneartou/listview-test/tree/8be0be021e03ade8db92cae188b212ad68d3dbdc)
