### ISSUE TITLE
No zoom scale level being returned in the RadChart Zoom Event

### ISSUE THREAD

**Issue by camsethsum** [NativeScript/nativescript-angular#1846]
**Is your feature request related to a problem? Please describe.**
Yes, Currently using the radCartesianChart with DateTimeContinousAxis that has a majorStep value of Day, Week, Month and Year. Client wants to implement a zoom feature with the chart that will base on the zoom level depth that it will also change the majorStep value of the DateTimeContinousAxis.
(Ex. Zoomlevel=3, then with that value I would want to dynamically change the value of majorStep value to Day). 

I have tried accessing the event data being returned from the chartZoomed event in the RadCartesianChart but it only returns data that will tell us that the chart has been zoomed with no data being returned of what is now the zoom level depth, or even telling us that zoom performed is Zoom-out or Zoom-in.
 

**Describe the solution you'd like**
The solution that most likely will solve this, is for the event data to also return a zoom level depth or return something that will tell us that the zoom is **IN** or **OUT** or best to have both, but the zoom scale level will most likely solve this problem, but also having to know what zoom is being performed will be great for another use case.

**Describe alternatives you've considered**
I could have use the individual gestures available in nativescript but the problem is the chart already overrides these gestures if we interact with the chart.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-ui-feedback #1147](https://github.com/NativeScript/nativescript-ui-feedback/issues/1147) via [**ZenHub**](https://www.zenhub.com/)
