### ISSUE TITLE
Show modal on init Android

### ISSUE THREAD

**Issue by nicolainormann** [NativeScript/nativescript-angular#1847]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.0
 - Cross-platform modules: 5.3.1
 - Android Runtime: 5.2.0
 - Plugin(s):
 - NativeScript-Angular: 7.2.3
 - Angular: 7.2.13
 
**Describe the bug**
On Android an error is thrown when trying to calling `this.modalDialogService.showModal(...)` in `ngOnInit`.

`[Galaxy S10+]: ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentTransaction.add(android.support.v4.app.Fragment, java.lang.String)' on a null object reference`
`[Galaxy S10+]: com.tns.Runtime.callJSMethod(Runtime.java:1070)`
`[Galaxy S10+]: com.tns.Runtime.callJSMethod(Runtime.java:1050)`
`[Galaxy S10+]: com.tns.Runtime.callJSMethod(Runtime.java:1042)`
`[Galaxy S10+]: com.tns.Runtime.callJSMethodNative(Native Method)`
`[Galaxy S10+]: com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)`
`[Galaxy S10+]: com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)`
`[Galaxy S10+]: android.support.v4.app.DialogFragment.show(DialogFragment.java:159)`
`[Galaxy S10+]: com.tns.gen.java.lang.Runnable.run(Runnable.java:17)`
`[Galaxy S10+]: android.os.Handler.handleCallback(Handler.java:873)`
`[Galaxy S10+]: android.os.Handler.dispatchMessage(Handler.java:99)`
`[Galaxy S10+]: android.os.Looper.loop(Looper.java:214)`
`[Galaxy S10+]: android.app.ActivityThread.main(ActivityThread.java:7032)`
`[Galaxy S10+]: java.lang.reflect.Method.invoke(Native Method)`
`[Galaxy S10+]: com.android....`

The error isn't thrown if you wrap the `this.modalDialogService.showModal(...)` in a `setTimeout(() => ..., 1000)`, so it seems like it could be a race condition on application startup

**To Reproduce**
Open the playground on an Android device

**Expected behavior**
To open modal on ngOnInit on Android

**Sample project**
https://play.nativescript.org/?template=play-ng&id=wG35Hx

**Comment by tsonevn** [comment]
Hi @nicolainormann,
In your scenario, you need to open the modal page on page loaded event. For example:
```
ngOnInit(): void {
        this.page.on(Page.loadedEvent, (args) => {
            this.modalDialogService.showModal(ModalComponent, { viewContainerRef: this.vcRef })
        })
    }
```
For further help, check out the sample project [here](https://play.nativescript.org/?template=play-ng&id=wG35Hx&v=2).
