### ISSUE TITLE
Custom component position manipulation in AbsoluteLayout

### ISSUE THREAD

**Issue by DanielRitvas** [NativeScript/nativescript-angular#1848]
Lets say I've created a custom component and want to place it inside `AbsoluteLayout` of parent component. So basically I would do something like this:

    <AbsoluteLayout>
       <custom-component></custom-component>
    </AbsoluteLayout>

But what if I want to adjust a position of the custom component and use `AbsoluteLayout`'s `top` and `left` attributes on the child? The problem is that I can't put this attributes directly on custom child tag. The only solution I found is to wrap custom component with `StackLayout`:

    <AbsoluteLayout>
        <StackLayout top="50">
           <custom-component></custom-component>
        </StackLayout>
    </AbsoluteLayout>

So my question is how can I position custom child without adding additional wrapper layout and make code like below to work:

    <AbsoluteLayout>
           <custom-component top="50"></custom-component>
    </AbsoluteLayout>

Should I make any changes to my child component? Or maybe it's not possible to get rid of wrapper layout at all?

**Comment by tsonevn** [comment]
Hi @DanielRitvas,
Setting the position directly to the custom component is not supported. In your case, you have two option. The first one as you have suggested is to wrap the custom component inside a Layout structure and to set up the position on it. The second option is to pass the parameter to the custom component while using the `@Input` and to set up the position to the root container inside the custom component. For the second option, you can check the sample project [here](https://play.nativescript.org/?template=play-ng&id=LhxqAh).

**Comment by DanielRitvas** [comment]
> here

Hi @tsonevn , thank you for your response! The second option is a quite surprise for me since I thought that ns angular wraps a content of the child component with a <child_component_name_tag> in a same way as it does in a dom. So that root container inside the custom component is not the direct child of `AbsoluteLayout`:

<AbsoluteLayout>
   <custom-component>
      <custom-component-container-here top="50"><custom-component-container-here>
   </custom-component>
<AbsoluteLayout>

I'm probably missing something 😅
