### ISSUE TITLE
Android -  Unable to destroy activity 

### ISSUE THREAD

**Issue by KkevinLi** [NativeScript/nativescript-angular#1850]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 5.4.1 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.0 version and is up to date.
 
**Describe the bug**

After upgrading to Nativescript 5.4.0  I am noticing a that Android devices will get the following error occasionally (especially Samsung phones) when I swipe my app from the recent tasks. 

```System.err: java.lang.RuntimeException: Unable to destroy activity {org.nativescript.crash/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onDestroy failed
System.err: 
System.err: Error: View not added to this instance. View: Frame(2) CurrentParent: undefined ExpectedParent: AppHostView(1)
System.err: File: "file:///data/data/org.nativescript.crash/files/app/vendor.js, line: 108789, column: 12
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 79589, column: 33
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view-base/view-base.js.ViewBase._removeView', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 108789, column: 19
System.err: 	Frame: function:'push.../node_modules/nativescript-angular/view-util.js.ViewUtil.removeFromVisualTree', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 78137, column: 20
System.err: 	Frame: function:'push.../node_modules/nativescript-angular/view-util.js.ViewUtil.removeChild', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 78065, column: 18
System.err: 	Frame: function:'push.../node_modules/nativescript-angular/renderer.js.NativeScriptRendererFactory.ngOnDestroy', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 75339, column: 27
System.err: 	Frame: function:'callNgModuleLifecycle', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 54026, column: 31
System.err: 	Frame: function:'push.../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.destroy', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 54645, column: 9
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 74967, column: 31
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/data/observable/observable.js.Observable.notify', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 96635, column: 23
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/frame.js.ActivityCallbacksImplementation.onDestroy', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 114828, column: 21
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/frame/activity.js.NativeScriptActivity.onDestroy', file:'file:///data/data/org.nativescript.crash/files/app/vendor.js', line: 112601, column: 25
System.err: 
System.err: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4703)
System.err: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4726)
System.err: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:214)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7045)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onDestroy failed
```
**To Reproduce**

Launch app
Tap square icon (which shows all your recent apps)
Leave the screen on like this for ~1 minute
Swipe the app to kill it and the ErrorReportActivity will be launched

Easily replicable on Samsung devices. Occasionally on Pixel.
**Expected behavior**
`<activity android:name="com.tns.ErrorReportActivity"/>` shouldn't be triggered like in previous versions

**Sample project**

https://github.com/KkevinLi/Android-Crash

**Additional context**

```
@Component({
    selector: "ns-app",
    moduleId: module.id,
    template: `<page-router-outlet></page-router-outlet>
    <Label visibility="collapsed">
    </Label>`
})
```
The cause of this issue seems to be having: ` <Label visibility="collapsed"> </Label>`
`Span` would also crash.

Reason for using ^ is because I would attach a directive to the `label` or `span` etc  and enable it with an ngIF.

**Comment by tsonevn** [comment]
Hi @KkevinLi,
If you need to display the `page-router-outlet` and the `Label` at the same level inside the `AppComponent`, you need to wrap them in Layout(e.g. `GridLayout`). For example:
```
    <GridLayout rows="* 50">
             <StackLayout row="0">
                      <page-router-outlet></page-router-outlet>
             </StackLayout>
            <Label row="1" visibility="collapsed"></Label>
    </GridLayout>
```
Can you check if you will be able to recreate the issue after making this change?

**Comment by KkevinLi** [comment]
@tsonevn  Thanks that fixed it ! Going to close this now.

Just had a few follow up questions. What changed between Nativescript 5.3 to 5.4 that made it necessary to wrap the `page-router` and `Label` in a layout? Also, how does putting the two in a layout resolve this issue?

**Comment by KkevinLi** [comment]
With the fix you mentioned, I noticed that the app is not actually killed when we swipe it away (Android studio shows that the process is not marked `DEAD`).

**Comment by edusperoni** [comment]
Your app is not necessarily dead after swiping it

https://www.itworld.com/article/2693446/closing-android-apps-by-swiping-them-away-what-that-actually-does.html

**Comment by tsonevn** [comment]
Hi @KkevinLi,
@edusperoni  is right. It is not necessarily the app to be killed immediately after force closing it.  It is something that is controlled by the OS. 
Regarding, your first question, I am not sure which change exactly disables the option to use multiple views on the same level for root. However, the recommended way always was to have a single root component
