### ISSUE TITLE
SearchBar Styles inconsistency in Android and IOS

### ISSUE THREAD

**Issue by M-kothakapu** [NativeScript/nativescript-angular#1853]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - NativeScript-Angular: 4.2.0

 
**Describe the bug**
Trying to utilize NativeScript's SearchBar component to customize its styles. In this process I'm not finding a consistency with IOS and Android screens. Here I'm attaching the screenshots please verify. 

**Expected behavior**
Android Styles to match with IOS styles. Both the screens should look same.

**Additional context**

IOS Screen: 
![image](https://user-images.githubusercontent.com/17285726/59152231-9f160200-8a05-11e9-8434-ac174c70b7b9.png)

Android Screen:
![image](https://user-images.githubusercontent.com/17285726/59152265-2ebbb080-8a06-11e9-8c96-e0a979055b73.png)

**Comment by NickIliev** [comment]
@M-kothakapu from one hand, both controls are having conceptual differences coming from the native APIs (iOS vs Android) so it is expected that the SearchBar will look differently on iOS vs Android. However, we have created a base abstraction that should allow you to change the background color, font color on both platforms. 

Can you please clarify what UI are you expecting to see? The best approach would be to [create a Playground](https://play.nativescript.org/) with the styles you have applied.

**Comment by M-kothakapu** [comment]
> @M-kothakapu from one hand, both controls are having conceptual differences coming from the native APIs (iOS vs Android) so it is expected that the SearchBar will look differently on iOS vs Android. However, we have created a base abstraction that should allow you to change the background color, font color on both platforms.
> 
> Can you please clarify what UI are you expecting to see? The best approach would be to [create a Playground](https://play.nativescript.org/) with the styles you have applied.

I agree with you. I got an alternative solution where I used a Text Field to customize the search bar to my required styles instead of utilizing the actual search bar of NS.

**Comment by M-kothakapu** [comment]
Fixed in an alternative solution.
