### ISSUE TITLE
Using HMR with a modal view breaks livesync

### ISSUE THREAD

**Issue by lini** [NativeScript/nativescript-angular#1854]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.0
 - Cross-platform modules: 5.4.0
 - Android Runtime: 5.4.0
 - iOS Runtime: 5.4.0
 - Plugin(s): Kinvey Studio Angular Shared App (web/mobile)
 - NativeScript-Angular: 7.2.4
 - Angular: 7.2.15
 
**Describe the bug**
If something is changed in the app while a modal view is opened, the sync finishes successfully, but the view is not refreshed, the modal is not closed and is no longer connected with the angular app (i.e. cannot be closed).

**To Reproduce**
Reproduced in Kinvey Studio projects. Add a modal view, build/deploy using a device / emulator. Open the modal and change something (e.g. button text in HTML) to force a sync. Tested in Android 9.

**Expected behavior**
Sync finishes, modal is closed, page is refreshed.

**Additional context**
Contact me for additional details  if needed.

**Comment by zbranzov** [comment]
The fix is released in nativescript-angular@8.2.1
