### ISSUE TITLE
Use placeholder nativescript with angular 2

### ISSUE THREAD

**Issue by ngydat** [NativeScript/nativescript-angular#186]
Hi,

Since the [Nativescript Telerik UI](https://www.npmjs.com/package/nativescript-telerik-ui) plugin isn't ready to be used with Angular 2 ([yet](https://github.com/telerik/nativescript-ui-samples/issues/71)), I turned myself to the use of the [Nativescript placeholder](https://docs.nativescript.org/ui/placeholder).

[Here](http://pastebin.com/wVejVmLJ) is the view of my page : I'd like to put a sidedrawer in the messages tab (you'll see in the code where I want to put it exactly) but even when I try to put a simple native Textfield in the page, I get nothing. Has anyone used the placeholder in a nativescript/angular2 project ?

**Comment by tzraikov** [comment]
Currently the placeholder tag is not implemented in Angular 2.

**Comment by kazemihabib** [comment]
I tried in angular.I used it for placeholder and this helped me : https://github.com/NativeScript/nativescript-angular/issues/283#issuecomment-228046936
