### ISSUE TITLE
Key Listener Feature for TextFields/TextView

### ISSUE THREAD

**Issue by virtualbjorn** [NativeScript/nativescript-angular#1862]
**Is your feature request related to a problem? Please describe.**
 
I wanted to capture the "Clear/Del key" event even if textfield is already empty
**Describe the solution you'd like**

Maybe add key events from soft input.
**Describe alternatives you've considered**

**Additional context**

It will definitely be a big help for those who needs to handle different input keys

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/NativeScript #7349](https://github.com/NativeScript/NativeScript/issues/7349) via [**ZenHub**](https://www.zenhub.com/)
