### ISSUE TITLE
Http failure response for http://localhost...

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#1864]
@rezaee commented on [Sat Jun 15 2019](https://github.com/NativeScript/android-runtime/issues/1397)

I am a new learner of NativeScript. I am following a video tutorial on Coursera to create an Android project using NativeScript, and I got the above error that is made by this part of my code:

`process-httpmsg.service.ts` :

    import { Injectable } from '@angular/core';
    
    import { throwError } from 'rxjs';
    import { HttpErrorResponse } from '@angular/common/http';
    
    @Injectable({
      providedIn: 'root'
    })
    export class ProcessHTTPMsgService {
    
      constructor() { }
    
      public handleError(error: HttpErrorResponse | any) {
        let errMsg: string;
    
        if (error.error instanceof HttpErrorResponse) {
          errMsg = error.error.message;
        } else {
          errMsg = `${error.status} - ${error.statusText || ''} ${error.message}`;
        }
    
        return throwError(errMsg);
      }
    }

`dish.services.ts`:

    import { Injectable } from '@angular/core';
    import { Dish } from '../shared/dish';
    
    import { Observable } from 'rxjs';
    import { map, catchError } from 'rxjs/operators';
    import { HttpClient, HttpHeaders } from '@angular/common/http';
    import { baseURL } from '../shared/baseurl';
    import { ProcessHTTPMsgService } from './process-httpmsg.service';
    
    @Injectable({
      providedIn: 'root'
    })
    export class DishService {
    
      constructor(private http: HttpClient,
        private processHTTPMsgService: ProcessHTTPMsgService) { }
    
      getDishes(): Observable<Dish[]> {
        return this.http.get<Dish[]>(baseURL + 'dishes')
          .pipe(catchError(this.processHTTPMsgService.handleError));
      }
    
      getDish(id: string): Observable<Dish> {
        return this.http.get<Dish>(baseURL + 'dishes/' + id)
          .pipe(catchError(this.processHTTPMsgService.handleError));
      }
    
      getFeaturedDish(): Observable<Dish> {
        return this.http.get<Dish[]>(baseURL + 'dishes?featured=true').pipe(map(dishes => dishes[0]))
          .pipe(catchError(this.processHTTPMsgService.handleError));
      }
    }

`menu.component.html`:

    <ActionBar title="Menu" class="action-bar">
    </ActionBar>
    <StackLayout class="page">
        <ListView [items]="dishes" class="list-group" *ngIf="dishes">
            <ng-template let-dish="item">
                <StackLayout orientation="horizontal" class="list-group-item">
                    <Image row="0" col="0" rowSpan="2" height="108" width="108"  [src]="BaseURL + dish.image" class="thumb p-16"></Image>
                    <GridLayout class="list-group-item" rows="auto *" columns="*">
                        <Label row="0" col="0" [text]="dish.name" class="list-group-item-heading"></Label>
                        <Label row="1" col="0" class="list-group-item-text" [text]="dish.description"></Label>   
                    </GridLayout>
                </StackLayout>
            </ng-template>
        </ListView>
        <ActivityIndicator busy="true"  *ngIf="!(dishes || errMess)" width="50" height="50" class="activity-indicator"></ActivityIndicator>
        <Label *ngIf="errMess" [text]="'Error: ' + errMess"></Label>
    </StackLayout>

`menu.component.ts`:

    import { Component, OnInit, Inject } from '@angular/core';
    import { Dish } from '../shared/dish';
    import { DishService } from '../services/dish.service';
    
    
    @Component({
      selector: 'app-menu',
      moduleId: module.id,
      templateUrl: './menu.component.html',
      styleUrls: ['./menu.component.css']
    })
    export class MenuComponent implements OnInit {
    
      dishes: Dish[];
      errMess: string;
    
      constructor(private dishService: DishService,
        @Inject('baseURL') private baseURL) { }
    
      ngOnInit() {
        this.dishService.getDishes()
          .subscribe(dishes => this.dishes = dishes,
            errmess => this.errMess = <any>errmess);
      }
    
    }

My server is running and accessable by my browser in `http://localhost:3000` and other paths work well, but don't know why I see the error in the screen of the mobile AVD?

I also tried `export const baseURL = "http://192.168.1.5:3000/";` for my `baseURL` but again the same error!

**Comment by NickIliev** [comment]
@rezaee `localhost` is **not** the proper loopback address when working through the emulators VM. Local IP addresses (e.g. like that starting with 192.168.x.x) won't work as well for the very same reason.

[See this thread for more details](https://stackoverflow.com/a/39958955/4936697) on what loopback to use instead of localhost when working with AVDs.

**Comment by rezaee** [comment]
I tried `10.0.2.2:3000/` but didn't work and I get the same error as before!

**Comment by NickIliev** [comment]
@rezaee you still need to add the `http://` prefix to your `baseURL`

**Comment by rezaee** [comment]
> @rezaee you still need to add the `http://` prefix to your `baseURL`

I added it but no difference! I get the same error :(

**Comment by rezaee** [comment]
I have uploaded my project here, maybe it helps: https://github.com/rezaee/conFusion

**Comment by rezaee** [comment]
Please open this thread maybe someone could help me!
