### ISSUE TITLE
Update zone.js peer dependency

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-angular#1867]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.4.x
 - Cross-platform modules: 5.4.2
 - Android Runtime: 5.4.0
 - iOS Runtime:
 - Plugin(s):
 - NativeScript-Angular: 8.0.1
 - Angular: 8.0.0
 
**Describe the bug**

Angular 8+ depends on zone.js@^0.9.1 but nativescript-angular wants zone.js@^0.8.4.

**To Reproduce**

On a nativescript-angular 8.0.1 project -> Run: npm ls
```bash
npm WARN nativescript-angular@8.0.1 requires a peer of zone.js@^0.8.4 but none is installed. You must install peer dependencies yourself.
```
**Expected behavior**
No warning about peer dependency.

**Comment by tsonevn** [comment]
PR: https://github.com/NativeScript/nativescript-angular/pull/1869
