### ISSUE TITLE
When using registerElement addChildFromBuilder overloads are not being called.

### ISSUE THREAD

**Issue by TheOriginalJosh** [NativeScript/nativescript-angular#187]
Example project . https://github.com/TheOriginalJosh/ng2ParallaxTest

if you go through the code with a debugger, inside of the nativescript-parallax plugin it's addChildFromBuilder  overload function is not being called. however if you use the plugin in the conventional sense inside of the page object like: `<Page xlms:parallax='nativescript-parallax'   ...` the addChildFromBuilder function is called.

**Comment by vakrilov** [comment]
@TheOriginalJosh  First of all - nice plugin.
To the point: In the Angular Renderer we use the [`insertChild` and `addChild` methods directly](https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/view-util.ts#L57-L63) when the parent view is `LayoutBase` (which is the case with ParalaxView). The reason: they accept `index` parameter and the `_addChildFromBuilder` does not.

Here are some suggestions: You can pass [additional metadata](https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/element-registry.ts#L6-L10) when registering your component with [`registerElement`](https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/element-registry.ts#L30) where you can override the `insertChild` and `removeChild` hooks which will be used inside the renderer. 

One other suggestion: you can expose properties of the (`header`, `anchor`, `content`) and set those directly inside the  `_addChildFromBuilder` and `insertChild` hooks. 

Last thing: In Angluar components usually the `loaded` event is fired before the children are added (in vanilla {N} this could also happen if you are adding children dynamically). So you might have to change the code of the [nativescript-parallax](https://github.com/TheOriginalJosh/nativescript-parallax) plugin to handle that case.

**Comment by vakrilov** [comment]
@TheOriginalJosh 
I'm closing the issue for now. Please, feel free to reopen it again, if the metadata hooks are not sufficient to implement the plugin.

**Comment by TheOriginalJosh** [comment]
@vakrilov I had actually figured out a way around using _addChildFromBuilder however no success still. registerElement didn't seem to want to work with adding the multiple child elements. of header and content. 

Any suggestions on how to maybe restructure the plugin? Should I open a new issue?  

Thanks for your help.

**Comment by vakrilov** [comment]
Yes - you can open another issue and elaborate a bit more on the problem
