### ISSUE TITLE
Nativescript-vue CLI getting stuck when trying to create project

### ISSUE THREAD

**Issue by tomkochi** [NativeScript/nativescript-angular#1871]
Everything was working fine until recently. Now, whenever trying to create project, it got stuck at
```? Project description (A native application built with NativeScript-Vue)```

Can't type a description, or continue (``Enter key``). No input is possible. Not even ``ctrl+c``.

CLI successfully reinstalled a few times via ``npm install -g @vue/cli @vue/cli-init``. Ran ``tns doctor'``. No Errors - everything is fine.

I had projects already done. When I try to run ``tns run ios --bundle``, ```$ tns run ios --bundle
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Skipping prepare.
Unable to apply changes on device: C7CAE2E0-F26B-445E-AE65-BC28B6EC3358. Error is: cp: no such file or directory: testProject/platforms/ios/testProject/app/*.```

Some times the error will be
```Unable to apply changes on device: 532EF6C1-B8A9-4BD7-9B62-267B0BD458DD. Error is: Cannot read property 'env' of undefined.```

When I try ``tns run android --bundle`` it says

```BUILD FAILED in 2m 47s
Unable to apply changes on device: TA09404OBE. Error is: Command ./gradlew fail
ed with exit code 1.```.

Some times the error will be
```Unable to apply changes on device: 532EF6C1-B8A9-4BD7-9B62-267B0BD458DD. Error is: Cannot read property 'env' of undefined.```


I tried removing ``node_modules`` and ``platforms`` folders. No luck.

I am stuck at everything. Please help.

**Comment by VladimirAmiorkov** [comment]
Hi @tomkochi ,

This repository is related to `nativescript-angular` and is not connected to the `nativescript-vua` repository. I would suggest you to bring up this issue [here](https://github.com/nativescript-vue/nativescript-vue/issues).
