### ISSUE TITLE
ListViewGridLayout's itemHeight doesn't change when bound in html file

### ISSUE THREAD

**Issue by elonmallin** [NativeScript/nativescript-angular#1876]
`ListViewGridLayout`s `itemHeight` attribute won't update the items height when it's updated by a one-way bound value.

**Steps to reproduce:**
1. Have a `RadListView` with a `ListViewGridLayout` like below:
```
<RadListView [items]="products">
      <ListViewGridLayout #listViewGridLayout tkListViewLayout [itemHeight]="rowHeight"></ListViewGridLayout>
      <ng-template let-item="item">
        ...
      </ng-template>
    </RadListView>
```
2. Change the `rowHeight` in TypeScript.
3. See that the items height in the list doesn't change.

**Doing it in the code-behind works however:**
If you directly access `#listViewGridLayout` in TypeScript like this it works.
```
@ViewChild('listViewGridLayout') listViewGridLayout: ElementRef;
...
let layout: ListViewGridLayout = this.listViewGridLayout.nativeElement;
layout.itemHeight = 123; // This works.
```

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-ui-feedback #1163](https://github.com/NativeScript/nativescript-ui-feedback/issues/1163) via [**ZenHub**](https://www.zenhub.com/)
