### ISSUE TITLE
Text Masking support in NativeScript Angular

### ISSUE THREAD

**Issue by M-kothakapu** [NativeScript/nativescript-angular#1877]
**Is your feature request related to a problem? Please describe.**

Hi, I'm looking to create an SSN masking for text field using asterisk `*`. For example, I want to mask my ssn text field as `***-**-***`.

 I haven't found any sample in the documentation https://github.com/PeterStaev/nativescript-masked-text-field . Could you please provide me few ideas to generate a text masking for `ssn` using `*
`.

**Comment by tsonevn** [comment]
Hi @M-kothakapu,
The `nativescript-masked-text-field` plugin does not seem to provide similar functionality. On that matter, I would suggest logging a [new feature request ](https://github.com/PeterStaev/nativescript-masked-text-field/issues) in its repository. Meanwhile, you can try attaching to the textChange event and try to modify the text.  For example:
```HTML
<MaskedTextField  class="input input-border" mask="(999) 999-9999" secure="false" updateTextTrigger="textChanged" [(ngModel)]="value" (textChange)="txtChange()"  keyboardType="phone"></MaskedTextField>
```
```TypeScript
txtChange(){
        
        setTimeout(() => {
            console.log(this.value);
        }, 100);
       
    }
```

Keep in mind that I haven't tested this solution and can not guarantee that it will work properly. Also for further questions, please use our SO [thread here ](https://stackoverflow.com/questions/tagged/nativescript) or contact the author by opening a [new issue](https://github.com/PeterStaev/nativescript-masked-text-field/issues). This repository is used only for bug reporting and feature requests related to nativescript-angular.

**Comment by M-kothakapu** [comment]
I tried the above solution. It's not productive. Maybe as you have said I should post this issue in the actual repository.

**Comment by detective-kenedi-novriansyah** [comment]
I think nativescript is very bad, what I'm saying is bad, because all packages from nativescript are not supported and many are wrong, and then this is not recommended for beginners, first I think it's a good programming language, and I want to learn nativescript , every time I solve a problem and the time I encounter a difficult problem
