### ISSUE TITLE
[Tabs] TabStripItem does not render

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-angular#1884]
**Environment**
 - nativescript-angular: 8.0.2-rc-2019-07-01-155323-01
 
**Describe the bug**

A `TabStripItem` with a `Label` and an `Image` does not render.

**To Reproduce** - a [sample tabs component](https://github.com/NativeScript/nativescript-angular/commit/dd04f793f074202e8308ee0ceef6e4aca15993e2#diff-0778d5170e7ef0c5d0b464e15b5d297cR13).

**Expected**

All three items render with a title and an image.

**Actual**

![Screenshot_1561996640](https://user-images.githubusercontent.com/12251337/60450690-0f91f680-9c33-11e9-9cb3-6bf7abf475c3.png)

**Comment by MartoYankov** [comment]
This appears to be fixed now.
