### ISSUE TITLE
[BottomNavigation] Binding inside BottomNavigation/Tabs will work only if wrapped in NgZone

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#1896]
Steps to reproduce:

- [Use this example ](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/niliev/bottom/app/ng-ui-widgets-category/bottom-navigation/events)with `BottomNavigation` or `Tabs` (NativeScript 6)

- [Observe the binding for `selectedIndex`](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/niliev/bottom/app/ng-ui-widgets-category/bottom-navigation/events/events.component.html#L13)

Behavior: [The Angular binding will work only when wrapped in the Angular zone](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/niliev/bottom/app/ng-ui-widgets-category/bottom-navigation/events/events.component.ts#L25-L28). Remove the NgZone and the binding won't update the UI (on `selectedIndexChanged` event).

Related to [https://github.com/NativeScript/NativeScript/issues/6967](https://github.com/NativeScript/NativeScript/issues/6967)

**Comment by MartoYankov** [comment]
We discussed this and it's actually expected and not connected to the `BottomNavigation` widget. All UI components event handlers are automatically wrapped in the zone when they are declared in the markup. This is not the case when event handlers are declared in the code-behind via the `on` API. The problem arises only with events that are fired from native code or callbacks called from a native code.

A possible solution would be to patch the Observable class in nativescript-angular to automatically wrap the `on` callback in the zone. Perhaps we should discuss this further with @VladimirAmiorkov and @vakrilov and log a new issue.

For the time being, we agreed to document this where needed.
