### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#19]
Support animations in the renderer and see how stuff like ngAnimate 2.0 fits in the big picture.

**Comment by hdeshev** [comment]
The latest plans are to support CSS-based animations in the core NativeScript modules framework first.

**Comment by hdeshev** [comment]
CSS animations will ship after {N} 1.7. We're still waiting for the animation changes to the ng2 Renderer API.

**Comment by vakrilov** [comment]
Some more demos on animations for @matsko that he used for his talk in ng-conf:
https://github.com/matsko/ng-conf-demos

**Comment by hdeshev** [comment]
Closing. Animations fully supported in 1.0.0

**Comment by IvRRimum** [comment]
What animations? Where's the documentation?

**Comment by tzraikov** [comment]
@IvRRimum: We integrate Angular animations, so all animations possible with Angular 2 web are also possible with {N}. You can use as reference the official Angular documentation: [Animations](https://angular.io/docs/ts/latest/guide/animations.html).
Some examples are included in the ng-sample application: [ng-sample](https://github.com/NativeScript/nativescript-angular/tree/master/ng-sample)
