### ISSUE TITLE
How can I set multiple action items inside an action bar?

### ISSUE THREAD

**Issue by ashhadaimviz** [NativeScript/nativescript-angular#1904]
I want a menu bar icon at left,one label in center and finally another add icon which will open the modal but I am facing an issue that add icon is placed at left over menu bar icon every time 
I tried android.position, a stacklayout inside but still the same issue
Thank you if any one can solve it?

**Comment by tsonevn** [comment]
Hi @ashhadaimviz,
For `How to` related questions, please use our [StackOverflow thread here](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests connected to {N} Angular.
