### ISSUE TITLE
How can I add a white board to my NativeScript-Angular mobile/website app?

### ISSUE THREAD

**Issue by rezaee** [NativeScript/nativescript-angular#1905]
Sorry if I ask my question in a wrong place. What I want to do is adding a whiteboard  to my NativeScript-Angular mobile/website app like other LMS systems like Adobe Connect for example. How can I create a multiplatform LMS using NativeScript-Angular? Is there any tools like whiteboard for it?

**Comment by tsonevn** [comment]
Hi @rezaee,
For `How to` related questions, please use our [StackOverflow thread here](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reporting and feature requests connected to {N} Angular.
