### ISSUE TITLE
Nativescript 6 Angular animations crushs the app

### ISSUE THREAD

**Issue by yonkoGH** [NativeScript/nativescript-angular#1916]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.1
 - Cross-platform modules: 6.0.1
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.1
 - Plugin(s): NSPlayground default plugins
 - NativeScript-Angular:
 - Angular: 8.0.3
 
**Describe the bug**
the application crushes when i use angular animation and the log gives me this message :

> JS ERROR TypeError: undefined is not an object (evaluating 'nativeView.layer')

**To Reproduce**
back and forth between the home page and the animation page in the sample app below

**Sample project**
https://play.nativescript.org/?template=play-ng&id=NF5zUl&v=3

**Additional context**
I'm having this same problem since Nativescript 5.4 
+
on IOS only (didn't try it on Android)

**Comment by tsonevn** [comment]
Hi @yonkoGH,
I tested the project on iPhone SE (iOS 11.0.1), iPhone 7 (iOS 12.4), iPhone Xr(iOS 12.1), however, was unable to recreate the problem. On that matter, can you provide more info about the exact steps that you are using for recreating the problem as well as more info about the device or simulator, that you are using for testing?

**Comment by yonkoGH** [comment]
Here is another version of the sample . 
[https://play.nativescript.org/?template=play-ng&id=NF5zUl&v=5](url)

You have to navigate several times between the two pages 

Also i'm using IPhone 7 with IOS 12.3.1 for testing.
BR,,

**Comment by tsonevn** [comment]
Hi @yonkoGH,
Excuse me for the delay in reply.
Can you check if you will be able to recreate the problem while using the latest `tns-core-modules` (v `6.0.4`)?

**Comment by yonkoGH** [comment]
same ! in 6.0.4

**Comment by tsonevn** [comment]
Hi @yonkoGH,
I've rechecked the attached project, however, I am still unable to recreate the problem on iOS. Are there any specific steps that I should follow to reproduce the issue?
