### ISSUE TITLE
Warning: When used inside StackLayout with vertical orientation, RadListView should have an explicit height

### ISSUE THREAD

**Issue by NikhilAkorde** [NativeScript/nativescript-angular#1917]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  "8.0.0",
 - Cross-platform modules:
 - Android Runtime:"6.0.0
 - iOS Runtime:"6.0.1"
 - Plugin(s): "7.0.1","nativescript-ui-listview"
 - NativeScript-Angular:6.0.1
 - Angular:8
 
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by tgpetrov** [comment]
@NikhilAkorde 
This is expected. The warning is self-explanatory - you should restrict the height of RadListView, in order to avoid bad performance, caused by RadListView having infinite size and trying to layout all of its items.
