### ISSUE TITLE
@angular/compiler-cli and @ngtools/webpack are not updated by update script

### ISSUE THREAD

**Issue by elena-p** [NativeScript/nativescript-angular#1924]
**Describe the bug**
dev dependencies @angular/compiler-cli and @ngtools/webpack are not updated by nativescript-angular update script

**To Reproduce**
npm i nativescript@6.0.0 -g
tns create --ng // angular dependencies are ~8.0.0
cd your-app-name
npm i nativescript-angular@8.1.0-next-2019-07-26-145152-01 --save 
 ./node_modules/.bin/update-app-ng-deps

angular dependencies are updated to ~8.1.0
@angular/compiler-cli and @ngtools/webpack are **NOT** updated

**Expected behavior**
all angular dependencies should be updated

**Comment by NickIliev** [comment]
As far as I know, the `nativescript-dev-webpack` is responsible for fo updating those two. Running the webpack update script should do the job (at least It was how things were working up to this moment)

```
./node_modules/.bin/update-ns-webpack --deps
```
