### ISSUE TITLE
Button tap event runs twice

### ISSUE THREAD

**Issue by valera1401** [NativeScript/nativescript-angular#1931]
**Environment**
 - NativeScript-Angular: 5.4
 
**Describe the bug**
Tap event runs twice on button double tap.

Created blank angular app 

`<GridLayout class="page">
    <Button (tap)="onButtonTap()"></Button>
</GridLayout>`

    async onButtonTap() {
        await dialogs.alert("Alert");
    }

Double tap on the button quickly. 
Sometimes tap event runs twice. 

Sometimes second tap is intercepted by the alert dialog (first tap opens the dialog and second tap closes it) as expected, sometimes it's not and onButtonTap method runs twice.

**Comment by tsonevn** [comment]
Hi @valera1401,
I've checked the case on my side, however, was unable to recreate a problem with the tap event with latest {N} (v`6.0`). On that matter, can you test with the most recent {N} version? Also, can you provide more info about the device/emulator that you are using for testing?

**Comment by valera1401** [comment]
Hi @tsonevn ,
Thank you for your response. 
ok I will check it with NS 6 in a few days.

**Comment by valera1401** [comment]
Unfortunately I've reproduced the issue with the NS 6.0.3
Clean NS install.
Created a new project with tns create --ng command
I'm using the Android studio Android emulator (Android 9 API 28) and I saw that the issue was reproduced on the Samsung S10 as well.

**Comment by NickIliev** [comment]
@valera1401 why are you using async/await for a UI interaction in the first place?

**Comment by valera1401** [comment]
@NickIliev In the real app I need to retrieve a result from the dialog.

**Comment by NickIliev** [comment]
@valera1401 that's pretty common but still, I don't see why you need to create async/await for the UI interaction.
