### ISSUE TITLE
Nativescript - Angular ListView Scrolling lags in ios

### ISSUE THREAD

**Issue by Puru0911** [NativeScript/nativescript-angular#1932]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0
 - Cross-platform modules:
 - Android Runtime:6.0
 - iOS Runtime:6.0
 - Plugin(s):
 - NativeScript-Angular:6
 - Angular:6
 
**Describe the bug**
I'm using ListView with multiple template and I have multidimensional array. In templates I used ngFor to render my dynamic data. I don't know it's ngFor or something else but after data is appended in listview scrolling lags

**Comment by NickIliev** [comment]
@Puru0911 hard to say what exactly is happening without a sample project but my guess is that you are probably breaking the recycling and the virtualization by using `ngFor` or other structural directives inside the item templates. [See this blog post](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f) about more details related to that topic.

**Comment by Puru0911** [comment]
@NickIliev Please look at the below code for more clarity. I have used same post to develop my code

<StackLayout class="cbMain" row="1" #chatbox  iosOverflowSafeArea="false"> 
        
            
                <ListView [items]="messages"  separatorColor="transparent" class="cbArea" #listView [itemTemplateSelector]="templateSelector" height="100%" iosOverflowSafeArea="false">
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="user">   
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <DockLayout class="cbUserSays" width="100%" stretchLastChild="false" iosOverflowSafeArea="false">
                                <StackLayout class="cbDP" flexShrink="0" dock="right" iosOverflowSafeArea="false">
                                    <StackLayout iosOverflowSafeArea="false">
                                        <Image src="~/images/78.jpg" class="cbDPpic" iosOverflowSafeArea="false"></Image>  
                                    </StackLayout>    
                                </StackLayout>
                                <StackLayout class="cbContent" dock="right" iosOverflowSafeArea="false">
                                    
                                        <StackLayout class="cbInstChat" iosOverflowSafeArea="false">
                                            <Label [text]="message.responses" textWrap="true" iosOverflowSafeArea="false"></Label>
                                        </StackLayout>
                                    
                                </StackLayout>
                            </DockLayout>
                        </GridLayout>
                    </ng-template>
                    
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="bot_preBotOptions">
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <DockLayout class="preBotOptions" orientation="horizontal" stretchLastChild="true" iosOverflowSafeArea="false">
                                <StackLayout flexShrink="0" dock="left" iosOverflowSafeArea="false">
                                    <StackLayout class="cbDP" iosOverflowSafeArea="false">
                                        <Image src="~/images/midnay-logo-icon.png"  class="cbDPpic" iosOverflowSafeArea="false"></Image>  
                                    </StackLayout>    
                                </StackLayout>
                                <StackLayout class="cbContent" dock="left" iosOverflowSafeArea="false">
                                    <ng-template ngFor let-response [ngForOf]="message.responses">
                                        <FlexboxLayout class="cbInstChatDiv" width="100%" iosOverflowSafeArea="false" [visibility]="response!='typing' ? 'visible' : 'collapse'">
                                            <FlexboxLayout iosOverflowSafeArea="false"> 
                                                <Label [text]="response" textWrap="true" class="cbInstChat" iosOverflowSafeArea="false"></Label>
                                            </FlexboxLayout>
                                        </FlexboxLayout>
                                        <FlexboxLayout class="cbInstChatDiv" [visibility]="response=='typing' ? 'visible' : 'collapse'">
                                            <Gif src="~/images/ball-lodaer.gif" height="50" loaded="gifLoaded"></Gif>
                                        </FlexboxLayout>
                                    </ng-template>    
                                </StackLayout>
                            </DockLayout>
                        </GridLayout>    
                    </ng-template>
                    
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="bot_botOptions_topic">
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <StackLayout class="botOptions" iosOverflowSafeArea="false">
                                <StackLayout class="cbContent" iosOverflowSafeArea="false">
                                    <WrapLayout orientation="horizontal" class="cbInstChat typeLinks" iosOverflowSafeArea="false">
                                        <ng-template ngFor let-response [ngForOf]="message.responses" let-contentIndex="index">
                                            <Label [text] = "response.title" textWrap="false" [ngClass]="{'selected' : response.selected}" (tap)="sendMessageWithIntent(response.payload,response.title,msgIndex,contentIndex)" iosOverflowSafeArea="false"></Label> 
                                        </ng-template>
                                    </WrapLayout>
                                </StackLayout>
                            </StackLayout>
                        </GridLayout>
                    </ng-template>
                    
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="bot_botOptions_category">
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <StackLayout class="botOptions" iosOverflowSafeArea="false">
                                <StackLayout class="cbContent" iosOverflowSafeArea="false">
                                    <ScrollView orientation="horizontal" hideScrollBar iosOverflowSafeArea="false"> 
                                        <StackLayout orientation="horizontal" class="cbInstChat typeLinks" iosOverflowSafeArea="false">
                                            <ng-template ngFor let-response [ngForOf]="message.responses" let-contentIndex="index">
                                                <Label [text] = "response.title" textWrap="false" [ngClass]="{'selected' : response.selected}" (tap)="sendMessageWithIntent(response.payload,response.title,msgIndex,contentIndex)" iosOverflowSafeArea="false"></Label> 
                                            </ng-template>    
                                        </StackLayout>
                                    </ScrollView>
                                </StackLayout>
                            </StackLayout>
                        </GridLayout>
                    </ng-template>
                    
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="bot_botOptions_content">
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <StackLayout class="botOptions" iosOverflowSafeArea="false">
                                <StackLayout class="cbContent" iosOverflowSafeArea="false">
                                    <StackLayout  class="cbInstChat typeCards" iosOverflowSafeArea="false">
                                        <ScrollView orientation="horizontal"  hideScrollBar iosOverflowSafeArea="false">
                                            <StackLayout class="cardStack" justifyContent="space-between" orientation="horizontal" iosOverflowSafeArea="false">
                                                
                                                <ng-template ngFor let-response [ngForOf]="message.responses">
                                                    <StackLayout class="card" [width]=cardWidth (tap)="showModal(response.url,response.title,response.video_id)" iosOverflowSafeArea="false">                                  
                                                        <WebImage [src]= "response.thumbnail" stretch="aspectFit" placeholder="~/images/ironman.jpg" iosOverflowSafeArea="false"></WebImage>
                                                        <StackLayout class="cardInfo" iosOverflowSafeArea="false"> 
                                                            <Label [text] = "response.title" textWrap="true" class="h3" iosOverflowSafeArea="false"></Label>
                                                            <Label text="youtube.com" class="small" iosOverflowSafeArea="false"></Label> 
                                                        </StackLayout> 
                                                    </StackLayout>    
                                                </ng-template>    
                                            </StackLayout>
                                        </ScrollView>                                      
                                    </StackLayout>
                                </StackLayout>
                            </StackLayout>
                        </GridLayout>
                    </ng-template>   
                   
                </ListView>   
            
        
    </StackLayout>

**Comment by Puru0911** [comment]
@NickIliev Please look at the below code for more clarity. I have used same post to develop my code

`<StackLayout class="cbMain" row="1" #chatbox  iosOverflowSafeArea="false"> 
        
            
                <ListView [items]="messages"  separatorColor="transparent" class="cbArea" #listView [itemTemplateSelector]="templateSelector" height="100%" iosOverflowSafeArea="false">
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="user">   
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <DockLayout class="cbUserSays" width="100%" stretchLastChild="false" iosOverflowSafeArea="false">
                                <StackLayout class="cbDP" flexShrink="0" dock="right" iosOverflowSafeArea="false">
                                    <StackLayout iosOverflowSafeArea="false">
                                        <Image src="~/images/78.jpg" class="cbDPpic" iosOverflowSafeArea="false"></Image>  
                                    </StackLayout>    
                                </StackLayout>
                                <StackLayout class="cbContent" dock="right" iosOverflowSafeArea="false">
                                    
                                        <StackLayout class="cbInstChat" iosOverflowSafeArea="false">
                                            <Label [text]="message.responses" textWrap="true" iosOverflowSafeArea="false"></Label>
                                        </StackLayout>
                                    
                                </StackLayout>
                            </DockLayout>
                        </GridLayout>
                    </ng-template>
                    
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="bot_preBotOptions">
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <DockLayout class="preBotOptions" orientation="horizontal" stretchLastChild="true" iosOverflowSafeArea="false">
                                <StackLayout flexShrink="0" dock="left" iosOverflowSafeArea="false">
                                    <StackLayout class="cbDP" iosOverflowSafeArea="false">
                                        <Image src="~/images/midnay-logo-icon.png"  class="cbDPpic" iosOverflowSafeArea="false"></Image>  
                                    </StackLayout>    
                                </StackLayout>
                                <StackLayout class="cbContent" dock="left" iosOverflowSafeArea="false">
                                    <ng-template ngFor let-response [ngForOf]="message.responses">
                                        <FlexboxLayout class="cbInstChatDiv" width="100%" iosOverflowSafeArea="false" [visibility]="response!='typing' ? 'visible' : 'collapse'">
                                            <FlexboxLayout iosOverflowSafeArea="false"> 
                                                <Label [text]="response" textWrap="true" class="cbInstChat" iosOverflowSafeArea="false"></Label>
                                            </FlexboxLayout>
                                        </FlexboxLayout>
                                        <FlexboxLayout class="cbInstChatDiv" [visibility]="response=='typing' ? 'visible' : 'collapse'">
                                            <Gif src="~/images/ball-lodaer.gif" height="50" loaded="gifLoaded"></Gif>
                                        </FlexboxLayout>
                                    </ng-template>    
                                </StackLayout>
                            </DockLayout>
                        </GridLayout>    
                    </ng-template>
                    
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="bot_botOptions_topic">
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <StackLayout class="botOptions" iosOverflowSafeArea="false">
                                <StackLayout class="cbContent" iosOverflowSafeArea="false">
                                    <WrapLayout orientation="horizontal" class="cbInstChat typeLinks" iosOverflowSafeArea="false">
                                        <ng-template ngFor let-response [ngForOf]="message.responses" let-contentIndex="index">
                                            <Label [text] = "response.title" textWrap="false" [ngClass]="{'selected' : response.selected}" (tap)="sendMessageWithIntent(response.payload,response.title,msgIndex,contentIndex)" iosOverflowSafeArea="false"></Label> 
                                        </ng-template>
                                    </WrapLayout>
                                </StackLayout>
                            </StackLayout>
                        </GridLayout>
                    </ng-template>
                    
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="bot_botOptions_category">
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <StackLayout class="botOptions" iosOverflowSafeArea="false">
                                <StackLayout class="cbContent" iosOverflowSafeArea="false">
                                    <ScrollView orientation="horizontal" hideScrollBar iosOverflowSafeArea="false"> 
                                        <StackLayout orientation="horizontal" class="cbInstChat typeLinks" iosOverflowSafeArea="false">
                                            <ng-template ngFor let-response [ngForOf]="message.responses" let-contentIndex="index">
                                                <Label [text] = "response.title" textWrap="false" [ngClass]="{'selected' : response.selected}" (tap)="sendMessageWithIntent(response.payload,response.title,msgIndex,contentIndex)" iosOverflowSafeArea="false"></Label> 
                                            </ng-template>    
                                        </StackLayout>
                                    </ScrollView>
                                </StackLayout>
                            </StackLayout>
                        </GridLayout>
                    </ng-template>
                    
                    <ng-template  let-message="item" let-msgIndex="index" nsTemplateKey="bot_botOptions_content">
                        <GridLayout iosOverflowSafeArea="false" itemHeight>
                            <StackLayout class="botOptions" iosOverflowSafeArea="false">
                                <StackLayout class="cbContent" iosOverflowSafeArea="false">
                                    <StackLayout  class="cbInstChat typeCards" iosOverflowSafeArea="false">
                                        <ScrollView orientation="horizontal"  hideScrollBar iosOverflowSafeArea="false">
                                            <StackLayout class="cardStack" justifyContent="space-between" orientation="horizontal" iosOverflowSafeArea="false">
                                                
                                                <ng-template ngFor let-response [ngForOf]="message.responses">
                                                    <StackLayout class="card" [width]=cardWidth (tap)="showModal(response.url,response.title,response.video_id)" iosOverflowSafeArea="false">                                  
                                                        <WebImage [src]= "response.thumbnail" stretch="aspectFit" placeholder="~/images/ironman.jpg" iosOverflowSafeArea="false"></WebImage>
                                                        <StackLayout class="cardInfo" iosOverflowSafeArea="false"> 
                                                            <Label [text] = "response.title" textWrap="true" class="h3" iosOverflowSafeArea="false"></Label>
                                                            <Label text="youtube.com" class="small" iosOverflowSafeArea="false"></Label> 
                                                        </StackLayout> 
                                                    </StackLayout>    
                                                </ng-template>    
                                            </StackLayout>
                                        </ScrollView>                                      
                                    </StackLayout>
                                </StackLayout>
                            </StackLayout>
                        </GridLayout>
                    </ng-template>   
                   
                </ListView>  `

**Comment by NickIliev** [comment]
Why are you using such excessive nesting in the first place? The more layouts are nested - the heavier your UI gets - the slower the rendering. Keep in mind that the UI rendering will happen on cell creation so when the user scrolls the list view it will have to render the UI and also apply the nested ngFor loops.

Look just at one of your item templates ...
```
<GridLayout iosOverflowSafeArea="false" itemHeight>
    <StackLayout class="botOptions" iosOverflowSafeArea="false">
        <StackLayout class="cbContent" iosOverflowSafeArea="false">
            <StackLayout  class="cbInstChat typeCards" iosOverflowSafeArea="false">
                <ScrollView orientation="horizontal"  hideScrollBar iosOverflowSafeArea="false">
                    <StackLayout class="cardStack" justifyContent="space-between" orientation="horizontal" iosOverflowSafeArea="false">
                        <!-- <CardView [width]='cardWidth' [responses]='message.responses' ></CardView> -->
                        <ng-template ngFor let-response [ngForOf]="message.responses">
                            <StackLayout class="card" [width]=cardWidth (tap)="showModal(response.url,response.title,response.video_id)" iosOverflowSafeArea="false">                                  
                                <WebImage [src]= "response.thumbnail" stretch="aspectFit" placeholder="~/images/ironman.jpg" iosOverflowSafeArea="false"></WebImage>
                                <StackLayout class="cardInfo" iosOverflowSafeArea="false"> 
                                    <Label [text] = "response.title" textWrap="true" class="h3" iosOverflowSafeArea="false"></Label>
                                    <Label text="youtube.com" class="small" iosOverflowSafeArea="false"></Label> 
                                </StackLayout> 
                            </StackLayout>    
                        </ng-template>    
                    </StackLayout>
                </ScrollView>                                      
            </StackLayout>
        </StackLayout>
    </StackLayout>
</GridLayout>
```

Why do you need to nest **GridLayout**  in **StackLayout** in **StackLayout** in **ScrollView** (!?) and then in another **StackLayout** ? An most of those layouts are used only to apply a single CSS sclass. 

Instead of nesting multiple layouts like this
```
<GridLayout iosOverflowSafeArea="false" itemHeight>
    <StackLayout class="botOptions" iosOverflowSafeArea="false">
        <StackLayout class="cbContent" iosOverflowSafeArea="false">
            <StackLayout  class="cbInstChat typeCards" iosOverflowSafeArea="false">
                <ScrollView orientation="horizontal"  hideScrollBar iosOverflowSafeArea="false">
                    <StackLayout class="cardStack" justifyContent="space-between" orientation="horizontal" iosOverflowSafeArea="false">
```

You could apply the CSS style on a single layout
```
<StackLayout class="botOptions cbContent cbInstChat typeCards" >
```

You don't need `iosOverflowSafeArea` set to **false** as this the default value for all views in NativeScript.


Btw. I would avoid creating a ngFor loos inside the ListView item templates as again - this could break the ListView recycling and virtualization (see the linked blog post). If you are trying to create a chat like UI then see [this blog post](https://www.nativescript.org/blog/create-a-realtime-chat-interface-with-firebase-and-angular) and [other available solutions posted online](https://www.google.com/search?q=nativescript+chat&rlz=1C1CHBF_enBG781BG781&oq=nativescript+chat&aqs=chrome..69i57j0l5.2127j0j7&sourceid=chrome&ie=UTF-8)

**Comment by Puru0911** [comment]
Hi @NickIliev I also don't want to use ngFor in ListView but our design asks for it . can you please share an alternative if you know any

**Comment by kanika-webosmotic** [comment]
I am facing similar issue. I have a timeline for posts in my Nativescript+Angular app that has post content, media, comments, replies, etc. The list is very slow and laggy on scrolling. Any solution for this?

**Comment by NathanWalker** [comment]
Hi @kanika-webosmotic make sure using template selectors as mentioned in this post:
https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f

For further help you can share your template setup in the community discord: https://nativescript.org/discord
Everyone is very helpful there.
