### ISSUE TITLE
Revert back to normal Nativescript project

### ISSUE THREAD

**Issue by ishaqueahmed-mev** [NativeScript/nativescript-angular#1934]
Hello,

I need to revert back from the shared NS project in angular to normal NS app, which it previously was, but I don't know how do I revert it back.

Any help would be much appreciated...

**Comment by NickIliev** [comment]
@ishaqueahmed-mev I guess [you have created a Code Shared project](https://docs.nativescript.org/angular/code-sharing/creating-a-new-project) that combines web project with a NativeScript project. If that is the case, you have ended up with a single folder that contains your Angular files for the web and your Angular files for the NativeScript app (which files names are ending with **_*.tns.ts_**).

If that is the case, then you need to manually revert to NativeScripty only project. What I would do is to create a new Angular project
```
tns create my-new-ng-proj --ng
```

and from there to migrate the content of the ***.tns** files into your new project (where the files are no longer ending in ***.tns**).

**Comment by ishaqueahmed-mev** [comment]
@NickIliev thanks for the info. I also thought that this could be the only way, and I have done the exact same way as you said and now its working fine.

Thanks
