### ISSUE TITLE
Not able to run App after migrated to NativeScript 6.0.3 version Getting error like TypeError: Cannot read property 'R' of undefined

### ISSUE THREAD

**Issue by kranthi-kiki** [NativeScript/nativescript-angular#1936]
ActivityManager: Start proc 24307:com.dev.totmaster.parent/u0a273 for activity com.dev.totmaster.parent/com.tns.NativeScriptActivity
Successfully synced application com.dev.totmaster.parent on device 192.168.56.109:5555.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
**System.err: TypeError: Cannot read property 'R' of undefined**
System.err: File: "file:///node_modules/nativescript-snackbar/snackbar.js:160:0
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///node_modules/nativescript-snackbar/snackbar.js:160:0
System.err: 	Frame: function:'', file:'file:///node_modules/nativescript-snackbar/snackbar.js:163:1
System.err: 	Frame: function:'../node_modules/nativescript-snackbar/snackbar.js', file:'file:///data/data/com.dev.totmaster.parent/files/app/vendor.js', line: 100555, column: 30
System.err: 	Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err: 	Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err: 	Frame: function:'./app/utils/index.ts', file:'file:///src/app/utils/index.ts:1:0
System.err: 	Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err: 	Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err: 	Frame: function:'./app/pages/modal-dialog/modal-dialog.ts', file:'file:///src/app/pages/modal-dialog/modal-dialog.ts:1:0
System.err: 	Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err: 	Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err: 	Frame: function:'./app/app.module.ts', file:'file:///src/app/app.module.ts:1:0
System.err: 	Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err: 	Frame: function:'fn', file:'file:///src/webpack/bootstrap:120:0
System.err: 	Frame: function:'', file:'file:///data/data/com.dev.totmaster.parent/files/app/bundle.js', line: 2478, column: 73
System.err: 	Frame: function:'./main.ts', file:'file:///data/data/com.dev.totmaster.parent/files/app/bundle.js', line: 2555, column: 30
System.err: 	Frame: function:'__webpack_require__', file:'file:///src/webpack/bootstrap:750:0
System.err: 	Frame: function:'checkDeferredModules', file:'file:///src/webpack/bootstrap:43:0
System.err: 	Frame: function:'webpackJsonpCallback', file:'file:///src/webpack/bootstrap:30:0
System.err: 	Frame: function:'', file:'file:///data/data/com.dev.totmaster.parent/files/app/bundle.js', line: 2, column: 57
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: TypeError: Cannot read property 'R' of undefined
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'R' of undefined
System.err: File: "file:///node_modules/nativescript-snackbar/snackbar.js:160:0
System.err: StackTrace:

**Comment by nmandyam** [comment]
Exactly the same thing happens to me, too, since I'm also using SnackBar.

**Comment by nmandyam** [comment]
Prefix "@nstudio/" to the declarations of SnackBar in all JS and XML and in package.json; do an npm -i. All good.

**Comment by meysam-mahmoodi** [comment]
To solve the problem, as @nmandyam mentioned, you should install new plugin: `tns plugin add @nstudio/nativescript-snackbar` then change the declarations of SnackBar to `@nstudio/nativescript-snackbar` so everything is going to ok.
