### ISSUE TITLE
Tns migrate failing. One package is missing

### ISSUE THREAD

**Issue by felixelgato92** [NativeScript/nativescript-angular#1948]
**Environment**
tns version: 6.0.3
npm version: 6.4.1

**Describe the bug**
Tns migrate command is failing with: 
Could not migrate the project! The error is: Error: Command npm failed with exit code 1

npm ERR! code ETARGET
npm ERR! notarget No matching version found for `@angular/http@8.0.0-beta.10`

If I run npm install @angular/http@latest, it installs version 7.2.15. I'm not sure why `tns migrate` is trying to update to a beta version or if that's the expected behavior. 

**To Reproduce**
Add a @angular/http to your package.json file and run `tns migrate`

**Expected behavior**
tns migrate command works

**Comment by tsonevn** [comment]
Hi @felixelgato92,
This is the expected behaviour. The migrate command will add `8.0.0-beta.10` versions for `@angular/http`, which is the compatible version for the latest `nativescript-angular`. You can check [here](https://github.com/NativeScript/nativescript-cli/blob/master/lib/controllers/migrate-controller.ts#L403) the packages, that are updated with the command and their versions.

**Comment by felixelgato92** [comment]
Ok, any idea why am I getting: npm ERR! notarget No matching version found for @angular/http@8.0.0-beta.10?

I just updated tns (v 6.0.3), and npm (6.4.1), am I missing something?

**Comment by tsonevn** [comment]
Hi @felixelgato92,
Can you send us the project or at least its `package.json` file?

**Comment by felixelgato92** [comment]
@tsonevn Yeah for sure. I didn't think those would make a difference. We have an interesting structure in our project, where our project(s) reference a common package.json. I have no issues updating the plugins manually, but I'm not sure how to update these files: "webpack.config.js", "karma.conf.js", "tsconfig.tns.json" (as specified in the [docs](https://docs.nativescript.org/tooling/docs-cli/general/migrate) ), plus I'm not sure of what other settings `tns migrate` change under the hood.

**Here is the package.json:**
`{
  "name": "our.company,name",
  "license": "UNLICENSED",
  "version": "1.0.0",
  "nativescript": {
    "id": "our.id",
    "tns-ios": {
      "version": "5.1.0"
    },
    "tns-android": {
      "version": "5.1.0"
    }
  },
  "scripts": {
    "test": "echo 'Unit tests must be run from the root of this repository'"
  },
  "dependencies": {
    "@angular/animations": "file:../../node_modules/@angular/animations",
    "@angular/common": "file:../../node_modules/@angular/common",
    "@angular/compiler": "file:../../node_modules/@angular/compiler",
    "@angular/core": "file:../../node_modules/@angular/core",
    "@angular/forms": "file:../../node_modules/@angular/forms",
    "@angular/platform-browser": "file:../../node_modules/@angular/platform-browser",
    "@angular/platform-browser-dynamic": "file:../../node_modules/@angular/platform-browser-dynamic",
    "@angular/router": "file:../../node_modules/@angular/router",
    "@ngx-translate/core": "file:../../node_modules/@ngx-translate/core",
    "@nrwl/nx": "file:../../node_modules/@nrwl/nx",
    "@xactremodel/core": "file:../../libs/core",
    "@xactremodel/features": "file:../../libs/features",
    "@xactremodel/nativescript": "file:../../xplat/nativescript",
    "@xactremodel/scss": "file:../../libs/scss",
    "@xactremodel/utils": "file:../../libs/utils",
    "apollo-angular": "file:../../node_modules/apollo-angular",
    "apollo-angular-link-http": "file:../../node_modules/apollo-angular-link-http",
    "apollo-cache-inmemory": "file:../../node_modules/apollo-cache-inmemory",
    "apollo-cache-persist": "file:../../node_modules/apollo-cache-persist",
    "apollo-client": "file:../../node_modules/apollo-client",
    "apollo-link": "file:../../node_modules/apollo-link",
    "apollo-link-context": "file:../../node_modules/apollo-link-context",
    "apollo-link-error": "file:../../node_modules/apollo-link-error",
    "apollo-link-http": "file:../../node_modules/apollo-link-http",
    "apollo-link-state": "file:../../node_modules/apollo-link-state",
    "currency-formatter": "file:../../node_modules/currency-formatter",
    "dateformat": "file:../../node_modules/dateformat",
    "fold-to-ascii": "file:../../node_modules/fold-to-ascii",
    "graphql": "file:../../node_modules/graphql",
    "graphql-tag": "file:../../node_modules/graphql-tag",
    "http-status-codes": "file:../../node_modules/http-status-codes",
    "jspdf": "file:../../node_modules/jspdf",
    "jspdf-autotable": "file:../../node_modules/jspdf-autotable",
    "lodash": "file:../../node_modules/lodash",
    "nativescript-angular": "file:../../node_modules/nativescript-angular",
    "nativescript-background-fetch": "file:../../node_modules/nativescript-background-fetch",
    "nativescript-directions": "file:../../node_modules/nativescript-directions",
    "nativescript-drop-down": "file:../../node_modules/nativescript-drop-down",
    "nativescript-email": "file:../../node_modules/nativescript-email",
    "nativescript-floatingactionbutton": "file:../../node_modules/nativescript-floatingactionbutton",
    "nativescript-hockey-sdk": "file:../../node_modules/nativescript-hockey-sdk",
    "nativescript-iqkeyboardmanager": "file:../../node_modules/nativescript-iqkeyboardmanager",
    "nativescript-loading-indicator": "file:../../node_modules/nativescript-loading-indicator",
    "nativescript-ngx-fonticon": "file:../../node_modules/nativescript-ngx-fonticon",
    "nativescript-oauth2": "file:../../node_modules/nativescript-oauth2",
    "nativescript-pdf-view": "file:../../node_modules/nativescript-pdf-view",
    "nativescript-phone": "file:../../node_modules/nativescript-phone",
    "nativescript-platform-css": "file:../../node_modules/nativescript-platform-css",
    "nativescript-purchase": "file:../../node_modules/nativescript-purchase",
    "nativescript-share-file": "file:../../node_modules/nativescript-share-file",
    "nativescript-social-share": "^1.5.1",
    "nativescript-swift-3.0": "file:../../node_modules/nativescript-swift-3.0",
    "nativescript-theme-core": "file:../../node_modules/nativescript-theme-core",
    "nativescript-ui-listview": "^5.0.0",
    "nativescript-ui-sidedrawer": "4.3.0",
    "nativescript-vector-icons": "file:../../node_modules/nativescript-vector-icons",
    "reflect-metadata": "file:../../node_modules/reflect-metadata",
    "rxjs": "file:../../node_modules/rxjs",
    "rxjs-compat": "file:../../node_modules/rxjs-compat",
    "sanitize-filename": "file:../../node_modules/sanitize-filename",
    "tns-core-modules": "file:../../node_modules/tns-core-modules",
    "tslib": "file:../../node_modules/tslib",
    "zone.js": "file:../../node_modules/zone.js"
  },
  "devDependencies": {
    "@angular-devkit/core": "~7.0.4",
    "@angular/compiler-cli": "file:../../node_modules/@angular/compiler-cli",
    "@ngtools/webpack": "file:../../node_modules/@ngtools/webpack",
    "angular-router-loader": "~0.8.1",
    "awesome-typescript-loader": "^5.2.1",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "^3.0.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.19.0",
    "nativescript-worker-loader": "^0.9.2",
    "raw-loader": "~0.5.1",
    "remove-strict-webpack-plugin": "^0.1.2",
    "resolve-url-loader": "~2.2.1",
    "sass-loader": "~7.1.0",
    "terser-webpack-plugin": "^1.2.1",
    "tns-platform-declarations": "file:../../node_modules/tns-platform-declarations",
    "typescript": "file:../../node_modules/typescript",
    "webpack": "^4.10.2",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.1",
    "webpack-parallel-uglify-plugin": "^1.1.0",
    "webpack-sources": "^1.1.0"
  }
}`


**And here is the common package.json:**
`{
  "name": "project.name",
  "version": "0.0.0",
  "license": "UNLICENSED",
  "scripts": {
    "ng": "ng",
    "gulp": "gulp",
    "test": "jest",
    "e2e": "echo \"e2e tests not yet setup\"",
    "affected:apps": "./node_modules/.bin/nx affected:apps",
    "affected:libs": "./node_modules/.bin/nx affected:libs",
    "affected:build": "./node_modules/.bin/nx affected:build",
    "affected:e2e": "./node_modules/.bin/nx affected:e2e",
    "affected:test": "./node_modules/.bin/nx affected:test",
    "affected:lint": "./node_modules/.bin/nx affected:lint",
    "affected:dep-graph": "./node_modules/.bin/nx affected:dep-graph",
    "affected": "./node_modules/.bin/nx affected",
    "format": "./node_modules/.bin/nx format:write",
    "format:write": "./node_modules/.bin/nx format:write",
    "format:check": "./node_modules/.bin/nx format:check",
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
    "workspace-schematic": "./node_modules/.bin/nx workspace-schematic",
    "dep-graph": "./node_modules/.bin/nx dep-graph",
    "help": "./node_modules/.bin/nx help",
    "clean": "npx rimraf hooks node_modules package-lock.json && npm i",
    "start.web.web-xactremodel": "ng serve web-xactremodel"
  },
  "private": true,
  "dependencies": {
    "@ahmadnassri/spawn-promise": "^1.2.0",
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "7.0.4",
    "@angular/compiler": "7.0.4",
    "@angular/core": "^7.2.15",
    "@angular/forms": "7.0.4",
    "@angular/http": "7.0.4",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "7.0.4",
    "@angular/platform-browser-dynamic": "7.0.4",
    "@angular/router": "^7.2.15",
    "@ngx-config/core": "^7.0.0",
    "@ngx-config/http-loader": "^7.0.0",
    "@ngx-translate/core": "~11.0.0",
    "@nrwl/nx": "^7.8.7",
    "@xactremodel/scss": "file:libs/scss",
    "angular-oauth2-oidc": "^5.0.2",
    "apollo-angular": "^1.6.0",
    "apollo-angular-link-http": "^1.8.0",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-cache-persist": "^0.1.1",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.12",
    "apollo-link-context": "^1.0.18",
    "apollo-link-error": "^1.1.11",
    "apollo-link-http": "^1.5.15",
    "apollo-link-state": "^0.4.2",
    "core-js": "^2.6.9",
    "currency-formatter": "^1.5.5",
    "dateformat": "^3.0.3",
    "del": "^3.0.0",
    "fold-to-ascii": "^4.1.2",
    "graphql": "^14.4.2",
    "graphql-tag": "^2.10.1",
    "http-status-codes": "^1.3.2",
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.2.4",
    "lodash": "^4.17.15",
    "nativescript-angular": "7.0.2",
    "nativescript-background-fetch": "^1.2.1",
    "nativescript-directions": "^1.3.1",
    "nativescript-drop-down": "^4.0.1",
    "nativescript-email": "^1.5.5",
    "nativescript-floatingactionbutton": "^4.1.4",
    "nativescript-hockey-sdk": "^1.2.0",
    "nativescript-hook": "^0.2.5",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-loading-indicator": "^2.5.2",
    "nativescript-ngx-fonticon": "^4.2.1",
    "nativescript-oauth2": "1.4.2-propsol.2",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-phone": "^1.4.0",
    "nativescript-platform-css": "^1.6.10",
    "nativescript-purchase": "2.0.11-xr.1",
    "nativescript-share-file": "1.0.4-xr.1",
    "nativescript-social-share": "^1.5.2",
    "nativescript-swift-3.0": "^1.0.0",
    "nativescript-theme-core": "^1.0.6",
    "nativescript-ui-listview": "^5.2.0",
    "nativescript-ui-sidedrawer": "5.0.0",
    "nativescript-vector-icons": "^1.0.0",
    "reflect-metadata": "^0.1.13",
    "roboto-fontface": "^0.10.0",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "sanitize-filename": "^1.6.2",
    "tns-core-modules": "5.2.1",
    "viz": "^0.0.1",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular-devkit/build-ng-packagr": "^0.11.4",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "7.0.4",
    "@angular/language-service": "7.0.4",
    "@fortawesome/fontawesome-pro": "^5.10.1",
    "@ngtools/webpack": "^7.3.9",
    "@nrwl/builders": "7.8.3",
    "@nrwl/schematics": "^7.8.7",
    "@nstudio/schematics": "^7.4.8",
    "@types/currency-formatter": "^1.3.0",
    "@types/graphql": "^14.2.3",
    "@types/jquery": "3.3.6",
    "@types/jspdf": "^1.3.1",
    "@types/lodash": "^4.14.136",
    "@types/node": "^6.14.7",
    "@types/sanitize-filename": "^1.1.28",
    "codelyzer": "^4.5.0",
    "cypress": "3.1.0",
    "hammerjs": "^2.0.8",
    "jasmine": "^3.4.0",
    "jasmine-marbles": "^0.3.1",
    "jest": "^23.6.0",
    "jest-preset-angular": "^5.2.3",
    "jest-teamcity-reporter": "^0.9.0",
    "ng-packagr": "^4.7.1",
    "prettier": "1.10.2",
    "protractor": "~5.1.2",
    "stylelint": "^9.10.1",
    "stylelint-config-standard": "^18.3.0",
    "stylelint-teamcity-reporter": "^1.1.0",
    "tns-platform-declarations": "^3.4.1",
    "ts-node": "~4.1.0",
    "tsickle": "^0.36.0",
    "tslib": "^1.10.0",
    "tslint": "^5.18.0",
    "tslint-eslint-rules": "^5.4.0",
    "tslint-microsoft-contrib": "^5.2.0",
    "tslint-teamcity-reporter": "^2.0.0",
    "typescript": "3.1.6"
  },
  "xplat": {
    "prefix": "xactremodel"
  }
}
`

**Comment by felixelgato92** [comment]
@tsonevn http:
Ok I was looking at this again. Angular 8 has removed that package. From their breaking [changes:](https://github.com/angular/angular/blob/master/CHANGELOG.md) 
> The deprecated @angular/http package has been removed, the @angular/common/http package should be used instead. For details on how to migrate, please refer to the deprecations guide.

It's my understanding that [Nativescript 6](https://www.nativescript.org/blog/announcing-nativescript-6.0---webpack-all-the-way-seamless-app-updates-new-core-theme-and-a-lot-more) supports angular 8.

Do I need to do something different here? Also is there a guide on how to do the steps `tns migrate` does? I tried following the code removing files, directories, and updating dependencies, but it still complains that my project is not compatible with the current version of Nativescript.

**Comment by tsonevn** [comment]
Hi @felixelgato92,
Try to install the latest LTS NodeJS and NPM on your side. Clear up the cache with `npm cache clear --f` and try to run again `tns migrate` command. If the issue still persists, please send us the project, which will help us to investigate further the case.
