### ISSUE TITLE
I am having this issue

### ISSUE THREAD

**Issue by zeeshan-mehdi** [NativeScript/nativescript-angular#1950]
i am facing this  issue while trying to build or run nativescript angular  application
![image](https://user-images.githubusercontent.com/31466216/63219210-4cd02a80-c186-11e9-9ad9-a52b371ccebe.png)
![image](https://user-images.githubusercontent.com/31466216/63219212-548fcf00-c186-11e9-94e9-9f6b24b959c5.png)

**Comment by tsonevn** [comment]
Hi @zeeshan-mehdi,
The given information is not enough to investigate further your case. Please, provide more detailed info about the problem, how you are reproducing it, as well as the full error log. Also send us more info about your environment( CLI, `tns-core-modules`, `tns-android`, `nativescript-angular` versions) and sample project that can be used for recreating the problem.

**Comment by zeeshan-mehdi** [comment]
Thank you @tsonevn  i have resolved the issue the problem was with a checkbox whose value was being picked from a variable which was undefined

**Comment by zeeshan-mehdi** [comment]
**<CheckBox style="  text-align: center; margin-left: 200; " #CB1 text="Remember Me" (checkedChange)="onRem()" class="label" fillColor="black" [checked]="rem" ></CheckBox>**



**

> this checkbox was causing issue

**

this is component.ts code


import { Component, OnInit, AfterViewInit } from "@angular/core";
import { ElementRef, ViewChild } from "@angular/core";
import { DatePicker } from "tns-core-modules/ui/date-picker";
import * as app from "tns-core-modules/application";
import { RouterExtensions } from "nativescript-angular/router";
import { RadSideDrawer } from "nativescript-ui-sidedrawer";
import { getRootView } from "tns-core-modules/application";
import { Page } from "tns-core-modules/ui/page/page";
import { User } from "../models/user.model";
import { LoginService } from "~/shared/login.service";
import { DataService } from "~/shared/Data.service";


@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html",
    styleUrls: ["./home.css"]
})
export class HomeComponent implements OnInit, AfterViewInit {
    public drawer: RadSideDrawer;
    public user: User;
    public rem: Boolean;
    public phone;
    public pass;
    showSpinner: Boolean;

    constructor(private _page: Page, private _loginService: LoginService, private DataService: DataService
        , private routerExtensions: RouterExtensions) {
        try {
            this.user = new User();
            this.rem = false;
        }catch (e) {
            console.log(e);
        }
       // Use the component constructor to inject providers.
    }

    ngOnInit(): void {
        try {
            // Init your component properties here.
            this._page.actionBarHidden = true;
            this.showSpinner = true;
        }catch (e) {
            console.log(e);
        }

    }

    ngAfterViewInit() {

        try {
            // use setTimeout otherwise there is no getRootView valid reference
            setTimeout(() => {

                const sideDrawer = <RadSideDrawer>app.getRootView();
                sideDrawer.gesturesEnabled = false;


            }, 100);
        }catch (e) {
            console.log(e);
        }
    }

    onDrawerButtonTap(): void {
        try{
        const sideDrawer = <RadSideDrawer>app.getRootView();
        sideDrawer.showDrawer();
        }catch (e) {
            console.log(e);
        }
    }

    onRem() {

        try{
        this.rem = !this.rem;
        console.log(this.rem);
        }catch (e) {
            console.log(e);
        }
    }


    submit() {
        //alert("here");


        try {

            console.log("fdfd" + this.user.phoneNumber + this.user.password);

            // alert(this.user.phoneNumber);
            if (!this.user.phoneNumber || !this.user.password) {

                alert("Please provide both A Phone Number and password.");
            } else {
                this.login();
            }
        }catch (e) {
            console.log(e);
        }
    }


    login() {
        this.showSpinner = false;

        var credentials = {

            phoneNo: this.user.phoneNumber,
            password: this.user.password
        };


        this._loginService.login(credentials).subscribe(result => {
            this.showSpinner = true;

            console.log(JSON.stringify(result));


            try {
                var x = result.json();

                console.log("credentials" + JSON.stringify(x));

                if (x.val == "-6") {
                    alert("Please Activate your account");
                    this.DataService.verifyphone = this.user.phoneNumber;

                    this._loginService.resetcode(this.user.phoneNumber).subscribe(res => {
                        console.log(JSON.stringify(res));
                    });
                    this.routerExtensions.navigate(['home/verify']);

                } else if (x.val == "-5") {
                    alert("Fields are empty");

                } else if (x.val == "-7") {
                    alert("Incorrect phone no or password");
                } else if (x.val == "-8") {
                    alert("Unable to find match");
                } else if (x.ID) {


                    this.user.id = x.ID;
                    this.user.name = x.name;
                    this.user.address = x.address;
                    this.user.dob = x.dob;
                    this.user.email = x.email;


                    this.user.image = x.userImage;
                    //  alert(JSON.stringify(this.user));


                    if (this.rem) {
                        this._loginService.insertData(this.user).then(result => {

                            this.DataService.activeUser = this.user;
                            this.routerExtensions.navigate(['search'], {clearHistory: true});

                        });
                    } else {
                        this.DataService.activeUser = this.user;
                        this.routerExtensions.navigate(['search'], {clearHistory: true});
                    }

                    var status = result.status;
                    console.log("status : " + status);
                    this.showSpinner = true;


                } else {
                    this.showSpinner = true;
                    alert("Unable to Login\n check Credentials");

                }

            } catch (ex) {
                alert("Unable to Login\n check Connection");
            }

        }, err => {
            this.showSpinner = true;
            console.log(err);
            alert("Unable to Connect to Server"+err);

        });


    }


    onButtonTap() {
        this.routerExtensions.navigate(['home/reset']);

    }

    register() {
        this.routerExtensions.navigate(['home/register']);

    }
}
