### ISSUE TITLE
Can't access UIMenuController iOS native API properly

### ISSUE THREAD

**Issue by yassern** [NativeScript/nativescript-angular#1958]
here is an sample code: 

```
html:
<StackLayout (loaded)="onStackLoaded($event)">
    <Label
        #label
        (tap)="onTap()"
        [text]="text"
    ></Label>
</StackLayout>

ts:
@Component(...)
export class MessageComponent {

    @Input() text;
    @ViewChild('label', { static: false }) labelRef: ElementRef;
    private wrapperView: UIView;

    onStackLoaded(args: EventData) {
        const stackLayout = args.object as StackLayout;
        this.wrapperView = stackLayout.ios;
    }

    onTap() {
        const labelElem: Label = this.labelRef.nativeElement;
        labelElem.focus(); // don't know if i need this

        const menu = UIMenuController.sharedMenuController;
        menu.update(); // don't know if i need this

        menu.menuItems = NSArray.arrayWithArray([
            UIMenuItem.alloc().initWithTitleAction('copy', null),
            UIMenuItem.alloc().initWithTitleAction('delete', null),
        ]);

        const nativeLabel = labelElem.ios as UILabel;
        menu.setTargetRectInView(this.wrapperView.frame, nativeLabel);
        menu.setMenuVisibleAnimated(true, true);
    }
}
```
After some hours of "go horse" the result was the same, nothing appears on the screen. 

I just started trying to use native API recently so, maybe something is wrong on that component. i tried to use the 'page' injected by the constructor but the line `this.page.ios.frame` returns undefined. so i tried the wrapper frame that returns something like `<struct CGRect: 0x600003aa8bc0>`.

I also already know the nativescript-tooltip and nativescript-popup plugins but none of these have a good UI by default.

**Comment by NickIliev** [comment]
@yassern try something like[ this](https://play.nativescript.org/?template=play-ng&id=j6NLST) - you will still need to create the logic for your custom actions.

**Comment by PluoAction** [comment]
@NickIliev The playground code is working on TextField. But it still doesn't work on Label
