### ISSUE TITLE
hooks/before-prepare will NOT be executed because it has invalid arguments - platformsData.

### ISSUE THREAD

**Issue by gvsakhil** [NativeScript/nativescript-angular#1959]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: Component nativescript has 6.0.3 version and is up to date.
           Component tns-core-modules has 6.0.6 version and is up to date.
           Component tns-android has 6.0.1 version and is up to date.
           Component tns-ios has 6.0.2 version and is up to date.
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s): 
"@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@ngx-translate/core": "10.0.2",
    "@ngx-translate/http-loader": "3.0.1",
    "@nstudio/nativescript-xavier-passport": "file:src/nativescript-xavier-passport",
    "enhanced-resolve": "4.1.0",
    "moment": "2.22.2",
    "nativescript-accordion": "5.0.4",
    "nativescript-angular": "^8.2.0",
    "nativescript-audio": "5.0.1",
    "nativescript-background-http": "3.2.7",
    "nativescript-background-task": "file:src/nativescript-background-task",
    "nativescript-barcodescanner": "2.7.7",
    "nativescript-bitmap-factory": "1.7.1",
    "nativescript-camera": "4.5.0",
    "nativescript-card-io": "file:src/nativescript-card-io",
    "nativescript-cardview": "3.2.0",
    "nativescript-checkbox": "3.0.3",
    "nativescript-cardio-custom": "github:maxbaki/nativescript-cardio-custom",
    "nativescript-custom-entitlements": "0.2.0",
    "nativescript-directions": "1.3.0",
    "nativescript-dom": "2.0.2",
    "nativescript-drop-down": "4.0.1",
    "nativescript-effects": "1.0.0",
    "nativescript-email": "1.5.3",
    "nativescript-enumerable": "3.5.2",
    "nativescript-exit": "1.0.1",
    "nativescript-geolocation": "5.1.0",
    "nativescript-gif": "4.0.1",
    "nativescript-google-analytics": "0.4.4",
    "nativescript-google-maps-sdk": "2.6.1",
    "nativescript-image-cache": "1.1.6",
    "nativescript-image-filters": "2.2.0",
    "nativescript-imagecropper": "1.0.4",
    "nativescript-imagepicker": "6.2.0",
    "nativescript-iqkeyboardmanager": "1.3.0",
    "nativescript-loading-indicator": "2.4.0",
    "nativescript-local-notifications": "3.1.0",
    "nativescript-localstorage": "2.0.0",
    "nativescript-masked-text-field": "3.0.1",
    "nativescript-microsoft-appcenter": "1.2.1",
    "nativescript-ng-shadow": "2.1.0",
    "nativescript-onesignal": "file:src/nativescript-onesignal",
    "nativescript-orientation": "2.2.0",
    "nativescript-pager": "8.0.2",
    "nativescript-status-bar": "1.1.1",
    "nativescript-theme-core": "1.0.4",
    "nativescript-ui-autocomplete": "5.0.0",
    "nativescript-ui-listview": "7.0.0",
    "nativescript-ui-sidedrawer": "7.0.0",
    "nativescript-vector-icons": "1.0.0",
    "nativescript-videoplayer": "4.0.4",
    "nativescript-webview-interface": "1.4.2",
    "nativescript-zxing": "file:src/nativescript-zxing",
    "ngx-moment": "3.0.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^6.4.0",
    "rxjs-compat": "6.3.3",
    "timeline-view": "0.0.6",
    "tns-core-modules": "^6.0.6",
    "zone.js": "^0.9.1"
 - NativeScript-Angular: 8.2.0
 - Angular: 8.2.0
 
**Describe the bug**
When I run **tns run android** Its giving a warning /Users/akki/Documents/Workspace/UTU/UTU.MobileApp/hooks/before-prepare/nativescript-custom-entitlements.js will NOT be executed because it has invalid arguments - platformsData. and this is happening from the day I migrated my nativescript version to tns6.

**Comment by Fatme** [comment]
@gvsakhil,

NativeScript 6.0 release has breaking changes that affects the way the hooks are executed. More info can be found [here](https://www.nativescript.org/blog/migrating-cli-hooks-to-nativescript-6.0).
As `platformsData` is renamed to `platformsDataService` in CLI 6.0, you need to change `$platformsData` to `$platformsDataService`:
```
module.exports = function($platformsDataService) {
```

If you want to make it backwards compatible, you could use the following:
```
module.exports = function($injector, hookArgs) {
    const platformsData = getPlatformsData($injector);
}

function getPlatformsData($injector) {
    try {
        return $injector.resolve("platformsData");
    } catch (err) {
        return $injector.resolve("platformsDataService");
    }
}
```

**Comment by Fatme** [comment]
I'm closing this issue as it is expected after migrating to NativeScript 6.0.

**Comment by gvsakhil** [comment]
In which file should I make that change module.exports = function($platformsDataService) { @Fatme

**Comment by Fatme** [comment]
@gvsakhil,
The change should be made in `/Users/akki/Documents/Workspace/UTU/UTU.MobileApp/hooks/before-prepare/nativescript-custom-entitlements.js`.

**Comment by gvsakhil** [comment]
Sometimes we delete hooks folder and again build. So we should change the code every time we delete hooks folder?
