### ISSUE TITLE
Nativescript Page Issue

### ISSUE THREAD

**Issue by Vinaykummar** [NativeScript/nativescript-angular#1960]
Hi. I am using  Nativescript 6 and angular for my project. The issue is My project contains 2 pages fron radsidedrawer one is Newsfeed Page and browse. Page.,

In newsfeed page I am getting the documents from firebase firestore in ngOnInit() function.whenever i go to the browse page and return back to the newsfeed page it again getting the documents from firebase which increase documents read value. 

Is there a way to save last page state so that the view will be constant whenever i visit the page.

**Comment by tsonevn** [comment]
Hi, @Vinaykummar,
I've checked your case in a sample project and the ngOnInit event should be triggered only when you've navigated to the Newsfeed page. When you are making back navigation, the event will not be fired. On that matter, perhaps the second document download is triggered by something else. I am not aware of the implementation of the firebase download functionality in your project. However, you can try adding a flag in your code that ensures that files will be downloaded only on the first load of the page. The state of the page should be restored automatically when you navigate back to the page.
