### ISSUE TITLE
nable to start activity ComponentInfo{org.nativescript.AngularYt/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed

### ISSUE THREAD

**Issue by johnny-stevie** [NativeScript/nativescript-angular#1969]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
https://github.com/johnny-stevie/ytDownloader/blob/master/package.json
 
**Describe the bug**
I keep getting this error:
`System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.AngularYt/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.AngularYt/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:24)
System.err:     at android.app.Activity.performCreate(Activity.java:7136)
System.err:     at android.app.Activity.performCreate(Activity.java:7127)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
System.err:     ... 11 more`
So i git cloned https://github.com/johnny-stevie/ytDownloader which was stable a few days ago but for some reason it produced the same error, could someone tell me what im doing wrong?
**To Reproduce**

git clone https://github.com/johnny-stevie/ytDownloader and run tns run android
**Expected behavior**
install and run app
**Sample project**
https://github.com/johnny-stevie/ytDownloader

**Comment by danielgek** [comment]
`Main entry is missing. App cannot be started. Verify app bootstrap.` this means that probably your webpack compilation had errors, @NickIliev this is asked a **lot** of times even in slack, i think is worth to change that error message and maybe give the developer a few hints of what might be causing the problem

**Comment by johnny-stevie** [comment]
Thank you for the response, this has happened only because i updated and installed a few packages and then it keeps giving me this error, even when i compiled with an older and stabler version it still gave the same error

**Comment by danielgek** [comment]
can you post the hole webpack config ?

**Comment by johnny-stevie** [comment]
Do you mean the console logs where I got the error message?

**Comment by johnny-stevie** [comment]
`Searching for devices...
Starting Android emulator with image Pixel_2_API_28
Waiting for emulator device initialization...
Preparing project...
File change detected. Starting incremental webpack compilation...

webpack is watching the files…

Hash: 813fdc94263e5e92c87e
Version: webpack 4.27.1
Time: 26862ms
Built at: 09/02/2019 15:01:09
              Asset      Size   Chunks             Chunk Names
          bundle.js  7.16 KiB   bundle  [emitted]  bundle
       package.json  81 bytes           [emitted]
         runtime.js  71.4 KiB  runtime  [emitted]  runtime
tns-java-classes.js   0 bytes           [emitted]
          vendor.js  3.58 MiB   vendor  [emitted]  vendor
Entrypoint bundle = runtime.js vendor.js bundle.js
[./app.css] 1020 bytes {bundle} [built]
[./main.ts] 1.17 KiB {bundle} [built]
[./package.json] 73 bytes {bundle} [optional] [built]
    + 172 hidden modules

ERROR in node_modules/nativescript-bottom-navigation/index.d.ts(21,3): error
TS2416: Property 'activeColor' in type 'BottomNavigationBar' is not assignable to the same property in base type 'BottomNavigationBarBase'.
  Type 'string' is not assignable to type 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(22,3): error TS2416: Property 'inactiveColor' in type 'BottomNavigationBar' is not assignable to the same property in base type 'BottomNavigationBarBase'.
  Type 'string' is not assignable to type 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(23,20): error TS2304:
Cannot find name 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(46,22): error TS2304:
Cannot find name 'EventData'.

Webpack compilation complete. Watching for file changes.
Webpack build done!
Project successfully prepared (android)
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Successfully transferred runtime.js on device emulator-5554.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.AngularYt on device emulator-5554.
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.AngularYt/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.AngularYt/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:24)
System.err:     at android.app.Activity.performCreate(Activity.java:7136)
System.err:     at android.app.Activity.performCreate(Activity.java:7127)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
System.err:     ... 11 more
`
This is the error message I get, ignore the one about the bottom navigation, that has to do with a lib plus its not a fatal error.

**Comment by danielgek** [comment]
```
ERROR in node_modules/nativescript-bottom-navigation/index.d.ts(21,3): error TS2416: Property 'activeColor' in type 'BottomNavigationBar' is not assignable to the same property in base type 'BottomNavigationBarBase'.
Type 'string' is not assignable to type 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(22,3): error TS2416: Property 'inactiveColor' in type 'BottomNavigationBar' is not assignable to the same property in base type 'BottomNavigationBarBase'.
Type 'string' is not assignable to type 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(23,20): error TS2304:
Cannot find name 'Color'.
node_modules/nativescript-bottom-navigation/index.d.ts(46,22): error TS2304:
Cannot find name 'EventData'.
```

as you can see these errors prevent webpack to actually build the application 
You can add `"skipLibCheck": true,` inside `compilerOptions` in tsconfig.json

**Comment by danielgek** [comment]
or contact the plugin author

**Comment by johnny-stevie** [comment]
Thanks, it's working now, the author just forgot to import Color and EventData. That is very weird because this error didn't stop me before to run android. Anyway, thank you very much for your help.
