### ISSUE TITLE
How to add a child to a specific position

### ISSUE THREAD

**Issue by mohammadreza99** [NativeScript/nativescript-angular#1994]
How can I append a child to a specific position in nativescript?
suppose I have this template :
```
<WrapLayout id="container">
<!-- I want to add some elements here -->
 <TextField></TextField>
</WrapLayout>
```
how can I do this? 
thanks!

**Comment by NickIliev** [comment]
@mohammadreza99 each layout provides specific methods and properties - for example, the WrapLayout has a method called `addChild` ([see the API references](https://docs.nativescript.org/api-reference/classes/_ui_layouts_wrap_layout_.wraplayout#addchild)).

That said there is also an [insertChild ](**url**)method that can accept an insertion index

**Comment by NickIliev** [comment]
@mohammadreza99 notice that in Angular I won't recommend using the above methods to dynamically add/remove elements. Instead, you should use structural directives and the recommended Angular way (e.g., like ***ngIf**)
