### ISSUE TITLE
Dynamically add view outside the Page context

### ISSUE THREAD

**Issue by mohammadreza99** [NativeScript/nativescript-angular#1995]
how can I dynamically create and add a view outside the Page context?
suppose :

**my-cmp.component.html:**
```
<GridLayout (loaded)="onLoaded($event)"></GridLayout>
```

**my-cmp.component.ts:**
```
onLoaded(args: EventData) {
        let grid = args.object as GridLayout;
        let page= grid.page; // <-- I want add some view dynamically outside this page reference.
}
```

**app.component.html:**
```
<Page> <!-- suppose this Page tag created by default via nativescript -->
<my-cmp></my-cmp>
</Page>

<Label></Label> <!-- I want create this Label dynamically from my-cmp.component -->
```

how can I do this??

**Comment by NickIliev** [comment]
@mohammadreza99 see my answer [here](https://github.com/NativeScript/nativescript-angular/issues/1994) - you should use the Angular way to add/remove dynamically components. 

Use structural directives like ***ngIf** .

**Comment by mohammadreza99** [comment]
@NickIliev thank you for your response.
but using structural directives like **ngIf** is for static components. not?
I want create Label using code behinde way and appned outside the Page.
how can I do this with **ngIf**?
