### ISSUE TITLE
After Angular 8 Upgrade -- @angular/core and other modules cannot be found

### ISSUE THREAD

**Issue by mchallenger88** [NativeScript/nativescript-angular#1996]
**Environment**
All the latest versions.
 
**Describe the bug**
After upgrading to ng 8, @angular/core cannot be found as well as many other modules. It might be some kind of pathing issue, but when I remove the references and try to use Visual Studio's auto import functions, it cannot find these modules either.

**To Reproduce**
Don't know. Running tns doctor didn't show any errors.

<img width="660" alt="9-30-2019 10-32-04 AM" src="https://user-images.githubusercontent.com/30409225/65893593-cf472f00-e36d-11e9-8228-f44ee6eee163.png">

**Comment by mchallenger88** [comment]
The weird thing is that once I fixed the "esNext" in tsconfig.tns.json, the project compiles and runs.

**Comment by Fatme** [comment]
@mchallenger88,

> Don't know. Running tns doctor didn't show any errors.

`tns doctor` checks only if your environment is properly configured (for example, if android studio is installed, if CocoaPods are installed and configured, if Xcode is installed and configured). It doesn't check for errors in the application.

However, these errors might appear as Visual Code doesn't reload properly the project. Try to completely close it and reopen again your project. If that doesn't resolve your issue, send us your `tsconfig.json` and `tsconfig.tns.json` files for further investigation.

**Comment by mchallenger88** [comment]
Yes that was it. I thought I had closed VS and reopened, but I must have just closed the project and reopened. Thanks for your help!

**Comment by mchallenger88** [comment]
Sorry closed it incorrect.y. I have attached the two files.

[tsconfig.tns.zip](https://github.com/NativeScript/nativescript-angular/files/3675404/tsconfig.tns.zip)

**Comment by mchallenger88** [comment]
I created a new project and it did not have the above problem. I compared tsconfig.json and there were differences. I copied the tsconfig.json from the new project to the old one and the problem disappeared. I think the problem may have been the module was pointing to esNext in the old file and commonjs in the new.
