### ISSUE TITLE
[Fresh Install] Main entry is missing. App cannot be started. Verify app bootstrap.

### ISSUE THREAD

**Issue by yeshwanthvshenoy** [NativeScript/nativescript-angular#1997]
**Environment**
 - CLI: 6.1.2
 - Cross-platform modules: Android
 - Android Runtime: Android P (API Level 28)
 - iOS Runtime: none
 - Plugin(s): none
 - NativeScript-Angular: Yes
 - Angular CLI: 8.3.6
 - Node: 12.10.0
 - NPM: 6.11.3
 - Nativescript Schematics: 0.7.1
 
**Describe the bug**
So, on my mac I wanted to evaluate Nativescript-Angular for a PWA + Native app. I didn't have node or npm or anything else related to it installed before today. Installed node via homebrew. Followed guide from [here](https://www.nativescript.org/blog/how-to-build-a-pwa-an-ios-app-and-an-android-app-from-one-codebase). I only did `ng new Checklist --collection @nativescript/schematics --shared --sample` and did `ng serve` and as expected, I was able to see the app but when I did `npm run android`, the app crashed with some weird error message. I haven't done one code change to the sample app but still run into errors.

**To Reproduce**
Follow the linked guide with mentioned node/cli/angular/schematics version or can clone sample app from [here](git@github.com:yeshwanthvshenoy/ng8-nativescript.git)

**Expected behavior**
Run the app on Android without errors.

**Sample project**
[Github Link](git@github.com:yeshwanthvshenoy/ng8-nativescript.git)

**Additional context**
Stack Trace:
```
Gradle build...
         + setting applicationId
         + applying user-defined configuration from /Users/yeshwanths/Documents/Checklist/App_Resources/Android/app.gradle
         + using android X library androidx.legacy:legacy-support-v4:1.0.0
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: /Users/yeshwanths/Documents/Checklist/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Project successfully built.
The build result is located at: /Users/yeshwanths/Documents/Checklist/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.Checklist on device emulator-5554.
JS: HMR: Hot Module Replacement Enabled. Waiting for signal.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{org.nativescript.Checklist/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.Checklist/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1063)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1055)
System.err: 	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err: 	at android.app.Activity.performCreate(Activity.java:7136)
System.err: 	at android.app.Activity.performCreate(Activity.java:7127)
System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
System.err: 	... 11 more
```

**Comment by Fatme** [comment]
Hey @yeshwanthvshenoy,

Most probably your issue is related [to this one](https://github.com/NativeScript/nativescript-schematics/issues/249). You can check if this is the case on your side if there is the following message in your output:
```
ERROR in node_modules/@types/jasminewd2/index.d.ts(8,23): error TS2688: Cannot find type definition file for 'jasmine/v2'.
```

**Comment by yeshwanthvshenoy** [comment]
@Fatme Yes, I am getting this above the stack trace. Is there a workaround for this? When can we expect next release if there is no workaround for this??

Quick Question: Why can't we just show the error a little more properly. The stack trace is totally confusing for beginners atleast.

**Comment by Fatme** [comment]
@yeshwanthvshenoy,

> Is there a workaround for this? 

Yes, there is a workaround. You need to modify your `tsconfig.json` file:
```
{
    compilerOptions: {
        "skipLibCheck": true
    }
}
```

> When can we expect next release?

We're planning to release a new version of `@nativescript/schematics` this week.

> Quick Question: Why can't we just show the error a little more properly. The stack trace is totally confusing for beginners atleast.

We'll improve this behavior in the next minor release of NativeScript that is planned at the end of October.

**Comment by yeshwanthvshenoy** [comment]
@Fatme thanks a lot for the prompt responses!!
