### ISSUE TITLE
[iOS 13] Animation-examples application crash when navigate to example with animation

### ISSUE THREAD

**Issue by DimitarTodorov** [NativeScript/nativescript-angular#2002]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.x
 - Cross-platform modules: 6.1.x
 - Android Runtime: 6.1.x
 - iOS Runtime: 6.1.x
 - NativeScript-Angular: master branch
 - Angular: 8.2
 
**Describe the bug**
When navigate to example with animation the app crashes

**To Reproduce**
1. Deploy the app on iOS 13 simulator
2. Navigate to "Angular docs animations" example

Actual: The app crashes

**Expected behavior**
The "angular docs animations" example should be loaded.

**Sample project**
The animation-examples app from the e2e/ folder of the repo

**Additional context**
```
JavaScript error:
file:///node_modules/tns-core-modules/ui/animation/animation.js:285:0: JS ERROR TypeError: undefined is not an object (evaluating 'nativeView.layer')
```

**Comment by VladimirAmiorkov** [comment]
Resolved in https://github.com/NativeScript/nativescript-angular/pull/2022
