### ISSUE TITLE
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.

### ISSUE THREAD

**Issue by AnandkumarBShetty** [NativeScript/nativescript-angular#2010]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 √ Getting NativeScript components versions information...
√ Component nativescript has 6.1.2 version and is up to date.
√ Component tns-core-modules has 6.1.1 version and is up to date.
‼ Update available for component tns-android. Your current version is 6.1.1 and the latest available version is 6.1.2.
× Component tns-ios is not installed.

Angular CLI: 8.3.8
Node: 10.16.0
OS: win32 x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package Version
@angular-devkit/architect 0.802.2
@angular-devkit/build-angular 0.802.2
@angular-devkit/build-optimizer 0.802.2
@angular-devkit/build-webpack 0.802.2
@angular-devkit/core 8.2.2
@angular-devkit/schematics 8.2.2
@angular/cli 8.3.8
@angular/http 7.2.15
@ngtools/webpack 8.2.2
@schematics/angular 8.3.8
@schematics/update 0.803.8
rxjs 6.5.3
typescript 3.5.3
webpack 4.38.0
 
**Describe the bug**
tns run android --bundle keeps failing with this message:
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap. 

**To Reproduce**
tns run android --bundle

**Expected behavior**
tns run android --bundle should run smoothly as the basic steps followed from the migration doc. 

**Additional context**
 ng add @nativescript/schematics was used to for updating the existing web based project under development

**Comment by tsonevn** [comment]
Hi @AnandkumarBShetty 
Can you send us the project or sample one, where the issue can be reproduced?

**Comment by AnandkumarBShetty** [comment]
Hi Nikolay Tsonev,

I have my Web application  which is under Development however it is good to go with NativeScript with already built usecases. The best way to see the issue is through the skype call. I have posted 2 other issues:
https://github.com/NativeScript/nativescript-angular/issues/2008
https://github.com/NativeScript/nativescript-angular/issues/2009

Even these can be looked at it.

If this works fine, then I am available now or whenever you are fine.

My Skype ID: anandkumar.b.shetty@outlook.com<mailto:anandkumar.b.shetty@outlook.com>

Thanks,
Anand

________________________________
