### ISSUE TITLE
Global error handling in iOS apps

### ISSUE THREAD

**Issue by janossuta** [NativeScript/nativescript-angular#2013]
Hi,

I would like to implement a global exception handling in my app but I'm not sure where to start. 
I'm using nativescript for a year now and fortunately and got away without any production errors until now. I'm using firebase in my app and I can see in the reports that I had some crashes (and also can see in itunesconnect dashboard) but I don't know what causing this issues because I couldn't reproduce the issues on my test devices. So I decided to implement a global error handling in my app and I found this article (https://docs.nativescript.org/angular/core-concepts/error-handling) but I don't really know how to and where to add this code to my angular app (I think the example is in vanilla JavaScript). I would really appreciate if somebody could help me with an example or something.

Thank you in advance!

**Comment by tsonevn** [comment]
HI @janossuta,
In NativeScript Angular, you can try adding your custom error handler before `platformNativeScriptDynamic().bootstrapModule(AppModule);` in `main.ts` file. The approach for defining the error handler must be the same as the example shown in [the article](https://docs.nativescript.org/angular/core-concepts/error-handling#defining-custom-error-handler).

**Comment by janossuta** [comment]
Hi @tsonevn,

I've tried it but it's not exactly working:
https://play.nativescript.org/?_ga=2.219220377.1867127049.1571071411-667934789.1523464008&template=play-ng&id=Dt27ZR&v=3

**Comment by tsonevn** [comment]
HI @janossuta,
Thank you for the provided sample project. 
First of all, you need to remove `application.run({ moduleName: 'app-root' });` from the code. This line is not needed in NativeScript Angular. You can also try moving the error handler inside the `app.module.ts`.
It seems that registering it inside `main.ts` is too early. I am attaching [the sample project ](https://play.nativescript.org/?_ga=2.219220377.1867127049.1571071411-667934789.1523464008&template=play-ng&id=Dt27ZR&v=4)with some edits.

**Comment by janossuta** [comment]
Hi @tsonevn,

Thank you for your sample code!
I copied your sample into my code but I'm not sure how it supposed to work. 
For example if I throw a random Error somewhere in my code and let say I put a console.debug("some error happened") in the global error handler it should appear on the console when an error happens? 

I've updated the playground code: [sample code](https://play.nativescript.org/?_ga=2.219220377.1867127049.1571071411-667934789.1523464008&template=play-ng&id=Dt27ZR&v=13)

Sorry if my questions seem too basic to you but I'm trying to figure out how all these things are work.

My final goal would be to log all the unhandled crashes into firebase.

**Comment by tsonevn** [comment]
Hi @janossuta,
Excuse me for the delayed reply. 
Ones you've registered the error handler you must be able to print the errors that appear in the callback method. With its help, you also must be able to send the error to your crash analytics service.
