### ISSUE TITLE
ScrollView with Tabs NS 6.0

### ISSUE THREAD

**Issue by PabloPG** [NativeScript/nativescript-angular#2017]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.0
 - Cross-platform modules:
 - Android Runtime:
 - Plugin(s):
 - NativeScript-Angular: 8.0.2
 - Angular:
 
**Describe the bug**
When using the new tabs component with scrollview, the tab content item does not work

**To Reproduce**
`
<ScrollView>
    <Tabs id="tabViewContainer" swipeEnabled="false" selectedIndex="0" class="tab-font-size">
            <TabStrip>
                <TabStripItem title="Info"></TabStripItem>
                 <TabStripItem title="Checklists"></TabStripItem>
             </TabStrip>
             <TabContentItem>
                 <StackLayout>
                        <Label textWrap="true" text="Info Content" class="h2 description-label"> 
                        </Label>
                  </StackLayout>
              </TabContentItem>
              ...
</ScrollView>
`

**Expected behavior**
Show the content

**Sample project**
Example: https://play.nativescript.org/?template=play-ng&id=yHTBGL

**Additional context**

**Comment by horlarme** [comment]
@PabloPG please how'd you pass this? I've been stuck with the same place for days now.

**Comment by NickIliev** [comment]
@PabloPG @horlarme both ScrollView and StackLayout are going to take only the space that they need to render their children. The thing is that in the Playground above nor the ScrollView neither the StackLaoyut that is nested inside had some pre-defined height. Meaning that they won't "know" how much space they need (and will take exactly 0 space).

Set a height if you want to render a proper space for their nested elements.
Example: https://play.nativescript.org/?template=play-ng&id=yHTBGL&v=2
