### ISSUE TITLE
How to stop animated navigation using <page-router-outlet>?

### ISSUE THREAD

**Issue by okmttdhr** [NativeScript/nativescript-angular#202]
How can I stop animated navigation using `<page-router-outlet>`?

It seems to always navigate with animation here https://github.com/NativeScript/nativescript-angular/blob/77b943769949c339fc380fe80f21eec26c92e318/src/nativescript-angular/router/page-router-outlet.ts#L180

Is it possible to stop animated navigation in some way?

**Comment by hdeshev** [comment]
I don't think we've added the option for that yet, but we definitely should. Adding it shouldn't be too hard, but I'm not sure if making it work for the "old" (`@angular/router-deprecated`) router is worth the effort.

Maybe we should just keep this in mind when adding support for the new ng2 router.

**Comment by tjvantoll** [comment]
Just to add to this, when we do add support for the new router it’d be nice if we supported all the other options that `topmost().navigate()` provides. I’ve already had the need to clear history and configure transitions in my app.

**Comment by hdeshev** [comment]
There is little value in implementing support for this with the current `router-deprecated` package. We'll add this feature when we integrate the new router.
