### ISSUE TITLE
[BottomNavigation] Navigation between tabs with RouterExtension

### ISSUE THREAD

**Issue by Firetrip** [NativeScript/nativescript-angular#2038]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1
 - Android Runtime: 6.1
 - iOS Runtime: 6.1

**Describe the bug**
When changing the tab of the bottom navigation with a routerextension.navigate, the page within the tab will load, but the bottomnavigation does not change to the tab. I would have to set the selected tab index manually by accessing the native element, which cannot be expected behaviour. 

**To Reproduce**

Add a normal bottomnavigation component with multiple tabs. Navigate to a different page-router-outlet with the following command: 

(From organized-trips, see the routing below!)
```
 const outlets = {};
 outlets["benefitTab"] = ["benefit"];
this.routerExt.navigate(["../post-login/default", { outlets, relativeTo: this.activatedRoute }]);
```

To give some further information, this is how my routing is constructed:

app.routing--> post-login.routing:
```
const routes: Routes = [
    {

        path: "default", component: MenuComponent, children: [
            {
                path: "organized-trips",
                outlet: "organizedTripsTab",
                component: NSEmptyOutletComponent,
                loadChildren: () => import("~/app/post-login/organized-trips/organized-trips.module").then((m) => m.OrganizedTripsModule),
                canActivate: [LoginActivate]
            },
            {
                path: "benefit",
                outlet: "benefitTab",
                component: NSEmptyOutletComponent,
                loadChildren: () => import("~/app/post-login/benefit/benefit.module").then((m) => m.BenefitModule),
                canActivate: [LoginActivate]
            },
```
    

**Expected behavior**

The navigation completes and the bottom navigation changes the tab.
I can see that the page actually loads, as ngOnInit is triggered, but no visual navigation happens.

**Additional context**
I want to achieve this due implement a navigation center.  In the final implementation i will pass additional params to the navigation as my benefits page has multiple tabs and i want to be able to deeplink for example to the second tab of the benefit page within th notification center.

**Comment by Firetrip** [comment]
Hey @tsonevn ,

i am sorry for the late reply, as i fixed the issue by navigation the bottom navigation via setting the selectedTabIndex property.
however this will lead to the navigation not completing if I want to change the current router outlets navigation at the same time of changing the tab of the bottomnavigation.

A little example:
Preset: You have two tabs in your Bottomnavigation, one tab called Master, and the other tab called OtherPage
1. You navigate from Master to Detail Page by clicking a button on Master
2. On Detail page you click a button which will trigger two events:
           2.1 Reset the navigation of the page-router-outlet to the Master Page by calling `this.routerExtension.back();`
           2.2 Changing the selectedTabIndex of the BottomNavigation by setting the selectedTabIndex to the Index of OtherPage

What happens is that we change the tab, but the back navigation only completes once the user switches back to the tab called Master.

Expected Behaviour: Let the back() navigation complete in the background, so when the user navigates back to the tab called Master, he already sees Master and not the navigation from Detail to Master

I expect those two being related.

**Comment by IyyappanAmirthalingam** [comment]
@Firetrip 

I found something and seems it is working for me. Just try the following in your `home-routing.module.ts` 
Make sure the parent path for the shouldn't be empty when you use the **named router outlet(in angular) or page-router-outlet (in nativescript angular) **
change the home component path from "" to "default" in `home-routing.module.ts`  and use the navigation route  as "/home/default"

`
        path: "",
        component: HomeComponent,
`

`
    **path: "default",
        component: HomeComponent,**
`
Let me know how it goes.

Correct me if I am wrong.
Thanks
