### ISSUE TITLE
Action Item visibility binding for the specific platform.

### ISSUE THREAD

**Issue by valera1401** [NativeScript/nativescript-angular#2043]
How to bind the visibility of the Acition Item for the specific platform ?
`<ActionBar title="My App" class="action-bar">
    
    <ActionItem android:visibility="collapse"
        text="Test1">
    </ActionItem> 
    
    <ActionItem [android:visibility]="'collapse'"
        text="Test2">
    </ActionItem>     
</ActionBar>`

**Comment by tsonevn** [comment]
Hi @valera1401,
In your case, you can define a custom directive. Check out the gist [here](https://gist.github.com/vakrilov/522dbd30085142c515a5359658f06e54).
For further How to questions, please use the StackOverflow thread [here](https://stackoverflow.com/questions/tagged/nativescript). This repository is used only for bug reports and feature requests.
