### ISSUE TITLE
Can't find variable: window - aws-amplify-angular with nativescript

### ISSUE THREAD

**Issue by nirmay** [NativeScript/nativescript-angular#2044]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  "@angular/compiler-cli": "~8.2.0",
 - Cross-platform modules: -na-
 - Android Runtime: -na-
 - iOS Runtime: 6.1.0
 - Plugin(s): nativescript-randombytes
 - NativeScript-Angular: "nativescript-angular": "~8.2.0",
 - Angular: "@angular/core": "~8.2.0",
 
**Describe the bug**
I am following the [docs](https://aws-amplify.github.io/docs/js/angular) for aws-amplify-angular for angular+nativescript project I am working on.
As the 'aws-amplify-angular' module is loaded, I see following error:

JavaScript error:
file:///node_modules/aws-amplify-angular/dist/src/components/interactions/chatbot/aws-lex-audio.js:549:0: JS ERROR ReferenceError: Can't find variable: window
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: ReferenceError: Can't find variable: window

**To Reproduce**
1. create a simple nativescript [project](https://github.com/nirmay/tns-amplify-angular)
2. follow instruction [here](https://aws-amplify.github.io/docs/js/angular) to setup amplify-angular.

**Expected behavior**
window object from Node runtime mapped in nnativescript.

**Sample project**
-na-

**Additional context**
there is no guidance on how to map window object from Node in nativescript.

**Comment by NickIliev** [comment]
@nirmay the instructions are made for Angular for Web but the library does not seem compatible with NativeScript (it uses DOM which is used by neither iOS nor Android and things like `window` makes no sense in  the context of mobile world).
