### ISSUE TITLE
[QUESTION] How would you write unit test on a function that uses  RouterExtensions from “nativescript-angular/router” for navigation

### ISSUE THREAD

**Issue by Denniskamau** [NativeScript/nativescript-angular#2045]
I have a login function that navigates user to home page on succesfull login 
```
    login() {
        if(this.user){
            this.processing = false;
            this.routerExtensions.navigate(["/home"], { clearHistory: true });
        }else{
            this.processing = false;
            this.alert("Unfortunately we could not find your account.");
        }

    }
```

A comprehensive understanding of the question can be found here [stackoverflow](https://stackoverflow.com/questions/58519271/unit-testing-component-that-depends-on-routerextensions-from-nativescript-angul).

**Comment by tsonevn** [comment]
HI @Denniskamau,
You can review our test app [here](https://github.com/NativeScript/nativescript-angular/blob/master/tests/app/tests/router-module-tests.ts) and to use it as a reference.
