### ISSUE TITLE
tns create - using --template (ng option): adds a tsconfig.json with "noEmitOnError": true <-- problemo

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#205]
`noEmitOnError`:`true` is not helpful since there are various plugins and other things that `tsc` may warn about but are not **errors**, therefore if the `tsconfig.json` that comes down when creating a new TypeScript based project could instead have a relaxed `tsconfig.json` would help, something like this would probably be better for newbies:

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "sourceMap": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

I ran into this when presenting NativeScript at a Meetup this week.

**Comment by NathanWalker** [comment]
I may need to move this to nativescript-cli... wasn't sure where this was coming from. The specific template I was installing was this one:
https://github.com/NativeScript/template-hello-world-ng
However no `tsconfig.json` is there, so I assume it's coming from cli or here. I was going to submit a PR to fix this but could not find where it was coming from.

**Comment by NathanWalker** [comment]
FYI, in case this does need to be moved, this is a great tool to move it easily to another repo:
https://github.com/google/github-issue-mover

**Comment by hdeshev** [comment]
> noEmitOnError:true is not helpful since there are various plugins and other things that tsc may warn about but are not errors,

The reverse holds as well. I've seen too many "broken" projects that turn out to be caused by a TS compile error buried 5 pages up in the console output.

I wonder how many broken plugins are out there. I'd really want to handle this one by fixing any offending plugins.
