### ISSUE TITLE
topmost deprecate (first build after upgrade to v.6.2)

### ISSUE THREAD

**Issue by Cheas** [NativeScript/nativescript-angular#2054]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI:  6.2
 - Cross-platform modules: 6.2
 - Android Runtime: 6.2
 - Plugin(s):
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-snackbar": "^1.0.0",
    "base-64": "^0.1.0",
    "email-validator": "^2.0.4",
    "guid-typescript": "^1.0.9",
    "nativescript-angular": "~8.2.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-plugin-firebase": "^10.0.1",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-listview": "^7.0.5",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "sha1": "^1.1.1",
    "tns-core-modules": "^6.2.0",
    "underscore": "^1.9.1",
    "utf8": "^3.0.0",
 - NativeScript-Angular: ~8.2
 - Angular: ~8.2

**Describe the bug**

1. After building the project on the 6.2 android emulator, a message appeared on console:

`topmost() is deprecated. Use Frame.topmost() instead.`

I do not use it (topmost) directly. There is a list (RadListView) on the page and scrolling does not occur. When you re-enter the page, everything is OK.

2. When building the release, a message appeared

```
ERROR in NativeScriptSnapshot. Snapshot generation failed!
Docker installation cannot be found. Install Docker and add it to your PATH in order to build snapshots.
Executing webpack failed with exit code 2.
```

I deleted the parameter `--env.snapshot` and managed to collect the release.

In previous versions, this was not.

**Comment by elena-p** [comment]
Hi @Cheas, 

Regarding the first issue `topmost() is deprecated. Use Frame.topmost() instead.` there is a new release of nativescript-ui-listview@8.0.0 in which this usage is changed and the warning does not appear. Could you test with that version and log a new issue if there is anything not working with the scroll.

Regarding your second issue, I will transfer it to https://github.com/NativeScript/nativescript-cli/issues where it could be answered in detail.

**Comment by Cheas** [comment]
Hi. elena-p.
Yes, I changed the package "nativescript-ui-listview": "^7.0.5" to "nativescript-ui-listview": "8.0.0", the message does not appear. Thanks for the help.

**Comment by Cheas** [comment]
The problem disappeared after replacing the version Angular 8.2.0 to 8.2.13.

**Comment by alereisan** [comment]
@Cheas I had to upgrade Angular and nativescript-angular packages both, then the topmost warning is gone.
