### ISSUE TITLE
WebView Upgrade to Latest Version of Your Browser Error

### ISSUE THREAD

**Issue by atchaiecommerce** [NativeScript/nativescript-angular#2057]
**Environment**
tns ios 5.4.0
OS: IOS version 13.2.2
 
**Describe the bug**
Opening a webview produces an error message.
"We recommend that you upgrade to the latest version of your browser."

![Capture](https://user-images.githubusercontent.com/57281867/68466964-58486480-0250-11ea-951f-9e99679bd6fd.PNG)

**Comment by NickIliev** [comment]
Is that happening from simply opening any URI or a specific one? It might be that the web resource you are opening is having an internal check of what browser is used (and is not liking the WebView component which uses the native iOS WKWebView).

Closing as unrelated to Angular.
