### ISSUE TITLE
Error in the simulator but none in the console

### ISSUE THREAD

**Issue by ngydat** [NativeScript/nativescript-angular#206]
For my mobile app, I've been using the 9th beta of angular 2 (mostly because I had issues when I used more recent versions). But now, angular 2 is in its 17th beta so I decided I'll give it a shot.

 And by running the command "npm outdated" I also noticed I had outdated plugins. So obviously I updated those plugins (those I could because of the dependency thing). 

So when I used the latest version of angular 2  and nativescript-angular, I have this [error](https://github.com/angular/angular/issues/8329) in the console (but I was able to launch the application, which I wasn't able to do with versions of angular 2 between the 9th and the 17th beta). So I decided to use an older version of nativescript-angular (0.0.45) and keep using the latest version of angular 2 : and I have this [error](http://hpics.li/28a9d4e) now.

What am i missing ?

THank you

**Comment by matt4446** [comment]
Angular2 has been a challenge to upgrade for a while ... zones have been causing a little grief from what I've seen over the last few months (bugs in angular2 code and few hacks over here to support it). 

I would strongly recommend reverting some of dependencies (angular 2 - beta 16 at most) ... or tread carefully beyond some of the sample projects.   

Check out the list of dependencies here as it tends to be quite reliable:
https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/package.json

I'll try to update my project this evening hopefully. Angular2 2.0.0-beta.14 was a good build for me previously and these settings have worked quite well:  
```json
"angular2": "2.0.0-beta.14",
"es6-shim": "^0.35.0",
"zone.js": "^0.6.6",
"nativescript-angular": "~0.0.45",
...
```

looking briefly at the commit there have been a few fixes added to support beta 16 as well:
https://github.com/NativeScript/nativescript-angular/commits/master

**Comment by matt4446** [comment]
https://github.com/NativeScript/nativescript-angular/issues/207
Nathan appears to have stumbled on the same issue I think.

**Comment by ngydat** [comment]
@matt4446 I've just tried your settings and it works so I guess I'll use these settings for the moment. And thanks ;)

**Comment by matt4446** [comment]
https://github.com/NativeScript/nativescript-angular/pull/213
upgrade test time/soon
