### ISSUE TITLE
Missing text-value-accessor

### ISSUE THREAD

**Issue by atchaiecommerce** [NativeScript/nativescript-angular#2068]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.0
 - Cross-platform modules: 6.2.0
 - NativeScript-Angular: 8.20.1
 - Angular: 8.2.0
 
**Describe the bug**
current release of nativescript-angular does not contain _nativescript-angular/forms/value-accessors/text-value-accessor_ which breaks the plugin nativescript-masked-text-field.

**Comment by atchaiecommerce** [comment]
#2059

**Comment by atchaiecommerce** [comment]
reopening as i think the fix does not include this.

**Comment by tbozhikov** [comment]
closing as the patch for this is released as v8.20.3
