### ISSUE TITLE
0.0.46 with {N} 2.0 when navigating - page-router-outlet: componentView.parent.removeChild is not a function

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#207]
```
file:///app/tns_modules/angular2/src/platform/server/parse5_adapter.js:56:75: EXCEPTION:
Error: Uncaught (in promise): TypeError: componentView.parent.removeChild is not a function. 
(In 'componentView.parent.removeChild(componentView)', 'componentView.parent.removeChild' is undefined)
```

Issue stems from here:
https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/router/page-router-outlet.ts#L158

`parent.removeChild` simply doesn't exist anymore. This is likely due to beta.16 breaking changes... trying to find a fix.

**Comment by hdeshev** [comment]
I think I have a fix for that as a part of my migration effort to support the ng RC0 build. I'm still fighting some issues that seem to appear in the test runner app only, but I hope I can push a release soon enough.

**Comment by NathanWalker** [comment]
Thanks @hdeshev I was just wondering what the current effort was to support that ;)
