### ISSUE TITLE
Issue related nested routing on BottomNavigation using RouterExtensions

### ISSUE THREAD

**Issue by smorcuend** [NativeScript/nativescript-angular#2072]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.0
 - Cross-platform modules:
- tns-core-modules: 6.2.1 
 - Android Runtime: 6.2.0
 - iOS Runtime: - 
 - Plugin(s): -
 - NativeScript-Angular: 8.20.2
 - Angular: 8.2.11
 
**Describe the bug**
Issue related nested routing on BottomNavigation using nativescript-angular

Navigation structure according this structure:
![](https://docs.nativescript.org/angular/img/navigation/navigation-diagram-ng-tab.png)

* App-routing:
```
const routes: Routes = [
    { path: "welcome", component: WelcomeComponent },
    { path: "pages", loadChildren: () => import("./pages/pages.module").then(m => m.PagesModule) },
    { path: "", redirectTo: "welcome", pathMatch: "full" },
];
```
* Pages-routing module
```
const routes: Routes = [
  {
    path: '',
    component: PagesComponent,
    children: [
      {
        path: 'home',
        outlet: 'homeoutlet',
        component: HomeComponent
      },
      {
        path: 'advices',
        outlet: 'advicesoutlet',
        component: AdvicesComponent
      },
      {
        path: 'alerts',
        outlet: 'alertsoutlet',
        component: AlertsComponent
      },
      { path: '', redirectTo: '/(homeoutlet:home//advicesoutlet:advices//alertsoutlet:alerts)', pathMatch: 'full' }
    ]
  }
];
```
When i am trying to navigate from /welcome route to pages/[path] route,
```this.routerExtensions.navigate([{ outlets: { homeoutlet: ['pages', 'home'] } }]);```
If I use `relativeTo: this.activeRoute` the result is the same.

i get this error:
Error: ` ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'pages/home' `

**To Reproduce**

**Expected behavior**

**Sample project**
Playground example: https://play.nativescript.org/?template=play-ng&id=sVR895&v=6

**Additional context**

**Comment by NickIliev** [comment]
@smorcuend sounds like an issue with passing the proper path - try enabling the Angular router tracing to see what happens behind the scenes.

```
imports: [NativeScriptRouterModule.forRoot(routes, { enableTracing: true })],
```

**Comment by smorcuend** [comment]
Thanks you @NickIliev. I will test on a pure Angular app to find about navigation issues with outlets.
Meanwhile, i am using https://github.com/Akylas/nativescript-material-components and it works perfectly.

**Comment by eddadjei** [comment]
@smorcuend did you figure out a solution to this? been beating my head against the wall for 2 days. worst case is to pivot to react-native as there is bigger community support

**Comment by Meyer-dev** [comment]
Hi. A possible workaround is to use visibilities and different components
instead of the nested routing. Then you can just write a function that sets
which component you want to see. I didn't use tabs or anything like that to
select which component to "navigate" to. I made a custom navigation bar
that looks like tabs. If you send a your code I can see if I can help you
with that. Hope this helps.
