### ISSUE TITLE
Classes for dark mode support on iOS are not applied when using page-router-outlet

### ISSUE THREAD

**Issue by gdurys** [NativeScript/nativescript-angular#2077]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.1
 - Cross-platform modules:
 - iOS Runtime: 6.2.0
 - Plugin(s):
 - NativeScript-Angular: 8.20.3
 - Angular: 8.2.13
 
**Describe the bug**
Since NativeScript 6.2, iOS dark mode has been implemented
When using a page-router-outlet, the ns-dark and ns-light classes are not applied, thus not applying the correct component css rules.

**To Reproduce**
* Launch attached project.
* The first label color should be red in dark mode, green in light mode. It's currently blue.
* Edit src/app/app.component.tns.html
*comment the page-router-outlet and uncomment the stack layout
*  the correct behaviour will be shown

**Sample project**
[nsbug.zip](https://github.com/NativeScript/nativescript-angular/files/3864232/nsbug.zip)

**Comment by NickIliev** [comment]
@gdurys there is a specific rule that has to be followed when applying your custom light/dark styles. [See the documentation here for details](https://docs.nativescript.org/angular/ui/dark-mode#how-does-it-work) - basically, you have to do the following 

**_authentication.component.tns.css_**
```CSS
:host-context(.ns-dark) .ns-dark .connection {
    color: red;
}

:host-context(.ns-dark) .ns-light .connection {
    color: green;
}

```
