### ISSUE TITLE
No component factory found for DetachedLoader

### ISSUE THREAD

**Issue by sebestindragos** [NativeScript/nativescript-angular#2078]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2.1
 - Cross-platform modules: 6.2.1
 - Android Runtime: 6.2.0
 - iOS Runtime: 6.2.0
 - Plugin(s): 
 - NativeScript-Angular:8.20.3
 - Angular: 8.2.13
 
I've recently upgraded to NS 6.2 and I can't get the app to run on release mode. 
On release I'm building the project using AoT.

Here's the runtime exception:
```
No component factory found for DetachedLoader. Did you add it to @NgModule.entryComponents?

Error: No component factory found for DetachedLoader. Did you add it to @NgModule.entryComponents?
    at ZoneAwareError (<embedded>:116749:33)
    at noComponentFactoryError (<embedded>:18833:17)
    at CodegenComponentFactoryResolver.push.CodegenComponentFactoryResolver.resolveComponentFactory (<embedded>:18880:19)
    at new PageRouterOutlet (<embedded>:83425:47)
    at createClass (<embedded>:21830:20)
    at createDirectiveInstance (<embedded>:21699:20)
    at createViewNodes (<embedded>:30059:36)
    at callViewAction (<embedded>:30375:13)
    at execComponentViewsAction (<embedded>:30294:13)
    at createViewNodes (<embedded>:30087:5)
```

It works fine when running in debug mode.
Any ideas?

**Comment by tsonevn** [comment]
HI @sebestindragos,
I tested your case with a newly created project. However, I was unable to recreate such an issue, while building it for release with AoT. As a reference, I am attaching my sample project. On that matter, it will help if you can send us your project and the exact steps that you've followed while building the app.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/3873038/Archive.zip)

**Comment by sebestindragos** [comment]
Hi @tsonevn and thanks for the quick reply. I wasn't able to reproduce either using a blank project. Our production NS app has around 7 other plugins so that might be the issue. I can share the repository with you, just need your BitBucket account.

**Comment by NickIliev** [comment]
@sebestindragos were you able to resolve the issue? If not you could contact me in the NativeScript community slack and share with me the application (username: **niliev**). I guess that you need to update your **webpack.config.js** and the version of **nativescript-dev-webpack** and then make a clean rebuild.
