### ISSUE TITLE
Use SVG images on NativeScript + Angular (Last Version)

### ISSUE THREAD

**Issue by arodriguezpayall** [NativeScript/nativescript-angular#2083]
Implement a new way to display SVG images on NativeScript + Angular integration. 
Actually there are some problems to show images with this format and there no exist official documentation beyond the plugins in your marketplace and GitHub's projects.
Actually, this plugin (https://market.nativescript.org/plugins/nativescript-svg) not work on Android 9 Pie.
![Screenshot from 2019-11-21 17-14-57](https://user-images.githubusercontent.com/54999865/69377387-8f703a00-0c82-11ea-9158-007d7c2029b0.png)

**Comment by NickIliev** [comment]
SVG images are not supported in NativeScript by default and unfortunately, the linked plugin is broken.  We are open to PRs for implementing the support for SVGs[ in the modules](https://github.com/NativeScript/NativeScript) or as an alternative for creating new independent 3rd party plugin. The N-team is not  planning the im[plementation of SVG
