### ISSUE TITLE
ActionBar inside router-outlet is not shown

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-angular#2084]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2
 - Cross-platform modules: 6.1.2
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.1
 - Plugin(s): unrelated
 - NativeScript-Angular: 8.0.2
 - Angular: 8.0.0
 
**Describe the bug**
If a page which is shown inside a router-outlet and it has an ActionBar, ActionBar is not shown after you navigate to another page and then turn back.

In the root component html file, I have a page-router-outlet. Inside a child page which is loaded in this page-router-outlet I have a router-outlet.

I noticed that if I don't directly put the page inside the router-outlet but put an NSEmptyOutletComponent in between, it works. I can see the action bar after navigating to that page again.

This is my route definition:
````ts
{
        path : "tabs",
	component : TabsComponent,
	children : [
                 // This works:
		{
			path : "profile",
			component : NSEmptyOutletComponent,
			children : [
				{ path : ":id", component : ProfileComponent },
			]
		},
                // This doesn't work:
                //{ path : "profile/:id", component : ProfileComponent },
                // ....
        ]
}
````

Also, if I use a page-router-outlet instead of a router-outlet, there is no problem. However, I cannot use page-router-outlet here because it causes another bug unrelated to this issue.

**To Reproduce**

- Create a project
- Create a page (main page) with page-router-outlet
- Load a page (page 1)  inside that page-router-outlet
- Put a router-outlet inside that new page
- Load another page (page 2) inside router-outlet
- Put an ActionBar inside that page
- Create another page (page 3)
- Navigate to page 3, then navigate to page 2. 

No actionbar.

**Expected behavior**
It should always show the actionbar.

**Sample project**
If you want I can send whole project to your mail address.

**Additional context**
I only tested this on iOS. Don't know if Android has the same problem.

**Comment by NickIliev** [comment]
This is expected and this is the reason why we are having the `page-router-outlet`. In the web development with Angular, an `ActionBar` makes no sense so there is no additional logic for supporting one. This said you should use a PRO when you need the ActionBar in the context of a mobile app. By default, all PRO will create an action bar so you could explicitly hide one if needed.
