### ISSUE TITLE
Tabs TabsStrip does not reflect changes to Tabs.selectedIndex

### ISSUE THREAD

**Issue by iianev** [NativeScript/nativescript-angular#2085]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.2, 6.2.3
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: 6.2.0
 - Plugin(s):
 - NativeScript-Angular: 8.2.2
 - Angular:8.2.14
 
**Describe the bug**
The selectedIndex property of Tabs is not reflected on the TabStrip.
TabStrip always starts with item 0, regardless of the Tab set by selectedIndex.
programmatic changes of the property do not reflect on the selected TabStripItem

**To Reproduce**
Run nativescript-sdk-examples - tabs->usage
<Tabs selectedIndex="2"> has no effect on TabStrip

**Expected behavior**
TabStrip should update on programmatic changes to Tabs.selectedIndex
**Sample project**

**Additional context**

**Comment by NickIliev** [comment]
@iianev thank you for posting the issue - this one is marked as a bug and linked in[ the tracking issue. ](https://github.com/NativeScript/NativeScript/issues/6967)Closing this issue as a duplicate,
