### ISSUE TITLE
App crash when changing Tab visibility with ngIf

### ISSUE THREAD

**Issue by lambourn** [NativeScript/nativescript-angular#2086]
**Environment**

 - CLI: 6.2
 - Cross-platform modules: 6.2.1
 - Android Runtime: 6.2
 - iOS Runtime: 6.2
 - NativeScript-Angular: 8.20.3
 - Angular: ~8.2.0
 
**Describe the bug**

**Given** that `<Tabs>` have multiple `<TabContentItem>` created via `*ngFor`
**And** `<Tabs>` tag is visible depending on `*ngIf`
**When** I will switch `*ngIf`  from `false` state into `true`
**Then** `Tab` tag will crash whole app

**Sample project**

Tap button on second or other tab page to trigger this error:
https://play.nativescript.org/?template=play-ng&id=iBjLn7&v=14

**Comment by NickIliev** [comment]
@lambourn the thing is that you are using the top abstraction (Angular) to change a component from the middle abstraction (NativeScript)  which should change the bottom implementation (the native code). That is pretty much the reason why structural directives from Angular could cause issues when used to change a tab. Currently, we are not supporting changing tabs dynamically (no matter if done through code-behind or Angular directives)

**Comment by Pandishpan** [comment]
@lambourn if you just want to hide/show the Tabs component why you don't use the visibility property?

> [visibility]="isTabVisible ? 'visible' : ''collapsed"

*ngIf directive it will recreate that component when is switched between true/false

Here you can see that the component is recreated after you press the button 
https://play.nativescript.org/?template=play-ng&id=OzTdXK&v=2
