### ISSUE TITLE
IOS, Android: NativeScript switch offBackgroundColor is not effecting.

### ISSUE THREAD

**Issue by M-kothakapu** [NativeScript/nativescript-angular#2094]
Hi,

I have been working around Switch in Nativescript and trying to utilize its CSS properties as mentioned in the document. 
<img width="786" alt="Screen Shot 2019-12-06 at 2 25 56 PM" src="https://user-images.githubusercontent.com/17285726/70354162-911a3000-1834-11ea-8f0d-ba636129d651.png">

Here is the output: 
https://play.nativescript.org/?template=play-ng&id=d8Dctd

screenshots: 
IOS: 
![C9548AE0-986E-4C73-B037-7070584452A2](https://user-images.githubusercontent.com/17285726/70354869-5618fc00-1836-11ea-8eaa-a40f4ffdbf8f.jpeg)
![F9A709DB-319D-4024-B2A1-82FBAA1FDCA5](https://user-images.githubusercontent.com/17285726/70354870-5618fc00-1836-11ea-8368-40455489e173.jpeg)

Android:
![image](https://user-images.githubusercontent.com/17285726/70354993-adb76780-1836-11ea-8668-311fe4f6b60f.png)

![image](https://user-images.githubusercontent.com/17285726/70355043-cb84cc80-1836-11ea-881e-e6164139ec26.png)

Observations: 
1. **offBackgroundColor** is not applying in both IOS and Android.
2. In **Android** colors are very **light and dim to see**. Not as effective as in IOS.

**Comment by NickIliev** [comment]
Due to a native limitation the off-color can be applied only on higher API levels (Android) and won't work on lower API levels (Android) and on iOS.
