### ISSUE TITLE
TCP connection cancels/ends after connecting via Spotify iOS SDK

### ISSUE THREAD

**Issue by jholmes12** [NativeScript/nativescript-angular#2095]
**Environment**
- XCode: 11.2.1
- Spotify iOS SDK: 1.2.0 (latest)
 - NativeScript-Angular: 8.20.3
 - Angular: 8.2.14
 
**Issue Description**
When using the latest official Spotify iOS SDK framework,  the SDK has a built in method to connect to Spotify in order to receive updates when songs change and other events happen.  It appears they are using the iOS nw_connection to stream that data.

After initializing a new Spotify appRemote instance, there seems to be an issue when "connecting" the appRemote that is causing the TCP connection used by the spotify SDK to cancel a few seconds after successfully connecting.  Everything appears to work and a successful connection is established, but then shortly afterwards the logs show 'TCP Conn 0x2818e06c0 canceled'.

**To Reproduce**
I have included a sample project, by following the steps in the README you should be able to replicate the issue. You will need to run the Nativescript project on your phone with Spotify already installed.

**Expected behavior**
Maintain connection to be able to receive player updated events.  When using the SDK in the demo native Swift project included in the Spotify SDK, the app connects and the connection is maintained with out cancelling.

**Sample project**
I set up a sample project that has the spotify ios SDK framework added in and demonstrates the issue when trying to connect.
https://github.com/jholmes12/nativescript-spotify-appremote-sample/tree/master

**Logs from attempting to connect**

CONSOLE LOG file:///src/app/app.component.ts:31:28: attempting to connect...
CONSOLE LOG file:///src/app/spotify.service.ts:37:20: attempting to connect...
TCP Conn [1:0x2818e06c0] using empty proxy configuration
Stream client bypassing proxies on TCP Conn [1:0x2818e06c0]
TCP Conn 0x2818e06c0 started
[C1 EFD9C55E-BDF9-4474-B81E-6112F61A92D2 Hostname#9b9b1e2c:9095 tcp, legacy-socket] start
nw_connection_report_state_with_handler_on_nw_queue [C1] reporting state preparing
nw_socket_handle_socket_event [C1.1:1] Socket received CONNRESET event
nw_socket_handle_socket_event [C1.1:1] Socket received DISCONNECTED event
nw_socket_handle_socket_event <private> Socket SO_ERROR [61: Connection refused]
nw_flow_disconnected [C1.1 ::1.9095 in_progress socket-flow (satisfied (Path is satisfied), interface: lo0)] Output protocol disconnected
nw_socket_handle_socket_event [C1.2:1] Socket received CONNECTED event
nw_flow_connected [C1.2 127.0.0.1:9095 in_progress socket-flow (satisfied (Path is satisfied), interface: lo0)] Output protocol connected
nw_connection_report_state_with_handler_on_nw_queue [C1] reporting state ready
TCP Conn 0x2818e06c0 event 1. err: 0
TCP Conn 0x2818e06c0 complete. fd: 6, err: 0
CONSOLE LOG file:///src/app/spotifyPlayer.ts:7:20: **app is now connected.**
TCP Conn 0x2818e06c0 canceled
[C1 EFD9C55E-BDF9-4474-B81E-6112F61A92D2 Hostname#9b9b1e2c:9095 tcp, legacy-socket] cancel
[C1 EFD9C55E-BDF9-4474-B81E-6112F61A92D2 Hostname#9b9b1e2c:9095 tcp, legacy-socket] cancelled
[C1.2 BC120717-4F38-4F73-96DC-3653812AAB1B 127.0.0.1:51202<->127.0.0.1:9095]
Connected Path: satisfied (Path is satisfied), interface: lo0
Duration: 0.496s, DNS @0.000s took 0.003s, TCP @0.005s took 0.001s
bytes in/out: 54/432, packets in/out: 1/1, rtt: 0.000s, retransmitted packets: 0, out-of-order packets: 0
0.000s [C1 80C0308D-351A-4523-BA72-7630A9806E97 Hostname#9b9b1e2c:9095 resolver path=satisfied (Path is satisfied), interface: lo0] path:start
0.000s [C1 80C0308D-351A-4523-BA72-7630A9806E97 Hostname#9b9b1e2c:9095 resolver path=satisfied (Path is satisfied), interface: lo0] path:satisfied
0.000s [C1 80C0308D-351A-4523-BA72-7630A9806E97 Hostname#9b9b1e2c:9095 resolver path=satisfied (Path is satisfied), interface: lo0] resolver:start_dns
0.003s [C1 80C0308D-351A-4523-BA72-7630A9806E97 Hostname#9b9b1e2c:9095 resolver path=satisfied (Path is satisfied), interface: lo0] resolver:receive_dns
0.003s [C1.1 00000000-0000-0000-0000-000000000000 ::1.51201<->::1.9095 socket-flow path=(null)] path:start
0.003s [C1.1 00000000-0000-0000-0000-000000000000 ::1.51201<->::1.9095 socket-flow path=(null)] path:satisfied
0.003s [C1.1 00000000-0000-0000-0000-000000000000 ::1.51201<->::1.9095 socket-flow path=(null)] flow:start_connect
0.004s [C1.1 00000000-0000-0000-0000-000000000000 ::1.51201<->::1.9095 socket-flow path=(null)] flow:failed_connect
0.004s [C1.2 BC120717-4F38-4F73-96DC-3653812AAB1B 127.0.0.1:51202<->127.0.0.1:9095 socket-flow path=satisfied (Path is satisfied), interface: lo0] path:start
0.005s [C1.2 BC120717-4F38-4F73-96DC-3653812AAB1B 127.0.0.1:51202<->127.0.0.1:9095 socket-flow path=satisfied (Path is satisfied), interface: lo0] path:satisfied
0.005s [C1.2 BC120717-4F38-4F73-96DC-3653812AAB1B 127.0.0.1:51202<->127.0.0.1:9095 socket-flow path=satisfied (Path is satisfied), interface: lo0] flow:start_connect
0.006s [C1.2 BC120717-4F38-4F73-96DC-3653812AAB1B 127.0.0.1:51202<->127.0.0.1:9095 socket-flow path=satisfied (Path is satisfied), interface: lo0] flow:finish_connect
0.006s [C1 80C0308D-351A-4523-BA72-7630A9806E97 Hostname#9b9b1e2c:9095 resolver path=satisfied (Path is satisfied), interface: lo0] flow:finish_connect
0.006s [C1.2 BC120717-4F38-4F73-96DC-3653812AAB1B 127.0.0.1:51202<->127.0.0.1:9095 socket-flow path=satisfied (Path is satisfied), interface: lo0] flow:changed_viability
0.006s [C1 80C0308D-351A-4523-BA72-7630A9806E97 Hostname#9b9b1e2c:9095 resolver path=satisfied (Path is satisfied), interface: lo0] flow:changed_viability
0.496s [C1] path:cancel
nw_flow_disconnected [C1.2 127.0.0.1:9095 cancelled socket-flow ((null))] Output protocol disconnected
nw_connection_report_state_with_handler_on_nw_queue [C1] reporting state cancelled

**Comment by NickIliev** [comment]
@jholmes12 the issue doesn't sound related to Angular or `nativescript-angular`. The provided application would be hard to test as the Spotify API requires [additional setup](https://github.com/jholmes12/nativescript-spotify-appremote-sample/blob/master/src/app/spotify.service.ts#L16-L20). 

Please consider posting the issue in the community channels like SO or the NativeScript community slack and/or the Spotify GitHub issues.

**Comment by edusperoni** [comment]
@NickIliev I know this isn't related to `nativescript-angular` but maybe this problem is a bit deeper and deserves it's on issue on ios-runtime.

nativescript-websockets also gets `TCP Conn 0x----- canceled` which I assumed it was a problem with the current plugin implementation, but maybe it isn't, as the problem also happens with spotify, which seems like is using a websocket as well.

https://github.com/NathanaelA/nativescript-websockets/issues/63
https://github.com/NathanaelA/nativescript-websockets/issues/61
https://github.com/edusperoni/nativescript-mqtt/issues/9

**Comment by jholmes12** [comment]
@edusperoni thanks for your reference and information with the other links! I actually was able to re-configure a few things with the plug-in implementation and it appears to be working now. Still not exactly sure how or why that would have fixed it, but will continue to work with it and see if that was the case.
