### ISSUE TITLE
Plugin with Angular component templateUrl & Css

### ISSUE THREAD

**Issue by juniorschen** [NativeScript/nativescript-angular#2109]
**Environment**
"@angular/core": "^8.2.14",
"tns-core-modules": "^6.0.0",
"tns-platform-declarations": "^6.0.0",
"typescript": "~3.4.5",
"prompt": "^1.0.0",
"rimraf": "^2.6.3",
"tslint": "^5.12.1",
"semver": "^5.6.0"

**Describe the bug**
Hello I was trying to create a nativescript plugin, I wanted to add a nativescript-angular component to use in my application, but when I add an html and css file to my component and the demo-angle I use it, but when I do build my plugin and use it in my native-angular application, I get the following error:
Error: Could not resolve /../../src/node_modules/nativescript-test/angular/teste.component.html.
But when I declare html in my "template" component all goes well, so does css.

**To Reproduce**
Use an angular component with "templateUrl" and "styleUrls" in a plug-in, build it in a native-angular application

**Expected behavior**
Can use templateUrl and styleUrls in Angular plugin component.

**Sample project**
https://github.com/juniorschen/Mobile

![image](https://user-images.githubusercontent.com/46031261/72568251-7953b400-3896-11ea-9ba2-00b24fd3e594.png)

**Comment by NickIliev** [comment]
@juniorschen l[ooking at this documentation section ](https://docs.nativescript.org/angular/plugins/angular-plugin)it appears that your plugin is lacking some of the requirements like created directives - please double-check your plugin structure with the one created in the documentation article

**Comment by juniorschen** [comment]
> @juniorschen l[ooking at this documentation section ](https://docs.nativescript.org/angular/plugins/angular-plugin)it appears that your plugin is lacking some of the requirements like created directives - please double-check your plugin structure with the one created in the documentation article.
> 
> Note: I am able to build your GitHub demo and the app is running without any errors on my side/


Yes, if you can create a demo of my project it would be great, i'm starting with angular plugins/ nativescript-angular and i'm still very confused

**Comment by juniorschen** [comment]
The problem is that I didn't find any reference using html and css, I looked in some githubs but I didn't find any demo contemplating html and css, would you have a simple example demonstrating this? I didn't find it in your documentation

**Comment by juniorschen** [comment]
@NickIliev Look i create a new repo, fork of plugin seed:
https://github.com/juniorschen/nativescript-plugin-seed
And i trying to use a sample nativescript/angular component (not Directives present in your documentation) with html and css.
Its work fine when i run in test ambient (import from ../src in demo-angular):
![image](https://user-images.githubusercontent.com/46031261/74840719-3b6b0500-5306-11ea-8d8f-67bf17f782dc.png)
But when i build this plugin and install (from verdaccio/proget/npm etc...) in my demo-angular, give me this error:
Error: Could not resolve test.component.html. Looked for: /data/data/org.nativescript.demoangular/files/app/test.component.html.
![image](https://user-images.githubusercontent.com/46031261/74841028-bdf3c480-5306-11ea-9bde-000daf164a12.png)

I just want to create a plugin with html / css, as nativecript / angular does, because it makes it very easy to develop, its possible?

**Comment by NickIliev** [comment]
@juniorschen you are approaching the problem from the wrong side - you are trying to create Angular UI via HTML file that contains a mobile element (ActionBar + Label). What you actually could do is to create the UI logic in your NativeScript part of the plugin and then follow the Angular steps to create a directive that will allow you to register your own element in any Angular HTML file.

See how to create the "wrapper" [here](https://docs.nativescript.org/angular/plugins/angular-plugin#angular-wrapper) and if for example your UI element is called `MyCustomLabel` then after creating the Angular directive as shown in the documentati0n you will be able to do something like :

```
<MyCustomLabel text="custom text"></MyCustomLabel>
```

The directive is sparing the need for your UI component to be registered by the users with the `registerElement` method (you will provide this out-of-the-box via the code shown in the documentation).

Note: The **ActionBar** is a bit more specific and is not the trivial UI component. On iOS behind the `ActionBar`, the native component is UINavigationBar which is not exactly a UI component as it also handles the navigation in iOS. So when making a custom ActionBar you have to know that you are going to be limited in the implementation as you can have an action bar whenever you want and there are some cases where you can simply remove it.

**Comment by juniorschen** [comment]
@NickIliev  
So, first I have to create my plug-in for Android and iOS, after that, do i need to create a wrapper to be able to use this in my angular application, through the directives?

**Comment by NickIliev** [comment]
@juniorschen have you read & tried the plugin article in the documentation (linked above) - it should answer both of your questions. 

By the way, you are not obligated to create a plugin - you can directly develop directives inside your Angular based application (but then, of course, you won't be able to reuse this as a plugin would allow you to)
