### ISSUE TITLE
Support Angular Backend Proxying config

### ISSUE THREAD

**Issue by csimpi** [NativeScript/nativescript-angular#2114]
**Is your feature request related to a problem? Please describe.**

During local development when you want to reach your backend server it can be complicated from the served angular project. Have to setup CORS, change and handle the base URL based on the environment (test/staging/production).

Angular solves this problem with a very awesome workaround:
https://angular.io/guide/build#proxying-to-a-backend-server 

Unfortunately, this doesn't work with `NativeScriptHttpClientModule` some reason. 

**Describe the solution you'd like**

Please, support this feature in `NativeScriptHttpClientModule`
https://angular.io/guide/build#proxying-to-a-backend-server 

**Describe alternatives you've considered**

Maybe use interceptors? But it would be awesome to support the Angular's official workaround.

**Additional context**

**Comment by sublime392** [comment]
I had the same issue; got it working decently. I run a backend Laravel server on homestead. My proxy.conf.json looks like the following. Normally this is all the is needed.
`{
  "**/api/**": {
    "target": "http://ib",
    "secure": false,
    "changeOrigin": true
  },
  "/ipay/v1/**": {
    "target": "http://ib",
    "secure": false,
    "changeOrigin": true
  },
  "/sap/**": {
    "target": "http://ib",
    "secure": false,
    "changeOrigin": true
  },
  "/storage/**": {
    "target": "http://ib",
    "secure": false,
    "changeOrigin": true
  }
}
`
But to have it work with NativeScript, I had to do two additional changes.
1. add a `host 0.0.0.0` to the start line in package.json. Actually, I already had it in there for when I test my website from another computer on my network. So the start line looks like:
`ib-ng --configuration=development --aot --proxy-config proxy.conf.json --host 0.0.0.0`

2. Find out what my local ip4 address is before starting and set the full path to all the urls defined in  my project. e.g. `apiEndpoint: 'http://192.168.0.20:4200/api/v1'`

I don't think I had to change anything else, and it works.

**Comment by csimpi** [comment]
Thank you, but I don't think this is going to work with android platform, this is going to works with ng serve only as I understand.

This is my workaround, I've added an interceptor:

```
import { Injectable, isDevMode} from '@angular/core';
import { HttpRequest, HttpHandler, HttpEvent, HttpInterceptor } from '@angular/common/http';
import { Observable } from 'rxjs';

import { AuthenticationService} from "../services/authentication.service";
import {isAndroid} from "tns-core-modules/platform";
import {environment} from "../../environments/environment";

@Injectable()
export class BackendProxyInterceptor implements HttpInterceptor {
  constructor(private authenticationService: AuthenticationService) { }

  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    //console.log('request.url',request.url,request);
    let origReqUrl = request.url;
    //Use this only dev environment and NS otherwise proxy.json works
    let newUrl = isAndroid && isDevMode ? 'http://vagrant.mtp.travel'+request.url : request.url;
    console.log('Change the request URL:',origReqUrl,newUrl);

    request = request.clone({ url: newUrl });

    return next.handle(request);
  }
}
```

**Comment by csimpi** [comment]
@NickIliev Why did you close this? It's NOT solved, only a workaround has been offered by me, but it's still very frustrating I can't initialize things before the app starts.
