### ISSUE TITLE
how to use native scriptrenderer ?

### ISSUE THREAD

**Issue by ppyoosuf** [NativeScript/nativescript-angular#2118]
When I trying to use nativescriptrenderer getting error like

StaticInjectorError(AppModule)[RegistrationComponent -> NativeScriptRenderer]

Should I add any moulds or services ?

Any idea to resolve this one  ?

**Comment by ppyoosuf** [comment]
Sample code 
===========
```
constructor(
		private renderer: NativeScriptRenderer,
		private cdRef:ChangeDetectorRef
	) {

}


//method to change the position of the view component

const viewElement = this.page.getViewById('floating-' + field).nativeView;
			if (viewElement) {
				this.renderer.removeChild(this.advancedFieldsLayout.nativeElement, viewElement);
				this.renderer.appendChild(this.mandatoryLayout.nativeElement, viewElement);

}
```

When I try, getting error like 'StaticInjectorError(AppModule)[RegistrationComponent -> NativeScriptRenderer]'

I did not load any modules to include nativeScriptRenderer. Do we need to add any modules in app module

**Comment by edusperoni** [comment]
You shouldn't try to inject NativeScriptRenderer, but `Renderer2`:

https://github.com/JoshDSommer/nativescript-ngx-shadow/blob/master/lib/src/nativescript-ngx-shadow/ng-shadow.directive.ts#L50

**Comment by ppyoosuf** [comment]
Hi @edusperoni 

I tried with Renderer2. Unfortunately the validation for form control is not working in ios after  call the remove and appendChiled method. But i's working perfectly in android. 

So i tried with NativeScriptRenderer.

Thanks

**Comment by edusperoni** [comment]
@ppyoosuf in this case t you should describe the bug with renderer2 in your issue, because it should work.

NativeScriptRenderer is injected when you inject Renderer2

**Comment by ppyoosuf** [comment]
Hi @edusperoni 

I have created one sample playground project. Please check it

https://play.nativescript.org/?template=play-ng&id=17PwMx

Issue:-

I have created a form which contains two fields like firstName and lastName. the firstName field is initially in mandatory field section but the lastName field is in optionalField section.

When i enter values in both fields and tap submit button it will print both values in console. But if I tap the 'reposition' button and change the value in lastName field it will not change in console out put(It's happening in IOS only. working in android)

**Comment by edusperoni** [comment]
@ppyoosuf I'm sorry, I never saw your reply until now that I'm taking a look at some old issues in this repo.

If you still need this, let me give some small summary of what's going on:

NativeScript has a few limitations on view creation/deletion. Adding a view can be costly, as it creates all the native stuff when you add a view, if that view's parent is attached to the view tree (loaded). When the view is removed, NativeScript believes the view will not be used anymore. On android this doesn't have much of an impact, as views are created again if you reinsert, but iOS has a few limitations (views are reordered but a lot of the delegates are lost).

This is why I created the option to create reusable views in core: https://github.com/NativeScript/NativeScript/pull/9163

This should solve issues with removing/adding views (do `this.view.nativeElement.reusable = true`, just have to remember to call `destroyNode()` to clean the views up on ngOnDestroy!). With angular 12 this is already done for you https://github.com/NativeScript/angular/blob/main/packages/angular/src/lib/nativescript-renderer.ts#L154 (unless you create the view yourself, in which case we have no management over it)

The Angular 12 integration also exposes the injection token `ENABLE_REUSABE_VIEWS` which you can set to true and all views are automatically reusable (still experimental at this point).

For your scenario, the best case is probably using `ngIf` or `ngFor` to reorganize your views, but you can give reusable views a try and see if they're a good fit.
