### ISSUE TITLE
Nativescript Angular BottomNavigation Horizontal Scroll

### ISSUE THREAD

**Issue by IyyappanAmirthalingam** [NativeScript/nativescript-angular#2119]
**When I have more than 5 items in the BottomNavigation Nativescript Angular there is no scrolling enabled.**
 

**BottomNavigation with scrollbar**

**In case of apps with only BottomNavigation it is good to have scroll enabled.**

**Comment by NickIliev** [comment]
@IyyappanAmirthalingam the BottomNavigaiton is not meant to support an unlimited number of tabs. Both iOS guidelines and Android material design are recommending side-drawer based interface for 5 and more options
