### ISSUE TITLE
Form control validation not working in IOS after remove and append operation by Renderer2

### ISSUE THREAD

**Issue by ppyoosuf** [NativeScript/nativescript-angular#2120]
**Environment**
   CLI: 5.1
   IOS : 5.1
 
**Describe the bug**
I tried  to remove and append the position of the textfield component to anther layout by angular Renderer2 service. It works fine in android. But in ios the position was changed but the validation not working after this operation.

**To Reproduce**
Create a reactive form component with some validation.
Try to remove and append one form component to the another layout.
Check whether the validation is working before and after

Thanks

**Comment by NickIliev** [comment]
@ppyoosuf the best approach would be to post a demo app that demonstrates how you are cresting the form component and how are you appending/removing components. Without the actual test app it is hard to say what  are you dealing with.
