### ISSUE TITLE
RouterExtensions back() not working

### ISSUE THREAD

**Issue by larxenne** [NativeScript/nativescript-angular#2129]
**Environment**
 - NativeScript-Angular: 8.21.0
 - Angular: 8.2.13
 
**Describe the bug**
I am trying to use the RouterExtensions back method.

I am keep getting that error:
`ERROR TypeError: frame_1.Frame.topmost is not a function`

Do you have any idea about what is happening and how to fix it ?

**Comment by NickIliev** [comment]
@larxenne please provide a demo project (or Playground) that can reproduce the issue above.
