### ISSUE TITLE
page-router-outlet child of named page-router-outlet is not displaying content

### ISSUE THREAD

**Issue by jeanpaulattard** [NativeScript/nativescript-angular#2131]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.4.1
 - Cross-platform modules: 6.4.2
 - Android Runtime: 6.4.1
 - iOS Runtime: 6.4.2
 - NativeScript-Angular: 8.20.4
 - Angular: 8.2.14
 
**Describe the bug**
've encountered an issue in Nativescript Angular where content of a page-router-outlet is not rendered when it is a child of a named page-router-outlet.

I've created a playground to show the differences between the behavior of a PRO that is a child of the default PRO, and a PRO that is the child of a named (auxiliary) page router outlet.

Structure is as follows

- Root PRO (app component)
  - PRO (Home Component)
    - PRO (Unnamed component) (yellow part in preview)
      - Content (named child component) (gray part in preview)
  - Named PRO (Home Component)
    - PRO (Named Component) (Red part in preview)
      - Content (Unnamed child component) (Orange part in preview)
With the above structure, the content that should be rendered in the page-router-outlet of the Named component, ie. that is a child of a named page router outlet, is not rendered, and no orange part is shown.

If the PRO of the Named Component is changed to an Angular <router-outlet></router-outlet> element, the orange part is rendered.

I am doing something wrong in attempting to render the orange content?

**To Reproduce**
Here's the url of the playground app https://play.nativescript.org/?template=play-ng&id=3GMdit

**Expected behavior**
Content of PRO that is a child of a named PRO should be rendered

**Comment by NickIliev** [comment]
@jeanpaulattard this seems to be a limitation as the root PRO is already unnamed and you can't have a nested PRO that s unnamed. Still, the workaround is pretty straight forward - just don't create unnamed outlet. This should be easy to follow as I see not actual benefit of having an unnamed outlet (compared to creating a named one).

https://play.nativescript.org/?template=play-ng&id=3GMdit&v=2

**Comment by jeanpaulattard** [comment]
@NickIliev can you please provide a plunker to show me what you're trying to say please?

Because in https://play.nativescript.org/?template=play-ng&id=3GMdit&v=3 the gray and orange parts, that should be rendered (these are children of another page router outlet in ```UnnamedComponent``` and ```NamedComponent``` respectively are still not being rendered.

Would appreciate it if you could offer a working plunker with the solution, otherwise reopen the issue please.
