### ISSUE TITLE
TextUtils.TruncateAt.START bug

### ISSUE THREAD

**Issue by Theo-Sioris** [NativeScript/nativescript-angular#2132]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

Your current version is 6.3.3 and the latest available version is 6.4.1.
Your current version is 6.2.3 and the latest available version is 6.4.2.
 Your current version is 6.2.0 and the latest available version is 6.4.1.
Your current version is 6.2.0 and the latest available version is 6.4.2.
 
**Describe the bug**

I want to have a label with a set number of lines and truncate the text at the start, but it only works if the text is one line (works as expected when `TruncateAt.END`).

**To Reproduce**

````html
  <label #myLabel
    [textWrap]="true"
    [text]="'Long text here'">
  </label>
````

````typescript
 @ViewChild("myLabel", {static: false}) public myLabel;

public styleText() {
// Works fine with END or if textWrap is removed from html
        this.myLabel.nativeElement.android.setEllipsize(android.text.TextUtils.TruncateAt.START);
        this.myLabel.nativeElement.android.setMaxLines(2);
 }
````
**Expected behavior**

To add `...` at the begining of the text

**Comment by NickIliev** [comment]
@Theo-Sioris I guess there is a conflicting native settings when using the `textWrap` property from NativeScript and trying to set the truncate natively. You could try to set them both natively.
