### ISSUE TITLE
Cannot navigate to nativescript tab

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/nativescript-angular#2143]
I have problems to navigate to root tabs. I have seen many examples with nested tabs navigation but not even one with root tab navigation. Could not imagine that it might be so complex or it is a bug. I have in root simple 3 tabs

```
export const routes: Routes = [
{
    path: '',
    redirectTo: '/(ATab:A//BTab:B//CTab:C)',
    pathMatch: 'full'
},

{
    path: 'A',
    component: NSEmptyOutletComponent,
    loadChildren: () => import('@src/app/components/search/A.module').then((m) => m....),
    outlet: 'ATab',
    ...authGuards,
},
{
    path: 'B',
    component: NSEmptyOutletComponent,
    loadChildren: () => import('@src/app/components/inquiries/B.module.tns').then((m) => m.....),
    outlet: 'BTab',
    ...authGuards,
},
{
    path: 'C',
    component: NSEmptyOutletComponent,
    loadChildren: () => import('@src/app/components/account/C.module').then((m) => m.....),
    outlet: 'CTab',
    ...authGuards,
}
```
In each module there is child empty route

`
export const routes: Routes = [
{ path: '', component: BComponent }
];
`
From what i understand in order to navigate to BTab i should do something like:

```
this.routerExtension.navigate([
         '/', { outlets: { BTab: ['B'] } },
        ]);
```
But it does not work. I have tried many other solutions but just no...

**Comment by vytautas-pranskunas-** [comment]
I thought that it is possible by using router navigate through tabs also. I realised that i need to rigger tabs switch manually

**Comment by anhtata** [comment]
I got the same issue.
