### ISSUE TITLE
When adding selectedIndex on BottomNavigation first tab is frozen

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/nativescript-angular#2144]
I have BottomnNavigation and if i add [selectedIndex]="0" first tabs content is frozen. This does not apply if i add any other value then 0 - 1, 2 etc.

This also does nto applies if i add  selectedIndex="0"

```
BottomNavigation [selectedIndex]="0" (selectedIndexChanged)="onSelectedIndexChanged($event)">
            <TabStrip isIconSizeFixed="false">...
```

Also some elements are not rendered at all for example some images..
You can see from attached images same tab content with and without selectedIndex - button is frozen and button is clicable

![image](https://user-images.githubusercontent.com/3918999/79053678-6b1bf680-7c3f-11ea-8fb4-fed5465c1eca.png)

![image](https://user-images.githubusercontent.com/3918999/79053700-8a1a8880-7c3f-11ea-9369-a3cea29ef351.png)

If you want some reproducable playground you can try by taking this example: https://docs.nativescript.org/angular/ui/ng-components/bottom-navigation

because i did not change much...
This is huge issue because i want to bind tab to state...

**Comment by NickIliev** [comment]
@vytautas-pranskunas- the issue is not reproducible on my side - here is [a Playground demo ](https://play.nativescript.org/?template=play-ng&id=sK0ywC)using the documentation example.

**Comment by vytautas-pranskunas-** [comment]
Actually it is. I am a bit shocked how fast you are trying to close issues. It i snot m aking development experience better using nativescript...

I have created playground:
https://play.nativescript.org/?template=play-ng&id=J5oNhi&v=2

It is big issue for me please advice how to solve it

**Comment by limyandi** [comment]
Hi vytautas-pranskunas, did you ever fix this? I am still having the same issue...

**Comment by limyandi** [comment]
@vytautas-pranskunas-

**Comment by vytautas-pranskunas-** [comment]
No... NS has no bright future sry to say that. I switched to other tech
stack after a month of tryings and do not regret
