### ISSUE TITLE
Progress valueChange event not firing

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/nativescript-angular#2145]
I have working progress. It is weired, because this kind of bug should be noticed by other users but i cannot make (valueChange) event fired.

```
<Progress #progress [value]="actions.progress?.value" [maxValue]="actions.progress?.maxValue" class="progress"
            (valueChanged)="onProgressLoaded($event)"></Progress>
```

**Comment by NickIliev** [comment]
the event is **valueChange** (and not _valueChanged_).

Use [this Playground ](https://play.nativescript.org/?template=play-ng&id=3xOx6r&v=2)as a reference.
