### ISSUE TITLE
Execution failed for task ':app:mergeDebugAssets'.=> After migrate from 5.1.0 to 6.5.0

### ISSUE THREAD

**Issue by murtirahayu** [NativeScript/nativescript-angular#2149]
**Describe the bug**

After migrate from 5.1.0 to 6.5.0, i am get error like :
![image](https://user-images.githubusercontent.com/7122367/79443308-dda42200-8003-11ea-962e-14dbbd8c8db5.png)

i do this step :
1. tns platform remove android
1. tns platform add android
1. tns run android

But, still getting the same error.

Please help me, sir. Thank you.

**Comment by murtirahayu** [comment]
**the above problem is complete. but there is a new problem**

JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'readTex
t' of undefined
JS: TypeError: Cannot read property 'readText' of undefined
JS:     at file: node_modules\@nativescript\core\file-system\file-system-access.
android.js:249:0
JS:     at new ZoneAwarePromise (file: node_modules\@nativescript\angular\zone-j
s\dist\zone-nativescript.js:902:0)
JS:     at FileSystemAccess.push.../node_modules/@nativescript/core/file-system/
file-system-access.js.FileSystemAccess.readTextAsync (file: node_modules\@native
script\core\file-system\file-system-access.android.js:247:0)
JS:     at file: node_modules\@nativescript\core\file-system\file-system.js:277:
0
JS:     at new ZoneAwarePromise (file: node_modules\@nativescript\angular\zone-j
s\dist\zone-nativescript.js:902:0)
JS:     at File.push.../node_modules/@nativescript/core/file-system/file-system.
js.File.readText (file: node_modules\@nativescript\core\file-system\file-system.
js:268:0)
JS:     at file: node_modules\nativescript-ngx-fonticon\services\fonticon.servic
e.js:48:0
JS:     at new ZoneAwarePromise (file:///data/data/co.id.fasapay.mobile/files/ap
p/vendor.js:9068...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onViewAttachedToWindow failed
System.err: TypeError: Cannot read property 'extend' of undefined
System.err: StackTrace:
System.err: __extends(/data/data/co.id.fasapay.mobile/files/internal/ts_helpers.
js:51:36)
System.err:     at (file: node_modules\@nativescript\core\ui\frame\fragment.andr
oid.js:4:0)
System.err:     at (file: node_modules\@nativescript\core\ui\frame\fragment.andr
oid.js:54:1)
System.err:     at ../node_modules/@nativescript/core/ui/frame/fragment.js(file:
///data/data/co.id.fasapay.mobile/files/app/vendor.js:113134:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:750:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ensureFragmentClass(file: node_modules\@nativescript\core\ui\
frame\frame.android.js:624:4)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.Fra
me.createFragment(file: node_modules\@nativescript\core\ui\frame\frame.android.j
s:209:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.Fra
me._navigateCore(file: node_modules\@nativescript\core\ui\frame\frame.android.js
:303:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame-common
.js.FrameBase.performNavigation(file: node_modules\@nativescript\core\ui\frame\f
rame-common.js:300:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame-common
.js.FrameBase._processNextNavigationEntry(file: node_modules\@nativescript\core\
ui\frame\frame-common.js:291:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.Fra
me._processNextNavigationEntry(file: node_modules\@nativescript\core\ui\frame\fr
ame.android.js:160:0)
System.err:     at push.../node_modules/@nativescript/core/ui/frame/frame.js.Fra
me._onAttachedToWindow(file: node_modules\@nativescript\core\ui\frame\frame.andr
oid.js:128:0)
System.err:     at AttachListener.onViewAttachedToWindow(file: node_modules\@nat
ivescript\core\ui\frame\frame.android.js:39:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)

System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1160)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1138)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1134)
System.err:     at com.tns.gen.java.lang.Object_vendor_114428_36_AttachListener.
onViewAttachedToWindow(Object_vendor_114428_36_AttachListener.java:18)
System.err:     at android.view.View.dispatchAttachedToWindow(View.java:13818)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.jav
a:2901)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.jav
a:2909)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.jav
a:2909)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.jav
a:2909)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.jav
a:2909)
System.err:     at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.jav
a:2909)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java
:1300)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1062)

System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.
java:5873)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.j
ava:767)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:580
)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:550)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Chor
eographer.java:753)
System.err:     at android.os.Handler.handleCallback(Handler.java:739)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:135)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5753)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(Zy
goteInit.java:1405)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

ActivityManager: Process co.id.fasapay.mobile (pid 17796)(adj 0) has died(195,16
5)
ActivityManager: cleanUpApplicationRecord -- 17796

**Comment by NickIliev** [comment]
Please follow the report a bug template and provide all of the requested information

```
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):
 - NativeScript-Angular:
 - Angular:
 
**Describe the bug**
<!-- A clear and concise description of what the bug is. Please, explain whether it's a build time error or a runtime error. More detailed logs can be easily obtained by following the instructions in this guide: https://docs.nativescript.org/get-support#how-to-obtain-diagnostic-reports. -->

**To Reproduce**
<!-- Add commands used or steps taken to reproduce the behaviour. -->

**Expected behavior**

**Sample project**
<!-- If possible, provide a link from the [Playground](https://play.nativescript.org) with reproduction of the problem. If not, consider attaching a sample project or link to a repository with such project. -->

**Additional context**
<!-- Add any other context about the problem here. -->

```
