### ISSUE TITLE
import {RouteConfig} from '@angular/router-deprecated' instead

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-angular#215]
Hi, the Navigation examples are configured to use RouteConfig which is only on router-deprecated, not router.

Check the [Angular Changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02)

**Comment by hdeshev** [comment]
@leocaseiro Thanks for pointing that out!

We'll release a RC1-compatible update very soon (todayish), and that will use @angular/router-deprecated.

**Comment by leocaseiro** [comment]
Cheers, I had lot's of issues trying to make work and I gave up...
Cheers!
