### ISSUE TITLE
background-image is not working

### ISSUE THREAD

**Issue by FengLin96** [NativeScript/nativescript-angular#2150]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - tns-core-modules: 6.5.0
 - Cross-platform modules:
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
 - NativeScript-Angular: 8.21.0
 - Angular: 8.2.0

_package.json file screenshot_

 [![Image from Gyazo](https://i.gyazo.com/20a7ec48e3067ab0c3001dda47c0f8d1.png)](https://gyazo.com/20a7ec48e3067ab0c3001dda47c0f8d1)

**Describe the bug**

 I tried to set a background image for a flexboxLayout but it doesn't work. I have tried via css and property + databinding, as shown on the example located in marketplace (https://play.nativescript.org/?template=play-ng&id=GYAGpS&v=1). I can change the background colors. It doesn't work on Android an iOS

**Sample project**

**set background image with css**
[![Image from Gyazo](https://i.gyazo.com/514bb603a2618da984c2196f03cfbd6c.png)](https://gyazo.com/514bb603a2618da984c2196f03cfbd6c)

[![Image from Gyazo](https://i.gyazo.com/146c379fd108aac72617f52c5330dc04.png)](https://gyazo.com/146c379fd108aac72617f52c5330dc04)

------

**set background image with property and databinding**
[![Image from Gyazo](https://i.gyazo.com/176dab3e9834091f5f591176a43f1fa6.png)](https://gyazo.com/176dab3e9834091f5f591176a43f1fa6)

[![Image from Gyazo](https://i.gyazo.com/1f978870c8058fd8ec0483c4109e7df2.png)](https://gyazo.com/1f978870c8058fd8ec0483c4109e7df2)

I am a Nativescript beginner, thank you in advance for your help

**Comment by NickIliev** [comment]
@FengLin96 you code works as expected on my side with (here is[ the test Playground](https://play.nativescript.org/?template=play-ng&id=GYAGpS&v=348)) - try to change the f8ile name to use only small letters (not sure if Android handle capital letters) and if not check the demo for differences in your code.

**Comment by FengLin96** [comment]
Same code works for online playground but does not work from project created via sidekick. Weird
