### ISSUE TITLE
Modal CloseCallback in a subscribe of an observable is called after the closing component .then

### ISSUE THREAD

**Issue by pandabuilt** [NativeScript/nativescript-angular#2153]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules: 6.3.1
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):
 - NativeScript-Angular: ^8.20.4
 - Angular: ^8.1.3
 
**Describe the bug**

this._modalService.showModal(ArriveDepartComponent, options).then((result)=>{
      console.log(test);
      console.log(result);
});

 gets called BEFORE this.params.closeCallback(responseData); is called when this.params.closeCallback(responseData) is in an observable subscribe.

**To Reproduce**

Put the closeCallback method inside a subscribe.

**Expected behavior**
The Then would get called with the appropriate data being called. 

**Sample project**

**Additional context**

**Comment by facetious** [comment]
Can you provide a playground (or at the very least a proper source snippet) that reproduces what you describe? For example, what is `params`, what is `_modalService.showModal`, and in which `subscribe` are you suggesting this is placed?
