### ISSUE TITLE
Remove border from Search Bar

### ISSUE THREAD

**Issue by mm-spiio** [NativeScript/nativescript-angular#2161]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.5.0
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: 13.4.1
 - Plugin(s):
 - NativeScript-Angular: 8.21.0
 - Angular: 8.2.14
 
**Describe the bug**
Cannot remove border from search bar

**To Reproduce**
`border-color: "red";` and has no effect

**Expected behavior**
expected the border of the search bar to be red and therefore not having the black thin border above the search bar disrupting the ui.

**Sample project**
https://play.nativescript.org/?template=play-ng&id=qJqG8y

**Comment by Meyer-dev** [comment]
Hi.
You can try this code,it will give you something with a red border,you can
then just change to whatever colour you want. Cant see where your problem
is from the playground code. Hope this helps you. Regards, Meyer

<StackLayout>
<GridLayout  style="
background-color: #f1efef; border-width:1.5;border-color:red;border-radius:22;
" class="m-x-15 m-t-2" rows="auto" cols="*,auto,*">
    <SearchBar col="1"
        style="background-color: #f1efef; opacity:1;" width="90%"
        hint="Find products"
        class="text-center m-y-5"  textFieldBackgroundColor="#f1efef" >
    </SearchBar>
</GridLayout>
<label class="m-x-10" textwrap="true" text="hello"></label>
</StackLayout>

**Comment by mm-spiio** [comment]
This is the issue, see that thin border in the picture 
![image](https://user-images.githubusercontent.com/61713248/81295807-47e33c00-9071-11ea-8062-346d5640cc48.png)

**Comment by jessorlisa** [comment]
@mm-spiio I just had the same problem and have been able to resolve it with [this solution](https://github.com/NativeScript/NativeScript/issues/4319#issuecomment-386316078).

**Comment by mm-spiio** [comment]
Thanks that worked!
