### ISSUE TITLE
`application.systemAppearance()` failing for iOS

### ISSUE THREAD

**Issue by jessorlisa** [NativeScript/nativescript-angular#2166]
**Environment**
 - CLI: 6.5.0
 - Cross-platform modules: 6.5.1
 - Android Runtime: 6.5.0
 - iOS Runtime: 6.5.0
 - Plugin(s): @nativescript/theme@2.3.3
 - NativeScript-Angular: 8.21.0
 - Angular: 8.2.14
 
**Describe the bug**
`application.systemAppearance()` is failing for iOS with the following error and stack trace
```
CONSOLE ERROR file: node_modules/@angular/core/fesm5/core.js:4002:0: ERROR Error: Uncaught (in promise): TypeError: null is not an object (evaluating 'this.rootController.traitCollection')
get(file: node_modules/@nativescript/core/application/application.ios.js:100:0)
at systemAppearance(file: node_modules/@nativescript/core/application/application.ios.js:419:0)
at ItemsComponent(file: src/app/item/items.component.ts:17:72)
at createClass(file: node_modules/@angular/core/fesm5/core.js:21148:0)
at createDirectiveInstance(file: node_modules/@angular/core/fesm5/core.js:21027:0)
at createViewNodes(file: node_modules/@angular/core/fesm5/core.js:29387:0)
at createRootView(file: node_modules/@angular/core/fesm5/core.js:29301:0)
at callWithDebugContext(file: node_modules/@angular/core/fesm5/core.js:30309:0)
at file: node_modules/@angular/core/fesm5/core.js:20506:0
at file: node_modules/@angular/core/fesm5/core.js:20617:0
at file: node_modules/@nativescript/angular/common/detached-loader.js:38:0
at file: node_modules/@nativescript/angular/router/page-router-outlet.js:300:0
at file: node_modules/@nativescript/angular/router/page-router-outlet.js:270:0
at file: node_modules/@angular/router/fesm5/router.js:2310:0
at file: node_modules/@angular/router/fesm5/router.js:2261:0
at forEach([native code])
at file: node_modules/@angular/router/fesm5/router.js:2260:0
at file: node_modules/@angular/router/fesm5/router.js:2185:0
at file: node_modules/@angular/router/fesm5/router.js:2169:0
at file: node_modules/rxjs/_esm5/internal/operators/map.js:35:0
at file: node_modules/rxjs/_esm5/internal/Subscriber.js:53:0
at file:///ap<…>
```
**To Reproduce**
Setup new Angular based project:
```
tns create testSystemAppearanceNg --ng
cd testSystemAppearanceNg
```
Change the content of `src/app/item/items.component.ts` to:
```
import { Component, OnInit } from "@angular/core";

import * as application from "@nativescript/core/application";

import { Item } from "./item";
import { ItemService } from "./item.service";

@Component({
    selector: "ns-items",
    templateUrl: "./items.component.html"
})
export class ItemsComponent implements OnInit {
    items: Array<Item>;

    constructor(private itemService: ItemService) {

        // check for current systemAppearance (dark or light):
        console.log('systemAppearance >>>', application.systemAppearance());
    }

    ngOnInit(): void {
        this.items = this.itemService.getItems();
    }
}

```
Run for iOS:
`tns run ios`

**Expected behavior**
No error.

**Additional context**
This is only failing for iOS, Android is working fine.

**Comment by timoschlueter** [comment]
I can confirm that this is a problem on iOS. 
Any news on this?

**Comment by Final-File** [comment]
Having the same Issue. Found a workaround yet?

**Comment by lufixSch** [comment]
Having the same Issue. Any workaround yet?

**Comment by jessorlisa** [comment]
How am I supposed to check the system appearance on iOS? Any input? The issue exists still with latest NS7.

**Comment by facetious** [comment]
I've got a service that makes it easy to use in TypeScript.

```typescript
import { Injectable } from '@angular/core';
import { on as applicationOn, systemAppearanceChangedEvent, SystemAppearanceChangedEventData } from '@nativescript/core/application';
import { Observable, Subject } from 'rxjs';
import { map } from 'rxjs/operators';

const EVENT_STREAM: Subject<SystemAppearanceChangedEventData> = new Subject<SystemAppearanceChangedEventData>();

@Injectable()
export class DarkModeService {
    readonly changedAppearance$: Observable<'dark' | 'light'>;
    constructor() {
        this.changedAppearance$ = EVENT_STREAM.pipe(map((event: SystemAppearanceChangedEventData) => {
            return event.newValue;
        }));
    }
}

applicationOn(systemAppearanceChangedEvent, (event: SystemAppearanceChangedEventData) => {
    EVENT_STREAM.next(event);
});
```

In your templates, you can use the CSS classes:

```css
.ns-root.ns-light :host .my-class {
  ...
}

.ns-root.ns-dark :host .my-class {
  ...
}
```

**Comment by facetious** [comment]
I suspect it might also be an implementation issue on your side. You've called that function in the `constructor` of an injectable service. It's possible that you may be constructing that before your application has a root view controller assigned, which is what's causing the error you see.

Move it into an observable or function such that it's queried when needed, and not at application start.

**Comment by jessorlisa** [comment]
Thanks @facetious for your input. It helped me a lot finding a working solution for my use case.

It is just so irritating that some stuff is working just fine in Android and not iOS or the other way round.

**Comment by cjohn001** [comment]
> I've got a service that makes it easy to use in Angular.
> 
> ```ts
> import { Injectable } from '@angular/core';
> import { on as applicationOn, systemAppearanceChangedEvent, SystemAppearanceChangedEventData } from '@nativescript/core/application';
> import { Observable, Subject } from 'rxjs';
> import { map } from 'rxjs/operators';
> 
> const EVENT_STREAM: Subject<SystemAppearanceChangedEventData> = new Subject<SystemAppearanceChangedEventData>();
> 
> @Injectable()
> export class DarkModeService {
>     readonly changedAppearance$: Observable<'dark' | 'light'>;
>     constructor() {
>         this.changedAppearance$ = EVENT_STREAM.pipe(map((event: SystemAppearanceChangedEventData) => {
>             return event.newValue;
>         }));
>     }
> }
> 
> applicationOn(systemAppearanceChangedEvent, (event: SystemAppearanceChangedEventData) => {
>     EVENT_STREAM.next(event);
> });
> ```
> 
> In your templates, you can use the CSS classes:
> 
> ```css
> .ns-root.ns-light :host .my-class {
>   ...
> }
> 
> .ns-root.ns-dark :host .my-class {
>   ...
> }
> ```

@facetious : I just tried the service code you provided. Unfortunately, it seems that the systemAppearanceChangedEvent is only called when a change is happening. However, I need to get the dark or light mode state already on app startup, Hence in case the app was started before a change happened. Do you have an idea how I can read out the currrently set state?
