### ISSUE TITLE
Using the CLI to tns create an angular project does not compile

### ISSUE THREAD

**Issue by tb707** [NativeScript/nativescript-angular#2175]
**Environment**
 - CLI: 6.7.4
 
**Describe the bug**
Using tns create to generate an angular project results in some of the Ivy-based issues specified in other bug reports, 

i.e. ERROR in The target entry-point "@nativescript/angular" has missing dependencies: - @nativescript/core/ui/layouts/layout-base

**To Reproduce**
tns create testapp --ng
tns run android

**Expected behavior**
Created application runs on device

**Additional context**
Was able to make it work using feedback some of the other bug reports, just want to make sure that the "create" capability is fixed and maintains parity with any future fixes (it was frustrating for the sample project to immediately fail on my first foray into nativescript, could be a barrier to adoption for other users).

**Comment by NathanWalker** [comment]
Thanks for heads up @tb707 `tns create name --ng` now resolves the `ngcc.config.js` file 👍

**Comment by tb707** [comment]
Thanks heaps - awesome turnover time there.
