### ISSUE TITLE
Is Nativescript fully supported for IOS 14?

### ISSUE THREAD

**Issue by zhaoyouliang** [NativeScript/nativescript-angular#2182]
After the release of IOS 14, does native script need to be upgraded to adapt to the new IOS system? The current version of NativeScript we are using is 6.1.1. If we need to upgrade, which version should we upgrade to or will there be an updated version?
Thanks ,Looking forward to reply.

**Comment by NathanWalker** [comment]
Confirmed here: https://github.com/NativeScript/NativeScript/issues/8665
