### ISSUE TITLE
TextView Creates Weird Horizontal Line

### ISSUE THREAD

**Issue by JimLynchCodes** [NativeScript/nativescript-angular#2193]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.0",
    "nativescript-angular": "~8.21.0",
    "nativescript-ui-sidedrawer": "~8.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@nativescript/schematics": "^9.0.0",
    "@ngtools/webpack": "~8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-angular-cli": "^0.1.9",
    "nativescript-dev-webpack": "~1.5.0",
    "node-sass": "^4.7.1",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
**Describe the bug**

TextView creates a weird horizontal line underneath the text...

![Screenshot_2020-07-19-10-37-48-869_org nativescript preview](https://user-images.githubusercontent.com/5354163/87877579-27a6f600-c9ad-11ea-8d88-397e6a227207.jpg)

**To Reproduce**
create a <TextView> with text

**Expected behavior**

Should show ONLY the text.

Does anyone know _why_ this line appears? what is the reasoning for having it? How should I hide it?

Thanks!

**Comment by iamabs2001** [comment]
@JimLynchCodes 

Hey TextView is Like TextArea in html. Its a material input that's why you getting bottom border line of TextView.
You can style it in different ways by giving it class like _**class="search -border"**_ , _**class="search -circle"**_ etc.

**Comment by iamabs2001** [comment]
Different Style available 
<img src="https://docs.nativescript.org/angular/img/theme/forms-ios.png">
https://docs.nativescript.org/angular/img/theme/forms-ios.png
https://docs.nativescript.org/angular/ui/theme#forms

**Comment by JimLynchCodes** [comment]
thanks @iamabs2001!

I think it is just a case of me using the wrong component. 

I didn't realize that TextView was meant to be an input that accepts text from the user.

I really just wanted to display some text, and so for that I am not using a <Label>.

Thanks!
