### ISSUE TITLE
SassError: File to import not found or unreadable: ~@nativescript/theme/core

### ISSUE THREAD

**Issue by adams-family** [NativeScript/nativescript-angular#2205]
**Environment**
 - CLI: `tns --version` = 6.7.8
 - Cross-platform modules: `@nativescript/core has 7.0.0-rc.33 version and is up to date`
 - Android Runtime: `tns-android is not installed`
 - iOS Runtime: `tns-ios has 6.5.2 version and is up to date`
 - Plugin(s): -
 - NativeScript-Angular: `10.0.0`
 - Angular: `10.0.4`
 
**Describe the bug**
Both `tns preview` and `tns run ios` throw the following error

```
ERROR in ./app.scss
Module build failed (from ../node_modules/sass-loader/dist/cjs.js):
SassError: File to import not found or unreadable: ~@nativescript/theme/core.
        on line 1 of src/_app-common.scss
        from line 2 of /Users/user/Documents/Projects/NativeScript/test/src/app.scss
>> @import "~@nativescript/theme/core";

   ^

 @ ../node_modules/@nativescript/webpack/load-application-css-angular.js 5:49-65 6:47-63
 @ ./main.tns.ts
```

**To Reproduce**
```
ng new -c=@nativescript/schematics test --shared --style=scss --no-theme
cd test
npm i
tns preview
```

**Expected behavior**
The app preview should start.

**Sample project**
This is a bare unmodified project generarated using the comands above.

**Comment by vijay180396** [comment]
i had same issues in android
**ERROR in ./app.css**

so i use the command to build a nativescript-angular project 
=>tns create <projectName> --template tns-template-blank-ng

and you can also install @nativescript/schematics in globally(npm i -g @nativescript/schematics) 
to install in local(npm i @nativescript/schematics)

then use command to run(tns run android **or** ios)

**Comment by adams-family** [comment]
Hi @vijay180396, thank you, I confirm that a project created from scratch as you described works and builds fine.

However, I'm trying to integrate a NativeScript app with a NRWL NX stack and set up code sharing, therefore I'm still wondering, the above code in my description should work IMO, I'm wondering whether I'm doing something wrong?

**Comment by NathanWalker** [comment]
@adams-family are you using [xplat](https://github.com/nstudio/xplat) with Nx? If so, we're updating those for Angular 10 at the moment and should have new updates out for those schematics with full compliance with latest by early next week.

**Comment by adams-family** [comment]
Hi @NathanWalker no, this is the first time I heard about xplat. Therefore I would confidently say no :)
