### ISSUE TITLE
Module not found: Error: Can't resolve '@nativescript/angular/platform' in ./main.ts 28:0-90 53:0-67

### ISSUE THREAD

**Issue by falcorp-cloud** [NativeScript/nativescript-angular#2211]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

```
Angular CLI: 10.0.5
Node: 12.18.3
OS: darwin x64

Angular: 10.0.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.5
@angular-devkit/core         10.0.5
@angular-devkit/schematics   10.0.5
@angular/cli                 10.0.5
@ngtools/webpack             10.0.5
@schematics/angular          10.0.5
@schematics/update           0.1000.5
rxjs                         6.6.2
typescript                   3.9.7
webpack                      4.27.1

✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.8.0 version and is up to date.
✔ Component tns-core-modules has 6.5.12 version and is up to date.
⚠ Update available for component tns-android. Your current version is 6.5.0 and the latest available version is 6.5.3.
✔ Component tns-ios has 6.5.2 version and is up to date.
 ```

**Describe the bug**

After upgrading typescript and running ng update all to upgrade to version 10, I can't emulate project anymore it produces the following error

```
ERROR in ./main.ts
Module not found: Error: Can't resolve '@nativescript/angular/platform' in '../src'
 @ ./main.ts 28:0-90 53:0-67
```

**To Reproduce**

create a new angular typescript project

```
npm update
tns plugin update
tns update
ng update all
tns debug ios --device ${your_device_id}
```

**Expected behavior**

Application should run successfully after updates

**Sample project**

**Additional context**

Appears I need to update projected seeing that `"nativescript-angular": "^10.0.0",` was on version 10 but project was using angular version 9. It would be great if updates ran smoothly.

**Comment by betosalvador** [comment]
@falcorp-cloud 
Try to change from '@nativescript/angular/platform' to '@nativescript/angular'

**Comment by NathanWalker** [comment]
@betosalvador is correct - there’s no more deep imports. Everything comes from @nativescript/angular in all the latest. Reason for this is to avoid update trouble in the future. Historically the inconsistent and varied deep import paths across the integration was confusing and created a situation where every time an improvement was made it may have affect on deep import path. Everything comes from @nativescript/angular - that’s all you’ll ever need to know now and in the future.

**Comment by jmlauron118** [comment]
asdasdasd

**Comment by ethanzhu1** [comment]
> @betosalvador is correct - there’s no more deep imports. Everything comes from @NativeScript/angular in all the latest. Reason for this is to avoid update trouble in the future. Historically the inconsistent and varied deep import paths across the integration was confusing and created a situation where every time an improvement was made it may have affect on deep import path. Everything comes from @NativeScript/angular - that’s all you’ll ever need to know now and in the future.

It helped me with the issue. Thank you!
`Cannot find module '@nativescript/angular/element-registry'`
