### ISSUE TITLE
[NG10] Angular team is removing solution-style tsconfig. How is NS+NG affected?

### ISSUE THREAD

**Issue by mahmoudajawad** [NativeScript/nativescript-angular#2219]
Per the following PRs:
* https://github.com/angular/angular-cli/pull/18478
* https://github.com/angular/angular/pull/38394

Angular team is rolling-back on supporting Typescript v3.9 solution-style `tsconfig`. This is already in use by `nativescript/schmeatics` and it's resulting in getting `tsconfig` shared between web and mobile apps. However, Angular team decision is probably going to be carried on to Angular v11, meaning, taking this into consideration from now might save sometime planning next version support.

**Comment by NathanWalker** [comment]
This is a good thing, they were a bit problematic so I'm happy to hear they have decided to switch that. We'll update the schematics to match the way they go 👍

**Comment by d-koppenhagen** [comment]
I've already create an issue for the schematics: https://github.com/NativeScript/nativescript-schematics/issues/294

**Comment by mahmoudajawad** [comment]
Closing as irrelevant of today.
