### ISSUE TITLE
Angular 9,10 NSRouterLinkActive does not set CSS class

### ISSUE THREAD

**Issue by denlysenko** [NativeScript/nativescript-angular#2224]
After upgrading Angular from 8 to 10, `nsRouterLinkActive` directive stopped adding CSS class on element. Seems like the reason is in this `this.renderer.setStyle`(should be `this.renderer.addClass`) call here

https://github.com/NativeScript/nativescript-angular/blob/51bd639ab044fefff6b4f6735d2f9d20a012c156/nativescript-angular/router/ns-router-link-active.ts#L107

**Comment by NathanWalker** [comment]
Thanks @denlysenko we’ll get this updated and publish a patch this afternoon.

**Comment by NathanWalker** [comment]
@denlysenko published in 10.0.1 - let us know if you have further issue; thanks again for report.

**Comment by denlysenko** [comment]
@NathanWalker  After your fix CSS class is being added, but it's added to the link, which is not active. 
I guess you should swap `removeClass` and `addClass` in this if/else

https://github.com/NativeScript/nativescript-angular/blob/23cf9dcbdf47a6fa764c22cd6cba27a1c13de406/nativescript-angular/router/ns-router-link-active.ts#L108-L112

**Comment by NathanWalker** [comment]
Ah @denlysenko thanks, do you wanna try to submit a PR?

**Comment by denlysenko** [comment]
ok
