### ISSUE TITLE
Hot loading code changes causes frozen white screen on phone

### ISSUE THREAD

**Issue by cowchin12** [NativeScript/nativescript-angular#2234]
**Environment**
√ Getting NativeScript components versions information...
√ Component nativescript has 6.8.0 version and is up to date.
√ Component @nativescript/core has 7.0.0-rc.54 version and is up to date.
√ Component tns-android has 6.5.3 version and is up to date.
× Component tns-ios is not installed.
 
**Describe the bug**
I just got started with the default code sharing app created through the command line. I'm running a Google Pixel 2 with API Level 28 on Android Studio, and the default app shows up just fine when I run it. However, any code changes I make cause the app to refresh (awesome!), but then the app just turns into a white screen, requiring a restart to get it working as normal again. I don't see any indication of a problem in the console output, everything seems fine i.e `Successfully synced application org.nativescript.handlebar on device emulator-5554.`

**To Reproduce**
Create a new project `ng new --collection=@nativescript/schematics project-name --shared`
Start your phone emulator and run `tns run android`
Once finished loading onto the emulator and the app is displayed, make some trivial code change. A white screen will be stuck on the app and a restart will be needed. For example, I changed this line in home.component.tns.html to include an extra exclaimation mark:
`<Label [text]="'Welcome to ' + title + '!!'" class="h1 text-center" textWrap="true"></Label>`

**Expected behavior**
The app will reload with the change instead of a white screen

**Comment by domzinhuu** [comment]
Complement - When update css file sometimes work nice but only sometimes.

**Comment by cowchin12** [comment]
This was already addressed here:
https://github.com/NativeScript/NativeScript/issues/8754#issuecomment-671583792

In short, just run the app with `tns run android --no-hmr` for now @domzinhuu
