### ISSUE TITLE
Use of template elements broken after upgrade to Nativescript 7.0.0/ Angular 10

### ISSUE THREAD

**Issue by lonerzzz** [NativeScript/nativescript-angular#2240]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: ~10.1.0
 - Cross-platform modules: Unsure
 - Android Runtime:  7.0.0
 - iOS Runtime: 7.0.0
 - Plugin(s): Not applicable
 - NativeScript-Angular: ~10.1.0
 - Angular: ~10.1.0
 
**Describe the bug**
After migrating to the nativescript 7.0.0 version, I am getting the following error for numerous template items. I have tried importing them from @nativescript/core without any effect except to add more errors. Not sure how to resolve the issue or whether it is a bug as this problem did not exist prior to the upgrade to Angular 10,
```
node_modules/@nativescript/core/ui/layouts/stack-layout/index.d.ts:7:14 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

This likely means that the library (@nativescript/core) which declares StackLayout has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

7 export class StackLayout extends LayoutBase {
```

and
```
app/common/dateTimeDurationPicker.component.ts:9:2 - error NG8001: 'StackLayout' is not a known element:
1. If 'StackLayout' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

9  <StackLayout margin="24" horizontalAlignment="center" verticalAlignment="center">
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The first error occurs when I attempt to add the following to the app.module.ts
```
import { StackLayout } from '@nativescript/core';
...
@NgModule({
	imports:
	[
		...
		StackLayout
		...
```

**To Reproduce**
Cannot provide as this is part of a larger project.

**Expected behavior**
How standard elements are referenced needs to be documented if it has changed.

**Sample project**
Since the playground is not yet updated to handle Nativescript 7 / Angular 10 , I am unable to provide a version that matches.

**Additional context**
None

**Comment by lowkeyboard** [comment]
hello 
is the issue still continuing? i was wondering if the docs are up to date.

**Comment by lostation** [comment]
Just passing here.. Question... Why are you importing stacklayout from app module import ? You just need to import nativescript common module and others...for that.

**Comment by lowkeyboard** [comment]
> Just passing here.. Question... Why are you importing stacklayout from app module import ? You just need to import nativescript common module and others...for that.

probably path finding issues, i had to manually import some of the  components as well

**Comment by NidheeshMv** [comment]
Hi @NathanWalker ,

Getting this below error after upgrading to Nativescript 7 and Angular 10. I have Nativescript common module imported from @nativescript/core/common

error NG8001: 'StackLayout' is not a known element:
1. If 'StackLayout' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

Could you please provide a solution

**Comment by edusperoni** [comment]
@NidheeshMv 
The solution is the number 2 in your comment.

Also, never add a things like "StackLayout" to your imports, those are equivalent to web HTML elements, not angular modules.

**Comment by NidheeshMv** [comment]
Hi @edusperoni ,

i tried the same as well inside @Ngmodule in app.module.tns. Same i have added to the specific component module file as well. But not working

  schemas:[NO_ERRORS_SCHEMA]

**Comment by edusperoni** [comment]
@NidheeshMv does the error come from your IDE or the build?

If it comes from the IDE, it's a known issue from using code sharing with the old schematics, which is why we're moving away from them. See https://github.com/NativeScript/nativescript-angular/issues/2290#issuecomment-854226427

**Comment by NidheeshMv** [comment]
@edusperoni It is a build error not from IDE. I have .tns.* and .ts files for Web and Mobile builds. 

Recently I upgraded the project to Nativescript 7 - Angular 10. Web build is working. Facing the above issues on mobile build

**Comment by edusperoni** [comment]
> I have .tns.* and .ts files for Web and Mobile builds.

Exactly, those are known to cause problems like this and the issue I linked. I've gone more in depth in the linked comment, but the reality of it is that those different extensions cause so many fights with the angular compiler that if you fix your project to build correctly, you'd eventually get new build errors on any newer version of angular.

In the same post I provided a tool you can use to migrate to a more sane environment with nx

**Comment by NidheeshMv** [comment]
Sure @edusperoni . Thanks for your support
