### ISSUE TITLE
Icon not displayed when using a Pipe

### ISSUE THREAD

**Issue by rerezz** [NativeScript/nativescript-angular#227]
Instead of displaying the icon the hex string is displayed when I use a Pipe.

This is working, the icon shows properly:
`[text]="item.isFavourite ? '&#xf006;' : '&#xf005;'" class="font-awesome"`

When I use a Pipe instead, the hex value is displayed:
`[text]="item.isFavourite | favouritesIcon" class="font-awesome"`

My Pipe:

```
@Pipe({
    name: 'favouritesIcon'
})
export class FavouritesIconPipe implements PipeTransform {
    transform(value: any, args: any[]): any {
        return value ? "&#xf006;" : "&#xf005;";
    }
}
```

**Comment by matt4446** [comment]
@rerezz 
my code for ionic icons returns them like: ["\uf127"](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/controls/icons/ion-icon.ts#L77)

Try: 
"\uf006"
"\uf005"
etc

**Comment by rerezz** [comment]
Thanks! You're absolutely right! That's the hint: "&#xf005; For xml"
It's working now.
