### ISSUE TITLE
ScrollView problem

### ISSUE THREAD

**Issue by wuilmerj24** [NativeScript/nativescript-angular#2285]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.8.0
 - Cross-platform modules:6.5.20
 - Android Runtime:6.5.3
 - iOS Runtime:6.5.3
 - Plugin(s):
 - NativeScript-Angular:8.21.0
 - Angular:8.21.0
 
**Describe the bug**
I have a ScrollView inside a GridLayout and inside a pager (nativescript-pager) and 2 RadlistView, but the first ScrollView doesn't work on ios, on android it works fine.

When I swipe up it gives me a message in the terminal
![WhatsApp Image 2020-10-23 at 8 40 39 AM](https://user-images.githubusercontent.com/7539995/97006034-3ef60200-150d-11eb-9d03-8743eb2f90d3.jpeg)

**Comment by iamabs2001** [comment]
can you share your code ?

**Comment by wuilmerj24** [comment]
@iamabs2001 solved thansk.
