### ISSUE TITLE
ActionBarComponent is not exported from @nativescript/angular/nativescript.module

### ISSUE THREAD

**Issue by xuhcc** [NativeScript/nativescript-angular#2287]
**Environment**
 - CLI: 7.0.11
 - Cross-platform modules: 7.0.13
 - Android Runtime: 7.0.0
 - NativeScript-Angular: 10.1.7
 - Angular: 10.1.6, 10.2.1
 
**Describe the bug**

When I'm running `tns debug android --no-hmr` I get this error:

```
ERROR in Symbol ActionBarComponent declared in ./node_modules/@nativescript/angular/directives/action-bar.d.ts is not exported from @nativescript/angular/nativescript.module
```

**Additional context**

I'm trying to upgrade code-sharing project from NS 6 and Angular 8

**Comment by lviss** [comment]
I get the same error when building for iOS, also upgrading to NS 7 and Angular 10

**Comment by lviss** [comment]
I solved this by changing the import in app.module.tns.ts from:

`import { NativeScriptModule } from 'nativescript-angular/nativescript.module';`

to

`import { NativeScriptModule } from "@nativescript/angular";`

**Comment by xuhcc** [comment]
Thanks @lviss !
