### ISSUE TITLE
Implement ngStyle directive

### ISSUE THREAD

**Issue by rerezz** [NativeScript/nativescript-angular#229]
Is the implementation of the ngStyle (ViewUtil.setStyleProperty) directive already planned?

My use case:
I get a color property with my data items from the backend. I need to display the color as a state indicator. ngStyle would be great to achieve this.

**Comment by hdeshev** [comment]
Thanks for bringing that up! I guess we forgot to add an issue for it.

Adding it to the NS 2.1 milestone (due the end of June)
