### ISSUE TITLE
Detect module for code sharing (ng) not working properly

### ISSUE THREAD

**Issue by Arystosedes** [NativeScript/nativescript-angular#2291]
**Environment**
NS: 7.0.7
Angular CLI: 10.2.0
Angular: 10.2.2
 
**Describe the bug**
Somethimes detecting which module/component (.ts or .tns.ts) should be used not working properly. My component have a property 'isAvailable' only in component.ts file (and not for component.tns.ts).  Html file for web is using that property, and for mobile is not. If I run mobile app I can see errors like:

```
ERROR in src/app/words/words.component.html:2:11 - error TS2339: Property 'isAvailable' does not exist on type 'WordsComponent'.

2   *ngIf="!isAvailable"
            ~~~~~~~~~~~~~~~~~~~~
  src/app/words/words.component.tns.ts:21:16
    21   templateUrl: './words.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component WordsComponent.
```

But this is wrong template/ts! This is only for web.

I found that I can declare which module should be used for web/mobile in tsconfig files (https://docs.nativescript.org/angular/code-sharing/intro#lazy-loaded-modules) but with the same results..

What can be wrong? I use @src aliases when import files

I can fix it (for now) If I add 'tns' extensions to templateUrl in tns.ts but it shouldn't work like that, correct?

```
@Component({
  selector: 'app-words',
  templateUrl: './words.component.tns.html',
  styleUrls: ['./words.component.tns.scss'],
})
```

**Comment by jessorlisa** [comment]
I am having the same issue, I reported this some weeks ago: https://github.com/NativeScript/nativescript-angular/issues/2271

**Comment by Arystosedes** [comment]
Duplacated bug, so I'm closing it.
