### ISSUE TITLE
[HELP NEEDED] Configuring Webpack to use environment.prod with --env.production 

### ISSUE THREAD

**Issue by mahmoudajawad** [NativeScript/nativescript-angular#2299]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.11
 - Cross-platform modules: 7.0.13
 - Android Runtime: 7.0.0
 - iOS Runtime: 7.0.4
 - Plugin(s): N/A
 - NativeScript-Angular: 10.1.0
 - Angular: 10.1.0
 
**Describe the bug**
This is half bug, half not-implemented feature, where running `ns run PLATFORM --env.production` doesn't affect which `environment` files is being used. Since, I'm quite ignorant on `Webpack`, I tried the following which lead to some results, but not perfect:
1. Add the required snippet to enable production on `main.tns.ts`:
```typescript
import { enableProdMode } from '@angular/core';
import { environment } from '@src/environments/environment';

if (environment.production) {
	console.log('environment.production detected! calling enableProdMode()');
	enableProdMode();
}
```
2. Updated `tsconfig.tns.ts` to include `*.prod.ts`:
```json
{
	...
	"compilerOptions": {
		...
		"paths": {
			"@src/*": [
				"src/*.tns.ts",
				"src/*.ts",
				"src/*.prod.ts"
			]
		}
	}
}
```
3. Update `webpack.config.js` to replace `environment` file if `env.production` is truth:
```typescript
// Line 124:
	if (!production) {
		// for development purposes only
		// for example, include mock json folder
		// copyTargets.push({ from: 'tools/mockdata', to: 'assets/mockdata' });

		if (hmr) {
			ngCompilerTransformers.push(nsSupportHmrNg);
		}
	}
	// Insert following snippet:
	else {
		fileReplacements['@src/environments/environment'] = '@src/environments/environment.prod';
		console.log('added environment replacement!');
	}
```

The results of the previous is `Webpack` getting the file to be correctly replaced, but when `main.tns.ts` tries to load it, it fails with:
```
ERROR in ./environments/environment.prod.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: /path/to/project/src/environments/environment.prod.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

I believe something is needed either in one of the `tsconfig` files, or an additional modification in `webpack.config.js` to get this resolved and getting `ns run PLATFORM --env.production` to load `environment.prod`. I'll try further, but I'm sure someone with good `Webpack` knowledge could get this way faster than I could.

**To Reproduce**
N/A

**Expected behavior**
Being able to run, or build Angular-powered apps with production mode.

**Sample project**
N/A

**Additional context**
N/A

**Comment by Stanteq** [comment]
Open `webpack.config.js`, search for something like this and add new line: `env: JSON.stringify(env)`

```
    plugins: [
      // Define useful constants like TNS_WEBPACK
      new webpack.DefinePlugin({
        'global.TNS_WEBPACK': 'true',
        'global.isAndroid': platform === 'android',
        'global.isIOS': platform === 'ios',
        env: JSON.stringify(env),       // <----- this line
        process: 'global.process'
      }),
```

Create folder `environments` (like angular style, in the `src` directory) with 3 files: `environment.dev.ts`,  `environment.prod.ts`,  and `environment.ts`.

In `environment.ts`:

```
import { environment as devEnvironment } from "./environment.dev";
import { environment as prodEnvironment } from "./environment.prod";

declare const env: any;

export const environment: typeof prodEnvironment = (() => {
    if (env?.production) {
        return prodEnvironment;
    }

    return <typeof prodEnvironment>devEnvironment;
})();
``` 

In other 2 files put your stuff depending of your environment

**Comment by mahmoudajawad** [comment]
@Stanteq, I'm very sorry for this really late reply.
Thanks a ton, somehow I missed it. I'll give your work a shot and see how it works for me. Thanks again.

**Comment by marbletravis** [comment]
I have the same issue, but am using NS 8, with a newer version of webpack, my config looks like this 

```
const webpack = require("@nativescript/webpack");

module.exports = (env) => {
	webpack.init(env);

	return webpack.resolveConfig();
};
```

Any suggestions on how to get it to use environment.prod.ts when doing a release build?

**Comment by Marcelrama** [comment]
> I have the same issue, but am using NS 8, with a newer version of webpack, my config looks like this
> 
> ```
> const webpack = require("@nativescript/webpack");
> 
> module.exports = (env) => {
> 	webpack.init(env);
> 
> 	return webpack.resolveConfig();
> };
> ```
> 
> Any suggestions on how to get it to use environment.prod.ts when doing a release build?

`module.exports = (env) => {

	webpack.init(env);

	// Learn how to customize:
	// https://docs.nativescript.org/webpack

  webpack.chainWebpack(config => {
    config.plugin('DefinePlugin').tap(args => {
      Object.assign(args[0], {
        "global.TNS_WEBPACK": "true",
        'global.isProduction': !!env.production,
        "process.env": {
            environment: (env && Object.prototype.hasOwnProperty.call(env, 'environment')) ? JSON.stringify(env.environment) : undefined
        }
      })

      return args
    })
  })

	return webpack.resolveConfig();
};`

**Comment by mahmoudajawad** [comment]
As @Marcelrama's answer solves the issue. I'm closing this issue. 

P.s.: If you are on NativeScript 8.1 with Nx workspace, you'll get this out of the box.
