### ISSUE TITLE
Not able to see image in ios

### ISSUE THREAD

**Issue by dasarijit88** [NativeScript/nativescript-angular#2307]
I am trying to display an image  but nothing happens. This is only an issue in ios , in android it runs fine. I am referring to the correct location which contains the image file.  

```
<StackLayout>
        <Image src="~/app/image/add.png" class="add" ></Image>
</StackLayout>
```

My tsconfig.json have the below configuration

```
   "paths": {
          "~/*": [
              "src/*"
          ],
```

**Comment by jamescodesthings** [comment]
What's your webpack config look like?

I have:
```
const copyTargets = [
  { from: 'assets/**', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } },
];
// ...
// Copy assets
new CopyWebpackPlugin({
  patterns: copyTargets,
}),
```

With a directory structure like:
```
[project-root]/
  src/
    app/
      -NG Code
    assets/
      images/
        - pngs
```

Which allows me to use urls like:
```
<Image
  stretch="aspectFit"
  src="~/assets/images/image-name.png"
></Image>
```

**Comment by dasarijit88** [comment]
Hi James,

I also have the same structure and similar web pack config

const copyTargets = [
{ from: 'assets/**', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } },
{ from: 'fonts/**', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } },
...copyReplacements
];

I am having the images folder inside  app folder

<Image src="~/app/images/profile.png"></Image>

In tsconfig.json I have

"paths": {
"~/*": [
"src/*"
],

Regards,
Arijit Das

On 10 Dec 2020, at 16:12, James Macmillan <notifications@github.com<mailto:notifications@github.com>> wrote:



What's your webpack config look like?

I have:

const copyTargets = [
  { from: 'assets/**', noErrorOnMissing: true, globOptions: { dot: false, ...copyIgnore } },
];
// ...
// Copy assets
new CopyWebpackPlugin({
  patterns: copyTargets,
}),


With a directory structure like:

[project-root]/
  src/
    app/
      -NG Code
    assets/
      images/
        - pngs


Which allows me to use urls like:

<Image
  stretch="aspectFit"
  src="~/assets/images/image-name.png"

**Comment by jamescodesthings** [comment]
Hey, move your images folder to `src/assets`. 

The `src/app` folder isn't copied by that webpack config. But `src/assets` and `src/fonts` are.

**Comment by dasarijit88** [comment]
@jamescodesthings - Thanks alot James. Now it works perfectly fine. I have moved the images folder under **src/asset**
