### ISSUE TITLE
Node is not defined when running jasmine tests with karma

### ISSUE THREAD

**Issue by elatus111** [NativeScript/nativescript-angular#2311]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.11
 - Cross-platform modules:
 - Android Runtime: 7.0.1
 - iOS Runtime: 7.0.0
 - Plugin(s):
 - NativeScript-Angular: 10.1.0
 - Angular: 10.1.7
 
**Describe the bug**
When running karma tests I get the error "Node is not defined". This is happening in a sandbox project and an existing project that is being upgraded from Angular/Nativescript-angular 8 to 10. I updated the imports in my test-main.ts to what it seems they should be on however the documentation has not been updated so I am not sure if they are correct. My test-main.ts is below. I was unable to only import '@nativescript/zone-js/testing.jasmine' as my tests would fail with the error that "Zone is not defined". I am able to get the error to go away by importing '@nativescript/zone-js/zone-nativescript' as well, but then I get the error that I described above. This is with node version 10.16.0.

`import '@nativescript/zone-js/zone-nativescript';`
`import '@nativescript/zone-js/testing.jasmine';`  
`import {nsTestBedInit} from '@nativescript/angular/testing';`
`nsTestBedInit();`

![error](https://user-images.githubusercontent.com/76446917/103692134-f6bb7d00-4f5c-11eb-999b-6025dfb8aea7.jpg)

**To Reproduce**
I created a fresh project using Angular 10 and added nativescript and i get the same issue. 
**Expected behavior**
Tests would run correctly

**Sample project**

This is my sandbox project where I am getting the same error.

https://github.com/elatus111/nativescript-angular-sandbox

**Additional context**
Package.json below 
 
{
  "name": "angular10project",
  "version": "0.0.0",
  "scripts": {
    "android": "ns run android --no-hmr",
    "ios": "ns run ios --no-hmr",
    "mobile": "ns run",
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.2.3",
    "@angular/common": "~10.2.3",
    "@angular/compiler": "~10.2.3",
    "@angular/core": "~10.2.3",
    "@angular/forms": "~10.2.3",
    "@angular/platform-browser": "~10.2.3",
    "@angular/platform-browser-dynamic": "~10.2.3",
    "@angular/router": "~10.0.14",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.0.13",
    "@nativescript/theme": "~2.3.0",
    "@nativescript/unit-test-runner": "^1.0.2",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.7",
    "@angular/cli": "~10.1.7",
    "@angular/compiler-cli": "~10.1.6",
    "@nativescript/android": "7.0.1",
    "@nativescript/ios": "~7.0.0",
    "@nativescript/schematics": "^10.1.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/types": "~7.0.0",
    "@nativescript/webpack": "~3.0.0",
    "@ngtools/webpack": "~10.0.0",
    "@types/jasmine": "3.5.14",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^13.1.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "^1.5.0",
    "karma-nativescript-launcher": "0.4.0",
    "karma-webpack": "3.0.5",
    "protractor": "~7.0.0",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.0",
    "typescript": "3.9.7"
  },
  "main": "main.tns.js"
}

**Comment by linuxsimba** [comment]
@elatus111 , i got beyond the node is not defined by fixing the webpack dependencies. discovered the webpack dependencies issues when i upgraded to node v15, it told me there was a problem :) here is my package.json dependencies  . still unable to unit test components, but everything services, interceptors, ngrx can all be unit tested. 
```
  "dependencies": {
    "@angular/animations": "~10.2.0",
    "@angular/common": "~10.2.0",
    "@angular/compiler": "~10.2.0",
    "@angular/core": "~10.2.0",
    "@angular/forms": "~10.2.0",
    "@angular/platform-browser": "~10.2.0",
    "@angular/platform-browser-dynamic": "~10.2.0",
    "@angular/router": "~10.2.0",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/core": "~7.1.0",
    "@nativescript/geolocation": "^7.0.0",
    "@nativescript/theme": "~2.3.0",
    "@ngrx/effects": "^10.1.2",
    "@ngrx/store": "^10.1.2",
    "@proplugins/nativescript-masked-text-field": "^6.0.0",
    "nativescript-ui-sidedrawer": "~9.0.0",
    "ngx-mask": "^11.1.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.6.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/core": "~10.2.0",
    "@angular-devkit/schematics": "~10.2.0",
    "@angular/cli": "~10.2.0",
    "@angular/compiler-cli": "~10.2.0",
    "@nativescript/unit-test-runner": "1.0.2",
    "@nativescript/webpack": "^4.0.0",
    "@ngtools/webpack": "~10.2.0",
    "@types/jasmine": "3.6.2",
    "@typescript-eslint/eslint-plugin": "^4.14.2",
    "@typescript-eslint/parser": "^4.14.2",
    "codelyzer": "~6.0.0",
    "eslint": "^7.19.0",
    "eslint-import-resolver-typescript": "^2.3.0",
    "eslint-plugin-angular": "^4.0.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-ngrx": "^1.13.2",
    "htmlhint": "^0.14.2",
    "karma": "5.2.3",
    "karma-jasmine": "4.0.1",
    "karma-nativescript-launcher": "0.4.0",
    "karma-webpack": "~4.0.0",
    "node-sass": "^5.0.0",
    "sass-loader": "^10.1.1",
    "stylelint": "^13.9.0",
    "stylelint-config-standard": "^20.0.0",
    "tslint": "~6.1.3",
    "typescript": "~4.0.0"
  },
 
```

**Comment by linuxsimba** [comment]
figured how to write unit (component, service, interceptor)  tests using NG10 and NS7. read my blog about my adventures figuring it out.  https://linuxsimba.github.io/nativescript-unit-tests.  i hope in future NS releases unit test becomes easier and works out of the box.

**Comment by elatus111** [comment]
@linuxsimba Thanks for diving into this! I've been looking into your fixes and had a few questions. I see that you created your own custom nsTestBedInit which uses the BrowserTestingModule instead of the NativeScriptTestingModule. Was this your fix for the 'Node is not defined' issue? 

I saw in your blog that you mentioned you were not testing UI. Ideally I would keep using this module as my tests are using nsTestBedRender.

**Comment by edusperoni** [comment]
We have nailed it down to a regression in Angular which now checks for Node (which is not polyfilled). The next version of the angular integration won't use a custom zone implementation, which will improve things going forward.

To fix the Node error you can do:
class Dummy {}
global.Node = Dummy;

We already have it working and in a simpler way, so stay tuned

**Comment by dmrickey** [comment]
@edusperoni Is there preview release or something that fixes this problem now instead of whenever it's going to be released? What was the last version that didn't have this bug?

**Comment by edusperoni** [comment]
@dmrickey you can just put this code somewhere (preferably where you init your tests):

```
if (typeof Node === 'undefined' && !global.Node) {
	class DummyNode {}
	global.Node = DummyNode as any;
}
```
