### ISSUE TITLE
nsRouterLinkActive not working when nsRouterLink is on same element

### ISSUE THREAD

**Issue by yvdv-one** [NativeScript/nativescript-angular#2321]
Version:     "@nativescript/angular": "~10.1.7",

When I put the nsRouterLink on the same element as the nsRouterLinkActive, the style class is not added.
When I put it on an element within, it works as expected.

`    <GridLayout [nsRouterLink]="/user/bob" nsRouterLinkActive="highlight" [nsRouterLinkActiveOptions]="{exact: true}">
      <Label [text]="name" class="menu-text"></Label>
    </GridLayout>
`
does not work!

`    <GridLayout nsRouterLinkActive="highlight" [nsRouterLinkActiveOptions]="{exact: true}">
      <Label [nsRouterLink]="/user/bob" [text]="name" class="menu-text"></Label>
    </GridLayout>`
works! (and can be used as a workaround for now)

Maybe this has to do with change in angular?: https://github.com/angular/angular/issues/10098

Best regards,
Yves.

**Comment by yvdv-one** [comment]
Thank you for fixing this issue. 
I can confirm the style class is now added when nsRouterLink is on the same element as nsRouterLinkActive.

Yves,

**Comment by alexonozor** [comment]
I still experience this bug "@nativescript/angular": "^14.0.0",

**Comment by invergent** [comment]
I am experiencing this bug too. I am also using "@nativescript/angular": "^14.0.0",
