### ISSUE TITLE
drag and drop not working between layouts.

### ISSUE THREAD

**Issue by lonemanotzi** [NativeScript/nativescript-angular#2324]
Environment
Latest and 6.x versions

Describe the bug
Element's visibility is gone when dropping to another gridlayout. Same issue is observed in flexboxlayout. Stack layout works fine.

To Reproduce
See this playground https://play.nativescript.org/?template=play-ng&id=joJ1JA&v=2

Here is the markup

<GridLayout rows="*,*" columns="*,*" row="1" col="0" backgroundColor="red">
    
    <GridLayout row="0" col="0" columns="*,*" rows="*,*">
        <Label text="Drag Text" #dragImage class="drp" row="0" col="0"
            style="z-index:10000" (pan)="onPan($event)"></Label>
        <GridLayout height="200" backgroundColor="pink" row="2" col="0"
            style="z-index:-1">
            
        </GridLayout>
    </GridLayout>
    <GridLayout height="200" backgroundColor="black" #box1 row="0" col="1"
        style="z-index:-1" class="r-pane">
        
    </GridLayout>
    <GridLayout height="200" backgroundColor="purple" #box2 row="1" col="0"
        colspan="2" style="z-index:-1">
        
    </GridLayout>
</GridLayout>

    onPan(args: PanGestureEventData) {
        if (args.state === 1) // down
        {
            this.prevDeltaX = 0;
            this.prevDeltaY = 0;
        }
        else if (args.state === 2) // panning
        {
           this.dragImageItem.translateX += args.deltaX - this.prevDeltaX;
            this.dragImageItem.translateY += args.deltaY - this.prevDeltaY;

            this.prevDeltaX = args.deltaX;
            this.prevDeltaY = args.deltaY;
        }
        else if (args.state === 3) // up
        {
        }
    }

**Comment by edusperoni** [comment]
This isn't an issue with `nativescript-angular` but with nativescript itself. Views are usually clipped to their parents on android, so you have to disable clipping and change the order of elements to allow overflow (this is an issue with RN as well https://medium.com/entria/solving-view-overflow-in-android-reactnative-f961752a75cd )

Here's your example in a working state (notice the loaded call to the dontClip function) https://play.nativescript.org/?template=play-ng&id=joJ1JA&v=3
