### ISSUE TITLE
HttpClient blocks UI

### ISSUE THREAD

**Issue by csimpi** [NativeScript/nativescript-angular#2330]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7
 - Cross-platform modules: -
 - Android Runtime: 7.0.0
 - iOS Runtime: -
 - Plugin(s): -
 - NativeScript-Angular: 10.0.0.0
 - Angular: 10
 
**Describe the bug**

When I make a HTTP request with Angular's HttpClient the UI is blocking/hanging until the response arrives. Even the console is frozen until the request arrives. 

When I change to nativescript core's Http this doesn't happen. Since I use a shared web+Android hybrid solution I can't use Http exclusively, I'd need to use the Angular module instead. I have an api.service which is common for web and Android and the whole app built on this.

**To Reproduce**

In the `app.module.tns.ts` file:
`import { NativeScriptHttpClientModule } from '@nativescript/angular';`

in the `component`:
`import {HttpHeaders, HttpClient, HttpParams, HttpErrorResponse} from '@angular/common/http';`

```
this.http.get(`${this.baseUrl}${path}`, { params:parameters }).subscribe(r=>{})
```

Make a slow request and try to for example scroll or navigate in the app. It'll be blocked.

**Another approach**

In the `component`:
`import { getJSON} from "@nativescript/core/http";`

```
 getJSON('https://mtp.travel/api/v2/mapbox/tilesets/cveley.main-map/pip?lng='+lng+'&lat='+lat).then((response:{data:FeatureCollection}) => {})
```

No UI blocking, no hanging, no freezing it just works. But it obviously doesn't work with the web at all.

**Expected behavior**

No UI blocking with Angular's HttpClient

**Sample project**

I tried to create a sample project, but I'm getting memory allocation errors immediately when I try to pull a big JSON (slow request) with Playground. 

https://play.nativescript.org/?template=play-ng&id=bqQIRx

**Additional context**

Tried `@klippa/nativescript-http` too, but didn't work to me. Got a missing `Chache` function error with the webpack plugin.

**Comment by csimpi** [comment]
UPDATE:
I couldn't reproduce with a fresh NS project, after further investigating the issue it came up, a `match()` in the interceptor slowed down the request. It doesn't happen on web.

 Is that normal, this expression that slow it takes 10 seconds to get the result (Note 8)?
`request.url.match(/^(.*?){0,6}(:\/\/)/i)`

if so, I'll just simplify it, my case is closed :)

**Comment by edusperoni** [comment]
@csimpi that regex sure is suboptimal, but it shouldn't take more than 1ms to process, I'll have to try it out later to check what's holding it up

**Comment by csimpi** [comment]
@edusperoni Thx, I'm curious about the result, LMK. Now that I changed it less flexible `/https:\/\//` there's no hanging or slowness anymore. Very mysterious :)

**Comment by edusperoni** [comment]
@csimpi I just tested here and that regex resulted in no slowness on my end.

If you're just trying to validate for `https://`, a simple regex is `^https?:\/\/`, actually, just changing yours around to `^(.{0,6}?):\/\//i` maintains the same functionality while requiring much fewer steps. If you want to validate an URI, though, you're looking for this monster:
```
/^([a-z][a-z0-9+.-]*):(?:\/\/((?:(?=((?:[a-z0-9-._~!$&'()*+,;=:]|%[0-9A-F]{2})*))(\3)@)?(?=(\[[0-9A-F:.]{2,}\]|(?:[a-z0-9-._~!$&'()*+,;=]|%[0-9A-F]{2})*))\5(?::(?=(\d*))\6)?)(\/(?=((?:[a-z0-9-._~!$&'()*+,;=:@\/]|%[0-9A-F]{2})*))\8)?|(\/?(?!\/)(?=((?:[a-z0-9-._~!$&'()*+,;=:@\/]|%[0-9A-F]{2})*))\10)?)(?:\?(?=((?:[a-z0-9-._~!$&'()*+,;=:@\/?]|%[0-9A-F]{2})*))\11)?(?:#(?=((?:[a-z0-9-._~!$&'()*+,;=:@\/?]|%[0-9A-F]{2})*))\12)?$/i
```

And even this did not hang my application.

I'll take a guess here. Maybe you're doing something with these matches (or request.url is null), and what you're seeing hang is actually {N} in debug mode printing/building the stack trace with debug information (which is known to lock the UI), and not the match itself that's hanging it.

If you're just using a regex just for validation, `regex.test` is faster than `string.match` (https://www.measurethat.net/Benchmarks/Show/11043/0/stringmatch-vs-regextest)
