### ISSUE TITLE
How to get coordinates of starting point for pan gesture

### ISSUE THREAD

**Issue by jsparks19** [NativeScript/nativescript-angular#234]
Pan gesture exposes the delta X and delta Y, but I need to know the actual coordinates where the user started the pan. How do I do this? Do I need to use a combination of touch gesture and pan? Thanks

**Comment by vakrilov** [comment]
Yes - you can use the touch gesture.
One other option is to use the native APIs to get the coordinates:
 * In IOS - you can get the [UIGestureRecognizer](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIGestureRecognizer_Class/) from `eventArgs.ios` 
 * In Android - you can get the initial [MotionEvent](http://developer.android.com/reference/android/view/MotionEvent.html) trough `eventArgs.android.initial`

**Comment by jsparks19** [comment]
The touch gesture is working for me. Thanks
