### ISSUE TITLE
Error in Groceries Guide

### ISSUE THREAD

**Issue by abarranco** [NativeScript/nativescript-angular#235]
Hello i am following this guide: http://docs.nativescript.org/angular/tutorial/ng-chapter-0

At this point: http://docs.nativescript.org/angular/tutorial/ng-chapter-3

In the **Exercise: Create an account** the guide says we have to include in app/app.component.ts

import {HTTP_PROVIDERS} from "@angular/http";
providers: [UserService, HTTP_PROVIDERS],

I added that and i'm getting this error:

JS: Page loaded
JS: BOOTSTRAPPING...
JS: Setting DOM
JS: EXCEPTION: Error in :0:0
JS: ORIGINAL EXCEPTION: No provider for Http!
JS: ORIGINAL STACKTRACE:
JS: Error: DI Exception
JS:     at NoProviderError.BaseException [as constructor] (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/facade/exceptions.js:17:23)
JS:     at NoProviderError.AbstractProviderError [as constructor] (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:39:16)
JS:     at new NoProviderError (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/di/reflective_exceptions.js:75:16)
JS:     at ReflectiveInjector_._throwOrNull (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:776:19)
JS:     at ReflectiveInjector_._getByKeyDefault (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:804:25)
JS:     at ReflectiveInjector_._getByKey (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:767:25)
JS:     at ReflectiveInjector_.get (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/di/reflective_injector.js:576:21)
JS:     at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent_Host.template.js:19:68)
JS:     at DebugAppView.AppView.create (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:66:21)
JS:     at DebugAppView.create (/data/data/org.nativescript.groceries/files/app/tns_modules/@angular/core/src/linker/view.js:259:44)
JS: ERROR CONTEXT:
JS: [object Object]

It says something about a constructor and http provider so i made this changes in app/app.component.ts and it worked but i don't know if it's the best solution.

1. import {**Http**, HTTP_PROVIDERS} from "@angular/http";

Notice i added **Http**

2. export class AppComponent {
    user: User;
    isLoggingIn = true;

    constructor(private _userService: UserService, **private _http: Http**) {
        this.user = new User();
    }

- Notice i added  **private _http: Http** in the constructor.

This way i can create an account and i will follow the rest of the guide. If there is a better solution i would like to know it. Thank you.

**Comment by abarranco** [comment]
I didn't know if creating another issue was a good idea, so i will post here another error i found.

In this url: http://docs.nativescript.org/angular/tutorial/ng-chapter-3  at the step "Exercise: Use an Angular 2 service" 

register(user: User) {
    let headers = new Headers();
    headers.append("Content-Type", "application/json");

    return this._http.post(
      Config.apiUrl + "Users",
      JSON.stringify({
        Username: user.email,
        Email: user.email,
        Password: user.password
      }),
      { headers: headers }
    )
    .catch(**this.handleErrors**);
  }

  handleErrors(error: Response) {
    console.log(JSON.stringify(error.json()));
    return Observable.throw(error);
  } 

This function is called in GroceryListService 2 times and in UserService 2 times too. It's giving me a compilation error, and in every call i just make this change:

register(user: User) {
        let headers = new Headers();
        headers.append("Content-Type", "application/json");

        return this._http.post(
            Config.apiUrl + "Users",
            JSON.stringify({
                Username: user.email,
                Email: user.email,
                Password: user.password
            }),
            { headers: headers }
        )
            .catch(**(error: Response) => {this.handleErrors(error)}**);
    }

    handleErrors(error: Response) {
        console.log(JSON.stringify(error.json()));
        return Observable.throw(error);
    }

I think that's better/cleaner because i know the parameters type and order of the function without looking to the function.

**Comment by NickIliev** [comment]
Hello @abarranco 

Following the tutorial yours app.component.ts should have @Component which should be looking like this (before the change to the providers)
```
import {Component} from "@angular/core";
 .....

@Component({
  selector: "my-app",
  providers: [UserService],
  templateUrl: "pages/login/login.html",
  styleUrls: ["pages/login/login-common.css", "pages/login/login.css"],
})
```

and after your change it should look like this

```
import {Component} from "@angular/core";
import {HTTP_PROVIDERS} from "@angular/http";
 .....

@Component({
  selector: "my-app",
  providers: [UserService, HTTP_PROVIDERS],
  templateUrl: "pages/login/login.html",
  styleUrls: ["pages/login/login-common.css", "pages/login/login.css"],
})
```

As a tip you can change the working angular-start branch to angular-end branch to see how the final project looks like in its final stage. Hope that will help you out - let me know if you need further assitance!
