### ISSUE TITLE
Question - Showing an nativescript angular app in a angular website

### ISSUE THREAD

**Issue by kriefsacha** [NativeScript/nativescript-angular#2366]
Hi,

First of all i would like to thank you for all your work that help us very much.

I wanted to know if something that we want to do is possible or if you heard about something.

We have a nativescript angular android and ios app, and we would like to do the same in web.

Instead of doing everything from scratch, we wanted to know if thats possible to show the app in a angular website ( with an emulator maybe or something else ).

I would like to know what you think, if i'm not clear enough please tell me.

Have a nice day !

**Comment by lostation** [comment]
You meant running compiled .apk .ipa  mobile app version inside a kind of web wrapper ? … I don’t think it’s really possible...

Electron <https://www.electronjs.org/> is a kind of web wrapper for cross platforms…but not currently to host a builded Nativescript app… maybe one day.

—> So you need what so called a ‘shared’ angular project…welcome in the game ;-)

It means to create all the web side of your project…meaning:

- Create all the web files template + dedicated logic and web imports…
- Create helpers file to refactor and use same function call but distinguishing web and mobile implementations.

Then you will be able to build web files and show your app inside a web browser.

https://docs.nativescript.org/code-sharing/index.html <https://docs.nativescript.org/code-sharing/index.html>

Best regards.

**Comment by kriefsacha** [comment]
@lostation first of all thank you very much for you fast answer !

Yeah i meant or that or be able to run the same code but in the web.

About the 'shared' project, can i turn my current project (which is an android/ios nativescript angular project) into a shared project ?

For that i will need to change the current code (ts, html ..) of my project into web stuff ?

Thank you !

**Comment by lostation** [comment]
Yes... check the link I've provided above.
You should find all the answers you're looking for.

In fact...NS6 was using a .tns.ts suffix extension to differentiate NS files from WEB files...and that was great.

But now from NS7 it's over -> a new way of doing a shared project has come. 
(Currently I'm still using NS6 way... but I will probably be forced soon to do the same)

So Check [Nrwl with Nativescript/nx](https://github.com/NativeScript/nx) 
Some dedicated folders architecture to contain the web side of your app, another folder containing only the mobile and a shared folder to...share between sub projects. The goal is to share and re-use as much as you can to avoid rewrite too much stuff.

**Comment by edusperoni** [comment]
Code sharing should be done with nx. I've written more in-depth here: https://github.com/NativeScript/nativescript-angular/issues/2290#issuecomment-854226427. You can also find more information further down the thread.

You might believe that you just need a different html file for your components, but the reality of it is that if you just need a different html file your app performance is probably suffering and you'll need different ts files that change 1 or 2 lines, so it's easier to write base classes and extend them in an nx workspace instead.

The idea is:

1. Create an nx workspace
2. Create/move your nativescript application `apps/ns-app`
3. Create/move your web angular application `apps/web-app`
4. `npx nx g @nrwl/angular:lib shared` (this will create `@yourworkspace/shared`)
5. write things that are shared in your shared lib, things that are not shared in `apps/ns-app` or `apps/web-app`. Import shared stuff in the apps using `import { SharedThings } from '@yourworkspace/shared';`.

You can even mix stuff up. Let's say you're using sqlite for your application and IndexDB for your frontend.

```ts
@Injectable({providedIn: 'root'})
export class ItemService {
  constructor(private backend: StorageBackend) {}
  getItems() {
    return this.backend.getItems(); // do other stuff with the storage backend
  }
}
```


```ts
@Injectable()
export abstract class StorageBackend {
  abstract insert(item: Item): Promise<void>;
  abstract getItems(): Promise<Items[]>;
  abstract remove(item: Item): Promise<void>;
}
```

```ts
// web-app
@Injectable()
export class IndexDBBackend extends StorageBackend {
 // implement the abstract methods here
}
```

```ts
// ns-app
@Injectable()
export class SqliteBackend implements StorageBackend {
 // implement the abstract methods here
}
```


```ts
//web-app app.module.ts
@NgModule({
  ... // other module stuff
  providers: [provide: StorageBackend, useClass: IndexDBBackend]
})
```


```ts
//ns-app app.module.ts
@NgModule({
  ... // other module stuff
  providers: [provide: StorageBackend, useClass: SqliteBackend]
})
```

The possibilities are endless.
