### ISSUE TITLE
Forms Crash Occasionally In Angular 2 Apps

### ISSUE THREAD

**Issue by nraboy** [NativeScript/nativescript-angular#244]
I've been getting this error maybe 1 in 20 runs:

![angular-couchbase](https://cloud.githubusercontent.com/assets/983958/15398541/dc0dcfda-1d98-11e6-8ec6-89bbdbf1ebe6.gif)

Basically when I start my Angular 2 application and try to type something in a form, it crashes.  The error received is as follows:

```
JS: Page loaded
JS: BOOTSTRAPPING...
JS: Setting DOM
JS: Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ANGULAR BOOTSTRAP DONE.
I/DEBUG   (  146):     #02  pc 0024a377  /data/app-lib/org.nativescript.CouchbaseAngular-1/libNativeScript.so (Java_com_tns_Runtime_callJSMethodNative+231)
I/DEBUG   (  146):          bfc23dc4  947d9f31  /data/app-lib/org.nativescript.CouchbaseAngular-1/libNativeScript.so (tns::Runtime::CallJSMethodNative(_JNIEnv*, _jobject*, int, _jstring*, int, unsigned char, _jobjectArray*)+17)
I/DEBUG   (  146):          bfc23dd8  947d5378  /data/app-lib/org.nativescript.CouchbaseAngular-1/libNativeScript.so (Java_com_tns_Runtime_callJSMethodNative+232)
```

It is not particularly descriptive.

Any ideas?

**Comment by slavchev** [comment]
It seems like a bug in the {N} runtime. Is it possible to send a repro project or steps to reproduce? If not possible, can you put `__enableVerboseLogging()` somewhere in your app (for example in the first line in `app.js`) and send us the full log when the app crashes?

**Comment by nraboy** [comment]
Hey @slavchev,

See the attached project that I was using:

[CouchbaseAngular.zip](https://github.com/NativeScript/nativescript-angular/files/282268/CouchbaseAngular.zip)

See if anything seems out of the ordinary to you.

Best,

**Comment by slavchev** [comment]
Hi @nraboy 

I investigated the issue further and can confirm it's the same as https://github.com/NativeScript/android-runtime/issues/385. So far we identified the problem in `ashmem` but don't have a solution. We experienced (quite severely, especially on Genymotion) the same problem in our test environment and only on `x86` emulators. As a workaround we switched to `arm` emulators.

Currently our team doesn't have enough resources and the mentioned workaround works fine for us. If you frequently experience the problem I would suggest to try another `x86` emulator or switch to `arm`. Hopefully, in near future we will have more resources and solve the problem.

I am closing this issue. You can keep the track at https://github.com/NativeScript/android-runtime/issues/385.
