### ISSUE TITLE
Creating custom widget

### ISSUE THREAD

**Issue by denkomanceski** [NativeScript/nativescript-angular#248]
Hi,

I tried searching for documentation on how to create custom widget and use it in nativescript app but i could not find any useful documentation. I need to create chat bubbles which look different on iOS and differently on Android?

Could someone tell me what is the best approach to create custom UI components?

Thanks

**Comment by hdeshev** [comment]
There are several NativeScript extensibility approaches:

1. Use a NativeScript plugin, and integrate it in an Angular app: http://docs.nativescript.org/angular/plugins/angular-third-party.html
2. Build a vanilla NativeScript component, and integrate it in your Angular app (described in the link above).
3. Build an Angular component or directive that works with templates or uses content projection:
  - http://blog.thoughtram.io/angular/2015/04/09/developing-a-tabs-component-in-angular-2.html
  - http://juristr.com/blog/2016/01/ng2-multi-content-projection/
