### ISSUE TITLE
Image doesn't support redirects

### ISSUE THREAD

**Issue by jrz** [NativeScript/nativescript-angular#253]
If I set the source to http://graph.facebook.com/XXXXX/picture?type=large, no image shows up.

How should I support (max)redirects?

**Comment by hdeshev** [comment]
It looks like a bug in the Android HTTP client (works fine on iOS). I added a reproduction project here:

https://github.com/hdeshev/nativescript-image-redirect

**Comment by hdeshev** [comment]
This issue was moved to NativeScript/NativeScript#2176
