### ISSUE TITLE
Image src calls binding constantly

### ISSUE THREAD

**Issue by jrz** [NativeScript/nativescript-angular#254]
The following code floods my console (image does show properly):

```
get profilePictureUrl(): string {
console.log("called");
return 'http://some/valid/image.jpg';
}

<Image [src]="friend.profilePictureUrl"></Image>
```

**Comment by jrz** [comment]
The same happens with a ListView.

**Comment by hdeshev** [comment]
I believe this is how the Angular change detection algorithm works. You could fine tune it by changing the change detection strategy (e.g. OnPush):

http://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html
