### ISSUE TITLE
iOS navigation bug

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#257]
_From @denkomanceski on May 24, 2016 21:7_

There are two bugs involved here. 

The first one is when I start navigating back on iOS (slowly sliding left to right) the action bar is losing the styling (its going white with blue letters) and the components on the page are disappearing.

The second one which is worse is if you dont navigate back but stay on the page after you trigger the navigation transition (slide back to the same view instead of navigating back) the app crashes (before it crashes bug no.1 comes and the page is blank).

Here is a video: https://www.dropbox.com/s/tfz18kuhyottcuc/IMG_2936.MOV?dl=0
(First I show the first bug, than both together)

Is there any workaround that could help?

Edit: I tried with the ng-sample app (the NavigationTest, the one that is using page router and normal router) and the excatly same error happens. Here is the error also:

```
file:///app/tns_modules/rxjs/Subscriber.js:229:22: JS ERROR TypeError: undefined is not an object (evaluating 'state.isPageNavigation')
May 24 23:30:13 DenkoMBP com.apple.CoreSimulator.SimDevice.B0C93223-F914-47B3-97F0-E6B1D8739AE5.launchd_sim[11323] (UIKitApplication:org.nativescript.ngsample[0xfa7][11393]): Service exited due to signal: Segmentation fault: 11
```

Thanks

_Copied from original issue: NativeScript/NativeScript#2168_

**Comment by NickIliev** [comment]
Hello @denkomanceski

I can confirm that indeed in nativescript-angular project the navigation is throwing error when you initiate  swipe-back but still stay on the same page. 

I have moved your issue to the nativescript-angular repository to log this bug and i will create another issue for the first problem with the styling of transitioned action bar.

**Comment by denkomanceski** [comment]
@vakrilov does this also fixes the part "the action bar is losing the styling (its going white with blue letters) and the components on the page are disappearing." ? If it is how can we start using this version since the app is currently unusable?

Thanks

**Comment by vakrilov** [comment]
@denkomanceski Not sure about the styling. The components on the page that you are navigating back from should remain there until the navigation is completed. If you cancel it - they will be still alive.

**Comment by denkomanceski** [comment]
Okay great.. How do we start using this fix? Do we need to update nativescript library or ?
Thanks

**Comment by denkomanceski** [comment]
I tried it, it works and doesnt throw errors but the status bar color is still changing to default just to let you know

**Comment by vakrilov** [comment]
Thanks for the updates.
I'm not sure about if this is default IOS behavior. However, this particular behavior is not specific for the `angular-nativescript` so the [NativeScript repo](https://github.com/NativeScript/NativeScript) will be the right place to continue the discussion if needed.
