### ISSUE TITLE
Support handling `loaded` events in a consistent manner

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#259]
At the moment, if you don't use the router, it is impossible to attach to the loaded event in from html markup (we attach the event after adding the view to the visual tree, and the event never fires).

It looks pretty convenient to just add a `<TextField #searchBox (loaded)="myHandler(searchBox)">` binding and avoid dealing with `ViewChild` decorators and `ElementRef`'s.

Related #200, #250

**Comment by nsndeck** [comment]
Fixed with commit #260.
