### ISSUE TITLE
Critical - Memory and cpu usage.

### ISSUE THREAD

**Issue by jrz** [NativeScript/nativescript-angular#262]
According xcode, memory usage for a very simple app (Just a listview) is around 100MB, and cpu is 40% (1 thread is maxed out).

The weird thing is that cpu usage drops as soon as I scroll (and hold) the ListView

![image](https://cloud.githubusercontent.com/assets/149668/15605624/75a9f186-2407-11e6-8239-3df3bec4a6d6.png)

![image](https://cloud.githubusercontent.com/assets/149668/15605635/7f054b9a-2407-11e6-9461-f7473819eadc.png)

![image](https://cloud.githubusercontent.com/assets/149668/15605639/853a2c1a-2407-11e6-93a2-eaff6794106b.png)

If I open a second listview, cpu jumps from 40% to 60%. Press/hold still brings it back to 0
![image](https://cloud.githubusercontent.com/assets/149668/15605701/e6e53874-2407-11e6-8699-6a05529d8e34.png)

![image](https://cloud.githubusercontent.com/assets/149668/15605745/25127418-2408-11e6-8536-1a85a93a5f5f.png)

**Comment by vakrilov** [comment]
@jrz: Can you share the code of the project your using?
