### ISSUE TITLE
Angular Http.delete() operation does not work on Android 4.4.2 (api 19)

### ISSUE THREAD

**Issue by jandsu** [NativeScript/nativescript-angular#270]
Issue reproduced on https://github.com/NativeScript/sample-Groceries in branch **angular-end** (commit 3dca425fdde3fd5a725f23d28edd97999fbfc7cc)
1. Create an AVD with API 19 (see my exact config below if required):
2. Debug the Grocery application on that device and set a breakpoint in grocery-list-service.ts on the handleErrors() function:
3. Sign in to the application using the default provided login/password.
4. Try and delete an item.
5. Hit the breakpoint and check out the content of the 'error' parameter.

==> observe that it contains the following message: "java.net.ProtocolException: method does not support a request body: DELETE"

Stepping into the Http code in Angular2, I observed that the request body was set to null (not undefined)... presumably, this might be a reason why it fails.

I don't know (yet?) how to step into the NativeScript code and then in the Android SDK....
### Context Code

```
  delete(id: string) {
    var headers = new Headers();
    headers.append("Authorization", "Bearer " + Config.token);
    headers.append("Content-Type", "application/json");

    return this._http.delete(
      Config.apiUrl + "Groceries/" + id,
      { headers: headers }
    )
    .map(res => res.json())
    .catch(this.handleErrors);
  }

  handleErrors(error: Response) {
    console.log(JSON.stringify(error.json()));  // <==== SET BREAKPOINT HERE
    return Observable.throw(error);
  }
```
### Config

FWIW this was run on Ubuntu 16.04... here is the AVD config

```
avd.ini.encoding=UTF-8
abi.type=x86
disk.dataPartition.size=200M
hw.accelerometer=yes
hw.audioInput=yes
hw.battery=yes
hw.camera.back=none
hw.camera.front=none
hw.cpu.arch=x86
hw.dPad=no
hw.device.hash2=MD5:37a2ff6e511626ba3ceddec8264474be
hw.device.manufacturer=Google
hw.device.name=Nexus S
hw.gps=yes
hw.gpu.enabled=yes
hw.keyboard=yes
hw.lcd.density=240
hw.mainKeys=yes
hw.ramSize=1024
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-19/google_apis/x86/
skin.dynamic=yes
skin.name=480x800
skin.path=480x800
tag.display=Google APIs
tag.id=google_apis
vm.heapSize=32
```

**Comment by tsonevn** [comment]
This behavior seems to be fixed with latest `sample-Grocery` version in `angular-end` branch. 
You could clone again [sample-Groceries](https://github.com/NativeScript/sample-Groceries) app and to build again.
