### ISSUE TITLE
unit testing with angular/core/testing

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#272]
_From @circy on June 3, 2016 23:10_

Hi Guys.
Is it possible to unit tests with the test lib to make of angular?
Or this is only possible in the browser?

for example:

```Typescript
import {
  it,
  describe,
  expect
} from '@angular/core/testing';

describe('App', () => {

  it('the first', () => {
    expect(true).toEqual(true);
  });

});
```

I use Native Script Version: 2.0.1
And I use Jasmine.

Many thanks.

_Copied from original issue: NativeScript/NativeScript#2246_

**Comment by hdeshev** [comment]
`@angular/core/testing` isn't officially supported yet, but people have been able to get it running using the nativescript karma runner: #212

**Comment by souly1** [comment]
+1
