### ISSUE TITLE
Cookbook UI documentation + ng2

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#276]
A lot of the “cookbook” UI documentation on docs.nativescript.org is not applicable to building with ng2. For instance nearly all of the components include a `<Page>` XML element—e.g. http://docs.nativescript.org/angular/cookbook/ui/activity-indicator.

This problem recently came up on Twitter https://twitter.com/weezhen/status/739487960014290944.

I’m not exactly sure how we’d tackle this because the cookbook comes from the modules repo, but I thought I’d least report this so it’s documented.

**Comment by hdeshev** [comment]
This issue was moved to NativeScript/docs#390
