### ISSUE TITLE
Router does not work with push plugin (and Google Sign In SDK)

### ISSUE THREAD

**Issue by emelois** [NativeScript/nativescript-angular#285]
Hi, I think there is an issue with the page-router-outlet when used with the Telerik Push Notification Plugin.

When I tap the notification, the app is brought on the foreground, the navigate call is executed but the view is not updated (the current view is still displayed).

`
pushPlugin.onMessageReceived(function callback(message, data) {
            this.router.navigate(['MyRoute']);
            console.log("Navigate done");
        }.bind(this));
`

I've been looking in the detached-loader.ts file, everything seems fine except that the ngAfterViewInit method is never called after the router.navigate call.

I've tried to add a ApplicationRef.tick() to force the refresh, the view goes blank (at least something happens) and the app seems in an unstable state.

If I tap the notification (nothing happens), then tap a button in the current view (which only print a console message), it triggers the ngAfterViewInit and the view is displayed.

I have the exact same problem in the callback of the Google Sign In SDK which display a foreground activity during the login process. If the account has already been selected and the process is done without the foreground modal, it works perfectly.

Any idea on where I should be looking?

Thank you

**Comment by NathanWalker** [comment]
Hi @emelois try this:
If using TypeScript:
```
// at top of file
declare var zonedCallback: Function;

// then wherever this is:
pushPlugin.onMessageReceived(zonedCallback((message, data) => { 
  this.router.navigate(['/MyRoute']); 
  console.log("Navigate done"); 
}));
```
If using plain JS:
```
var callback = function(message, data) {
  this.router.navigate(['/MyRoute']);
  console.log("Navigate done"); 
};
pushPlugin.onMessageReceived(zonedCallback(callback.bind(this)));
```

**Comment by NathanWalker** [comment]
@emelois Please close this if the above worked for you ^

**Comment by emelois** [comment]
Wow it works!
Can you tell me what I got wrong?
Thanks a lot @NathanWalker.

**Comment by NathanWalker** [comment]
It's a very common thing that everyone runs into eventually. Anytime a third party plugin is being integrated with callbacks, it's usually the case that those callbacks will execute outside of a zone, therefore resulting in no change detection happening and thus your view not updating. Whenever you run into this case, just wrap your callback with zonedCallback (a global loaded by the NativeScript runtime), and it will ensure it executed in a zone to properly update your view.

**Comment by emelois** [comment]
Great, thank you. :+1:

**Comment by krisidmisso** [comment]
@NathanWalker 
Can somebody help me navigate after push notification is received??
I get "cannot read property 'navigate' of undefined"

This code is inside main.ts and there is no class or constructor to initialize variables:
`
import { RouterExtensions } from "nativescript-angular/router";

let router: RouterExtensions;
setTimeout(() => {

    let firebase = require("nativescript-plugin-firebase");  

    firebase.init({ 
        onPushTokenReceivedCallback: function(token) {             
            deviceToken = token;  
            console.log("Firebase push token: " + token);  
        },  
        onMessageReceivedCallback: (message) => {  
           // let router: RouterExtensions; //tried initializing it here but didnt work also
            dialogs.alert({  
                title: "Push message: " + (message.title !== undefined ? message.title : ""),  
                message: JSON.stringify(message.website),  
                okButtonText: "OK"  
            });

//even tried this.router.navigate.....

            router.navigate(["webViewPage"],{
           clearHistory:true,
           transition: {
            name: "slideTop",
            duration: 800,
            curve: "spring"
            },
            queryParams:{"url": "http://www.google.com"}, 
            animated: true
      
          });
            
        }
..........
`

**Comment by souly1** [comment]
@krisidmisso , got it to work eventually? what did you do?

**Comment by krisidmisso** [comment]
@souly1 i selected a different approach to the problem. I created another public function navigate(route:string) and put inside navigation route functions depending on the passed parameter "route".

```

let that = this; //INSERT THIS LINE BEFORE FIREBASE.INIT

firebase.init({ 
    onPushTokenReceivedCallback: function(token) {             
        deviceToken = token;  
        console.log("Firebase push token: " + token);  
    },  
    onMessageReceivedCallback: (message) => {  
       that.navigate("home"); // USE THAT TO REFERENCE NEW FUNCTION
        
    }
..........
```
