### ISSUE TITLE
Getting following error while implementing facebook login plugin

### ISSUE THREAD

**Issue by yogeshwar607** [NativeScript/nativescript-angular#290]
Trying to implement nativescript-facebook-login  (https://www.npmjs.com/package/nativescript-facebook-login) using angular2 and typescript. Its showing following error.
I have following code in file app.ios.ts

-----------==================---------------

var application = require("application");
 
class MyDelegate extends UIResponder implements UIApplicationDelegate {
  public static ObjCProtocols = [UIApplicationDelegate];
 
  applicationDidFinishLaunchingWithOptions(application: UIApplication, launchOptions: NSDictionary): boolean {
   return FBSDKApplicationDelegate.sharedInstance().applicationDidFinishLaunchingWithOptions(application, launchOptions);
  }
  
  applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation) {
    return FBSDKApplicationDelegate.sharedInstance().applicationOpenURLSourceApplicationAnnotation(application, url, sourceApplication, annotation);
  }
  
  applicationDidBecomeActive(application: UIApplication): void {
      FBSDKAppEvents.activateApp();
  }
 
  applicationWillTerminate(application: UIApplication): void {
    //Do something you want here
  }
 
  applicationDidEnterBackground(application: UIApplication): void {
    //Do something you want here
  }
}
 
application.ios.delegate = MyDelegate;
application.start();

-------------------------===============================-------------------------
<img width="1280" alt="screen shot 2016-06-14 at 3 19 33 am" src="https://cloud.githubusercontent.com/assets/10059011/16055017/321b9520-328d-11e6-84e3-3ec5f6d9b29d.png">

**Comment by getmetorajesh** [comment]
@yogeshwar607 try declaring them as a `any` type.
```
declare var UIResponder: any
declare var UIApplicationDelegate: any
declare var UIApplication: any
...
...
```

**Comment by hdeshev** [comment]
The error is caused by the TypeScript compiler not being able to find the iOS platform types. We do not ship those with the tns-core-modules package. @getmetorajesh's solution is the simplest, and I usually prefer it.

An alternative approach would be to add the [tns-platform-declarations](https://www.npmjs.com/package/tns-platform-declarations) package to your project and reference `node_modules/tns-platform-declarations/ios.d.ts`. That should get all definitions in your project. A word of warning though -- your compile time will go up, as `ios.d.ts` is pretty big.

**Comment by NeerajBah** [comment]
I tried the solution by @getmetorajesh but that doesn't seem to work completely. I tried declaring them as "class" and it compiled. However when I added "FBSDKApplicationDelegate" and FBSDKApplicationDelegate.sharedInstance() it did not compile as these classes were not found. I am using TypeScript 1.8.10.  Can you please help?
