### ISSUE TITLE
ListView - Reusing existing view - is not fully updated when switched 

### ISSUE THREAD

**Issue by matt4446** [NativeScript/nativescript-angular#298]
Running on Android (Genymotion).

I have a listview with 100 + items (number doesn't matter too much as long as it repeats). The item template has two modes and the problem comes when some content inside the row is expanded (it remains open where the item view is reused ie row 1 becomes row 11, row 2 becomes row 12 etc). 

It has two modes:
- competitor result  (Name + Rank, Total Score)
- expanded row (clicking on the row), which details the scores. Example:
 
![image](https://cloud.githubusercontent.com/assets/1550939/16177905/ad8b8bd2-3631-11e6-94aa-e4296539a86f.png)
First item is expanded and the later ones are not. 

The listview is working well enough (I had previously used `ng-for` but that made it crash after a certain amount of rows, but it didn't have this side effect). The listview is mostly doing well excluding the state of the expanded item repeating on the reused view:

``` js 
//JS: ListView.onItemLoading: 125 - Reusing existing view
//JS: ListView.onItemLoading: 89 - Reusing existing view
```

- [Listview Page](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/competition/grade/grade.page.ts#L36-L42)
- [Component](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/templates/competitor.results.ts)

But when the item is reused where a previous row had expanded it stays open throughout the listview: 
![expanded-stays-open](https://cloud.githubusercontent.com/assets/1550939/16177766/0f88d546-362e-11e6-8e18-e4178f5953dc.gif)
Depending on the reused view the first item won't necessarily be open when scrolled back to the top either. 

`*ngIf="expanded"` does not appear to take effect when scrolling where the template is replaced. So after every x in the list, it will display the item as open regardless (see the gif above). However, everything inside that [StackLayout ](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/templates/competitor.results.ts#L25-L35) is correct (all values correct to the person on the item including the detail part). The right scores are shown, withdrawn (which also has a `ng-if`) is correct. It is just odd that one.

I expect the problem comes down to change detection but I've tried a few and it's made no difference. 

### Hierarchy: 

- ListView
- [ListView template](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/competition/grade/grade.page.ts#L37-L41) - pushes the data into the child component below
- [CompetitorResult](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/templates/competitor.results.ts) - Child component of the list view template. Has the content for the two templates for expanded and not (depending on the expanded state). Tapping on the item switches the expanded state. 

### Reproduce:
Grab the project from [GIT](https://github.com/matt4446/WhatsMyScore2-NativeScript) 

1. Select Leagues & Regions 
2. Select Bucs 
3. Select BUCS 2016 Day 1 <- more data 
4. Select Grades
5. Select a grade with >20 competitors (BUCS 4/5 Female have the most competitors) 
6. Tap on a person to expand it. 
7. Scroll down the list. 

Any ideas anyone?

**Comment by vakrilov** [comment]
Hey @matt4446 
I noticed that you keep the `expanded` state inside a filed of the component ([here](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/templates/competitor.results.ts#L46)) -  so when the same component is reused.recycled to show different item of the list - the `expanded` state is reused too.
Couple of solutions come to my mind:

* Move the `expanded` state into the item(`ICompetitor` type) so that the state will be preserved in the item itself, not the component showing it. When an item is expanded and moved out and the into view - it will remain expanded.
* Reset the `expanded` state inside [`competitor setter`](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/templates/competitor.results.ts#L53-L58). This means that if an item is expanded and then moved out and then into view - it will show as collapsed again.

I hope that helps

**Comment by matt4446** [comment]
@vakrilov Thanks, you've saved me a few hours

Silly me. Ok so that means I have a dozen or so *static* `<competitor-result>` components hanging around (i was still imagining all rows to be created, which just got replaced as needed)   ... makes sense. 

The model ... yes, I can stash the flag there, but I think I will just create a more stateful context on the items for the listview:
```js
{
   expanded: yay/nay 
   person: person  
}
```

It's highly likely to work given the rest of the view is behaving as expected when the data changes so I'll close it.
