### ISSUE TITLE
Document the use of the RC3 router?

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/nativescript-angular#306]
Add some documentation for the developments since RC1 (which is used in the ng2 tutorial). I think the biggest change is the router?

**Comment by leocaseiro** [comment]
I agree that the documentation needs an upgrade, but for the time being, you can check this example out https://github.com/NativeScript/nativescript-angular/tree/master/ng-sample/app/examples/router

**Comment by jlooper** [comment]
We really need a 'state of the art' with the router, including support for http calls and passing parameters over the router (which has changed afaik) ... the Slack channel is crying out in the wilderness 😨

**Comment by matt4446** [comment]
I've started a new project off with RC3 + router. It seemed quite easy to understand. The only thing that  stumped me was the setup for a bit until I spotted: [nsProvideRouter](https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/router/page-router-outlet-test.ts#L126-L128) 
I'll upgrade one of my public samples somewhen soon to provide the basics if the documentation takes a while.

**Comment by harlankoehn** [comment]
I think this is a significant issue. I created a new Angular NS project (tns create my-app --ng) and then tried to configure the router and I never could get it to work. I tried using the router-deprecated as well as the new router and both of them result in error messages. Specifically, I'm seeing "No provider for RouterOutletMap" when using router-deprecated as well as when trying to use the newer router. Am I missing some important little piece here? Is it documented somewhere already? I've tried to follow every example and every piece of documentation I can find and nothing seems to fix it. It seems like a mismatch of packages:

`    "dependencies": {
        "@angular/common": "2.0.0-rc.3",
        "@angular/compiler": "2.0.0-rc.3",
        "@angular/core": "2.0.0-rc.3",
        "@angular/http": "2.0.0-rc.3",
        "@angular/platform-browser": "2.0.0-rc.3",
        "@angular/platform-browser-dynamic": "2.0.0-rc.3",
        "@angular/platform-server": "2.0.0-rc.3",
        "@angular/router": "3.0.0-alpha.7",
        "@angular/router-deprecated": "2.0.0-rc.2",
        "nativescript-angular": "0.2.0",
        "tns-core-modules": "^2.1.0"
    },
    "devDependencies": {
        "nativescript-dev-typescript": "^0.3.2"
    }`

**Comment by vakrilov** [comment]
[Angular navigation article](http://docs.nativescript.org/angular/core-concepts/navigation-angular.html) updated.
