### ISSUE TITLE
Running ng-sample causes a reboot of a Galaxy S4 and error in emulator

### ISSUE THREAD

**Issue by mattgalvin** [NativeScript/nativescript-angular#307]
I did a completely clean checkout and ran ng-sample per instructions. On my emulator, as soon as the application starts up I get the message "Unfortunately, Launcher3 has stopped." but the application runs. When I run it on my Galaxy S4, as soon as the app attempts to start up, the device freezes for about 30 seconds and then reboots. Running on a Moto X (2nd Generation), the app starts up with no issue.

Android Versions:
Emulator: v6 (API 23)
MotoX: v5.1.1 (API 22)
S4: v5.0.1 (API 21)

The application that I'm writing is not using the most recent version (angular rc.1 and nativescript-angular 0.1.6) and it is deploying fine.

I do not have a Mac so I cannot test iOS.

--log TRACE does not provide any error outputs.

Possibly the same as this report https://github.com/NativeScript/NativeScript/issues/2369 in the main NativeScript repo.

**Comment by mattgalvin** [comment]
At least for the emulator, it seems to be related to how the emulator is started.

If I run "tns run android --emulator" without the emulator already running, the project builds, starts the emulator, and then displays the "Unfortunately, Launcher3 has stopped." message. Dismiss the error and ng-sample starts.

If start the emulator using the AVD and then run "tns run android --emulator", the project builds, deploys the application to the running emulator, and starts up just fine. The launcher error does not happen.

I'm going to try installing the APK manually and running on my Galaxy instead of using tns run.

If that works, it'll at least let me continue working but that's a horrible workflow (I'm trying to upgrade specifically to see if the latest versions fix a different issue that I'm seeing on Galaxy devices so all of my testing has to be on the device).

**Comment by mattgalvin** [comment]
Installing the APK manually runs without an issue. So it's something related to the launching process when using tns run.

**Comment by dtopuzov** [comment]
Users report reboot issue is solved with {N} 2.2.1. Please try it and reopen if it is still an issue.
