### ISSUE TITLE
ListPicker on iOS doesn't resize correctly

### ISSUE THREAD

**Issue by sebawita** [NativeScript/nativescript-angular#314]
This issue only happens on iOS. On Android the ListPicker behaves as expected.

Setting the width on ListPicker doesn't work as expected. The component's actual width changes, however the text that should be displayed doesn't appear in the middle of the component after resizing it, but instead it appears where it would be if the component was not resized.

In short if I set width="50%" then the text will be on the right side of the ListPicker, if I set the width to 30% then the text won't be visible at all. Also the same happens when the width is set to a specific value (not %).

Similarly if I have a grid with 3 columns, each with a ListPicker, then each ListPicker will be cropped and not very usable.

<GridLayout rows="auto" columns="*, *, *">
    <ListPicker row="0" col="0"
        [items]="availableEyes" 
        [(ngModel)]="selectedEyesIndex" 
        (selectedIndexChange)="reloadAvatar()">
    </ListPicker>
    <ListPicker row="0" col="1"
        [items]="availabelNoses" 
        [(ngModel)]="selectedNoseIndex" 
        (selectedIndexChange)="reloadAvatar()">
    </ListPicker>
    <ListPicker row="0" col="2"
        [items]="availableMouths" 
        [(ngModel)]="selectedMouthIndex" 
        (selectedIndexChange)="reloadAvatar()">
    </ListPicker>
</GridLayout>

**Comment by nsndeck** [comment]
The underlying native iOS UIPickerView component does not support resizing - it is designed to used the entire width of the screen. Instead it supports adding multiple components to represent different columns (instead of different pickers). Unfortunately for the time being NativeScript ListPicker component does not support it.
