### ISSUE TITLE
Failed to find module "@angular/router/common_router_providers" ,  relative to : /app/tns_module

### ISSUE THREAD

**Issue by nithinshiriya** [NativeScript/nativescript-angular#317]
I am getting below error
Failed to find module "@angular/router/common_router_providers" ,  relative to : /app/tns_module

https://github.com/nithinshiriya/NativescriptAngularStarter

tns 2.1.0
Package.json
		"@angular/common": "^2.0.0-rc.3",
		"@angular/compiler": "^2.0.0-rc.3",
		"@angular/core": "^2.0.0-rc.3",
		"@angular/platform-browser": "^2.0.0-rc.3",
		"@angular/platform-browser-dynamic": "^2.0.0-rc.3",
		"@angular/platform-server": "^2.0.0-rc.3",
		"@angular/router": "^3.0.0-alpha.7",
		"@angular/router-deprecated": "^2.0.0-rc.2",
		"nativescript-angular": "^0.2.0",
		"tns-core-modules": "^2.1.0"

**Comment by nithinshiriya** [comment]
I have resolved this issue.

"**@angular/router": "^3.0.0-alpha.7**" however in my node_modules the version was **@angular/router": "^3.0.0-alpha.8** 


Make sue you have installed right version of router. [@angular/router": "^3.0.0-alpha.7]

**Comment by ngydat** [comment]
I also have the issue but not because of the difference of version of the router :
[https://github.com/ngydat/connect](https://github.com/ngydat/connect)

**Comment by georgeedwards** [comment]
What is the **correct** version? I am using ng2 - rc.4 so I had `3.0.0-beta.2` of the **@angular/router** and am still struggling...
