### ISSUE TITLE
No provider for RouterOutletMap! {NS} 2.1.0

### ISSUE THREAD

**Issue by seb-bizeul** [NativeScript/nativescript-angular#318]
Hi,

I recently upgrade to v2.1.0 and started a new App.

I think there is a bug with the Angular router or maybe the NS_ROUTER_PROVIDERS.
Here is the error when i run 

     tns run android 

on my Nexus 5x:

    JS: EXCEPTION: Error in ./AppComponent class AppComponent - inline template:0:0
    JS: ORIGINAL EXCEPTION: No provider for RouterOutletMap!

Here is my Code:

main.ts:
    
    import {nativeScriptBootstrap} from "nativescript-angular/application";
    import {AppComponent} from "./app.component";

    nativeScriptBootstrap(AppComponent);

and my app.component.ts component :

    import {Component} from "@angular/core";
    import {RouteConfig} from '@angular/router-deprecated';
    import {HTTP_PROVIDERS} from "@angular/http";
    import {NS_ROUTER_DIRECTIVES, NS_ROUTER_PROVIDERS} from 'nativescript-angular/router';
    import LoginPage from './components/login/login.component';

    @Component({
        selector: "my-app",
        directives: [NS_ROUTER_DIRECTIVES],
        providers: [NS_ROUTER_PROVIDERS, HTTP_PROVIDERS],
        template: "<page-router-outlet></page-router-outlet>"
    })
    @RouteConfig([
         { path: '/Login', component: LoginPage, name: 'Login', useAsDefault: true}
    ])
    export class AppComponent { }

the package.json dependencies :

    "dependencies": {
        "@angular/common": "2.0.0-rc.3",
        "@angular/compiler": "2.0.0-rc.3",
        "@angular/core": "2.0.0-rc.3",
        "@angular/http": "2.0.0-rc.3",
        "@angular/platform-browser": "2.0.0-rc.3",
        "@angular/platform-browser-dynamic": "2.0.0-rc.3",
        "@angular/platform-server": "2.0.0-rc.3",
        "@angular/router": "3.0.0-alpha.7",
        "@angular/router-deprecated": "2.0.0-rc.2",
        "nativescript-angular": "0.2.0",
        "tns-core-modules": "^2.1.0"
      },

I remember having the same problem with ng2 a few months ago and solve it by declaring the providers in the bootstrap function of the main.ts file like this:

    bootstrap(AppComponent, [
         NS_ROUTER_DIRECTIVES, 
         NS_ROUTER_PROVIDERS
    ])

But still doesn't work...
Regards

**Comment by DomGaud** [comment]
same here.

**Comment by DomGaud** [comment]
Try import `NS_ROUTER_DIRECTIVES`, `NS_ROUTER_PROVIDERS` from `"nativescript-angular/router-deprecated/ns-router-deprecated"`

```javascript
import {NS_ROUTER_DIRECTIVES, NS_ROUTER_PROVIDERS} from "nativescript-angular/router-deprecated/ns-router-deprecated";
```

**Comment by seb-bizeul** [comment]
Works like à charm ! Thank you

**Comment by vakrilov** [comment]
This was a [breaking change we made in the `0.1.7`](https://github.com/NativeScript/nativescript-angular/blob/master/CHANGELOG.md#breaking-changes).
If you are using the `@angular/router-deprecated` you should also use the `nativescript-angular/router-deprecated`.

**Comment by johntomcy** [comment]
In 2.2.0 i got the error showed in the main question. I added the below line:
import {ROUTER_DIRECTIVES} from '@angular/router';

and also added ROUTER_DIRECTIVES in the directives and i got it working.
Not sure whether this will help other, but this is how i got this error vanish.

**Comment by knitesh** [comment]
import {NS_ROUTER_DIRECTIVES, NS_ROUTER_PROVIDERS} from "nativescript-angular/router-deprecated/ns-router-deprecated";
-- works

**Comment by mannanj** [comment]
this no longer works!
