### ISSUE TITLE
ListView on ios crashing

### ISSUE THREAD

**Issue by jahidshohel** [NativeScript/nativescript-angular#322]
I am using `tns --version` ---> 2.1.0

I have a custom row on a list view. Which runs on Android, but crashes on iOS (sometimes). By sometimes, I mean, it works on first launch, but as soon as I move away from the segment (the list view is on first segment of a segmented bar), and then come back to that segment, then it crashes.

> `<StackLayout>
     <ListView [items]="items">
        <template let-item="item">
            <list-item-component [item]="item"></list-item-component>
        </template>
    </ListView>
</StackLayout>`

However, if I remove the custom row and do the view inline, then it works on both Android and iOS.

> `<StackLayout>
     <ListView [items]="items">
        <template let-item="item">
            <StackLayout>
                <Label [text]="item.title" textWrap="true"></Label>
            </StackLayout>
        </template>
    </ListView>
</StackLayout>`

Here is the stacktrace I get-

`Jul  2 00:47:19 --- last message repeated 3 times ---
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/nativescript-angular/directives/list-view-comp.js:64:24: ListView.onItemLoading: 0 - Creating view from template
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/nativescript-angular/directives/list-view-comp.js:64:24: ListView.onItemLoading: 1 - Creating view from template
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/nativescript-angular/directives/list-view-comp.js:64:24: ListView.onItemLoading: 2 - Creating view from template
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/nativescript-angular/directives/list-view-comp.js:60:24: ListView.onItemLoading: 0 - Reusing exisiting view
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: EXCEPTION: Error in pages/actionbar/tabs/tab1/tab1.html:1:4
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: ORIGINAL EXCEPTION: TypeError: undefined is not an object (evaluating 'viewRef.context')
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: ORIGINAL STACKTRACE:
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: setupViewRef@file:///app/tns_modules/nativescript-angular/directives/list-view-comp.js:72:30
	onItemLoading@file:///app/tns_modules/nativescript-angular/directives/list-view-comp.js:69:26
	_handle_itemLoading_2_0
	[native code]
	file:///app/tns_modules/@angular/core/src/linker/view.js:316:36
	invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:281:34
	onInvoke@file:///app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:45:47
	invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:280:43
	runGuarded@file:///app/tns_modules/zone.js/dist/zone-node.js:188:54
	file:///app/tns_modules/zone.js/dist/zone-node.js:164:40
	notify@file:///app/tns_modules/data/observable/observable.js:155:31
	notifyForItemAtIndex@file:///app/tns_modules/ui/list-view/list-view.js:41:20
	_prepareCell@file:///app/tns_modules/ui/list-view/list-view.js:285:44
	tableViewCellForRowAtIndexPath@file:///app/tns_modules/ui/list-view/list-view.js:62:31
	UIApplicationMain@[native code]
	start@file:///app/tns_modules/application/application.js:272:26
	file:///app/tns_modules/nativescript-angular/application.js:81:26
	ZoneAwarePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:542:38
	nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:80:23
	anonymous@file:///app/main.js:4:36
	evaluate@[native code]
	moduleEvaluation@[native code]
	[native code]
	promiseReactionJob@[native code]
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: ERROR CONTEXT:
Jul  2 00:47:19 samara sampleGroceries[24951]: CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:370:16: [object Object]
Jul  2 00:47:19 samara sampleGroceries[24951]: 1   0x64050 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
Jul  2 00:47:19 samara sampleGroceries[24951]: 2   0x72bc50 ffi_closure_inner
Jul  2 00:47:19 samara sampleGroceries[24951]: 3   0x72c5a2 ffi_closure_i386
Jul  2 00:47:19 samara sampleGroceries[24951]: 4   0x1674a7d -[UITableView _createPreparedCellForGlobalRow:willDisplay:]
Jul  2 00:47:19 samara sampleGroceries[24951]: 5   0x1644b32 -[UITableView _updateVisibleCellsNow:isRecursive:]
Jul  2 00:47:19 samara sampleGroceries[24951]: 6   0x1663416 __29-[UITableView layoutSubviews]_block_invoke
Jul  2 00:47:19 samara sampleGroceries[24951]: 7   0x167e6cc -[UITableView _performWithCachedTraitCollection:]
Jul  2 00:47:19 samara sampleGroceries[24951]: 8   0x16632eb -[UITableView layoutSubviews]
Jul  2 00:47:19 samara sampleGroceries[24951]: 9   0x15b93d4 -[UIView(CALayerDelegate) layoutSublayersOfLayer:]
Jul  2 00:47:19 samara sampleGroceries[24951]: 10  0x330b059 -[NSObject performSelector:withObject:]
Jul  2 00:47:19 samara sampleGroceries[24951]: 11  0x5a1e096 -[CALayer layoutSublayers]
Jul  2 00:47:19 samara sampleGroceries[24951]: 12  0x5a118b6 CA::Layer::layout_if_needed(CA::Transaction*)
Jul  2 00:47:19 samara sampleGroceries[24951]: 13  0x5a1171a CA::Layer::layout_and_display_if_needed(CA::Transaction*)
Jul  2 00:47:19 samara sampleGroceries[24951]: 14  0x5a03ee7 CA::Context::commit_transaction(CA::Transaction*)
Jul  2 00:47:19 samara sampleGroceries[24951]: 15  0x5a38847 CA::Transaction::commit()
Jul  2 00:47:19 samara sampleGroceries[24951]: 16  0x5a39108 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
Jul  2 00:47:19 samara sampleGroceries[24951]: 17  0x374e75e __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
Jul  2 00:47:19 samara sampleGroceries[24951]: 18  0x374e6be __CFRunLoopDoObservers
Jul  2 00:47:19 samara sampleGroceries[24951]: 19  0x374403c __CFRunLoopRun
Jul  2 00:47:19 samara sampleGroceries[24951]: 20  0x3743846 CFRunLoopRunSpecific
Jul  2 00:47:19 samara sampleGroceries[24951]: 21  0x374365b CFRunLoopRunInMode
Jul  2 00:47:19 samara sampleGroceries[24951]: 22  0x54b4664 GSEventRunModal
Jul  2 00:47:19 samara sampleGroceries[24951]: 23  0x54b44a1 GSEventRun
Jul  2 00:47:19 samara sampleGroceries[24951]: 24  0x14e8eb9 UIApplicationMain
Jul  2 00:47:19 samara sampleGroceries[24951]: 25  0x72c468 ffi_call_i386
Jul  2 00:47:19 samara sampleGroceries[24951]: file:///app/tns_modules/rxjs/Subscriber.js:229:22: JS ERROR EXCEPTION: Error in pages/actionbar/tabs/tab1/tab1.html:1:4
	ORIGINAL EXCEPTION: TypeError: undefined is not an object (evaluating 'viewRef.context')
	ORIGINAL STACKTRACE:
	setupViewRef@file:///app/tns_modules/nativescript-angular/directives/list-view-comp.js:72:30
	onItemLoading@file:///app/tns_modules/nativescript-angular/directives/list-view-comp.js:69:26
	_handle_itemLoading_2_0
	[native code]
	file:///app/tns_modules/@angular/core/src/linker/view.js:316:36
	invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:281:34
	onInvoke@file:///app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:45:47
	invoke@file:///app/tns_modules/zone.js/dist/zone-node.js:280:43
	runGuarded@file:///app/tns_modules/zone.js/dist/zone-node.js:188:54
	file:///app/tns_modules/zone.js/dist/zone-node.js:164:40
	notify@file:///app/tns_modules/data/observable/observable.js:155:31
	notifyForItemAtIndex@file:///app/tns_modules/ui/list-view/list-view.js:41:20
	_prepareCell@file:///app/tns_modules/ui/list-view/list-view.js:285:44
	tableViewCellForRowAtIndexPath@file:///app/tns_modules/ui/list-view/list-view.js:62:31
	UIApplicationMain@[native code]
	start@file:///app/tns_modules/application/application.js:272:26
	file:///app/tns_modules/nativescript-angular/application.js:81:26
	ZoneAwarePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:542:38
	nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:80:23
	anonymous@file:///app/main.js:4:36
	evaluate@[native code]
	moduleEvaluation@[native code]
	[native code]
	promiseReactionJob@[native code]
	ERROR CONTEXT:
	[object Object]
Jul  2 00:47:19 samara com.apple.CoreSimulator.SimDevice.209E4B11-CCD2-4D5D-943D-7FF333E0F668.launchd_sim[24669] (UIKitApplication:org.nativescript.groceries[0xb29b][24951]): Service exited due to signal: Segmentation fault: 11

`

**Comment by nsndeck** [comment]
I've tried to reproduce the issue unfortunately to no avail. It works just fine with an inline template and custom control.
@jahidshohel You are talking about SegmentedBar - since I do not a way to add something more than just a text in a `SegmentedBar` I performed my test with `TabView`.Could you please try your scenario with our latest version (just delete platforms forlder before)?

**Comment by jahidshohel** [comment]
@nsndeck The use case is like this -

I have three items (lets call them tabs, easier to write) on a  `SegmentedBar`. When 1st tab is selected I was showing a `ListView`. The list view works perfectly as long as I have inline view component declared like below -
`<StackLayout> 
    <ListView [items]="items">
    <template let-item="item"> <StackLayout> <Label [text]="item.title" textWrap="true"></Label> </StackLayout> </template> </ListView> </StackLayout>`

But instead of having a very large view with all 3 tabs view items, I wanted to make each tab's view as a separate component like below -
`<StackLayout> <ListView [items]="items"> <template let-item="item"> <list-item-component [item]="item"></list-item-component> </template> </ListView> </StackLayout>`

And that caused iOS app crashing. You can find the stack trace above.

I don't think trying out same scenario with `TabView` can/will cause same problem.

**Comment by nsndeck** [comment]
@jahidshohel Could you send me the entire page template and code behind, since I still cannot simulate the problem? Thanks in advance.

**Comment by jahidshohel** [comment]
@nsndeck Here is the code. Also please take a look into this video https://drive.google.com/file/d/0BwzkDzuXQGx8cTB0TVI3bXdFQms/view?usp=sharing

**tab1.html**
`<StackLayout>
    <ListView [items]="items">
        <template let-item="item">
            <list-item-component [item]="item"></list-item-component>
        </template>
    </ListView>
</StackLayou
`

**tab1.componenet.ts**
`import {Component} from "@angular/core";
import {ListItemComponent} from "./list-item/list-item.component";

@Component({
    selector: "tab1",
    directives: [ListItemComponent],
    templateUrl: "pages/actionbar/tabs/tab1/tab1.html",
    styleUrls: ["pages/actionbar/tabs/tab1/tab1-common.css", "pages/actionbar/tabs/tab1/tab1.css"],
})
export class Tab1Page {
    public items:Array<any> = [
        {title: "Javeria Jahid"},
        {title: "Farhana Kabir"},
        {title: "Jahid Shohel"}
    ];

    onBooTap(e:any, item:any){
        console.log("Item boooooooo: ", JSON.stringify(item));
    }
}
`

**lite-item.html**
`
<StackLayout>
    <Label text="{{item.title}}"></Label>
</StackLayout>
`

**lit-item.component.ts**
`
import {Component, Input} from "@angular/core";

@Component({
    selector: "list-item-component",
    templateUrl: "pages/actionbar/tabs/tab1/list-item/list-item.html",
    styleUrls: ["pages/actionbar/tabs/tab1/list-item/list-item-common.css", "pages/actionbar/tabs/tab1/list-item/list-item.css"],
})
export class ListItemComponent {
    @Input() item: any;
}
`

**Comment by nsndeck** [comment]
@jahidshohel I've created a [gist](https://gist.github.com/nsndeck/3c116f49294bf4087e84ef09d4390edb) with my sample project where I'm trying to reproduce the issue.
Could you please take a look what I'm doing wrong in my attempts to simulate the problem?

P.S. An easy way to run this code is:
1. Create an empty nativescript-angular app:
`tns create NSA_Issue_322 --ng`
2. Copy all four files from gist (app.component.html, app.component.ts, list-item.component.html, list-item.component.ts) into app folder (app.component.* files should be replaced).
3. run the app `tns run ios`

**Comment by jahidshohel** [comment]
@nsndeck It seems like your example is working. I tried to replace your code with my code in my project, but its failing. I believe it has something to do with how the project was build or configured. As you mentioned, creating an app from scratch doesn't give the error.

However, I am leaving my old example and using your project so that I can move forward. Already lost lots of time.

**Comment by nsndeck** [comment]
Generally removing `platforms` and `node_modules` folders (may require and some little adjustments to package.json file) within your app will bring you latest and greatest versions of all dependencies, run-time and modules like for a newly created app. Sorry for the lost time.

**Comment by jahidshohel** [comment]
I tried that several time, but no luck. Anyway seems like its ok now. Thanks a lot :)
