### ISSUE TITLE
Angular template is broken and updating to RC4 fixes it

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#323]
_From @tinchou on July 1, 2016 20:51_

Hi,

I just tried out the angular template (`tns create demo --ng`) and it's broken. It'll compile but then display an error message in the emulator.

I fixed it by manually updating to RC4:

```
  #...
  "dependencies": {
    "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/platform-server": "2.0.0-rc.4",
    "@angular/router": "3.0.0-beta.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    #...
```

_Copied from original issue: NativeScript/NativeScript#2404_

**Comment by tsonevn** [comment]
Hi @tinchou,

I tested your scenario, however I was unable to reproduce such an issue. Could you try to upgrade to latest NS using the described steps [here](https://docs.nativescript.org/releases/upgrade-instructions) and then to create new sample project using `tns create demo --ng`.

Let me know whether this helps .

**Comment by tinchou** [comment]
I tried again and it's working now ¯\_(ツ)_/¯

Thanks for checking!
