### ISSUE TITLE
iconSource doesn't seem to work in TabView

### ISSUE THREAD

**Issue by aalhaimi** [NativeScript/nativescript-angular#328]
Hi all, 

I've created a tabview starter project, but can't implement icons using iconSource property as indicated in the official examples. A copy of my project can be found in this repo: 
https://github.com/aalhaimi/nativescript-angular2-tabview-starter

Thanks for any pointers.

**Comment by leocaseiro** [comment]
I've tried on ios emulator and it worked for me.

Make sure you run `tns prepare ios` everytime you add a new media inside App_Resources. As Nativescript will copy to your `platforms` dir.

**Comment by aalhaimi** [comment]
Hmm.. I can see the icon in the platform directory under 'Resources' subfolder. I wonder if Xcode 7.2.1 has anything to do with this.. I will update to 7.3.1 and report back. Thanks, @leocaseiro!

**Comment by aalhaimi** [comment]
Problem solved. Updating to Xcode 7.3.1. didn't fix the problem.. So, I updated Nativescript installation, took care of the breaking changes, and the icons appeared. Closing this issue now!
