### ISSUE TITLE
nsRouterLink with relative path stops working after navigation

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/nativescript-angular#329]
The `nsRouterLink` directive stops working after navigation when the route is relative.
To reproduce:

1. Have a page with relative `nsRouterLink`
2. Navigate forward to other page
3. Navigate back
4. The link stops working

**Comment by jlooper** [comment]
I can confirm this is a yucky bug. Thanks for taking a look, Alex :)

**Comment by vakrilov** [comment]
*Progress update*:
I have some hacky work-arounds in [this branch](https://github.com/NativeScript/nativescript-angular/tree/page-outlet-v3), but there are still issues with NS integration with the angular router described here angular/angular#7757. I hope to get some feedback on this from the NG team as well.

**Comment by NathanWalker** [comment]
Good insight Alex thanks for this update!
