### ISSUE TITLE
ng-conf May 4th - 6th 2016: pair on a proposal to present something amazing with ng2 + {N}

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#33]
I'd like to submit a proposal to present something on ng2 + {N} and was curious if anyone wanted to pair with me on preparing something that pushes the boundaries?

https://www.ng-conf.org/#/cfp

I'm beginning to brainstorm some ideas and am willing to code the majority of what we decide to present if someone wanted to take a crack at submitting a joint proposal. 

Time window to submit: Today - Feb. 14th.

No guarantees that we would get accepted but I'm willing to put forth a solid effort.

/cc @EddyVerbruggen @tjvantoll @hdeshev @vakrilov

**Comment by jlooper** [comment]
@NathanWalker I'd be happy to help, I don't currently know what our plans will be at ng-conf but I'm sure we'll be there in force both speaking and at a booth. Let us know what you'd like to do.

**Comment by NathanWalker** [comment]
@jlooper (and anyone else interested) let's take discussion to email: walkerrunpdx [at] gmail
Just send me hello and I'll respond with what I'm thinking.
