### ISSUE TITLE
Dynamic binding for *tabItem directive to show selected iconSource

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-angular#332]
Hi, I'm trying to make my tabItems dynamic. I'm trying to replace my icon.png the same way that it's done on [marketplace app](https://github.com/NativeScript/nativescript-marketplace-demo/blob/9e261667273506ef677a29490b04f439027ccb9e/app/examples/layouts/layouts-example.xml#L30).

I believe the tabItem directive gets wherever is on it's [ngOnInit](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/directives/tab-view.ts#L55) and after that won't update anymore. Are there any way to bind(watch) values, instead? So we could update the sourceIcon or text? 

```xml
<TabView [(ngModel)]="selectedIndex">
    <StackLayout *tabItem="{title: 'Tab1', iconSource: selectedIndex == 1 ? 'res://icona' : 'res://icona1'}">
        <Label text="You are in Tab 1"></Label>
        <Label text="{{selectedIndex}}"></Label>
    </StackLayout>
    <StackLayout *tabItem="{title: 'Tab2', iconSource: selectedIndex == 1 ? 'res://iconb' : 'res://iconb1'}">
        <Label text="You are in Tab 2"></Label>
        <Label text="{{selectedIndex}}"></Label>
    </StackLayout>
</TabView>
```

```javascript
export class AppComponent {
    public selectedIndex: number = 0;
}
```

My label shows the correct `selectedIndex`, but the Tab keeps as it is on load. If I set `selectedIndex = 1` on my `ngOnInit`, shows the second tab selected tab, but after that, won't change the icon. The tab works great.

Thanks

**Comment by aalhaimi** [comment]
Exactly my problem.. I even tried replacing the whole JSON object, like: 
`*tabItem="selectedIndex == 1 ? { title: 'Tab1', iconSource:'res://icona'} : { title: 'Tab1', iconSource:'res://icona1'}"`
But it didn't work either.

**Comment by aalhaimi** [comment]
My temporary solution is to leave the icons fixed, and just change the text font color.. You can check it out [here](https://github.com/aalhaimi/nativescript-angular2-tabview-starter).

**Comment by nsndeck** [comment]
We are working on a solution for this scenario and it will be available by the end of the day in master branch (so 2-3 days after will be available in npm too). When I push the change will post a sample example how to use the new functionality of the TabViewDirective.
Sorry for the inconvenience caused.

**Comment by leocaseiro** [comment]
Thank you both for big help.

**Comment by aalhaimi** [comment]
Awesome.. Just saw the update in the master branch. Thanks @nsndeck!

**Comment by nsndeck** [comment]
Yep this is online now. For more information how to used it just review `ng-sample\app\examples\tab-view\tab-view-test.html` first tab. The example shows a binding for `title` property, but I can ensure you that it also works for `iconSource`.

**Comment by leocaseiro** [comment]
Hi @nsndeck, thank you for this fix.

I'd like to test it on my app, how do I use the newest code for `nativescript-angular`?
Do I need to wait for the npm?

Thanks

**Comment by leocaseiro** [comment]
I've tried to install versions `nativescript-angular@0.2.1` and `nativescript-angular@0.2.1-2016-07-18-737`, however, both are not working properly.

I'll wait for the next release.

**Comment by NathanWalker** [comment]
@leocaseiro you can use now with their recent `next` build setup. Point your npm package to this:
`"nativescript-angular": "next"`

👍

**Comment by leocaseiro** [comment]
Hi @NathanWalker, thanks for that. 
However, I believe the `next` version is getting an error perhaps with the router, because it's happening only while I direct with `router.navigate()`

```bash
file:///app/tns_modules/@angular/platform-server/src/parse5_adapter.js:619:96: JS ERROR Error: not implemented
```

I'll might investigate it later or just wait for the next release be published.

Again, Thanks for that.

**Comment by nsndeck** [comment]
Hi @leocaseiro,
nativescript-angular@0.2.1-2016-07-18-737 build should work fine with TabView iconSource binding. Could you please try it on a separate project (to eliminate any router related problems) and let me know how it goes? It will help me to fix any problem with TabView directive before official release. Thanks in advance.

**Comment by leocaseiro** [comment]
Hi @nsndeck, first of all, I'm sorry I didn't test before. I didn't have time to.

Well, thank you so much for this fix. I've just updated to the new `nativescript-angular@0.3.1` and it's working nice.

I'm able to custom the `title` and the `iconSource` as you mentioned.

However, I've noticed that the selectedColor is not working for my iconSource. They still getting the ios blue on selectedColor. It only works for text color.

My html:

```xml
<TabView #element [(ngModel)]="selectedIndex" selectedColor="#d8292f" *ngIf="!displayAuthentication">
    <template tabItem iconSource="{{selectedIndex === 0 ? 'res://tab1_filled' : 'res://tab1'}}">
        <StackLayout>
            <label text="My Tab 1"></label>
        </StackLayout>
    </template>
    <template tabItem iconSource="{{selectedIndex === 1 ? 'res://tab2_filled' : 'res://tab3'}}"
        <StackLayout>
            <label text="My Tab 2"></label>
        </StackLayout>
    </template>
    <template tabItem title="{{selectedIndex === 2 ? 'Tab 3 selected' : 'Tab 3'}}">
        <StackLayout>
            <label text="My Tab 2"></label>
        </StackLayout>
    </template>
</TabView>
```

Could you please help me with that?

Thanks.

**Comment by Ihor912** [comment]
Hi guys,
This solution for me. Maybe it will help someone else.

I use two different icons for the selection state and for the inactive state.
Also, property iosIconRenderingMode value should be "alwaysOriginal".

In template:
```
<TabView tabBackgroundColor="#6E7AFA" androidTabsPosition="bottom" iosIconRenderingMode="alwaysOriginal" (selectedIndexChanged)="tabViewIndexChange($event)">
    <page-router-outlet *tabItem="homeTab" name="homeTab"></page-router-outlet>
    <page-router-outlet *tabItem="settingsTab" name="settingsTab"></page-router-outlet>
</TabView>
```

In component:
```
homeTab: any;
settingsTab: any;

constructor() {
    this.homeTab  = { iconSource: this.getIconSource("home") };
    this.settingsTab  = { iconSource: this.getIconSource("settings") };
}

tabViewIndexChange(args) {
    const index = args.newIndex;
    this.homeTab = { iconSource: this.getIconSource(index === 0 ? "home_selected" : "home") };
    this.settingsTab = { iconSource: this.getIconSource(index === 1 ? "settings_selected" : "settings") };
}

getIconSource(icon: string): string {
    const iconPrefix = isAndroid ? "res://" : "res://tabIcons/";
    return iconPrefix + icon;
}
```
