### ISSUE TITLE
Failed to find module : @angular/router/common_router_providers

### ISSUE THREAD

**Issue by ngydat** [NativeScript/nativescript-angular#337]
As #317 the module cannot be found but the cause of the issue isn't the same. Here is a link to my code :
[https://github.com/ngydat/connect](https://github.com/ngydat/connect) 

Except @nithinshiriya (who obviously solved the issue), has anyone encountered the issue ?

Thank you in advance

**Comment by georgeedwards** [comment]
Yes I am currently facing it!

**Comment by triniwiz** [comment]
@ngydat  & @georgeedwards  try pinning your dependencies `^2.0.0-rc.3` -> `2.0.0-rc.3`  see`^`tells npm to match the most recent major version and sometimes something may not be compatible

**Comment by ngydat** [comment]
I found a [workaround](http://stackoverflow.com/questions/38294680/failed-to-find-module-angular-router-common-router-providers-error-with-angu/38309022?noredirect=1#comment64040054_38309022) :)

**Comment by georgeedwards** [comment]
So I suppose the real issue is that `nativescript-angular` isn't compatible with **angular@rc.4** or **router@3.0.0-beta.x**

**Comment by vakrilov** [comment]
The @angular/router package is still in beta and evolving fast. Naturally, this introduces breaking changes - especially for the NS integration that relies on some internal router files as well.

@triniwiz is right on spot - to be on the safe side pin your dependencies on exact version. Probably, when the @angular/router is out of beta (and angular is released officially) you can start using `^` again to get hotfixes.

**Comment by vakrilov** [comment]
I'm closing this for now. 
Feel free to reopen it if needed.
