### ISSUE TITLE
Label or Button [text] removing 0 from strings that starts with 0.

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-angular#344]
It seems that strings started with 0 are being treated as numbers.

I need to show some phone numbers that start with 0, but the app is removing the 0.

Code:

```html
<Label text="{{'01234'}}"></Label>
```

It results on `1234` only;

I've tried convert to string, concatenate empty string os spaces, and none of these solutions work.

Anybody with same issue?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#2455
