### ISSUE TITLE
Observable notification not updating UI when triggered from 'on' handler

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#346]
_From @victorhurdugaci on July 14, 2016 7:17_

Maybe I'm doing something totally wrong but I just can't figure it out why the example below doesn't work. Is this a bug?

1. `tns create Foo --ng`
2. `tns platform add android`
3. Replace `app.component.ts` with:

    ```typescript
    import {Component, ElementRef, ViewChild} from "@angular/core";
    import {Observable} from 'data/observable'
    import {StackLayout} from 'ui/layouts/stack-layout'
    import {Button} from 'ui/button'

    @Component({
        selector: "my-app",
        template:
        `<StackLayout #container>
            <Label [text]="model.count"></Label>
            <Button text="Button 1" (tap)="onTap()"></Button>
        </StackLayout>`,
    })
    export class AppComponent {
        public model = new Model();

        @ViewChild('container')
        private container: ElementRef;

        public ngOnInit() {
            var stack = <StackLayout>this.container.nativeElement;

            var button = new Button();
            button.text = "Button 2";
            button.on(Button.tapEvent, data => {
                this.ChangeModel();
            });

            stack.addChild(button);
        }

        public onTap() {
            this.ChangeModel();
        }

        private ChangeModel() {
            this.model.count++;
        }
    }

    class Model extends Observable {
        private _count: number = 0;

        get count() {
            return this._count;
        }
        set count(val: number) {
            console.log("Model updated");
            this._count = val;
            this.notifyPropertyChange('count', val);
        }
    }
    ```

4. Run
5. Tap *Button 1* and notice that the model (see the console log) and the label (see the UI) are updated
6. Tap *Button 2* and notice that the model is updated but the UI doesn't get the notification

CLI: 2.1.0
core modules: 2.1.0
tns-android: 2.1.1
OS: Win 10 x64
Emulator: Genymotion

_Copied from original issue: NativeScript/NativeScript#2453_

**Comment by tsonevn** [comment]
Hi @victorhurdugaci,
Thank you for reporting this issue.

I confirm that this is a real problem in NativeScript Angular2 project, when you are adding a Button as a child to the Layout on ngOnInit. I will move this issue in our [nativescript-angular](https://github.com/NativeScript/nativescript-angular) repo.  

Regard,
@tsonevn

**Comment by victorhurdugaci** [comment]
Thanks for moving this. Is there a workaround?

**Comment by nsndeck** [comment]
Hi @victorhurdugaci,
The problem comes from the fact that event handler for the button created with a code behind is executed outside angular2 zone which prevents angular2 change detection to detect changes and to reflect them into UI. So basically all you have to do is to wrap a code in the angular2 zone. For achieving this you have too options:

1. Inject Renderer - which in case with nativescript-angular will be a NativeScriptRenderer and use it `listen` method instead of `on`

``` TypeScript
import {Renderer} from "@angular/core";
import {NativeScriptRenderer} from "nativescript-angular/renderer";
...
constructor(private nsr: Renderer) {
}

....
var button = new Button();
button.text = "Button 2";
this.nsr.listen(button, Button.tapEvent, data => {
    this.ChangeModel();
});
```
2. The other options is to inject NgZone and wrap the code in the event handler into zone:

``` TypeScript
import {NgZone} from "@angular/core";
....

constructor(private zone: NgZone) {
}
....

private ChangeModel() {
   this.zone.run(() => {
       this.model.count++;
   });
}
```
I would recommend using the first approach with NativeScriptRenderer, where nativescript-angular deals with angular2 zone, because zone.run will be called unnecessary for the button created with HTML.
