### ISSUE TITLE
ActionBar and TabVew Color Matching Issue on some iOS Devices

### ISSUE THREAD

**Issue by aalhaimi** [NativeScript/nativescript-angular#348]
**Description:** 
If you specify a background color (through css or xml property), ActionBar and TabView elements will not display the corresponding color.. The view seems to display the corresponding color without a problem. 

**Context:** 
This happens when testing on iPhone 6 emulator.. However, iPad2 emulator works as expected. 
- Did some searching, and I believe this is related to this [issue](https://github.com/NativeScript/NativeScript/issues/2091). 

**Example:**
I will try to include a sample app, if needed. For now, here are some screenshots that displays how iPhone 6 and iPad 2 emulator renders `background-color: #d90429;`:

iPhone6 (`tns run ios --emulator --device 'iPhone 6' --sdk 9.3`): 
![iphone6](https://cloud.githubusercontent.com/assets/4491274/16848856/c4e80272-49c5-11e6-9af6-111e0eb0898d.png)

iPad2 (`tns run ios --emulator --device 'iPad 2' --sdk 9.3`):
![ipad2](https://cloud.githubusercontent.com/assets/4491274/16848855/c4e7b128-49c5-11e6-868f-9235413e88f6.png)

**Comment by vakrilov** [comment]
Hi @aalhaimi 
You are right - it is indeed same issue as NativeScript/NativeScript#2091. I believe it not angular-specific so I'm going to close this issue. Feel free to continue the discussion in NativeScript/NativeScript#2091.
