### ISSUE TITLE
Variables Not Being Updated In UI As Of RC3, Maybe Zone Issue?

### ISSUE THREAD

**Issue by nraboy** [NativeScript/nativescript-angular#351]
Hey,

I am having an issue which I think may be a bug in how the zone is being handled.

I have an array which is bound to a `ListView`.  I can populate the array throughout the application and it updates fine in the `ListView`, however, when I update it via a listener, it doesn't seem to refresh in the UI.  I can confirm by printing it out that the value was added.

The strange thing is that this worked fine in RC1.  As soon as I switched over to RC3, it stopped working.  Did the zone break?  I know I can force update using NgZone, but I would prefer not to if I can avoid it.

Let me know what the plans are.  I think this user is having a similar issue:

https://github.com/NativeScript/nativescript-angular/issues/346

**Comment by vakrilov** [comment]
Hey @nraboy,
It sure looks like a zone issue, but it might be related to some optimizations we made in the `ListView` in the last release.
Can you please share more info about the listener that updates the array:

1. Is it a native listener?
1. Is it attached via code or markup?

One thing you can try is to execute the code of the listener inside a ngZone (with `zone.run(() => { ... });`). However, if the listener is attached in the markup this should be done automatically by the renderer.

**Comment by nraboy** [comment]
Hey @vakrilov,

Here is the project I'm working with (notice the highlighted lines):

https://github.com/couchbaselabs/nativescript-couchbase/blob/master/ng-demo/app/components/list/list.component.ts#L25-L39

Back in RC1, I did not need NgZone to refresh the UI from that listener.  The plugin code for that listener is as follows:

https://github.com/couchbaselabs/nativescript-couchbase/blob/master/couchbase.android.ts#L126-L138

Should I plan on using NgZone when it comes to plugin listeners?

Best,

**Comment by vakrilov** [comment]
@NathanWalker did a nice [snack-video](http://www.nativescriptsnacks.com/videos/2016/06/13/zoned-callbacks.html) on the matter.

Basically if you plugin exposes an API that uses callbacks and if you fire those in code that has gone trough native execution - you should wrap the callbacks with the `zonedCallback` function. It will ensure that the callback will be executed in the same zone as you are in the moment (which is usually the angular zone).

**Comment by nraboy** [comment]
I think I'll have to skip that.

I want my plugin to work with or without Angular 2.  By wrapping in a zonedCallback, I have a feeling it will exclude functionality for vanilla users.

**Comment by vakrilov** [comment]
The `zonedCallback` method is relatively safe - it will just return the same callback if there is no `zonejs` loaded in the app. Also it is added in the global context by the `tns-core-modules`, so you don't have to depend on angular to use it. 
You can check the code [here](https://github.com/NativeScript/NativeScript/blob/ffb82e250a8f6df6d55cf44836b35e5ac52d56fa/tns-core-modules/globals/globals.ts#L34-L45).
