### ISSUE TITLE
Hiding action bar for android

### ISSUE THREAD

**Issue by ahmedelgendy** [NativeScript/nativescript-angular#353]
I want to hide the action bar for Android
I tried actionBarHidden="true" but didn't work because I am using native script with Angular2 and I can't  use the `<page>` tag due to an error
Are there any solutions to hide it for all activities?
Thanks

**Comment by vakrilov** [comment]
For the initial page you can use the `startPageActionBarHidden` property of the in the application options when bootstrapping you app. [Docs link](http://docs.nativescript.org/angular/core-concepts/customizing-bootstrap.html#nativescript-application-options)

For subsequent page navigations you can inject the `Page` in your component and use `actionBarHidden`. [Docs link](http://docs.nativescript.org/angular/ui/action-bar.html#showinghiding-the-actionbar)

Hope that helps.

**Comment by ahmedelgendy** [comment]
Oh thank you

**Comment by dianjuar** [comment]
Just for the record
```typescript
import { Component, OnInit } from '@angular/core';

import { Page } from "ui/page";

export class YourComponent implements OnInit {

    constructor(private _page: Page) { }

    ngOnInit() {
        this._page.actionBarHidden = true;
    }
}
```

---------------

Is not better if the documentation is improved @vakrilov ?
I face the same problem and the documentation doesn't tell any of this.

https://docs.nativescript.org/angular/code-samples/ui/action-bar.html

**Comment by vakrilov** [comment]
@dianjuar You are absolutely right!
@NickIliev Can you please update the angular action-bar article with a section about `startPageActionBarHidden` when bootstrapping angular app.

**Comment by NickIliev** [comment]
@vakrilov it appears that it is already included in [this article section](http://docs.nativescript.org/angular/ui/action-bar.html#defining-the-actionbar)

**Comment by erkanarslan** [comment]
This option was working prior to Nativescript 4 but doesn't work anymore.

**Comment by NickIliev** [comment]
@erkanarslan than you for noticing that - I will investigate the case.

Meanwhile, as a workaround, you could explicitly hide the action bar on the page it is shown while directly accessing the Page instance via DI.
```TS
constructor(private itemService: ItemService, private _page: Page) { 
    this._page.actionBarHidden = true;
}
```

**Comment by d4rkd0s** [comment]
So I've tried myself and the action bar is still showing... hmm...

```
import { Component, OnInit } from "@angular/core";
import { Page } from "ui/page";

@Component({
    selector: "Auth",
    moduleId: module.id,
    templateUrl: "./auth.component.html",
    styleUrls: ["./auth.component.css"]
})
export class AuthComponent implements OnInit {
    constructor(private _page: Page) {
        // Hides the action bar, that appears on android
        this._page.actionBarHidden = true;
    }

    ngOnInit(): void {

    }
}

```

Also tried

```
import { Component, OnInit } from "@angular/core";
import { Page } from "ui/page";

@Component({
    selector: "Auth",
    moduleId: module.id,
    templateUrl: "./auth.component.html",
    styleUrls: ["./auth.component.css"]
})
export class AuthComponent implements OnInit {
    constructor(page: Page) {
        // Hides the action bar, that appears on android
        page.actionBarHidden = true;
    }

    ngOnInit(): void {

    }
}

```

**Comment by d4rkd0s** [comment]
Ahh! I figured it out, so you can't have `createFrameOnBootstrap: true` in your main.ts and expect the ActionBar to go away, so you must set it to `createFrameOnBootstrap: false` I found my answer here:  https://github.com/NativeScript/nativescript-angular/issues/1439#issuecomment-406522534

**Comment by larssn** [comment]
@vakrilov Your link http://docs.nativescript.org/angular/core-concepts/customizing-bootstrap.html#nativescript-application-options is broken. Could you fix it?

**Comment by vakrilov** [comment]
Thanks @larssn 
I have updated the comment - no need to use the `startPageActionBarHidden` - you should be able to do this in a similar way for all pages (the 2nd approach in the answer)

**Comment by jktaylor21** [comment]
@vakrilov is there any way to globally disable the action bar for all pages? I'm converting my app to use schematics (adding web support) and I'm trying to tease out the nativescript specific stuff from my components. I haven't been able tease out the page DI though since I need it to hide the action bar so I am currently stuck with nativescript specific components so I can hide the action bar.

Any ideas would be appreciated, oh, and sorry for commenting on a closed issue. :-)

**Comment by jktaylor21** [comment]
FYI - just in case anyone else stumbles on this thread. I was able to solve my problem with the following simple method:

```
    hideActionBar() {
        const rootFrame = topmost();
        rootFrame.actionBarVisibility = 'never';
    }
```

That method lives in a service with a nativescript implementation (above) and a web implementation (empty) and it gets called from ngOnInit() for the components that have to worry about hiding the action bar. That allowed met to only have one component file.

**Comment by KissBalazs** [comment]
For any1 late for this party:
- actionBar cannot be hidden from app.component (root component)
- you either need to hide it in every component, or, 
- if your root component contains app-router, you can set this parameter to hide it `<page-router-outlet actionBarVisibility="never"></page-router-outlet>`

**Comment by olcayertas** [comment]
```
<template>
  <Page actionBarHidden="true">
      ...
  </Page>
</template>
```
