### ISSUE TITLE
create activity for each component

### ISSUE THREAD

**Issue by kazemihabib** [NativeScript/nativescript-angular#357]
when we have an activity for each component(page) and override methods of `onCreate()` and  `onPause()` and ... . we can handle to what should first happen if user pressed home button [user pressed this button in `page A`: hey app do job A before going  home --- user pressed this button in `page B` hey app do job B befor going home ] , backButton [user pressed this button in `page A`: hey app do job A before going  back --- user pressed this button in `page B` hey app do job B befor going back ]  and ... .
but when we have just one activity `com.tns.NativeScriptActivity`  we can put just one logic for whole app not for each page.
I don't know, maybe there is a better way than creating activity for each component but I think it would be really good if we could have these methods [onStop,onDestroy, onBackPressed,...] for each page.

**Comment by kazemihabib** [comment]
**UPDATE**:
using ```    application.android.off();```
and ```     application.android.on()``` 
will not help 
look at the this project https://github.com/kazemihabib/sample-tns-
I added `activityBackPressedEvent` listener to the login page and list page.
run it and in the `login page` and press back button it will log in the console `**nativescript back event fired in login page**`  in this time open the app login and in the `list page` press back button it will log
`**nativescript back event fired in list page**` and it will go to login page now press back button again 
it will log `nativescript back event fired in list page` but I want to log `**nativescript back event fired in login page**`  when some one press back in login page.
thats why I say they will not help.

**Comment by vakrilov** [comment]
There are some specifics when using page-navigation in NativeScript. The component you are navigating **from** is not destroyed and so when you navigate **back** to it is not created anew. There is more detailed explanation in [this article](https://github.com/NativeScript/nativescript-angular/wiki/Router#page-router-outlet), but probably this is the reason for the behavior you are seeing with the on/off methods.

That said, in you scenario it looks like it is more appropriate to use [route guards](https://angular.io/docs/ts/latest/guide/router.html#!#guards) to hook into the navigation events. You can also attach to the `Router.events` observable.

Note, the `master` version of the groceries app is already using [auth.guard](https://github.com/NativeScript/sample-Groceries/blob/master/app/auth.guard.ts) to redirect the initial navigation based on the login state - you might find it interesting.

**Comment by kazemihabib** [comment]
Thanks to this  post http://fluentreports.com/blog/?p=261
I found  a solution : 
 application.android.off();
 application.android.on() 
should be used in loaded and unloaded events.
