### ISSUE TITLE
Router Navigation Issue using ROUTER OUTLET

### ISSUE THREAD

**Issue by rrcoolp** [NativeScript/nativescript-angular#359]
Here is the issue with ROUTER:

http://stackoverflow.com/questions/38502132/nativescript-angular-router-3-0-0-alpha-7-navigation-failure

**Comment by vakrilov** [comment]
Answered [here](http://stackoverflow.com/questions/38502132/nativescript-angular-router-3-0-0-alpha-7-navigation-failure/38521758#38521758).

Closing this issue - continue discussion in SO.
