### ISSUE TITLE
row/col properties for Component don't work

### ISSUE THREAD

**Issue by victorhurdugaci** [NativeScript/nativescript-angular#365]
Maybe my expectation is incorrect but I thought that `row`/`col` properties work on any component. However, for the code below, `AComponent` is not set in row 1, col 1. Instead, it ends up in row 0 col 0 and it overlaps button "0".

Do I have to do anything special or redefine the row/col properties in the component?

```Typescript
import {Component} from "@angular/core";

@Component({
    selector: "AComponent",
    template: '<Button text="3"></Button>'
})
export class AComponent {
}

@Component({
    selector: "my-app",
    directives: [AComponent],
    template: `
        <GridLayout columns="auto, auto" rows="auto, auto">
            <Button text="0" row="0" col="0"></Button>
            <Button text="1" row="0" col="1"></Button>
            <Button text="2" row="1" col="0"></Button>
            <AComponent row="1" col="1"></AComponent>
        <GridLayout>`
})
export class AppComponent {
}
```

**Comment by vakrilov** [comment]
Currently, `row` and `col` properties do not automatically apply to the actual root element of the component.
There is a workaround for that: #278
