### ISSUE TITLE
Can we use the @angular/upgrade  with NativeScript?

### ISSUE THREAD

**Issue by yazantahhan** [NativeScript/nativescript-angular#369]
Hi,
I tried to use AngularJS 1.5 along with AngularJS 2 and NativeScript, but I got the following error after running it on an Android device:

`com.tns.NativeScriptException: failed to find module: "@angular/upgrade" relative to :/app/tns_module/ .....`.

The module was added using `npm i @angular/upgrade`
Thanks

**Comment by hdeshev** [comment]
Short answer - no. NativeScript supports Angular 2.0+ only. Angular 1.x doesn't support non-browser platforms.
