### ISSUE TITLE
How to bind value to element in html

### ISSUE THREAD

**Issue by enchev** [NativeScript/nativescript-angular#370]
_From @IvRRimum on July 26, 2016 11:48_

Hello,

So i have been battling this from yesterday.

Situation: When you open the app, you see a button and a label with text "hello there". WHen you click the button, text changes to "Ohh you clicked me".

Is it related to zonedCallbacks ? How does one do that ?

_Copied from original issue: NativeScript/NativeScript#2509_

**Comment by IvRRimum** [comment]
bump

**Comment by m-abs** [comment]
Not really an issue, but here:

```html
<Button [text]="labelValue" (tap)="labelValue = 'Ohh you clicked me'"></Button>
```

```typescript
@Component({
...
})
export class MyComponent {
   labelValue = 'hello there';
}
```

*Note*: The square bracket syntax `[text]`, it make it a dynamic value.
