### ISSUE TITLE
Tab to Next and Previous buttons to show on iOS and android keyboard 

### ISSUE THREAD

**Issue by dotdreaming** [NativeScript/nativescript-angular#372]
Is it possible to get the tab to Next and Previous buttons to show on iOS and android keyboard for TextFields inputs? It would improve the usability of my app somewhat. The ability to tab to the nxt TextField instead of having to scroll and tap into the next TextField would be great.

![input-next](https://cloud.githubusercontent.com/assets/808135/17172642/f16cec18-53ed-11e6-9298-6cea80748201.png)

**Comment by spike1292** [comment]
I used ReturnKeyType, here is an example with nativescript-angular:
https://github.com/NativeScript/sample-Groceries/blob/master/app/pages/login/login.html#L41

some more info about ReturnKeyType, see https://github.com/NativeScript/NativeScript/issues/713

**Comment by leocaseiro** [comment]
There's also a {N} plugin for iOS that uses the IOS **IQKeyboardManager**: https://github.com/tjvantoll/nativescript-IQKeyboardManager

**Comment by pmz** [comment]
@spike1292 the link is 404. Curious to see how you implemented it!

**Comment by vakrilov** [comment]
Probably [this](https://github.com/NativeScript/sample-Groceries/blob/2e36c8cb32a5a8578a484c37cc80e248560a920d/app/login/login.component.html#L41) is where the @spike1292 link has moved.

In any case - probably the **IQKeyboardManager** is what you are looking for.

**Comment by vakrilov** [comment]
Closing, please reopen if additional discussion is requiered

**Comment by alejandro-heredia-coderoad-com** [comment]
I got the IQKeyboardManager plugin to work but I can't get the previous and next arrows to be enabled. Maybe it's the markup. Any idea?

![screen shot 2017-12-15 at 3 37 09 pm](https://user-images.githubusercontent.com/19911943/34057576-f0686654-e1ad-11e7-9cb6-8b608e0be987.jpg)

**Comment by alejandro-heredia-coderoad-com** [comment]
I figured it out by putting the <TextField> elements inside the same parent element wrapper.
