### ISSUE TITLE
where RouterExtensions?

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#381]
_From @peirancao on July 30, 2016 5:12_

https://docs.nativescript.org/angular/core-concepts/navigation-angular.html#navigation-options

_Copied from original issue: NativeScript/NativeScript#2534_

**Comment by NickIliev** [comment]
_From @tsonevn on August 1, 2016 6:22_

Hi @peirancao, 

Could you provide some more info about your problem. It would also help if you could give me some sample project. 

Regards,
@tsonevn

**Comment by vakrilov** [comment]
Duplicate of #380

**Comment by diegomelo182** [comment]
I'm found "RouterExtensions" on "nativescript-angular/router", look this code:

``` typescript
import {RouterExtensions} from "nativescript-angular/router";

export class YourComponent {
	public constructor (private routerExtensions: RouterExtensions) {
		this.page.actionBarHidden = true;
	}
}
```

**Comment by weijyewang** [comment]
Thanks @diegomelo182   from saving my time digging into NativeScript code to search for the modules. The documentation could improve to specify where to import `RouterExtensions`
