### ISSUE TITLE
RadSideDrawer doesn't close on route change with showOverNavigation true

### ISSUE THREAD

**Issue by lukabers** [NativeScript/nativescript-angular#384]
Hello,
I'm using Radsidedrawer with showOverNavigation true.
Clicking on a menu link and changing the route cause this:

![schermata 2016-08-02 alle 11 19 54](https://cloud.githubusercontent.com/assets/8421302/17323601/19080456-58a3-11e6-8b39-8b58469e4106.png)

I have tried to close the drawer before the route change :
`goTo(position){
        this.drawer.closeDrawer();
        this.router.navigate([position]);
    }`
And it works for now on iOS but on Android i have to set a timeout before the router change.

Any solution?

thanks

**Comment by NickIliev** [comment]
The showOverNavigation for RadSideDrawer is currently not supported but this feature is on its way with the next release of nativescript-telerik0ui plugin. More details can be found [here](https://github.com/telerik/nativescript-ui-feedback/issues/61#issuecomment-286466919)
