### ISSUE TITLE
Webpack-based developer workflow

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#385]
We want to extend our nativescript-dev-webpack plugin and make it more web-like. We want it to be as similar to what popular seed projects (e.g. the [AngularClass webpack starter](https://github.com/AngularClass/angular2-webpack-starter)) as possible.
- [x] replace module prepares with a webpack bundling step that builds a bundle and places it in platforms/.../(android|ios)
- [x] integrate with `tns livesync --watch`. Might require changing nativescript-cli
- [x] take care of non-code assets by either copying them with a webpack plugin or integrating with the current `tns prepare` code.

**Comment by sis0k0** [comment]
The items from the list are already implemented.
