### ISSUE TITLE
Platform specific page transitions.

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-angular#389]
Thank you for adding page transitions to the router.

Could you also add platform specific page transitions?
{N}'s NavigationEntry have three transition parameters:
https://docs.nativescript.org/api-reference/interfaces/_ui_frame_.navigationentry.html#transition
* transition
* transitionAndroid
* transitionIOS

In the current implementation `nativescript-angular` only supports `transition`, so if we want to set another transition for `iOS` than we want for `Android` we can't do that.

**Comment by NickIliev** [comment]
Hello @m-abs ,

You can use Angular-2 directives (like *ngIf, ngSwitch or custom ones) to create your own platform-specific controls.
e.g. with custom directive

 my-page.component.ts

```
import {Component, Directive, ViewContainerRef, TemplateRef, Inject} from '@angular/core';
import {Device, platformNames} from "platform";
import {DEVICE} from "nativescript-angular/platform-providers";

@Directive({ selector: "[ifAndroid]" })
export class IfAndroidDirective {
    constructor( @Inject(DEVICE) device: Device, container: ViewContainerRef, templateRef: TemplateRef<Object>) {
        if (device.os === platformNames.android) {
            container.createEmbeddedView(templateRef);
        }
    }
}

@Directive({ selector: "[ifIos]" })
export class IfIosDirective {
    constructor( @Inject(DEVICE) device: Device, container: ViewContainerRef, templateRef: TemplateRef<Object>) {
        if (device.os === platformNames.ios) {
            container.createEmbeddedView(templateRef);
        }
    }
}

@Component({
    selector: 'create-custom-directive',
    styleUrls:["custom-directive/create-custom-directive/create-custom-directive.component.css"],
    directives: [IfIosDirective, IfAndroidDirective],
    templateUrl: "custom-directive/create-custom-directive/create-custom-directive.component.html",
})

export class CreateCustomDirectiveExampleComponent{

}
```
my-page.component.html
```
<Button *ifAndroid [nsRouterLink]="yourLink" pageTransition="curl" ></Button >
<Button *ifIos [nsRouterLink]="yourLink" pageTransition="explode" ></Button >
```

[Another example](https://github.com/NativeScript/nativescript-angular/issues/350#issuecomment-234512171) with the usage of *ngIf can also be applicable for your case (with a little modification to set the specific page transition).

**Comment by m-abs** [comment]
Hi @NickIliev 

Thank you for your suggestion.

Unfortunately it only covers using the `[nsRouterLink]`-directive for navigating. It doesn't cover using the `RouterExtensions`-class directly.

**Comment by vakrilov** [comment]
In code you can do:
```
import {isAndroid, isIOS} from "platform";
```
And pass different transitions based on the `isAndroid` and `isIOS` variables.

**Comment by m-abs** [comment]
That's a good idea, thank you.
