### ISSUE TITLE
[Feature] Provide a way to replace the default 'Page' with a custom instance

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-angular#394]
Hi,

It would be great if there is a way to change the way nativescript-angular's bootstrap creates the `Page` instances used though the application life circle. I looked though the code and noticed there is a [provider](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/platform-providers.ts#L11) (defaultPageProvider) for the `Page` elements (not exactly sure how it is utilized as removing it in my fork did not break any navigation) and couple of places where the `new Page` is being created (for example [here](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/application.ts#L126) and [here](https://github.com/NativeScript/nativescript-angular/blob/9785e95cd04f9816f1e8e09cf41ef750cbe0d85e/nativescript-angular/router/page-router-outlet.ts#L182))

Having the possibility of placing our own class which inherits the `Page` class in an Angular 2 {N} application will be very useful and as it is already possible in vanilla {N} I think it will make migrating to Angular even easier and better.

**Comment by vakrilov** [comment]
Some thoughts on that: 

The `Page` provider gives you access to the current page instance that is hosting the component and there is no way to replace it. 

Maybe the way to go is to use `PageFactoryProvider`, that you can replace with custom factory for pages in your app.

**Comment by VladimirAmiorkov** [comment]
Another way of achieving this behavior would be (not sure if possible probably not :)) to use the same approach like the [ActionBar](https://docs.nativescript.org/angular/ui/action-bar) in Angular 2, by simply declaring a `<Page>` in the Component itself. This way we may have different HTML declared Page instances rather than having nativescript-angular create them for us.

**Comment by janteloo** [comment]
Hi guys, any progress on this?, has someone found a workaround for android?.
