### ISSUE TITLE
Error: Failed to find module nativescript-angular/application 

### ISSUE THREAD

**Issue by ssaatya** [NativeScript/nativescript-angular#398]
I'm unable to start my app after switching to nativescript-angular unable to create application com.tns.NativeScriptApplication

**Comment by vakrilov** [comment]
Can you please verify that you have all the necessary dependencies in your `package.json`.
You can create an `nativescript-angular` hello project using the CLI (`$tns create ngProgect --ng`) and copy the dependencies from there.

**Comment by ssaatya** [comment]
I fixed it with by rebuilding the project and some cleaning
