### ISSUE TITLE
README is broken cannot build sample

### ISSUE THREAD

**Issue by vekexasia** [NativeScript/nativescript-angular#399]
I followed the readme but when arriving at tns run android i get:

```
npm WARN package.json tns-template-hello-world@1.1.0 license should be a valid SPDX license expression
Executing before-prepare hook from /home/andrea/tmp/nativescript-angular/ng-sample/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.8.10
app/app.ts(49,38): error TS2307: Cannot find module './examples/animation/animation-ngclass-test'.
```

**Comment by vakrilov** [comment]
I couldn't reproduce the issue.
The file [exists](https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/app/examples/animation/animation-ngClass-test.ts). 

One thing I noticed that the casing of the import is different : ng**C**lass. However, it doesn't cause the error on my end.

Could you please verify that `animation-ngclass-test.ts` file is there and if it is - can you try changing the casing of the import statement to see if this is actually the problem.

**Comment by vekexasia** [comment]
@vakrilov renaming works. :+1:
