### ISSUE TITLE
Navigate with ClearHistory  error after making swipe in the second page

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#400]
In case you use  `RouterExtensions` to navigate with `clearHistory` and make swipe from left to right in the second page, after return to the main page, only white screen will be shown. I am attaching sample project where this issue has been reproduced - [https://github.com/tsonevn/NGNavClearHistory.git](https://github.com/tsonevn/NGNavClearHistory.git) . 

Possible workaround has been given in [StackOverflow](http://stackoverflow.com/questions/38907953/nativescript-angular-2-disable-swipe-back-on-ios/38915927?noredirect=1#comment65223650_38915927).

nativescript-angular: 0.3.0
tns-core-modules:2.2.0

**Comment by artonio** [comment]
Is there any new on this?

**Comment by hdeshev** [comment]
Looks like a duplicate of NativeScript/NativeScript#2836. The fix will go live with tns-core-modules@2.4.0.
