### ISSUE TITLE
App crash when calling closeCallback() (ModalDialogParams), Android API 17

### ISSUE THREAD

**Issue by imkrish** [NativeScript/nativescript-angular#403]
import { ModalDialogParams } from 'nativescript-angular/modal-dialog'

constructor(
       private params: ModalDialogParams
) {}
    
this.params.closeCallback()  <== 

my app crash, when this function is called, only on android api 17, 
the later versions are working fine

this is log from the emulator when this.params.closeCallback() is called, my app close suddenly

F//system/bin/app_process( 2751): stack corruption detected: aborted
I/ActivityManager( 1202): Process org.nativescript.ABMTimesheets (pid 2751) has died.
W/ActivityManager( 1202): Force removing ActivityRecord{b33e56c0 u0 org.nativescript.ABMTimesheets/com.tns.NativeScriptActivity}: app died, no saved state
I/WindowState( 1202): WIN DEATH: Window{b3584390 u0 org.nativescript.ABMTimesheets/com.tns.NativeScriptActivity}
I/WindowState( 1202): WIN DEATH: Window{b35993b0 u0 org.nativescript.ABMTimesheets/com.tns.NativeScriptActivity}
D/Zygote  (  787): Process 2751 terminated by signal (6)
E/SurfaceFlinger(  786): ro.sf.lcd_density must be defined as a build property
W/EGL_emulation( 1327): eglSurfaceAttrib not implemented
W/InputMethodManagerService( 1202): Got RemoteException sending setActive(false) notification to pid 2751 uid 10047

Could you help me please?

**Comment by dtopuzov** [comment]
Where you test this? {N} core framework have some known issues with Modal dialog on x86 emulators.
Can you please try on arm emulator or arm physical device?

**Comment by imkrish** [comment]
Got it, I've tried on arm emulator and now it's working just fine.
Thanks so much, you save my days. 👍
