### ISSUE TITLE
Inconsistent ngAfterViewInit Behaviour

### ISSUE THREAD

**Issue by shripalsoni04** [NativeScript/nativescript-angular#406]
I am getting inconsistent behaviour of `ngAfterViewInit` hook in terms of view element's dimension across Android/iOS and in scenarios where the component is loaded as route component.

You can find the sample application describing the issue at https://github.com/shripalsoni04/NS-AfterViewInit-Issue.
### Issue Description:

When we load `Page2` component as default route, we will get all of these mentioned in below code in ngAfterViewInit.

`page2.component.ts`

```
@ViewChild('txt') txtEle: ElementRef;
ngAfterViewInit(){
       // Page2 as default route.
        console.log('page measured height ', this.page.getMeasuredHeight()); // has proper height value
        console.log('txtEle android ', this.txtEle.nativeElement.android); // has native android element
        console.log('txtEle ios ', this.txtEle.nativeElement.ios); // has native ios element
  }
```

But when we load `Page2` component as some route, that means when you navigate to `Page2` from other route, page height is coming 0 and `android` instance is undefined. But we will get `ios` instance.

`page2.component.ts`

```
@ViewChild('txt') txtEle: ElementRef;
ngAfterViewInit(){
       // Page2 loaded from another route.
        console.log('page measured height ', this.page.getMeasuredHeight()); // height: 0
        console.log('txtEle android ', this.txtEle.nativeElement.android); // android undefined on Android phone
        console.log('txtEle ios ', this.txtEle.nativeElement.ios); // has native ios element on iPhone
  }
```

If we put the code in `setTimeout` with 0 timeout, it will work as expected in Android, but for iOS the page height will still be 0. To make it work in iOS, we need to add timeout of 1ms, which is strange and a hacky solution.

`page2.component.ts`

```
@ViewChild('txt') txtEle: ElementRef;
ngAfterViewInit(){
        setTimeout(()=>{
            console.log('page measured height ', this.page.getMeasuredHeight()); // page height is coming
            console.log('txtEle android ', this.txtEle.nativeElement.android); // has native android element on Android Phone
            console.log('txtEle ios ', this.txtEle.nativeElement.ios); // has native ios element on iPhone.
        }, 1); // Note this weird 1ms timeout.
    }
```

So my question is, can we have a consistent behaviour of `ngAfterViewInit` hook across Android/iOS and irrespective of whether the component is loaded as default route or not, so that when it is executed we are sure that the view is actually loaded and ready.

**Comment by kazemihabib** [comment]
I had exactly the same problem (android undefined after route) I read in one of issues that nativescript not guarantee the android property in ngAfterViewInit() event.

I fixed this problem by using (loaded) event;

**Comment by shripalsoni04** [comment]
I tried to use `(loaded)` event. But that also gives some inconsistent behaviour as mentioned below in code.

`page2.component.html`
```
<StackLayout (loaded)="onLoad($event)">
    <Label #txt text="Page 2"></Label>
</StackLayout>
```

`page2.component.ts`
```
...
onLoad(args){
        console.log('after load stacklayout height is ', args.object.getMeasuredHeight()); // 0 on android. works for ios
        console.log('after load page measured height ', this.page.getMeasuredHeight()); // 0 on android. works for ios
        console.log('after load txtEle android ', this.txtEle.nativeElement.android); // has native android element
        console.log('after load txtEle ios ', this.txtEle.nativeElement.ios); // has native ios element
}
...
```

I checked that, for both Android and iOS, `ngAfterViewInit` is getting called before `loaded` event handler is executed, which I think is wrong.

For iOS, we are getting height in `loaded` handler, but for Android its still 0.

I have updated the code with `loaded` event at https://github.com/shripalsoni04/NS-AfterViewInit-Issue.

**Comment by kazemihabib** [comment]
any update on this?

**Comment by ErikGrijzen** [comment]
Having the same issue. The measured width and height are always 0 in the (loaded) event.

Any updates on this?

**Comment by borislemke** [comment]
I'm having the same issue on Android. I want to set the border radius of a `Button` programmatically  by dividing it's height by 2. But the height of the `Button` element is 0 inside the `(loaded)` hook.

**Comment by sgotliv** [comment]
I have the same problem. The workaround that has been proposed on that thread saved me a lot of time. Thanks guys.

**Comment by Acanguven** [comment]
Another example for this problem, animation not working.

```
ngAfterViewInit():void {
        let el = <View>this.upperBody.nativeElement;
        el.animate({
            opacity: 0,
            duration: 3000
        });
    }
```

Animations works

```
ngAfterViewInit():void {
        setTimeout(() =>{
            let el = <View>this.upperBody.nativeElement;
            el.animate({
                opacity: 0,
                duration: 3000
            });
        });
    }
```

**Comment by NickIliev** [comment]
@Acanguven as suggested use the `loaded` event for the NativeScript element to resolve the issue.
