### ISSUE TITLE
Not possible to control visibility of Action bar when tab-view is used

### ISSUE THREAD

**Issue by asaph26** [NativeScript/nativescript-angular#409]
**Issue**
When a tab-view is being used, it is currently not possible to control the visibility of the action-bar as all possible(documented) options to control the visibility is through the Page. And a tab-view doesn't seem to play along with a page.

**What I want to achieve:** 
The ability to hide the Action bar when the user scrolls down the page inside a tab view. A good example for this is the youtube app.

**Comment by tsonevn** [comment]
Hi @asaph26,

I reviewed your scenario, however I was unable to reproduce such an issue. I am attaching a link to the repo, where I uploaded a  sample project. Could you review my code and to verify, whether you still have the same issue. 

[https://github.com/tsonevn/NGHideActionBar.git](https://github.com/tsonevn/NGHideActionBar.git)

If you still expire the same problem you could send me sample project which could be debugged locally.

I hope this helps

**Comment by asaph26** [comment]
Hi @tsonevn 

Thanks for the quick reply. This helps a lot. I didn't try it this way. I was more focussed on getting it to work with TS. 

Are there any plans to make a page and a tab-view play well together? Is it possible to include routing in a nativescript ng app while also using a tab-view?

I am closing the issue. Thanks again for the quick reply.

**Comment by tsonevn** [comment]
Hi @asaph26 ,
You could use `page-router-outlet` to navigate between the pages. You could review [this ](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#router-outlet) article from the documentation. I am also attaching sample [project](https://github.com/tsonevn/NGNavigationRtConf/tree/master/app), where has been demonstrated how to use navigation in your NativeScirpt Angular2 project .
