### ISSUE TITLE
Using Http and .json() - unexpected result. 

### ISSUE THREAD

**Issue by matt4446** [NativeScript/nativescript-angular#41]
I've taken a look at the previous issue [taking me to here](https://github.com/eesdil/test_mobile/blob/master/app/access/backend.service.ts)
, but seems unrelated. 

Im expecting an Array from .json() but I cant iterate over it, or get the length.

Testing in Android... 
[My current code](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/regionsPage/regionsPage.ts#L85-L112)

The call is correct. 
.Text() has the expected outcome. 
.JSON() appears to work - but i cant get any data from it. 
Expected: Array<IProvider> (well Array<any>) 

Its working correctly in a ionic2 application [link](https://github.com/matt4446/WhatsMyScore2-Ionic2/blob/master/app/pages/RegionsPage/regionsPage.ts#L46-L62). 

Here is the Logging for that view:
![angular-http-json](https://cloud.githubusercontent.com/assets/1550939/12664211/cc1bdfb0-c625-11e5-9bfb-d1f24946f2bc.png)

I've included your json passed log line. Any thoughts? 

best regards, 
Matt

**Comment by hdeshev** [comment]
Hi @matt4446 

That turned out to be caused by a bug in our `XMLHttpRequest` implementation. I [fixed](https://github.com/NativeScript/NativeScript/pull/1467) it, and published a small [sample repo](https://github.com/NativeScript/sample-ng-http) that contains both a web and a mobile project that uses the `Http` service to read JSON data.

You could test it in your app by changing your `tns-core-modules` dependency to `1.6.0-angular-2`.

**Comment by matt4446** [comment]
Perfect.  
Thanks.

**Comment by matt4446** [comment]
@hdeshev I'm still having trouble with this (android). Shouldn't this now be part of 1.6?

package.json
```
"tns-core-modules": "^1.6.0"
```

I've tried switching to 1.6.0-angular-2 on my main project, but the response still does not deserialize into an array there either. 

[Pretty much the same code again](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/regionsPage/regionsPage.ts#L84-L94) 
```
JS: =Debug===============
JS: 2016-02-17T23:47:33.734Z: [{"Id":1,"Name":"BUCS","Logo":"content/logos/bucs-logo.jpg","CompetitionCount":2},{"Id":2,"Name":"SUTL","Logo":"content/logos/sutl.jpg","CompetitionCount":8},{"Id":1008,"Name":"South East Region","Logo":null,"CompetitionCount":4}]
JS: ======================
JS: =Debug===============
JS: 2016-02-17T23:47:33.739Z: items available:undefined
JS: ======================
```

items.forEach fails as well.

**Comment by hdeshev** [comment]
@matt4446 My code [here](https://github.com/NativeScript/sample-ng-http/blob/master/mobile/app/main-page.ts#L32-L39) looks almost the same, and it works. The only difference is that I just tried it with tns-core-modules@1.6.0. Could you try upgrading to that version? I also upgraded the project to the latest angular renderer and Angular beta-6.

**Comment by matt4446** [comment]
thanks @hdeshev 
I'm preparing for a competition this evening from Friday -> Sunday evening after work so may not have time to check till Monday with a day off (wiil try this evening). 

So change the package.json? 
[your demos:](https://github.com/NativeScript/sample-ng-http/blob/master/mobile/package.json#L30) 

[my package file:](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/package.json#L9)

Am i missing something simple ? 
npm install has been run a number of times against the different versions.

I made the upgrade to 1.6 yesterday and now have several other things working like the Arrray.create on the animation. Some other things have chagned like the border element disapearing on the view ... 
but im focusing on this at the moment.

**Comment by matt4446** [comment]
cmd line... 
```
h:\WhatsMyScore2\WhatsMyScoreNativeScript>npm install tns-core-modules@1.6.0
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
tns-core-modules@1.6.0 node_modules\tns-core-modules
└── tns-core-modules-widgets@1.6.1

h:\WhatsMyScore2\WhatsMyScoreNativeScript>

h:\WhatsMyScore2\WhatsMyScoreNativeScript>tns run android
```

```
JS: =Debug===============
JS: 2016-02-19T09:55:41.326Z: Region-page ngAfterViewInit
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:41.327Z: Load :https://breakouttrampoliningwebservices.azurewebsites.net/Api/Providers/List/Enabled
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:41.530Z: I Should have navigated from start -> regions
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:41.967Z: response:
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:41.970Z: [{"Id":1,"Name":"BUCS","Logo":"content/logos/bucs-logo.jpg","CompetitionCount":3},{"Id":2,"Name":"SUTL","Logo":"content/logos/sutl.jpg","CompetitionCount":8},{"Id":1008,"Name":"South East Region","Logo":null,"CompetitionCount":4}]
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:41.999Z: items loaded - status:200
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:42.001Z: [{"Id":1,"Name":"BUCS","Logo":"content/logos/bucs-logo.jpg","CompetitionCount":3},{"Id":2,"Name":"SUTL","Logo":"content/logos/sutl.jpg","CompetitionCount":8},{"Id":1008,"Name":"South East Region","Logo":null,"CompetitionCount":4}]
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:42.003Z: json parsed: [{"Id":1,"Name":"BUCS","Logo":"content/logos/bucs-logo.jpg","CompetitionCount":3},{"Id":2,"Name":"SUTL","Logo":"content/logos/sutl.jpg","CompetitionCount":8},{"Id":1008,"Name":"South East Region","Logo":null,"CompetitionCount":4}]
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:42.004Z: Take a peak at json object ...
JS: ======================
JS: Property: constructor
JS: Property: <init>
JS: Property: buf
JS: Property: count
JS: Property: close
JS: Property: reset
JS: Property: size
JS: Property: toByteArray
JS: Property: toString
JS: Property: write
JS: Property: writeTo
JS: Property: flush
JS: Property: clone
JS: Property: equals
JS: Property: finalize
JS: Property: getClass
JS: Property: hashCode
JS: Property: notify
JS: Property: notifyAll
JS: Property: wait
JS: =Debug===============
JS: 2016-02-19T09:55:42.010Z: test property count: 230
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:42.011Z: test property size:function () { [native code] }
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:42.011Z: test property size:230
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:42.012Z: Try again at the array length:
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:42.013Z: length:undefined
JS: ======================
JS: =Debug===============
JS: 2016-02-19T09:55:42.017Z: items available:undefined
JS: ======================
```
