### ISSUE TITLE
How to stop setInterval when page was closing

### ISSUE THREAD

**Issue by tomylee001001** [NativeScript/nativescript-angular#412]
Hi,

I am using setInterval to track the position the video in my player page but when i go to another page my setInterval functions continue to work and if i enter the page again this time there will be two setInterval functions working simultaneously. where can i stop them before user leave the page.
Thanks.

**Comment by kazemihabib** [comment]
you can use clearInterval 
http://stackoverflow.com/documentation/proposed/changes/77807
you can use this clearInterval in (unloaded) event.
Like this 
https://github.com/kazemihabib/nativescript-vlc-player/blob/master/src/app/pages/player/player.component.ts#L127-L133

https://github.com/kazemihabib/nativescript-vlc-player/blob/master/src/app/pages/player/player.html#L1
