### ISSUE TITLE
Unable to start activity error after Updating to the "next"

### ISSUE THREAD

**Issue by tomylee001001** [NativeScript/nativescript-angular#413]
Hi,
After successfully updating to the "next" version of tns-core-modules and nativescript-angular my app was working good but as of yesterday i started to get the following error on my app start.But if i remove platform and add again for the first time of running my app there is no error but after that i get the error again until i remove and add the platform again.

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.platformtest/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'getResources' of undefined
File: "/data/data/org.nativescript.platformtest/files/app/tns_modules/ui/action-bar/action-bar.js, line: 105, column: 56

StackTrace: 
    Frame: function:'ActionBar', file:'/data/data/org.nativescript.platformtest/files/app/tns_modules/ui/action-bar/action-bar.js', line: 105, column: 57
    Frame: function:'Page', file:'/data/data/org.nativescript.platformtest/files/app/tns_modules/ui/page/page-common.js', line: 36, column: 26
    Frame: function:'Page', file:'/data/data/org.nativescript.platformtest/files/app/tns_modules/ui/page/page.js', line: 75, column: 16
    Frame: function:'navEntry.create', file:'/data/data/org.nativescript.platformtest/files/app/tns_modules/nativescript-angular/application.js', line: 99, column: 24
    Frame: function:'resolvePageFromEntry', file

**Comment by vakrilov** [comment]
It is probably a problem with the [NativeScript CLI](https://github.com/NativeScript/nativescript-cli) please reopen the issue there is it is still relevant.
