### ISSUE TITLE
CAGradientLayer not working

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/nativescript-angular#414]
_From @bdauria on August 23, 2016 16:59_

I'm trying to fill a GridLayout with a gradient background but I can't make it work on ios. 
Here's the code I'm using:

session.component.html:
```
  <GridLayout
      #gradientBackground
      width="100%"
      height="100%"></GridLayout>
```

session.component.ts
```
  ngOnInit() {
    let gradientBackgroundLayout = <View>this.gradientBackground.nativeElement;
    setBackgroundGradient({
      view: gradientBackgroundLayout,
      colorCodes: ['#7319b1', '#13b3f0']
    });
  }
```

background-processor.ts:
```
export function setBackgroundGradient(args: { view: View, colorCodes: string[] }): void {
  let colors = NSMutableArray.alloc().initWithCapacity(2);
  args.colorCodes.forEach(function(c) {
    let color = new Color(c);
    colors.addObject(interop.types.id(color.ios.CGColor));
  });
  let gradientLayer = CAGradientLayer.layer();
  gradientLayer.colors = colors;
  gradientLayer.frame = args.view.ios.bounds;
  args.view.ios.layer.insertSublayerAtIndex(gradientLayer,0);
}
```

Trying to change the background color instead of applying the CAGradient layer works perfectly...

What am I missing here? 
Thanks.

_Copied from original issue: NativeScript/ios-runtime#633_

**Comment by vakrilov** [comment]
@bdauria The problem here is that the `ngOnInit` hook is executed before the layout pass of the view. So `args.view.ios.bounds` is a zero-width/height rectangle.

One thing you can do is to set dimensions of the layer that equal those of the screen:
```
import { screen } from "platform";

export function setBackgroundGradient(args: { view: View, colorCodes: string[] }): void {
    //...
    gradientLayer.frame = CGRectMake(0, 0, screen.mainScreen.widthDIPs, screen.mainScreen.heightDIPs);
    //...
}
```

**Comment by bdauria** [comment]
@vakrilov 
Thanks for your answer, that solved my problem. I guess we can close this issue now.
