### ISSUE TITLE
[Android] Routing stuck at blank screen after last back() call

### ISSUE THREAD

**Issue by corne-de-bruin** [NativeScript/nativescript-angular#417]
I've implemented a flow in our app where we show a blocking screen under certain circumstances. When the block is removed we call the back function on RouterExtensions, before we make the call we ask if it's possible to go back. If we can't go back we route the user to the first page of the app.

If the block screen is shown when the user was on the very first screen, he will get stuck on a blank page after we removed the block screen by calling the back function, even if we perform a specific route the user still gets stuck at the blank page.

I've created a small example application to demonstrate our workflow and the issue we encounter.
https://github.com/corne-de-bruin/Nativescript-angular-routing-issue-example

**Comment by vakrilov** [comment]
Hey @corne-de-bruin 
Thanks for the project - I managed to run it and reproduce the problem.
One thing I noticed is that you were subscribing to the service multiple times. So in the destroyed instances of block screen we causing navigations in some cases. 

I have added an `unsubscribe()` calls in [this PR](https://github.com/corne-de-bruin/Nativescript-angular-routing-issue-example/pull/1) and the app started work (at least I didn't manage to reproduce the original problem).

One other useful thing when debugging is [subscribing to the router events](https://github.com/vakrilov/Nativescript-angular-routing-issue-example/blob/master/app/app.component.ts#L23-L25). Which can help you get a better idea of what navigations are performed inside the app.

I hope that help you move on with the app.

**Comment by corne-de-bruin** [comment]
Hey @vakrilov 

Thanks for helping me out, indeed i totally forgot to call unsubscribe().
But still this didn't solve the problem for me.

I've merged you commit and that showed me the following issue:
Every time the app is closed by pressing the back button the ngOnInit is also fired when you resume the app but the ngOnDestroy is never called. This causes multiple resumeEvent handlers to be added.

If you pull the example app again you can see this behaviour also if you follow the flow below:
Open the app
Suspend the app
Open the app again
Press the back button
Resume the app

Now you will see that ngOnInit is never called and that the ngOnInit and the resumeEvent is called twice.

**Comment by dennis-montana** [comment]
I also have this issue in my app on Android.
When I click the physical back button, my components ngOnDestroy isn't called, when I reopen the app the ngOnInit is called again. This is causing resumeEvents being added again every time I reopen the app while the old resumeEvents are also still being fired.

**Comment by corne-de-bruin** [comment]
The conclustion of this issue is the same as #923 and as of now duplicated
