### ISSUE TITLE
ActionBar - usage of `<android>` and `<ios>` platform scoping does not work

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#418]
For example, I expected this to work but it did not:
```
<ActionBar title="App title">
  <!-- Android -->
  <android>
    <StackLayout>
      <Label text="Hello Android"></Label>
     </StackLayout>
  </android>

  <!-- iOS -->
  <ios>
    <StackLayout>
      <Label text="Hello iOS"></Label>
     </StackLayout>
  </ios>
</ActionBar>
```

On both platforms, nothing is rendered.
Using `next` tag.

**Comment by vakrilov** [comment]
Duplicate of #350 
Summary: Indeed `<andoird>`/`<ios>` does not work inside ActionBar. You can [define isPlatform directives](https://gist.github.com/vakrilov/522dbd30085142c515a5359658f06e54) instead.

The directive approach is preferable even in scenarios that do not involve ActionBar as directives don't add an additional "placeholder" element in the NativeScript UI tree.

**Comment by MContagious** [comment]
vakrilov the following code is not rendering the icons. platform if directives are not working for this case.

```
<ActionBar title="vCard">
   <NavigationButton icon="res://ic_menu" *ifAndroid text="Menu"></NavigationButton>
   <ActionItem icon="res://ic_menu" ios.position="left" *ifIso text="Menu"></ActionItem>
</ActionBar>
```

**Comment by vakrilov** [comment]
Hey @MContagious, I think you have a typo in the code: `*ifIso` should be `*ifIos`.

**Comment by MContagious** [comment]
what about the android ?

**Comment by vakrilov** [comment]
Can you please make sure you have added the directives in you `ngModule` definition.
