### ISSUE TITLE
Android dialogs: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#427]
I can't open dialogs on Android with a nng app, I get this everytime:

> JS: Error: Uncaught (in promise): Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
> JS:     android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:154)
> JS:     android.app.AlertDialog$Builder.<init>(AlertDialog.java:379)
> JS:     com.tns.Runtime.callJSMethodNative(Native Method)

I saw this reported here: https://github.com/NativeScript/NativeScript/pull/1632  but it was closed but I'm still seeing this.
Any thoughts on how to resolve?

**Comment by NathanWalker** [comment]
I should mention this happens on GenyMotion emulator running Nexus 5 - 5.1.0 - API 22 - 1080x1920.
Not sure if related to emulator environment but very stumped by this.

**Comment by NathanWalker** [comment]
Chalking this up to strange emulator issue. Nexus 6P virtual device works fine.

**Comment by Sharique-Hasan** [comment]
This is happening on real device too.

**Comment by Martin652** [comment]
It seems your context object is null. You may need to check before you try to attach  or show your dialog.

**Comment by IAMtheIAM** [comment]
Sometimes I need to stop and restart the emulator to fix it, or rebuild the app entirely (incremental fail)

**Comment by itsmerockingagain** [comment]
I am also facing same issue on emulator, any fix available for this?

**Comment by chandra1234456** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.AlertDialog android.app.AlertDialog$Builder.create()' on a null object reference
