### ISSUE TITLE
Using the 'page-router-outlet' causes deprecated error. message

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-angular#428]
[rc5-test.zip](https://github.com/NativeScript/nativescript-angular/files/449556/rc5-test.zip)
# Issue

With Angular **RC5** and nativescript-angular **0.4.0** the following messaged is written in the terminal:

> JS: ComponentResolver is deprecated for dynamic compilation. Use ComponentFactoryResolver together with @NgModule/@Component.entryComponents or ANALYZE_FOR_ENTRY_COMPONENTS provider instead. For runtime compile only, you can also use Compiler.compileComponentSync/Async.

# Way to reproduce

Created an app that has routes and uses the `<page-router-outlet></page-router-outlet>` in its first `Component`. You can find attached an example to the report.

# Research

The issue seams to be caused by the page-router-outlet directive and its [detachedLoaderFactory](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/page-router-outlet.ts#L67) private field of type `ComponentFactory`.

**Comment by hdeshev** [comment]
Fixed in 1.0.0

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
