### ISSUE TITLE
Custom modal dialogs partially broken in 0.4.0

### ISSUE THREAD

**Issue by rrjohnson85** [NativeScript/nativescript-angular#430]
It seems that the custom modal dialogs are partially broken in nativescript-angular 0.4.0 and Angular2 RC5.  I say partially broken because the custom modal appears to work fine when loaded in the first child NgModule, but in other modules I receive the following error from page.ios.ts ([here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/page/page.ios.ts#L385)):

`Parent page is not part of the window hierarchy. Close the current modal page before showing another one!`

I've created a sample based on the Ng2-RC5 branch of sample-groceries, and my sample can be found [here](https://github.com/rrjohnson85/ns-modal-issue).  I'm currently showing the modal in a `setTimeout` after 5 seconds to quickly show the problem and not bother with modifying the sample's UI.  In the login module, everything works as expected; however, I see the error in groceries module.  I have only tested iOS and don't know if this is a problem on Android devices.

**Comment by ignaciolarranaga** [comment]
I think the problem is related to navigation (may be it is the same you are thinking), checkout here: https://github.com/NativeScript/NativeScript/issues/2759

**Comment by rrjohnson85** [comment]
Thanks @ignaciolarranaga!  I was hoping this was fixed with the latest changes to the ModalDialogService, but I haven't had a chance to check yet.  By looking at your issue and sample, it seems this is not the case.

**Comment by ignaciolarranaga** [comment]
@rrjohnson85, check out the last comment in here #459, may be it is also your problem.

**Comment by rrjohnson85** [comment]
@ignaciolarranaga Thanks, but I don't think that is the problem since I added the ModalDialogService to providers in the root module.  I didn't try creating a [core module](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-module), but I don't think that will change anything.  

It could be that the problem is fixed by the [latest changes to the ModalDialogService](https://github.com/NativeScript/nativescript-angular/commit/5dd8306aa5b0a89520de2e176df6bf357a4fcfba#diff-7e68951b6daff4ac8dec6c680fb961ceR35), but I haven't been able to check.

**Comment by hdeshev** [comment]
> I added the ModalDialogService to providers in the root module

You should add it to every module that opens a dialog page. If you have just one provider in your root module, a `page-router-outlet` page that tries to open a new dialog will get the wrong parent page, and likely crash.

I just scheduled #460 for the current milestone so we document all that.

**Comment by rrjohnson85** [comment]
Thanks @hdeshev!  I added the ModalDialogService to each page that opens a modal - the problem seems to be resolved.  Closing this ticket.

**Comment by vakrilov** [comment]
@rrjohnson85 We have done some refactoring of the way the dialogs are shown in #489. Summary:
 - No need to use the `modal-dialog-host` directive anymore.
 - No need to provide `ModalDialogService` in your module or component. It is now exported by the `NativeScriptModule`.
 - You should inject a `ViewContainerRef` and pass it in the `options` object when calling `showModal`. This eliminates the need of adding `modal-dialog-host` in your template and makes the whole process more explicit and less error-prone. It is also the current approach in the [angular-material2 dialog](https://github.com/angular/material2/blob/0e0ff0e7aae4a4f87ad92e17bc1af14e20a3e17a/src/demo-app/dialog/dialog-demo.ts#L14-L29).
