### ISSUE TITLE
keyframe animations (css) problems using NNG

### ISSUE THREAD

**Issue by jlooper** [NativeScript/nativescript-angular#431]
I ran this by Tsvetan Raikov and we think this is an issue that needs fixing: 

In an app scaffolded as per normal in the cli (`tns create myNNGapp --ng) I am attempting to animate cards using keyframe animation:

```
@keyframes card {
    from { opacity: 0 }
    to { opacity: 1}
}
.card {
    opacity: 0;
    background-color: #DA4167;
    animation-name: card;
    animation-duration: 4s;
    animation-iteration-count: 1;
    margin: 10;
    border-radius: 5;
    color: #EBEBD3;
}
```

The keyframe animation to fade in does work, but in console, I get this error:

```
CONSOLE LOG file:///app/tns_modules/@angular/core/src/facade/lang.js:360:16: resolvePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:516:41
    resolvePromise@file:///app/tns_modules/zone.js/dist/zone-node.js:501:32
    file:///app/tns_modules/zone.js/dist/zone-node.js:549:32
    invokeTask@file:///app/tns_modules/zone.js/dist/zone-node.js:323:43
    onInvokeTask@file:///app/tns_modules/@angular/core/src/zone/ng_zone_impl.js:44:51
    invokeTask@file:///app/tns_modules/zone.js/dist/zone-node.js:322:55
    runTask@file:///app/tns_modules/zone.js/dist/zone-node.js:223:58
    drainMicroTaskQueue@file:///app/tns_modules/zone.js/dist/zone-node.js:455:43
    promiseReactionJob@[native code]
    UIApplicationMain@[native code]
    start@file:///app/tns_modules/application/application.js:233:26
    nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:144:22
    anonymous@file:///app/main.js:5:36
    evaluate@[native code]
    moduleEvaluation@[native code]
    [native code]
    promiseReactionJob@[native code]
Sep  2 11:05:55 LOOPERMAC ndduiworkshop[40158]: CONSOLE ERROR file:///app/tns_modules/zone.js/dist/zone-node.js:442:27: Unhandled Promise rejection: Animation cancelled. ; Zone: angular ; Task: Promise.then ; Value: Error: Animation cancelled. _rejectAnimationFinishedPromise@file:///app/tns_modules/ui/animation/animation-common.js:110:31
    animationFinishedCallback@file:///app/tns_modules/ui/animation/animation.js:115:57
    animationDidStopFinished@file:///app/tns_modules/ui/animation/animation.js:67:35
    UIApplicationMain@[native code]
    start@file:///app/tns_modules/application/application.js:233:26
    nativeScriptBootstrap@file:///app/tns_modules/nativescript-angular/application.js:144:22
    anonymous@file:///app/main.js:5:36
    evaluate@[native code]
    moduleEvaluation@[native code]
    [native code]
    promiseReactionJob@[native code]
Sep  2 11:05:55 LOOPERMAC ndduiworkshop[40158]: CONSOLE ERROR file:///app/tns_modules/zone.js/dist/zone-node.js:444:23: Error: Uncaught (in promise): Error: Animation cancelled.
```

Perhaps this could be fixed in the next release.

**Comment by roblav96** [comment]
@jlooper I've noticed that the syntax you're using in your example (with `to` and `from`) don't play well in nativescript.

I've only been able to get it working like so:
```css
@keyframes modalOpen {
    0% {
        opacity: 0;
        transform: scale(0, 0) rotate(15deg);
    }
    50% {
        opacity: 1;
        transform: scale(1.1, 1.1) rotate(0deg);
    }
    75% {
        transform: scale(0.9, 0.9) rotate(-5deg);
    }
    100% {
        transform: scale(1, 1) rotate(0deg);
    }
}
```

**Comment by bnussey** [comment]
I am also getting these errors in console, even if I change to percentages as @roblav96 suggests

**Comment by jlooper** [comment]
Closing, as with 2.3 keyframe animations work without issue now! 👍

**Comment by alterx** [comment]
Hey @jlooper, you sure this is fixed? 
I'm getting the same error when trying to animate views inside a tabbed view. Updated to 2.3 but it's still reproducible.

@bnussey did updating work for you?

**Comment by alterx** [comment]
Also, just installed the latest version of the groceries sample and the error is still there when you log out.

**Comment by bnussey** [comment]
I'm still getting errors on some of my animations but was thinking that was my own issue @alterx

**Comment by alterx** [comment]
Yeah @bnussey , me too but I downloaded the sample groceries application and it has the errors (even though it's been updated to 2.3 and angular 2 final)

**Comment by Arthurisme** [comment]
Yes, I download the latest groceries with angular 2 final and nativescript 2.3, the problem still there.

**Comment by jlooper** [comment]
I think it might depend on the animation. A very simple one was working for me with 2.3 (the one listed above) but the animations in Groceries are more complex, and might error. I think they run, but they would possibly error. So I guess we should track down what works and what doesn't. One thing to remember is the Angular way of animation should work as well.

**Comment by devna13** [comment]
same error

**Comment by 9thwall** [comment]
I'm getting similar errors on navigation animations and also CSS animations. Using 2.3

```
Unhandled Promise rejection: Animation cancelled. ; Zone: <root> ; Task: Promise.then ; Value: Error: Animation cancelled. Error: Animation cancelled.
JS:     at Animation._rejectAnimationFinishedPromise (/data/data/org.nativescript.app/files/app/tns_modules/ui/animation/animation-common.js:110:22)
JS:     at Animation._onAndroidAnimationCancel (/data/data/org.nativescript.app/files/app/tns_modules/ui/animation/animation.js:113:14)
JS:     at Animation._animatorListener.android.animation.Animator.AnimatorListener.onAnimationCancel (/data/data/org.nativescript.app/files/app/tns_modules/ui/animation/animation.js:53:22)
JS:     at Animation.cancel (/data/data/org.nativescript.app/files/app/tns_modules/ui/animation/animation.js:92:27)
JS:     at KeyframeAnimation.cancel (/data/data/org.nativescript.app/files/app/tns_modules/ui/animation/keyframe-animation.js:105:31)
JS:     at RadListView.View._unregisterAllAnimations (/data/data/org.nativescript.app/files/app/tns_modules/ui/core/view-common.js:1114:27)
JS:     at Style._resetCssValues (/data/data/org.nativescript.app/files/app/tns_modules/ui/styling/style.js:925:20)
JS:     at resetCssValuesFunc (/data/data/org.nativescript.app/files/app/tns_modules/ui/page/page-common.js:291:24)
JS:     at localCallback (/data/data/org.nativescript.app/files/app/tns_modules/ui/core/view-common.js:58:29)
JS:     at GridLayout.LayoutBase._eachChildView (/data/data/org.nativescript.app/files/app/tns_modules/ui/layouts/layout-base-common.js:146:22)
JS: Error: Uncaught (in promise): Error: Animation cancelled.
```

**Comment by odubuc** [comment]
I'm having the same issue in my app using this simple animation (on page navigation):
```
.progress {
    animation-name: progressKeyframe;
    animation-duration: 1s;
    animation-iteration-count: infinite;
    animation-timing-function: linear;
}
@keyframes progressKeyframe {
    0% { transform: translate(0, 0); }
    100%   { transform: translate(30, 0); }
}
```

**Comment by odubuc** [comment]
Just to add more info, I can also reproduce using ngClass instead of page natigation. simply removing the class that triggers the animation :

```
<StackLayout [ngClass]="{'progress': isAnimated}"></StackLayout>
this.isAnimated = true;
this.isAnimated = false;
```

**Comment by devna13** [comment]
Any updates on this issue!?

**Comment by NathanWalker** [comment]
Curious here as well, I'm seeing the same thing with latest `2.4.2`.

**Comment by tskweres** [comment]
confirmed I see this issue when using keyframes as well

**Comment by JuanDelgadillo** [comment]
I have the same issue over here, with tns version: 2.4.1

**Comment by SBD580** [comment]
same here (2.4.2)

**Comment by smarza** [comment]
I have the same issue with tns version: 2.5

**Comment by alexziskind1** [comment]
I'm seeing this issue on 2.5.0 and on @next (3.0.0-2017-02-09-7977)
iOS is able to gracefully ignore the error and the app continues, but on Android the app completely crashes.

Error:

```
5:51:06 PM - Compilation complete. Watching for file changes.

JS: EXCEPTION: Uncaught (in promise): Error: Animation cancelled.
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): Error: Animation cancelled.
JS:     at resolvePromise (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:416:31)
JS:     at resolvePromise (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:401:17)
JS:     at file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:449:17
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:223:37)
JS:     at Object.onInvokeTask (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/@angular/core/bundles/core.umd.js:4382:41)
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:222:42)
JS:     at Zone.runTask (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:123:47)
JS:     at drainMicroTaskQueue (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:355:35)
JS: Unhandled Promise rejection: Animation cancelled. ; Zone: angular ; Task: Promise.then ; Value: Error: Animation cancelled. Error: Animation cancelled.
JS:     at Animation._rejectAnimationFinishedPromise (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/animation/animation-common.js:110:22)
JS:     at Animation._onAndroidAnimationCancel (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/animation/animation.js:113:14)
JS:     at Object.onAnimationCancel (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/animation/animation.js:53:22)
JS:     at Animation.cancel (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/animation/animation.js:92:27)
JS:     at KeyframeAnimation.cancel (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/animation/keyframe-animation.js:105:31)
JS:     at StackLayout.View._unregisterAllAnimations (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/core/view-common.js:1325:27)
JS:     at StackLayout.View.onUnloaded (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/core/view.js:88:14)
JS:     at file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/core/view-common.js:764:27
JS:     at StackLayout.LayoutBase._eachChildView (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:144:22)
JS:     at StackLayout.View._unloadEachChildView (file:///data/data/org.nativescript.rpsconfng/files/app/tns_modules/tns-core-modules/ui/core/view-common.js:762:18)
```

**Comment by smarza** [comment]
This issue continues with tns version: 2.5.1

**Comment by devna13** [comment]
@tsonevn After upgrading xcode and cocoapods, I get this new error message in iOS  

> CoreAnimation: stiffness must be greater than 0. 

xcode 8.2.2
pods 1.2.0
nativescript@2.5.1
    "tns-ios": {
      "version": "2.5.0"
    },
 "tns-core-modules": "^2.5.1"

```

CoreAnimation: stiffness must be greater than 0.
Feb 23 11:15:27 --- last message repeated 2 times ---
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:342:26: Unhandled Promise rejection: Animation cancelled. ; Zone: <root> ; Task: null ; Value: Error: Animation cancelled. _rejectAnimationFinishedPromise@file:///app/tns_modules/tns-core-modules/ui/animation/animation-common.js:110:31
	animationFinishedCallback@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:117:57
	animationDidStopFinished@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:68:35
	UIApplicationMain@[native code]
	start@file:///app/tns_modules/tns-core-modules/application/application.js:251:26
	bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:68:28
	bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:56:26
	anonymous@file:///app/main.js:35:57
	evaluate@[native code]
	moduleEvaluation@[native code]
	[native code]
	promiseReactionJob@[native code]
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): Error: Animation cancelled.
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:342:26: Unhandled Promise rejection: Animation cancelled. ; Zone: <root> ; Task: null ; Value: Error: Animation cancelled. _rejectAnimationFinishedPromise@file:///app/tns_modules/tns-core-modules/ui/animation/animation-common.js:110:31
	animationFinishedCallback@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:117:57
	animationDidStopFinished@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:68:35
	UIApplicationMain@[native code]
	start@file:///app/tns_modules/tns-core-modules/application/application.js:251:26
	bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:68:28
	bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:56:26
	anonymous@file:///app/main.js:35:57
	evaluate@[native code]
	moduleEvaluation@[native code]
	[native code]
	promiseReactionJob@[native code]
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): Error: Animation cancelled.
CoreAnimation: stiffness must be greater than 0.
```

**Comment by NathanWalker** [comment]
Sounds like your stiffness needs to be greater than 0 :-0

**Comment by jlooper** [comment]
🙀

**Comment by devna13** [comment]
Really !?

**Comment by danielKugler** [comment]
same here (3.0.1)

**Comment by tjzfg** [comment]
same issue with tns-3.0.1,any solution?

**Comment by spmamidi** [comment]
+1

**Comment by dvdbrk** [comment]
Same here, iOS only, tns 3.0.2?

**Comment by gpfiel** [comment]
+1

**Comment by morzyns** [comment]
So is there any fix for the animation? 
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:571:22: Error: Uncaught (in promise): Error: Animation cancelled.
        _rejectAnimationFinishedPromise@file:///app/tns_modules/tns-core-modules/ui/animation/animation-common.js:98:31 [<root>]
        animationFinishedCallback@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:148:57 [<root>]
        animationDidStopFinished@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:70:35 [<root>]
        UIApplicationMain@[native code] [<root>]
        start@file:///app/tns_modules/tns-core-modules/application/application.js:212:26 [<root>]
        bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:73:28 [<root>]
        bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:61:26 [<root>]
        anonymous@file:///app/main.js:6:57 [<root>]
        evaluate@[native code] [<root>]
        moduleEvaluation@[native code] [<root>]
        [native code] [<root>]

For:
  "dependencies": {
    "@angular/animations": "4.2.5",
    "@angular/common": "4.2.5",
    "@angular/compiler": "4.2.5",
    "@angular/core": "4.2.5",
    "@angular/forms": "4.2.5",
    "@angular/http": "4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/router": "4.2.5",
    "email-validator": "^1.0.7",
    "nativescript-angular": "4.2.0",
    "nativescript-telerik-ui": "3.1.1",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.3",
    "tns-core-modules": "3.2.0",
    "zone.js": "0.8.17"
  },
  "devDependencies": {
    "codelyzer": "3.2.0",
    "nativescript-dev-sass": "1.3.2",
    "nativescript-dev-typescript": "0.5.0",
    "node-sass": "4.5.3",
    "tslint": "5.7.0",
    "typescript": "2.5.2"
  }

**Comment by knusperkrone** [comment]
+1
I've been implementing a hybrid drag and drop list, with some responsive elements.
Works like a charm on Android, but sadly leads to undefined and unusable behavior on ios.

NativeScript 3.2

**Comment by sittingbool** [comment]
Still having this issue in 3.2. Cant figure out where its coming from. I caught all Promises I could find but still no change. This breaks my app because after 20 sek I have about 3k log statements.

**Comment by p-3** [comment]
+1

**Comment by jeffswitzer** [comment]
Also getting `ERROR Error: Uncaught (in promise): Error: Animation cancelled.`
This is on tns 3.3 android, angular 4.4.1. 

The code causing this looks like:
`<FlexboxLayout [ngClass]="{'some-animated-css-class' : some-var-that-toggles-true-and-false}"> ...`

```
@keyframes fadeout {
    0% {
        background-color: $color-save-button;
    }
    100% {
        background-color: $color-btn;
    }
}

.some-animated-css-class {
    background-color: $color-save-button;
    animation-name: fadeout;
    animation-duration: 2s;
    animation-fill-mode: forwards;
}
```

I get the error only when `some-var-that-toggles-true-and-false` goes from true to false which should remove the css class doing the animation. Also the css animation only takes 2 seconds, but the css class isn't removed until after like 5 seconds so it's not like I'm removing the class in the middle of the animation.

Maybe this issue need to be reopened?

**Comment by jhoopmann** [comment]
@jeffswitzer 

error appears on iOS if you're going to manipulate element properties while do some animations on them.

For example:  on layout touch  => set style translateY of element X for pulldown;
 but clicking on layout childs tap (icon f.e.) => animate some properties of element X for opening.

=> parents touch event is fired before childs tap; animation starts => but in touch you're going to manipulate manually which will stop the animation execution.

**Comment by yyankov** [comment]
Also getting that ugly error in the console:

`JS: Error: Animation cancelled.
JS:     at KeyframeAnimation._rejectAnimationFinishedPromise (file:///data/data/org.nativescript.WaterTrend/files/app/tns_modules/tns-core-modules/ui/animation/keyframe-animation.js:208:22) [angular]
...`

**Comment by shabib3** [comment]
Also here:

```
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:569:26: Unhandled Promise rejection: Animation cancelled. ; Zone: <root> ; Task: null ; Value: Error: Animation cancelled. _rejectAnimationFinishedPromise@file:///app/tns_modules/tns-core-modules/ui/animation/animation-common.js:98:31 [<root>]
```

**Comment by ManuelSch** [comment]
+1

**Comment by frapaa** [comment]
I also see this issue on 3.4.1 and 4.0.0

**Comment by vultix** [comment]
@jlooper @hdeshev - I can confirm this issue is still prevalent on 4.0.0.  Perhaps it's time to reopen?

**Comment by Socha17** [comment]
+1

**Comment by cerireyhan** [comment]
+1

**Comment by NathanWalker** [comment]
It’s due to another misusage of ‘throw’ around animation handling - I’ll submt a PR shortly.

**Comment by RoyiNamir** [comment]
@NathanWalker  Is it merely an informative error  or does it also stop further code execution ?

**Comment by NathanWalker** [comment]
It has potential to crash an app however often will just leave app in unstable state which may cause oddities later during all usage.

**Comment by cerireyhan** [comment]
@NathanWalker Can we reopen the issue to follow it?

**Comment by alterx** [comment]
It really worries me that this kind of issue (with a lot of reports. Mine, for example, dates to late 2016) just gets closed despite the fact that multiple people are reporting the same thing. 
If it were just an esthetic issue I'd understand but this has the potential to break the app during usage.

**Comment by NathanWalker** [comment]
@hdeshev Could you please reopen this issue... I have a PR coming for this.

**Comment by NathanWalker** [comment]
@alterx I can certainly understand that. Please see PR above.

**Comment by vakrilov** [comment]
Thanks to @NathanWalker for addressing that with a PR :)
It's not included in the 4.1 official release, but it will be available in `@next`

**Comment by alqabali** [comment]
Still facing that problem with nativescript 4.2.4 .
steps to reproduce the problem:
just install nativescript-ngx-slides plugin and i set some slides inside it and make it autoplay using setInterval function and when i try to make a half swipe(make a swipe and cancel it before going to next slide) i'm getting this error:

`CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:676:30: Unhandled Promise rejection: Animation cancelled. ; Zone: <root> ; Task: null ; Value: Error: Animation cancelled. _rejectAnimationFinishedPromise@file:///app/tns_modules/tns-core-modules/ui/animation/animation-common.js:100:31 [<root>]
animationFinishedCallback@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:148:57 [<root>]
animationDidStopFinished@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:70:35 [<root>]
UIApplicationMain@[native code] [<root>]
start@file:///app/tns_modules/tns-core-modules/application/application.js:272:26 [<root>]
run@file:///app/tns_modules/tns-core-modules/application/application.js:300:10 [<root>]
bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:153:26 [<root>]
bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:87:38 [<root>]`

**Comment by JillevdW** [comment]
Still reproducible by using the `animate` function, for example:
`
elem.animate({
    scale: { x: 1, y: 1 },
    opacity: 1,
    duration: 50
})
`

I believe this happens when multiple animations are overlapping; in this case it's part of an animation when a button is tapped. That tap will start the segue to a new view, and the second the slide animation to the new VC starts I get the `Animation cancelled` error.

**Comment by jbarnabe** [comment]
Like @alqabali & @JillevdW this errors still occurs (ns-angular 7.1.0).
In my case I link several animations for a "bounce" effect:

 ```
this.error.nativeElement
                        .animate({
                            translate: { x: 0, y: 2 },
                            curve: enums.AnimationCurve.linear,
                            duration: 150,
                        })
                        .then(() =>
                            errorContainer.animate({
                                translate: { x: 30, y: 2 },
                                curve: enums.AnimationCurve.linear,
                                duration: 53,
                            })
                        )
                        .then(() =>
                            errorContainer.animate({
                                translate: { x: 15, y: 2 },
                                curve: enums.AnimationCurve.linear,
                                duration: 75,
                            })
                        )
                        .then(() =>
                            errorContainer.animate({
                                translate: { x: 0, y: 2 },
                                curve: enums.AnimationCurve.linear,
                                duration: 75,
                            })
                        )
                        .then(() =>
                            errorContainer.animate({
                                translate: { x: 5, y: 2 },
                                curve: enums.AnimationCurve.linear,
                                duration: 75,
                            })
                        )
                        .then(() =>
                            errorContainer.animate({
                                translate: { x: 0, y: 2 },
                                curve: enums.AnimationCurve.linear,
                                duration: 75,
                            })
                        );
```
```
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:676:30: Unhandled Promise rejection: Animation cancelled. ; Zone: <root> ; Task: null ; Value: Error: Animation cancelled. _rejectAnimationFinishedPromise@file:///app/tns_modules/tns-core-modules/ui/animation/animation-common.js:100:31 [<root>]
animationFinishedCallback@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:148:57 [<root>]
animationDidStopFinished@file:///app/tns_modules/tns-core-modules/ui/animation/animation.js:70:35 [<root>]
UIApplicationMain@[native code] [<root>]
start@file:///app/tns_modules/tns-core-modules/application/application.js:273:26 [<root>]
run@file:///app/tns_modules/tns-core-modules/application/application.js:301:10 [<root>]
bootstrapNativeScriptApp@file:///app/tns_modules/nativescript-angular/platform-common.js:187:26 [<root>]
bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:105:38 [<root>]
bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:89:26 [<root>]
./main.ts@file:///app/bundle.js:1532:148 [<root>]
__webpack_require__@file:///app/bundle.js:76:34 [<root>]
checkDeferredModules@file:///app/bundle.js:45:42 [<root>]
file:///app/bundle.js:149:38 [<root>]
anonymous@file:///app/bundle.js:150:12 [<root>]
evaluate@[native code] [<root>]
moduleEvaluation@[native code] [<root>]
promiseReactionJob@[native code] [<root>]
require@[native code] [<root>]
anonymous@file:///app/starter.js:2:8 [<root>]
evaluate@[native code] [<root>]
moduleEvaluation@[native code] [<root>]
promiseReactionJob@[native code] [<root>]
```
Note : this errors occurs only on iOS for me.

**Comment by Nevaan** [comment]
Hi, any updates on this one?

**Comment by dudipsh** [comment]
any updates?

**Comment by cavalos0086** [comment]
Hey guys! I am also getting the same error when using `.animate`. Any new updates on this? 

As a workaround (given that the app doesn't crash with this error), I put the `animate` in a try/catch and don't put anything in the catch so no errors are shown. 
Ex:
```
try {
  elem.nativeElement.animate(getAnimation());
} catch (err) {}
```

**Comment by ChadStrat** [comment]
Any ideas on eliminating this error?

**Comment by edusperoni** [comment]
@ChadStrat this error comes from nativescript core, not angular, so you can probably find better resources there.

But one way to solve unhandled promise rejection with the animate function is to handle the rejection:

```
elem.nativeElement.animate(...).catch(); // ignore rejections
```

**Comment by lostation** [comment]
Yes indeed, same error on iOS long time ago and I've added for any view.animate calls ->  .then() .catch() ... That did the trick.

**Comment by ChadStrat** [comment]
Some context, angular/nativescript, I don't see a way to catch() the actual animation sequence.  The following does not work:
```
goToSubscribe() {
    this.router.navigate(
      ['/appname', { outlets: { outlet: ["subscribe"] } }], 
      { 
        relativeTo: this.activeRoute,
        animated: true,
        transition: { duration: 300, name: 'slideLeft' }
      }
    ).catch(()=>{});
  }
```
