### ISSUE TITLE
Http thows an error JS: EXCEPTION: TypeError: Cannot read property 'toString' of null RC5

### ISSUE THREAD

**Issue by nithinshiriya** [NativeScript/nativescript-angular#433]
I am experiencing below error while calling http get.

> thows an error JS: EXCEPTION: TypeError: Cannot read property 'toString' of null RC5

```
   httpGet(url: string): Observable<any>{        
        url = "http://servicetest.picpollapp.com/PollService.svc/rest/Test/nitheen";        
        return this._http.get(url, {headers:  this.headers})
        .map(res =>{ 
                console.log(res);
               return res;
            })
        .catch(this.handleError)        
    }
```

**Package.json**
```
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/platform-server": "2.0.0-rc.5",
    "@angular/router": "3.0.0-beta.2",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "jugaadcode-chart": "file:plugins\\jugaadcode-chart",
    "moment": "^2.14.1",
    "nativescript-angular": "^0.4.0",
    "nativescript-cardview": "^1.1.11",
    "nativescript-facebook-login": "^0.2.0",
    "nativescript-telerik-ui": "^1.3.1",
    "nativescript-unit-test-runner": "^0.3.3",
    "rxjs": "^5.0.0-beta.6",
    "tns-core-modules": "^2.2.1"
  },

```
**Full Error**

> JS: EXCEPTION: TypeError: Cannot read property 'toString' of null
> JS: STACKTRACE:
> JS: TypeError: Cannot read property 'toString' of null
> JS:     at Request.Body.text (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/@angular/http/src/body.js:44:26)
> JS:     at Request.getBody (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/@angular/http/src/static_request.js:141:29)
> JS:     at Observable._subscribe (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/@angular/http/src/backends/xhr_backend.js:113:37)
> JS:     at Observable.subscribe (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/rxjs/Observable.js:52:62)
> JS:     at Observable._subscribe (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/rxjs/Observable.js:109:28)
> JS:     at MapOperator.call (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/rxjs/operator/map.js:54:23)
> JS:     at Observable.subscribe (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/rxjs/Observable.js:52:38)
> JS:     at Observable._subscribe (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/rxjs/Observable.js:109:28)
> JS:     at CatchOperator.call (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/rxjs/operator/catch.js:29:23)
> JS:     at Observable.subscribe (/data/data/org.nativescript.PicPollANS/files/app/tns_modules/rxjs/Observable.js:52:38)
> JS: TypeError: Cannot read property 'toString' of null
> 

_**Note: It works fine with RC2**_

**Comment by NathanWalker** [comment]
Do you have a project on github where I could run this to help you more?

**Comment by nithinshiriya** [comment]
Let me create a an GitHub project.

**Comment by NathanWalker** [comment]
@nithinshiriya There were a couple version mismatch issues and primarily were missing the app transport security plist setting which was causing this warning:

> App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

Additionally your server will need to return json properly and you don't need to headers set on the frontend here.
It handles the request just fine now but due to your server's configuration, this results:
```
ErrorSyntaxError: JSON Parse error: Unexpected identifier "You"
```
You will see what I mean if you access this url directly in the browser: 
http://servicetest.picpollapp.com/PollService.svc/rest/Test/nitheen
You will notice it returns a plain string. Instead it should return an object so the json() extraction on the client will work correctly.

PR here with fixes: https://github.com/nithinshiriya/NHttpTestRC5/pull/1

Please close this issue.
