### ISSUE TITLE
col property (GridLayout) not working on ng-content

### ISSUE THREAD

**Issue by victorhurdugaci** [NativeScript/nativescript-angular#435]
1. Create a new application using `tns new ngcontent --ng`
2. Replace the content in `app.component.ts` with the code below and then run the app.
   
   ``` typescript
   import {Component} from "@angular/core";
   
   @Component({
       selector: "my-component",
       template: `
           <GridLayout columns="*,*" rows="auto">
               <Label col="0" text="col0"></Label>
               <ng-content col="1"></ng-content>
           </GridLayout> 
       `
   })
   export class MyComponent {
   }
   
   @Component({
       directives: [MyComponent],
       selector: "my-app",
       template: `
           <my-component>
               <Label text="col1"></Label>
           </my-component>
       `
   })
   export class AppComponent {
   }
   ```

Expected: the two labels (col0 and col1) are side by side
Actual: col0 and col1 are on top of each other (the `col` property for `ng-content` is ignored).

![untitled](https://cloud.githubusercontent.com/assets/5921642/18222818/26f4e674-7158-11e6-9bef-3ba97b77c318.png)

PS: if you set the `col` property on the col1 label inside `my-component` then it will be displayed correctly.

**Comment by victorhurdugaci** [comment]
Probably related: I've noticed that other properties don't work either. For example, setting the background color for the `GridLayout` in `my-component` will not include the elements under `ng-content`. They appear almost as being outside of the grid layout.

**Comment by matt4446** [comment]
This is where I would normally bash out some stack panels to contain the various ng-contents lying about and decorate those. One doesn't normally see ng-content decorated with anything other than its select property, Are there any examples out there where ng-content is used for any other purpose than transclusion? The element is replaced by the content, after which the replaced content will get the default properties (col=0; row=0); The way I see it is that it is doing everything that I would expect it to.
