### ISSUE TITLE
 error TS2307: Cannot find module 'nativescript-angular/application'

### ISSUE THREAD

**Issue by monikamathur** [NativeScript/nativescript-angular#436]
i got this error after upgrading "nativescript-angular": "0.4.0" or "nativescript-angular": "next" ,   there is no application.ts file in native script angular 
here is my package.json

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.IGM",
    "tns-android": {
      "version": "2.2.0"
    }
  },
  
  "dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/platform-server": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.7",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "nativescript-angular": "0.4.0",
    "nativescript-fresco": "^1.0.5",
    "nativescript-intl": "^0.0.2",
    "nativescript-telerik-ui-pro": "1.3.1",
    "nativescript-unit-test-runner": "^0.3.2",
    "punycode": "1.3.2",
    "querystring": "0.2.0",
    "reflect-metadata": "^0.1.5",
    "tns-core-modules": "^2.2.1",
    "url": "0.10.3"
  },
  "devDependencies": {
    "babel-traverse": "6.10.4",
    "babel-types": "6.10.2",
    "babylon": "6.8.1",
    "chai": "^3.5.0",
    "filewalker": "0.1.3",
    "karma": "^0.13.22",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^0.2.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "^2.4.5",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
}

**Comment by NathanWalker** [comment]
@monikamathur You should be using at least rc.4 or 5 at this point (especially if using `next` tag). That is likely some part of the issue.
Use these package deps: https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/package.json#L26-L43
Then:
```
rm -rf hooks lib platforms node_modules
tns emulate ios 
// or...
tns run android
```
If that fixes the issue, please close 👍

**Comment by hdeshev** [comment]
Closing since with angular 2.0.0 and nativescript-angular 1.0.0 we now use the `nativescript-angular/platform` module
