### ISSUE TITLE
Reuse an angular 1 module - support for UpgradeAdapter

### ISSUE THREAD

**Issue by fdnhkj** [NativeScript/nativescript-angular#438]
I would like to reuse an angular 1 module (mostly services) in a NativeScript - angular 2 app.

I have read about the upgrade module and its `UpgradeAdapter` service in [angular 2 docs][1].
> [...] service that can bootstrap and manage hybrid applications that support both Angular 2 and Angular 1 code.

In order to use the `UpgradeAdapter` service, its [`bootstrap`][2] function should be called.

Knowing that NativeScript also requires to call a bootstrap function [`nativeScriptBootstrap`][3], I am wondering if it exposes a way to use the `UpgradeAdapter` bootstrap instead of standard angular 2 one.

  [1]: https://angular.io/docs/ts/latest/guide/upgrade.html#!#upgrading-with-the-upgrade-adapter
  [2]: https://angular.io/docs/ts/latest/api/upgrade/index/UpgradeAdapter-class.html#!#bootstrap-anchor
  [3]: https://github.com/NativeScript/nativescript-angular/blob/v0.3.0/nativescript-angular/application.ts#L175

**Comment by cusJunDev** [comment]
+1 also interested in that issue

**Comment by hdeshev** [comment]
We never intended to support Angular 1 components, and I doubt we'll allocate resources for it in the foreseeable future.

That said, there is no problem for support for the UpgradeAdapter come from a separate library developed by the community. We'll consider PR's that make it easy for such a library to do its job.
