### ISSUE TITLE
RC6 compatibilty libraries and documentation

### ISSUE THREAD

**Issue by njl07** [NativeScript/nativescript-angular#439]
Hello,

When I have `Angular2` in `2.0.0-rc6` version, I have the following error:

```bash
file:///app/tns_modules/nativescript-angular/renderer.js:3:33: JS ERROR SyntaxError: Importing binding name '__core_private__' is not found
```

Thanks to upgrade as soon as possible to latest version (`2.0.0-rc6` for `core`... and `3.0.0-rc.2` for `router`) to be compliant between WEB application and `nativescript` mobile application.

If documentation can be updated too it will be very nice.

Best regards.

**Comment by hdeshev** [comment]
Does this error exist with Angular 2.0.0 and nativescript-angular 1.0.0? Please, reopen if so.
