### ISSUE TITLE
how to reduce app size

### ISSUE THREAD

**Issue by ahmedelgendy** [NativeScript/nativescript-angular#441]
Dears,
I made a simple app and when compile it to ipa i found the app size is 170MB
i did similar apps before using ionic and the size maximum is 35 MB. 
i like the performance of nativescript but the app size is too large for small app. 
any advice to reduce the size, minimize or merging files? 
regards

**Comment by NathanWalker** [comment]
@ahmedelgendy When deploying your app (building for release), you should use the webpack plugin:
http://docs.nativescript.org/tooling/bundling-with-webpack

Install with:
```
npm i nativescript-dev-webpack --save-dev
```

Then you can drastically reduce size of your app with the following commands:
iOS: `WEBPACK_OPTS="--display-error-details" tns build ios --bundle`
Android: `WEBPACK_OPTS="--display-error-details" tns build android --bundle`
