### ISSUE TITLE
[nsRouterLink] not working in view but navigate working in component

### ISSUE THREAD

**Issue by bnussey** [NativeScript/nativescript-angular#447]
Hi,

After upgrading to `ng2-rc6` and `nativescript-angular 0.5.0` all the `[nsRouterLink] ` inline links in my templates are not working. So this does not work:

`<Button text="Settings" [nsRouterLink]="['/settings']"></Button>`

But this does:

```
<Button text="Settings" (tap)="goSettings()"></Button>

goSettings() {
    this._router.navigate(["/settings"]);
}
```

Any ideas on what is causing this issue?

Thanks

**Comment by bnussey** [comment]
I confirm this is occurring with the sample-groceries project if I add in a `nsRouterLink`

**Comment by NickIliev** [comment]
hey @bnussey 

We are using [nsRouterLink] in [this sample app](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/examples-list.component.html) and it works as expected (with RC6 and nativescript-angular 0.5.0)

**Comment by bnussey** [comment]
Ok so the fix is on every single module, this must be imported:

`import { NativeScriptRouterModule } from "nativescript-angular/router";` and then add that to the imports.
