### ISSUE TITLE
Action bar not working RC6

### ISSUE THREAD

**Issue by lukashlobil** [NativeScript/nativescript-angular#450]
homepage: 

`<ActionBar title="Hello"></ActionBar>`

other page 

`<ActionBar title="Other page"></ActionBar> `

Haven't changed anything regarding action bars since RC4. Homepage works fine, when I navigate to Other page though, Actionbar is reset to the default one with application name.

nativescript-angular: 0.5.0
tns --version: 2.2.1
"@angular/router": "3.0.0-rc.2",

**Comment by vakrilov** [comment]
Could it be something related to the module declaration? 
The `ActionBar` component is included in the `NativeScriptModule` so make sure you import that if you are using submodule.

**Comment by chrillewoodz** [comment]
Also experiencing this issue in 2.5.2, I've imported the module but the actionbar refuses to show up on any page. All other elements works so I'm not sure what could be wrong..

**Comment by sis0k0** [comment]
Hey @chrillewoodz, can you share an application with the above problem? We couldn't reproduce that behaviour and won't be able to resolve the problem without a particular example.

**Comment by chrillewoodz** [comment]
@sis0k0 Here you go: https://github.com/andresfleat/native-app/tree/sprint1

**Comment by rugdealer** [comment]
+1 Getting the same problem. ActionBar works on one page, and doesn't on another.
