### ISSUE TITLE
ListView: item added event

### ISSUE THREAD

**Issue by bdauria** [NativeScript/nativescript-angular#451]
I'm wondering if it's possible to get notified when an item has been added to a ListView. Basically, I want to scroll to the latest item (using scrollToIndex()) as soon as it's available within the items property. 

I've tried to trigger the scroll when the item in question has been added to the mapped array, but it's actually too early. It's working for now using a setTimeout() but it's surly not a long-term solution.

any thoughts on that?

Thanks in advance.

**Comment by tsonevn** [comment]
For your case you could use ListView `loaded` event and when this event has been fired you could use `scrollToIndex` method to scroll to the last item in your ListView. You could also review the example below.


app.component.html

```
<ListView id="lv" (loaded)="listviewLoaded($event)" [items]="myItems">
    <template let-item="item" let-i="index" let-odd="odd" let-even="even">
        <StackLayout  [id]="item.id" [class.odd]="odd" [class.even]="even">
            <Label [text]='"index: " + i'></Label>
            <Label [text]='"[" + item.id +"] " + item.name'></Label>
        </StackLayout>
    </template>
</ListView>
```

app.component.ts
```
import {Component, Input, ChangeDetectionStrategy} from '@angular/core';
import  {setTimeout} from "timer";
import {Page} from "ui/page";
import {ListView} from "ui/list-view";

class DataItem {
    constructor(public id: number, public name: string) { }
}

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public myItems: Array<DataItem>;
    private counter: number;
    public index:number;

    constructor(private page:Page) {
        this.myItems = [];
        this.counter = 0;
        for (var i = 0; i < 50; i++) {
            this.myItems.push(new DataItem(i, "data item " + i));
            this.counter = i;

        }
        this.index=33;
        
    }
public listviewLoaded(args){
        console.log("listview loaded ");
        var that=this;
         setTimeout(function(){
           var listView:ListView = <ListView>that.page.getViewById("lv");
           console.log(listView);
             listView.scrollToIndex(33);
         },1);
    }
}
```

I hope this is applicable for you.

**Comment by bdauria** [comment]
Well, this is not exactly what I need. I need to trigger an event whenever a new item comes into the ListView items, not when the ListView itself is loaded.

**Comment by hdeshev** [comment]
@bdauria Perhaps you need the [setupItemView](https://github.com/NativeScript/nativescript-angular/blob/master/tests/app/tests/list-view-tests.ts#L18) event

**Comment by bdauria** [comment]
This is still different from what I need. 
To be a bit more precise:
I have a ListView backed by an array within the host Component. The ListView represents a list of events that are displayed from top to bottom. Whenever a new event is added to the array, I need to scroll down right to it. The method adding the event looks like this:
```

  sendMessage(): void {
    const content = this.newMessageView.text;
    if (content == '') {
      return;
    }

    const message =  this.messageService.createMessage({
      content: content,
      transaction_id: this.transaction.id
    });

    this.events.push(message);
    this.dismissKeyboard();
    this.newMessageView.text = '';
    this.scrollChatToBottom();
  }
```
the scrollChatToBottom is the following: 
```
  scrollChatToBottom() {
      this.chatBoxView.scrollToIndex(this.events.length - 1);
      this.chatBoxView.focus();
      this.chatBoxView.refresh();
  }

```

This seems to happen a bit too soon. Therefore, when I change it to:
```
  scrollChatToBottom() {
    // TODO there's got to be a better way!
    setTimeout(() => {
      this.chatBoxView.scrollToIndex(this.events.length - 1);
      this.chatBoxView.focus();
      this.chatBoxView.refresh();
    }, 50);
  }
```

This works perfectly. But it's not really a viable solution to me...

The problem with setupItemView is that there is the possibility that the item is not reachable because its view has not been set up yet.

Any other suggestion?

**Comment by ptdede** [comment]
@bdauria What if you put after you push new data to your array then [yourlistviewreference].refresh() before scrollToIndex() ???

**Comment by cmckni3** [comment]
I had to use a `setTimeout` as well. Calling refresh before `scrollToIndex` does fix the issue.

It would be nice to have `ListView` events. I tried the `loaded` approach that was mentioned in another NS issue but the output doesn't appear to exist.

**Comment by tsonevn** [comment]
HI @cmckni3,
You can try calling`scrollToIndex ` on ScrollView's [layoutChanged](https://docs.nativescript.org/core-concepts/navigation#layoutchanged) event

**Comment by cmckni3** [comment]
This is for `ListView` but it looks like a generic component event. I will try that @tsonevn. Thanks!
