### ISSUE TITLE
Navigation is slow (freezes on the fade-in animation) on Android with version 1.0.0

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/nativescript-angular#453]
Hi,

When upgrading to the latest and final version of **Angular 2** (**2.0.0**) and **nativescript-angular** (**1.0.0**) I started getting an issue where navigation via Router's  `.navigate()` method causes the navigation to be really slow (it looks like the fade-in animation gets stuck). I tested the navigation with `nsRotuerLink` but the issue is inconsistent when navigating forwards , on the other hand the backwards is always slow and has the described issue. 

You can observe this behavior in the **nativescript-ui-samples-angular** repo's project, [here](https://github.com/telerik/nativescript-ui-samples-angular/tree/angular-final-update) us a direct link to the branch with the latest version.

**Comment by VladimirAmiorkov** [comment]
Hi @hdeshev ,

After debugging the issue it looks like it is caused by the latest "tns-core-modules" version **2.3.0** the **2.2.1** version is ok and does not experience this issue.

**Comment by hdeshev** [comment]
Shall we move the issue to NativeScript/NativeScript then?

**Comment by VladimirAmiorkov** [comment]
It looks like it yes.
