### ISSUE TITLE
too many errors to mention

### ISSUE THREAD

**Issue by davidmontgom** [NativeScript/nativescript-angular#454]
test your code ...so many errors to mention.   tried on rc4 went great.  Your final release is kinda of a disaster. QA!

**Comment by valentinstoychev** [comment]
Hey David, this sounds scary!  Are you trying to create a new app or upgrading from existing?

We do have automated tests for a lot of angular apps, so we should see what you are hitting exactly.

**Comment by matt4446** [comment]
I'm running through some upgrades with lots of errors as well.... those are mostly due angular 2 RC6, RC7 breaking changes with modules and bootstrapping in existing apps. I expected that was going to happen. @davidmontgom Do you have any problems in particular you are trying to get through?

**Comment by valentinstoychev** [comment]
@matt4446 Thanks Matthew! - yes there are a lot of breaking changes during the RC releases. The best option for the latest code is to check our Code Samples repo - it is automated and always up to date with the latest changes - http://docs.nativescript.org/angular/code-samples/overview.html

**Comment by devna13** [comment]
I checked out latest code from your sample repos and it's not working: 

https://github.com/NativeScript/sample-Groceries/issues/142

**Comment by dtopuzov** [comment]
I believe issues line this are useless, if if have a concrete problem, please let us know and log it separate issues with enough info how to reproduce it.
