### ISSUE TITLE
How to persist data when navigating from one page to another angular2 nativescript

### ISSUE THREAD

**Issue by sarvagayatri** [NativeScript/nativescript-angular#456]

**Comment by tsonevn** [comment]
Hi @sarvagayatri,
Thank you for your interest in NativeScript.

In NativeScript Angular project you could use `RouterConfig` object which maps paths to components and you could past parameters while navigating as it is described in our [documentation](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#configuration).
For further help you could review the Angular2 documentation, where you could find further info about the Angular router and, how you could parse data.

You could review this thread in SO [here](http://stackoverflow.com/questions/38443407/navigate-with-parameters-in-latest-nativescript-with-angular-and-typescript), where this scenario has been described.

You could also use our [StackOverflow ](http://stackoverflow.com/questions/tagged/nativescript) and [Slack ](https://nativescript.slack.com/) canals for your questions.
I hope this helps.
@tsonevn

**Comment by sarvagayatri** [comment]
I want to save few variable values through out the app, so that i can refer them in any page of app. so routing variables does't work for me. i want to persist few application state variables eg. userId, userStatus etc..

**Comment by AzSiAz** [comment]
Maybe this ?
https://docs.nativescript.org/api-reference/modules/_application_settings_.html

**Comment by tsonevn** [comment]
Hi @sarvagayatri, 

You could use Application Settings as  @AzSiAz has suggested, you could find an example how to use this module [here ](https://docs.nativescript.org/cookbook/application-settings) in the documentation. You could also review the SO thread [here](http://stackoverflow.com/questions/36715918/how-to-define-global-variables-in-angular-2-in-a-way-that-i-can-use-them-for-pro), where has been described how to define global variables in Angular2.

**Comment by hdeshev** [comment]
In addition to what people have already brought up, the Angular router allows you to provide parameters for the component you are navigating to:

https://angular.io/docs/ts/latest/guide/router.html#!#route-parameters

**Comment by RoyiNamir** [comment]
What about back navigation params?

**Comment by tameshnirmalkar** [comment]
you can use service in that case, routing will not fit.
try like this.

PersistDataClass.ts
=================
`class PersistDataClass {
    userData: Array<object>
}
`
Component where you want to set and later get.
`
import { PersistDataClass } from './PersistDataClass';
import { OnInit } from '@angular/core';
export class UserComponent implements OnInit() {

   constructor(private _userservice: PersistDataClass) {

  }
  
    ngOnInit() {
        service.getUserList().subscribe( res => {
          _userservice.userData = res;
      })
    }
}
`
