### ISSUE TITLE
Accessing native api (Searchbar)

### ISSUE THREAD

**Issue by denkomanceski** [NativeScript/nativescript-angular#458]
Which is the best way to access the native APIs of an element? 
I tried with ViewChild to get the instance of a <SearchBar> and call functions in ngAfterViewInit but I it doesnt seem to work.. I accessed with nativeElement, than nativeElement.ios but I dont get any native functions? 
I want to call setHidesNavigationBarDuringPresentation(true) so when I focus the searchbar it will hide the actionbar.. Also, how do I get onfocused for searchbar lets say?
I saw most of the examples where the native APIs are being accessed but its not very clear in this case? What am I doing wrong?

Thanks

**Comment by kazemihabib** [comment]
I think this is related to your problem 
https://github.com/NativeScript/nativescript-angular/issues/406

**Comment by tsonevn** [comment]
Hi @denkomanceski,

To access the native component you could use Component loaded event as it is suggested in the above-referred issue.  You could review the attached example below, where has been shown how to access the native view and to access its properties. 
```
@Component({
    selector: "my-app",
    template: `
        <StackLayout>
            <Label (loaded)="labelLoaded($event)" text="Tap the button" class="title"></Label>
        </StackLayout>
    `
    
})
export class AppComponent {

    public labelLoaded(args){
        var label:Label=<Label>args.object;
        var newcolor=new Color("red");
        if(isIOS){
            console.log("--------native element----------")
            console.log(label.ios);
            label.ios.textColor=newcolor.ios;
        }
    }
}
```

In regard to your next question you could use SearchBar  [focus ](https://docs.nativescript.org/api-reference/classes/_ui_search_bar_.searchbar.html)method, which will return try to focus the view and will return value, which indicating whether it has been focused 

I hope this is applicable for you.

**Comment by hdeshev** [comment]
Yes, using injected `ElementRef`'s and `ViewChild` properties are the recommended way. You can (and should) wrap such code in directives that you attach in attributes or just auto-attach them to the element tag. Here's an example of the latter approach that works around an annoying auto-focus issue with the `SearchBar`:

```typescript
import { Directive, ElementRef } from "@angular/core";
import { Page } from "ui/page";
import { isAndroid } from "platform";

@Directive({
    selector: "SearchBar"
})
export class SearchBarDirective {
    constructor(private element: ElementRef, private page: Page) {
        this.page.on("navigatedTo", () => {
            const bar = this.element.nativeElement;

            if (isAndroid) {
                bar.android.clearFocus();
            }
        });
    }
}
```
