### ISSUE TITLE
Custom dialogs not working 

### ISSUE THREAD

**Issue by alterx** [NativeScript/nativescript-angular#462]
Been testing the custom dialog functionality and it seems to be broken.

I'm getting this error when triggering it:

`CONSOLE ERROR file:///app/tns_modules
/@angular/core/bundles/core.umd.js:3468:36: BaseError@file:///app/tns_modules/@angular/core/bundles/core.um
d.js:1255:42                                                                                               
        NoComponentFactoryError@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6053:24          
        resolveComponentFactory@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6062:46          
        resolveComponentFactory@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6087:62          
        loadInLocation@file:///app/tns_modules/nativescript-angular/common/detached-loader.js:18:60        
        loadComponent@file:///app/tns_modules/nativescript-angular/common/detached-loader.js:30:35         
        showDialog@file:///app/tns_modules/nativescript-angular/directives/dialogs.js:51:49                
        file:///app/tns_modules/nativescript-angular/directives/dialogs.js:27:61                           
        invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:42   
        onInvokeTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6233:51                     
        invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:54   
        runTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:123:57      
        invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:291:40       
        invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:190:33       
        onInvoke@file:///app/tns_modules/@angular/core/bundles/core.umd.js:6242:47                         
        invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:189:42       
        runGuarded@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:97:53    
        file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:73:39               
        tick@file:///app/tns_modules/timer/timer.js:17:26                                                  
        UIApplicationMain@[native code]                                                                    
        start@file:///app/tns_modules/application/application.js:234:26                                    
        bootstrapModule@file:///app/tns_modules/nativescript-angular/platform.js:97:26                     
        anonymous@file:///app/main.js:6:57                                                                 
        evaluate@[native code]                                                                             
        moduleEvaluation@[native code]                                                                     
        [native code]                                                                                      
        promiseReactionJob@[native code]                                                                   
Sep 20 18:42:50 --- last message repeated 1 time ---          `

 It's reproducible with the following dependencies:

`  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0",
    "nativescript-angular": "^0.6.0",
    "nativescript-cardview": "^1.1.11",
    "nativescript-slides": "^2.1.5",
    "reflect-metadata": "^0.1.5",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.3.0"
  },
  "devDependencies": {
    "babel-traverse": "6.15.0",
    "babel-types": "6.15.0",
    "babylon": "6.9.2",
    "codelyzer": "0.0.28",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^0.3.0",
    "nativescript-dev-typescript": "^0.3.2",
    "tslint": "^3.15.1",
    "typescript": "^1.8.10",
    "zone.js": "^0.6.21"
  }`

The code I'm using is copy&pasted from the sample app in this repo [https://github.com/NativeScript/nativescript-angular/tree/master/ng-sample]

**Comment by hdeshev** [comment]
Please, double check that your dialog "content" component has been registered with the `entryComponents` in your `NgModule` definition. I keep forgetting that and usually get the "no component factory error"

**Comment by alterx** [comment]
@hdeshev that was it! Thank you for your quick response!
