### ISSUE TITLE
Nativescript with Angular 2: proper i18n approach?

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#464]
_From @andy-tai on September 21, 2016 7:35_

Angular 2 has its own i18n functionality:
http://www.savethecode.com/angular2-i18n-native-support/

Will NativeScript adapt Angular's i18n for its own use?  Or the nativescript-i18n plugin is to be officially supported part of NS going forward?

_Copied from original issue: NativeScript/NativeScript#2776_

**Comment by hdeshev** [comment]
It looks like translations are compiled to TypeScript files, which should be perfectly usable in NativeScript apps. I haven't tried it yet, but my guess is that it's just a matter of tweaking the tools, and publishing an article in the docs.

**Comment by m-abs** [comment]
We use https://github.com/NathanWalker/angular2-seed-advanced as a base for our project, with this we get ng2-translate support for both web, desktop and nativescript in the same codebase.

Translations are super easy, it's just an JSON-file with KEY => translated string.

**Comment by andy-tai** [comment]
While that seems working well, the choice of the Angular team matters greatly--they made a choice, and if you don't go with it, that will mean greater cost in keeping up to date and so on.

**Comment by ignaciolarranaga** [comment]
Some update on this guys ?, I feel the same as @andy-tai, but currently using ng2-translate.

**Comment by Svoig** [comment]
Any news on this? I second @andy-tai on this one. ng2-translate is good as far as it goes, but I prefer the Angular team's solution. And it would be nice to see NativeScript stay close to the Angular team's decisions.

**Comment by NickIliev** [comment]
The support for L18 is logged [here ](https://github.com/NativeScript/nativescript-angular/issues/1133)and is under development
