### ISSUE TITLE
ListPicker two-way binding via [ngModel] is not working

### ISSUE THREAD

**Issue by devna13** [NativeScript/nativescript-angular#465]
Changing first list picker doesn't update the second one.
Also there is no change detection using ngModel and selectedIndex never gets updated.
      
```
<ListPicker 
                #picker 
                [items]="itemsList" 
                [selectedIndex]="selectedIndex" 
                (selectedIndexChange)="selectedIndexChanged(picker)"
></ListPicker>
              
<ListPicker 
                [items]="itemsList"
                [(ngModel)]="selectedIndex"
></ListPicker>
```

in the controller: 

    selectedIndex = 0;
    itemsList = ['A', 'B', 'C', 'D'];

    selectedIndexChanged(picker) {

        console.log(' selection:  ' + picker.selectedIndex + ' ' + this.selectedIndex);
    }

output:

```
JS:  selection: 0 0
JS:  selection: 1 0
JS:  selection: 2 0
JS:  selection: 3 0
```

**Comment by denkomanceski** [comment]
Do you have the Nativescript formModule included in your main NgModule? none of the ngmodel bindings work without it

**Comment by devna13** [comment]
Thanks @denkomanceski for the tip.

import { NativeScriptFormsModule } from "nativescript-angular/forms";
