### ISSUE TITLE
Nativescript Angular iOS built is successful (and works in emualator) but crashes on physical phone 

### ISSUE THREAD

**Issue by blaur** [NativeScript/nativescript-angular#469]
I need your help!

My nativescript app is running perfectly fine on android as well as in my iPhone 6S (iOS 10) emulator. The problem arise when trying to run the exact same code on my physical iPhone 6S (with the cmd: tns run ios) - it simply crashes with the following error:

Native stack trace:
```
1   0x10064bd48 -[TNSRuntime executeModule:]
2   0x1000a1494 main
3   0x180d568b8 <redacted>
JavaScript stack trace:
1   @file:///app/shared/student/student-list.service.js:14:24
JavaScript error:
file:///app/shared/student/student-list.service.js:14:24: JS ERROR Error: Could not find module './student'. Computed path '/var/containers/Bundle/Application/D87AA4D8-4172-4BBB-A033-FA56D354C6E9/instructorapp.app/app/shared/student/student'.
```

I have been trying to figure out what is going on for a couple of days now. I still have a suspicion that it is related to nativescript and angular versions where NgModule was introduced but since it runs on android and in the emulator i sort of dropped the thought. I have been fiddling around with npm/node versions but I have come to a full stop now and have no idea how to progress from here since it is running in the emulator.

I have also tried opening the project in xcode, building the ipa (also succesfull) and then copying it to the phone. It always get to the loadscreen and then crashes.

My package.json:

```
 "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/platform-server": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "email-validator": "1.0.4",
    "moment": "2.13.0",
    "nativescript-angular": "0.4.0",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.1.0",
    "nativescript-telerik-ui-pro": "file:nativescript-ui-pro.tgz",
    "nativescript-timedatepicker": "^0.2.2",
    "nativescript-unit-test-runner": "0.3.3",
    "nativescript-web-image-cache": "^2.0.1",
    "rxjs": "5.0.0-beta.6",
    "tns-core-modules": "^2.3.0",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "babel-traverse": "6.8.0",
    "babel-types": "6.8.1",
    "babylon": "6.8.0",
    "filewalker": "0.1.2",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^1.8.10"
  }
```

Any suggestions would we dearly appreciated. This is really getting to me ;)

**Comment by hdeshev** [comment]
It looks like a missing module import that may have been passing on your simulator due to an older version of a file lying around. You could verify that by deleting your platforms folder and trying to run your app.

In addition you could try upgrading to angular 2.0.0 and nativescript-angular 1.0.0, if you suspect you hit an issue in the old RC builds.
