### ISSUE TITLE
JS ERROR Error: Could not find module './'.

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#471]
_From @tskweres on September 26, 2016 3:44_

When I try to run on a simple helloworld app with routes setup from the docs ( first.component, second.component ):

tns livesync ios --emulator --watch

I get this error:

NativeScript loaded bundle file:///System/Library/Frameworks/UIKit.framework
NativeScript loaded bundle file:///System/Library/Frameworks/Foundation.framework
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x100457d48 -[TNSRuntime executeModule:]
2   0x10005d4b4 main
3   0x180b4e8b8 <redacted>
JavaScript stack trace:
1   @undefined
JavaScript error:
undefined: JS ERROR Error: Could not find module './'.

_Copied from original issue: NativeScript/nativescript-cli#2080_

**Comment by hdeshev** [comment]
I have seen this error when using an old node/npm combination. @tskweres, what version(s) are you using, and does the problem go away, if you try switching to Node 6.x?

**Comment by koichirokamoto** [comment]
@tskweres
I have same error after delete package.json created by `tns create <app> --ng` under app folder.
Then, I recover pakcage.json and I resolve error.

**Comment by danieljohngomez** [comment]
Having this issue as well even on a newly created project

**Comment by tskweres** [comment]
This has since been resolved for me by updating my nodejs version

**Comment by enoonan** [comment]
I am running into the same problem using node 6.10.2

**Comment by charalamposc** [comment]
Same problem here:

node: 6.11.2
nativescript: 3.1.3 
tns-core-modules: 3.1.1 
tns-android: 3.1.1 
tns-ios: 3.1.0
typescript 2.2.2

What means this error? Is there a workaround? All things I found in other issues (like, node downgrading, other typescript versions, reinstall of tns etc) didn't work.

**Comment by charalamposc** [comment]
After hours of searching I found out (sadly for me) that I deleted the `main.ts` file. After restoring the file everything worked fine as before.
