### ISSUE TITLE
Http module allways returns {} for .text()

### ISSUE THREAD

**Issue by cime** [NativeScript/nativescript-angular#473]
Angular Http result is not the same (it's wrong) as nativescript's http module result.

In main @NgModule I import NativeScriptHttpModule and then I use it like so:

```
import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import http = require("http");

const testUrl = "https://github.com/NativeScript/nativescript-angular/issues";

@Injectable()
export class DataService {

    constructor(private http: Http) { 

    }

    test() {
        this.http.get(testUrl).map(x => x.text()).subscribe((content) => {
            console.log("NG2 HTTP: " + content);
        });

        http.getString(testUrl).then((content) => {
            console.log("NS HTTP: " + content);
        });
    }
}
```

The result:

```
JS: NG2 HTTP: {}
JS: NS HTTP:
JS:
JS:
JS:
JS: <!DOCTYPE html>
JS: <html lang="en" class="">
JS:   <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# object: http://ogp.me/ns/object# article: http://ogp.me/ns/article# profile: http://ogp.me/ns/profile#">
JS:     <meta charset='utf-8'>
....
```

**Comment by cime** [comment]
res.json() works as expected, but my response is not a (valid) json but a normal text

**Comment by nsndeck** [comment]
Hi @cime,

Another option is to call `res._body.toString()` or just `res._body` (indeed accessing private fields is not the best practice ...). I believe you can take a look at the `body.text()` (second link from my previous response) method and see what actually angular 2 do with the response when this method is called. 
Do you search angular 2 issues for something similar?

Nedyalko

**Comment by CuBiC3D** [comment]
@nsndeck Why this has been closed? Issue is still present. Everything that's not Content-Type: application/json results in {}. text() works on application/json.

**Comment by cime** [comment]
I created a plunked which shows that res.text() works as expected in a normal web application:
https://plnkr.co/edit/13Z45fSqgfiwtlWoEBZi?p=preview

**Comment by nsndeck** [comment]
@cime 
Sorry for the delay we fix this issue within nativescript core modules, so you can test it with installing `tns-core-modules@next` or after the official release in a week.

**Comment by corne-de-bruin** [comment]
I've run into the same issue where .text() returns {}. But when i use tns-core-modules@next (thats version 2.5.0 right now) on iOS i'll receive _body: <3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d227574 in my responses.

This have been an issue before.
