### ISSUE TITLE
Feature Request: Provision to put test files in feature folder instead of tests folder

### ISSUE THREAD

**Issue by shripalsoni04** [NativeScript/nativescript-angular#482]
It will be great if we can put our test files in the respective feature folder instead of putting all the test files in app/tests folder.

When we do development for web version of angular application, we put the test files in respective feature folders with `.spec.ts` suffix as per the angular style guide. 

If we can do the same thing in angularNative app also, it will be very easy to get started and it will open a way for unit-test code sharing. As currently we have different structures for test files in nativescript and web version, we cannot share the unit-test files easily and we need to manually copy the unit-test files and change the import path of the module being tested in test file for any cross platform shared code. 

I thought to run a script which copies all the .spec.ts file to tests folder from feature folders, but then it will add complexities like adding new/changed test files back to app/tests folder in watch mode.

Let me know if there is already some way and I am missing that.

Thanks.

**Comment by hdeshev** [comment]
This issue was moved to NativeScript/nativescript-cli#2095
