### ISSUE TITLE
Dynamic Linking Error: dlopen(libc.dylib, 2): image not found

### ISSUE THREAD

**Issue by agrawal-mohit** [NativeScript/nativescript-angular#483]
I ran through the ios setup properly, tns doctor resulted into this : 

> 
> Verifying CocoaPods. This may take more than a minute, please be patient.
>   ◡ Installing iOS runtime.tns-ios@2.3.0 ../../var/folders/9t/0qgpwgy906z_sww71dnkgkr80000gn/T/nativescript-check-cocoapods11692-12489-xraco2/node_modules/tns-ios
>   ◝ Verifying CocoaPods. This may take some time, please be patient..
>  sandbox-exec: /Users/mohit/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod: Operation not permitted
> 
> WARNING: There was a problem with CocoaPods
> Verify that CocoaPods are configured properly.
> There seem to be issues with your configuration.
> ? Do you want to visit the official documentation? No
> ? Do you want to run the setup script? No
> Your components are up-to-date.
> 
> When you file an issue, these warnings will help the NativeScript team to investigate, identify, and resolve the report.
> Please, ignore them if you are not experiencing any issues with NativeScript.
> 
> 

I'm trying to run the groceries app, on issuing : tns run ios --emulator

> Dynamic Linking Error: dlopen(libc.dylib, 2): image not found
> # run ios
> ┌──────────────────────────────────┬─────────────────────────────────────────────────┐
> │ Usage                            │ Synopsis                                        │
> │ Run on all connected devices     │ $ tns run ios [--release] [--justlaunch]        │
> │ Run on a selected connected      │ $ tns run ios [--device <Device ID>] [--release │
> │ device                           │ ] [--justlaunch]                                │
> │ Start an emulator and run the    │ $ tns run ios --emulator [<Emulator Options>] [ │
> │ app inside it                    │ --release]                                      │
> └──────────────────────────────────┴─────────────────────────────────────────────────┘
> 
> Runs your project on a connected iOS device or in the iOS Simulator, if configured. This is shorthand for prepare, build, and deploy. While your app is running, prints the output from the application in the console.
> 
> IMPORTANT: Before building for iOS device, verify that you have configured a valid pair of certificate and provisioning profile on your OS X system. 
> 
> ### Options
> 
>     * --watch - If set, when you save changes to the project, changes are automatically synchronized to the connected device.
>     * --device - Specifies a connected device on which to run the app.
>     * --emulator - If set, runs the app in a native emulator for the target platform, if configured. When set, you can also set any other valid combination of emulator options as listed by $ tns help emulate ios. You cannot use --device and --emulator simultaneously.
>     * --release - If set, produces a release build. Otherwise, produces a debug build.
>     * --justlaunch - If set, does not print the application output in the console.
> 
> ### Attributes
> 
>     * <Device ID> is the index or name of the target device as listed by $ tns device ios
>     * <Emulator Options> is any valid combination of options as listed by $ tns help emulate ios
> 
> Sending exception report (press Ctrl+C to stop).....
>

**Comment by tsonevn** [comment]
Hi @agrawal-mohit,
After reviewing the given information it seems that there is a problem with installation the `cocoapods`.
In regard to that you could follow the below-given commands, which will help you to setup them, 

`echo Y | sudo gem uninstall cocoapods`

`sudo gem install cocoapods`

`pod setup`


I hope this helps.

**Comment by agrawal-mohit** [comment]
New error trace : 
Verifying CocoaPods. This may take more than a minute, please be patient.
  ◞ Installing iOS runtime.tns-ios@2.3.0 ../../../../../../var/folders/9t/0qgpwgy906z_sww71dnkgkr80000gn/T/nativescript-check-cocoapods116912-21941-1m23w1v/node_modules/tns-ios
  ◠ Verifying CocoaPods. This may take some time, please be patient..
 sandbox-exec: /Users/mohit/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-1.0.1/bin/pod: Operation not permitted

WARNING: There was a problem with CocoaPods
Verify that CocoaPods are configured properly.
There seem to be issues with your configuration.
? Do you want to visit the official documentation? No
? Do you want to run the setup script? No
Your components are up-to-date.

**Comment by tsonevn** [comment]
Hi @agrawal-mohit,

Could you verify, whether `ANDROID_HOME` has been set up correct. To do that you  could run `echo $ANDROID_HOME`. This command will show you, where is pointing this variable. If the command show empty string or not correct path you could setup `ANDROID_HOME` using following command: `export ANDROID_HOME=<path to android-sdk folder>`. If that doesn't help you could run our setup script for [OS X](https://docs.nativescript.org/start/quick-setup.html#os-x) , which will setup your workstation.


I hope this helps.
