### ISSUE TITLE
Configure Page properties with nativeScriptBootstrap

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#49]
Think of a way to configure the Page with the new style nativeScriptBootstrap that initializes everything. Several options on the table:

- Expose a way to pass a `loaded` callback for the page.
- Pass a Page DI provider to `nativeScriptBootstrap`
- Configure Page properties with components/directives in HTML.

**Comment by NathanWalker** [comment]
This sounds interesting and may be related to my confusion here:
https://github.com/NativeScript/nativescript-angular/issues/53

**Comment by hdeshev** [comment]
Fixed by #67
