### ISSUE TITLE
How to create a formData Object from selecting a file from gallery in the android.

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-angular#494]
Can any one please send about creation of formData object by selecting a file from gallery.

**Comment by JaganJonnala** [comment]
how to create formData.append("file",file,file.name) with the parametes from the selectedAsset
Whats that file as second parameter from selectedAsset

**Comment by hdeshev** [comment]
@JaganJonnala, this is the development issue tracker for the NativeScript-Angular integration. Please use StackOverflow for user questions.
