### ISSUE TITLE
can't render to view 

### ISSUE THREAD

**Issue by mostafa-raafat** [NativeScript/nativescript-angular#498]
### i have strange problem i don't know if it's angular 2 thing or nativescript problem but i need some help:

```
javascript

this.ordersService.getData(this.user)
            .subscribe(
                (res) => {
                        let data = JSON.parse(res);
                        this.mydata = data.detalis;
                        console.log(this.mydata)
                },
                (err) => alert("Please check your internet connection and try again")
            );

html

  <Label [text]="mydata"></Label>  or 
  <Label text="{{ mydata }}"></Label>
```

when i console the result it's show but i can't render it in the view

**Comment by NickIliev** [comment]
Hey @mostafa-raafat 

Try to wrap your this.data in ngZone like the example shown [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/connectivity/using-connectivity/using-connectivity.component.ts#L34). Do not forget to declare it in your constructor

```
import { NgZone } from "@angular/core";
....
constructor(private zone: NgZone) { }
```

More information about NgZone can be found [at the oficial documentation] (https://angular.io/docs/ts/latest/api/core/index/NgZone-class.html) and also a nice [blog-post can be found here](http://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html)

**Comment by mostafa-raafat** [comment]
```

**Comment by mostafa-raafat** [comment]
```this.ordersService[name](this.user)
            .subscribe(
                (res) => {
                    this.zone.run(() => {
                        let data = JSON.parse(res);
                        this.isLoading = false;
                        if(data.details == ''){
                            this.noResult = true;
                            console.log(this.noResult);
                        }
                    });
                },
                (err) => alert("Please check your internet connection and try again")
            );

**Comment by mostafa-raafat** [comment]
```
### still not working , do you think i made something wrong 

import { NgZone } from "@angular/core";
....
constructor(private zone: NgZone) { }

this.ordersService[name](this.user)
            .subscribe(
                (res) => {
                    this.zone.run(() => {
                        let data = JSON.parse(res);
                        this.mydata = data.detalis;
                        console.log(this.mydata)
                    });
                },
                (err) => alert("Please check your internet connection and try again")
            );
```

**Comment by NickIliev** [comment]
Hey @mostafa-raafat 

Can you provide us with a sample app that reproduces this scenario - the binding on Label should work if the data is received successfully even without the help of the ng zone. You canalso refer to this examples for [fetch](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/fetch/fetch-get/fetch-get.component.ts#L45-L65) and [http module](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/httpModule/http-module-get/http-module-get.ts) where there is also binding of the received data.
