### ISSUE TITLE
Upgrade app to Angular 2.1 - Failed to find module "stream".

### ISSUE THREAD

**Issue by adisoftbn** [NativeScript/nativescript-angular#501]
Hello,

If i upgrade angular modules to 2.1.0, router 3.1.0, nativescript-angular 1.1.0 I get the following error:

Failed to find module "stream".

![screenshot_20161020-005231](https://cloud.githubusercontent.com/assets/1209902/19539138/774313ee-9660-11e6-991a-920a85888167.png)

Even if I remove node_modules/hooks/platform directories.

If I revert back to 2.0.1/3.0.1 Everything works flawless.

I didn't saw any node module dependecy conflict.

The error comes automatically after loading screen.

**Comment by tsonevn** [comment]
Hi @adisoftbn,

The latest version of  `nativescript-angular` does not require `@angular/platform-server` dependencies. regarding to that you could check your package.json for it. To be sure that you have the right dependancies in your project you could follow the `package.json` file from this repo. If this  doesn't solve the problem could you provide more info about your project and the `dependencies` in its 
`package.json` file.
Hope this helps.

**Comment by adisoftbn** [comment]
Hey @tsonevn 

This was the problem! After i removed ***@angular/platform-server*** from ***package.json*** everything works as expected :D found no other issue so far :D

There needs to be a warning somewhere about this.

Best regards :D

**Comment by b-lawrence** [comment]
I'm afraid this did not solve the problem for me. I don't even have `@angular/platform-server` listed as one of my dependencies.
