### ISSUE TITLE
TypeScript compilation no longer works after upgrade to TypeScript 2.0.3

### ISSUE THREAD

**Issue by blaur** [NativeScript/nativescript-angular#502]
Hi guys,

I have recently upgraded to TypeScript 2.0.3 to get past a problem with the firebase nativescript plugin.

Everything is compiling and building but my javascript files are no longer generated.

Maybe it is due to my lack of knowledge about the matter but I have not been able to find any help through google or anywhere else.

Following is my package.json dependecies:

```
{
  .
  .
  .
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/platform-server": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "email-validator": "1.0.4",
    "moment": "2.13.0",
    "nativescript-angular": "0.4.0",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.1.0",
    "nativescript-plugin-firebase": "^3.7.1",
    "nativescript-timedatepicker": "^0.2.2",
    "nativescript-unit-test-runner": "0.3.3",
    "nativescript-web-image-cache": "^2.0.1",
    "rxjs": "5.0.0-beta.6",
    "tns-core-modules": "^2.3.0",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "babel-traverse": "6.8.0",
    "babel-types": "6.8.1",
    "babylon": "6.8.0",
    "filewalker": "0.1.2",
    "jasmine-core": "^2.4.1",
    "karma": "^0.13.22",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "nativescript-dev-webpack": "0.0.20",
    "typescript": "^2.0.0"
  }
}
```

And this is my tsconfig.json:

```
{
    "compilerOptions": {
        "outDir": "app",
        "rootDir": "app",
        "module": "commonjs",
        "target": "es5",
        "inlineSourceMap": true,
        "experimentalDecorators": true,
        "removeComments": false,
        "emitDecoratorMetadata": true,
        "noEmitOnError": true
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}
```

Also, I have made sure that I have run npm install -g typescript and tsc --version gives me the correct version.

Again, everything compiles:

```
Executing before-prepare hook from C:\Users\Brian\Desktop\Development\student-application\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.0.3
Project successfully prepared (android)
```

Any help?

**Comment by mcordes** [comment]
I believe I can help. I had the same issue. I was able to fix it by updating my tsconfig.json to be the following:

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "removeComments": true,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "dom"
        ],
        "inlineSourceMap": true,
        "pretty": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "noImplicitAny": false,
        "noImplicitReturns": true,
        "noImplicitUseStrict": false,
        "noFallthroughCasesInSwitch": true,
        "typeRoots": [
            "node_modules/@types",
            "node_modules"
        ],
        "types": [
        ]
    },
    "exclude": [
        "node_modules",
        "platforms"
    ],
    "compileOnSave": false
}
```

And I was pointed in the right direction by looking at these:

1. https://github.com/NathanWalker/angular-seed-advanced/blob/master/nativescript/tsconfig.json
2. https://github.com/NathanWalker/angular-seed-advanced/blob/master/nativescript/package.json

**Comment by blaur** [comment]
HI @mcordes,

Thanks a lot for your answer.

It indeed build generates .js files with your tsconfig file. After switching my application simply crashes on start up without any error messages except for the "has stopped working" on android.

Also, I am getting the following errors on build (but it still builds successfully):
```
Found peer TypeScript 2.0.3
error TS2318: Cannot find global type 'Boolean'.


error TS2318: Cannot find global type 'Function'.


error TS2318: Cannot find global type 'IArguments'.

error TS2318: Cannot find global type 'Number'.

error TS2318: Cannot find global type 'Object'.

error TS2318: Cannot find global type 'RegExp'.

error TS2318: Cannot find global type 'String'.
```

Does that tell you anything?

**Comment by vakrilov** [comment]
Hey @blaur 
I see you are using quite old version of `nativescript-angular` and `@angular`. 
Have you tried updating you project to the current official versions:
-  `1.1.1` for `nativescript-angular`
- `2.1.1` for `@angular` packages
- `3.1.1` for `@angular/router`

**Comment by blaur** [comment]
Hi @vakrilov 

I have not tried because it introdues a lot of refactoring in bascially everythng but it seems like I have no choice.

One wonders me is that the build is still successful.

**Comment by vakrilov** [comment]
I'm and currently using version `2.3.0` of the NativeScript CLI (a.k.a. `tns`) and the the `run`/`livesync` commands fail whenever there are compile errors - indeed this is the expected behavior.

**Comment by blaur** [comment]
I am not really sure how that helps me.

I am getting the above errors but the run commands do not fail.

**Comment by blaur** [comment]
It disappeared after upgrading to newest version 2.5 of nativescript and 2.1.6 of TypeScript.
