### ISSUE TITLE
DatePicker two-way binding via [(ngModel)] is not working with docs exemple

### ISSUE THREAD

**Issue by Quovadisqc** [NativeScript/nativescript-angular#506]
The [documentation](https://docs.nativescript.org/angular/code-samples/ui/date-picker.html) for NativeScript-Angular mentions to use the DatePicker control like this:
`<datePicker #datePicker (loaded)="configure(datePicker)" verticalAlignment="center"></datePicker>`

If I use this exemple to implement two-way binding using ngModel
`<datePicker #endDatePicker [(ngModel)]="endDate"></datePicker>`
I get this error:
> No value accessor for form control with unspecified name attribute

If I use this code instead, it works perfectly
`<DatePicker #endDatePicker [(ngModel)]="endDate"></DatePicker>`

Perhaps this is a typo in the documentation?

**Comment by tsonevn** [comment]
Hi @Quovadisqc,

Thank you for reporting this issue. 
I reviewed your case and confirm that this is a real issue, while using `ngModel` directive and the `DatePicker` open and closing tag has been written with first lowercase letter. You could keep tracking this issue for further info.

Regards,
@tsonevn
