### ISSUE TITLE
Dev workflow - there is no 'grunt app'

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#51]
I've been able to get stuff to work, but not following the dev workflow in the readme.
There is no `grunt app`... task not found.

I wanted to verify this is indeed the case, and if so, I'll add a PR to remove that from the dev workflow or if there are new recommended dev workflow steps, if someone could please update the readme.
:)

**Comment by hdeshev** [comment]
I fixed the README, `grunt app` was an old step that isn't needed anymore.
