### ISSUE TITLE
iOS TabView - Icon color not adhere to selectedColor 

### ISSUE THREAD

**Issue by dacrystal** [NativeScript/nativescript-angular#510]
I have a Tabview with selecredColor as follow:

```html
<TabView #tabview id="tabview" class="tab-bar"   selectedColor="#E64A19">
   <StackLayout *tabItem="{title:'Me'}">
  </StackLayout>

  <StackLayout *tabItem="{iconSource: 'res://tabbar-icon-home'}">
        <home></home>        
  </StackLayout>

  <StackLayout *tabItem="{title: 'Notifications'}">
  </StackLayout>

</TabView>
```

Title color is rendered correctly. However, icon color (as the underline iOS render mode is set automatic) is not applying selectedColor. Instead it is rendered as default blue IOS color.

***Workaround***

 Is to trigger `_updateIOSTabBarColorsAndFonts`  manually in `ngAfterViewInit `

```ts
export class FooComponent implements AfterViewInit{

	constructor(private page: Page) {
	}

	ngAfterViewInit(){
		var tabview = <any>this.page.getViewById("tabview");
		tabview._updateIOSTabBarColorsAndFonts();
	}
}
```

```
$ tns --version
2.3.0

$ cat package.json 
...
 "dependencies": {
    "@angular/common": "2.0.1",
    "@angular/compiler": "2.0.1",
    "@angular/core": "2.0.1",
    "@angular/forms": "2.0.1",
    "@angular/http": "2.0.1",
    "@angular/platform-browser": "2.0.1",
    "@angular/platform-browser-dynamic": "2.0.1",
    "@angular/platform-server": "2.0.1",
    "@angular/router": "3.0.1",
    "google-libphonenumber": "^2.0.3",
    "nativescript-angular": "1.0.1",
    "nativescript-dev-sass": "^0.3.0",
    "nativescript-telerik-ui": "^1.4.1",
    "nativescript-theme-core": "^0.1.2",
    "reflect-metadata": "^0.1.8",
    "tns-core-modules": "2.3.0"
  },
...

```

**Comment by tsonevn** [comment]
Hi @dacrystal,
Did you try to run your project with `@next` modules. You could do that by running `tns plugin remove tns-core-modules` and `tns plugin add tns-core-modules@next` you should also remove `platforms`, 'node_modules' and `hooks` folders before building your project.  You could also upgrade your other dependencies version by following the `package.json` file from the [template-hello-world-ng](https://github.com/NativeScript/template-hello-world-ng/blob/master/package.json). With the new modules you should also use the new `TabView`  properties. you could read more about them  here in [this ](https://github.com/NativeScript/NativeScript/issues/2738#issuecomment-255745605) issue.


Hope this helps

**Comment by dacrystal** [comment]
Yes I can confirm the issue is fixed.  

The new `TabView` properties maybe still not make to the current @next `"tns-core-modules": "^2.5.0-2016-10-25-4563"`. I'll test them once they are there.

**Comment by Ihor912** [comment]
Hi guys,
This solution for me. Maybe it will help someone else.

I use two different icons for the selection state and for the inactive state.
Also, property iosIconRenderingMode value should be "alwaysOriginal".

In template:
```
<TabView tabBackgroundColor="#6E7AFA" androidTabsPosition="bottom" iosIconRenderingMode="alwaysOriginal" (selectedIndexChanged)="tabViewIndexChange($event)">
    <page-router-outlet *tabItem="homeTab" name="homeTab"></page-router-outlet>
    <page-router-outlet *tabItem="settingsTab" name="settingsTab"></page-router-outlet>
</TabView>
```

In component:
```
homeTab: any;
settingsTab: any;

constructor() {
    this.homeTab  = { iconSource: this.getIconSource("home") };
    this.settingsTab  = { iconSource: this.getIconSource("settings") };
}

tabViewIndexChange(args) {
    const index = args.newIndex;
    this.homeTab = { iconSource: this.getIconSource(index === 0 ? "home_selected" : "home") };
    this.settingsTab = { iconSource: this.getIconSource(index === 1 ? "settings_selected" : "settings") };
}

getIconSource(icon: string): string {
    const iconPrefix = isAndroid ? "res://" : "res://tabIcons/";
    return iconPrefix + icon;
}
```
