### ISSUE TITLE
Add [visible] or [hidden] attribute

### ISSUE THREAD

**Issue by aboalwi** [NativeScript/nativescript-angular#520]
instead of visibility="{{ cond ? 'visible' : 'collapsed' }}" which takes time and effort each time...
i have to look around to copy and paste this stuff.. shouldn't we just have [hidden] or [visible] right out of the box?
I'm pretty sure it will be worth having.. please consider it.

**Comment by vakrilov** [comment]
You can definitely implement those as custom directives or just use `*ngIf` instead

**Comment by NickIliev** [comment]
Hey @aboalwi 

This exact same scenario is shown in [this sample](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ui-category/ng-directives/using-ngif) - using @ngIf for controlling the visibility of your element.

**Comment by aboalwi** [comment]
@NickIliev so ngIf is basically controlling the visibility of an element is that right? in this case they are just the same. In web it removes from DOM in my particular case visibility is better. But we are not on a webview arent we :) ? 
Thanks for the link it cleared things up. Also +1 for create-custom-directive

**Comment by NickIliev** [comment]
@aboalwi as described in Angular docs:

> Removes or recreates a portion of the DOM tree based on an {expression}.

Only in our case we are not working with DOM but with the NativeScript elements.
