### ISSUE TITLE
RadSideDrawer seperation

### ISSUE THREAD

**Issue by RyanSMurphy** [NativeScript/nativescript-angular#521]
I have successfully implemented RadSideDrawer into my app. However, currently, I am implementing it on every HTML view separately. I have 5 pages, they all have the full RadSideDrawer code in the view and component. 

Is there a way of segregating this so I don't have to copy and paste the code onto every new page I create? 

Thanks

**Comment by janteloo** [comment]
Yes there is, I followed this article, and could do it without any issues
https://codedump.io/share/S9LgvPW6tgA8/1/nativescript---make-telerik-sidedrawer-in-all-views

**Comment by NickIliev** [comment]
@RyanSMurphy this feature will be implemented once [this one](https://github.com/NativeScript/NativeScript/issues/48) is ready for production.
