### ISSUE TITLE
TabView: Android and iOS have different init behavior

### ISSUE THREAD

**Issue by lorcanfurey** [NativeScript/nativescript-angular#525]
I have implemented TabView on my app, and I noticed these differences:
- Android: upon initial TabView load, the `selectIndexChanged` event is run
- iOS: upon initial TabView load, the `selectIndexChanged` event is not run

I'm not asking for a side-fix, only curious: was this behavior intentional, or is there any drive to have implementation parity between these differences? (this confused me as I expected event behavior to be the same for both)

**Comment by m-abs** [comment]
This question might belong as an issue on NativeScript.
I assume {N} without angular have the same behavior.
