### ISSUE TITLE
Clarification on `app.ts` vs. `main-page.ts` for bootstrap

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#53]
Recent changes were pushed in today that are confusing. There's now 2 files the deal with bootstrap. `app.ts` and `main-page.ts`... It appears `app.ts` is taking precedence... as the `ListTestAsync` component is now launching (on current master) as opposed to whatever change I make in `main-page` to try out different examples. So is the intent for `app.ts` to take place of `main-page.ts` as far as bootstrapping goes? :/

**Comment by hdeshev** [comment]
The goal is to have a single ts file that would be the application entrypoint similar to what the Angular2 web tutorials make you go through (the usual `boot.ts`).

We think that having a separate page module that you navigate to [1], and having an XML file that is handled by the non-Angular NativeScript component builder would be too confusing for users. That's the goal here -- expose client code to as little non-Angular API's as possible.

--------
[1] And of course using the NativeScript navigation framework that is completely different than the Angular rouuter.

**Comment by hdeshev** [comment]
Oh, and forgot to mention, if you want to get your app running quickly with the new renderer changes, just swap `nativeScriptBootstrap` for `bootstrap` in your `main-page.ts` file. The difference between the two is that `bootstrap` will just start the Angular app while `nativeScriptBootstrap` will set up the NativeScript app and main page, then start the Angular app.

**Comment by NathanWalker** [comment]
Thanks for the explanation, that makes sense.
