### ISSUE TITLE
canDeactivate and back navigation

### ISSUE THREAD

**Issue by dacrystal** [NativeScript/nativescript-angular#531]
I was able to implement `canActivate` and `canDeactivate` guard successfully. 

`canDeacivate` works fine with normal navigation. However with back navigation (`NavigationButton` or `RouterExtensions.back()`), page will navigate back even if `canDeactivate` is resolving to `false`. And all navigation on the previous page  will stop working except `navigation back` will result on fatal error:

```
file:///app/tns_modules/rxjs/Subscriber.js:227:2
2: JS ERROR Error: Calling startGoBack while going back.
```

**Comment by vakrilov** [comment]
[Currently, there is no way to prevent user-initiated back navigation - trying to apply guards in such scenario is not supported.](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#route-guards)
