### ISSUE TITLE
Android Performance Issues w/ Simple List/Detail App

### ISSUE THREAD

**Issue by kronok** [NativeScript/nativescript-angular#532]
Hey, I've been dabbling with Nativescript for awhile now, but I'm running into a pretty big issue right out the door now that I'm ready to make a real app.

I started by moving a slice of my complex Angular 2 web app to Nativescript, and had performance issues. So I created a simple list/detail app to try to figure out what the big issue was (no http calls or fancy services) with RadListView, but it still feels very sluggish transitioning from the list to the detail and back again. It feels like it freezes anywhere from 1-5 seconds every time it navigates.

I figured it must be the emulator I'm using (genymotion), so I tried deploying it to my Android device and it still has that same feeling. Tried enableProdMode() and still, same sluggish feeling.

Not sure about the iOS performance because I don't have a mac to build on yet.

I stuck my code up here: https://github.com/kronok/nativescript-performance-issue (sorry about the .js included)

One thing to note is the Nativescript code I've tested from other repos don't seem to have this issue for me, so there's something up with my simple code. Perhaps a router issue? I mimicked sample-Grocery's routing.

Tested on (emulated) Nexus 4 (api 19), Nexus 5 (api 22), Nexus 6 (api 23), Moto X (api 19) and my own Nexus 5 phone.

Bonus points: Try it out on an API 19 phone. Tends to be a bit crashy at times for such a simple app, especially if you leave it still for a few minutes and then touch something. I think it may be a RadListView issue, though.

**Comment by OscarLopezArnaiz** [comment]
Same issue here. Transitions to new screen - and navigate back- are so sluggish (taking 3-5 secs). Destination window is loaded but it keeps inaccessible behind a kind of white veil for mentioned time.
Here is demo app.
https://github.com/OscarLopezArnaiz/androidNavigation

Thanks

**Comment by eleddie** [comment]
Same here, I need it to be fixed.. We are about to deliver the app :S

**Comment by kronok** [comment]
@OscarLopezArnaiz That "white veil" is a good description for the freezing. I've also had the "Skipping x frames!" warning, but after making it as simple as possible, it seems to have gone away, but making everything super simple obviously isn't a fix. The white veil transition is still there, though.

**Comment by vakrilov** [comment]
Hi guys. 
I guess this is the same issue as NativeScript/NativeScript#2735.
The good news is that the issue is resolved so you can: 
- You can switch to using **@next** version of `tns-core-modules` (just add `"tns-core-modules" : "next"` in your `package.json`) 
- You can wait for the official `2.4.0` release of NativeScript which should come out within a week.

**Comment by OscarLopezArnaiz** [comment]
@vakrilov Definitely a significant improvement in performance when using @next version of` tns-core-modules` :)

Thanks so much!

**Comment by kronok** [comment]
Cool, I'll close this and re-check with 2.4.0.
