### ISSUE TITLE
24 hour date format does not work

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/nativescript-angular#536]
## Problem
The date pipe does not respect the 24 hour format (it always shows 12 hours format)

## Context
Verified on iOS emulator / 9.1

* tns-core-modules: 2.3.0
* tns-ios: 2.3.0

## How to reproduce it
* Create a sample application (tns create Sample --ng) and for example introduce the same:
app.component.ts:
```
import {Component} from "@angular/core";

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public myDate = new Date("Tue Nov 15 2016 21:02:49 GMT-0300 (UYT)");
    ...
}
```

app.component.html
```
<StackLayout>
    ...
    <Label [text]="myDate | date:'d/MMM/yy H:m'"></Label>
    <Label [text]="myDate | date:'d/MMM/yy j:m'"></Label>
</StackLayout>
```

You should see H:m uses 12 hours format instead of 24, check out the screenshot:
![simulator screen shot nov 15 2016 08 13 52](https://cloud.githubusercontent.com/assets/15932965/20303741/a18a08f0-ab0b-11e6-964d-915c2a5381cc.png)

Verified on plain angular just in case and it does work:
<img width="721" alt="screen shot 2016-11-15 at 08 16 13" src="https://cloud.githubusercontent.com/assets/15932965/20303783/d4276136-ab0b-11e6-969c-e815dd1808e6.png">

**Comment by ignaciolarranaga** [comment]
Please note also the 12 hours format is incorrect, even for 'jm' it appears "09 PM02" instead of "9:02 PM", i.e. PM wrongly placed and 09 instead of just 9.

**Comment by NickIliev** [comment]
Hey @ignaciolarranaga 

In Angular2, there are some predefined [DatePipes](https://angular.io/docs/ts/latest/api/common/index/DatePipe-pipe.html) which you can use.
For example:
```
<StackLayout>
    <Label [text]="myDate | date"></Label><!-- output is 'Jun 15, 2015' -->
    <Label [text]="myDate | date:'medium'"></Label><!-- output is 'Jun 15, 2015, 9:43:11 PM' equivalent to 'yMMMdjms' (e.g. Sep 3, 2010, 12:05:08 PM for en-US)-->
    <Label [text]="myDate | date:'short'"></Label><!-- output is '9:43 PM' equivalent to 'yMdjm' (e.g. 9/3/2010, 12:05 PM for en-US) -->
    <Label [text]="myDate | date:'shortTime'"></Label><!-- output is '9:43 PM' equivalent to 'jm' (e.g. 12:05 PM for en-US)-->
    <Label [text]="myDate | date:'fullDate'"></Label><!-- equivalent to 'yMMMMEEEEd' (e.g. Friday, September 3, 2010 for en-US)-->
    <Label [text]="myDate | date:'longDate'"></Label><!-- equivalent to 'yMMMMd' (e.g. September 3, 2010 for en-US) -->
    <Label [text]="myDate | date:'mediumDate'"></Label><!-- equivalent to 'yMMMd' (e.g. Sep 3, 2010 for en-US)-->
    <Label [text]="myDate | date:'shortDate'"></Label><!--  equivalent to 'yMd' (e.g. 9/3/2010 for en-US) -->
    <Label [text]="myDate | date:'mediumTime'" ></Label><!-- equivalent to 'jms' (e.g. 12:05:08 PM for en-US) -->

    <Label [text]="myDate | date:'mmss'"></Label><!--  output is '43:11' -->
</StackLayout>

```

In your case you can create the Date Pipe like this
```
<Label [text]="myDate | date:'dMMMyyHm'"></Label><!--  your example -->
<!-- and the same with formatting-->
<Label [text]="myDate | date:'d/MMM/yy H:m'"></Label><!--  your example -->
```

**Comment by ignaciolarranaga** [comment]
Hi @NickIliev, I might not explain it clearly, if you place this:
`<Label [text]="myDate | date:'d/MMM/yy H:m'"></Label>`
It doesn't show a 24 hour format, but instead the hour in 12 hour format but without the AM/PM

I also include in the same example the other format:
`<Label [text]="myDate | date:'d/MMM/yy j:m'"></Label>`
to show that the variable actually has the right value (21:02)

**Comment by NickIliev** [comment]
@ignaciolarranaga Yes it took me a while to get into the problem but now it is clear - the 24format is not working.Furthermore, I've notice the following at my side (reproducible in both iOS and Android)

if **myDate** is created with `new Date()` the result will be the exact hour but always in 12-hour format.

However, if myDate is created with `new Date("Tue Nov 15 2016 21:02:49 GMT-0300 (UYT)");` it will be parsed as totally wrong date (at my side the result is 16.Nov.2016 02.0249 AM

**Comment by ignaciolarranaga** [comment]
Oh, got it. I didn't notice that, probably with the epoch time would be better to reproduce it (but quite less readable).
I didn't put myDate = new Date() because it will depend on the time you executed :)

**Comment by nsndeck** [comment]
I've just made a fix inside `nativescript-intl` plugin. Version 0.0.5 should be OK.
@ignaciolarranaga Could you please try it on your side. Please note that `nativescript-angular` has dependency to this plugin so you have to install 0.0.5 version before installing `nativescript-angular` (at least with node 6+ it works).

**Comment by radhakrishnan0404** [comment]
thanks @NickIliev it works great

**Comment by mutazmq** [comment]
I had the same issue and the below hack got it right

```
<Label *ngIf="student.created"
    <FormattedString>
        <Span [text]="student.created| date:'d MMM, '" fontWeight="Bold"></Span>
        <Span [text]="student.created| date:'jm'" fontWeight="Bold"></Span>
    </FormattedString>
</Label>
```

**Comment by shaikhspear16** [comment]
I face the same issue. Any fix other than Date Pipes?
I want to display my date as `dd/mm ` and not `dd/mm/yyy`, so DatePipe may not work in my case.

**Comment by sanidz** [comment]
Solution is really simple, just use 'HH' for 24hour format and 'hh' for 12.
`{{"field | date: 'HH.mm'" }}`

@shaikhspear16 
For custom formats just use multiple interpolations like...
`{{myDate | date: 'dd'}}/{{myDate | date: 'MM'}}`

**Comment by faisalSiddiqui03** [comment]
> Solution is really simple, just use 'HH' for 24hour format and 'hh' for 12.
> `{{"field | date: 'HH.mm'" }}`
> 
> @shaikhspear16
> For custom formats just use multiple interpolations like...
> `{{myDate | date: 'dd'}}/{{myDate | date: 'MM'}}`

this solved my issue, thanks. it should have been in the official docs
