### ISSUE TITLE
Allow templateUrl files to be XML files

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#54]
A few of us were confused that `templateUrl` files have to be `.html` files. I get why it works like it does today, but the current setup is hard for us to explain—especially since we tell people we don’t use HTML/DOM/browsers. The `.html` files also screw up tooling, because some editors start suggesting elements like `<div>`.

I’m not sure this is possible, but could we change the integration so that the `templateUrl` property alternatively lets you point at files with a `.xml` extension? Currently if I try to do that I get some bizarre TypeScript error. (`Cannot read property 'localNSMap' of undefined`)

Thanks.

**Comment by jlooper** [comment]
+1 on this. I was shocked, shocked I say, to see an .html file in my {N} workspace. And then the XML snippets in VSCode didn't work... so yes if we can support .xml it will make our 'story' that much more interesting.

**Comment by hdeshev** [comment]
There shouldn't be any code preventing you from naming template files with an .xml extension or something else for that matter. I chose the `.html` extension since Angular templates aren't valid XML either. Should we pick another extension? Maybe something wild like `.nsml` or just `.template`?

**Comment by vakrilov** [comment]
Btw, I tried to rename all the `.html` files in the [qsf-app](https://github.com/NativeScript/qsf-angular-nativescript) to `.xml` and I also go the build time error:
```
Cannot read property 'localNSMap' of undefined
```
I will investigate what is causing it, but if the app is built it should run OK.

**Comment by vakrilov** [comment]
OK - the problem is caused by a XML validation step in the CLI build. As @hdeshev the ng-templates are not valid XML. Good news is that the guys from the CLI already fixed that - with the new version it will just output a warning instead of failing the build.
Renaming `html` files to `nsml` worked, as it does not trigger XML validation.

**Comment by tjvantoll** [comment]
@vakrilov @hdeshev: I confirmed that using `.xml` template files technically works now, however, the warnings you get from the CLI are more than a little annoying. You even see them with `livesync` running.

So my broader question is: what extension do we want to recommend using for templates? If we want to recommend `.xml`, I feel like we should request that the CLI give us some way of opting out of XML validation. I think our other option is to use something like `.nsml`. Thoughts? Also ping @jlooper to get another opinion.

**Comment by hdeshev** [comment]
I think the best option here is `.html`.

- `.xml` causes problems with the CLI, besides those templates are not valid XML anyway.
- `.nsml` will require us to reconfigure every editor and IDE out there, and make it treat it as something containing balanced tags.
- good HTML editors will take care of syntax highlighting, indentation, auto-closing tags, quick navigation, etc for us, even if the tags are more exotic.

**Comment by tjvantoll** [comment]
@hdeshev: You make good points, and I tend to agree. I think `.html` files confuse those of us that use {N} without Angular, but I’m guessing that devs that use {N} for the first time with ng2 won’t find it all that odd. I’ll  make a note to discuss this in the getting started guide.

**Comment by bundyo** [comment]
There is another point you don't take into consideration - what about editors that have both HTML and {N} XML files intellisense? How would they distinguish between the html files?

My opinion is that ```.nsml``` (or whatever we come up with) is probably the best option - for editors with extensions we can easily install a new mime type. For the rest it is really just several clicks in Settings.
