### ISSUE TITLE
How to open 3rd party apps from Nativescript?

### ISSUE THREAD

**Issue by NgSculptor** [NativeScript/nativescript-angular#541]
I was trying to open google maps when user clicks on a link but could not find the necessary documentation, is that currently not possible?

**Comment by PetrPrazak** [comment]
For iOS, see this link: https://developers.google.com/maps/documentation/ios-sdk/urlscheme

**Comment by NickIliev** [comment]
For applications that are using URL scheme, you can use the build in method [openUrl](http://docs.nativescript.org/api-reference/modules/_utils_utils_.html#openurl). 

e.g. 
```
var utils = require("utils/utils");
utils.openUrl('waze://?ll=37.44469,-122.15971&z=10');
```

For iOS there is one additional step and it is to include the name of the app you want to open in your info.plist file as follows:
```
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>waze</string>
</array>

```

Keep in mind that the 3r party application will open only if it is already installed in the device.
