### ISSUE TITLE
Latest version of Nativescript-angular-snapshot without snapshot folder

### ISSUE THREAD

**Issue by williamltb** [NativeScript/nativescript-angular#550]
Download the latest https://registry.npmjs.org/nativescript-angular-snapshot/-/nativescript-angular-snapshot-1.1.3-5.2.361.tgz

Unzip the tgz file and you will notice the snapshot folder with all the .blob files are missing from the platforms/android-snapshot-files

This cause the nativescript-dev-android-snapshot plugin not able to build the android apk correctly. 

Please provide the snapshot files for angular 2.2.0

**Comment by deneshr** [comment]
I too don't see the blob files in https://registry.npmjs.org/nativescript-angular-snapshot/-/nativescript-angular-snapshot-1.3.0-5.2.361.tgz.
Are we supposed to generate the blob files ourselves? If so how?

**Comment by NickIliev** [comment]
nativescript-dev-android-snapshot`` has been deprecated and the latest CLI is now providing a built-in flag for creating Andriod snapshots..
```
tns run android --env.snapshot
````
