### ISSUE TITLE
Support styles and stylesUrl

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#56]
Because you cannot use NativeScript’s “page-specific” CSS approach with Angular 2, I’ve been trying to come up with some way to scope styling to individual components. If we could find some way to support Angular’s `styles` and `stylesUrl` that would be great.

**Comment by matt4446** [comment]
:+1: Yes please. I tried part of this earlier in the week (i think)  
Is this what you mean by Angular's styles? 

`<label (tap)="tapIcon" #item 
         class="ion-icon"
         [style.color]="color"       
         [text]="GetIcon()"></label>`

ORIGINAL EXCEPTION: Error: Not implemented: setStyleProperty

**Comment by nsndeck** [comment]
Support for component specific css (both styles and stylesUrls are supported) is added with commit #68 and is available with `nativescript-angular-0.30` npm version.
