### ISSUE TITLE
nsRouterLink - lets check if we can use routerLink directly

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/nativescript-angular#561]
Currently, we have the [nsRouterLink] attribute, it will be nice if we can use the default [routerLink] name for this and not introduce new names.

Lets' research if this is possible at all.

**Comment by NickIliev** [comment]
This would ease the code-sharing story as well.

**Comment by NickIliev** [comment]
Closing the issue as due to implementation details at this point we are not going to remove the wrapper around `routerLink`
