### ISSUE TITLE
A problem with change detection on dialog close

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-angular#573]
Component bindings do not update on dialog close.

Version: nativescript-angular@1.2.0, angluar@2.2.1

Example:
https://github.com/NativeScript/tests-app-ng/blob/master/app/modal/modal-dialogs/modal-dialog.component.ts#L65

**Comment by hdeshev** [comment]
This turned out to be the expected behavior when using `ChangeDetectionStrategy.OnPush`. The recommended solution is to explicitly schedule a change detection pass:

```typescript
this.modal.showModal(ModalContent, options).then((res: string) => {
    this.result = res || "empty result";
    this.cdRef.markForCheck();
});
```
