### ISSUE TITLE
[Bug] onLoaded-Event fired before PropertyChange-Event

### ISSUE THREAD

**Issue by flexxis** [NativeScript/nativescript-angular#574]
If I integrate a NS-Core custom component into NS-Angular (like [here](http://docs.nativescript.org/angular/plugins/angular-third-party.html)) the behaviour of onLoaded- and PropertyChange-Event seems to be different from the behaviour in plain NS-Core.

As test project I just took the created samples from `tns`, once with Angular, once with Core/Typescript. Then I defined a custom component in the template.

NG-Core template:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:test="test-view" navigatingTo="navigatingTo">
    <StackLayout class="p-20">
        <test:TestView user="{{user}}"></test:TestView>
    </StackLayout>
</Page>
```

NS-Angular template:
```
<StackLayout>
    <TestView [user]="user"></TestView>
</StackLayout>
```

`registerElement("TestView", () => require("./test-view").TestView);`

Custom NS-Core component:
```
export class TestView extends stackLayout.StackLayout {

    public static userProperty = new Property(
        "user",
        "TestView",
        new PropertyMetadata(null, PropertyMetadataSettings.None, TestView.onMyPropertyChanged)
    );

    private static onMyPropertyChanged(eventData: PropertyChangeData) {
        var myClassInstance = <TestView>eventData.object;
        console.log("onMyPropertyChanged " +
            myClassInstance.toString() +
            " property: " + eventData.property.name +
            ", oldValue: " + JSON.stringify(eventData.oldValue) +
            ", newValue: " + JSON.stringify(eventData.newValue));
    }

    public get user(): User {
        return this._getValue(TestView.userProperty);
    }

    public set user(newUser: User) {
        this._setValue(TestView.userProperty, newUser);
    }

    constructor() {
        console.log("testView : constructor");
        super();
    }

    onLoaded() {
        console.log("testView : onLoaded");
        console.log("testView : onLoaded: user: " + JSON.stringify(this.user));
    }

}

export class User {

    constructor(public name: string) { }
}
```

The console log of onLoadedEvent-hook and onPropertyChanged-hook is as follows:

NS-Core:
> JS: testView : constructor
> JS: onMyPropertyChanged TestView [...] property: user, oldValue: null, newValue: {"name":"John Doe"}
> JS: testView : onLoaded
> JS: testView : onLoaded: user: {"name":"John Doe"}

I expect the properties to be fully initialized when the `onLoaded`-hook is invoked, so this seems to work fine.

NS-angular:

> JS: testView : constructor
> JS: testView : onLoaded
> JS: testView : onLoaded: user: null
> JS: onMyPropertyChanged TestView(5) property: user, oldValue: null, newValue: {"name":"John Doe"}

This is inconsistent to the former case and leads to initialization problems when integrating custom NS-Core components in NS-Angular.

**Comment by hdeshev** [comment]
This happens because the Angular renderer adds the element to the visual tree (hence firing the `loaded` event) before setting properties.

You have several options:
1. Move initialization to property setters or change callbacks and do it when you have all the data.
2. Use the Angular `ngOnInit` callback. You can wrap your "vanilla" {N} view implementation with an Angular component, if needed.

**Comment by flexxis** [comment]
Thanks for your quick answer.

As my `TestView` stands for an external component, i cannot take your first mentioned approach, but the second one sounds promising.
So I would be interested to know what is the preferred way to "wrap your "vanilla" {N} view implementation with an Angular component".

By that do you mean creating the custom component programmatically instead of registering it in the Angular template with `registerElement` ?

```
@Component({
    ...
})
export class AppComponent implements AfterViewInit, OnInit {

    user: User = xxx;

    ngOnInit() {
        // create custom component
        let testView: TestView = new TestView();

        // set properties custom component  
        testView.user = this.user;

        // get reference to layout container
        let myLayout = (<StackLayout>this.templateContainer.element.nativeElement.parent);
        myLayout.addChild(testView);
    }
}
```

**Comment by hdeshev** [comment]
> By that do you mean creating the custom component programmatically instead of registering it in the Angular template with registerElement ?

I meant that you should both `registerElement` it, and create a component (or a directive for that matter) with a selector matching that same element. Or have another component that creates your element in its template. Of course, your wrapper will need to export an NgModule that exports the component/directive.

**Comment by flexxis** [comment]
OK, now an example would be kind.
Perhaps to clarify things: I am dependent on an external NS Core component (that's my `TestView`). It defines an `onload` lifecycle hook, which has to be invoked with properties fully initialized.

I have tried your proposal with a directive wrapper:

```
...
registerElement("TestView", () => require("./test-view").TestView);
...


@Directive({
    selector: 'TestView',
})
export class TestViewDirective implements OnInit {
    
@Input() user : User;

constructor() { 
        console.log("TestView NG-Component: constructor");
    }

    ngOnInit() { 
        console.log("TestView NG-Component: ngOnInit");
    }
}
```

Unfortunately, onLoaded is  still invoked with user not set, see below.

```
JS: testView NS-Core: constructor
JS: TestView NS-NG: constructor
JS: testView NS-Core: onLoaded: user: null
JS: TestView NS-NG: ngOnInit: user : [object Object]
```

The only solution that worked was to create `TestView` programmatically, because properties can be set before the view is added to the visual tree via `addChild`.

I think, creating a view programmatically is ugly and I really wanna understand how to develop NativeScript Angular in the best way.

**Comment by flexxis** [comment]
Having read the source code for [TabView NS-Angular](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/directives/tab-view.ts) and [NS Core TabView ](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/tab-view/tab-view.android.ts) i would come to the conclusion that you cannot use properties set in an Angular template in `onLoaded` or `_createUI` (Android) methods . The only way i found out was to initialize the view programmatically.

From my side it would be much clearer if you could map the NS-Angular `ngOnInit` lifecycle to the NS-Core `onLoaded` / `createUI` lifecycle. Then you had consistency with the existent NS-Core concepts.
But I don't know how much effort would be that.

Would appreciate your opinion on this, because I think this would confuse people switching over to NS Angular (including me ;-))
