### ISSUE TITLE
[(ngModel)] numeric inputs are passed as string values to TypeScript's numeric properties

### ISSUE THREAD

**Issue by tuncaya** [NativeScript/nativescript-angular#577]
I am testing a simple calculator which should sum 2 numbers but it concatanates them although I declare properties with type definitions. 

It's OK if I code as `+this.number1 + +this.number2`. But isn't there any way to pass them from `[(ngModel)]` to typescript class as numeric values?

I have researched but cannot find anything. Am I missing something?

**app.component.html**
```html
...
<TextField hint="Number 1" [(ngModel)]="number1" keyboardType="number"></TextField>
<TextField hint="Number 2" [(ngModel)]="number2" keyboardType="number"></TextField>
<Button text="Calculate" (tap)="calculate()"></Button>
...

```
**app.component.ts**
```javascript
...
public number1: number = 0;
public number2: number = 0;
public result: number = 0;

calculate(){
        this.result = this.number1 + this.number2;
        // if I code this as "this.result = +this.number1 + +this.number2;" it is working.
}
...
```

[stackoverflow](http://stackoverflow.com/questions/41007924/angular2-ngmodel-numeric-inputs-are-passed-as-string-values-to-typescripts)

**Comment by tsonevn** [comment]
Hi @tuncaya, 

Thank you for your interest in NativeScript Angular2.
In NativeScript `TextField` expects to receive string and in your case  numbers will be converted to string. One possible solution is to use `parseInt(<string>)` method, to convert the value to int. I am also attaching sample code, related with your scenario.

app.component.html
```
<StackLayout class="p-20">
    <TextField hint="Number 1" [(ngModel)]="number1"  keyboardType="number"></TextField>
    <TextField hint="Number 2" [(ngModel)]="number2" keyboardType="number"></TextField>
    <Button text="Calculate" (tap)="calculate()"></Button>
</StackLayout>
```
app.component.ts
```
import { Component } from "@angular/core";

@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
    public number1: string = "0";
    public number2: string = "0";
    public result: number = 0;

    calculate(){
            this.result =parseInt(this.number1) + parseInt(this.number2);
            console.log(this.result)
    }
}
```

Hope this helps.

**Comment by tuncaya** [comment]
Hi @tsonevn,

I thank you for developing NativeScript Angular2.
I just thought whether it is possible without needing to cast to Integer after passing or not. e.g. `<TextField dataType="numeric" ...` It is not vital by the way :)

I know TypeScript (typed) is transpiled to CommonJS (not typed) and NativeScript communicate with CommonJS or pure JS. So NativeScript doesn't know what is the actual type of the value provided with TextField. 

Thank you for the answer.

**Comment by tsonevn** [comment]
HI @tuncaya,

Thank you for writing us back

NativeScript TextField is a common abstraction over iOS `UITextField` and Android's `EditText`. The both native component expects to receive string value and will also return string value. This behavior has been related with the iOS and Android platform. Regarding to that, you could open new issue [here](https://github.com/NativeScript/NativeScript/issues) , where you could described your feature request. If there is interest, we will research, whether it is possible in the native world and if it is possible, we will implement it in the NativeScript.

Regards,
@tsonevn

**Comment by radhakrishnan0404** [comment]
boss this is not working

**Comment by tsonevn** [comment]
@radhakrishnan0404,
Could you provide some more info about your case and about your environment(CLI, node, modules versions)? It will help if you also send us some sample project or code snippets, which could be used for debugging.

**Comment by yahiyaiqbal** [comment]
{{ number1*1 +number2*1 }}

You can also use binding to do this. Hope this also helps.

**Comment by sapabg** [comment]
If you use type="number" on the input it will not return it as string.

**Comment by Creed-1** [comment]
it concatinates {{ number11 +number21 }}

**Comment by Sachin124** [comment]
Simply you can achieve this using JS Number function to convert it into Number
https://www.w3schools.com/jsref/jsref_number.asp
