### ISSUE TITLE
nativescript-angular@next currently breaks angular-seed-advanced

### ISSUE THREAD

**Issue by schaermu** [NativeScript/nativescript-angular#582]
The latest @next dist-tag on npm completely breaks [angular-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced). This is the related stack-trace:

```
1   0x108cc45dc -[TNSRuntime executeModule:referredBy:]
2   0x10576cd02 main
3   0x10aaf792d start
Dec  8 05:35:59 MacBook-Pro-2 nativescript[60102]: 4   0x1
Dec  8 05:35:59 MacBook-Pro-2 com.apple.CoreSimulator.SimDevice.AA4409B4-8F5C-4E1F-A991-59669D34BA6A.launchd_sim[52791] (UIKitApplication:**.**.**.**.**[0xecd4][60102]): Service exited due to signal: Segmentation fault: 11
file:///app/app.ts:2:0: JS ERROR SyntaxError: Importing binding name 'categories' is not found.
```
After some investigation, i think i isolated the related commit on nativescript-angular: 0b2c6449b3fdfe9faa4448b1b2a42c42a0c0b92, more specifically the changes related to the main barrel-roll file `nativescript-angular/index.ts` and `nativescript-angular/initial-imports.js`.

Since i have no clue about the exact inner workings of NativeScript, i can't be of any further help. Maybe @NathanWalker can jump in with an idea or suggestion.

**Comment by lovetofail** [comment]
Me too. Using  "version": "1.3.0-2016-12-08-1148" and can't get to work "seed advanced" and other projects for android.
App log http://pastebin.com/vpN11sty

**Comment by millea1** [comment]
same here...version 1.3.0-2016-12-08-1148

**Comment by NathanWalker** [comment]
This is fixed on master of seed as of tonight, please close this issue. In future please report issues like these on seed repo :)
