### ISSUE TITLE
Array.create is not a function (animation)

### ISSUE THREAD

**Issue by matt4446** [NativeScript/nativescript-angular#59]
Tested on Android. 

This appeared to have worked week in my project, but not anymore (quite a few updates everywhere, so not certain when it broke)...

![angular-nativescipt-array create](https://cloud.githubusercontent.com/assets/1550939/12876701/6179548c-cdfd-11e5-8ec2-c18bb43947bd.png)

... and I've reproduced it in the hello world sample app (added a button to create an animation) 
![angular-nativescipt-array create-sample-app](https://cloud.githubusercontent.com/assets/1550939/12876710/9f083a34-cdfd-11e5-9c25-95681a72c7f3.png)

[repo](https://github.com/matt4446/template-hello-world-ng)

[source file](https://github.com/matt4446/template-hello-world-ng/blob/master/app/app.component.ts)

Thanks, 
Matt

**Comment by hdeshev** [comment]
The angular renderer requires a tns-core-modules build off the master branch (not the official release). It seems we're using a feature there that isn't available in the official release of the Android runtime.

You could wait for our official 1.6.0 release (due in a couple of weeks) or you can try this unofficial Android runtime build: http://sh.deshev.com/npm/tns-android-1.6.0-2016.2.8.1.tgz

**Comment by matt4446** [comment]
Thanks @hdeshev, unofficial does sound more interesting. ;)
