### ISSUE TITLE
Getting error while using iOS Module

### ISSUE THREAD

**Issue by mohitgorakhiya** [NativeScript/nativescript-angular#592]
I want to fetch iOS device vendor ID and I found 1 module for this.
**tns plugin add nativescript-ios-uuid**
I have install this and when trying to fetch UUID using below code 
**var plugin = require("nativescript-ios-uuid"); 
var uuid = plugin.getUUID(); 
console.log("The device UUID is " + uuid);**
 
 then I am getting below error
CONSOLE ERROR
file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:344:22: 
Error: Uncaught (in promise): TypeError: UIDevice.currentDevice is not a function. (In 'UIDevice.currentDevice()', 'UIDevice.currentDevice' is an instance of UIDevice)

I have searched a lot but not found any useful solution.
Can anyone help me out to solve this issue?

I have found 1 in built way to get uuid but for iOS on every reinstall it will change, but I want same every time.

**Comment by hamorphis** [comment]
@mohitgorakhiya I will take a look. The plugin might need to be updated. Stay tuned.

**Comment by mohitgorakhiya** [comment]
Ok thanks for your reply.
Wating for the solution.

Thanks,
Mohit

**Comment by hamorphis** [comment]
@mohitgorakhiya It is a bug: https://github.com/hamorphis/nativescript-ios-uuid/issues/5
I will try to fix it today and publish a new version.

**Comment by mohitgorakhiya** [comment]
ok fine.

**Comment by hamorphis** [comment]
@mohitgorakhiya I released v1.0.0: https://www.npmjs.com/package/nativescript-ios-uuid. Please, give it a try and let me know if something does not work properly.

**Comment by mohitgorakhiya** [comment]
I think it will work but when I have tried to use in my code using installing latest module then I got below error:
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): ReferenceError: Can't find variable: SAMKeychain

**I have installed module using "tns plugin add nativescript-ios-uuid"**
and then used below code:
**import { getUUID } from "nativescript-ios-uuid";
let uuid = getUUID();
console.log(`>>> uuid: ${uuid}`);**

But when I tried your sample code then it works fine.
