### ISSUE TITLE
SO_NOAPNFALLBK failed: Protocol not available [iOS 10.x]

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#593]
_From @tbehunin on December 14, 2016 5:56_

Going through the Nativescript tutorial which uses sample-Groceries repo. Hitting what appears to be a bug somewhere when testing out Chapter 4.3 ListView (http://docs.nativescript.org/angular/tutorial/ng-chapter-4#43-listview). After logging in, the code attempts to make an http request out to return a list of groceries. However, an exception occurs and this is what gets logged out:
```
[] nw_host_stats_add_src recv too small, received 24, expected 28
[] __nwlog_err_simulate_crash simulate crash already simulated "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
[] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace:
	        [x86_64] libnetcore-856.20.4
	    0   libsystem_network.dylib             0x000000010fa6d682 __nw_create_backtrace_string + 123
	    1   libnetwork.dylib                    0x00000001106aa932 nw_socket_add_input_handler + 3100
	    2   libnetwork.dylib                    0x00000001106884f4 nw_endpoint_flow_attach_protocols + 3768
	    3   libnetwork.dylib                    0x0000000110687511 nw_endpoint_flow_setup_socket + 563
	    4   libnetwork.dylib                    0x0000000110686270 -[NWConcrete_nw_endpoint_flow startWithHandler:] + 2612
	    5   libnetwork.dylib                    0x00000001106a144d nw_endpoint_handler_path_change + 1261
	    6   libnetwork.dylib                    0x00000001106a0e7c nw_endpoint_handler_start + 570
	    7   libnetwork.dylib                    0x00000001106b8ae5 nw_endpoint_resolver_start_next_child + 2240
	    8   libdispatch.dylib                   0x00000
```

Anyone know what's happening here?

_Copied from original issue: NativeScript/sample-Groceries#194_

**Comment by NickIliev** [comment]
Hey @tbehunin  those are just warning not errors so you can continue working - thank you for reporting this. We will investigate and come back with more information.

**Comment by NickIliev** [comment]
Reproducible also with HTTP examples from sdk app [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/http)

**Comment by tbehunin** [comment]
@NickIliev When I press the "Sign In" button (from the sample-groceries repo), it attempts to make that request and fails. However, the app continues with routing, pushing a new page (list view) into view which, instead of showing a list of groceries, shows an empty list.

**Comment by NickIliev** [comment]
Hey @tbehunin I have tested the app recreating every step up to chapter 4.3 and indeed the error is shown in your terminal but still the app manage to make connection to the backend and get the list of groceries. In order to get an actiual list of groceries you will need to use the demo account made for this step which is as follows:
```
username: user@nativescript.org
password: password
```

And the list will appeear after a second ro so.

[Here](https://github.com/NickIliev/sample-Groceries/tree/chapters/4.3) you can find my step-by-step recreation of the tutorial up to chapter 4.3 (included)

**Comment by tbehunin** [comment]
Interesting - thanks for following up @NickIliev! Do you know the reason why my own account won't work?

**Comment by NickIliev** [comment]
@tbehunin there might be different reasons for your result blank page. At this point in the article if you use your own credentials they will lead to you to emtpy list so you should use the credentials provided in the tutorial ("user@nativescript.org" and "password") as these credentials are already populated thorugh th final version of the application. You can try my applicaiton to se eif it is loading.
