### ISSUE TITLE
Question - Is there an on-release event for touch events in Nativescript Angular?

### ISSUE THREAD

**Issue by tskweres** [NativeScript/nativescript-angular#602]
The docs show how to use (touch) in the HTML to specify a touch event, but how do I fire a (release) event?

Thanks.

**Comment by NickIliev** [comment]
Hi @tskweres 

For the touch event you have a property called [action](http://docs.nativescript.org/api-reference/interfaces/_ui_gestures_.touchgestureeventdata.html#action) which returns **up**, **down**, **move** and **cancel**.

e.g.:

**_page.xml_**
```
    <FlexboxLayout (touch)="onTouch($event)">
        <Label class="h2" text="Test text'"></Label>
    </FlexboxLayout>
```

**_page.ts_**
```
import { TouchGestureEventData } from "ui/gestures";
export class ItemDetailComponent {
    onTouch(args: TouchGestureEventData) {
        console.log(args.action);
    }
}
```

**Comment by tskweres** [comment]
works perfectly, thank you!

**Comment by alexhribsek** [comment]
Thank you very much @NickIliev ❤️ This way I can finally self-implement RadListView item reorder cancellation event 😃
