### ISSUE TITLE
Http issue on iOS with final release of Angular 2

### ISSUE THREAD

**Issue by genesis06** [NativeScript/nativescript-angular#604]
Hi, I'm trying to get some information using a service and when I run the iOS emulator for testing the service, and I get this message: Response with status : 200 for URL: null. Now I'm using the 2.4.2 Nativescript current and latest version.

And also I changed the Info.plist file. Here is my service code:
```
getRecords(stringUrl:string){`
//Asign Headers
let headers = new Headers();
headers.append("Content-Type", "application/json");
headers.append("Authorization", "Bearer: "+ this.config.loginToken);
// Returns observable with API answer
return this.http.get(
this.config.qqcURL +"/records?from_date=2016-11-22T00:00:00&to_date=2016-12 22T23:59:59&tags=Testing&durop=>=&startduration=00:00:00",
{headers : headers}
)
.map(response => response.json())
.map(data => {
let searchList = [];
data.Result.forEach((item) => {
if(item.session_status==1){
searchList.push(new Record(item.startdate,
item.duration, item.inbound,item.outbound,
item.common_id, item.score_avg, item.my_score,
item.id,item.tags));
}
});
return searchList;
},
err => console.log(err))
}
```
And my Info.plist file here:

![captura de pantalla 2016-12-22 a la s 11 55 34 a m](https://cloud.githubusercontent.com/assets/18293999/21438439/819a897e-c84e-11e6-9691-e5540f7594c6.png)

There is something similar on this closed issue https://github.com/NativeScript/nativescript-angular/issues/457 but it doesn't work for me.
Please, If you could help I would be so gratefull.

**Comment by NickIliev** [comment]
@genesis06 From your posted code snippet it is not clear from where you are receiving this message.
The HTTP status is 200 (OK) so you have successfully made a request to your server. Then you ar pushing all the needed info in an array called **_searchList_** and returning that array.  Can you elaborate where **URL: null** is coming from!?

**Comment by eleddie** [comment]
Hola @genesis06. I've had that problem before and it's for sure that the problem is the lack of SSL certificate. iOS is very annoying with that. I also tried to add it to the Info.plist and it didn't work for me either...
Anyways, have you tried to make a request from android or (i.e.) postman and it works? Just to make sure that the problem is the insecure request in iOS

**Comment by genesis06** [comment]
Hi @NickIliev and @eleddie, thanks for your reply, and sorry for replying you a little late.

Fortunately I found where was the problem. It wasn't related with the SSL certificate because the API is not running on HTTPS.

That "Response with status : 200 for URL: null" message was because of an encoding problem. There were invalid characters used on the URL:  "<" (less than), and  ">" (greater than). So I used  "%" + the character ascii code, to fix it.

Finally, my URL seems like: 

this.config.qqcURL +"/records?from_date=2016-11-22T00:00:00&to_date=2016-12 22T23:59:59&tags=Testing&durop=%3E%3D&startduration=00:00:00"

instead of

this.config.qqcURL +"/records?from_date=2016-11-22T00:00:00&to_date=2016-12 22T23:59:59&tags=Testing&durop=>=&startduration=00:00:00"

Thank you so much.
Kind regards 😃
