### ISSUE TITLE
Get Device Current Name

### ISSUE THREAD

**Issue by mohitgorakhiya** [NativeScript/nativescript-angular#605]
Hello,

In iOS if we want device name then we can get using `[[UIDevice currentDevice] name]`
This same thing I want in Nativescript-Angular, so any idea about how we can achieve this?
Waiting for reply....

**Comment by tsonevn** [comment]
Hi @mohitgorakhiya,
Information about the current device and screen could be get by using NativeScript [Platform Module](https://docs.nativescript.org/cookbook/platform). For your case you should use utils modules and to get this info as it has been shown in the snippet below:
```
import * as utils from "utils/utils";

class DeviceInfo {
    constructor() { 
        console.log("Device name");
        console.log(utils.ios.getter(UIDevice, UIDevice.currentDevice).name);
 
    }
}
```
For further help you could review the sample app [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/platform/platform-module-example/platform-module-example.tsc).

**Comment by mohitgorakhiya** [comment]
Ok thank u so much for ur reply,
I will try this one,
Any idea about to get device name of android device?

**Comment by sis0k0** [comment]
Hi @mohitgorakhiya,
For Android you can simply use `android.os.Build.MODEL`. You will need to add the following reference to your `references.d.ts`:
``` typescript
/// <reference path="node_modules/tns-platform-declarations/android.d.ts" />
```

Also, you can check out [this article](https://docs.nativescript.org/core-concepts/accessing-native-apis-with-javascript).
