### ISSUE TITLE
Build ipa for iOS Developement

### ISSUE THREAD

**Issue by mohitgorakhiya** [NativeScript/nativescript-angular#613]
Hi,

I want to make archive for iOS Devices using development profile.
I have taken it from platforms-->ios-->build-->device here there is ipa file and now I have added file in iTunes LIbrary and trying to install in iPhone7 Plus.
But it gives iTunes Sync error (-54).
While its working in other devices iPod, iPhone 5S with same way installing.
So can you tell me I am doing anything wrong to make build for development or some issue with iTunes or iPhone7 plus?
iPhone7 Plus UDID also there is in the Development Profile.

Waiting for reply...

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-cli#2378
