### ISSUE TITLE
Datepicker ngModel not working only on IOS

### ISSUE THREAD

**Issue by SamuelGRwebfab** [NativeScript/nativescript-angular#618]
I have a simple date picker which, on android, works as it should using ngModel. When the user selects a new day, month, or year, the value of date changes to the selected date. However on IOS the variable date remains undefined no matter what I do.

This is a link to a (public) repo with the issue shown - https://github.com/SamuelGRwebfab/datePickerIOS.git

I ran this project using an emulator as to not have to worry about signing. However this issues does persist on devices.

I have done quite a bit of research and have been unable to find a reason behind this. Which leads me to believe it is a bug and not an issue on my end.

If you need any more info about this issue please let me know!

**Comment by devna13** [comment]
**nativescript-timedatepicker** works for me...

[https://github.com/AntonioCuevaUrraco/nativescript-timedatepicker](https://github.com/AntonioCuevaUrraco/nativescript-timedatepicker)

**Comment by tsonevn** [comment]
Hi @SamuelGRwebfab, 

Thank you for the sample project. 
I reviewed your code and found that you have missed to add `NativeScriptFormsModule` in the `imports` in `app.modules.ts` file, which has been related with data binding. I am attaching example below:

app.modules.ts
```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/platform";
import { NativeScriptFormsModule } from "nativescript-angular/forms";

import { AppComponent } from "./app.component";

@NgModule({
    declarations: [AppComponent],
    bootstrap: [AppComponent],
    imports: [NativeScriptModule, NativeScriptFormsModule],
    schemas: [NO_ERRORS_SCHEMA]
})
export class AppModule { }
```

Hope this helps.

**Comment by SamuelGRwebfab** [comment]
Hello @tsonevn,

I must have forgotten to add  this module to the demo project. However I do have this on my actual app, which is still experiencing this issue. Would you have any idea what else could be causing this issue?

**Comment by tsonevn** [comment]
Hi @SamuelGRwebfab, 

Adding the `NativeScriptFormsModule` seems to resolve the problem in your sample project. Could you tested again and to verify whether it will work for you. Could you also give us more info about the device or emulator, which you use for testing?

Regards,
@tsonevn

**Comment by SamuelGRwebfab** [comment]
@tsonevn 

It does resolve the issue on my sample project. I must have something wrong with my main project that is causing this issue. Any ideas as to what it could be? I am testing my project on an iphone 5

**Comment by tsonevn** [comment]
Hi @SamuelGRwebfab, 

Could you provide some more info about your project and the way you are using `Datepicker` in it?

Regards,
@tsonevn
