### ISSUE TITLE
ListView.scrollToIndex only works on loaded event

### ISSUE THREAD

**Issue by chimon2000** [NativeScript/nativescript-angular#625]
**Overview of Issue**

Inside of a component, when attempting to call ListView.scrollToIndex after load, the UI does not update.

**Use Case**
I have a simple scrolling function inside of my Angular component `scrollToBottom`

````
    scrollToBottom() {

        this.listView.scrollToIndex(this.messages.length - 1)
        this.listView.refresh()
    }
````

Scroll works successfully on the`loaded` event for the ListView, however when I try to use the`setupView` event it does not. I also have tried using`ngOnChanges` event of my component and calling the method without success.

**Telerik NativeScript version(s)**
* CLI Version: 2.4.1
* Android Version: 2.4.1
* Target Platform: Android

**Similar Issue**
#451  references a similar issue in which @bdauria cannot execute the scroll when using`setupView` because the view of the item hasn't been setup.

**Comment by NickIliev** [comment]
Hello @chimon2000 

I have tested the described scenario and on my side, it works as expected.
[Here you can find a sample project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/nativescript-angular/issue_625) that recreates a list-view and scrollToBottom functionality.

**Comment by chimon2000** [comment]
@NickIliev after some deliberation I was able to figure out the issue. I was not binding to the initial array but rather to a copy:

`[items]="items.slice().reverse()"`

Not 100% sure why that would cause the scroll method to act weird, but once I removed "slice" everything worked as intended. This issue can be closed.
