### ISSUE TITLE
tns livesync android --emulator --watch 

### ISSUE THREAD

**Issue by rhernandez-itemsoft** [NativeScript/nativescript-angular#626]
if you not include model or service on your project this found. :)
Buty if you add one model o one service on execute tns livesync android --emulator --watch this return an error.
I tried  with typescript 2.0.3, 2.0.10, 2.1.4
and 
**npm -v**  
4.1.1

**nodejs - v** 
6.9.4

**ng -v**
angular-cli: 
1.0.0-beta.24
node: 6.9.4
os: linux x64
@angular/common: 2.3.1
@angular/compiler: 2.3.1
@angular/core: 2.3.1
@angular/forms: 2.3.1
@angular/http: 2.3.1
@angular/platform-browser: 2.3.1
@angular/platform-browser-dynamic: 2.3.1
@angular/router: 3.3.1

.. and i get this error:

![captura de pantalla de 2017-01-10 14-37-15](https://cloud.githubusercontent.com/assets/4327356/21823798/53277e14-d742-11e6-8571-54cfe4b52db2.png)

**Comment by kazemihabib** [comment]
increase the max amount of watches : 
http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc

**Comment by rhernandez-itemsoft** [comment]
It's OK :) Thank you!
