### ISSUE TITLE
ngIf directive breaks ListView functionality

### ISSUE THREAD

**Issue by Green-Cat** [NativeScript/nativescript-angular#638]
If any items are added to a listview with an ngIf directive after the view has loaded, they will all be displayed as identical to the first item in the listview. Example code for reproduction:
```
  <ListView [items]="messages" >
      <template let-item="item">
            <TextView
              editable="false" 
              [text]="item.content"
              textWrap="true"
              *ngIf="item.type == 1"></TextView>
      </template>
    </ListView>
```
Add an extra item to messages array after the load of the view.
The ngSwitch directive seems to exhibit the same bug as ngIf above.

Edit: I ended up using template selectors to solve my issue, but there might be use cases where that won't help.

**Comment by triniwiz** [comment]
You don't need to use `*ngIf` if you want to use multiple templates there is something built in for this you should look at this
