### ISSUE TITLE
Failed to find Angular2 own created module

### ISSUE THREAD

**Issue by dgomezs** [NativeScript/nativescript-angular#642]
hi everyone, 

I'm trying to setup a nativescript-angular app using a module I created myself. The app compiles fine but when executing I get an error that the module cannot be found 

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "test-angular-2-module", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:159)
    com.tns.Module.resolvePath(Module.java:60)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:514)
    com.tns.Runtime.run(Runtime.java:509)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    an
```

You can see the module declaration here 

https://github.com/dgomezs/test-angular2-module

and the mobile app which is the default just importing my module 

https://github.com/dgomezs/test-mobile-app

Some info about my environment

tns --version --> 2.4.2
node -v --> 7.4.0
npm --version --> 4.0.5

Any idea what is wrong with my setup or with the module configuration? I want my modules to be compatible with nativescript and a Angular2 web app so i can reuse as much as code as possible.

Thank you very much in advanced. 
Best
David

**Comment by hdeshev** [comment]
Your external module needs some changes to get this working:
- Add a `main` key to your package.json. That will get the `require` implementation to resolve the module properly.
- Your [index.js](https://github.com/dgomezs/test-angular2-module/blob/master/dist/index.js) is an ES6 module, which isn't supported by the NativeScript runtimes. Tell TypeScript to target ES5 modules.

**Comment by dgomezs** [comment]
@hdeshev thank you very much. It's working now
