### ISSUE TITLE
BUG - Lazy Loaded Modules break pageTransition specifications

### ISSUE THREAD

**Issue by tskweres** [NativeScript/nativescript-angular#643]
Please view my example implementation using the Lazy Ninjas tutorial:

https://github.com/tskweres/lazy-load-transitions-bug

if you clone and run the app on IOS, you will notice I have 3 states:

1. Home ( loaded on init )
2. Ninjas ( lazy loaded with loadChildren )
3. Settings ( lazy loaded with loadChildren )

In the component.html of Home & Ninjas, I specify a pageTransition of 'curlDown'. From Home to Ninjas route the transition works, but from Ninjas to Settings route you will see that I get the default transition of slide from left to right.

**Comment by patrickpereira** [comment]
Here's a fix: https://github.com/NativeScript/nativescript-angular/pull/637

**Comment by tskweres** [comment]
I'm still seeing this bug after the 2.5 release. My steps are:

1. clone repo
2. change package.json to nativescript-angular 1.4, and tns-core-modules 2.5.0
3. tns platform add ios
4. tns run ios

the transition bug is still there. Any ideas?

**Comment by lfabreges** [comment]
It works for me. Can you uninstall the app of the device or emulator before trying again on a fresh install ?

**Comment by tskweres** [comment]
Hmm i tried running tns update next and I get this weird error: Could not update the project!

Can you send me your package.json so I can make sure which of the latest I need?

**Comment by tskweres** [comment]
So i uninstalled and reinstalled nativescript globally, now I'm able to run tns update next. Here's what my package.json looks like before running tns run ios:

`
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.lazyNinjas",
    "tns-android": {
      "version": "2.5.0"
    },
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "nativescript-angular": "1.3.0",
    "nativescript-telerik-ui": "^1.5.1",
    "nativescript-theme-core": "1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.5.0"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "~2.1.0",
    "zone.js": "~0.7.2"
  }
}
`

**Comment by lfabreges** [comment]
Now you need to update nativescript-angular to 1.4.0

**Comment by tskweres** [comment]
Money! Not only did I have to update to nativescript-angular 1.4.0, but I also needed to run tns update next. My final package.json that worked:

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.lazyNinjas",
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "nativescript-angular": "1.4.0",
    "nativescript-telerik-ui": "^1.5.1",
    "nativescript-theme-core": "1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "5.0.0-beta.12",
    "tns-core-modules": "^2.6.0-2017-02-03-5543"
  },
  "devDependencies": {
    "babel-traverse": "6.18.0",
    "babel-types": "6.18.0",
    "babylon": "6.13.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "~2.1.0",
    "zone.js": "~0.7.2"
  }
}
