### ISSUE TITLE
POST mutipart/form-data actually sends application/json

### ISSUE THREAD

**Issue by dgomezs** [NativeScript/nativescript-angular#644]
hi everyone, 

I'm having problems making a POST request for multipart/form-data. I have set up a sample app here 

https://github.com/dgomezs/test-mobile-app

This is the code I use for the POST 

```
        let fd = new FormData();
        fd.append("name", "David");
        this.http.post("https://httpbin.org/post", fd).subscribe((r) => {
            console.error("Response " +  JSON.stringify(r.json()));
            alert("Form submitted with values " + JSON.stringify(r.json().form));
        }, (error) => {
            console.error("Response " + error.json());
            alert("Error in form " + error.json());
        });
```

It is the default app but making a POST request to https://httpbin.org/post when you tap on the button. 

Making a normal POST request to the service gives you the output echoed. 

`curl --request POST --url https://httpbin.org/post --header 'content-type: multipart/form-data' --form name=David`

```
{
  "args": {}, 
  "data": "", 
  "files": {}, 
  "form": {
    "name": "David"
  }, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "144", 
    "Content-Type": "multipart/form-data; boundary=------------------------2036a8885103dc31", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.47.0"
  }, 
  "json": null, 
  "url": "https://httpbin.org/post"
}

```

However when the same request gets done through the app the form field is empty. This is the same result you get if you submit "application/json" to the post service so my guess is that the http post is actually submitting application/json content instead of multipart/form-data. 

I have made a test with a web app developed in Angular2 and I don't have the same issue. 

Any thoughts?
Thank you in advanced.

**Comment by hdeshev** [comment]
I think Angular doesn't set content types by default. I got to the [setDetectedContentType](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts#L153-L180) method and it doesn't seem to check if the payload is a FormData object.

You should probably set your request content type via the HTTP request options API:
https://angular.io/docs/ts/latest/guide/server-communication.html#!#override-default-request-options

**Comment by dgomezs** [comment]
hi @hdeshev  I have tried setting directly the headers with multipart/form-data type but it still does not work. 

It seems that it is actually a problem with nativescript itself https://github.com/NativeScript/NativeScript/issues/59

I have changed to application/x-www-form-urlencoded and everything is working fine on my side.

**Comment by kakoma** [comment]
This is likely an Angular issue. There's more on it here: https://github.com/angular/angular/issues/15441
Multipart forms are sent with content-type set to application/json

**Comment by prawin2k** [comment]
Even I'm facing the problem. Is this fixed?
