### ISSUE TITLE
UI bindings don't fire when orientation changes

### ISSUE THREAD

**Issue by EricRobertBrewer** [NativeScript/nativescript-angular#651]
**Can I make my Angular2 UI bindings affect the UI when the device orientation changes?**

Because of [the issue where layout qualifiers are not yet supported in Angular2 apps](https://github.com/NativeScript/nativescript-angular/issues/404), I tried using [this nativescript-orientation plugin](https://github.com/NathanaelA/nativescript-orientation) and one-way bindings to change my UI when the device's orientation changes.

    <DockLayout>
        <Label dock="{{isLandscape ? 'left' : 'top'}}" text="Controls" backgroundColor="red"></Label>
        <Label dock="{{isLandscape ? 'right' : 'bottom'}}" text="Results" backgroundColor="yellow"></Label>
    </DockLayout>

and:

    import { Component, OnInit, OnDestroy } from "@angular/core";
    import * as application from "application";
    import { DeviceOrientation } from "ui/enums";
    //import * as orientation from "nativescript-orientation";
    var orientation = require("nativescript-orientation");

    @Component({
        templateUrl: "pages/dock-layout.html"
    })
    export class DockLayoutComponent implements OnInit, OnDestroy {

        isLandscape: boolean = false;

        constructor() {
        }

        ngOnInit() {
            this.isLandscape = orientation.getOrientation() == DeviceOrientation.landscape;
            application.on(application.orientationChangedEvent, this.onOrientationChanged);
        }

        ngOnDestroy() {
            application.off(application.orientationChangedEvent, this.onOrientationChanged);
        }

        onOrientationChanged = (args: application.OrientationChangedEventData) => {
            this.isLandscape = args.newValue == DeviceOrientation.landscape;
            console.log("onOrientationChanged():"+args.newValue+" isLandscape:"+this.isLandscape);
        };
    }

The result is:
![device-2017-01-30-131521](https://cloud.githubusercontent.com/assets/1558524/22442446/4a0d9e18-e6f0-11e6-92c3-fbddd363e118.png)

![device-2017-01-30-131549](https://cloud.githubusercontent.com/assets/1558524/22442449/4e1c9dce-e6f0-11e6-89af-e01c4f446ec9.png)

I expected the 'Controls' label to appear on the left, and the 'Results' label to appear on the right.

I initially thought that my bindings were written incorrectly. But when I added:

    <ActionBar title="{{!isLandscape ? 'Portrait' : 'Landscape'}}">
        <ActionItem text="{{isLandscape ? 'Portrait' : 'Landscape'}}" (tap)="onRotateTapped($event)" ios.position="right"></ActionItem>
    </ActionBar>

and

        onRotateTapped(event) {
            this.isLandscape = !this.isLandscape;
        }

By tapping the `ActionItem`, I found that the bindings *did work properly* and the UI elements moved to the left or right (ie. that the `dock` property of a child of a `DockLayout` is bindable), but the UI doesn't update despite the log saying `isLandscape:true`. 

**How can I update the UI during an orientation change, preferably without using `setTimeout`?**

**Comment by EricRobertBrewer** [comment]
Project is [here](https://github.com/EricRobertBrewer/ns-bind-orientation-change).

**Comment by hdeshev** [comment]
I just tested your project, and it turns out to be an Ng zone issue. The nativescript-orientation plugin isn't angular-aware, and its callbacks do not execute in the zone. The resolution here is to wrap your event handler in our `global.zonedCallback` utility method:

`application.on(application.orientationChangedEvent, global.zonedCallback(this.onOrientationChanged));
`

Ideally that would be done by the plugin and you shouldn't have to call that method yourself (`global.zonedCallback` is a noop when running without Angular). Details here:
http://www.nativescriptsnacks.com/videos/2016/06/13/zoned-callbacks.html

**Comment by tsonevn** [comment]
Hi @EricRobertBrewer,
I reviewed your sample code and found that the problem with the binding could be related with the missing `NativeScriptFormsModule` inside the `imports` in `app.modules.ts`. For example 

`app.modules.ts`

```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NativeScriptRouterModule } from "nativescript-angular/router";
import { routes, navigatableComponents } from "./app.routing";
import { AppComponent } from "./app.component";
import {NativeScriptFormsModule} from "nativescript-angular/forms"

@NgModule({
    declarations: [
        AppComponent,
        ...navigatableComponents
    ],
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        NativeScriptRouterModule,
        NativeScriptRouterModule.forRoot(routes),
        NativeScriptFormsModule
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule {
}
```


Another behavior which I noticed is has been related to the appropriate property change detection inside the callback method. We will research further this problem. In the meantime, you could use NgZone inside the callback, which will fix this issue at the moment.
I am also providing sample code for this case:

`dock-layout.component.ts`

```
import { Component, OnInit, OnDestroy, NgZone } from "@angular/core";
import * as application from "application";
import { DeviceOrientation } from "ui/enums";
//import * as orientation from "nativescript-orientation";
var orientation = require("nativescript-orientation");

@Component({
    templateUrl: "pages/dock-layout.html"
})
export class DockLayoutComponent implements OnInit, OnDestroy {

    isLandscape: boolean = false;

    constructor(private zone:NgZone) {
    }

    ngOnInit() {
        this.isLandscape = orientation.getOrientation() == DeviceOrientation.landscape;
        application.on(application.orientationChangedEvent, this.onOrientationChanged);
    }

    ngOnDestroy() {
        application.off(application.orientationChangedEvent);
    }

    onOrientationChanged = (args: application.OrientationChangedEventData) => {
        this.zone.run(()=>{
            this.isLandscape = args.newValue == DeviceOrientation.landscape;
            console.log("onOrientationChanged():"+args.newValue+" isLandscape:"+this.isLandscape);
        })
        
    };

    onRotateTapped(event) {
        this.isLandscape = !this.isLandscape;
    }
}
```

Hope this information helps.

**Comment by EricRobertBrewer** [comment]
Magically, by toggling `isLandscape` within an `NgZone` resolved the issue:

    import { Component, OnInit, OnDestroy, NgZone } from "@angular/core";
    ...
        constructor(private zone: NgZone) {
        }
        ...
        onOrientationChanged = (args: application.OrientationChangedEventData) => {
            this.zone.run(() => {
                this.isLandscape = args.newValue == DeviceOrientation.landscape;
                console.log("onOrientationChanged():"+args.newValue+" isLandscape:"+this.isLandscape);
            });
        };

Commit to project is [here](https://github.com/EricRobertBrewer/ns-bind-orientation-change/commit/4eda5854bc1178645291a461e0776280806412e1#diff-9a78abf5de779ed09d6ff711b163ea10R29).

Thanks for the help, @tsonevn.
