### ISSUE TITLE
Extending Android Application onCreate method 

### ISSUE THREAD

**Issue by code0wl** [NativeScript/nativescript-angular#653]
Regarding the documentation found [on the NativeScript doc site](https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity) which goes into detail on implementing an extension for the application object found on Android. 

The documentation is most likely for non-Angular users. 
Running the following code snippet in LTS version of the CLI (2.5.0) will result in 

```javascript
import * as application from "application";

// the `JavaProxy` decorator specifies the package and the name for the native *.JAVA file generated. 
@JavaProxy("org.myApp.Application")
class Application extends android.app.Application {
    protected onCreate(): void {
        super.onCreate();

        // initialize the modules with the custom application object
        application.android.init(this);

        // Enter custom initialization code here
    }

    protected attachBaseContext(baseContext: android.content.Context) {
        super.attachBaseContext(baseContext);
    }
}
```

> Output with Error
application.android already initialized.

The culprit in this case is the following:
```javascript
application.android.init(this);
```

If one removes the context snippet then it works fine again. But does the application.onCreate get affected negatively by this?

Can this be made more clear that the Angular flavoured NativeScript variant initialisation works differently? 

P.S. I have made a PR to update the documentation, but wanted to know 100% sure if this is not the expected behaviour and could possibly be a bug.  [PR](https://github.com/NativeScript/android-runtime-docs/pull/30)

**Comment by Pip3r4o** [comment]
Please check out https://github.com/NativeScript/android-runtime/issues/612#issuecomment-258432021

It would appear that the Javascript sample was updated, but the TS counterpart was skipped in the process. It is no longer necessary to invoke `application.init` inside the onCreate, as the core modules do that for you now. 

You can close the PR, and I'll update the samples, or you could update your PR to address the TypeScript code and the following note in the article. 

Thank you!

**Comment by vchimev** [comment]
The [sample](https://github.com/NativeScript/sample-android-extend) has been updated to NativeScript@4.1. An angular sample could be found [here](https://github.com/NativeScript/nativescript-dev-webpack/tree/master/demo/AngularApp).
