### ISSUE TITLE
Creating a sample app with AoT enabled - can't find 3rd party plugins.

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/nativescript-angular#655]
Trying to create a sample app with AoT enabled. It works, if I don't add 3rd party plugins, but fails, when I add something trivial:

1. `tns create test --ng`
2. `tns plugin add nativescript-vibrate`

In docs(http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html) NS says, that one would specify the plugin upon app bootstraping like so:
```
// app.module.ts
..

require("globals");
global.registerModule("nativescript-vibrate", function() { return require("nativescript-vibrate"); });

@NgModule({
...
```

However, getting error:
```
ERROR in ./app.module.ts
Module not found: Error: Can't resolve 'nativescript-vibrate' in 'C:\projects\test\app'
 @ ./app.module.ts 16:67-98
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts
```
What am I doing wrong?

**Comment by hdeshev** [comment]
It seems nativescript-vibrate needs to be updated in order to be resolvable by webpack:

**Comment by patrickpereira** [comment]
The same issue is happening to me trying to add 'nativescript-taptic-engine', which has been updated the way the docs show.

Any clue what might be causing that?

PS. I'm using lazyloaded modules in my app.

**Comment by dxshindeo** [comment]
> I'm using lazyloaded modules in my app.
Same here.
