### ISSUE TITLE
Action bar not showing with lazy loading

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#662]
_From @dlucidone on February 8, 2017 11:50_

I'm having issues with getting different action bar on each pages. All i'm getting is same action bar with app name in every page. Thanks

_Copied from original issue: NativeScript/NativeScript#3607_

**Comment by m-abs** [comment]
Hi, 

I don't understand what you mean by "the same action bar"?

But since you mention the app name on every page, have you set a title on the ActionBar?
Otherwise by default the app name will be shown on the page. A simple workaround is to set an empty string as the title.

**Comment by NickIliev** [comment]
@dlucidone  apart from the solution to explicitly set each page action bar title you can create a custom directive and use predefined data for each different page.

For example in [this application](https://github.com/NativeScript/nativescript-sdk-examples-ng) we have a custom directive which is snapshot each route and based on the predefined title for this route is reusing the same title as an action bar title.

Here is how it is done step by step:

- creating each route with a title property  [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/app.routes.ts)
- creating the [custom directive](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/directives/example.directive.ts#L5-L13) to reuse this title property as an ActionBar title. The directive is imported in[ this file](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/directives/title-and-nav-button.module.ts)
- the file with the exported directives is imported in the needed ngModule as [shown here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/examples-list.module.ts#L15)
- and finally call the directive where needed like [in this page](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/examples-list.component.html#L1)

**Comment by deepak4u2006** [comment]
Hi @NickIliev , 
Recently I have started converting my NS-ng app into lazyloading, for that I am using the reference from [groceries](https://github.com/NativeScript/sample-Groceries/tree/angular-end) .

I am able to switch between login and Home page of my app based on the loggedIn logic.

My problem is for Home page I have created a ActionBar like:
```
<ActionBar title="Home">
    <NavigationButton text="Menu" icon="res://ic_menu" (tap)="openDrawer()"></NavigationButton>
    <StackLayout orientation="horizontal" horizontalAlignment="center" verticalAlignment="center">
        <Label text="Scan to Pay " color="white" class="actionBarTitle" horizontalAlignment="center" verticalAlignment="center"></Label>
        <Image src="res://view_qr_code" width="20" height="20" class="actionBarTitleImage"></Image>
    </StackLayout>
    <ActionItem (tap)="onShowBarcode()" icon="res://qr_scan"></ActionItem>
</ActionBar>

<RadSideDrawer showOverNavigation="true" #drawerComponent tkToggleNavButton>

    <StackLayout tkDrawerContent class="drawer-content" horizzontalAlign="left">
        <drawer-content></drawer-content>
    </StackLayout>

    <GridLayout tkMainContent class="home-page" rows="*,50">
        <absolutelayout row="0">
            <scroll-view class="mainScrollView" #mainScrollView width="100%" height="100%">
                <!-- <Custom Code..........> -->
            </scroll-view>
    </GridLayout>

</RadSideDrawer>
```

Before lazyloading everything was fine, but post that I am just able to get an ActionBar with the app name.

Kindly suggest ..
