### ISSUE TITLE
ModalDialogService - no way to close the modal programatically

### ISSUE THREAD

**Issue by bot2600** [NativeScript/nativescript-angular#663]
Unless I am missing something, there is no clear way to close the modal created by showmodal on the ModalDialogService.

Under the hood, showmodal is called on the page pulled out of the viewcontainerref, but closemodal is called on the modal itself.

I can't get to the page that is the modal because it is in a private static func, and if I pull the get(Page) off the viewcontainerref and call closemodal on it or call closemodal on the page I am on in the app, the grayed out background stays.

This is of course in the instances where I am navigating away because of something else that has happened and the close button on the modal is not going to get touched.

I can post code, but it is mostly this to show the modal:

            let options: ModalDialogOptions = {
                viewContainerRef: this.viewContainerRef,
                context: {}
            }

            this.modalService.showModal(MyModalType, options).then((result: MyResultType) => {

            })

then this to navigate away:

        this.routerExtensions.navigate(["/home"], { clearHistory: true }).then(() => {
            this.submitted = false
        })

Ive tried this to try to close the modal:

                let refPage: Page = this.viewContainerRef.injector.get(Page)
                refPage.closeModal()
                this.page.modal.closeModal()

or just calling close on my current page, but neither works.

this.page.closeModal()

I have also tried getting the modal's button by calling this.page.getViewById, but its in a different page and doesn't return. And tried passing a func back and forth between my page through params, but that doesnt seem to work consistently.

thoughts?

**Comment by bot2600** [comment]
nevermind, looks like I can close it by calling this.page.modal.closeModal(), though it acts funny, it hangs navigation by several seconds, even when calling it in the promise returned from the navigation

**Comment by bot2600** [comment]
Re-opening, I closed it thinking that I had to be doing something wrong, but if I am, I sure can't figure it out. Any thoughts?

**Comment by DavyDeDurpel** [comment]
This should do the trick:

import { topmost } from "ui/frame";

...

const page = topmost().currentPage;
if (page && page.modal) {
     page.modal.closeModal()
}

**Comment by bot2600** [comment]
@DavyDeDurpel thanks! that partially works, it gets rid of the modal, but not the gray overlay from what I assume is it being full screen.

Thoughts?

**Comment by DavyDeDurpel** [comment]
I never had the issue of the gray overlay not disappearing.  Did you try first closing the modal and than navigating away?

**Comment by tsonevn** [comment]
Hi @bot2600,
The correct way to use a `ModalPage` with navigation in NativeScript is, as @DavyDeDurpel  suggested, to close the modal page and then to make the navigation. To be able to access the Page in the project, you could set up new private page property in the constructor of the component.  For example:
```
import { Component, OnInit, NgModule } from "@angular/core";
import { ModalDialogParams } from "nativescript-angular/modal-dialog";
import { Page } from "ui/page";

@Component({
    moduleId: module.id,
    templateUrl: "./modal-view.html",
})
export class ModalViewComponent implements OnInit {

    constructor(private params: ModalDialogParams, private page: Page) {
    }

    ngOnInit() {
    }

 
}
```

The navigation could be made after returning from the modal Page:
```
this._modalService.showModal(ModalViewComponent, options)
            .then((result: string) => {
                if (args === "navigate") {
                    this.routerExtensions.navigate(["/main"], { clearHistory: true });
                } else if (args === "findTheDay") {
                    //do something else
                }
            });
```
For further help, you could also review the sample code in nativescript-sdk-examples-ng [repo](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/release/app/modal-page/sample-modal-page-module-example)

**Comment by bot2600** [comment]
@tsonevn thanks, but you missed what I was actually asking. I can't close it in the then of showmodal because the flow I am trying to fix is when I need to close it without the user interacting with it.

A good example is touch id. You run your bank of america app or which ever, you get a modal prompt and behind the scenes it also starts listening to the fingerprint authentication manager. The user might hit cancel, in which case the modal would close itself and the then would run. But the more likely path is the user creds with touch id, the modal needs to be closed programmatically and then the application navigates. This is identical to my situation. When you aren't using components, the documentation looks like you can just call closemodal on the page, but there is no comparable closemodal method on the modal service. The path Davy gave me will probably work once I get in there today, but it seems like modal service should have a consistent way to handle this use case besides relying on something unclear and undocumented.

Thanks again for your time, I will verify what Davy posted will work today and close the issue if it does.

**Comment by bot2600** [comment]
Ok, so back from testing, the code Davy gave me works under some circumstances, but under others isn't even though page and modal are both true. I have this code:

                console.log("I BELIEVE I CAN FLY")
                let page = topmost().currentPage
                if (page && page.modal) {
                    console.log("trying to close the modal")
                    page.closeModal()
                }

both get logged to the console, but the then from the showmodal does not get hit and the modal is not closed.

**Comment by dgomezs** [comment]
Probably not the best way but what I'm doing at the moment is to use Observables to implement this functionality. I wanted to implement the typical Android loading popup. This is what I did

Pop up component 

```
import {Component} from "@angular/core";
import {ModalDialogParams} from "nativescript-angular/modal-dialog";

@Component({
    template: `
        <StackLayout orientation="horizontal" padding="20" horizontalAlignment="left" verticalAlignment="center">
            <ActivityIndicator busy="true" height="50" width="50"
                       visibility="visible"></ActivityIndicator>
            <Label margin="10 5 0 5" text="Loading ..."></Label>           
        </StackLayout>
    `
})
export class LoadingPopUpComponent {

    constructor(private params: ModalDialogParams) {

        params.context.closeObserver.subscribe((r) => {
            this.close(null);
        });
    }

    public close(result: string) {
        this.params.closeCallback(result);
    }
}
```

Opening and closing the modal 

```
loadingIndicator(): void {
        let options: ModalDialogOptions = {
            context: {closeObserver: this.dialogObservable},
            fullscreen: false,
            viewContainerRef: this.viewContainerRef
        };

        this.modalService.showModal(LoadingPopUpComponent, options);
    }

    closeIndicator(): void {
        this.dialogSubject.next(true);
    }
```

I define the Subject and observable as follows 

```
dialogSubject: Subject<boolean>;
dialogObservable: Observable<boolean>;
this.dialogSubject = new Subject();
this.dialogObservable = this.dialogSubject.asObservable();
```

Hope it helps.

**Comment by bot2600** [comment]
@dgomezs thanks, yeah I did something similar except I think I used a broadcaster

**Comment by racknoris** [comment]
Since it's been a while: Is there any new way to close an opened modal?

**Comment by RioBautista** [comment]
Funny but I just simply called the closeCallBack() which I couldn't figure out how to assign (since it's supposed to be a callback function, but it simply closed the modal page.

```
closeWindow(event) {
        this.params.closeCallback()
}
```

**Comment by freddiandrew** [comment]
look like an issue using {N} angular,
 `
this.modalSvc.showModal(MdtcellComponent, options).then((res) => {
    console.dir(res);
    let url = res.url ;
    let param = res.param ;
    this.route.navigate(['/'+ url + '/'+ param],{ clearHistory: true });
    })
`

after modal close, the page navigate to url but after few second it`will back to previous page where the modal tap

**Comment by vick16ach** [comment]
everything is working fine except closing .. please anyone if found the answer post it here in pure javascript version.....

**Comment by kkoates** [comment]
@freddiandrew @vick16ach @bot2600 

I opened a feature request as I have run into the same modal close nav back issue.  Maybe it can get some traction or at least the conversation going again.

https://github.com/NativeScript/nativescript-angular/issues/1534

**Comment by fransyozef** [comment]
@kkoates I hope it will be picked up. I have the same issue. I can close the modal in iOS, but not in Android (and I mean from outside the modal). For now I think I also will use a Observable or something.

**Comment by WrightTrae** [comment]
Here is what I ended up doing to close a model from another class using an interface. https://play.nativescript.org/?template=play-ng&id=q1mDZI&v=6

**Comment by rg777** [comment]
@dgomezs 
Thanks a lot for the solution. It works fine. (Couldn't find any other working solution till date.)
Any downside of using such a solution?
