### ISSUE TITLE
Navigate to back page

### ISSUE THREAD

**Issue by mohitgorakhiya** [NativeScript/nativescript-angular#667]
Hi,

I am new to Native script development. I am developing iOS app.
And now my requirement is to remove page from navigation history.
Suppose
My navigating is like
A-->B-->C
So my back navigation will be C-->B-->A
But here I want to go to A from C.
Means when moving B-->C I want to clear B from navigation stack history.
Such that when click on Back button from C, it will redirect to A page.
So can anyone help me out to achieve this functionality?
Waiting for Reply ASAP!!!!!!!!

**Comment by eleddie** [comment]
You need to use RouterExtensions, import this in the B component instead of the `@angular/router`
`import { RouterExtensions } from "nativescript-angular/router";`
Add it to your constructor like this:
`constructor(private router: RouterExtensions,..)`
And whenever you want to navigate and remove current page from stack, do this:
`this.router.navigate(['/Component-C'], {clearHistory: true});`

**Comment by NickIliev** [comment]
@mohitgorakhiya detailed documentation article about navigation in Angular-2 application can be found [here](https://docs.nativescript.org/angular/core-concepts/angular-navigation.html#navigation-options) and also the suggestion provided by @eleddie is applicable. 

Please keep in mind that the issues are for posting, discussing and resolving bugs and features so please post similar questions ni the community channels such as [StackOverflow](http://stackoverflow.com/questions/tagged/nativescript)

**Comment by mohitgorakhiya** [comment]
Thanks for the solution.
I am sorry if i have written something wrong.
But i just discussing the solution here.

Thanks,
Mohit.

On Feb 13, 2017 1:47 PM, "Nick Iliev" <notifications@github.com> wrote:

@mohitgorakhiya <https://github.com/mohitgorakhiya> detailed documentation
article about navigation in Angular-2 application can be found here
<https://docs.nativescript.org/angular/core-concepts/angular-navigation.html#navigation-options>
and also the suggestion provided by @eleddie <https://github.com/eleddie>
is applicable.

Please keep in mind that the issues are for posting, discussing and
resolving bugs and features so please post similar questions ni the
community channels such as StackOverflow
<http://stackoverflow.com/questions/tagged/nativescript>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/NativeScript/nativescript-angular/issues/667#issuecomment-279320361>,
or mute the thread

**Comment by jdnichollsc** [comment]
@mohitgorakhiya Maybe you need to replace the current URL navigating from B to C
```
this.route.navigate(['/C'], { replaceUrl: true })
```
