### ISSUE TITLE
With Webpack and AOT my css for pages break?

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#669]
_From @dlucidone on February 15, 2017 6:25_

With using webpack and AOT compilation my Action bar is touching the status bar when i make my application bundle and other pages container are overflowing too. with the normal app compilation its working as desired.

My package.json is like - 

    "dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "email-validator": "1.0.4",
    "nativescript-angular": "1.4.0",
    "nativescript-calendar": "^1.2.0",
    "nativescript-camera": "0.0.8",
    "nativescript-cardview": "^1.2.1",
    "nativescript-checkbox": "^1.2.3",
    "nativescript-drop-down": "^1.5.1",
    "nativescript-fancyalert": "^1.1.2",
    "nativescript-floatingactionbutton": "^2.2.7",
    "nativescript-imagepicker": "^2.4.1",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-progressbar": "^1.0.2",
    "nativescript-social-share": "~1.3.2",
    "nativescript-theme-core": "^1.0.2",
    "nativescript-unit-test-runner": "^0.3.3",
    "reflect-metadata": "^0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "^2.5.0"
     },
    "devDependencies": {
    "@angular/compiler-cli": "2.4.5",
    "babel-traverse": "6.8.0",
    "babel-types": "6.8.1",
    "babylon": "6.8.0",
    "codelyzer": "2.0.0-beta.4",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "filewalker": "0.1.2",
    "jasmine-core": "^2.4.1",
    "karma": "^1.2.0",
    "karma-jasmine": "^1.0.2",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "nativescript-dev-webpack": "^0.3.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "tslint": "^4.0.0",
    "typescript": "^2.1.0",
    "webpack-sources": "~0.1.3",
    "zone.js": "~0.7.2",
    "nativescript-css-loader": "~0.26.0",
    "htmlparser2": "^3.9.2",
    "webpack": "2.2.0",
    "@ngtools/webpack": "1.2.4"
    }

_Copied from original issue: NativeScript/NativeScript#3638_

**Comment by NickIliev** [comment]
_From @dlucidone on February 15, 2017 7:17_

I'm getting something like this when bundling - 

    WARNING in ../~/resolve-url-loader!../~/nativescript-css-loader!../~/nativescript-dev- 
    webpack/platform-css-loader.js!./app.css
      resolve-url-loader cannot operate: CSS error

**Comment by dlucidone** [comment]
Now my action bar look like this -
![screen shot 2017-02-15 at 12 52 06 pm](https://cloud.githubusercontent.com/assets/9256365/22964290/dc7608aa-f37d-11e6-9a89-186530391114.png)

**Comment by NickIliev** [comment]
@@dlucidone  this is just a Warning and should not be the reason your application is crashing.
Perhaps you can provide the detailed error log from your application build.
Also please let us know with what command you are bundling and also are you bundling in a release or in debug mode?

Based on your last post with the screenshot from your action bar that this means you have successfully bundled your app with webpack bu now experiencing different issue?

**Comment by dlucidone** [comment]
I'm bundling my app using- 

    npm run start-android-bundle

I'm juss getting the warning i mentioned above the bundling is completed but i'm facing this sorta issues with css.
with nomal compilation i'm having no issues like this.

**Comment by NickIliev** [comment]
@dlucidone can you please share with us your CSS files (the ones that are broken) and also share with us where they are standing in your application. If possible a sample application to reproduce your case can be of help as well.

**Comment by dlucidone** [comment]
My app.css -

    
    .actionItemLabel {
    font-size: 20;
    font-family: "SourceSansPro-Regular";
    }

    .font-awesome {
    font-family: "fontawesome-webfont";
    font-size: 14;
    font-weight: normal;
    text-align: center;
    font-style: normal;
    }

    .font-awesome-button {
    font-family: "fontawesome-webfont";
    font-size: 12;
    font-weight: normal;
    text-align: center;
    font-style: normal;
    }

    .font-awesome-label {
    font-family: "fontawesome-webfont";
    font-size: 24;
    font-weight: normal;
    text-align: center;
    font-style: normal;
    color: #ED2831;
    padding:5px;
    }

    Page {
    background-color: #DEDEDE;
    font-size: 15;
    background-size: cover;
    background-position: center;
    font-family: "SourceSansPro-Regular";
    }

    TextField {
    font-size: 16;
    color: black;
    border-bottom-width: 1;
    border-bottom-color: #DEDEDE;
    }

    .allMaskedInput {
    font-size: 16;
    color: black;
    border-bottom-width: 1;
    border-bottom-color: #DEDEDE;   
    }

    .fitnessLabel {
    color: black;
    font-weight: bold;
    font-size: 16;
    margin-bottom: 5px;
    margin-top: 10px;
    }

    .labelRadio {
    color: black;
    font-weight: bold;
    font-size: 16;
    margin-bottom: 0px;
    margin-top: 5px;
    }

    .stackOfRadio {
    padding:5px;
    display: block;
    /*background-color: #F2F2F2*/
    }

    .bookingLabel {
    color: black;
    font-weight: bold;
    font-size: 16;
    margin-bottom: 5px;
    margin-top: 10px;
    }

    .rupeeSymbol {
    margin-left: 5%;
    }

    .textAboveLabel {
    color: gray;
    font-size: 15;
    margin-top: 5px;
    margin-left: 4px;
    }

    .firstLabel {
    font-weight: bold;
    margin-left: 5;
    color: black;
    margin-top: 5px;
    margin-bottom: 5px;
    font-size: 17;
    }

    .viewLabelOutside {
    font-weight: bold;
    margin-left: 10px;
    color: black;
    margin-top: 15px;
    margin-bottom: 5px;
    font-size: 14;
    }


    .radioText {
    /*margin-left: 15;*/
    color: gray;
    vertical-align: middle;
    font-size: 16;
    font-weight: normal;
    text-align: center;
    font-style: normal;
    padding:5px;
    }

    .small-spacing {
    margin: 10;
    background-color: white;
    width: 100%;
    height: 100%;
    }

    .medium-spacing {
    margin-left: 20%;
    margin-top: 15;
    }

    .id-spacing {
    margin-top: 10;
    margin-right: 30;
    }

    /*css for the plus and minus button when adding the package*/
    .addPopup {
    text-align: right;
    vertical-align: middle;
    color:#ED2831;
    font-size: 22;
    margin-top: 5px;
    }

    #addIcon {
    color: #ED2831;
    vertical-align: middle;
    text-align: right;
    margin-right: 5px;
    font-size: 18;
    }

    @import 'nativescript-theme-core/css/core.light.css';

**Comment by hdeshev** [comment]
@dlucidone could you publish a reproduction project on github that I can take a look at?

**Comment by dlucidone** [comment]
@hdeshev Thanks for the reply however 
Changing webpack module loader config by reordering 

#### "nativescript-css-loader", and "resolve-url-loader", 
     
     {
          test: /app\.css$/,
          loader: ExtractTextPlugin.extract([
          "nativescript-css-loader",
          "resolve-url-loader", 
          "nativescript-dev-webpack/platform-css-loader",
            ]),
      }

Solved my problem don't know the reason yet and no warning with this config also. Thanks
