### ISSUE TITLE
Unable to bind property for Platform Directives (sample below)

### ISSUE THREAD

**Issue by ADjenkov** [NativeScript/nativescript-angular#671]
Should it be possible to bind property for a specific platform only?

Something like:
`<Label 
            android:[text]="model.property1"
            ios:[text]="model.property2"`
or 
`<Label 
            [android:text]="model.property1"
            [android:text]="model.property2"`

**Comment by NickIliev** [comment]
Binding for a specific platform is not supported via your HTML/XML files. However, the easiest solution is to create platform-specific "blocks" via an angular directive.  Example of creating your own platform-specific directive (to detect if the platform is either Android or iOS) can be found `[here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/release/app/ui-category/ng-directives/ngif-directive-advanced)`

**Comment by ADjenkov** [comment]
@NickIliev  Yes I know for the platform-specific "blocks", but I don't like this approach when there is relatively big template/snippet. My problem was that I wanted to bind `height` property for iOS only. But then I must specify value for android too (which I don't want to do since the android will resize the control by itself)

Anyway I've managed to do it like this:

`[height]="isAndroid ? '*' : getMyHeightFunc()"`

**Comment by ADjenkov** [comment]
This solution '[height]="isAndroid ? '*' : getMyHeightFunc()"' works only in debug mode.
