### ISSUE TITLE
NativeScript actionbar add Icon

### ISSUE THREAD

**Issue by culunvb** [NativeScript/nativescript-angular#672]
Hi Guys, How to add something icon beside title Bar in Native script, would you like to help me, please

Thank in advanced

**Comment by tsonevn** [comment]
Hi @culunvb,
You could review the both examples in `nativescript-sdk-examples-ng`, where has been shown, how to use [systemIcon ](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/ui-category/action-bar/navigation-button/navigation-button.component.html) or [icon from the resources](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/release/app/ui-category/action-bar/title/title.component.html) in `ActionBar` component. 
For further `How to` questions, please use our StackOverflow thread [here](http://stackoverflow.com/questions/tagged/nativescript).
