### ISSUE TITLE
TypeError: Cannot read property 'getCookie' of null at CookieXSRFStrategy.configureRequest

### ISSUE THREAD

**Issue by sebastienratez** [NativeScript/nativescript-angular#674]
Hi,

Using nativescript-angular v1.4.0 I get this error:

```
JS: EXCEPTION: Error in :0:0 caused by: Cannot read property 'getCookie' of null
JS: ORIGINAL EXCEPTION: Cannot read property 'getCookie' of null
JS: ORIGINAL STACKTRACE:
JS: TypeError: Cannot read property 'getCookie' of null
JS:     at CookieXSRFStrategy.configureRequest (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/http/bundles/http.umd.js:1284:108)
JS:     at XHRBackend.createConnection (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/http/bundles/http.umd.js:1331:32)
JS:     at httpRequest (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/http/bundles/http.umd.js:1677:24)
JS:     at Http.request (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/http/bundles/http.umd.js:1784:38)
JS:     at Http.get (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/http/bundles/http.umd.js:1798:25)
JS:     at HeroesService.getHeroes (file:///data/data/org.nativescript.nativescript/files/app/app/services/heroes.service.js:23:26)
JS:     at AppComponent.ngOnInit (file:///data/data/org.nativescript.nativescript/files/app/app/app.component.js:21:28)
JS:     at Wrapper_AppComponent.ngDoCheck (/AppModule/AppComponent/wrapper.ngfactory.js:22:53)
JS:     at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/AppModule/AppComponent/host.ngfactory.js:34:26)
JS:     at CompiledTemplate.proxyViewClass.AppView.detectChanges (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:12583:18)
JS: ERROR CONTEXT:
JS: [object Object]
JS: ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: Error in :0:0 caused by: Cannot read property 'getCookie' of null
```

Now, I have tried the instructions of that other older defect suggesting using NS_HTTP_PROVIDERS, but it's not exported in my version of nativescript-angular/http so I can't try it (weird isn't it?)

This is the content of ns-http.d.ts:

```
import { Http, ConnectionBackend, RequestOptionsArgs, Response } from "@angular/http";
import { Observable } from "rxjs/Observable";
import "rxjs/add/observable/fromPromise";
import { NSFileSystem } from "../file-system/ns-file-system";
export declare class NSXSRFStrategy {
    configureRequest(_req: any): void;
}
export declare class NSHttp extends Http {
    private nsFileSystem;
    constructor(backend: ConnectionBackend, defaultOptions: any, nsFileSystem: NSFileSystem);
    /**
     * Performs a request with `get` http method.
     * Uses a local file if `~/` resource is requested.
     */
    get(url: string, options?: RequestOptionsArgs): Observable<Response>;
}
```

**Comment by sebastienratez** [comment]
this commit of september 2016 removed the http fix:

![image](https://cloud.githubusercontent.com/assets/6885597/23129415/e44da2c8-f782-11e6-93c9-b9ba9f6fcff8.png)

Now, there must be a good reason for it. What's the alternative?

**Comment by sebastienratez** [comment]
I see HTTP_PROVIDERS has been deprecated in angular 2 rc5, but then what's the alternative? I could use the NSHttp export instead of Http (though I´m not certain that would solve my problem?), but then again, my webapp components are shared across angular webapp and nativescript so they need Http, not NSHttp.

What's the solution?

**Comment by NathanWalker** [comment]
@sebastienratez everything is on Angular final now.
You will want to make sure your dependencies reflect these:
https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/package.json#L26-L36
however, use `tns-core-modules: 2.5.0` and `nativescript-angular: 1.4.0`

**Comment by NathanWalker** [comment]
Then in your root module, ensure you use `NativeScriptHttpModule` similar to how this is setup:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/nativescript/src/components.module.ts#L36

**Comment by sebastienratez** [comment]
Okay, it now compiles. Then it crashes (obviously) when using the Http object I inject in one of my ng2 services:

```
  getHeroes(): Observable<Hero[]> {
      let url = environment.apiUrl + "heroes";    
      return this.http.get(url)
                .map((res:Response) => res.json())
                .catch((error:any) => Observable.throw(error.json().error || 'Server error'));
  }
```

Error is:

```
JS: EXCEPTION: Uncaught (in promise): Server error
JS: ORIGINAL STACKTRACE:
JS: Error: Uncaught (in promise): Server error
JS:     at resolvePromise (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:416:31)
JS:     at file:///data/data/org.nativescript.nativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:452:17
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:223:37)
JS:     at Object.onInvokeTask (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/@angular/core/bundles/core.umd.js:4382:41)
JS:     at ZoneDelegate.invokeTask (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:222:42)
JS:     at Zone.runTask (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:123:47)
JS:     at drainMicroTaskQueue (file:///data/data/org.nativescript.nativescript/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:355:35)
JS: Unhandled Promise rejection: Server error ; Zone: angular ; Task: Promise.then ; Value: Server error
JS: Error: Uncaught (in promise): Server error
```

I suspect it is related: I can't use the Http module in NativeScript. But this component is shared with my regular ng2 app, how can I work this around?

**Comment by sebastienratez** [comment]
Nathan I see you're the author of nativescript-ngx-magic; could you please clarify if its dependency is still needed when in need to share components across mobile and web? I'm confused as to how nativescript-ngx-magic and nativescript-angular dependencies relate with each other, and how to use them in the code (my project is angular-cli based but I want to reuse the components with nativescript)

My understanding is that in my @Components, I just use import { Component } from '@wwwalkerrun/nativescript-ngx-magic'; instead of the regular component from angular core. But then, shouldn't I use the Http module from that package as well instead of the one from nativescript-angular?

You see in the readme of https://github.com/wwwalkerrun/nativescript-ngx-magic, there's no import of nativescript-angular so in theory I should be able to use things as they come (e.g. the http module). Could you confirm whether I need this additional nativescript-angular module anyway?

Thank you

**Comment by sebastienratez** [comment]
Thanks, in fact that was enough to solve it.
