### ISSUE TITLE
Nativescript Webpack bundling

### ISSUE THREAD

**Issue by manishmlv50** [NativeScript/nativescript-angular#676]
I am using the following versions of angular and nativescript-angular 
```
"dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "email-validator": "1.0.4",
    "moment": "2.17.0",
    "nativescript-angular": "1.4.0",
    "nativescript-camera": "0.0.8",
    "nativescript-cardview": "^1.2.0",
    "nativescript-carousel": "^2.1.1",
    "nativescript-checkbox": "^1.2.2",
    "nativescript-drop-down": "1.5.1",
    "nativescript-keyboardshowing": "^1.0.0",
    "nativescript-loading-indicator": "^2.2.2",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-plugin-firebase": "^3.10.0",
    "nativescript-screen-orientation": "1.0.2",
    "nativescript-telerik-ui": "^1.4.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-timedatepicker": "1.1.0",
    "nativescript-toast": "1.4.5",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.0",
    "tns-platform-declarations": "2.4.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.4.5",
    "@ngtools/webpack": "1.2.4",
    "babel-traverse": "6.19.0",
    "babel-types": "6.19.0",
    "babylon": "6.14.1",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "htmlparser2": "~3.9.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "0.3.3",
    "nativescript-dev-webpack": "^0.3.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "^2.0.10",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3",
    "zone.js": "^0.7.2"
  }
```

``
ERROR in Error encountered resolving symbol values statically. Reference to a non-exported class ListViewLayoutBase. Consider exporting the class (position 292:1 in the original .ts file), resolving symbol ListViewLinearLayout in /Users/manishmalviya/Desktop/one-2/node_modules/nativescript-telerik-ui/listview/index.d.ts

ERROR in ../~/nativescript-angular/router/ns-module-factory-loader.js
Module not found: TypeError: Cannot convert undefined or null to object
 @ ../~/nativescript-angular/router/ns-module-factory-loader.js 23:15-40
 @ ../~/nativescript-angular/router.js
 @ ./vendor.ts
Child extract-text-webpack-plugin:
       [0] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ../~/nativescript-css-loader!../~/nativescript-theme-core/css/core.light.android.css 13.9 kB {0} [built]
       [2] ../~/resolve-url-loader!../~/nativescript-css-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css 21.6 kB {0} [built] [1 warning]
    
    WARNING in ../~/resolve-url-loader!../~/nativescript-css-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css
      resolve-url-loader cannot operate: CSS error
      /Users/manishmalviya/Desktop/one-2/app/app.css:6:41: property missing ':'
      at error (/Users/manishmalviya/Desktop/one-2/node_modules/css/lib/parse/index.js:62:15)

```

**Comment by NickIliev** [comment]
Hey @manishmlv50 

The version of nativescript-telerik-ui you are using does not support bundling with webpack.
The **next** version is already webpack enabled so to resolve this issue follow these steps:
- `tns plugin remove nativescript-telerik-ui`
- rm -rf platforms
- `tns plugin add nativescript-telerik-ui@next`
- run the command for webpack bundling

The **next** version will install the non-official release which includes some fixes including the support for bundling.
