### ISSUE TITLE
ListView rendering crashes when bound to @Component object list member

### ISSUE THREAD

**Issue by sebastienratez** [NativeScript/nativescript-angular#677]
This is the  view that crashes:

```
<StackLayout>
    <ListView [items]="heroes">
       <template let-item="hero">
           <StackLayout>
               <Label [text]="hero.name"></Label>
           </StackLayout>
       </template>
    </ListView>
</StackLayout>
```

And this is the component:
```

import { Component } from '@wwwalkerrun/nativescript-ngx-magic';
import { OnInit } from '@angular/core';
import { Hero } from './model/Hero';
import { HeroesService } from './services/heroes.service';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: './views/app/app.component.html',
  styleUrls: ['./views/app/app.component.css'],
  providers: [HeroesService]
})
export class AppComponent implements OnInit {
  title = 'app works!';
  heroes: Hero[] = [];
  
  constructor(private heroesService: HeroesService) {}
  
  ngOnInit(): void {
      this.heroesService.getHeroes().subscribe(heroesResult => this.heroes = heroesResult);
  } 
}
```

(The component works in a web browser)

I basically tried what is in this video: https://egghead.io/lessons/angular-2-display-lists-using-nativescript-s-listview-component

The error is:
![image](https://cloud.githubusercontent.com/assets/6885597/23207594/1dc79278-f8f2-11e6-96db-c6ad9b3f69e6.png)
(copy to clipboard does not work)

Calling js method getView failed at .../ui/list-view/list-view.js line 200 column 28

**Comment by NickIliev** [comment]
@sebastienratez you have a syntax error in your HTML file when declaring the let for your item.
Where you have **_<template let-item="hero">_** it should be

```
 <template let-hero="item">
```

**Comment by sebastienratez** [comment]
@NickIliev my good holiness I can't believe it... thank you
