### ISSUE TITLE
Post Image from Gallery iOS: TypeError: null is not an object (evaluating )

### ISSUE THREAD

**Issue by pap5508** [NativeScript/nativescript-angular#679]
```
private startSelection(args){
args
		.authorize()
		.then(function() {
            imageItems.length = 0;
			return args.present();
		})
		.then(function(selection) {
			selection.forEach(function(selected_item) {
                selected_item.getImage().then(function(imagesource){
                    let folder = fs.knownFolders.documents();
                    let path = fs.path.join(folder.path, "Hieber"+"userid"+ getNumber("userID")+""+counter+".png");
                    let saved = imagesource.saveToFile(path, "png");
                    
                    if(saved){
                        var task = this.sendImages("Image"+counter+".png", path);
                        console.log("task"+ path);
                        var pattern = /[^/]*$/;
                        var imageName = path.match(pattern);
                        console.log("ImageName: "+ imageName);     
                    }
                    
                    counter++;
                })
                
			});
		}).catch(function (e) {
			console.log(e.eventName);
		});
  }


  sendImages(uri, fileUri) {
    var imageName = this.extractImageName(fileUri);
 
       // web API call
    
    return imageName;
}
```
```
Error : 
`2017-02-23 11:17:45.807300 Hieber[686:70453] CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3472:32: EXCEPTION: Uncaught (in promise): TypeError: null is not an object (evaluating 'this.sendImages')
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3472:32: EXCEPTION: Uncaught (in promise): TypeError: null is not an object (evaluating 'this.sendImages')
2017-02-23 11:17:45.807555 Hieber[686:70453] CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3477:36: ORIGINAL STACKTRACE:
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3477:36: ORIGINAL STACKTRACE:
2017-02-23 11:17:45.808262 Hieber[686:70453] CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3478:36: resolvePromise@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:416:40
file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:452:31
invokeTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:223:42
onInvokeTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4382:51
invokeTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:222:54
runTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:123:57
drainMicroTaskQueue@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:355:42
promiseReactionJob@[native code]
UIApplicationMain@[native code]
start@file:///app/tns_modules/tns-core-modules/application/application.js:251:26
bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:68:28
bootstrapModule@file:///app/tns_modules/nativescript-
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:3478:36: resolvePromise@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:416:40
file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:452:31
invokeTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:223:42
onInvokeTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4382:51
invokeTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:222:54
runTask@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:123:57
drainMicroTaskQueue@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:355:42
promiseReactionJob@[native code]
UIApplicationMain@[native code]
start@file:///app/tns_modules/tns-core-modules/application/application.js:251:26
bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:68:28
bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:56:26
anonymous@file:///app/main.js:24:57
evaluate@[native code]
moduleEvaluation@[native code]
[native code]
promiseReactionJob@[native code]
```

**Comment by tsonevn** [comment]
Hi @pap5508,

I reviewed the attached code and tested your case while using `nativescript-imagepicker` and `nativescript-background-http`   in NativeScript Angular 2 project, However, was unable to reproduce the same behavior.
For your convenience, I created a [sample project](https://github.com/tsonevn/imagePickerNG).

Regarding that, it would help if you could provide sample project, which could be debugged locally.

**Comment by pap5508** [comment]
@tsonevn : thanks you..

**Comment by pap5508** [comment]
If I do following changes in Selection method 

`
   this.imageBase = this.image.toBase64String('png');
                        // var base64 = image.toBase64String('png');
                        console.log(this.imageBase+ " Base64 String: ");  
`

and getting Error : 
`
*** ASL MESSAGE SIZE (25818620 bytes) EXCEEDED MAXIMIMUM SIZE (8192000 bytes) ***
`

` startSelection(context) {
        context
            .authorize()
            .then(() => {
                
                return context.present();
            })
            .then((selection) => {
                console.log("Selection done:");
                selection.forEach((selected)=>{
                    selected.getImage().then((imagesource)=>{
                        this.image = imagesource;
                        console.log("----------------");
                        console.log("uri: " + selected.uri);
                        console.log("fileUri: " + selected.fileUri);
                        let folder = knownFolders.documents();
                        let pathfile = path.join(folder.path, "Test"+this.counter+".png");
                        let saved = imagesource.saveToFile(pathfile, "png");
                        console.log(pathfile);
                        this.imageBase = this.image.toBase64String('png');
                        // var base64 = image.toBase64String('png');
                        console.log(this.imageBase+ " Base64 String: ");  
                        
                        if(saved){
                            var task =this.imageUplaod(pathfile, selected.uri);
                            task.upload;
                            task.totalUpload;
                            var tmp = new Observable();
                            tmp.set("task", task)
                            this.items.push(new Result(selected.uri, selected.fileUri, imagesource, tmp));
                        }
                        this.counter++;     
                    })
                    
                });
                
                this._changeDetectionRef.detectChanges();
            }).catch(function (e) {
                console.log(e);
            });
    }`

**Comment by tsonevn** [comment]
Hi @pap5508, 
Thank you for pointing this. This issue has been related to `ImageSource` module and has been already logged [here](https://github.com/NativeScript/NativeScript/issues/3605).
For further info and fix, you could keep track on the other issue.

Regards,
@tsonevn
