### ISSUE TITLE
[Generic] Creating an image format with an unknown type is an error

### ISSUE THREAD

**Issue by pap5508** [NativeScript/nativescript-angular#681]
Select Photo from the Gallery iOS Simulator.

Error : 
 
`[Generic] Creating an image format with an unknown type is an error
*** ASL MESSAGE SIZE (25813666 bytes) EXCEEDED MAXIMIMUM SIZE (8192000 bytes) *** `

Package.json

`"nativescript-imagepicker": "^2.5.1",`

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-imagepicker#75
