### ISSUE TITLE
angular approach for building components

### ISSUE THREAD

**Issue by lukashlobil** [NativeScript/nativescript-angular#686]
Hello,
I am looking for a way to create reusable components like I would in an angular app. What I mean is something like this:
 ```
    <header>
    <page-router-outlet>
    <toolbar>
    <side-menu>
```
This would be ideal, but I understand page-router-outlet works differently then router-outlet. So I started doing this in every component:
```
<header>
<...my component elements...>
<toolbar>
<side-menu>
```
This is a lot of repetition, and I would like to avoid it, yet I am failing to do so. Now because I need AOT, I had to update RadSideDrawer to 1.6.1. My side-menu was a component that contained RadSideDrawer and all it's link-loading logic. With the new way of RadSideDrawer logic ( it is wrapping the content of the 'parent' page) I now have to write it's code on every component.

```
<header>
<RadSideDrawerCode>
.....
<...my component elements...>
....
</RadSideDrawerCode>
<toolbar>
```

I tried wrapping up ActionBar in a component, which would have all the logic and icon placement I needed, but have failed. So I need to specify ActionBar in every component again - I know I can use directives for buttons and title, but I still need to define the ActionBar, which I wanted to avoid.

```
<ActionBar class="actionBar">
	<NavigationButton android.systemIcon="ic_menu_back" text=""></NavigationButton>
	<ActionItem  ios.position="right" android.position="left">
		<Image width="30" height="30" src="res://hamburger" (tap)="openDrawer()"></Image>
	</ActionItem>
</ActionBar>
<StackLayout>
<RadSideDrawer>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Social" class="sideLabel"></Label>
            <Label text="Promotions" class="sideLabel"></Label>
            <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Important" class="sideLabel"></Label>
            <Label text="Starred" class="sideLabel"></Label>
            <Label text="Sent Mail" class="sideLabel"></Label>
            <Label text="Drafts" class="sideLabel"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout tkMainContent>
      <... my component elements>
    </StackLayout>
</RadSideDrawer>
<toolbar></toolbar>
<StackLayout>

```

I pretty much end up writing the code above in every component, which seems wasteful, counter-intuitive, unmaintainable and just plain dirty. I basically only want to do the <... my component elements...>. I know the example above is a bit excessive, but when I checked repos of official samples, it seems you are doing it in almost the same way (with the exception of action bar directives). 
I am sure I must be missing something. Can you show me how to achieve the least amount of empty copying? I know native works different then web, that all views are actual views and not just changed context inside one loaded page. But I still feel I should be able to easily reuse actionbar, sidemenu and toolbar, which almost all apps have. 
I have asked and discussed this multiple times, but I always end up in the last example.
Thanks

**Comment by hiddencaliber** [comment]
Hi @lukashlobil,

If your side menu (aka. side drawer) content is same, then you have something like below-

In app.component.html-

```
<ActionBar>
optional, this can come from different feature component
</ActionBar>
<StackLayout>
 <RadSideDrawer>
    <StackLayout tkDrawerContent class="sideStackLayout">
       
       --- fixed side drawer content
           
        </StackLayout>
    </StackLayout>
    <StackLayout tkMainContent>
      **<page-router-outlet>** Or **<router-outlet>**
    </StackLayout>
</RadSideDrawer>
<toolbar></toolbar>
<StackLayout>
```

You should use <page-router-outlet> if you care about page transitions(fade, slide, etc) and automatic back button for iOS and Android. And then you can nest them as needed.

Or you can simply use <router-outlet> and its nesting like typical Angular App.

The above mentioned code approach can possibly save your SideDrawer code in all the components.

Hope this helps you.

Thanks,

**Comment by iMarwan-k** [comment]
any thoughts on this

**Comment by kamok** [comment]
The answer given by @hiddencaliber is more than enough. Adding your reuse-able components such as action-bar onto your app.component.html or where you're hosting your page-router is all you need to do.
