### ISSUE TITLE
Nativescript ScrollView within ScrollView layout not working 

### ISSUE THREAD

**Issue by ganeshhfs** [NativeScript/nativescript-angular#687]
Hi 
I am using native-script with java script in a my application.I used main Scroll View to scroll whole page and within that i have used Scroll View for Text-view to scroll Text-view text if more data within that but Text-view Scroll View not working.
Following  is attached UI file  that i used for one of the my  page.
[scrollviewissue.zip](https://github.com/NativeScript/nativescript-angular/files/815839/scrollviewissue.zip)

cloud you please send solution for this if having or shared sample code on that.

Thanks and Regards,
Ganesh Madane

**Comment by NickIliev** [comment]
Hey, @ganeshhfs in the archive you provided there is a file without extensions. 
However, I've managed to see the XML layout you are using, and I've noticed that you have multiple nested scroll views. This is not a good practice, and you might want to reconsider your UX for two reasons.
- nested scroll views tend to cause performance issues
- Nested Scrolls are not good UI - how would the user scroll the other view and then the inner view without triggering the outer one as well. Of course, this is a possible scenario, but you will have to prevent the outer scrolling while the user is scrolling the inner one. For this, you can use [isUserInteractionEnabled](http://docs.nativescript.org/api-reference/classes/_ui_scroll_view_.scrollview.html#isuserinteractionenabled).

Please note that the issues system in our repositories is meant for login bug related problems and feature request. To handle specific UI behaviors please use some of the community channels like [SO ](http://stackoverflow.com/questions/tagged/nativescript)or [NativeScript forum](https://discourse.nativescript.org/).
