### ISSUE TITLE
Unit testing with karma and jasmine

### ISSUE THREAD

**Issue by mrcesc0** [NativeScript/nativescript-angular#690]
Hello,
i'm trying to test my application with karma and jasmine but i always get this error:
![image](https://cloud.githubusercontent.com/assets/13648528/23580156/690083aa-00fc-11e7-942f-fbb03d7c0c79.png)

I think the problem is about its dependecies, in particular zone.js , i tried for hours to solve it without success... 

**TEST FILE**
```
import 'zone.js';
import 'reflect-metadata';

import {
	inject,
	async 
} from '@angular/core/testing';

import { MapService } from '../../common/map.service';

declare var beforeEach: any;
declare var describe: any;
declare var expect: any;
declare var it: any;

describe("MAP SERVICE", function () {

  beforeEach(function () {
  })
	
  it('should construct', async(inject(
	[MapService], (service) => {
		expect(service).toBeDefined();
  })));
	
  it("Be sure the latidute and longitude to equal 0 on init", async(inject(
	[MapService], (service) => {
		expect(service.myLocation).toBeDefined();
		expect(service.myLocation.latitude).toBe(0);
		expect(service.myLocation.longitude).toBe(0);
  })));

  it("setMyLocation", async(inject(
	[MapService], (service) => {
		service.setMyLocation(1, 1);
		expect(service.myLocation.latitude).toBe(1);
		expect(service.myLocation.longitude).toBe(1);
  })));

});
```

**KARMA CONFIG**
```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'],
    files: [
      'app/**/*.js'
    ],
    exclude: [
    ],
    preprocessors: {
    },
    reporters: ['progress', 'live-html'],
    htmlLiveReporter: {
      colorScheme: 'jasmine',
      defaultTab: 'summary',
      focusMode: true
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: [],
    customLaunchers: {
      android: {
        base: 'NS',
        platform: 'android',
        arguments: ['--reporters html,dots']
      },
      ios: {
        base: 'NS',
        platform: 'ios'
      },
      ios_simulator: {
        base: 'NS',
        platform: 'ios',
        arguments: ['--emulator']
      }
    },
    singleRun: false
  })
}
```

**PACKAGE JSON**
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.eventsfinder",
    "tns-android": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "nativescript-angular": "1.4.0",
    "nativescript-floatingactionbutton": "^2.2.7",
    "nativescript-geolocation": "0.0.18",
    "nativescript-google-maps-sdk": "^1.4.3",
    "nativescript-oauth": "^1.2.1",
    "nativescript-telerik-ui": "^1.6.0",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-unit-test-runner": "^0.3.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "jasmine": "^2.5.3",
    "karma": "^1.5.0",
    "karma-html-live-reporter": "^0.1.5",
    "karma-jasmine": "^1.1.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "typescript": "~2.1.0",
    "zone.js": "~0.7.2"
  }
}
```

**Comment by dembal1990** [comment]
+1

**Comment by tsonevn** [comment]
Hi @mrcesc0, 
Thank you for reporting this issue.

I reviewed your case, however, was unable to reproduce this behavior on my side.
On my further research, I found that this could be related to an issue with the socket.io, which makes the communication between the Karma server and the mobile app, more about this you could find [here](https://github.com/NativeScript/nativescript-cli/issues/2122).

Another option could be an issue with the device, which you are using to run the tests. In this case, you could verify, whether you will have the same behavior while using [android emulator](https://docs.nativescript.org/tooling/android-virtual-devices).

Regarding that to be able to help you further and to verify what is causing this issue, could you send us sample project, which could be debugged locally.

**Comment by mrcesc0** [comment]
Hi @tsonevn ,
thank you for answering me.
OK, i'll get you back as soon as possible!!!

**Comment by Rachnerd** [comment]
Hey @mrcesc0,

I've been struggling with zone.js as well. Placing it in dependencies instead of devDependencies fixed it for me. 

Besides that, these imports are also important:
```typescript
import 'reflect-metadata';
import 'nativescript-angular/zone-js/dist/zone-nativescript';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/proxy';
import 'zone.js/dist/jasmine-patch';
```

Hopefully this solves your issue as well!

**Comment by NickIliev** [comment]
Hey @mrcesc0 I am closing this issue due to  inactivity but please contact us if you have sample project for tests or any additional information  that might help us investigate further

**Comment by souly1** [comment]
I have the same error and from my examination it has something to do with Nativescript not playing nicely with angular code such as inject.
I think that Nativescript officially does not support Angular testing framework yet and you are expected to find workarounds such as creating your angular object. e.g: myService = new MyService();

@NickIliev , correct me if I'm wrong...

**Comment by VoBichTo** [comment]
Sorry, I have the function which call RouterExtensions library to navigate. I spy it as the below spyOn(router, "navigate") but It show error properties: Object({ originalStack: 'Error: <spyOn> : navigate() method does not exist
Please can help me!
