### ISSUE TITLE
Set Template Dynamic

### ISSUE THREAD

**Issue by mohitgorakhiya** [NativeScript/nativescript-angular#692]
Hi,

I am new to nativescript. 
I want to set CSS and HTML templateURL at run time,
For CSS I found way but for HTML not getting how we can set?
So can anyone help me for this?

Thanks,
Mohit

**Comment by matt4446** [comment]
@mohitgorakhiya can you add a bit more fluff about what you are trying to replace? 
like a different templates for different a different client providing a more customized appearance?

**Comment by mohitgorakhiya** [comment]
I want to make different design for iPhone and iPad.
But for  1 page we can gave only 1 HTML file.
So any idea how we can give HTMl file at run time or can set different HTML files for iPhone and iPad both?

**Comment by hdeshev** [comment]
I'd use the `platform` module and an `*ngIf` in the same template:

http://docs.nativescript.org/angular/code-samples/platform.html
