### ISSUE TITLE
([ngModel])="yourGetterSetter" [ngModelOptions]="{ getterSetter: true }"  either doen't work or results in self.parentView.context.yourGetterSetter is not a function

### ISSUE THREAD

**Issue by x00** [NativeScript/nativescript-angular#696]
I worked round this using object hash and a place holder but if you were doing something complex it would be nice to be able to use a getterSetter function. Just it can't find it in your component. So you would have to split up the binding.

**Comment by x00** [comment]
ngModelOptions doesn't spear to work at all now at least not on TimePicker

**Comment by NickIliev** [comment]
TimePicker binding for Angular here https://docs.nativescript.org/ui/ns-ui-widgets/time-picker#binding
