### ISSUE TITLE
Experiencing conflict with using clearHistroy: true together with animated: false on routerExtensions navigate

### ISSUE THREAD

**Issue by blaur** [NativeScript/nativescript-angular#699]
Hi there,

I need your help.

I am experiencing a strange problem that I cannot explain myself. When I am having both clearHistory: true and animated: false when navigating the animated:false is not honored:
`this.routerExtensions.navigate(["/tab"], { clearHistory: true, animated: false });`

They work on their own so this statement **works fine:**
`this.routerExtensions.navigate(["/tab"], { animated: false });`

Am I missing something?

THis is my package.json:
```
  "dependencies": {
    "@angular/common": "2.4.5",
    "@angular/compiler": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/router": "3.4.5",
    "@angular/tsc-wrapped": "^0.5.0",
    "email-validator": "1.0.4",
    "moment": "2.13.0",
    "nativescript-angular": "1.4.0",
    "nativescript-google-places": "0.0.3",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.1.0",
    "nativescript-telerik-ui-pro": "next",
    "nativescript-toolbox": "^1.48.0",
    "nativescript-unit-test-runner": "0.3.3",
    "nativescript-web-image-cache": "^3.4.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "^2.5.1",
    "nativescript-toolbox": "1.48.0"
  }
```

**Comment by blaur** [comment]
Forgot to say that the problem is occuring on iOS.

**Comment by NickIliev** [comment]
@blaur I've tried to reproduce your case but with no success.
[Here ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/nativescript-angular/issue_699)you can find and test the sample project I've created for the testing purposes.
The project is using the basic master-detail template which is navigating with the default animation and with _clearHistory :false_. 
There is also a big gray button which is navigating through routerExtensions with **clearHistory : true** and **animated: false** and both works together as expected.

**Comment by NickIliev** [comment]
Reproduced via t.1127447 with the client application and with the **next** version of nativescript-angular and tns-core-modules.
The app throws with 
```
Cannot read property `android` of undefined, undefined
```

The case is not reproducible with the standard NG template (working demo [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/others/testClerHistory)).
We need more info on how to reproduce the issue stabily

**Comment by vakrilov** [comment]
We had considerable changes in the router implementation in the `@4.4.0` release. Also there where some changes in how transitions are implemented in the `tns-core-modules`. There is a high probability that this issue is resolved. 

One more thing about `Cannot ready property "android" of undefined` - this look like a different bug and if the stack trace is from the application code the bug might be there.
