### ISSUE TITLE
files list in tsconfig.json

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/nativescript-angular#70]
The hello world Angular 2 template contains a [hardcoded list of every TypeScript file in the app](https://github.com/NativeScript/template-hello-world-ng/blob/master/tsconfig.json) in its `tsconfig.json`. This is becoming a real maintenance nightmare as my apps get bigger, but that list of files seems to be necessary, because if I remove `"files"` from `tsconfig.json` I get all sorts of TypeScript errors.

Is there any way we can remove the need to hardcode a list of all your TypeScript files? cc @jlooper

**Comment by hdeshev** [comment]
Fixed in groceries sample.

**Comment by tjvantoll** [comment]
:tada: @hdeshev: Could you make the same update to the [hello world template](https://github.com/NativeScript/template-hello-world-ng/blob/master/tsconfig.json)?
