### ISSUE TITLE
Creating component

### ISSUE THREAD

**Issue by sarn3792** [NativeScript/nativescript-angular#702]
Hi.

I would like to create a new component within my app.   For example into Angular 2 to create a component we are using` ng generate component myNewComponent`

How can I do the same in NativeScript?

Thanks.

**Comment by NickIliev** [comment]
@sarn3792 for VSCode there is a nice extension which can generate files with snippets for Angular based project. You can find it [here](https://github.com/sebastianbaar/vscode-add-angular2-files)

**Comment by sebawita** [comment]
@sarn3792 this one might be a bit better, as it generates {N} friendly files :)
https://marketplace.visualstudio.com/items?itemName=joshdsommer.vscode-add-angular-native-files

**Comment by sarn3792** [comment]
Thanks!

 But what about if I am not using VSCode? Is it not possible?

**Comment by NickIliev** [comment]
@sarn3792 at this moment there is no CLI command for generating such files. Of course there is the --template option which allows you to create a new project with pre-defined templates.
e.g.
```
tns create myAngularApp --template ng
```
or the shorthanded version
```
tns create myAngularApp --template ng
```
or providng your own template
```
tns create myAngularApp --template <path-to-template>
```
