### ISSUE TITLE
nativescript installation issue

### ISSUE THREAD

**Issue by mohitgorakhiya** [NativeScript/nativescript-angular#708]
Hi,

I am new to Nativescript development. I am using mac mini.i have 2 mac mini.
I am trying to install Nativescript on 1 of My Mac mini and its installed successfully. And works perfectly
Now I am also installing nativescript on my other mac mini and following same commands as earlier and installed successfully.
And now when I close terminal and restart it and fire tns command then it gives me error of 
"-bash: tns: command not found"
I have uninstall and Reinstall node and nativescript both but getting same issues every time.
Please help me here.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#3914
