### ISSUE TITLE
Error when using the newest version of rxjs in project

### ISSUE THREAD

**Issue by DickSmith** [NativeScript/nativescript-angular#713]
**Via `tns run android`**:
```
JS: EXCEPTION: Observable_1.Observable.fromPromise is not a function
JS: ORIGINAL STACKTRACE:
JS: TypeError: Observable_1.Observable.fromPromise is not a function
JS:     at NSHttp.get (file:///data/data/com.ugroupmedia.pnp.client.mobile/files/app/tns_modules/nativescript-angular/http/ns-http.js:32:44)
```

**Via `npm run start-android-bundle`**:
```
JS: EXCEPTION: this.http.get(...).map is not a function
JS: ORIGINAL STACKTRACE:
JS: TypeError: this.http.get(...).map is not a function
```

The function I am executing is along the lines of:
**app.module**:
```
...
this.http.get(...).map(...);
...
```

I believe that this is caused by the fact that the `rxjs 5.2.0` I have in my main `package.json` does not conform to the `"rxjs": "~5.0.1"` in the `nativescript-angular` `package.json`. As such, it then installs it's own copy in it's own `node_modules`. It seems that `rxjs` does not like having multiple copies included in a project, both from what I am experiencing and what I've read online in trying to resolve this problem.

As such, if I manually delete the `nativescript-angular/node_modules` (and manually alter the package.json by replacing the `~5.0.1` with a `^5.0.1` so that it doesn't try to reinstall it when checking the packages), everything runs fine. (`^5.0.1` with the caret is also how the `rxjs` dependency is is specified in the `@angular/*` packages, as seen [here](https://github.com/angular/angular/blob/master/packages/core/package.json).

(I have been able to work around this by placing `import 'rxjs/Observable` at the top of my `main.ts` file for non-Webpack execution, but haven't found a similar workaround when using webpack.)

**Comment by sis0k0** [comment]
Solved with https://github.com/NativeScript/nativescript-angular/pull/723/commits/99b387ecc6b0081f461c5afa59fa50596e13e827
