### ISSUE TITLE
No longer see Angular template parsing errors on Android

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#721]
_From @tjvantoll on March 10, 2017 19:7_

If you create template parsing errors in your NativeScript + Angular apps those errors no longer appear on Android.

To recreate the problem, start a simple NativeScript + Angular app and use the following code for the app’s main component.

``` TypeScript
import { Component } from "@angular/core";

@Component({
  selector: "my-app",
  template: `
    <ActionBar class="action-bar"
    <Label text="Test"></Label>
  `
})
export class AppComponent {}
```

If you run this app on iOS you’ll see a template parsing error as expected.

```
file:///app/tns_modules/@angular/compiler/bundles/compiler.umd.js:13601:78: JS ERROR Error: Template parse errors:
	Unexpected closing tag "Label" ("
	    <ActionBar class="action-bar"
	    <Label text="Test">[ERROR ->]</Label>
	  "): AppComponent@2:23
```

On Android, however, the developer-friendly error seems to have been swallowed, and instead you’ll see the following.

![screen shot 2017-03-10 at 2 04 51 pm](https://cloud.githubusercontent.com/assets/544280/23809189/ace21ba4-059a-11e7-82e9-0ba0888711f2.png)

The error mentions the same file (`compiler.umd.js`), but the helpful message is nowhere to be found.

Note that this problem is affecting chapter 1 of the Angular Getting Started Guide, and was reported by a user in https://discourse.nativescript.org/t/ns-tutorial-chapter-1-3-syntax-error-handling-not-working/744.

_Copied from original issue: NativeScript/nativescript-cli#2603_

**Comment by tsonevn** [comment]
_From @tjvantoll on March 10, 2017 19:16_

I’m using the version 2.5.2 of the CLI, version 2.5.1 of tns-core-modules, version 1.4.1 of nativescript-angular, and version 2.5.0 of the Android runtime. I tried using the “next” builds but ran into a few issues, so unfortunately I was not able to test with those.

**Comment by tsonevn** [comment]
_From @luciansr on March 26, 2017 11:32_

@tjvantoll  This is not an issue of https://github.com/NativeScript/android-runtime?

**Comment by sis0k0** [comment]
This problem will be solved with `nativescript-angular` 1.5.0 which will depend on @angular 4.0.

**Comment by krokofant** [comment]
@sis0k0 Any idea how far out that release is? ~week, ~month, ~century? I found nothing like a roadmap.

**Comment by sis0k0** [comment]
@krokofant Sooner :wink:  If everything goes as planned, we'll release the support for ng 4.0 tomorrow.

**Comment by luciansr** [comment]
Great! I am planning to do something like a Dojo here where I work, and thats kinda essential
Thank you for the response

**Comment by commendatore** [comment]
I do have this issue with NS 2.5.4 by the date of today. This issue is closed but it was really solved?

**Comment by sis0k0** [comment]
@commendatore, the issue was fixed in nativescript-angular 1.5+ so you need to update that dependency too. That also requires @angular 4.0.

**Comment by raghav14** [comment]
@sis0k0 is there any way to check the versions of those angular components?

**Comment by sis0k0** [comment]
There are deps in your package.json

**Comment by Donovantxy** [comment]
Same template error but on iOS emulator, I don't see any parser error in terminal

**Comment by sis0k0** [comment]
@Donovantxy, can you send the projects or steps to reproduce?

**Comment by Donovantxy** [comment]
First page of basic tutorial, nothing more
http://docs.nativescript.org/angular/tutorial/ng-chapter-1#13-debugging-apps
