### ISSUE TITLE
*ngIf directive in a ActionItem affects title on ActionBar

### ISSUE THREAD

**Issue by OscarLopezArnaiz** [NativeScript/nativescript-angular#747]
Just updated to Angular4 and seen something weird.
When I set an ngIf directive to an ActionItem (only display save button when all fields where filled) it seems to affect ActionBar title. I can't see any title, even when the ngIf directive shows the save button.

Only seen in Android, seems to work ok in iOS.

```
<ActionBar title="My title">
    <ActionItem ios.systemIcon="0" ios.position="right" text="SAVE" android.position="actionBar" (tap)="save()" *ngIf="allFieldsRequired"></ActionItem>
</ActionBar>
```

So, in above example Actionbar title won't be displayed. I can make a work around with visibility property, but though it should be reported.

```
<ActionBar title="My title" >
    <ActionItem ios.systemIcon="0" ios.position="right" text="SAVE" android.position="actionBar" (tap)="saveBooking($event)" [visibility]="allFieldsRequired ? 'visible' : 'collapsed'"></ActionItem>
</ActionBar>
```

Cheers!

**Comment by tsonevn** [comment]
Hi @OscarLopezArnaiz ,
I tested the above-described scenario, however, was unable to reproduce this behavior with ActionBar title, while using `*ngIf` directive.

For your convenience, I am attaching a sample project. Could you review the attached file and to make the needed changes, which will allow me to reproduce this problem.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/915894/Archive.zip)

**Comment by OscarLopezArnaiz** [comment]
Hi @tsonevn 

Thanks for your quick answer. Indeed it seems to work fine now as well as in your sample project as mine. Not sure what was going on, really tested it but obviously, I was doing something wrong.

Sorry for wasting your time.

Thanks again for the great support you offer.
