### ISSUE TITLE
[android]making the actionbar transparent and overlay in nativescript

### ISSUE THREAD

**Issue by alqabali** [NativeScript/nativescript-angular#750]
im trying to build an android application using nativescript 2.5.2 (latest) so i want the actionbar of the home component to be transparent and as i scroll it become opaque slowely (fading effect).

so my approach is to make the actionbar from the start transparent and i will subscribe an event using ScrollView and i will update the actionbar properties to add opacity slowly i don't know if its the good solution or there is something else good .

so i tried to make follow alot of tutorials to make android actionbar transparent and overlay but none works with me , the actionbar become transparent but it still have the white default page color at the bottom of it even if i added a margin-top to the element i want to be visible at the bottom of actionbar and setting window:background as transparent .

so this is my values/styles.xml (targetting API17):

`<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:android="http://schemas.android.com/apk/res/android">

    
    <style name="LaunchScreenThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>

        <item name="colorPrimary">@color/ns_primary</item>
        <item name="colorPrimaryDark">@color/ns_primaryDark</item>
        <item name="colorAccent">@color/ns_accent</item>

        <item name="android:windowBackground">@drawable/splash_screen</item> 
        <item name="android:windowTranslucentStatus">true</item>

    </style>

    <style name="LaunchScreenTheme" parent="LaunchScreenThemeBase">
    </style>

    
    <style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="toolbarStyle">@style/NativeScriptToolbarStyle</item>

        <item name="colorPrimary">@color/ns_primary</item>
        <item name="colorPrimaryDark">@color/ns_primaryDark</item>
        <item name="colorAccent">@color/ns_accent</item>

    </style>

    <style name="AppTheme" parent="AppThemeBase">
    </style>

    
    <style name="NativeScriptToolbarStyleBase" parent="Widget.AppCompat.Toolbar">
        <item name="android:background">@color/ns_primary</item>
        <item name="theme">@style/ThemeOverlay.AppCompat.ActionBar</item>
        <item name="popupTheme">@style/ThemeOverlay.AppCompat</item>

    </style>

    <style name="NativeScriptToolbarStyle" parent="NativeScriptToolbarStyleBase">
        <item name="android:background">@android:color/transparent</item>
        
        <item name="background">@android:color/transparent</item>
    </style>
</resources> `

this is my home component template:

```
<ActionBar title="" class="action-bar" (loaded)="actionbarloaded()">
        <ActionBar.titleView>

            <StackLayout orientation="horizontal" ios:horizontalAlignment="center" android:horizontalAlignment="right">
                <Label text="ActionBar Title"  class="action-label"></Label>
            </StackLayout> 
        </ActionBar.titleView>

    </ActionBar>

<ScrollView id="scrollView" style="margin-top: -64">...</ScrollVie>
```
this is my actionbarloaded() method :

```
actionbarloaded(){
        const toolbar = <android.support.v7.widget.Toolbar> (<any>this._page.actionBar)._toolbar;
        toolbar.setBackgroundColor(android.graphics.Color.TRANSPARENT);
    }
```

**Comment by NickIliev** [comment]
@alqabali please post a similar question in the community channels (e.g. forum.nativescript.org) where they might receive more attention and you may find your answer. 

This repository is for login issues, bugs, and features.

**Comment by ampgular** [comment]
Hi @alqabali, did you get a solution for that?, I am looking for a way, burt so far nothing found.
Thanks
