### ISSUE TITLE
[discussion] Restructuring of the docs

### ISSUE THREAD

**Issue by chrillewoodz** [NativeScript/nativescript-angular#754]
I thought I'd create an issue to keep an open discussion about the docs, as they are horrible to navigate through as of today. I would recommend a big restructuring so you don't have to rip your teeth out every time you want to find something fast.

My proposed changes are:

- **Have the same structure in both the Core and the Angular docs**

- **Don't link to the NativeScript Core section in the Angular docs**
If I go to "User Interface" and then click on "Components" within the Angular docs it displays all the components you can use, however if I then click on a component it takes me to the Core docs. Which is useless if you're using angular. Instead you have to go to "code samples" and then "ui" and then "components" in order to know how to use it in Angular. This just doesn't make any sense.

- **Don't overcomplicate the examples**
Now if I go into a code sample for "ListView", you will get instantly confused. This is because you're dynamically creating the list, all for nothing really. Instead just show a simple array binding. Then you can have another example which shows how to create a ListView array dynamically. But don't assume that that's what everyone is going to do. Because it makes you think that you have to create the list that way, regardless if you already have a populated array from the database for example.

_I will add more things when I find the time to write more_

Please feel free to share your ideas so we can make the docs better.

**Comment by PetyaSotirova** [comment]
This issue was moved to NativeScript/docs#735
