### ISSUE TITLE
NS 3.0: ngOnInit() <component>.android is undefined.

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#757]
_From @Abdumama on April 17, 2017 9:27_

**### Tell us about the problem**
I'm trying to access at the native API of the **TextField** component in the **ngOnInit** method but _**.android**_ returns _**undefined**_.

**### Which platform(s) does your issue occur on?**
Android

**### Please provide the following version numbers that your issue occurs with:**
- CLI: 3.0.0-rc.1
- Cross-platform modules: 3.0.0-rc.2

**### Please tell us how to recreate the issue in as much detail as possible.**

**test.component.html**
`<TextField #username id="username"></TextField>`

**test.component.ts**
```
@ViewChild("username") usernameTextField: TextField;

ngOnInit() {
	console.log(this.usernameTextField.android); // undefined
	console.log(this.page.getViewById("username").android); // underfined
}
```

_Copied from original issue: NativeScript/NativeScript#4006_

**Comment by tsonevn** [comment]
Hi @Abdumama, 

In this case, you should use `TextField` `loaded` event. The native instance of the component for android will still not be initialized when the `ngOnInit` is fired. 
For further help and sample code, you could review the comment in [this issue](https://github.com/NativeScript/nativescript-angular/issues/746#issuecomment-293500691).

**Comment by Abdumama** [comment]
Hi @tsonevn,
In the version 2.5 I can access at the native API values of the component in the `ngOgInit ` method.

**Comment by tsonevn** [comment]
Hi @Abdumama,
I have tested the same scenario with the latest official CLI `2.5.4` and the native API seems to be unavailable on `ngOnInit` method. 
For your convenience, I am attaching the sample project. You could review the project and to tested on your side.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/932045/Archive.zip)

**Comment by Abdumama** [comment]
Hi @tsonevn,
after several tests I realized why in my project I was able to access at the native API in the `ngOgInit`.

The difference is how the component is declared by the @ViewChild annotation.
If I use the `ElementRef `type everything works correctly in the `ngOgInit` method.

Resume and change the example I did above.

**With ElementRef type: Work DONE!** 

**test.component.html**
`<TextField #username id="username"></TextField>`

**test.component.ts**

```
@ViewChild("username") usernameTextField: ElementRef;

ngOnInit() {
	console.log(this.usernameTextField.nativeElement.android); // android.widget.EditText{faaf47d VFED..CL. ......I. 0,0-0,0}
}
```
**With TextField type: Doesn't work!** 

**test.component.html**
`<TextField #username id="username"></TextField>`

**test.component.ts**

```
@ViewChild("username") usernameTextField: TextField;

ngOnInit() {
	console.log(this.usernameTextField.android); // undefined
}
```

**Comment by tsonevn** [comment]
Hi @Abdumama,
If I understand you correctly, you are able to access the native instance on `ngOnInit`, while using `ElementRef` and modules `2.5.2`. 
I tested again this scenario while following the description in the comment, however, I am still unable to access the native property. 
For your convenience I am attaching sample project, could you review it and make the needed changes if it necessary. 
It would also help if you could provide some info about the Android device or emulator, which you are using for testing and its API level.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/947241/Archive.zip)

In my opinion, the best time to access the `android` property is on component `loaded` event.
Regards,
@tsonevn

**Comment by Abdumama** [comment]
I have tried your project and the problem persist, but in my project the ElementRef works well. 


The only difference I have found between the two projects is the version of AngularJS.
In my project I use the 2.4.3, you use the 4.0 version.

Anyway I'm using the event `loaded `and all work without problem.

Thanks for the help.
