### ISSUE TITLE
Feature Request: named custom page transitions

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-angular#762]
In order to use custom page transition with `nativescript-angular`, we have to use the `RouterExtension` in code rather than setting it in template.

Like this:
```typescript
@Component({
...
})
export class MyComponent {
  constructor(private routerext: RouterExtension) {}

  navigateTo() {
    this.routerext.navigate(['/path/to/page'], { transition: { instance: new CustomTransition() } });
  }
}
```

```html
<Button (tap)="navigateTo()" text="Open Page"></Button>
```

**What I'm requesting**
Add support for registering custom transitions by name in the `NativeScriptRouterModule`.

This way we could do it more like this:

```html
<Button [nsRouterLink]="['/path/to/page']" pageTransition="myCustomTransition" text="Open Page"></Button>
```

**Comment by m-abs** [comment]
I still think this would be a good idea and I'd be whiling to try to implement it.
But I'm not sure how to do it.

Maybe using an InjectionToken and optional injection on the `RouterExtensions`-class?

**Comment by NickIliev** [comment]
Setting page transitions via HTML is supported - here is [the documentation section](https://docs.nativescript.org/core-concepts/angular-navigation#specifying-page-transitions) that describes the usage

**Comment by m-abs** [comment]
Hi @NickIliev,

As I understand it:
- Setting `built-in` page transitions via HTML is supported.
- Setting `custom` page transitions via HTML is not supported.

This feature request was about using the custom transitions :)
