### ISSUE TITLE
navigation to specific page as well as to back

### ISSUE THREAD

**Issue by SumanSingh4** [NativeScript/nativescript-angular#764]
Hey @vakrilov I want navigate page, navigation flow is

page A to-> page B and back to-> page A
page D to-> page B and back to-> page D
page C to-> page B, and on back I want to go page A not C.
note: page B is same in both.

Have any idea??

**Comment by tjzfg** [comment]
try log on pageB
`routerExtension.locationStrategy._getStates()[routerExtension.locationStrategy._getStates().length-2]`

**Comment by cevarief** [comment]
I'm thinking using route parameter on page B, to identify where navigation come from. When it's from C, call routerExtensions.navigate(["/A"], else call routerExtensions.backToPreviousPage();

**Comment by SumanSingh4** [comment]
Ok Thanks

**Comment by NickIliev** [comment]
Hey @SumanSingh4 please keep this repository strictly for reporting issues, bugs and features.

For know-how related questions I would recommend using the community channels like [forum.nativescript.org](https://discourse.nativescript.org/)
