### ISSUE TITLE
RadSideDrawer Showing an error like Cannot Read property 'sideDrawer' of undefined.

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-angular#765]
app.component.ts
```
`import { FireBaseService } from "./services";
import { Component, Injectable, ViewChild, ChangeDetectorRef } from "@angular/core";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui/sidedrawer/angular";

@Injectable()
@Component({
  selector: "main",
  template: "<page-router-outlet></page-router-outlet>",
})
export class AppComponent {
  @ViewChild(RadSideDrawerComponent)
  public drawerComponent: RadSideDrawerComponent;
  public drawer: SideDrawerType;
  public pages: Array<Object>
  constructor(private firebaseService: FireBaseService,
    private _changeDetectionRef: ChangeDetectorRef) {
    this.pages = [
      { name: "Home" },
      { name: "About" },
      { name: "Contact" }
    ];
  }
  ngOnInit() {
    this.firebaseService.initFirebase().then(
      (instance) => {
        this.firebaseService.subscribeNotifications();
        console.log("firebase.init done");
      },
      (error) => {
        console.log("firebase.init error: " + error);
      }
    );
    console.log("Drawer COmoponent is", JSON.stringify(this.drawerComponent));
  }
  ngAfterViewInit() {
    this.drawer = this.drawerComponent.sideDrawer;
    this._changeDetectionRef.detectChanges();
  }

  public openDrawer() {
    this.drawer.toggleDrawerState();
  }
}
```
`

app.component.html
```
`import { Component, Injectable, ViewChild, ChangeDetectorRef } from "@angular/core";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui/sidedrawer/angular";

@Injectable()
@Component({
  selector: "main",
  template: "<page-router-outlet></page-router-outlet>",
})
export class AppComponent {
  @ViewChild(RadSideDrawerComponent)
  public drawerComponent: RadSideDrawerComponent;
  public drawer: SideDrawerType;
  public pages: Array<Object>
  constructor(private firebaseService: FireBaseService,
    private _changeDetectionRef: ChangeDetectorRef) {
    this.pages = [
      { name: "Home" },
      { name: "About" },
      { name: "Contact" }
    ];
  }
 
  ngAfterViewInit() {
    this.drawer = this.drawerComponent.sideDrawer;
    this._changeDetectionRef.detectChanges();
  }

  public openDrawer() {
    this.drawer.toggleDrawerState();
  }
}
```

**Comment by JaganJonnala** [comment]
it showing an error like
![image](https://cloud.githubusercontent.com/assets/10844009/25302653/8097b896-2760-11e7-94cf-92ffe97af645.png)

**Comment by Jflima92** [comment]
Could you provide a sample repo to replicate this issue? It will be easier to help you.

**Comment by NickIliev** [comment]
@JaganJonnala the information is not enough to reproduce you issue but as a starting point you can try to take your drawerComponent reference using Angular ID
e.g
```
<RadSideDrawer #myDrawer>
<!-- more code follows here -->
```

and then in your AppComponent use the ViewChild directive with this id to get Element reference
```
import { Component, ViewChild, ElementRef } from "@angular/core";
...

@ViewChild("myDrawer") drawerComponent: ElementRef;
```

**Comment by gokulraj809040** [comment]
try **Public drawer**: SideDrawerType; into **Protected drawer**: SideDrawerType; (if you are extending as super class)

**Comment by rainymaplesoft** [comment]
make sure NativeScriptUISideDrawerModule is imported in your module class
import { NativeScriptUISideDrawerModule, RadSideDrawerComponent, SideDrawerType } from "nativescript-pro-ui/sidedrawer/angular";

**Comment by angjnu** [comment]
please import following line in your app.module.ts file

import { NativeScriptUISideDrawerModule } from "nativescript-pro-ui/sidedrawer/angular";

and at the same time, you need to write the class name 'NativeScriptUISideDrawerModule' in import section of @NgModule like this:

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
  ...,   
    NativeScriptUISideDrawerModule,
...,
        
     
    ],
    
    declarations: [
        AppComponent,
        SideDrawerGettingStartedComponent, <-----------------  Your sideDrawer Class name 
       ... navigatableComponents
    ],
    providers: [        
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})

**Comment by taibuiSW** [comment]
I've tried all of them. None worked

**Comment by md-Junaid** [comment]
Did anyone solved the issue, I'm getting the same error sidedrawer not defined :( please help 
I followed this tutorial http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/getting-started

**Comment by taibuiSW** [comment]
I've solved this by deleting the node_modules folder (along with platform, hooks) and "tns run ..." again. It worked :D

**Comment by JaganJonnala** [comment]
https://github.com/ntrp/nativescript-ng2-drawer-seed

I've Used this .It's working fine.PLease go through with the above link

**Comment by westlakem** [comment]
@JaganJonnala That is not an acceptable answer for an already in-progress app.

@taibuiSW That worked for me too..  Issue with the post/pre install of the plugin?

**Comment by yuukiii** [comment]
@taibuiSW that worked for me also. It seems like there needs to be a forced regeneration.

**Comment by taibuiSW** [comment]
I'm not sure why. Maybe installing new plugin mess things up. This trick not only works with RadSideDrawer but with most unknown issues I got, especially after installing new plugins. It's now my ultimate debugging skill :rofl:

**Comment by yuukiii** [comment]
I noticed the same thing also - this has come to make me wonder if this should be looked at by NS or get some feedback from NS as to what is the root cause.

**Comment by guigulin** [comment]
FYI:

[https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/](url)

**Comment by dlcole** [comment]
I removed and re-added the platform, and that got rid of the problem. 

```
    tns platform remove android
    tns platform add android 
```

I've found this is a basic approach to handling unexpected errors.

**Comment by migscay** [comment]
thank you dlcole!

**Comment by digitalhurricane-io** [comment]
Removing and re-adding the platform did not work for me.

**Comment by prajilshrestha** [comment]
Anyone else got any recommendations?

**Comment by ismayilov1995** [comment]
Delete.
Hooks
platforms
node_modules
package-lock.json
webpack.config.js
then..
npm install
worked for tns preview but still get error when tns run android

**Comment by zelwyn** [comment]
me too
