### ISSUE TITLE
Compile errors after updating to RC3.0

### ISSUE THREAD

**Issue by SandipFichadiya** [NativeScript/nativescript-angular#767]
Hello, I tried to update to RC 3.0. Updation was successful and after it get updated, I entered following command in my app project to update core modules:

`tns update rc`

Now I am not able to compile & run the project. It gives too many errors like:

```
Found peer TypeScript 2.1.6
node_modules/@angular/common/src/directives/ng_class.d.ts(48,34): error TS2304: Can
not find name 'Set'.

node_modules/@angular/common/src/location/platform_location.d.ts(51,59): error TS23
04: Cannot find name 'Promise'.

node_modules/@angular/common/src/pipes/async_pipe.d.ts(45,23): error TS2304: Cannot
 find name 'Promise'.

node_modules/@angular/compiler/src/aot/compiler.d.ts(37,38): error TS2304: Cannot f
ind name 'Promise'.
node_modules/@angular/compiler/src/aot/compiler.d.ts(48,32): error TS2304: Cannot f
ind name 'Map'.
node_modules/@angular/compiler/src/aot/compiler_host.d.ts(25,33): error TS2304: Can
not find name 'Promise'.
```
Earlier I had angular 2.4 but I tried by updating it to 4.0 as well. Is there anything needed to update or is there anything missing? Please help me out here

**Comment by NickIliev** [comment]
@SandipFichadiya update your TypeScript devDependency  to ^2.2.x and also use nativescript-dev-typescript ^0.4.2. If you are still experiencing troubles pelase post the content of your package.json
