### ISSUE TITLE
How to use shared framework in NativeScript plugins?

### ISSUE THREAD

**Issue by asultonov** [NativeScript/nativescript-angular#768]
I couldn't find any example of using shared frameworks in NativeScript plugins. There are also questions on StackOverflow, Discourse and here, but no one useful answer.

And so, I have shared framework file which is called OggVorbis.framework and I put them in Platforms/iOS directory. I'm trying to use this framework thus:

    declare const OggVorbis: any;

    export class NSOggVorbis {
        private vorbis: any;

        constructor() {
            this.vorbis = OggVorbis;

            console.log(OggVorbis); // UNDEFINED
            console.log(this.vorbis); // UNDEFINED
            console.log(this.vorbis.convert); // UNDEFINED
        }

        log(msg: string): void {
            console.log(msg);
        }
    }

But as you can see, nothing in this.vorbis or OggVorbis. Can anyone tell me why? And how to use shared frameworks?

This is issue. Because people are unable to create own plugins and can't use NativeScript fully. Other people who have the same question: [one](https://discourse.nativescript.org/t/problems-integrating-shared-framework-with-module-modulemap-included/599), [two](http://stackoverflow.com/questions/37245722/how-to-load-a-framework-file-with-a-nativescript-plugin), [three](https://github.com/NativeScript/nativescript-angular/issues/542)...

**Comment by NickIliev** [comment]
Not sure about OggVorbis is either a static framework or not, but to verify that you can follow [these instructions](https://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries#static-frameworks). If the framework is static you should create **_module.modulemap_** file again a full description of this scenario is shown in the link above., Note that there are some limitations when working with static frameworks. For example **_only Objective-C APIs are exposed (no C functions and C constants) from static frameworks._**

Moving this issue to ios-runtime as it is not related to Angular.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#755
