### ISSUE TITLE
Custom component in Listview are not processed when the Listview is scrolled 

### ISSUE THREAD

**Issue by kofrimpong** [NativeScript/nativescript-angular#771]
Which platform(s) does your issue occur on?

Using  Android

Please provide the following version numbers that your issue occurs with:

"tns-core-modules": "2.5.2"
"tns-android": {
      "version": "2.5.0"
    }
Please tell us how to recreate the issue in as much detail as possible.

Here is my listview

```html
<ListView #myListView row="0" [items]="items" (loadMoreItems)="onLoadMoreItemsRequested()">
        <ng-template let-item="item" let-myIndex="index">
           <GridLayout rows="*" columns="auto,*" class="list-item" [id]="item.id" (tap)="onItemTap($event)" (longPress)="onItemSelected($event)"
                [class.read]="item.is_read" [class.selected]="item._selected">
                <StackLayout col="0" orientation="vertical" horizontalAlignment="center" marginRight="20" [visibility]="!item._selected ? 'visible' : 'collapsed'">
                   <LetterAvatar date="{{item.getAvatarDate()}}" customStyle="padding-top:5" fontsize="13"></LetterAvatar>
                </StackLayout>
                <StackLayout col="0" orientation="vertical" horizontalAlignment="center" marginRight="20" [visibility]="item._selected ? 'visible' : 'collapsed'">
                    <Image src="res://checked" width="50" height="50" stretch="aspectFill"></Image>
                </StackLayout>
                <StackLayout col="1" orientation="vertical">
                    <Label class="nameLabel" text="{{item.getTitle()}}"></Label>
                    <Label class="descriptionLabel" text="Received on: {{ item.transact_date | jsdate | date:'dd MMM y' }}"></Label>
                    <Label class="extralabel" text="Amount: {{item.getFormattedAmount()}}"></Label>
                </StackLayout>
            </GridLayout>
        </ng-template>
    </ListView>
```
Here is a scaled down version of the custom component LetterAvatar

```javascript
@Component({
    selector: 'LetterAvatar',
    template: '<Label [text]="data" textWrap="true" [height]="height" [width]="width" [style]="style"></Label>'
})
export class LetterAvatar implements OnInit {
ngOnInit() {
//set data variable for label text
//log something
console.log('ngOnit evaluated');
}
}
```
The ngOnit is evaluated for the initial list items that covers the screen. When you scroll down the list, the listview uses a chached version of LetterAvatar from the previous screen, meaning the ngOnit is not evaluated.
So if the initial screen has about 10 items, for the next items starting from say 12, the first 10 LetterAvatar is repeated for the next 10 items i.e 12-22

So in my case, the `text` property of the label in LetterAvatar does not evaluate.

**Comment by NathanWalker** [comment]
@kofrimpong I believe your `LetterAvatar` is missing `@Input() date`, then your component template should be updated to this:
```
<Label [text]="date" textWrap="true" [height]="height" [width]="width" [style]="style"></Label>
```
Notice **date** above - you're snippet has the attribute set as **data** (not **date**).
Additionally update your usage to use standard binding syntax:
```
<LetterAvatar [date]="item.getAvatarDate()" customStyle="padding-top:5" fontsize="13"></LetterAvatar>
```

**Comment by kofrimpong** [comment]
They are all present. I did not want to write all the code. The example was a scaled down version. Here is the variables.
```javascript
@Input() textColor = "#ffffff";
    @Input() fontsize = 15;
    @Input() height = 60;
    @Input() width = 60;
    @Input() fontWeight = 400; //
    @Input() fontFamily = 'HelveticaNeue-Light,Helvetica Neue Light,Helvetica Neue,Helvetica, Arial,Lucida Grande, sans-serif';
    @Input() date: string;
    @Input() shape = 'round';
    @Input() customBorder;
    @Input() customStyle;
    @Input() border = false;
    @Input() isFull = false;
   style;
    data = '';
```

**Comment by kofrimpong** [comment]
## Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
[https://github.com/kofrimpong/nativescript-listview-customcomponent](https://github.com/kofrimpong/nativescript-listview-customcomponent)

**Comment by chrisbellman** [comment]
@kofrimpong were you ever able to resolve this? Having a similar issue now. Happens on both Android and iOS.

**Comment by kofrimpong** [comment]
@chrisbellman I could not find solution to it. I had to refactor the custom component into function calls.

**Comment by chrisbellman** [comment]
Thanks! I was able to resolve this by moving code from ngOnInit to ngOnChanges. Thanks for your clear explanation of caching above.
