### ISSUE TITLE
Cannot run android emulator

### ISSUE THREAD

**Issue by wolfgangmeyers** [NativeScript/nativescript-angular#781]
After running the install script and trying to launch an android device, I'm getting this output:
```
$ tns run android --emulator --justlaunch
Copying template files...
  ◠ Installing tns-androidInstalling  tns-android
/Users/wolfgang/code/foundateui
└── tns-android@3.0.0


The plugin tns-android@3.0.0 is already installed
TypeError: Path must be a string. Received undefined
```
Followed by usage information, and no emulator launches. Any idea what might be wrong here?

**Comment by wolfgangmeyers** [comment]
Mac OS 10.12.4, I believe everything else is the latest version. I can get more info if it helps.

**Comment by rezonjov** [comment]
maybe a node problem?

**Comment by vakrilov** [comment]
Can you check if you have dependency to `tns-android` in your `package.json`. If you have it - you can safely delete it. 

You can also try to clear your `node_modules` and `platforms` folders and do a clean build.

**Comment by rickydamta** [comment]
Hi,
I'm having the same issue.
So everithing is fine with IOS but there is no way to see something under andorid emulator.

" tns run android --emulator --justlaunch"

Any suggestion?

**Comment by xnramx** [comment]
+1

**Comment by wolfgangmeyers** [comment]
I removed tns-android from my package.json, removed node_modules, removed platforms and re-ran `tns run android`. Works after that. Thanks!
