### ISSUE TITLE
Navigating on suspend event on android causes freeze

### ISSUE THREAD

**Issue by danielgek** [NativeScript/nativescript-angular#783]
Hi, i'm seeing a strange behavior only on android and resume event
#### Context:

what i'm trying to achieve is a pin screen, so every time the app is suspended the `/pin` route sould be called

on iOS i works, but on android everytime i reopen the application it is frozen, i can still see a few button animations but nothing happens, maybe change detection related ?

my suspend event is implemented this way:
```typescript
application.on(application.suspendEvent, (args) => {
     // this.store.dispatch(new pinActions.CloseAction());
    this.ngZone.run(() => {
        this.routerExtensions.navigate(['/pin'], { clearHistory: true, animated: false });
    });
});
```

**Comment by NickIliev** [comment]
@danielgek I've recreated the described scenario in [this test application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/nativescript-angular/issue_783) and on my side, it works as expected. 

The only difference is that I am navigating in the resume event [here](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/nativescript-angular/issue_783/app/item/items.component.ts#L28-L41).

Perhaps you can try my project and tell us what are the differences in your implementation - or even better provide a sample project that reproduces this case.

**Comment by danielgek** [comment]
@NickIliev the problem is that i need to do it on suspend, because the app i'm working on displays sensitive data and when i put the app on the background and open recents app it will show the last thing that was on the app(lastscreen).
That's why i would prefer to do it on the suspend event and not on resume, besides that if i do it on resume the user will see the app going from one page to the pin page

**Comment by danielgek** [comment]
@NickIliev just tested with your sample and changed the `navigate` to suspend event, if you resume, the application is blank and if you hit back 2 times you will get an exeption also tested without `clearHistory: true`

Maybe this is related with #778 (we are actually not doing anything file-system related but the "freeze" issue seams to be the same), what do you think ?

**Comment by 3rror404** [comment]
@danielgek did you ever find a solution to this? I'm doing something similar with a pin screen, opening a modal on application.suspend. This works great on iOS but behaves strangely on Android. It seems like none of the Javascript is loaded and only some of the CSS is working.

**Comment by danielgek** [comment]
@3rror404  i havn't actually, ended up doing what @NickIliev but was not perfect nor right :/ haven't tried with new version of the framework

**Comment by manojdcoder** [comment]
@danielgek @tsonevn @3rror404 I ran into similar issue with {N} 3.4.1 and Angular 5.4, in my case I was trying to navigate on resume event, it did navigate but frozen UI / no bindings were happening as others described already. 

> I had to move the code inside resume event's callback to `ngZone.run` and everything got back to normal.

**Comment by morzyns** [comment]
For me the same..

**Comment by NickIliev** [comment]
Closing as the issue can be soled while using different event from suspend and in the same time there are many possibilities to clear the sensitive data on suspend event,
