### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'child.meta.skipAddToDom')

### ISSUE THREAD

**Issue by pitAlex** [NativeScript/nativescript-angular#784]
This type of error is thrown in special cases where you might want destroy an angular application.
It can happen with "bootInExistingPage" scenario or normal.

To reproduce, keep a reference of the PlatformRef which "platformNativeScriptDynamic()" creates:
` let Platform = platformNativeScriptDynamic({bootInExistingPage:true|false})`

Call `Platform.destroy()` later on, after you bootstrap the application. The application will crash with error:
`TypeError: undefined is not an object (evaluating 'child.meta.skipAddToDom')`.

I tracked it down to nativescript-angular/view-util.js in the removeChild function where "child" in this case will be undefined. Maybe the function should also check if child param has value before looking for the "meta" property.

**Comment by vakrilov** [comment]
Hey @pitAlex - You are indeed right - the `view-util` file is where the error is.
Can you please share a bit more about your scenario: Do you use the `bootInExistingPage` option and what do you expect to happen when the platform is destroyed?

The reason I'm asking is that If `bootInExistingPage` is `false` the platform will automatically create a `Page` that hosts the angular app. When the app is destroyed - so will the page and the application will just remain "empty".

**Comment by vakrilov** [comment]
Closing due to innactivity
