### ISSUE TITLE
ng-template ngFor not repeating within layouts

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#789]
_From @x00 on May 6, 2017 13:11_

Android / Nativescript 3.0

            <StackLayout>
                <ng-template ngFor let-index [ngForOf]="[1,2,3,4]">
                <Label [text]="'This is Label' + index"></Label>
                </ng-template>
            </StackLayout>

yield only `This is Label 1`, where as 

            <StackLayout>
                <Label text="This is Label 1"></Label>
                <Label text="This is Label 2"></Label>
                <Label text="This is Label 3"></Label>
                <Label text="This is Label 4"></Label>
            </StackLayout>

should have the same result. 

this is true is grid wrap and other layouts. 

It is also true if you use the depreciated template. It was working prior to update. 

_Copied from original issue: NativeScript/NativeScript#4133_

**Comment by tsonevn** [comment]
_From @x00 on May 6, 2017 13:31_

            <StackLayout>
                <Label [text]="'This is Label' + index" *ngFor="let index of [1,2,3,4]"></Label>
            </StackLayout>

works correctly but does help if you need a template.

**Comment by tsonevn** [comment]
_From @x00 on May 6, 2017 18:20_

I can confirm this with fresh angular app

**Comment by tsonevn** [comment]
Hi @x00,
Thank you for reporting this issue.
I tested the above-mentioned scenario and unfortunately have to confirm that this is a real issue for both iOS and Android while using `ng-template` in NativeScript Angular 2 project.
I am attaching sample project, where this could be reproduced. 

[Archive.zip](https://github.com/NativeScript/NativeScript/files/986668/Archive.zip)

In the meantime, you could use `StackLayout` as a template and attach to it `ngFor` directive. For example:
```
 <StackLayout>
        <StackLayout height="50" *ngFor="let index of [1,2,3,4]">
            <Label [text]="'This is Label' + index" ></Label>
        </StackLayout>
</StackLayout>
```

**Comment by x00** [comment]
@tsonevn Thank you for the workaround

**Comment by sis0k0** [comment]
fixed with #785

**Comment by davidjonz2005** [comment]
are you sure ? because now i have the same problem

**Comment by steadycoding** [comment]
None of these display the columns horizontally.  The last one only displays the first column.
`    <StackLayout orientation="horizontal" *ngFor="let col of columns">
        <Label [text]="col"></Label>
    </StackLayout>

    <StackLayout orientation="horizontal">
        <ListView [items]="columns" class="list-group">
            <ng-template let-item="item" let-odd="odd" let-even="even">
                <Label [text]="item" class="list-group-item"></Label>
            </ng-template>
        </ListView>
    </StackLayout>

    <GridLayout rows="auto, auto, auto, auto" columns="auto, auto, auto, auto">
        <ListView [items]="columns">
            <ng-template let-item="item" let-i="index">
                <Label row="0" col="i" text="{{item + i}}"></Label>
            </ng-template>
        </ListView>
    </GridLayout>`
