### ISSUE TITLE
TextField onChange support

### ISSUE THREAD

**Issue by ofirdagan** [NativeScript/nativescript-angular#79]
Hi, Is there a way I can hook an event handler on TextField change with (onchange) handler?
From the docs it seems the only option is 'secure'.

10x!

**Comment by ofirdagan** [comment]
Update - ngModel and ngModelChange works :). So basicly this is what I wanted to do:

   <TextField hint="my hint" [(ngModel)]="foo" (ngModelChange)="onChange($event)"></TextField>

**Comment by delanick** [comment]
What about JS Core apps? My textChange event handler isn't even getting called.

**Comment by toppa80** [comment]
Is there a solution for JS-Apps? Looking aswell...
