### ISSUE TITLE
image icon in segmented bar in nativescript

### ISSUE THREAD

**Issue by bjai** [NativeScript/nativescript-angular#790]
how to add the image icon in the segmented bar in nativescript-angular. can you please help me with this 
```
 <SegmentedBar #tabs [selectedIndex]="selectSegment">
                <SegmentedBarItem title="test1"></SegmentedBarItem>
                <SegmentedBarItem title="test2"></SegmentedBarItem>
                <SegmentedBarItem title="test3"></SegmentedBarItem>
                <SegmentedBarItem title="test4"></SegmentedBarItem>
        </SegmentedBar>
```

**Comment by NickIliev** [comment]
@bjal the SegmentedBar does not have options to assign images for each [SegmentedBarItem](http://uatdocs.nativescript.org/api-reference/classes/_ui_segmented_bar_.segmentedbaritem.html). This is a valid scenario for TabView. For SegmentedBar you can only set background-image for the whole Segmented bar which can be used to apply image pattern but is no applicable to apply different icons for the different SegmentedBarItems

**Comment by bjai** [comment]
thanks @NickIliev

**Comment by gokulraj809040** [comment]
can we add font-awesome to segmentbar?

**Comment by JamzyKimani** [comment]
@gokulraj809040 yes, you can add font awesome icons to {N} segment bar items. A few edits to the above code (assuming you've already installed FontAwesome to your app) do the trick:

`<SegmentedBar #tabs [selectedIndex]="selectSegment" style="font-family: 'FontAwesome'; color: #eee; background-color: #31394C;">
            <SegmentedBarItem title="&#xf0c0;"></SegmentedBarItem>
            <SegmentedBarItem title="&#xf007;"></SegmentedBarItem>
            <SegmentedBarItem title="&#xf008;"></SegmentedBarItem>
            <SegmentedBarItem title="&#xf0f3;"></SegmentedBarItem>
</SegmentedBar>`

For more details, check out an answer to a similar question I put up on StackOverflow:
https://stackoverflow.com/questions/43885043/image-icon-in-segmented-bar-in-nativescript/48284296#48284296

**Comment by stanimirsp5** [comment]
Can we rotate  font-awesome icons in segmentBarItem? I tried with 'fa-rotate-90' but doesn't work.
