### ISSUE TITLE
RSA Encrytion in NativeScript.

### ISSUE THREAD

**Issue by deepak4u2006** [NativeScript/nativescript-angular#791]
I am working on a NativeScript-Angular project, I need to encrypt password before sending it to server.
We are using RSA encryption on all other Platforms, I searched a lot for RSA encryption, I also tried `node-RSA` from [npmjs.com](www.npmjs.com), but as it internally calls `Crypto` so it is failing in Nativescript.
I have tried posting the issue in Stackoverflow also, but didn't got any help.

**Comment by NickIliev** [comment]
@deepak4u2006 there is currently no plugin that provides out-fo-the-box RSA encryption for NativeScript.
As you yourself observed you can not use node-RSA as it depends on Crypto (the reason why Node.js packages like Crypto are not supported out-of-the-box can be found [here](https://github.com/NativeScript/NativeScript/issues/195).

You have the option to use [this plugin](https://github.com/NativeScript/nativescript-app-encryption) if AES encryption is applicable for your case (plugin for versions of NativeScript 2.5.x and below0

**Comment by deepak4u2006** [comment]
@NickIliev Thanks for the quick reply, but my requirement is Strictly RSA encryption,.
Also I think closing the issue will solve anything for anyone, I would request let it be open so that others can give their input.

One more :) Can you guide me how can I use [JSEnCrypt](https://github.com/travist/jsencrypt), in my NativeScript-Angular project.

**Comment by NickIliev** [comment]
Hey @deepak4u2006 if  you want to add this as a feature I think the proper place would be in [the main modules repository](https://github.com/NativeScript/NativeScript/issues) - feel free to open issue there and I label it as a plugin request
