### ISSUE TITLE
Multiple searchbars are not working 

### ISSUE THREAD

**Issue by harriscreativity** [NativeScript/nativescript-angular#795]
Why is nativescript not allowing us to use two seachbar or even more

**Comment by tsonevn** [comment]
Hi @harriscreativity,
Could you provide some sample code, where this problem could be reproduced? 
I tested this case and was able to set several SearcBar components on a single page. For your convenience, I am attaching a sample project. You could download it and build it on your side.

[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/996823/Archive.zip)
