### ISSUE TITLE
Error while customizing searchbar on a css file

### ISSUE THREAD

**Issue by horeyes** [NativeScript/nativescript-angular#796]
Hello,

I'm facing this error: "Cannot read property 'android' of undefined, undefined"  whenever I try do add a property to a searchbar in the CSS file. However I can give a property i.e background color if I do it inline. 

Here's a screenshot of the error. 
![error](https://cloud.githubusercontent.com/assets/12671900/26010078/883e2dfa-3719-11e7-95e8-ca2e464ca7be.PNG)

**Comment by tsonevn** [comment]
Hi @horeyes,
Thank you for reporting this issue. 
I made a test app on my side, however, everything seems to work as expected. 
I am attaching a project, could you review it and make the needed changes, which will help us to debug this issue locally.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1001012/Archive.zip)

**Comment by horeyes** [comment]
Hello @tsonevn,
I was able to recreate the issue.
First I commented the SearchBar style on app.css. Then I created a css file linked to the html file template.
After that I assigned the property in the file css. 

If you run the app you should be taken directly into the same screen as the one I posted initially. 
To solve this just comment the code or remove it fom the css file. 

Currently knowns workarounds (What worked for me): 

1. Add properties from app.css
2. Inline styling.

Here's the link to the folder. I tried adding the zip file directly in here, but github wouldn't let me
even though it's a zip file.
[https://drive.google.com/drive/folders/0Bz2-GdMNzIDaNEY4Ry04aUpkUjA?usp=sharing](url)

**Comment by tsonevn** [comment]
Hi @horeyes,
Thank you for the attached sample project.
I reviewed it and indeed this is a real issue, while applying a style to the SearchBar component, while using CSS class.
I also found that this issue is already reported [here ](https://github.com/NativeScript/NativeScript/issues/4147) and you could keep track on it for further info.
