### ISSUE TITLE
SegmentedBar with 3.0.0 causing 'not a valid View instance.'

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#798]
I investigated this issue for awhile and am puzzled. It appears that `SegmentedBar` can no longer be used here in the advanced seed after updating to 3.0 (it worked fine prior to upgrading):
https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/app/shared/i18n/components/lang-switcher.component.tns.html

I went searching and thought it was perhaps related to this:
https://github.com/NativeScript/nativescript-angular/issues/649
But I tried commenting out this:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/app/shared/i18n/components/lang-switcher.component.tns.scss#L9
But the same error persists.

Steps to repro:
```
git clone https://github.com/NathanWalker/angular-seed-advanced.git
cd angular-seed-advanced
npm i
```
Open this file:
https://github.com/NathanWalker/angular-seed-advanced/blob/master/src/client/app/shared/i18n/components/lang-switcher.component.tns.html
And uncomment the `SegmentedBar`, then:
```
npm run start.ios   // from root directory of seed
```
The app will launch in Simulator but you will see this error in console amid other normal logs:
```
ERROR Error: [object Object] is not a valid View instance.
ERROR CONTEXT [object Object]
```
Then navigate using 'About' at top right, then navigate back and watch it crash.
You can also choose 'read more about it' button at bottom of main page, then navigate back, same crash.

Commenting out the `SegmentedBar` allows everything to run as normal.

Stumped.

**Comment by jlooper** [comment]
SegmentedBar one of the modules that had big changes in 3.0. They are documented here: https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md#typescript

I had to change QuickNoms like this: https://github.com/jlooper/quicknoms-app/commit/0850f8aa7527a04eee5c2344d8def12ca78568b1 - you have to edit both the XML and the .ts file to create the Segments of the SegmentedBar. Idk why they did this but here we are.

**Comment by NathanWalker** [comment]
@jlooper Savior!! oh my goodness - feel like I had read over those changes dozens of times and don't know how I missed this - thank you so much!!
