### ISSUE TITLE
A binding does not work properly

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-angular#799]
The [item-detail](https://github.com/NativeScript/template-hello-world-ng/blob/master/item/item-detail.component.html#L4) component of the default hello world [template](https://github.com/NativeScript/template-hello-world-ng/) does not render properly. In particular:
```
<Label class="h2" [text]="item.id + '. '"></Label>
```

Expected:
*10. Messi*
![screen shot 2017-05-15 at 9 16 29 am](https://cloud.githubusercontent.com/assets/12251337/26044811/36c991c0-394f-11e7-9846-b39c9276836f.png)

Actual:
*10Messi*
![screen shot 2017-05-15 at 9 04 11 am](https://cloud.githubusercontent.com/assets/12251337/26044555/bcc511f2-394d-11e7-8502-307bf8c28669.png)

**Comment by NickIliev** [comment]
This is happening only when using FULL STOP (`\u002E`) but works with other symbols like COMMA(`\u002C`)

**Comment by sis0k0** [comment]
If you try to add `text`: "4.", the ns renderer will try to convert the string to number. Result: 4 (without decimal point). With NS 3.0 such conversions are no longer needed. I'll make a PR that removes the convert function from the renderer.
