### ISSUE TITLE
Build in Visual Studio 2015 with cordova tools.

### ISSUE THREAD

**Issue by khalla** [NativeScript/nativescript-angular#8]
Hi, nice work, i've been trying to achieve the same using Visual Studio 2015 RC.

I have forked your project, I will do some digging in order to have a vs build.

If its comes usefull, i would like to contribute.

Cheers, mate

**Comment by hdeshev** [comment]
Hey @khalla 

Having a VS2015 build would be great. I'm looking forward to that!

I was just curious if there is a way to keep the csproj file references set up so that they use wildcards and the csproj file wouldn't have to be updated every time we add or delete a file?

**Comment by hdeshev** [comment]
Closing this old issue. NativeScript projects using TypeScript now have a tsconfig.json file that works quite nice in Visual Studio Code, and probably work with the "real" Visual Studio too.
