### ISSUE TITLE
NativeScript-Angular Tabview Separate Files for TabViewItem Views

### ISSUE THREAD

**Issue by deepak4u2006** [NativeScript/nativescript-angular#800]
Hi, 
 I have been trying to find out any resource related to implement **"Separate Files for TabViewItem Views"**

I also came across a very nice [article](https://www.nativescript.org/blog/guest-post-getting-cozy-with-nativescript%27s-tabview). But was not able to translate this into NativeScript-Angular app.

**Comment by tsonevn** [comment]
Hi @deepak4u2006,
Thank you for contacting us,
You could create a separate component for every TabViewItems and to import them in the TabView by using the components selector name. 
Bear in mind that after you create the custom components, you should import them in the `declarations` in `app.modules.ts` file. You could review the attached sample project.
For further info, you could also review the Angular 2 documentation and this article [here](https://angular.io/docs/ts/latest/tutorial/toh-pt3.html) .
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1001312/Archive.zip)

**Comment by deepak4u2006** [comment]
Hi @tsonevn many thanks Sir!!!, Sorry for replying so late as I wanted to implement it fully then only respond. Now my tabview is working great.
Mean while I also found a discussion [here](https://discourse.nativescript.org/t/tabview-in-angular-better-example/78).

I am closing the issue.
Thanks again!!!

**PS**. I think a small mention of this feature should be in [official Documentation](https://docs.nativescript.org/cookbook/tab-view-ng).

**Comment by efares** [comment]
I agree with @deepak4u2006 I was having the same problem and had to search for a solution instead of it being mentioned in the official Documentation.

Thanks!
