### ISSUE TITLE
Components inside a nested router-outlet are recreated when navigating

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/nativescript-angular#802]
### The Scenario
We have a following app scenario:
- The app has root navigation using `<page-router-outlet>`
- On one of the pages (let's name it "main") there is a nested navigation using the stock angular `<router-outlet>`. Navigating the nested router outlet is usually controlled with `RadSideDrawer`.

There are sample implementations described in #343 and in [this gist](https://gist.github.com/NathanWalker/e8f4f7c42af04fc725764a9867936e3d#gistcomment-1993412) by @NathanWalker 

### The Problem
When navigating form "main" page to another page(let's name it "detail") and then back again, the content of the nested  `<router-outlet>` inside the main page is loaded after the page animation is finished:

![router-outlet-caching](https://cloud.githubusercontent.com/assets/4411891/17695449/38b16f80-63c6-11e6-8f35-266d69d0614e.gif)

There are two different issues at hand:
1. The component that was previously shown inside the `<rotuer-outlet>` is re-created and not reused.
2. The actual instantiation of the component happens **after** the page animations has finished. This is triggered in the  [`<page-router-outlet>` implementation and happens in  page.navigatedFrom](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/page-router-outlet.ts#L242-L247) event. Which means the "main" page is empty during the animation and the content is loaded after the navigations has finished.

### Additional Information
The reason why `page.navigatED From` event is used instead `page.navigatING From` is that in IOS you can start a back navigation using swipe gesture, but cancel it in the middle:

![may-16-2017 13-47-08](https://cloud.githubusercontent.com/assets/4092076/26102584/41b22544-3a3e-11e7-861f-c20c8c1481ca.gif)

If we trigger the angular `back` navigation on the `page.naivgatING` event, angular will remove 
the components form the current page and instantiate the component on the page you are navigation to. However, if you then cancel the animation you will end up with a page that has been cleared and corrupted navigations stack.

**Comment by manojdcoder** [comment]
@vakrilov Do you think is it possible to disable the `router-outlet` from listening for changes in url and enable back when detail page is closed.

**Comment by vakrilov** [comment]
@manojdcoder Good thinking! 
However, the `router-outlet` is more "passive" - it does not subscribe or listens for events. It just implements a [bunch of methods](https://github.com/angular/angular/blob/master/packages/router/src/directives/router_outlet.ts#L39-L135) that the router calls when needed. I'm not aware of any APIs that will allow you to freeze and unfreeze the content of the state of the outlet.

The closes thing is the `RouteReuseStrategy` feature in angular, but it is poorly documented and the best resource I found about it is this [SO thread](http://stackoverflow.com/questions/41280471/how-to-implement-routereusestrategy-shoulddetach-for-specific-routes-in-angular).

**Comment by manojdcoder** [comment]
@vakrilov Any idea about focusing on this issue during v3.2 release, along with other improvements on Angular layer.

**Comment by vakrilov** [comment]
We still haven't done any planning for `3.2`. 

For `3.1`(mid-late June) we are focusing mainly on more high priority bugs, so we won't be able to work on this.

**Comment by triniwiz** [comment]
@vakrilov any updates on this ?

**Comment by Jcook894** [comment]
Is there anymore information on this issue? I am having the exact problem

**Comment by vakrilov** [comment]
We have released `nativescript-angular@4.4.0` yesterday with some major improvements in how `page-router-outlet` works. This issue should be fixed with this version.
