### ISSUE TITLE
TextField  (propertyChange) no loger working on 3.0 android

### ISSUE THREAD

**Issue by x00** [NativeScript/nativescript-angular#807]
I have confirmed this with a fresh project. 

also using `[(ngModel)]` with `(ngModelChange)`

**Comment by x00** [comment]
(textChange) apears to work

**Comment by sis0k0** [comment]
See: https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md#events-raised-when-property-value-change

Also, for NgModel to work you need to import `NativeScriptFormsModule`.

**Comment by x00** [comment]
damn it! My reading comprehension is going, I did a text search of the breaking changes, but must have typed incorrectly.
