### ISSUE TITLE
Scaffold/Seed project

### ISSUE THREAD

**Issue by jaspersorrio** [NativeScript/nativescript-angular#81]
Should have a seed/scaffold project for developers to be able to start developing immediately.

**Comment by hellofornow** [comment]
I'd nominate what @NathanWalker is working on with https://github.com/NathanWalker/angular2-seed-advanced. It builds off of angular2-seed.

**Comment by NathanWalker** [comment]
@jaspersorrio The seed is operational. You can try out the {N} integration with this simple setup:
https://github.com/NathanWalker/angular2-seed-advanced#run-nativescript-app

There's a lot more to come with the seed; it's under heavy active development, but definitely give it a try. Maximizes code reuse and serves as an example of how to integrate `nativescript-angular` in with an existing Angular2 codebase. Utilizes a `ViewBroker` to handle relocating `html` view paths and swaps them at runtime for their {N} equivalent:
https://github.com/NathanWalker/angular2-seed-advanced/blob/development/src/frameworks/core.framework/services/view_broker.ts#L8-L12

Let me know your thoughts over on that repo if you check it out.

**Comment by hdeshev** [comment]
Of course, you can use the hello world ng template:

`tns create my-shiny-app --template tns-template-hello-world-ng`
