### ISSUE TITLE
Can't create an app

### ISSUE THREAD

**Issue by fant0m** [NativeScript/nativescript-angular#818]
Hello, I'm trying to install demo angular app using command from tutorial:
`tns create HelloWorld --template nativescript-template-ng-tutorial`
But I'm getting an TypeError:
```
-- nativescript-template-ng-tutorial@3.0.0


The plugin nativescript-template-ng-tutorial@3.0.0 is already installed
TypeError: Path must be a string. Received undefined
# create
```

I'm using Windows 10. Tns doctor says no issues were detected. What's wrong?

**Comment by tsonevn** [comment]
Hi @fant0m,
Could you verify, whether you are trying to create a new NativeScript Angular 2 project inside the existing one?
Could you try to run `tns create HelloWorld --template nativescript-template-ng-tutorial` while use some other directory as a root?

**Comment by fant0m** [comment]
@tsonevn I have tried multiple folders but the result is same. After running this command it makes a new folder HelloWorld. There's package.json inside with this content:
```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.HelloWorld"
	}
}
```
Then the folder disappears and the error is displayed in console.

**Comment by tsonevn** [comment]
Hi @fant0m,
If I understand you correctly this error is shown just after you run `tns create HelloWorld --template nativescript-template-ng-tutorial`?
I tested this case on my side ones again, however, was unable to reproduce this behavior, while using latest NativeScript 3.0.
Regarding that, could you provide some more info about your environment(CLI, node version)?

In the meantime, you could verify, whether you will have the same problem with the other NativeScript templates. You could follow the below given steps:
1. `npm cache clear`
2. `tns create sample --ng`.

Let me know, whether this helps.

**Comment by fant0m** [comment]
@tsonevn I'm sorry, it didn't help. This is what happens: http://prntscr.com/fbxjzb

tns version: 3.0.1
node version: 6.9.5

**Comment by tsonevn** [comment]
Hi @fant0m,
Could you confirm that you have the same behavior with `tns create sample --ng` command?

**Comment by fant0m** [comment]
yes, with any `tns create` command

**Comment by tsonevn** [comment]
Hi @fant0m,
In my further research, I found that this issue could be related to using experimental Android `build-tools`.
Regarding that, could you give us more info about the `build-tools` version, which are installed on your machine and whether the highest
![screenshot 38](https://cloud.githubusercontent.com/assets/17448734/26454345/8372ec9c-416f-11e7-9c81-7e2619c1c81b.png)
 version is `25.0.3`. 
You could review the attached image.

Bear in mind that you should check `Show Package Details` box, which will list you detailed information about the installed packages.

**Comment by fant0m** [comment]
@tsonevn yes, the version `25.0.3` is the latest and it's the only one I have installed

**Comment by tsonevn** [comment]
Hi @fant0m,
This issue could be related to some mismatching version of the dependencies. Regarding that, could you send us the whole `package.json` file of the newly created project?

Thank you in advance for your cooperation.

**Comment by fant0m** [comment]
@tsonevn I already did in 3rd post.

**Comment by tsonevn** [comment]
Hi @fant0m,
Excuse me for the misunderstanding. 
I found that you have give us this info, however the `pachage.json` file should also include info about all dependencies, like `tns-core-modules`, `nativescript-angular`. This is the reason why I requested this file for the second time.
Regarding the problem, it might be an issue with downloading the package from npm. What you could do is to run `tns create HelloWorld --template nativescript-template-ng-tutorial --log trace` and to send us the full log from the console.

Also to verify, whether everything is correct with the download, you could run `npm i  nativescript-template-ng-tutorial` in an empty folder. after the installation complete verify, whether `nativescript-template-ng-tutorial` exist in `node_modules` folder and whether the package has `pachage.json` file similar to the attached one.

package.json
```
{
  "name": "nativescript-template-ng-tutorial",
  "version": "3.0.0",
  "main": "main.js",
  "description": "Template for starting the NativeScript Getting Started Tutorial",
  "repository": "https://github.com/tjvantoll/nativescript-template-ng-tutorial",
  "nativescript": {
    "id": "org.nativescript.tutorial"
  },
  "dependencies": {
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/router": "4.0.0",
    "nativescript-angular": "~3.0.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "~3.0.0",
    "zone.js": "~0.8.5"
  },
  "devDependencies": {
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.0",
    "typescript": "~2.2.1"
  }
}
```

**Comment by fant0m** [comment]
@tsonevn There are some problems with my environment variables & android installation. If I run your commands it doesn't create any folder. Thanks for helping but I have to solve it on my own.

**Comment by Sevensnake** [comment]
I am having the same problem and nothing is happen to fix it. native script is becoming prom-attic for any device.
