### ISSUE TITLE
loops on ng-container only render first element

### ISSUE THREAD

**Issue by daveware-nv** [NativeScript/nativescript-angular#825]
I noticed this when upgrading a NS2.5 app to NS3.0

When using `*ngFor` to loop on `ng-container` only the first element gets output

to reproduce:
- `tns create "test" --template angular`
- remove the routes in `app.routing.ts`
- replace the contents of `app.component.html` with the following:
```
<StackLayout>
  <ng-container *ngFor="let v of ['a', 'b', 'c']">
    <Label [text]="v"></Label>
  </ng-container>
  <ng-container *ngIf="true">
    <Label text="true"></Label>
  </ng-container>
  <ng-container *ngIf="false">
    <Label text="false"></Label>
  </ng-container>
</StackLayout>
```
expected:
```
a
b
c
true
```
actual:
```
a
true
```
platform: android
build machine: ubuntu 16.10

**Comment by sis0k0** [comment]
Hey @daveware-nv,

The issue was fixed with b127ba7aadd4734c4200bf3e66665e6892056f37. The fix will be released with nativescript-angular 3.1. Until that happens, you can use the `next` tag :)

```
npm i nativescript-angular@next
```
