### ISSUE TITLE
Nativescript app crashes when ngModel'ed value is being bound in the same UI

### ISSUE THREAD

**Issue by lu4** [NativeScript/nativescript-angular#827]
I have fairly simple helloworld app, the problem boils down to two lines of code:

```
    <Slider minValue="1" maxValue="999" [(ngModel)]="intertialResolution"></Slider>
    <Label [text]="intertialResolution" textWrap="false"></Label>
```

`intertialResolution` is an ordinary field with initial value equal to 10. I've found that the problem shows up in all cases when I try to bind the value which is ngModel'ed. If one of the above lines is removed the app works perfectly fine. Also I've successfully imported `NativeScriptFormsModule` into my NgModule.

**Comment by NickIliev** [comment]
@lu4 I was not able to reproduce the issue (using [this test project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/nativescript-angular/issue_827)) and [reusing a ngModel-ed property](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/nativescript-angular/issue_827/app/item/items.component.html#L4-L6) is working as expected.

However, you can overcome this by using two different properties for your slider and label agani [as demonstrated](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/nativescript-angular/issue_827/app/item/items.component.html#L8) in the linked project above

**Comment by lu4** [comment]
I can try to isolate this problem into separate project and provide the archive if you want?

**Comment by lu4** [comment]
I've created a [pull request](https://github.com/NickIliev/NativeScript-Issues-2017/pull/2) with code that I've extracted from my project, the issue is reproduced on real device, access to camera is required.

Steps to reproduce:
1. Launch application
2. Press "+" in right top section of the screen.

Result: app crashes

**Comment by lu4** [comment]
Ok, it seems I've misidentified the problem, it was related to manual `dealloc` call which was accompanied by another one done by `auto_release_pool`, so I think the case is closed, sorry for bothering.
