### ISSUE TITLE
How to register custom element?

### ISSUE THREAD

**Issue by nripendra** [NativeScript/nativescript-angular#83]
Let's say I have a custom nativescript element  created by inheriting Label. How can I use this element in nativescript-angular? Is there a way to register such element as angular directive??

**Comment by vakrilov** [comment]
You can use the `registerElement` method from the [element-registry](element-registry).
[Here](https://github.com/NativeScript/nativescript-angular/blob/master/src/nativescript-angular/element-registry.ts#L41-L74) you can see how this is done for the existing nativescript views.
