### ISSUE TITLE
Image throws error if src url does not return a valid image

### ISSUE THREAD

**Issue by eamon-hguk** [NativeScript/nativescript-angular#833]
Possibly relates to:

https://github.com/NativeScript/NativeScript/issues/3381

Affects IOS (not tested Android, but assuming it is a problem their too)

Though my issue is a little different as it relates to the view.

I am trying to retrieve images in the view by using an Url pointing at images in an S3 bucket

`<Image [src]="https://s3-eu-west-1.amazonaws.com/hgevents-images-test/26/1472222735722_Logo_Gradient_rgb.jpeg" width="100" height="100"></Image>`

When using a URL to an invalid image, or a non-existent one (such as given above), I get the following error:

`CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1091:24: ERROR Error: Uncaught (in promise): Error: Response content may not be converted to an Image
	file:///app/tns_modules/tns-core-modules/http/http-request/http-request.js:123:61 [<root>]
	UIApplicationMain@[native code] [<root>]
	start@file:///app/tns_modules/tns-core-modules/application/application.js:211:26 [<root>]
	bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:72:28 [<root>]
	bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:60:26 [<root>]
	anonymous@file:///app/main.js:5:57 [<root>]
	evaluate@[native code] [<root>]
	moduleEvaluation@[native code] [<root>]
	[native code] [<root>]`

My problem is not so much that an error is thrown, but that this error stops other areas of the application working, such as data being rendered on other pages.

Is there a way to either get Nativescript to ignore this error, or to handle it, so it does not break my application? 
If not then this is an issue, as it does not reflect how this would work in other applications, such as a web application, where the failure would not cause any collateral damage.

**Comment by tsonevn** [comment]
related to [#4339](https://github.com/NativeScript/NativeScript/issues/4339)
