### ISSUE TITLE
Adding class to SearchBar gives error "Cannot read property 'android' of undefined"

### ISSUE THREAD

**Issue by celsomtrindade** [NativeScript/nativescript-angular#839]
I'm running this on an android emulator, when I try to apply custom style to a SearchBar element via class, I keep getting this error:

> Cannot read property 'android' of undefined

The styles defined in the class are applied to the SearchBar. Also, the error only appears after I access the page and then try to navigate away from it. For example, if I have 3 views `Home`, `Search` and `Profile`, the error will show according to this navigation flow:

- Home -> Profile | no error;
- Profile -> Home | no error;
- Home -> Search | no error;
- Search -> Home or Profile | !error!

Also, when there is the error, the page doesn't change, it stays on the same page, but if I click again to navigate, then it works as expected.

I dont know if this is the intend behavior, since I didn't found anything about this in the docs.

Also, if I use the same css properties but on a style attribute on the SearchBar, then it works just fine, without any errors.

This is how my code looks like without errors:

```
<ActionBar title="">
    <SearchBar hint="Search here" (loaded)="onSearchBarLoaded($event)" (clear)="onClear($event)" (submit)="onSubmit($event)" style="background-color: #FFF; color: #7F7F7F; height: 40; margin-right: 8;"></SearchBar>
    
    <ActionItem>
        <FlexboxLayout class="cp-icon">
            <Label text="&#xE80B;"></Label>
        </FlexboxLayout>
    </ActionItem>
</ActionBar>
```

As soon as I add a class as simple as the one below, the error appear. 

````
.myClass {
    color: #7F7F7F;
}
````

Note: I just intalled NativeScript and Angular, on the latest versions, as follow:

    "@angular/core": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.0.0",
    "tns-core-modules": "^3.0.1",

**Comment by sis0k0** [comment]
That issue was fixed with https://github.com/NativeScript/NativeScript/pull/4239.
The fix is available when using the `next` tag of `tns-core-modules` and will be released as part of 3.1 :)
