### ISSUE TITLE
Data binding - scope issue when using observable subscribe

### ISSUE THREAD

**Issue by francoisruty** [NativeScript/nativescript-angular#841]
Hi all, here is the context.

I'm working on a cross-platform app, using the nativescript-angular seed project here:
https://jlooper.github.io/angular-starter/

I'm trying to have a component variable bind to a service property (I'm using a shared service for communication between components).
First, it's not possible in typescript to perform conditional imports. Since the codebase is used for the web and for mobile, I have to be careful. For example, I cannot import "data/observable" and use this for observables since this does not work during the web build.
I found out that "import {Subject} from 'rxjs/Subject';" works for both mobile and web build, so I decided to use that to make observables inside the shared service.

The shared service is "stateService". I want component "nsviewer" to update a property from  "stateService", and have component "opengl" display this update in its template.

**In "nsviewer" component:**
`self.state.editSelectedObject(params);  ` 
This is called after a http call.
This function edits the property in state.service.
All works well so far.

**In "stateService" service:**
```
public selectedObject3:Subject<any> = new Subject();
  public editSelectedObject3(newValue) {
    this.selectedObject3.next(newValue);
  }
```
So the service property exposes an observable, and a method to update the observable.

**In "opengl" component:**

```
    this.state.selectedObject3.subscribe(
      data => this.setSelectedObject(data));

  private setSelectedObject(value) {
    this.message = value;
  }
```

and in the template of "opengl" component:
`<Label class="h1 m-20 text-center" text='{{message}}'></Label>`

Normally, whenever "viewer" component updates stateService property, the change should appear in "opengl" component template.
That's not what happens: nothing changes in the template.
When I put console.log everywhere, here is what I notice:
- everything looks good
- the "this" refers to the component everywhere so there is no context issue
--> it's just the view that does not update, even though the component property IS updated.
- if I change the component variable from outside the observable subscribe, the change is reflected in the view without any problem.
--> this would lead me to think it's a context issue, but as stated, if I console.log the "this" from inside the observable subscribe, all is good. So maybe the component is kinda "instantiated" a second time from within the observable subscribe?
- I don't have a problem with the web build, it only happens with the mobile build, when using nativescript.

Here are my best guesses right now:
- for some reason, every change I make to the component from within the observable subscribe is not taken into account because it's impacting some kind of "shadow instance" of the component
- import {Subject} from 'rxjs/Subject'; does not work in nativescript and I must use a nativescript-specific component

Any idea?

At this stage, I'm considering to stop using observables, and using a brute force refresh loop with setTimeInterval, that reinitializes the local variable from the service property continously, I tried and it works.
But I would prefer to do all this the right way

**Comment by francoisruty** [comment]
nope, sorry mate, I stopped developing with nativeScript entirely and I stick with web-only
 less bloat-y

**Comment by NickIliev** [comment]
@viswa-optimusprime if you have a sample Playground or test app to demonstrate the issue I would be happy to help.

CLosing this one due to inactivity.
