### ISSUE TITLE
CONSOLE ERROR [native code]: ERROR Error: Invalid value: *

### ISSUE THREAD

**Issue by Mepk** [NativeScript/nativescript-angular#855]
I build app for ios with NS 3.0.1
After navigating to view I have an error
`CONSOLE ERROR [native code]: ERROR Error: Invalid value: *`

View Code is:
`<ActionBar title="НОВОСТИ">
    </ActionBar>

    <side-drawer-page>    
        <ScrollView (scroll)="onScroll($event)">
            <StackLayout *ngIf="!_showIndicator">
                <news-item *ngFor="let item of news" [info]="item"></news-item>
            </StackLayout>
            <GridLayout rows="*" columns="*" style="height: 100%" *ngIf="_showIndicator">
                <ActivityIndicator width="30" height="30" row="0" col="0" 
                    [busy]="true" class="activity-indicator"></ActivityIndicator>
            </GridLayout>
        </ScrollView>
    </side-drawer-page>
`

What it means?

**Comment by NickIliev** [comment]
@Mepk based the code above I noticed that you are using binding to assign a true value for your ActivityIndicator. In the same time the word true is reserved in JavaScript so are you sure that this is binded property? If not the busy should be set as follows:

```
<ActivityIndicator  busy="true"></ActivityIndicator>
```
or
```
<ActivityIndicator  [busy]="isBusyBoolean"></ActivityIndicator>
...

this.isBusyBoolean = true; // in your component class
```
