### ISSUE TITLE
BY using Nativescript animations Showing Error: ERROR TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-angular#856]
I used the below Css Animation
```
.view {
    animation-name: example;
    animation-duration: 1;
    animation-timing-function: ease-in;
   animation-fill-mode: forwards;
}
@keyframes example {
    from { transform: translate(0, 0); }
    to { transform: translate(0, 100); }
}
```
I referred this class in my view but shown Error : ERROR TypeError: Cannot read property 'length' of undefined

**Comment by NickIliev** [comment]
@JaganJonnala I am trying to reproduce the issue using [this project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/nativescript-angular/issue_856) but with no success at this point (everything works fine on my side).

Can you please post the XML layout used to style and also clarify on what platform you are experiencing this error (Android or iOS).

**Comment by JaganJonnala** [comment]
Android


And I am using Nativescript with angular 2
class name used in Html file i mean view

**Comment by NickIliev** [comment]
@JaganJonnala the actual HTML code involved would help a lot.

**Comment by JaganJonnala** [comment]
`<StackLayout class="view">
       <Label text="Medicines" class="c-white"></Label>
</StackLayout>`


Just given that class name which i have used to animation to the StackLayout as class

**Comment by jogboms** [comment]
@JaganJonnala I actually experience this same issue but in a different way. When I do exactly what you do, It works but when I split the functionality of the animation-* properties into different classes, it produces this very same error.

**Comment by kumaran-dena** [comment]
I am also facing same problem. Any updates regarding this issue @JaganJonnala & @jogboms ?

**Comment by JaganJonnala** [comment]
HTML
---------------------------
```
<FlexboxLayout #label1 (loaded)="animate(label1,150)" style="margin-top:120-dip;" flexDirection="column" flexWrap="nowrap">
								<StackLayout class="foodRow">
									<Image src="~/images/icon.png" style="width:65%;height:65%"></Image>
								</StackLayout>
								<Label text="Butchery" #label12 (loaded)="animate(label12,650,-5)" textWrap="true" style="margin-top:5;color:white;text-align:center"></Label>
							</FlexboxLayout>
```

View-Model - TypeScript
-------------------------------------------
`  animate(label: Label, durationTime: number, ynumber?: number) {
        // >> animation-animating-properties-code
        ynumber = ynumber || -100;
        label.animate({
            translate: { x: 0, y: ynumber },
            duration: durationTime,
            curve: AnimationCurve.easeInOut
        }).then(() => {
        }).catch((e) => {
            console.log(e.message);
        });
    }`


I have Used llike this @kumaran-dena

**Comment by jogboms** [comment]
@kumaran-dena I actually just ignored the animation property that was causing the error.

**Comment by kumaran-dena** [comment]
I was tried this. Now its working fine.Thank you @JaganJonnala.

**Comment by kumaran-dena** [comment]
Its working fine @jogboms. I tried with following code. This also works fine @JaganJonnala .

**app.component.html**

`<StackLayout class="login-page-animate">
<Image src="res://logo" stretch="none" horizontalAlignment="center"></Image>
<StackLayout >
<TextField id="untext" required #elementModel="ngModel" hint="Username" class="input input-border" [(ngModel)]="user.USER_ID" autocorrect="false" autocapitalizationType="none">
</TextField>
<Label class="validation" [visibility]="elementModel.valid ? 'collapse' : 'visible'" text="Username is required" ></Label>
</StackLayout >
<StackLayout >
<TextField id="pwdtext" required #elementModell="ngModel" hint="Password" class="input input-border" [(ngModel)]="user.PASSWORD" secure="true"></TextField>
<Label class="validation" [visibility]="elementModell.valid ? 'collapse' : 'visible'" text="Password is required" ></Label>
</StackLayout >

<FlexboxLayout orientation="horizontal" alignItems="center" justifyContent="space-between"> 
<CheckBox #CB1 text="Remember Me" checked="false"></CheckBox>
<Button id="btnlogin" text="Sign In" class="btn btn-primary btn-rounded-sm" (tap)="login()"></Button>
</FlexboxLayout >
</StackLayout>`

**app.css**
`.login-page-animate{
  animation-name: rotate;
  animation-duration: 2;
}
 @keyframes rotate {
    from { transform: rotate(360deg); }
    to { transform: rotate(0deg); }
}`

**Comment by erkanarslan** [comment]
I have the same problem and I cannot understand how you solved it. What is the problem? What did you change?

It would be nice if anything in the documents would just work without crashing the app.

**Comment by mudlabs** [comment]
@erkanarslan here's a [Playground](https://play.nativescript.org/?template=play-js&id=DFtvQj) example.
