### ISSUE TITLE
popup notification

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/nativescript-angular#858]
am looking for a way to make Facebook like popup notification 
i would appreciate any type of help thanks

**Comment by NickIliev** [comment]
There a number of plugins that can enable push notifications for your NativeScript applicaiton - e.g. 
 nativescript-push-plugin or nativescript-plugin-firebase 

Please post a similar question in the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/), SO or Slack channel. This repository's issues are meant to log bugs, feature request and investigate possible issues.
