### ISSUE TITLE
How to hide the Scroll bar for ScrollView Element..?

### ISSUE THREAD

**Issue by JaganJonnala** [NativeScript/nativescript-angular#859]
![image](https://user-images.githubusercontent.com/10844009/27421421-f0baac70-5747-11e7-88b4-f23579ffab8c.png)

Need to hide that Scroll bar While Scrolling

Used
![image](https://user-images.githubusercontent.com/10844009/27421396-d514b29a-5747-11e7-8aaf-47d550058feb.png)

**Comment by NickIliev** [comment]
@JaganJonnala please notice that this repository is for login issues, bugs and features related to nativescript-angular. For how-to related question use the community channels like [discourse.nativescript.org](https://discourse.nativescript.org/) SO or Slack.

To disable the scroll you can take a look at the techniques discussed in  [this forum thread](https://discourse.nativescript.org/t/hide-scrollview-indicator/808/2) or use [this plugin](https://github.com/TheOriginalJosh/nativescript-swiss-army-knife) which provides this functionality

**Comment by teulys** [comment]
Try this:
set a id to ScrollView like: adtsumscrl

@ViewChild('adtsumscrl') scrollview : ElementRef; 

ngAfterViewInit() {
        let scrollvie = <View>this.scrollview.nativeElement;

        setTimeout(() => {
            if(isAndroid){
                scrollvie.android.setHorizontalScrollBarEnabled(false);
            }
            else if (isIOS) {
                scrollvie.ios.showsHorizontalScrollIndicator = false; 
            }
        }, 10);
    }
