### ISSUE TITLE
Responsive sizing of the screen

### ISSUE THREAD

**Issue by crazycoder775** [NativeScript/nativescript-angular#862]
Hi,

I developed an app using NativeScript with Angular 2. Wrote the UI according to the official docs. Mostly stacked / grid layouts. I developed it using an Android emulator with 5 inch screen and it looks fine while testing on a 5 " device but while I tried to test on 4.7" or other lower screen sizes, the layout is not the same. It is either cutting down some text or hiding few components. 

I suppose the layout would be auto-aligned accordingly based on the screen size (if not for tablets, at least for all mobile screen sizes because I cannot build different APK versions based on the screen size, if you know what I mean). If it doesn't automatically align the sizes, how do I fix it ? by giving the values based on a percentage or any other work around ? I declared all the css properties without px. 
eg : margin : 20;

NOTE: I am trying to keep the look same for all mobile screen sizes.

**Comment by NickIliev** [comment]
@crazycoder775 in NativeScript the main unit is DP (a.k.a DIPs) - Device Independent Pixels which are calculated based on the screen density and scale. For GridLayouts you can also create youtr rows and cols using not only DP but also **auto** (will take only as much space as needed) or * (will take all the available space left). 

When working with images the best practice is to use the native folders (located in `App_Resources/Android` or `App_Resources/iOS`) and provide different scaled images for the different screens. More details can be found [here](https://docs.nativescript.org/publishing/creating-launch-screens-android) and [here](https://docs.nativescript.org/publishing/creating-launch-screens-ios)

**Comment by flipimmobilier** [comment]
I have long sought a solution to this problem in nativescript so here is a simple and free solution to manage in css the different size and format.

///////////////////////typescript code///////////////////////////////////////////////////
import { screen } from "tns-core-modules/platform";
  ngOnInit(): void {
    const deviceWidth: number = screen.mainScreen.widthDIPs;
    if (deviceWidth >= 1280) {
      this.ClassResponsive = "1280";
    } else if (deviceWidth >= 1024) {
      this.ClassResponsive = "1024";
    } else if (deviceWidth >= 800) {
        this.ClassResponsive = "800";
    } else if (deviceWidth >= 600) {
        this.ClassResponsive = "600";
    } else if (deviceWidth >= 540) {
        this.ClassResponsive = "540";
    } else if (deviceWidth >= 480) {//toute est bon dans cette grandeur!!!!!!!!!!!!!!!
        this.ClassResponsive ="480";
    } else if (deviceWidth >= 400) {
        this.ClassResponsive = "400";
    } else if (deviceWidth >= 360) {
        this.ClassResponsive = "360";
    }
}

ClassResponsive: any = "";


[class]="ClassResponsive"


after in css:
.360 .element{
}
.400 .element{
}

........
