### ISSUE TITLE
ListPicker examples

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#87]
These seem hard to come by. 
The api also doesn't appear to support events such as when selection changes?
https://docs.nativescript.org/ApiReference/ui/list-picker/ListPicker.html

Curious to develop with this component and trying to find ways forward with it.
It seems a common case would be to use a `Label`:
```
<Label text="Open" (tag)="openPicker()"></Label>
<ListPicker id="picker" class="picker" items="{{ items }}" selectedIndex="{{ selectedIndex }}"
              verticalAlignment="center" horizontalAlignment="center"/>

// css
// hide off page initially
.picker {
  top: -100;
  left:0;
  width:100%;
}
```

Which would open the picker by animating it into view?
```
// some component
public openPicker() {
   let picker = page.getViewById('picker');
   picker.animate({
        translate: { x: 0, y: 0 },
        duration: 300
    });
}
```

Is this way off? 
Anyone know best way forward with this component?

**Comment by hdeshev** [comment]
The list picker API has been designed in that way because it takes advantage of the dependency property system and its change notifications in vanilla NativeScript. Which we don't use much in Angular apps since Angular comes with its own bindings and change detection.

To bridge between the two, we allow you to listen for a "helper" event that fires whenever a dependency property changes. You get the name of the event by appending a "Change" to the name of the property. Here's how my list picker code looks now:

```html
<ListPicker #picker class="picker" [items]="items" [selectedIndex]="selectedIndex" 
    verticalAlignment="center" horizontalAlignment="center" 
    (selectedIndexChange)="selectedIndexChanged(picker)"></ListPicker>
```

```typescript
public selectedIndexChanged(picker) {
    console.log('picker selection: ' + picker.selectedIndex);
}

```

**Comment by NathanWalker** [comment]
Thank you @hdeshev! Good to know!

**Comment by jlooper** [comment]
hi, @hdeshev, I have a question on the way the Angular version of the ListPicker works. Currently I'm not able to set a default selectedIndex as pulled from the database:

```
<ListPicker #instrumentListPicker [selectedIndex]="instrument" [(ngModel)]="selectedInstrumentIndex" [items]="instruments" (selectedIndexChange)="selectedIndexChanged(instrumentListPicker)"></ListPicker>
```

Watching the console logs from selectedIndexChanged(), the value seems to be tested several times, flipping back to 0:

```
CONSOLE LOG file:///app/app/frameworks/practicebuddy/components/student-admin/student-admin.component.ts:108:16: picker selection: 10
CONSOLE LOG file:///app/app/frameworks/practicebuddy/components/student-admin/student-admin.component.ts:108:16: picker selection: 0
CONSOLE LOG file:///app/app/frameworks/practicebuddy/components/student-admin/student-admin.component.ts:108:16: picker selection: 10
CONSOLE LOG file:///app/app/frameworks/practicebuddy/components/student-admin/student-admin.component.ts:108:16: picker selection: 0
```

Whaaaat am I doing wrong!? thanks!

**Comment by x00** [comment]
why would you use `(selectedIndexChange)` and 'selectedIndex' and `[(ngModel)]` you are quadrupling the binding no?

**Comment by mutazmq** [comment]
How to animate the ListPicker from the bottom of the screen when a label is tapped? (in both Android and IOS). I'm unable to find examples that support this. 
Note: I'm using NS with Angular.

**Comment by sagar1911** [comment]
Hi @hdeshev ,
<ListPicker id="picker" class="picker" items={{items}} selectedIndexChange="onselectedIndexChanged"></ListPicker>

exports.onselectedIndexChanged = function() {
      console.log(page.getViewById("picker").selectedIndex);
}

will this work in NS-Core ????

**Comment by genkan-drew** [comment]
I'm trying to get the ListPicker to load a list of items from a API call. I changed the [items]="items" to items={{items}}, but now each list item has one single letter.

![screen shot 2017-09-08 at 11 21 31 am](https://user-images.githubusercontent.com/19398793/30192008-05cdd402-9488-11e7-8c30-534c140ceade.png)

**Comment by nmongiya** [comment]
Hey @genkan-drew , did you manage to get the solution for your problem? I am also facing the same issue. I changed the [items]="items" to items={{items}}, but now each list item has one single letter.

**Comment by nmongiya** [comment]
I realised that I was using the Array and that was causing the above issue. I have changed it to ObservableArray and it is working fine.
