### ISSUE TITLE
Navigation and dynamic params

### ISSUE THREAD

**Issue by nikis** [NativeScript/nativescript-angular#876]
I have following situation:
- Two pages /details and /detail/:id 
- Using RouterExtensions to navigate between pages
- In /detail/:id there are links to /detail/:id but with different :id values 

And i have these actions:
- Open /details and click on /detail/1
- From /detail/1 page i click on /detail/2 link
- From /detail/2 page i click on /detail/3 link

When i start go back, navigation does not keep sequence and go direct to /details

package.json:

```
"dependencies": {
    "@angular/animations": "~4.0.0",
    "@angular/common": "~4.0.0",
    "@angular/compiler": "~4.0.0",
    "@angular/core": "~4.0.0",
    "@angular/forms": "~4.0.0",
    "@angular/http": "~4.0.0",
    "@angular/platform-browser": "~4.0.0",
    "@angular/platform-browser-dynamic": "~4.0.0",
    "@angular/router": "~4.0.0",
    "moment": "^2.18.1",
    "nativescript-angular": "^3.0.0",
    "nativescript-drop-down": "^3.0.0",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-ngx-fonticon": "^2.2.1",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "~1.0.2",
    "query-string-object": "^0.2.5",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "^3.0.1",
    "zone.js": "~0.8.2"
  }
```

**Comment by NickIliev** [comment]
@nikis the router extensions have its own exposed methods for navigation back as described [here](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#navigating-back) - you can create your own back navigation using them.
