### ISSUE TITLE
Navigation Best Practices - Complex Navigation

### ISSUE THREAD

**Issue by shabib3** [NativeScript/nativescript-angular#879]
Hey,

I am trying to navigate correcly im my app, but for me there is a lot of things that is hard to understand what is the right way to do that.

for example route from **page1 to page2**, and then from **page2 to page3** and then from **page3 to page4** and then from **page4 to page2** but make sure that page3 and page4 will be removed from the history.

again this is the scenario:
**page1 -> page2
page2 -> page3
page3 -> page4
page4 -> page2**

and in the end of this scenario that history will be **page1/page2**

What I am asking is what is the right way to do that? with <page-route-outlet> or <route-outlet>? with children? with Angular Route or with RouterExtension?

If there is a good tutorial that you familiar with I would be happy to get it. :)

Thank you very much,
Bar.

**Comment by NickIliev** [comment]
@shabib3 the navigation in Angular is best covered in [this article](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#router) and you can also use this application as a real-life reference on how to navigate in a bigger app with many modules (in this case over 200). The application is also covering the usage of [Lazy Loading ](https://www.nativescript.org/blog/optimizing-app-loading-time-with-angular-2-lazy-loading)to improve the overall startup time and will show you how to create your routes when using lazy loading.

Regarding the questions about removing specific pages from the navigation stack I would recommend going through [this documentation section](http://docs.nativescript.org/angular/core-concepts/angular-navigation.html#clearing-page-navigation-history) where the usage of clearHistory is explained.

[Chapter 3 from the Groceries tutorial ](http://docs.nativescript.org/angular/tutorial/ng-chapter-3.html#35-routing)is covering the routing techniques so I would recommend going through the whole tutorial as well.

Please keep in mind that this repository is mainly for logging issues, bugs, and feature request so more How-To oriented questions should be posted in the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/) or SO.

**Comment by shabib3** [comment]
Thank you so much!

Just so you know, the **clearHistory** doesn't do the job for the issue that I wrote...because if I would use **clearHistory** from **page4 to page2**, when I press back from **page2**, I will exit the app instead of going to **page1**...
