### ISSUE TITLE
ListPicker wraps around?

### ISSUE THREAD

**Issue by tigrenok00** [NativeScript/nativescript-angular#881]
Hi,
I've noticed this issue on certain android models but not others:
When scrolling in a ListPicker, there is a option to scroll up and get to the end values of the list, it sort of wraps around with the values. Is it a bug? How can I prevent this, and limit the scroll of the list when getting to first and last value?
Thank you

**Comment by NickIliev** [comment]
Hey, @tigrenok00 can you tell me on what API level (or what devices) you are experiencing the wrapping?
We have [this application](https://github.com/NativeScript/nativescript-sdk-examples-ng) where you can find[ a basic demo for ListPicker](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ui-category/listpicker/creating-listpicker) - can you confirm that this is happening in the linked example as well?

**Comment by tigrenok00** [comment]
@NickIliev Hi, it happens on android 5.0.1 (and maybe on 5.1.1 as well)

**Comment by NickIliev** [comment]
@tigrenok00 even on Android 5.x.x I was not able to reproduce the issue - would it be possible to provide sample code that best demonstrates your case. (I have used [this sample](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ui-category/listpicker/creating-listpicker) to test on Android 5.0.1)
