### ISSUE TITLE
Image Border Radius

### ISSUE THREAD

**Issue by jogboms** [NativeScript/nativescript-angular#884]
Running on Android v7. Using TNS `3.1.1`

``` html
<Image src="res://image" width="50" borderRadius="100"></Image>
<Image src="res://image" width="50" borderRadius="100"></Image>
```
doesn't seem to apply border radius to any of the images.

**Comment by NickIliev** [comment]
Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/4521](https://github.com/NativeScript/NativeScript/issues/4521)
