### ISSUE TITLE
[Angular] Slider with two-way binding remains stuck after first usage

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/nativescript-angular#887]
_From @manoldonev on July 7, 2017 11:17_

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.2
- Cross-platform modules: 3.1.0
- Runtime(s): 3.1.0

### Please tell us how to recreate the issue in as much detail as possible.
Slider with two-way ngModel binding remains stuck after first usage. No errors are thrown but you cannot move the slider in either direction anymore. If you navigate away from the page and return back to it, the control is again operational on first usage, then remains stuck. This works correctly on Android.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
The issue is reproducible with any of the sliders in the Angular sdk examples that use two-way data binding [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/ui-category/slider/slider-access-value-code). You just need to update the tns-core-modules version in the app package.json to "~3.1.0".

_Copied from original issue: NativeScript/NativeScript#4530_

**Comment by manoldonev** [comment]
Hey guys, we came across this problem when we updated our https://github.com/NativeScript/template-master-detail-ng template to latest NativeScript. Generally we'd prefer not to hack / workaround this particular issue in the template -- do you have an estimate for the fix?

**Comment by KLLaw** [comment]
We are having the same issue. 
Sliders were working fine under 3.0.0, but not anymore after updating to 3.1.0 and up.

Any estimate for the fix would be nice.

**Comment by rowdyrabouw** [comment]
It's a very nasty issue.
We use quit a lot of Sliders and can't upgrade beyond 3.0.0 and Angular 4.1.

This is the last working combination:
"dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.0.0"
}

Can you please fix it?

**Comment by DimitarTodorov** [comment]
@sis0k0 
This issue is still reproducing in an app created from our template-master-detail-ng referencing official and  nativescript-angular@next versions. Can we reopen the issue?

**Comment by DimitarTodorov** [comment]
Issue is fixed with angular: 4.4+ and nativescript-angular: 4.4+.
