### ISSUE TITLE
angular http response.text() now returns [object Object]. Previously [{"Id":1,"Name":"BUC ...  

### ISSUE THREAD

**Issue by matt4446** [NativeScript/nativescript-angular#89]
It's not a big issue, and a little awkward to ask now :) ... as I get my array of objects from `.json()` [in my last issue](https://github.com/NativeScript/nativescript-angular/issues/78). 

I pretty much cleared my logging after that so I've only just noticed. Feel free to keep things the way they are as its just a nice to know. 

```
let text = response.text();
console.log(text);
```
results in: 
```
JS: =Debug===============
JS: [object Object],[object Object],[object Object]
```
It is a string (I checked)... just a very insignificant string. 
The '.text()' version should be the result body (i imagine its due to the content type header, which was fixed in core to automatically serialize) when the command should result in the content body in text format. 

Previous text: 
```
JS: [{"Id":1,"Name":"BUCS","Logo":"content/logos/bucs-logo.jpg","CompetitionCount":4},{"Id":2,"Name":"SUTL","Logo":"content/logos/sutl.jpg","CompetitionCount":8},{"Id":1008,"Name":"South East Region","Logo":null,"CompetitionCount":4}]
```

The later is quite useful for debugging, but I don't really have a use case beyond that. 

I have a workaround for the moment: 
```
var subscription = requestObservable.subscribe(response => {
	let text = response.text();
	let json = response.json();

	this.Notify(text);
	let jsonAsText = JSON.stringify(json)
	this.Notify(jsonAsText);
});
```

Results in: 
```
JS: =Debug===============
JS: 2016-02-25T23:27:46.876Z: [object Object],[object Object],[object Object]
JS: ======================
JS: =Debug===============
JS: 2016-02-25T23:27:46.878Z: [{"Id":1,"Name":"BUCS","Logo":"content/logos/bucs-logo.jpg","CompetitionCount":4},{"Id":2,"Name":"SUTL","Logo":"content/logos/sutl.jpg","CompetitionCount":8},{"Id":1008,"Name":"South East Region","Logo":null,"CompetitionCount":4}]
```

**Comment by vakrilov** [comment]
@matt4446 Indeed. When the response-type of the XHR request is `json` it is automatically parsed and returned as an object. The [`text()` method](https://github.com/angular/angular/blob/f2c7946cca76ab0013970b9cb013db928072fecb/modules/angular2/src/http/static_response.ts#L107) of the response object will only call `.toString()` of the xhr.response object - so you will get the `[object Object],[object Object],[object Object]` string.
Note, that if the response type is not `json` you will get the actual string of the response.
Does this makes sense?

**Comment by matt4446** [comment]
I only use the `.json()` and `.text()` in combination for debugging really. It saves on loading up fiddler. So as I pointed out it isn't a big problem, however, I'll point out one scenario where it might be trouble in the last paragraph. 

@vakrilov Yes. I understand the implementation, but... 
The [docs](https://angular.io/docs/js/latest/api/http/Response-class.html) state `text()`: `Returns the body as a string, presuming toString() can be called on the response body.` and `json()` : `Attempts to return body as parsed JSON object, or raises an exception.`. It doesn't mention response types. 

I would go with technically you may be playing by the rules, but the browsers are being less ambiguous and display any request's body as text (it had for my JSON results at least). Its been a few months since I've checked but `text()` on the web would always present the body in text and the 'json()' would always present it as an object, providing it could serialize it. `[object Object] etc` is unfortunate as it does not represent the body of the request. 

I'll also add that not all APIs respond the way they should. SendGrid's V2 API was bad like that returning JSON but as a text response type, which leads to: `json()`, `blob()` and `text()` ... should they cause serialization of the request body / reserialize / continue with the automated serialization... I'll leave it to your implementation and judgment. There is just the potential that it could limit calling some APIs without knowing some additional hacks.
