### ISSUE TITLE
Angular injection parameter resolution errors with core modules

### ISSUE THREAD

**Issue by vcooley** [NativeScript/nativescript-angular#893]
I am currently receiving the following error when trying to inject page into a component:

`Error:(13, 2) Angular: Can't resolve all parameters for LoginComponent in /Users/vincecooley/Projects/partnerpay/app/login/login.component.ts: ([object Object], [object Object], [object Object], ?).`

My current code looks like:

```
import { Page } from 'ui/page';

export class LoginComponent {
  constructor(\* . . . \* private page: Page) {}
}
```

I have found a workaround that fixes these errors, which is to use the full path for the page module (i.e. `import { Page } from 'tns-core-modules/ui/page';`). I do not like this approach though, since it is not the standard way to import the core modules in {N}.

**Comment by tsonevn** [comment]
Hi @vcooley,
The both ways are correct to import the `Page` while using `ui/page` or the full path `tns-core-modules/ui/page`. 
I tested the both ways on my side and they are working as expected and I could access the page without any issues on both iOS and Android. 
For your convenience I am attaching sample project, please review it and make the needed changes, which will allow me to reproduce the issue.

Regarding that, any further info about your environment will also help(CLI, tns-core-modules, node versions)
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1144426/Archive.zip)

**Comment by vcooley** [comment]
I believe I found the issue. I had a mismatched version number for `@angular/language-service` installed (used `^4.1.0` where all my other Angular packages were `~4.1.0`).

**Comment by vcooley** [comment]
Well, I managed to fix that problem by making `@angular/language-service` match the installed version of angular (switched from `^4.1.0` to `~4.1.0` to match other Angular packages). However, I am now getting another error for each of those instances where I'm injecting page:
`Error:(13, 2) Angular: Error encountered resolving symbol values statically. Could not resolve ui/page relative to /Users/vincecooley/Projects/my-project/app/login/login.component.ts.`

**Comment by tsonevn** [comment]
Hi @vcooley 
The second error might be related to webpack. Make sure that you are using the latest version of `nativescript-dev-webpack` `0.7.3`. Regarding the problem, could you send us your project `package.json` file. Also any additional information about the problem will help.

**Comment by vcooley** [comment]
I am not currently using webpack. Here is my current `package.json`. Thanks for taking a look.

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MyProject",
    "tns-ios": {
      "version": "3.0.1"
    },
    "tns-android": {
      "version": "3.0.1"
    }
  },
  "scripts": {
    "lint": "tslint 'app/**/*.ts?(x)'",
    "test ios": "tns test ios",
    "test android": "tns test android"
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/platform-browser-dynamic": "~4.1.0",
    "@angular/router": "~4.1.0",
    "card-validator": "^4.1.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "codelyzer": "^3.0.0-beta.4",
    "crypto-js": "^3.1.9-1",
    "datasets-us-states-names": "^1.0.0",
    "datasets-us-states-names-abbr": "^1.0.0",
    "lodash": "^4.17.4",
    "nativescript-advanced-webview": "^1.1.3",
    "nativescript-angular": "~3.0.0",
    "nativescript-async": "^1.0.2",
    "nativescript-drop-down": "^3.0.2",
    "nativescript-floatingactionbutton": "^3.0.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-iqkeyboardmanager": "^1.1.0",
    "nativescript-numeric-keyboard": "^3.0.3",
    "nativescript-sqlite": "^1.1.3",
    "nativescript-telerik-ui-pro": "file:./nativescript-ui-pro.tgz",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-unit-test-runner": "^0.3.4",
    "nock": "^9.0.13",
    "oauth": "file:./scripts/oauth",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.1",
    "squel": "^5.8.0",
    "tns-core-modules": "~3.0.1",
    "tslib": "^1.6.1",
    "zone.js": "~0.8.10"
  },
  "devDependencies": {
    "@angular/language-service": "~4.1.0",
    "@types/jasmine": "^2.5.47",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "chai": "^3.5.0",
    "del": "^2.2.2",
    "gulp": "^3.9.1",
    "gulp-mocha": "^4.3.1",
    "gulp-shell": "^0.6.3",
    "jasmine": "^2.5.3",
    "karma": "^1.5.0",
    "karma-chai": "^0.1.0",
    "karma-jasmine": "^1.1.0",
    "karma-junit-reporter": "^1.2.0",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "karma-sinon": "^1.0.5",
    "karma-spec-reporter": "0.0.30",
    "lazy": "1.0.11",
    "mocha": "^3.2.0",
    "mocha-jenkins-reporter": "^0.3.7",
    "mocha-typescript": "^1.0.23",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.4.2",
    "q": "^1.5.0",
    "sinon": "^2.1.0",
    "tns-platform-declarations": "^3.0.1",
    "tslint": "^4.5.1",
    "typescript": "~2.3.4",
    "vinyl-paths": "^2.1.0",
    "wd": "^1.2.0",
    "zone.js": "~0.7.2"
  }
}

```

**Comment by sis0k0** [comment]
@vcooley, can you share your tsconfig?

**Comment by vcooley** [comment]
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "skipLibCheck": true,
        "strictNullChecks": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable",
            "es2016.array.include"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts",
        "android.d.ts",
        "_helpers.d.ts"
    ]
}
```
