### ISSUE TITLE
Routing history is automatically cleared when user triggers navigation but remains in the same place

### ISSUE THREAD

**Issue by ScottF77** [NativeScript/nativescript-angular#894]
In my application I have a standard setup, a side menu for navigation to different view and once inside one of these I have a back button in the header.

I have a problem that if the main menu item is triggered for a view while the user is already inside that view they do not move anywhere but the history is cleared and thus leaves the back button with nowhere to go.

**clearHistory** happens in **nativescript-angular/router/ns-router-link.ts** but I think it would be better to only trigger this if the target path is found to be different.

**Comment by tsonevn** [comment]
Hi @ScottF77,
I tested the described scenario in a sample project, however, I was unable to recreate this scenario on my side. For your convenience, I am attaching sample project, please could you review it and to make the needed changes, which will allow us to review your specific case and verify whether I am missing something. 

In the attached project, when you navigate to the second page and tap the label, which should make navigation to the current page with `clearHistory`, the back button will still work as expected.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1144778/Archive.zip)
