### ISSUE TITLE
how to update users information  

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/nativescript-angular#898]
am building a social app with angular and i want users to be able to update their information from their profiles
any ideas about this 

thanks

**Comment by NickIliev** [comment]
@nelsonwilliam11 the official repositories issues are for logging bug, discussing issues and feature request.
Please address how-to related questions in the community channels where you will receive answers to similar problems.
Great place to ask similar question is [https://discourse.nativescript.org/](https://discourse.nativescript.org/)
or SO with tag [nativescript]
