### ISSUE TITLE
ngFor grid-layout adds new array items to the bottom, even if unshift is used

### ISSUE THREAD

**Issue by moritzvieli** [NativeScript/nativescript-angular#899]
If a new array item is added to the array using "unshift", I'd expect the item to appear at the top of an ngFor grid-layout list. However, the item is added to the bottom. As a workaround currently, I duplicate each entry in the list and add it to a new array. This handling of course has some negative performance impact.

Is there another way to get new items appear on top? Or is it a bug?

**Comment by NickIliev** [comment]
@moritzvieli not exactly workaround but I think a better approach would be to use ListView or RadListView to visualize an array of item templates. This way you will not only have better control on how to add/remove source items but you will also have the goodies of those controls such as virtualization and recycling which is very important if your templates are heavy. The performance optimization would be great compared to using the Angular structural directive. Great blog post on that matter can be found [here](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f)

**Comment by moritzvieli** [comment]
@NickIliev Thanks for your fast reply! I switched from ListView to this approach in NS 2.5 because it didn't work with my layout (pull-refresh-combination). But I'll check if I can reproduce this problem in NS 3.
