### ISSUE TITLE
TabView doesn't work with ngFor

### ISSUE THREAD

**Issue by anhoev** [NativeScript/nativescript-angular#90]
I tried some code but they don't work: 

`<TabView>
        <StackLayout *ngFor="#tab of tabs; #i = index" *tabItem="{title: tab.text}">
            content here
        </StackLayout>
</TabView>`
 or 
`
<TabView>
        <StackLayout *ngFor="#tab of tabs; #i = index">
            <StackLayout *tabItem="{title: tab.text}">
               content here 
            </StackLayout>
        </StackLayout>
</TabView>
`

**Comment by anhoev** [comment]
Sorry, I figured out a solution: 
```
    <TabView >
         <template ngFor #tab [ngForOf]="tabs">
            <StackLayout *tabItem="{title: tab.text}">
                content here
            </StackLayout>
         </template>
    </TabView>
```

**Comment by thohe973** [comment]
Another working example with *ngFor syntax:
```
<TabView>
    <ng-container *ngFor="let tab of tabList">
        <StackLayout *tabItem="tab">
            <Label [text]="tab.title"></Label>
        </StackLayout>
    </ng-container>
</TabView>
```
