### ISSUE TITLE
Angular Forms - dirty flag true by default

### ISSUE THREAD

**Issue by sebawita** [NativeScript/nativescript-angular#905]
I am using {N} 3.1.2.
When I try to use form validation on the `TextField` the `dirty` flag is `true` when the app loads, while it should be set to `false` to begin with.

Example:
```
  <TextField #fieldModel="ngModel" required [(ngModel)]="field"></TextField>
  <Label [text]="fieldModel.dirty"></Label>

  <TextField #nameModel="ngModel" required [(ngModel)]="name"></TextField>
  <Label [text]="nameModel.dirty"></Label>
```

**Comment by mdirienzo** [comment]
I am seeing a similar problem in Nativescript-angular 3.1.3. Even if I explicitly reset it after constructed

**Comment by oosthuja** [comment]
Same issues any resolve in 3.x.x branch ?

**Comment by vakrilov** [comment]
Seems to be resolved. Here is a playground with example: https://play.nativescript.org/?template=play-ng&id=1BJcG1&v=2
