### ISSUE TITLE
Is there any possible way to use cordova plugin in nativescript?

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/nativescript-angular#910]
x

**Comment by bradmartin** [comment]
I checked the website for EGHL Payment Gateway. I couldn't find any documentation on the native SDKs, or a Cordova wrapper, but I did read it has Android and iOS SDKs. You can definitely add those to your app and communicate directly with the API provided by those native sdks.

**Comment by priyangamani** [comment]
@bradmartin  But i have one issue for referring context to other class ..
app.android.currentContext || app.android.context||app.android.foregroundActivity||utils.ad.getApplicationContext() nothing worked..
how to pass the current Activity context..

**Comment by rdlauer** [comment]
FYI: https://www.nativescript.org/blog/how-to-use-any-cordova-plugin-with-nativescript

**Comment by priyangamani** [comment]
I created the plugin for eghl .Please refer the link for more info. [](https://github.com/priyangamani/nativescript-plugin-eghl)
