### ISSUE TITLE
Plugin to interact Nativescript with Mapbox SDK

### ISSUE THREAD

**Issue by Shifs** [NativeScript/nativescript-angular#912]
I want turn by turn navigation (like a GPS system) from point A to point B. In order to achieve this, I need to create a “plugin” to allow NativeScript to interact with the native Mapbox SDK.
I wanted some information on how to create plugins in Nativescript. Since I am very new to the technology , I wanted to know how much time estimate it will taek to achieve this for a newbie.

**Comment by bradmartin** [comment]
@Shifs - A lot of the native SDK has already been exposed in a plugin https://github.com/EddyVerbruggen/nativescript-mapbox if there are missing pieces in the plugin you can definitely fork the plugin repo and submit a PR. Eddy is great at getting contributions published.

**Comment by NickIliev** [comment]
@Shifs if you need detailed information on how to create your NativeScript plugins you can refer to the plugins section in[ the official documentation](http://docs.nativescript.org/angular/plugins/building-plugins.html) where currently there are 11 articles covering all the aspects a developer might need to handle when creating a plugin.
