### ISSUE TITLE
passing current context to java File in nativescript(Switch js to (Android) Activity onTap by using app.android.context )

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/nativescript-angular#915]
![b501820996221b01dd6f0dbcc2652229b5c61ca6_1_302x500](https://user-images.githubusercontent.com/6038069/28551839-0a7ee074-711d-11e7-8ebb-29697375915a.png)

This was my Error Report(By using **app.android.context||app.android.foregroundActivity**)
![device-2017-07-25-094357](https://user-images.githubusercontent.com/6038069/28551971-e683ced6-711d-11e7-830e-5ed9a2cb1c6f.png)

**Comment by vakrilov** [comment]
Can you please provide a little more context about the exception.
It looks like the root of the problem is `java.lang.NullPointerException: uriString in com.eghl.sdk.PaymentActivity` which is not related to the `nativescript-angular` plugin.

**Comment by priyangamani** [comment]
@vakrilov  
Iam using 3rd Party android sdk 
var eghl = new com.eghl.sdk.EGHL.getInstance();
Trying to execute this method by using  context  
var activity=app.android.foregroundActivity||app.android.startActivity;
**eghl.executePayment(paymentParams,activity);**
Error File
![continuation](https://user-images.githubusercontent.com/6038069/28562727-09c938f8-7156-11e7-8bff-fc65245bf0ae.png)
