### ISSUE TITLE
Using Pipes - ExpressionChangedAfterItHasBeenCheckedException

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#92]
```
<Label [text]="'LOVE_TECH' | translate"></Label>
```

Using [ng2-translate](https://github.com/ocombe/ng2-translate) for that. Standard pipe though. Everything is setup correctly with it in terms of loading locales via .json files.
Throws this error:
![screen shot 2016-02-26 at 9 29 37 am](https://cloud.githubusercontent.com/assets/457187/13367853/86e51886-dc9a-11e5-9d56-b6f5158863c2.png)

**Comment by NathanWalker** [comment]
This is with these `dependencies`:
```
"angular2": "2.0.0-beta.7",
    "nativescript-angular": "0.0.35",
    "ng2-translate": "^1.7.3",
    "parse5": "1.4.2",
    "punycode": "1.3.2",
    "querystring": "0.2.0",
    "reflect-metadata": "0.1.2",
    "rimraf": "^2.5.1",
    "rxjs": "5.0.0-beta.2",
    "tns-core-modules": "^1.7.0-angular-0",
    "url": "0.10.3",
    "zone.js": "0.5.15"
```

**Comment by NathanWalker** [comment]
Could this be because I need `ChangeDetectionStrategy.OnPush` on the component?
Trying to figure out the exact cases where thats needed vs. not.

**Comment by matt4446** [comment]
Oddly enough that might be why I added that line to one of my decorators. I'm pretty sure I had some directives working at one point or another (to make all text upper case for headers) but I don't have it on anymore. I'll check later on when I get back from work.

**Comment by matt4446** [comment]
`ChangeDetectionStrategy.OnPush` was not needed by the looks of it. I have it on my `control` directive, but I added the pipe to my `page` directive. 

[title pipe](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pipes/title.ts) - It was going to make my life easier making everything caps... good example .. undecided whether I will use it.  
[decorator](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/decorators/page.ts#L48) - adding `pipes: [MyPipe]` should work fine in the `@component` decorator 

[page view](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/startPage/startPage.html#L6) - the pipe is hidden away in the page decorator.

**Comment by NathanWalker** [comment]
Interesting. good insight. I'm seeing strange issues with change detection. will need to dive deeper when I get the chance.

**Comment by matt4446** [comment]
What kind of issues?

I have added a pipe using moment.js to format some dates. It worked except for the hours are off for some reason (I wonder what the local settings are on Genymotion). [This is within](https://github.com/matt4446/WhatsMyScore2-NativeScript/blob/master/app/pages/regionPage/regionPage.html#L20) `*ng-for` template. The items form correctly when the HTTP request is completed and the empty array is replaced with a collection.  

I've taken away the change detection on the other directive (so it should be what nativescript uses by default now).

**Comment by NathanWalker** [comment]
Just what is posted above... `changed after it was checked`... just in advanced seed on a branch when I use the translate pipes. I also see it with `[(ngModel)]`. Strange as I see other examples that work with that so need to look deeper.

**Comment by hdeshev** [comment]
I tried reproducing that [here](https://github.com/hdeshev/ng2-translate-ns-demo/blob/master/app/app.component.ts), but it seems to work fine on my end. Of course, I tested it with a very simple scenario, and we probably need to look deeper.

---

I took the opportunity to play with ng2-translate, and it looks really nice. I think we can easily implement a proper (instead of [this one](https://github.com/hdeshev/ng2-translate-ns-demo/blob/master/app/static-files-loader.ts)) static file translation loader and provide a plugin for nativescript.

**Comment by NathanWalker** [comment]
@hdeshev excellent, thanks for trying it out. Curious though, shouldn't it work just fine with `ng2-translate`'s default static loader which uses `Http`?  Shouldn't need to `provide` a custom one I wouldn't think as long as you set the location properly:
```
translate.useStaticFilesLoader('~/assets/i18n');
```
![screen shot 2016-03-01 at 8 38 04 am](https://cloud.githubusercontent.com/assets/457187/13433947/fac80114-df88-11e5-8cc0-1b9530e8262d.png)

Shouldn't that work to just load `.json` files from that 'local to project directory' resource via `Http` as normal?

I haven't gotten it to work btw with that, but it seems like it should right?

**Comment by hdeshev** [comment]
AFAIK `Http` does HTTP requests via the XHR object, which would work if your localization resources are stored on a server somewhere. (That almost feels like a valid use case.) That's why I wanted to try using the NativeScript file system API's first.

**Comment by NathanWalker** [comment]
With adding a milestone to this, curious if you are thinking of adding a proper static loader as you mentioned above, and basic example here https://github.com/hdeshev/ng2-translate-ns-demo/blob/master/app/static-files-loader.ts to `nativescript-angular` itself (wouldn't make sense IMO) or for supporting 3rd party libraries, adding as a separate npm module?  

Best way forward with things like this where it's a supporting piece to help make a 3rd party library work with `nativescript-angular`, should there be a standard practice to follow?
I would like to start building some supporting things for `nativescript-angular` that aren't specific to core necessarily but would either be utilities or like this, support a 3rd party library, and curious what you're thinking is with regards to how to publish stuff like that. 
* Standard naming convention? prefix?  `nativescript-ng2-translate-loader`? `tns-angular-translate-loader`?
* Add docs on a wiki here describing how to use them?

This is the type of stuff that would also be well served to highlight in a `nativescript-angular` cookbook with different recipe's detailing how to do things and integrate with other libs, etc. I could help with such a cookbook. How to do modals as mentioned here would also be nice in the cookbook (once they work): https://github.com/NativeScript/nativescript-angular/issues/98  

Just want to be sure I'm on the same page with what the core team is thinking about stuff like this since a milestone label has been added.

**Comment by NathanWalker** [comment]
@hdeshev I went ahead and implemented a working loader for {N} here which loads `.json` locale files from local resources: :+1: 

https://github.com/NathanWalker/angular2-seed-advanced/blob/master/nativescript/app/shared/core/services/ng2-translate-loader.service.ts

**Comment by hdeshev** [comment]
@NathanWalker this is really great. Love your work!

As for the milestone thing, I wanted to start a small plugin with a name like `nativescript-ng2-translate` and host the implementation there. I haven't started on that, so, if you want, you're welcome to do it.

The cookbook section in the docs sounds nice. I'll probably work on setting up a build for the nativescript-angular docs this week and I have several articles planned for that section already: routes and navigation, for example.

**Comment by NathanWalker** [comment]
@hdeshev I'll create this small plugin tonight! :+1: I'll post back here when it's ready and then close this issue afterwards.

**Comment by matt4446** [comment]
@NathanWalker That's great! I'll give that a go when it becomes a plugin. :+1:

**Comment by NathanWalker** [comment]
@hdeshev This plugin now exists: https://www.npmjs.com/package/nativescript-ng2-translate
Works great!
