### ISSUE TITLE
Livesync and lazy loaded modules results in white screen

### ISSUE THREAD

**Issue by thaoula** [NativeScript/nativescript-angular#920]
Hi Guys,

I am trying to create an app using lazy loaded modules. The app appears to work ok however, on first run.

However, livesynced changed seem to force the app to load a white screen. This only occurs if the app must load a lazy loaded module. 

Killing the app and starting again will make it work fine. Make one change and you get a white screen on IOS and a screen with the AppBar visible on IOS.

I have since moved back to a single Module and the problem seems to have gone away.

I was using the  { provide: NgModuleFactoryLoader, useClass: NSModuleFactoryLoader } approach to load the module.

Regards,
Tarek

PS - I am using node 8 and npm 5.3.0
Nativescript Cli 3.1.3
Nativescript IOS 3.1.0
Nativescript Android 3.1.1
tns-core-modules 3.1.0

**Comment by NickIliev** [comment]
Hello @thaoula ,

We have created [this sample application](https://github.com/NativeScript/nativescript-sdk-examples-ng) which is also using lazy loading with the above approach but all changes are applied and when the application is live synced it loads as expected. Can you provide a sample application demonstrating the issue so we could investigate further? You can also check the sample application linked above to compare your code base with ours  (when implementing Lazy loading)
