### ISSUE TITLE
Nativescript angular notify one component from other.

### ISSUE THREAD

**Issue by haris008** [NativeScript/nativescript-angular#921]
Hello All,

is there any way in Nativescript angular to notify one component from other. like we have [NSNotificationCenter](NSNOtificationCenter) in iOS or [BroadcastReceiver](https://developer.android.com/reference/android/content/BroadcastReceiver.html) in Android.

Thanks

**Comment by NickIliev** [comment]
@haris008 can you elaborate more - please provide more information about what you are trying to accomplish by saying "to notify one component from other"

**Comment by haris008** [comment]
So the scenario is, I got a push notification, now I want to notify 1 or 2 components that you need updated x and y values based on push notification.
How can this be achieved?

**Comment by NickIliev** [comment]
@haris008 you can use broadcast receiver (Android) as shown in [this example](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/0b0722025e83126efdf42433f25d1d4a676f9fc0/app/application/app-using-android-specifics/app-using-android-specifics.component.ts#L40-L48) or notification observer for iOS as shown [in this example](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/0b0722025e83126efdf42433f25d1d4a676f9fc0/app/application/app-using-ios-specifics/app-using-ios-specifics.component.ts#L27-L38)

**Comment by davorpeic** [comment]
@NickIliev Hi, how would you emit/catch a custom event with this? Here in the example we can see that we observe android intent, but how can I emit something from one component and use this example to observe it in other one? Thanks
