### ISSUE TITLE
router promise never resolved?

### ISSUE THREAD

**Issue by berchik** [NativeScript/nativescript-angular#925]
Is this the right way of executing a function after all params are read from the router? because in the following code `this.initializeQuestions(this.wid)` is never called:

```
   this.route.params
      .forEach((params) => { 
             this.wid = +params['itemId'];                
        }).then(()=>{
              this.initializeQuestions(this.wid);
        });
```

**Comment by NickIliev** [comment]
@berchik you can wrap your forEach execution in Promise
```
let xxx = true;

new Promise((resolve, reject) => { 
    if(xxx) {
        this.route.params.forEach((params) => {
            console.log(JSON.stringify(params));
        })
        resolve('ok');
    } else {
        reject('error');
    }
}).then(x => {
    console.log("Do somthing"); // e.g. this.initializeQuestions(this.wid);
})
```

**Comment by berchik** [comment]
Thanks @NickIliev. 
This still means that the router promise is never resolved. I can of course wrap it in my own promise as you've suggested but it is quite a lot of code in order to pass params.
