### ISSUE TITLE
zone-nativescript.js locks up my app on Android

### ISSUE THREAD

**Issue by wpfeiffe** [NativeScript/nativescript-angular#930]
I have a nativescript-angular app that I use a combination of the nativescript page routing and angular routing.  Most of the app is delivered out of a single page and I use the angular router to swap out content.  One of my components delivers a google map.  When my user taps a marker on the map, my app navigates to a new route.  This is locking up my app on Android (Not IOS, it works fine).  When I debug through my code I find it all completes without error, however, as I continue to step through, the events where the code runs start to finish up.  After all events are finished, it appears that the zone-nativescript.js is called.  It hits line  593 which calls: task.zone.runTask(task, null, null) in the drainMicroTaskQueue function and never returns controls to the application.

I have several similar navigation behaviors in the app invoked similarly and it doesn't hang up.  This particular path uses a service value which fires events (using rxjs) when changed.  The code appears to work and this really feels like something not getting cleaned up or some race/loop condition, but I've been unable to run it down.

The tns version is 3.1.1.  It looks like the nativescript-angular version in its package.json is 3.0.0.

I will try to reduce this to a simple example and post it.

**Comment by tsonevn** [comment]
Hi @wpfeiffe 
Thank you for contacting us.
Indeed It would help if you could provide a sample project, which is showing your problem and also could be debugged locally. 
In the meantime, you could also verify, whether you will have the same problem with the latest nativescript-angular 3.1.3.

Thank you in advance for your cooperation.
