### ISSUE TITLE
Activity indicator on splash screen

### ISSUE THREAD

**Issue by Nurgunkalol** [NativeScript/nativescript-angular#932]
Hello, how i can add activity indicator to splash screen, cant find any issue about this

**Comment by NickIliev** [comment]
@Nurgunkalol to add any element to splash screen you should add respective native code in your `App_resources` files. However, adding any heavy UI in the splash screen is not recommended in both iOS and Android as the loading screen is meant to be as light as possible and a visual representation of your Application before the actual application logic loads. 

Please, note that the issues in this repository are for logging bugs, features, and issue related threads. For how-to related questions use one of the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/) or SO.
