### ISSUE TITLE
Font awesome FormattedString not working in nativescript angular project

### ISSUE THREAD

**Issue by kmuthukrishnan** [NativeScript/nativescript-angular#933]
Hi 
In my nativescript angular project I am using font awesome icons in some buttons using formatted string like so
```
<StackLayout>
            <Button class=" btn-login" (tap)="onFacebookLoginTap()" >
                        <FormattedString>
                            <Span text="&#xf09a;     Facebook" fontFamily="FontAwesome"</Span>
                        </FormattedString>
                 </Button>
                <Button class="btn-login" tap)="onGoogleLoginTap()" ios:marginBottom="10">
                        <FormattedString>
                            <Span text="&#xf0d5;   Google +" fontFamily="FontAwesome"></Span>
                        </FormattedString>
                    </Button>
            </StackLayout>
```

My package.json
```
{
    "private": false,
    "nativescript": {
        "id": "org.nativescript.helloworldng"
    },
    "name": "tns-template-hello-world-ng",
    "main": "main.js",
    "version": "2.4.5",
    "author": "Telerik <support@telerik.com>",
    "description": "Nativescript Angular Hello World template",
    "license": "BSD",
    "keywords": [
        "telerik",
        "mobile",
        "angular",
        "nativescript",
        "{N}",
        "tns",
        "appbuilder",
        "template"
    ],
    "repository": {
        "type": "git",
        "url": "git://github.com/NativeScript/template-hello-world-ng"
    },
    "homepage": "https://github.com/NativeScript/template-hello-world-ng",
    "android": {
        "v8Flags": "--expose_gc"
    },
    "dependencies": {
        "nativescript-theme-core": "^0.2.1",
        "nativescript-angular": "1.3.0",
        "@angular/core": "2.3.1",
        "@angular/common": "2.3.1",
        "@angular/compiler": "2.3.1",
        "@angular/http": "2.3.1",
        "@angular/platform-browser": "2.3.1",
        "@angular/platform-browser-dynamic": "2.3.1",
        "@angular/forms": "2.3.1",
        "@angular/router": "3.3.1",
        "rxjs": "5.0.0-rc.4",
        "reflect-metadata": "~0.1.8"
    },
    "devDependencies": {
        "zone.js": "~0.7.2",
        "typescript": "~2.0.10",
        "nativescript-dev-typescript": "^0.3.2",
        "nativescript-dev-android-snapshot": "^0.*.*"
    }
}
```
However the font-awesome icons do not show in the button. The same code was working earlier. Any suggestions?

**Comment by NickIliev** [comment]
@kmuthukrishnan I have created test project using the latest supported version of the Angular dependencies and FontAwesome is working as expected for both iOS and Android - the test project can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/nativescript-angular/issue_933).

In your snippet, I've noticed that you have some syntax errors (missing closing tag on the first span and missing opening bracket for the tap event on the second one). Another thing you may try is to apply your FontAwesome via CSS `class`.
e..g
```
<StackLayout>
    <Button class=" btn-login" (tap)="onFacebookLoginTap()">
        <FormattedString>
            <Span text="&#xf09a;     Facebook" class="fa"></Span>
        </FormattedString>
    </Button>
    <Button class="btn-login" (tap)="onGoogleLoginTap()" ios:marginBottom="10">
        <FormattedString>
            <Span text="&#xf0d5;   Google +" class="fa"></Span>
        </FormattedString>
    </Button>
</StackLayout>
```

**Comment by kmuthukrishnan** [comment]
@NickIliev  Thanks for the quick response. The typos on the template were made when logging the issue. Sorry for that.  

I can confirm that your project works. I am still getting the issue, though only on IOS.

**Comment by NickIliev** [comment]
@kmuthukrishnan you might want to check the actual name of the font. In iOS, the name should be the original **font name** and not the **file name**. To see the actual name, locate the font and double click to open it with the default font reader in MAC. 
e.g. even if the file might be named `fontawesome-webfont.ttf` when you open the font with the font reader in MAC you will see that the actual name is **FontAwesome**. Also, try using the CSS class solution instead of setting it via the **fontFamily** inline property.

**Comment by kmuthukrishnan** [comment]
@NickIliev  - Fixed it. But noted something very strange in the process. If we define a btn-login class in app.css like so

```
.btn-login {
    height: 30;
    color: #ffffff;
    font-weight: bold;
    text-transform: capitalize;
    padding-left: 10;
    padding-right: 10;
    margin: 15;
    border-radius: 3;
}
```
You will find that the button does not appear. If you comment out the color property the button starts to appear again. This can also be seen on the sample project that you have created too.
Thanks for your prompt help.

**Comment by NickIliev** [comment]
@kmuthukrishnan  tested the CSS on my side and it is appearing but as the color and the background color are reset to white it is just not visible.. changing at l;east the color to red shows the buttons. Also, they have greater padding/margin than their height so the text is a bit offside.

tried with this
```
.btn-login {
    height: 30;
    color: red;
    font-weight: bold;
    text-transform: capitalize;
    padding-left: 10;
    padding-right: 10;
    margin: 15;
    border-radius: 3;
}
```
