### ISSUE TITLE
IOS - Font-awesome - letters extended downwards get truncated in nativescript angular project

### ISSUE THREAD

**Issue by anuragd7** [NativeScript/nativescript-angular#934]
To see this issue create a new nativescript-angular project for IOS.
In app.css create .fa class for font-awesome.

In the html file create a template like so
```
<Button>
        <FormattedString>
            <Span text="&#xf0d5; Abc  gpqgpqgpq" class="fa"></Span>
        </FormattedString>
 </Button>
```
You will notice that the downward extending letters are getting truncated. The text continues to be truncated even if we reduce the size of the font or give the button a larger height.

**Comment by tsonevn** [comment]
Hi @anuragd7,
We reviewed your case, however, the text and the icon seems to be displayed properly. For your convenience, I am attaching a sample project, you could review it and make the needed changes, which will allow us to recreate the issue
Regarding that please provide some more info about the case.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1214030/Archive.zip)

**Comment by anuragd7** [comment]
Hi @tsonevn 

Thanks for looking into it. I ran the archive you shared and observed the same behavior with the g getting cut off at the bottom. Please see screenshot link [here](https://ibb.co/i2SY4v)

**Comment by tsonevn** [comment]
Hi @anuragd7,
Thank you for the attached screenshot.
In my further investigation, I found that this problem also exists in a pure NativeScript application. I am attaching sample project, where the problem could reproduce. For further info, you could keep track on the issue.
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1217108/Archive.zip)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/NativeScript#4689
