### ISSUE TITLE
Which input options are allowed? 

### ISSUE THREAD

**Issue by tom94zoe** [NativeScript/nativescript-angular#937]
Hi, 

I am wondering if something like debouncing on input is allowed. 
In fact, i want to trigger the event listener of a searchbar when the user does not hit the keyboard for at least 300ms. 
I have not found anything about it. Are such options configurable at the view or do I have to program it by myself? 

Thank you in advance.

**Comment by NickIliev** [comment]
@tom94zoe you can write the logic yourself using either the Angular lifehooks or the NativeScript lifecycles.
For example, you can take the reference to your search bar when it is loaded (e.g. using `loaded` event on the search bar) and then use [the timer module](https://docs.nativescript.org/api-reference/modules/_timer_.html) to call the method when needed.

**Comment by tom94zoe** [comment]
Thank you

**Comment by goyote** [comment]
@tom94zoe how did you solve this?
