### ISSUE TITLE
 'Module '@angular/router/router"' has no exported member 'ChildrenOutletContexts'.' at: '2,26' source: 'ts'

### ISSUE THREAD

**Issue by nelsonwilliam11** [NativeScript/nativescript-angular#939]
my app was working fine till i updated nativescript-angular and i started to see this error can anyone help or at  least tell me what went wrong 
that error is in   page-routeroutlet.ds.ts file
thanks

**Comment by sis0k0** [comment]
Update @angular to 4.2. Please, post your package.json if that doesn't help.

**Comment by nelsonwilliam11** [comment]
alright cool

**Comment by nelsonwilliam11** [comment]
whats the easiest way to update it???

**Comment by nelsonwilliam11** [comment]
@sis0k0  thanks that help updating @angular solved the problem

**Comment by devgeektech** [comment]
leave the code and make it again
