### ISSUE TITLE
[Android] Adding new items to ListView only works with zone.run when called inside firebase push notification callback

### ISSUE THREAD

**Issue by Liooo** [NativeScript/nativescript-angular#944]
The code below shows the gist of what's happening. When adding items to an array from inside the firebase message received callback, the ListView doesn't get updated unless being wrapped in zone.run().
Why is this?

Thought of asking the question in the  [firebase plugin page](https://github.com/EddyVerbruggen/nativescript-plugin-firebase), but thought this could be an issue of nativescript itself because the [plugin's code](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/firebase.android.js#L322) was looking fairly simple.
Similar issue is discussed in #377, and this is where I knew about using `NgZone`.

assignmnent-list.component.html
```assignmnent-list.html
<StackLayout orientation="vertical" >
  <Button text="add" (tap)="tap()"></Button>
  <ListView verticalAlignment="stretch" [items]="assignments">  
    <ng-template let-assignment="item">
      <StackLayout>
        <Label text="hello"></Label>
      </StackLayout>
    </ng-template>
  </ListView>
</StackLayout>
```

assignmnent-list.component.ts
```ts
import { Component, OnInit, NgZone } from '@angular/core';
import { addOnMessageReceivedCallback } from "nativescript-plugin-firebase"

@Component({
    selector: 'assignment-list',
    templateUrl: './assignment-list.component.html'
})
export class AssignmentListComponent {
  public assignments = [];

  constructor( private zone: NgZone ) { }

  private addAssignments() {
     // this only works when called in tap(), and not in messageReceivedCallback
     // also tried 
     // - `this.assignments.push('new')`
     // - using async pipe (https://docs.nativescript.org/ui/list-view#using-async-pipe)
     // but both resulted in same
     this.assignments = this.assignments.concat('new');

     // this works in both tap() and messageReceivedCallback
     this.zone.run(() => {
       this.assignments = this.assignments.concat('new') 
     });
  }

  tap() { this.addAssignments(); }

  ngOnInit() { addOnMessageReceivedCallback(this.addAssignments.bind(this)); }
}
```

Here's my package.json
```
  "nativescript": {
    "id": "....",
    "tns-ios": {
      "version": "3.1.0"
    },
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "lodash": "^4.17.4",
    "nativescript-angular": "~3.1.0",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-local-notifications": "^1.2.1",
    "nativescript-ngx-fonticon": "^2.2.3",
    "nativescript-plugin-firebase": "^4.0.5",
    "nativescript-speech-recognition": "^1.2.0",
    "nativescript-textinputlayout": "^2.0.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.0",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "codelyzer": "^3.0.1",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.2.0",
    "nativescript-dev-typescript": "~0.5.0",
    "node-sass": "*",
    "tslint": "^5.4.3",
    "typescript": "~2.2.1"
  }
}
```

**Comment by justindujardin** [comment]
@Liooo this is due to how Angular change detection works with Zone.js, and is probably not a bug in NativeScript.

The Zone.js library attempts to patch all the points at which control may transfer to/from your app to the underlying system (usually a browser.) When Zone.js detects that a system call is complete, it automatically updates the bindings in your angular app.

The `nativescript-firebase` plugin invokes your callback directly from Android/iOS native code, and that code is not hooked by Zone.js. This means that you have to manually execute your callback code inside of a zone (like you did in your example) when you receive a change callback from the `nativescript-firebase` library.

The reason it works from `(tap)` is because your function is invoked by the Angular framework, and it properly executes inside of a zone.

**Comment by Liooo** [comment]
@justindujardin makes perfect sense, thank you 👍
