### ISSUE TITLE
Feature: Allow loader to handle relative paths without moduleId

### ISSUE THREAD

**Issue by abdulhaq-e** [NativeScript/nativescript-angular#947]
This is a feature request, I'll dig into the source code to see if it's doable.

On 13-03-17, Angular docs were updated with all references of using `moduleId: module.id` in the component properties were deleted. It isn't required if one uses the new SystemJS plugin (systemjs-angular-loader.js) and if someone is using Angular CLI then it's already not required.

I think it would be great if `tns` was able to handle relative paths without `moduleId`, I see many questions and problems in this repo's issues, it's annoying and easy to forget.

**Comment by NickIliev** [comment]
Supported for Webpack builds 

e.g.
```
npm i nativescript-dev-webpack
tns run android --bundle
```
