### ISSUE TITLE
webpack version don't load platform css

### ISSUE THREAD

**Issue by bumbella** [NativeScript/nativescript-angular#948]
Hi!
I make my project to webpack version ready.
npm install --save-dev nativescript-dev-webpack
npm install

My project folder has
_app_common.scss
app.android.scss
app.ios.scss
app.css (is empty)

app.android.scss content
@import 'app_common.scss';
@import '~nativescript-theme-core/scss/platforms/index.android';

app.ios.scss content
@import 'app_common.scss';
@import '~nativescript-theme-core/scss/platforms/index.ios';

If tns run android then fine but if webpack version npm run start-android-bundle then wrong
app common css is not loaded

Please help me what is the wrong in my code or logic.
It is bug?
Thanx

**Comment by NickIliev** [comment]
Hey @bumbella 

Based on the provided information I think you are hitting [this bug](https://github.com/NativeScript/nativescript-dev-webpack/issues/188). Our developers are currently working on a solution which is planned for version 1.0 of nativescript-dev-webpack. Please stay tuned and track the original issue.

Closing as duplicate to [https://github.com/NativeScript/nativescript-dev-webpack/issues/188](https://github.com/NativeScript/nativescript-dev-webpack/issues/188)
