### ISSUE TITLE
Trouble with Dependency Injection

### ISSUE THREAD

**Issue by SparkValor** [NativeScript/nativescript-angular#95]
I have some trouble with the dependency injection system. Every time I run my app I get the following error:

Error calling module function

ReferenceError: __param is not defined

I tried different things but couldn't get it to work.
Has anyone else have this problem? Am I missing something?

Cheers,
Nils

**Comment by NathanWalker** [comment]
@SparkValor open the `tsconfig.json` and **remove** this line if present:
```
"noEmitHelpers": true  // bad for angular :(
```

That line will cause problems with angular di.
Additionally, make sure you have this **added**:
```
"emitDecoratorMetadata": true,  /// good for angular :)
```

**Comment by hdeshev** [comment]
Disabling `noEmitHelpers` is the best solution at the moment. Unfortunately that will emit helpers in all JS modules. We are fixing that by moving some of the helper definitions to the core NativeScript modules.

NativeScript/NativeScript#1675 fixes the `__params` problem.

**Comment by SparkValor** [comment]
Thanks
