### ISSUE TITLE
Error while tns run android

### ISSUE THREAD

**Issue by LakshmiEvana** [NativeScript/nativescript-angular#950]
Getting below error while tns run android.
![image](https://user-images.githubusercontent.com/17317992/29452466-239a17b2-8424-11e7-9a1d-e3782c1d8bdd.png)

**Comment by NickIliev** [comment]
@LakshmiEvana the issue is most likely not related to Angular. Check [this solution](https://github.com/NativeScript/NativeScript/issues/3875).

Please, when posting issues give as much information as possible including the content of your `package.json` file

**Comment by LakshmiEvana** [comment]
Ok.Thank you @NickIliev.suggested solution worked for me.
