### ISSUE TITLE
Feature: Inject own ErrorHandler in nativescript-angular

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-angular#951]
Hi,

Sometimes an error is triggered in angular, that sends my app into a broken state, not fully crashed but not working right either.
When this happens in production, the user experience is pretty bad.
Unfortunately we don't know about it, unless the user complains to us and we can't handle it in a good way in the app.

What we really need it a way to inject our own `ErrorHandler, but `nativescript-angular` sets up it's own error handler and we cannot override it.
https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/nativescript.module.ts#L23-L25

**Comment by m-abs** [comment]
@tsonevn 
Hi, have you had a chance to look at my pull request?
We'd love to have this included soon.

**Comment by tsonevn** [comment]
@vakrilov

**Comment by danielgek** [comment]
i would love this to get merged!

**Comment by m-abs** [comment]
@danielgek 
Look at the feedback to my PR, you can inject your own ErrorHandler without my PR.
