### ISSUE TITLE
Css animation frozen after resumeEvent [Android][Typescript]

### ISSUE THREAD

**Issue by HighSoftWare96** [NativeScript/nativescript-angular#952]
Hi,
I have inserted in my application a simple css animation to an image. 
The problem is: when I lock the phone (only android tested) the css animation is stuck.
I tried using the resumeEvent and refreshing the page with router navigation, but still not works...
`applicationOn(resumeEvent, function name(args: ApplicationEventData): void {
          if(this.router.url == '/bomb') {
                  this.router.navigate(['']);
                  this.router.navigate(['/bomb']);
         }
 }.bind(this)); `

Are there some other solutions?

**Comment by tsonevn** [comment]
Hi @HighSoftWare96,
Thank you for reporting this issue. 
I reviewed your case and indeed the CSS animation will be stuck, while the app is suspended and will it will not be resumed to its initial state. I am attaching a sample project, which could be used for debugging. 
For further info, you could keep track on the issue. In the meantime, you could define the needed animation via code behind as it is described in [this part](https://docs.nativescript.org/ui/animation-code.html) of the documentation. 
[Archive.zip](https://github.com/NativeScript/nativescript-angular/files/1248838/Archive.zip)

**Comment by tsonevn** [comment]
duplicated with https://github.com/NativeScript/NativeScript/issues/4801
