### ISSUE TITLE
Angular animation using states doesn't work

### ISSUE THREAD

**Issue by madakk** [NativeScript/nativescript-angular#957]
I don't know if I'm missing anything, but I've copy pasted the following example to my own project, and nothing happens:

https://github.com/NativeScript/nativescript-angular/blob/eb3fd81c7bb4cdb9938feea13cd9e34b868e451a/ng-sample/app/examples/animation/animation-states-test.ts

**Comment by sis0k0** [comment]
Perhaps, you are missing the import of `NativeScriptAnimationsModule'?

```
// app.module

import { NativeScriptAnimationsModule } from "nativescript-angular/animations";

// ...
@NgModule({
    imports: [
        NativeScriptAnimationsModule,
    ]
})
export class AppModule
```

**Comment by madakk** [comment]
Of course. I apologize for the tracker noise.

Now I also found [this answer](https://stackoverflow.com/questions/45243411/nativescript-angular-animation-with-states-never-works) which I couldn't find yesterday. In fact, there seems to be very little documentation of animating with states in NativeScript. I also can't really find documentation of the NativeScriptAnimationModule import, it's not mentioned [here](http://docs.nativescript.org/angular/ui/animation) or [here](http://docs.nativescript.org/angular/ui/animation-code.html) or [here](http://docs.nativescript.org/angular/ui/animation-examples.html).

I only see it mentioned in [this blog post](https://www.nativescript.org/blog/nativescript-supports-angular-4) and a few other changelogs etc. Perhaps better documentation is necessary?

Also, maybe there's some way to detect the use of animations without the module being imported, and issue some warning, instead of just failing quietly?
