### ISSUE TITLE
border Radius for searchbar in nativeScript

### ISSUE THREAD

**Issue by steve-frank** [NativeScript/nativescript-angular#965]
I have added a search bar to my app by following samples in SDK examples. 

I am trying to give it rounded corners and gray border. For that I have tried doing something like this: 
```
@ViewChild('searchBarSchool') ngSearchBar: ElementRef;    

 ngAfterViewInit() {        
 this.nsSearchBar = this.ngSearchBar.nativeElement;       
  this.nsSearchBar.backgroundColor = new Color("pink"); 
   this.nsSearchBar.borderRadius = "2"; 
     this.nsSearchBar.borderBottomWidth = 10; 
        this.nsSearchBar.borderColor = new Color("gray");  
    }
```
And in html,
`<SearchBar #searchBarSchool hint="Search for school"(textChange)="onTextChange($event)"      (loaded)="onSearchBarLoaded($event)"></SearchBar>`

I can see the background color "pink" taking effect on UI but borderRadius does not work. I refereed the SearchBar class borderRadius is indeed one of the property there.
ref: https://docs.nativescript.org/api-reference/classes/_ui_search_bar_.searchbar.html.

Can someone help me, I need a rounded borders for my search box.
-- | --

**Comment by NickIliev** [comment]
@steve-frank partial border radiuses are not supported in NativeScript at this very moment.
Meaning that you can set **borderWidth** instead of **borderBottomWidth** and then you will be able to set **borderRadius**. Discussed also [here](https://discourse.nativescript.org/t/border-radius-top-left-is-not-working/452/5?u=nickiliev)

**Comment by evanfuture** [comment]
On the off chance that someone runs across this like I did, Nativescript now **does** support border radius for specific corners.  You can set `border-top-right-radius: 4` and it will just work.

https://github.com/NativeScript/NativeScript/blob/8973a6febde4a4b41637d80b17506a7d25ffebf8/tns-core-modules/ui/styling/style-properties.ts#L896

**Comment by tripper-app** [comment]
i am facing the same problem. i can't give border radius to search bar, the corners remains sharp. any help please?
