### ISSUE TITLE
Feature: Implement HttpClient

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-angular#966]
I was just wondering if there will be any implementations for the new [HttpClient](https://angular.io/guide/http) on Nativescript.

**Comment by dr1ss** [comment]
+1

**Comment by vakrilov** [comment]
We will try to add support for `HttpClient` in the upcoming `4.3` release. In theory it should use the XHR polyfill that is already part of the NativeScript core modules, However some additional changes might be required to make it working in all scenarios.

**Comment by MartinHlavna** [comment]
Hello is this feature available in latest release?

**Comment by vakrilov** [comment]
@MartinHlavna - yes it is.
