### ISSUE TITLE
How to reset scroll position to zero index for list view

### ISSUE THREAD

**Issue by LakshmiEvana** [NativeScript/nativescript-angular#970]

**Comment by NickIliev** [comment]
@LakshmiEvana you can use [scrollToIndex ](http://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview.html#scrolltoindex)method to set the scroll position of your ListView
Please notice that this repository is for logging issues, bugs, and feature related threads.
For how-to related question use one of the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/)

**Comment by LakshmiEvana** [comment]
Ok.Thank You @NickIliev
