### ISSUE TITLE
Cannot access native API of TabView

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-angular#971]
Here it says that we can access native API with `android` and `ios` properties of elements: [http://docs.nativescript.org/angular/tutorial/ng-chapter-6#62-accessing-android-apis](http://docs.nativescript.org/angular/tutorial/ng-chapter-6#62-accessing-android-apis)

In my code, I get a reference to TabView with this line:

````js
@ViewChild('tabView') tabView : ElementRef;
````

It works and I get a reference. However, `elem` variable here is undefined:

````js
ngAfterViewInit() : void {
    let elem = this.tabView.nativeElement.android;
}
````

How can i access the native API here?

**Comment by NickIliev** [comment]
@erkanarslan thank you for reporting this issue. Indeed it seems that the property **android** for **TabView**  returns **undefined**.

Steps to reproduce: use [this sample project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/nativescript-angular/issue_971

On iOS `tabView.ios` is working as expected.

**Comment by NickIliev** [comment]
@erkanarslan the TabView implementation for Android is relaying on GridLayout widget.
To access it in angular you can use the loaded event 
For example:
```
<TabView #tabView (loaded)="onTabLoaded($event)">
```
and in the component file
```
onTabLoaded(args: EventData) {
    let tab = <TabView>args.object;

    console.log("ontabLoaded: " + tab.nativeView)
}
```

**Comment by arunanamal** [comment]
Hi NickIliev,
I used your code, but I'm getting error at EventData. saying Cannot find name 'EventData'

Thanks

**Comment by NickIliev** [comment]
@arunanamal import the class methods, properties, etc. from the related modules.

```
import { EventData, Observable } from "data/observable";
import { TabView} from "ui/tab-view";
```

**Comment by arunanamal** [comment]
Thanks Nick
