### ISSUE TITLE
App worfking on emulator, crash at launch when released

### ISSUE THREAD

**Issue by SD-Lab** [NativeScript/nativescript-angular#974]
Hello,

I try to release an app for 4 days now but I still have crash…

I find on of the issue : in one of my modules, I have got:
`imports: [CommonModule, NativeScriptFormsModule, ReactiveFormsModule ],`
With this code application run fine on emulator (tns run android) but release (tns build android --release …) crash at launch !

When I remove “NativeScriptFormsModule” application release starts without error. If I had NativeScriptFormsModule in a basic HelloWorld, I don’t get any release issue…

I tried to have log informations with “adb logcat” command. Its hard to analyse because of the numbe of lines but I found this error;
`Error: com.tns.NativeScriptException: Failed to find module: "nativescript-angular", relative to: app/tns_modules/`

I’m lost but I realy need to release the application :frowning:

Thanks if you have some ideas or way to get deeper…

Serge

**Comment by NickIliev** [comment]
@SD-Lab can you share the content of your `package.json` or sample project which can reproduce the issue (you can attach an archive without `node_modules` and `platforms` folders)

**Comment by SD-Lab** [comment]
Hello,

I just find the answer couple hours ago, I had an error on declaration:
`import { NativeScriptFormsModule } from "nativescript-angular";`
instead of
`import { NativeScriptFormsModule } from "nativescript-angular/forms";`

but I don't understand why it's works on emulartor with tns run android ...
