### ISSUE TITLE
Good fit for an attempt at 1 codebase mobile native AND webapp ?

### ISSUE THREAD

**Issue by fabm22** [NativeScript/nativescript-angular#975]
Sorry if too generic, but I have two questions regarding the possibility of most code reuse possible between mobile apps AND web.

1. Is there known impossibilities (apart from phone hardware related of course) to share view's code between web and phone apps?

2. Is this even a supported use case from the platform ?

Thank you.

**Comment by NickIliev** [comment]
@fabm22 check out  [angular-seed-advanced repository](https://github.com/NathanWalker/angular-seed-advanced) demonstrating technique to share code base within web and NativeScript

**Comment by vakrilov** [comment]
Hey @fabm22 you can check this blog post on the matter:
[Code Sharing Between Web and Mobile with Angular and NativeScript](https://www.nativescript.org/blog/code-sharing-between-web-and-mobile-with-angular-and-nativescript)
