### ISSUE TITLE
Using page.showModal with @Component's

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-angular#98]
Given `my.component` is an angular `Component`:
```
page.showModal('./pages/my.component', 'Modal Context', () => {
 // close function
}, true);
```

Wasn't too surprised to see it throw this:
```
file:///app/tns_modules/ui/frame/frame-common.js:83:94: JS ERROR Error: Failed to load Page from entry.moduleName: ./pages/my.component
```

Curious how to integrate the page's `showModal` api with `nativescript-angular`.

**Comment by hdeshev** [comment]
I was thinking of modeling that after the [dialog component](https://github.com/angular/angular/tree/master/modules/angular2_material/src/components/dialog) in the material design examples which uses the DynamicComponentLoader to create a dialog and "load" a component in there.

**Comment by nripendra** [comment]
+1

**Comment by NathanWalker** [comment]
@hdeshev that would be great :+1:

**Comment by matt4446** [comment]
:+1:

**Comment by nripendra** [comment]
Any workaround that can be used as of now?

**Comment by hdeshev** [comment]
@nripendra You can create a directive that creates a `Page` object and calls `showModal`. If you build the entire dialog UI in your JS code, it should work.

**Comment by nripendra** [comment]
Not sure if I fully understood. How would I load my angular component into page object?

**Comment by hdeshev** [comment]
I meant that you should not use angular components into the dialog at all and build your entire dialog UI in JavaScript.

**Comment by nripendra** [comment]
Hmm that's bad news. But shouldn't be a problem for now though. I have couple of simple components only in dialog.

**Comment by PedroAnibarro1** [comment]
Hi!

    This was fixed? I'm still getting the error 

     Error: Failed to load Page from entry.moduleName: ./pages/menu/menu.component

    Any idea? Do I need to do something extra to the component? Thanks

**Comment by vakrilov** [comment]
@PedroAnibarro1 
In apps using angular you should not call `showModal` of the page directly (its equivalent of working directly with DOM elements in a ng-web app - you should avoid it). [Check this article](http://docs.nativescript.org/angular/ui/ui-dialogs.html#custom-dialog) that explains how to show modals in angular-nativescript app.

**Comment by IlliaFadnn** [comment]
The link below is deprecated, the article is now [here](https://docs.nativescript.org/angular/ui/dialogs)
