### ISSUE TITLE
disable auto string format

### ISSUE THREAD

**Issue by wendt88** [NativeScript/nativescript-angular#981]
If I have a `<Label text="+24.00"></Label>` my string gets cut from `"+24.00"` to `"24"`. is there a solution to output `+24.00`, As workaround I added a space (`"+ 24.00"`).

I created a stackoverflow question already some time ago:
https://stackoverflow.com/questions/45708661/nativescript-disable-standard-angular-2-filters-in-label-text

**Comment by Ablankzin** [comment]
This could be the same issue: #854

**Comment by NickIliev** [comment]
Closing as a duplicate to https://github.com/NativeScript/nativescript-angular/issues/854
