### ISSUE TITLE
Styling of SideDrawer's list items disappear when compiling with AOT

### ISSUE THREAD

**Issue by truewt** [NativeScript/nativescript-angular#984]
Hello,

I'm new to NativeScript and I already created a basic application which works pretty well. I'm using NativeScript with Angular (+ SASS with NativeScript Theme Light), and I created project with NativeScript Sidekick. So far I got through almost everything I had to implement, but there is something that I can't solve on my own.

The problem which I have is when I compile my app with AOT, the ListView items in SideDrawer are not styled. When I compile with JIT the SideDrawer items are always styled as expected. My directory structure for ListView item on SideDrawer is a bit deeper and I'm thinking that those files are not included into the end result. I'm trying to figure out which files are part of the executable (let's say apk for Android for example), so I could see where the CSS for items get lost. I configured project to use webpack and AOT as written [here](https://docs.nativescript.org/best-practices/bundling-with-webpack#angular-and-ahead-of-time-compilation).

Is there any possibility to find out which files are generated once webpack is started, to check why there is no styling for ListView items? What would be suggested way to find out why there is no styling othervise?

If I was unclear at any point and you have a question, please write it down and I will try to answer as soon as possible. I will be very grateful for any information you will provide. I would also be very happy if you could help me with other questions I have written [here](https://github.com/NativeScript/NativeScript/issues/4812).

Thank you very much in advance!

**Comment by cmargulhano** [comment]
have the same problem :(

**Comment by jevenson** [comment]
Found a solution, [check it out](https://github.com/NativeScript/nativescript-dev-webpack/issues/257#issuecomment-333249539)!

**Comment by truewt** [comment]
@jevenson Thank you very much, this also fixes the problem in my app.

I think the issue can be closed, but pleasing `nativescript-angular` developers to figure out why this problem appears and provide a real fix which won't need this workaround (or if I'm wrong at that point, at least provide the description why interpolation shouldn't be used inside class attribute).
