### ISSUE TITLE
Incorrect response when making GET requests on iOS

### ISSUE THREAD

**Issue by etabakov** [NativeScript/nativescript-angular#985]
**Steps to reproduce:** 
1. Create an Angular application.
2. Create a GET request to a RSS Feed (e.g. https://www.nasa.gov/rss/dyn/educationnews.rss)
3. The body of the response on iOS looks like:

> <3c3f786d 6c207665 7273696f 6e3d2231 2e302220 656e636f 64696e67 3d227574 662d3822 203f3e20 3c727373 20766572 73696f6e 3d22322e 30222078 6d6c3a62 6173653d 22687474 703a2f2f 7777772e 6e617361 2e676f76 2f222078 6d6c6e73 3a61746f 6d3d2268 7474703a 2f2f7777 ...

Everything works fine on Android. Also, the response on iOS is fine the response is text/html. Attached you can find a [sample project](https://github.com/NativeScript/nativescript-angular/files/1287144/ns-angular-http.zip) that reproduces the problem.

**Comment by NickIliev** [comment]
+1 Related to t.1129079 (included project ot reproduce the issue)
