### ISSUE TITLE
[iOS] More than one layout child inside a ContentView

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-angular#989]
When the layouts are using Angular structural directives we are throwing with 
```
JS ERROR Error: More than one layout child inside a ContentView
```

Reproducible with
```
"dependencies": {
 "@angular/animations": "~4.2.6",
    "@angular/common": "~4.2.6",
    "@angular/compiler": "~4.2.6",
    "@angular/core": "~4.2.6",
    "@angular/forms": "~4.2.6",
    "@angular/http": "~4.2.6",
    "@angular/platform-browser": "~4.2.6",
    "@angular/platform-browser-dynamic": "~4.2.6",
    "@angular/router": "~4.2.6",
    "nativescript-angular": "^4.2.0",
    "rxjs": "~5.3.0",
    "tns-core-modules": "^3.2.0",
}
 "devDependencies": {
    "@angular/compiler-cli": "~4.2.6",
    "@ngtools/webpack": "~1.5.3",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "codelyzer": "^3.0.1",
}
```

Reported via t. 1120485 (test application included)

**Comment by sis0k0** [comment]
fixed with fe672d26a6abf675d38b9375739fe2d919e95876
We plan to release it with 4.2.1 next week

**Comment by prestopasto** [comment]
I hate to pester, but any update on the 4.2.1 release?

**Comment by NickIliev** [comment]
@prestopasto the fix is currently included in the **next** release and will be part of the next official release of nativescript-angular.

**Comment by sis0k0** [comment]
available in 4.4

**Comment by jdnichollsc** [comment]
I can see this issue using nativescript-angular 4.4.0, maybe it's the livesync?

**Comment by Nogostradamus** [comment]
I see this with Nativescript 4.0.1 and angular 5.2 on iOS only
