### ISSUE TITLE
ControlValueAccessor implementation for all builtin components

### ISSUE THREAD

**Issue by hdeshev** [NativeScript/nativescript-angular#99]
* [ ] DatePicker
* [ ] TimePicker
* [ ] ListPicker
* [ ] SearchBar
* [ ] SegmentedBar
* [ ] Slider (related #84)

**Comment by anhoev** [comment]
Is there any plan for supporting of Sidedrawer in future?

**Comment by NathanWalker** [comment]
@anhoev this was discussed here: https://github.com/NativeScript/nativescript-angular/issues/91
It will come in time.

**Comment by hdeshev** [comment]
Shipped in nativescript-angular@0.0.36
