### ISSUE TITLE
On LiveWatch, html does not exist errors occur frequently

### ISSUE THREAD

**Issue by crutchcorn** [NativeScript/nativescript-angular#994]
While using {N} LiveWatch on an Android 7.1.1 (Moto Z Force Droid edition if that helps) from a Windows 10 Creator's update PC, I often get errors about an HTML file not existing. This is not the same file all the time and is most oftentimes the file that I have recently been editing (to update with LiveWatch). In order to fix this error, I have to stop and restart my build process entirely
```
Stopping tsc watch
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR Error: Uncaught (in promise): Error: File /data/data/pro.wireflare.Linkd/files/app/modules/dashboard/dashboard.component.html does not exist. Resolved from: /data/data/pro.wireflare.Linkd/files/app/modules/dashboard/dashboard.component.html.
```

**Comment by NickIliev** [comment]
@crutchcorn Does the file `app/modules/dashboard/dashboard.component.html` really exist in your application?
If yes, try to uninstall the application from your emulator, then wipe the emulator data (via AVD) and finally rebuild the application (with deleted platforms folder) and redeploy using `tns run android` (or iOS)

**Comment by crutchcorn** [comment]
I do indeed have the file in my application and I already know how to fix the problem, as I mentioned above. However, this is such a common occurance that I felt I should file a bug against, as it's caused many headaches in development. It really stinks to have to restart my entire build process for seemingly every change. It ruins most of the point of LiveWatch

**Comment by NickIliev** [comment]
@crutchcorn closing this issue as it seems not to be reproducible with the latest nativescript-angular.
