### ISSUE TITLE
Can't use SignalR with Angular NativeScript.

### ISSUE THREAD

**Issue by uopeydel** [NativeScript/nativescript-angular#998]
In my project i try to use signalr with nativescript starter project but when i import and build project it will be error before i tap any button
ts file =>> https://github.com/uopeydel/NativeScriptSignalR/blob/master/AssisChatApp/app/item/items.component.ts

error when build =>> https://github.com/uopeydel/NativeScriptSignalR/blob/master/Error.txt

when i use signalr in otherproject angular4 can use signalr have no error
signalr project  =>> https://github.com/uopeydel/signalr_core_test
 
or i need to post this issue to https://github.com/aspnet/SignalR ?

Thank for answer to much.
Sorry to bother.

**Comment by NickIliev** [comment]
@uopeydel there is a concept plugin (not officially published) that provides the functionality to use SignalR in NativeScript - see [here](https://github.com/NathanaelA/nativescript-signalr)

**Comment by uopeydel** [comment]
That plugin you give to me use signalr .netframework ,I ask to github signalr core 
https://github.com/aspnet/SignalR/issues/866#event-1251584967
The 2 frameworks are incompatible. 
Sorry about a queation ,I din't type scope for signalr core.

**Comment by NickIliev** [comment]
@uopeydel the SignalR library should be wrapped in a compatible NativeScript plugin - information on how to build plugins can be found [here](https://docs.nativescript.org/angular/plugins/building-plugins).

Closing the issue due to inactivity.
